### ISSUE TITLE
version 2.28.0 return errors

### ISSUE THREAD

**Issue by hendrixroa** [hashicorp/terraform-provider-aws#10091]
When I run the terraform plan command and the aws provider version property `version = 2.27.0` is not set, it returns that error because by default the version 2.28.0 has a bug

#Terraform Version
0.12.8

### Affected Resource(s)
* aws provider version: 2.28.0

### Panic Output

Error: missing expected [

### Actual Behavior
Error: missing expected [

### Steps to Reproduce
terraform init && terraform plan 

1. `terraform plan`
Error: missing expected [

**Comment by MarkKewley** [comment]
@bflad 

Seeing similar issues even with `2.28.1`, still `cloudfront` but instead:

`Error: missing expected {` 

this time it is a `{` instead of a `[`

I tried downgrading but it did not fix the issue.

Thanks!

**Comment by matthewduren** [comment]
@MarkKewley that'll be an error in your tf in that case most likely imo.

**Comment by MarkKewley** [comment]
@matthewduren Interesting considering there weren't any changes within my `cloudfront` module. I just reset the bad state to fix it. Might've been issues moving between 28.0 and 28.1.

**Comment by jtsaito** [comment]
@MarkKewley Could you tell me how you "reset the bad state"?

**Comment by MarkKewley** [comment]
@jsaito
You won't like it...but I removed my cloudfront instance and did a `terraform state rm` for each affected distribution. Really would not recommend it by any means but so far I haven't been running into any issues since.

I believe there are commands to repair your state as well, didn't look into it further since we are in a bit of a rush.

**Comment by jtsaito** [comment]
@MarkKewley I see. Thank you!
