### ISSUE TITLE
API Gateway replacement custom warning

### ISSUE THREAD

**Issue by Richard-Payne** [hashicorp/terraform-provider-aws#10431]
Is it possibly to specify a custom warning when resource replacement is planned?

The specific scenario is provoked the question is an api gateway which is called from other systems.  If a replacement occurs then the api id will change, as will the invocation urls.  It would be nice to be able to include details of the systems that would need updating if the plan were executed.  Of course, those details are specific to each use case and not known by Terraform so would have to specified as a custom warning string.

**Comment by bflad** [comment]
Hi @Richard-Payne 👋  Thank you for raising this. This is technically possible in Terraform Providers given some newer functionality we have in Terraform Plugin SDK version 2 and its support of resource-level warning diagnostic messages, however is not likely something we would implement on a per-resource level due to the potential amount of effort to implement this everywhere ("manually"). This seems like functionality that may be suited at a higher level, so it can be applied consistently across the broader ecosystem of Terraform resources. You may want to raise this type of proposal upstream in the [Terraform CLI repository](https://github.com/hashicorp/), similar to https://github.com/hashicorp/terraform/issues/27550. 👍
