### ISSUE TITLE
CodeDeploy: how to specify Lambda hooks for lifecycle events?

### ISSUE THREAD

**Issue by finferflu** [hashicorp/terraform-provider-aws#10440]
Hi all, 

I've been looking through the documentation, however, there seems to be no mention of [Lambda hooks that can be triggered by lifecycle events during a CodeDeploy deployment](https://docs.aws.amazon.com/en_pv/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-ecs). These seem to be vital to, e.g. [run automated tests before traffic is sent to a new deployment](https://docs.aws.amazon.com/en_pv/codedeploy/latest/userguide/tutorial-ecs-with-hooks-create-hooks.html). 

Am I missing something, or is it lacking in the Terraform AWS provider? Failing that, is there anything that this provider can do to facilitate the use of AppSpec files? 

Thanks!

**Comment by jpmontez** [comment]
Yeah, I noticed this too. Is this not supported by Terraform?

**Comment by harryurban** [comment]
Are there any news on the missing features?

While researching how to establish a proper CI/CD pipeline for aws lambdas I ended up choosing CodeDeploy, mostly because of the pre traffic hooks and the automated alias switiching. 
Now it looks like, that we would need to use SAM to get this feature, but this would mean, that all resources would be created with SAM and be written in CloudFormation.
For our team we agreed on terraform for IaaC, so using SAM / CF for this would mean, that we would have resources coming from two different sources, which we wanted to avoid.

**Comment by alexandergunnarson** [comment]
We've gone with using a `null_resource` to deploy the appspec separately (see [here](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v1.17.0/modules/deploy/main.tf) for a code example). Don't love that we have to use a workaround, but at least a workaround exists!

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still missing this functionality?

**Comment by MatthewEdwards** [comment]
I believe this is still missing functionality

**Comment by justinretzolk** [comment]
Hey @MatthewEdwards 👋 Thank you for taking the time to follow up with your findings here! Always great to see someone provider their solution in case someone else stumbles across this issue in the future 🎉.

Given your findings, I'll mark this issue as closed. If you feel we've done this in error, please open a new issue with any updated information you may have.
