### ISSUE TITLE
Error: Provider produced inconsistent final plan while creating APIGW VPC link to NLB

### ISSUE THREAD

**Issue by ellaqezi** [hashicorp/terraform-provider-aws#10524]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.10

### Affected Resource(s)

* aws_api_gateway_vpc_link
* aws_lb

### Terraform Configuration Files

```hcl
variable "environment" {}
variable "nlb_arn" {
  default = ""
}
variable "backend_bucket_name" {}
variable "project" {}
variable "aws_region" {}

locals {
  default_nlb_name = join("-", [var.environment, "this", "nlb"])
  nlb_arn             = var.nlb_arn == "" ? "" : var.nlb_arn
  nlb_name         = var.nlb_arn == "" ? local.default_nlb_name : ""
  nlb_count        = var.nlb_arn == "" ? 1 : 0
}

data "terraform_remote_state" "base_vpc" {
  backend = "s3"

  config = {
    bucket = var.backend_bucket_name
    key = "${var.project}/bootstrap/base-${var.aws_region}.tfstate"
    region = var.aws_region
  }
}

resource "aws_lb" "this" {
  count                            = local.nlb_count
  name                             = local.nlb_name
  internal                         = true
  load_balancer_type               = "network"
  enable_cross_zone_load_balancing = true
  subnets = data.terraform_remote_state.base_vpc.outputs.private_subnet_ids
}

data "aws_lb" "this" {
  depends_on = [aws_lb.this]
  arn        = local.nlb_arn
  name       = local.nlb_name
}

resource "aws_api_gateway_vpc_link" "this" {
  name        = local.default_nlb_name
  description = "API GW VPC Link to ${data.aws_lb.this.name}"

  target_arns = [
    data.aws_lb.this.arn,
  ]

  lifecycle {
    ignore_changes = [target_arns]
  }
}
```

### Debug Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_api_gateway_vpc_link.this to include new
values learned so far during apply, provider "aws" produced an invalid new
value for .target_arns: planned set element cty.StringVal("") does not
correlate with any element in actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
https://gist.github.com/ellaqezi/13e1f57baf811ebe2d20881973a2ea08

### Expected Behavior
Create a APIGW VPC link to the created NLB. The VPC link's lifecycle block prohibits unnecessarily recreating the link since the arn is read from the NLB's data block.

### Steps to Reproduce

1. `terraform apply -target=aws_api_gateway_vpc_link.this`

### References

* #0000

**Comment by bflad** [comment]
Hi folks 👋  In this case, it appears that the error message may be a little misleading due to the configuration being passed in.

```terraform
locals {
  default_nlb_name = join("-", [var.environment, "this", "nlb"])
  nlb_arn             = var.nlb_arn == "" ? "" : var.nlb_arn
  nlb_name         = var.nlb_arn == "" ? local.default_nlb_name : ""
  nlb_count        = var.nlb_arn == "" ? 1 : 0
}
```

In this locals block, the `nlb_arn` value is potentially `""`, which is then passed to the `arn` argument of the `aws_lb` data source. During the planning phase, Terraform assumes that the `data.aws_lb.this.arn` value is known to be `""` and uses it as the `target_arns` argument:

```terraform
data "aws_lb" "this" {
  depends_on = [aws_lb.this]
  arn        = local.nlb_arn
  name       = local.nlb_name
}

resource "aws_api_gateway_vpc_link" "this" {
  name        = local.default_nlb_name
  description = "API GW VPC Link to ${data.aws_lb.this.name}"

  target_arns = [
    data.aws_lb.this.arn,
  ]

  lifecycle {
    ignore_changes = [target_arns]
  }
}
```

However during the apply phase the lookup occurs and now there is a mismatch between the passed in value (`""`) and what the data source `arn` attribute contains after the lookup (`"arn:..."`). This confuses Terraform because it is expected for data sources and resources to always have the same attribute values during planning and apply.

The configuration fix in this situation is to only set the `arn` argument of the `aws_lb` data source when it is not an empty string. This can be done using `null`, which will prevent the attribute from thinking that it will be an empty string, e.g.

```terraform
data "aws_lb" "this" {
  depends_on = [aws_lb.this]
  arn        = local.nlb_arn != "" ? local.nlb_arn : null
  name       = local.nlb_name
}
```

To prevent this issue within the data source we would either need to update the `validateArn` schema validation function we use to not accept empty string (`""`) anymore or switch this attribute to new schema validation handling with effectively that change. The reason it accepted empty strings before was to cope for the Terraform 0.11 and earlier configuration language which did not support the concept of `null`. Changing this could cause a lot of issues for practitioners to upgrade old configurations so it is likely something we would not want to do this type of change until a major version update of the Terraform AWS Provider. That effort can be tracked in the proposal issue here: https://github.com/hashicorp/terraform-provider-aws/issues/13943

Given that this should be fixable via configuration updates and there is a longterm tracking issue for this type of code fix to return an error during planning, I'm going to close this.
