### ISSUE TITLE
Error: error getting Service Quotas Service Quota (vpc/L-2AEEBF1A): NoSuchResourceException

### ISSUE THREAD

**Issue by Geartrixy** [hashicorp/terraform-provider-aws#10929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.12
+ provider.aws v2.37.0
+ provider.template v2.1.2

### Affected Resource(s)

* resource "aws_servicequotas_service_quota"

### Terraform Configuration Files

```hcl
resource "aws_servicequotas_service_quota" "quota" {
  quota_code   = "L-2AEEBF1A"
  service_code = "vpc"
  value        = 40
}
```

### Expected Behavior

Create quota increase request

### Actual Behavior

```
Error: error getting Service Quotas Service Quota (vpc/L-2AEEBF1A): NoSuchResourceException: 
        status code: 400, request id: 1dc2ddf9-b456-458c-abda-d2af02677e0d

  on provider.tf line 10, in resource "aws_servicequotas_service_quota" "quota":
  10: resource "aws_servicequotas_service_quota" "quota" {
```

1. `terraform apply`

**Comment by jnerin** [comment]
Hate to do a me too, but as I'm running updated versions at least serves to probe it's still happening:

Terraform v0.12.16
+ provider.aws v2.38.0

An I think I know why, I think it's because this:

aws --region eu-west-1 --profile staging service-quotas list-service-quotas --service-code vpc | jq '.Quotas[] | "\(.QuotaName) \(.QuotaCode)"'
"Internet gateways per Region L-A4707A72"
"VPCs per Region L-F678F1CE"

Now, if I try to modify "VPCs per Region L-F678F1CE" it works:
aws_servicequotas_service_quota.vpcs_per_region: Creating...
aws_servicequotas_service_quota.vpcs_per_region: Creation complete after 1s [id=vpc/L-F678F1CE]

But if instead I want to modify "L-2AFB9258" Security groups per network interface, I get:

Error: error getting Service Quotas Service Quota (vpc/L-2AFB9258): NoSuchResourceException: 
	status code: 400, request id: 1b238ab8-b4f7-4ab0-af75-1bd1b1b9538c

  on aws_service_limits.tf line 17, in resource "aws_servicequotas_service_quota" "sg_per_eni":
  17: resource "aws_servicequotas_service_quota" "sg_per_eni" {

I think the service quotas service is not fully implemented on the AWS side, as I requested an increase of "L-2AFB9258" Security groups per network interface and I got it approved, can confirm the new limit works, but it's still pending on service quotas request history, and the value is still the default one there.

I commented on the support ticket that was created when I requested the increase of "L-2AFB9258" Security groups per network interface noting the discrepancy, they forwarded that to the service quotas team, still awaiting answer, but I think the issue is on AWS side. I suspect the moment "L-2AFB9258" Security groups per network interface appears as accepted on service quotas terraform will be able to update it (well, it creates a support request asking for the increase, but that's just how the service works).

**Comment by bootswithdefer** [comment]
I don't think this is an upstream issue.  Terraform is querying for service quotas when L-2AEEBF1A is a default service quota, they're separate API calls:
https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_GetServiceQuota.html
https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_GetAWSDefaultServiceQuota.html

CLI examples:
```
$ aws --region us-west-2 service-quotas get-service-quota --service-code vpc --quota-code L-2AEEBF1A

An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation: 
```

```
$ aws --region us-west-2 service-quotas get-aws-default-service-quota --service-code vpc --quota-code L-2AEEBF1A
{
    "Quota": {
        "QuotaName": "Rules per network ACL", 
        "Adjustable": true, 
        "QuotaArn": "arn:aws:servicequotas:us-west-2::vpc/L-2AEEBF1A", 
        "Value": 20.0, 
        "ServiceName": "Amazon Virtual Private Cloud (Amazon VPC)", 
        "GlobalQuota": false, 
        "ServiceCode": "vpc", 
        "QuotaCode": "L-2AEEBF1A", 
        "Unit": "None"
    }
}
```

**Comment by jnerin** [comment]
The answer I got from AWS support about this issue states that AWS API for service-quotas is incomplete, at least in the VPC area:

_"This is a function of how the service team (VPC) has onboarded to Service Quotas. It seems the default limits only appear."_

EC2 service-quotas API implementation is more detailed, not sure if 100% complete, but certainly has more than 2 (??!!) values available to be set.

Service quotas API by AWS was introduced +5 months ago, and still can't be trusted, I got a service quota approved and applied, that still showed as pending approval on service quotas dashboard for days until I pointed AWS Support to that. Another quota that the agent modified the requested value to a higher one and terraform wanted to create another request to downsize it (not allowed), and the quotas that just can't be handled due to incomplete implementation on AWS's side. It's sad, but not terraform's fault (well, maybe trying to decrease the limit is).

**Comment by acdha** [comment]
I ran into this bad API design as well — the RDS service has a “manual DB instance snapshot" quota (L-272F1212) which shows up and can be operated on normally and a “manual DB cluster snapshot” (L-9B510759) which requires use of the separate AWS default API. I'm not sure what the AWS timeframe for fixing the API would look like but the alternative of checking a second API on `NoSuchResourceException` seems like it could add a bit of overhead.

**Comment by wbwork** [comment]
Both `vpc/L-2AFB9258` and `vpc/L-0EA8095F`, which haven't been working in the past, ran now successfully. Seems that AWS fixed their API, I guess.

**Comment by ffreitas-te** [comment]
I'm hitting a similar error with `globalaccelerator` quota:

```
aws_servicequotas_service_quota.ga: Creating...

Error: error getting Service Quotas Service Quota (globalaccelerator/L-BE074EF3): NoSuchResourceException:

  on main.tf line 2, in resource "aws_servicequotas_service_quota" "ga":
   2: resource "aws_servicequotas_service_quota" "ga" {
```

**Comment by jonsimn** [comment]
I'm hitting a similar error with lambda quota:
 ```
Error: error getting Service Quotas Service Quota (lambda/L-B99A9384): NoSuchResourceException:

   with aws_servicequotas_service_quota.lambda_concurrent_connections,
   on main.tf line 20, in resource "aws_servicequotas_service_quota" "lambda_concurrent_connections":
   20: resource "aws_servicequotas_service_quota" "lambda_concurrent_connections" {
```

**Comment by nyt-larahelenaroth** [comment]
Getting similar here: 

```

Error: error getting Service Quotas Service Quota (s3/L-DC2B2D3D): NoSuchResourceException:
--
531 | &nbsp;
532 | on service-quotas.tf line 1, in resource "aws_servicequotas_service_quota" "s3-buckets-east":
533 | 1: resource "aws_servicequotas_service_quota" "s3-buckets-east" {


```

**Comment by aggallim** [comment]
Same for route53 zone associations.

Error: error getting Service Quotas Service Quota (route53/L-84B40094): NoSuchResourceException:

**Comment by richardj-bsquare** [comment]
And...
`Error: error getting Service Quotas Service Quota (iotcore/L-C0B2EF8B): NoSuchResourceException: `

**Comment by jon-simon** [comment]
What I've gleamed is that there are [Applied Quotas](https://docs.aws.amazon.com/sdk-for-go/api/service/servicequotas/#ServiceQuotas.GetServiceQuota) and [Default Quotas](https://docs.aws.amazon.com/sdk-for-go/api/service/servicequotas/#ServiceQuotas.GetAWSDefaultServiceQuota) and the API has separate methods for querying each.   The provider seems to only query applied quotas, and if you've never requested an increase on that particular quota, it will be null and return an error.  Once you've actually implemented an "Applied Quota" Terraform will return the quota value successfully.
