### ISSUE TITLE
Add AWS Lightsail Load Balancer Support

### ISSUE THREAD

**Issue by akonrath** [hashicorp/terraform-provider-aws#11049]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As described [here](https://aws.amazon.com/lightsail/features/load-balancing/), Lightsail supports the use of a load balancer. I have already begun initial work to get this implemented, and future work will be needed (e.g. attachment, certificates). This is being opened for visibility, updates, and tracking.

### New or Affected Resource(s)

Proposed resource name is:

* aws_lightsail_load_balancer

### Potential Terraform Configuration

```hcl
resource "aws_lightsail_load_balancer" "example_load_balancer_name" {
  load_balancer_name = "test"
  instance_port      = "5000"
  health_check_path  = "/health"
  tags = {
    "tag_1" = "test"
  }
}

```

### References
- [AWS Lightsail Load Balancer Reference](https://aws.amazon.com/lightsail/features/load-balancing/)
- [AWS Lightsail CreateLoadBalancer API](https://docs.aws.amazon.com/lightsai/2016-11-28/api-reference/API_CreateLoadBalancer.html)
- [AWS Lightsail AttachInstancesToLoadBalancer API](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_AttachInstancesToLoadBalancer.html)
- [AWS Lightsail DeleteLoadBalancer API](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_DeleteLoadBalancer.html)
- [AWS Lightsail GetLoadBalancer API](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_GetLoadBalancer.html)

* #0000

**Comment by brittandeyoung** [comment]
For Awareness I have begun work on creating a separate AWS lightsail provider in order to help with Speeding up contributions and to give it dedicated attention. 

The Github repo is located here: https://github.com/DeYoungTech/terraform-provider-awslightsail

The provider and documentation is published here: https://registry.terraform.io/providers/DeYoungTech/awslightsail/latest

With the most recent version, the provider has moved past resource parity for lightsail services and It includes this resource.

If you want to start using this resource now, feel free to check it out and provide feedback.
