### ISSUE TITLE
IAM Credentials with KMS asymmetric keys

### ISSUE THREAD

**Issue by jczerniak** [hashicorp/terraform-provider-aws#11053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Key Management Service (KMS) now enables you to create and use asymmetric customer master keys (CMKs) and data key pairs. So we can use it to encrypt and decrypt IAM access credentials instead of PGP keys.

### New or Affected Resource(s)

* [iam_access_key](https://www.terraform.io/docs/providers/aws/r/iam_access_key.html)

### Potential Terraform Configuration

```hcl
resource "aws_kms_key" "a" {
 description = "KMS key 1"
 deletion_window_in_days = 10
 key_usage = "ENCRYPT_DECRYPT"
 customer_master_key_spec = "RSA_4096"
}

resource "aws_iam_user" "user1" {
  name = "user1"
}

resource "aws_iam_access_key" "user1" {
  user = "${aws_iam_user.user1.name}"
  kms_key = "${aws_kms_key.a.public_key}"
}

```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/11/aws-key-management-service-supports-asymmetric-keys/
* https://aws.amazon.com/blogs/security/digital-signing-asymmetric-keys-aws-kms/

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/11042

**Comment by dragosrosculete** [comment]
This is still not implemented and we have to generate our own pgp key or rely on keybase .
Why can we not use AWS KMS instead for encrypt/descrypt on this resource
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key

**Comment by grossws** [comment]
I created PR with minimal KMS support (using symmetric CMK + optional encryption context). 

Not exactly what @jczerniak described but it could be useful to avoid plaintext secret access key in terraform state and allows subsequent decryption either using `aws kms decrypt ...` or relevant data source.

**Comment by bflad** [comment]
Since this was submitted, we have clarified our [Provider Design documentation](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#cross-service-functionality) to denote that cross-service functionality is discouraged within a resource and our [Data Conversion and Handling documentation](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/data-handling-and-conversion.md#hashed-values) to denote that hashed (or in this case, encrypted) attribute values will not be accepted. The existing PGP functionality is a legacy implementation that may be removed in the future during a major version release.

In these cases we would encourage practitioners to ensure secured state storage or omitting the usage of the `aws_iam_access_key` resource as appropriate for their security posture.

Given all this, I'm going to close this feature request out as we would not accept contributions implementing it as described.
