### ISSUE TITLE
Support for EC2 Image Builder

### ISSUE THREAD

**Issue by jaygorrell** [hashicorp/terraform-provider-aws#11084]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EC2 Image Builder was just announced. This issue is to track implementation (and votes) for the feature.

### References

* https://aws.amazon.com/about-aws/whats-new/2019/12/introducing-ec2-image-builder/

**Comment by ewbankkit** [comment]
[Blog post](https://aws.amazon.com/blogs/aws/automate-os-image-build-pipelines-with-ec2-image-builder/).
[User guide](https://docs.aws.amazon.com/imagebuilder/latest/userguide/what-is-image-builder.html).
[API reference](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/Welcome.html).

Requires [AWS SDK v1.25.44](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.44):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11083

**Comment by ewbankkit** [comment]
It looks like an initial set of resources would be
* `aws_imagebuilder_component`
* `aws_imagebuilder_distribution_configuration`
* `aws_imagebuilder_image`
* `aws_imagebuilder_image_pipeline`
* `aws_imagebuilder_image_recipe`
* `aws_imagebuilder_infrastructure_configuration`

**Comment by aosman-tibco** [comment]
Some nuance is required due to how components are created as there's a `/1` on the and of the component arns that is reserved for future use. The list_components call must be used in conjunction with list_component_build_versions in order to get the actual arn to be used with other api calls for image builder.

See https://github.com/boto/boto3/issues/2224 for some more details.

**Comment by Dogers** [comment]
I'm taking a stab at this - first time though so will be slow going! If anyone else fancies a go, don't let me stop you - happy to work together :)

**Comment by blckct** [comment]
@Dogers There are 6 resources + data sources here. You should probably start with one of them and say which one that is.

**Comment by Dogers** [comment]
I was/am planning to do them in this order: component, infraconfig, recipe, distrib, image, pipeline.

Component is done save for tests and the bug I believe I've found. I've pushed it up [here](https://github.com/Dogers/terraform-provider-aws/tree/image-builder), thoughts, comments, PRs and especially (having not come from a dev background!) tests welcome :)

**Comment by smiller171** [comment]
Is anyone still working on this?

**Comment by Dogers** [comment]
Slowly :(

**Comment by blckct** [comment]
@Dogers Do you need any help? It seems you created some code and now it's just sitting there. Maybe you create a PR individual resources and we can help you with the tests?

**Comment by Dogers** [comment]
Yeah, I'll take any help going! It's just slowed down now as sitting at this desk working all day isn't terribly conducive to sitting at the same desk and working on this in the evening :(

**Comment by iancward** [comment]
> It looks like an initial set of resources could be:
> 
> * `aws_imagebuilder_component`
> * `aws_imagebuilder_distribution_configuration`
> * `aws_imagebuilder_image`
> * `aws_imagebuilder_image_pipeline`
> * `aws_imagebuilder_image_recipe`
> * `aws_imagebuilder_infrastructure_configuration`

It would be good to get a data source for at least `aws_imagebuilder_image`; this would allow someone to use the Amazon-provided Images as the source for a pipeline/recipe.

It seems there are two APIs for this: `ListImages` (appears to allow you to filter by Source), and `ListImagePipelineImages` (appears to allow you to filter by pipeline ARN).

**Comment by iancward** [comment]
@Dogers do you want to open a PR with what you have so far?

**Comment by Dogers** [comment]
Is it worth it at this stage? Was planning to once I'd got at least all the pieces to _some_ level of functioning :)

**Comment by tylert** [comment]
For those waiting for Terraform AWS to natively-support EC2 Image Builder, it may be possible to use Terraform -> CloudFormation -> EC2 Image Builder as a "temporary workaround" (https://aws.amazon.com/about-aws/whats-new/2020/05/ec2-image-builder-now-includes-support-for-aws-cloudformation/).

**Comment by iancward** [comment]
@Dogers I think if you were to open a PR with what you have so far, others could come in and assist taking this across the finish line.

**Comment by smiller171** [comment]
> For those waiting for Terraform AWS to natively-support EC2 Image Builder, it may be possible to use Terraform -> CloudFormation -> EC2 Image Builder as a "temporary workaround" (https://aws.amazon.com/about-aws/whats-new/2020/05/ec2-image-builder-now-includes-support-for-aws-cloudformation/).

I've actually created some modules to do just that.

https://registry.terraform.io/modules/rhythmictech/imagebuilder-component-ansible/aws/0.3.0
https://registry.terraform.io/modules/rhythmictech/imagebuilder-recipe/aws/0.2.0
https://registry.terraform.io/modules/rhythmictech/imagebuilder-pipeline/aws/0.5.1

**Comment by wrschneider** [comment]
Is this still moving forward?

**Comment by Dogers** [comment]
Slowly yep - the distribution_configuration bit gets crazy deep which I'm still trying to work my way through. Have a look at the PR and feel free to grab stuff off the list :)

**Comment by blckct** [comment]
@Dogers You seem to have a lot of work in progress and while you did a great job all the resources still need a bit of work. How about we divide the work and focus on one thing each? I finish the work on `aws_imagebuilder_infrastracture_configuration` for example. It would be better if we get at least some of the resources done rather than wait for all of them (and they need one PR per resource).

**Comment by Dogers** [comment]
No issue at all - I'm not precious in any way about this, just want it done! If you want to take chunks of what I've done and fix it up, go for it :)

One PR per resource seems excessive, but I can see the logic in it..

**Comment by blckct** [comment]
@wrschneider I see you've asked how to get started elsewhere but I'm going to answer here for more visibility. I've recently did a PR against it based on the work by @Dogers so I think it will be relevant if I give a brief overview:
1) Get familiar with https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md
2) The work done by @Dogers is 90% done so you may start from there instead of from scratch, I used cherry-pick to get the commits I need and so they would show in the history properly with correct author and me as commiter
3) Set up test environment for terraform, there's probably a better way to do it but I just run terraform init and then replace `terraform/plugins/linux_amd64/terraform-provider-xxx` with a symlink to `~/go/bin/terraform-provider-aws`
4) Test every configuration of parameters to the resource to check if they work correctly, set correctly, change correctly, don't change or disappear when something else is changed etc.
5) Write docs
6) Write tests, you run tests like this:
```
export AWS_REGION=eu-west-1 
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx
make testacc TEST=./aws TESTARGS='-run=TestAccAWSImageBuilderInfrastructureConfiguration_tags'
```

That should get you started, lemme know if you have specific questions.

**Comment by wrschneider** [comment]
@blckct  thanks the problem I ran into with my compiled copy of the provider is this error:

`Failed to instantiate provider "aws" to obtain schema: Unrecognized remote plugin message: adding cert CN=localhost,O=HashiCorp`

not sure what I'm missing?

**Comment by blckct** [comment]
@wrschneider sorry, that's out of my depth, you'd have to ask one of the maintainers. Are you on Linux or Mac?

**Comment by wrschneider** [comment]
> @wrschneider sorry, that's out of my depth, you'd have to ask one of the maintainers. Are you on Linux or Mac?

Mac, and I suspect this is a general issue with TF providers and not specific to the AWS one. :-(

**Comment by maryelizbeth** [comment]
Hey Y'all! Dropping in to let everyone know we've added this to the [Aug-Oct Roadmap](https://github.com/terraform-providers/terraform-provider-aws/blob/master/ROADMAP.md). We're not yet working on the this feature. However once we pick it up, one of the maintainers will reach out to discuss!

**Comment by bflad** [comment]
Hi folks 👋 For those following here, I provided an initial update in the current work in progress open pull request: https://github.com/terraform-providers/terraform-provider-aws/pull/13485#pullrequestreview-519271203 -- there's a lot of good implementation work in, however there is still a ways to go before pieces of this functionality will be released. The maintainers are cognizant that this item was on the [Aug-Oct Roadmap](https://github.com/terraform-providers/terraform-provider-aws/blob/3cdaeabd25973ac18321c4febcfe57a59741a795/ROADMAP.md), but in fairness to the contributors involved so far and due to a late start on my part with some other competing priorities (my apologies), we will extend a short grace period into the beginning of next month to work through review cycles, if they are interested. I would say to tentatively plan on having most, if not all, of this available by November 19th.

**Comment by iancward** [comment]
Hey @bflad thanks for the amazing work here! Any chance that an Image Pipeline resource will be available with the 3.16.0 release that you've quoted on some of the resolved issues? The Image Pipeline is the last mile of EC2 Image Builder and would be necessary to actually take advantage of these new resources.

**Comment by bflad** [comment]
> Hey @bflad thanks for the amazing work here! Any chance that an Image Pipeline resource will be available with the 3.16.0 release that you've quoted on some of the resolved issues? The Image Pipeline is the last mile of EC2 Image Builder and would be necessary to actually take advantage of these new resources.

We are planning on cutting 3.16.0 today for launch day support of Network Firewall. I'm doubtful if I submitted the finishing touches for the `aws_imagebuilder_image_pipeline` resource today that it would also be reviewed today in time since `aws_imagebuilder_image_recipe` resource review is also pending. That said, the first batch of resources releasing is still useful to start managing some of the functionality. 😉 

Releasing with version 3.16.0 of the Terraform AWS Provider (likely today):

* New Data Source: `aws_imagebuilder_component`
* New Data Source: `aws_imagebuilder_distribution_configuration`
* New Data Source: `aws_imagebuilder_infrastructure_configuration`
* New Resource: `aws_imagebuilder_component`
* New Resource: `aws_imagebuilder_distribution_configuration`
* New Resource: `aws_imagebuilder_infrastructure_configuration`

Releasing next week:

* New Resource: `aws_imagebuilder_image_recipe`
* New Resource: `aws_imagebuilder_image_pipeline`

While I've got folks ears, thank you to @Dogers, @blckct, @wrschneider for their efforts in helping get this off the ground. 😄

**Comment by wrschneider** [comment]
> While I've got folks ears, thank you to @Dogers, @blckct, @wrschneider for their efforts in helping get this off the ground. 😄

Sorry I've gone silent - let me know if there's anything with testing or documentation you need help with.

**Comment by bflad** [comment]
Support for new `aws_imagebuilder_image_recipe` and `aws_imagebuilder_image_pipeline` resources/data sources has been merged and will release later today with version 3.18.0 of the Terraform AWS Provider.

Given that these types of "support service" issues do not have a great definition of done as time progresses, we are closing this one and have created followup issues:

* [New Resource: `aws_imagebuilder_image`](https://github.com/hashicorp/terraform-provider-aws/issues/16375)
* [New Data Source: `aws_imagebuilder_image`](https://github.com/hashicorp/terraform-provider-aws/issues/16377)
* [New Resource: `aws_imagebuilder_image_pipeline_execution`](https://github.com/hashicorp/terraform-provider-aws/issues/16376)

Please feel free to 👍  react to those if interested and subscribe to them for updates. If you have other feature requests or bug reports with this service, please create new issues. Thank you!
