### ISSUE TITLE
Accelerated Site-to-Site VPN support

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#11135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> We are excited to announce the availability of Accelerated Site-to-Site VPN which uses AWS Global Accelerator to improve the performance of VPN connections by intelligently routing traffic through the AWS Global Network and AWS edge locations.

### New or Affected Resource(s)

* [`aws_vpn_connection`](https://www.terraform.io/docs/providers/aws/r/vpn_connection.html)

### Potential Terraform Configuration

```hcl
resource "aws_vpn_connection" "example" {
  customer_gateway_id = "${aws_customer_gateway.example.id}"
  transit_gateway_id  = "${aws_ec2_transit_gateway.example.id}"
  type                = "${aws_customer_gateway.example.type}"

  enable_acceleration = true
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/announcing-accelerated-site-to-site-vpn-for-improved-vpn-performance/).
[User guide](https://docs.aws.amazon.com/vpn/latest/s2svpn/accelerated-vpn.html).

Requires [AWS SDK v1.25.46](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.46):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11116

**Comment by zenvdeluca** [comment]
This optional flag available for transit gateway vpn attachments only is very important, looking forward for terraform support

**Comment by LozanoMatheus** [comment]
Is there any update on this? Has a few other options that are not currently supported and it's quite important. In the AWS CLI documentation has all of them.

* AWS CLI documentation
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-vpn-connection.html

Note:
Unfortunately, the Go SDK documentation and the EC2 API documentation are out-dated. Usually, I use the Boto3 documentation or the AWS CLI as a guide (I think the Python one is updated because AWS CLI is based on it).

Go doc: https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.CreateVpnConnection
EC2 API doc: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpnConnection.html
Boto doc: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_vpn_connection

Thanks :D

**Comment by MRinalducci** [comment]
@LozanoMatheus this PR #14740 covers all of them.

**Comment by bill-rich** [comment]
Added in #14740
