### ISSUE TITLE
aws_api_gateway_documentation_version errors out during update

### ISSUE THREAD

**Issue by evanherc** [hashicorp/terraform-provider-aws#11550]
aws_api_gateway_documentation_version allows you to publish your API documentation and needs to specify a version. This version is then used in aws_api_gateway_stage to link the two together.

However if after your initial deploy a subsequent run wants to actually update the documentation it will first trigger a destroy of the previous aws_api_gateway_documentation_version (which btw you can't even do in the AWS console) which errors out since the stage is still associated with it. 

Error: BadRequestException: Cannot delete documentation version because there are API Stages associated with it.
        status code: 400, request id: 6d08524d-96c8-4340-9298-27adc6132b80

AFAIK you can only delete documentation versions after the stage has been destroyed. This is far from ideal from AWS as you definitely don't want to the delete the stage to just update some documentation so I think the only proper solution is to leave the documentation versions alive and delete them when the stage gets deleted.

**Comment by evanherc** [comment]
After you get in this situation you are unable to get out of it with terraform. It will keep try and destroy the documentation and even if you taint the stage you will end up with a problem.

this CLI call will allow you to remove the link from the stage to the documentation and is basically what should happen in the destroy in terraform first.
aws apigateway update-stage --rest-api-id 0wko2jc120 --stage-name live --patch-operations op=replace,path=/documentationVersion,value=""

**Comment by justinretzolk** [comment]
Hey @evanherc 👋 Thank you very much for taking the time to file this issue. Given that there's been a number of AWS provider releases since you initially filed this, can you confirm whether you're still experiencing this behavior?

**Comment by kevindixon** [comment]
@justinretzolk - certainly seems to be the case for me with `registry.terraform.io/hashicorp/aws` @  `v3.75.2`

**Comment by C4Pi-Q** [comment]
Currently using aws provider version 4.26.0.

This seems to be a fundamental flaw in the way Terraform (or perhaps the provider), manages these resources. Terraform is trying to re-create the version resource its already created, rather than deploy a new version to replace it and leave the old one behind. Of course this works for most resources, but I don't think it's ideal for these. It's true, you can use the command to remove the current documentation version from the stage, thus allowing Terraform to recreate the version resource. But then you're not leaving the old version behind, you're replacing it with a new one entirely, and that seems like maybe it defeats the purpose a bit. 

I think the ideal would be that rather than updating the documentation version resource on change, Terraform instead orphans the old version and creates a new one. That will avoid the conflict of trying to delete a version while it's still tied to a stage, and it will actually preserve the version history, which seems ideal. Though, admittedly, I don't really care much about the history (it will be essentially in git anyway), I really just want the version management to work.

In the meantime, I have tried to use a null resource with local-exec to run the command @evanherc mentioned, to strip the version from the stage during deployment. Unfortunately I cannot get the null resource to run before the version resource on updates. On updates, despite having the version resource `depends_on` the null resource, it's still trying to recreate the version resource before the null resource can remove he version from the stage, so it continues to fail.

**Comment by C4Pi-Q** [comment]
-------------- Potential workarounds

1. You can use the above command to get things sort-of working. And if you have a pipeline running your terraform, it's not even a hassle to have it do that first. 
2. You could manually orphan the version resource so that Terraform creates a new one and leaves the old one around.
3. You could change your .tfvars to .json format, store the current API version there, and write a small script to read the version from your tfvars and publish it using the AWS CLI. 

Unfortunately, all of these boil down to running some other command before you run Terraform. 

--------------- The least-bad workaround

You can continually add version resources to your Terraform, so that the old ones do not need to be recreated. This preserves your version history and allows Terraform to run without any extra commands needing to be run first. This is a minor inconvenience but hey, you were going to have to tweak the version in Terraform anyway, now you just have to tweak a little more.

This works great for adding a new documentation version to an environment. If, however, you're deploying to an environment that missed the past few versions, or you're creating a totally new environment, it's going to create several new documentation versions that all have the exact same content. That's less than ideal, effectively makes the versions history in AWS still useless, but not the end of the world. 

This solution looks something like: 

```
resource "aws_api_gateway_stage" "api_gw_stage" {
  deployment_id         = aws_api_gateway_deployment.env.id
  rest_api_id           = aws_api_gateway_rest_api.main.id
  stage_name            = var.env
  documentation_version = aws_api_gateway_documentation_version.publish_0-94.version

  depends_on = [aws_api_gateway_documentation_version.publish_0-94]
}

resource "aws_api_gateway_documentation_version" "publish_0-93" {
  version     = "0.93"
  rest_api_id = aws_api_gateway_rest_api.main.id
  description = "New version of our API GW documentation tester tester"
  depends_on  = [aws_api_gateway_documentation_part.businessunits_endpoint]
}

resource "aws_api_gateway_documentation_version" "publish_0-94" {
  version     = "0.94"
  rest_api_id = aws_api_gateway_rest_api.main.id
  description = "New version of our API GW documentation tester tester"
  depends_on  = [aws_api_gateway_documentation_part.businessunits_endpoint]
}
```

Then, when you want to add a new version, you simply leave the existing version resources alone, create a new one, and tweak the stage resource to point at it, ie: 

```
resource "aws_api_gateway_stage" "api_gw_stage" {
  deployment_id         = aws_api_gateway_deployment.env.id
  rest_api_id           = aws_api_gateway_rest_api.main.id
  stage_name            = var.env
  documentation_version = aws_api_gateway_documentation_version.publish_0-95.version

  depends_on = [aws_api_gateway_documentation_version.publish_0-95]
}

resource "aws_api_gateway_documentation_version" "publish_0-93" {
  version     = "0.93"
  rest_api_id = aws_api_gateway_rest_api.main.id
  description = "New version of our API GW documentation tester tester"
  depends_on  = [aws_api_gateway_documentation_part.businessunits_endpoint]
}

resource "aws_api_gateway_documentation_version" "publish_0-94" {
  version     = "0.94"
  rest_api_id = aws_api_gateway_rest_api.main.id
  description = "New version of our API GW documentation tester tester"
  depends_on  = [aws_api_gateway_documentation_part.businessunits_endpoint]
}

resource "aws_api_gateway_documentation_version" "publish_0-95" {
  version     = "0.95"
  rest_api_id = aws_api_gateway_rest_api.main.id
  description = "New version of our API GW documentation tester tester"
  depends_on  = [aws_api_gateway_documentation_part.businessunits_endpoint]
}
```
