### ISSUE TITLE
Unable to reference security_group_id from peered VPC with EKS node group remote access sg

### ISSUE THREAD

**Issue by dusansusic** [hashicorp/terraform-provider-aws#11596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.19
+ provider.archive v1.3.0
+ provider.aws v2.44.0
+ provider.external v1.2.0
+ provider.helm v0.10.4
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1

### Affected Resource(s)

* aws_eks_node_group

### Terraform Configuration Files

```hcl

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.21.0"

  name = local.env_name
  cidr = "${local.vpc_cidr_base}.0.0/16"

  azs                 = data.aws_availability_zones.available.names
  private_subnets     = ["${local.vpc_cidr_base}.1.0/24", "${local.vpc_cidr_base}.2.0/24", "${local.vpc_cidr_base}.3.0/24"]
  public_subnets      = ["${local.vpc_cidr_base}.101.0/24", "${local.vpc_cidr_base}.102.0/24", "${local.vpc_cidr_base}.103.0/24"]

  enable_nat_gateway                     = true
  single_nat_gateway                     = true
  one_nat_gateway_per_az                 = false
  enable_vpn_gateway                     = false
  enable_dns_hostnames                   = true
  enable_dns_support                     = true
  enable_public_redshift                 = false
  create_database_subnet_group           = true
  create_database_subnet_route_table     = false
  create_database_internet_gateway_route = false

  tags = {
    Terraform                                         = "true"
    Environment                                       = local.env_name
    "kubernetes.io/cluster/${local.eks_cluster_name}" = "shared"
  }

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.eks_cluster_name}" = "shared"
    "kubernetes.io/role/elb"                          = "1"
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.eks_cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"                 = "1"
  }
}


module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "8.0.0"

  cluster_name    = local.eks_cluster_name
  cluster_version = "1.14"
  subnets         = module.vpc.private_subnets
  vpc_id          = module.vpc.vpc_id

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

  map_users = [
    {
      userarn  = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:user/dusan.susic"
      username = "dusan.susic"
      groups   = ["system:masters"]
    }
  ]

  node_groups_defaults = {
    key_name                  = "ssh"
    source_security_group_ids = [data.terraform_remote_state.blablabla.outputs.some_security_group_id] <-  this is where I get an error, can't reference group 
    subnets                   = [module.vpc.private_subnets[0], module.vpc.private_subnets[1], module.vpc.private_subnets[2]]
  }

  node_groups = {
    nodes = {
      desired_capacity = 2
      max_capacity     = 3
      min_capacity     = 2
      instance_type    = "t3.medium"

      additional_tags = {
        Name = "eks-k8s-${local.env_name}-node",
        "k8s.io/cluster-autoscaler/${local.env_name}" = "owned",
        "k8s.io/cluster-autoscaler/enabled" = "true"
      }
      k8s_labels = {
        type = "app-node"
      }
    },
    workers = {
      desired_capacity = 1
      max_capacity     = 1
      min_capacity     = 1
      instance_type    = "t3.small"
    }
  }
}
```
### Expected Behavior

To be able to reference security_group_id from peered VPC.

### Actual Behavior

can't apply config:
```
Error: error creating EKS Node Group (eks-workers-accepted-serval): InvalidParameterException: Security group(s) [sg-xxxxxxxxxxx] are not in the same VPC as the subnets. Please specify a security group that is associated with the VPC: vpc-xxxxxxxxxx.
```

### Steps to Reproduce

1. `terraform plan -out "plan"`
2. terraform apply "plan"

Result:
```
Error: error creating EKS Node Group (eks-workers-accepted-serval): InvalidParameterException: Security group(s) [sg-xxxxxxxxxxx] are not in the same VPC as the subnets. Please specify a security group that is associated with the VPC: vpc-xxxxxxxxxx.
```
### References

we should be able to reference this. It's possible over the AWS Console. 

https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html

**Comment by dusansusic** [comment]
Any update on this?

**Comment by vinothav** [comment]
I tried to reference the security group id from a peered vpc using the formating "account-id/sg-id" but it still doesnt work. It says one or more sg-ids in remote access is not valid !! 

Is there a limitation in referencing peered vpc's sg-id with eks_node_groups?

**Comment by bflad** [comment]
Hi folks 👋 

If there is a restriction on which EC2 Security Groups can be passed into the EKS API, it is currently not something that is being hindered by the Terraform AWS Provider `aws_eks_node_group` resource. In this case, we are not adding any validation in the schema ([reference](https://github.com/hashicorp/terraform-provider-aws/blob/29f406730f42f8874912e0c1b44cb60ae87cb633/aws/resource_aws_eks_node_group.go#L140-L145)) or modifying the Terraform configuration value as it is being passed through to the EKS API ([reference](https://github.com/hashicorp/terraform-provider-aws/blob/29f406730f42f8874912e0c1b44cb60ae87cb633/aws/resource_aws_eks_node_group.go#L255-L257) / [reference](https://github.com/hashicorp/terraform-provider-aws/blob/29f406730f42f8874912e0c1b44cb60ae87cb633/aws/resource_aws_eks_node_group.go#L558-L576)).

The [EKS API Reference for the `RemoteAccessConfig` type](https://docs.aws.amazon.com/eks/latest/APIReference/API_RemoteAccessConfig.html#AmazonEKS-Type-RemoteAccessConfig-sourceSecurityGroups) does not list any specific valid or invalid values:

> The security groups that are allowed SSH access (port 22) to the worker nodes. If you specify an Amazon EC2 SSH key but do not specify a source security group when you create a managed node group, then port 22 on the worker nodes is opened to the internet (0.0.0.0/0). For more information, see [Security Groups for Your VPC](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html) in the Amazon Virtual Private Cloud User Guide.

Since this does not appear to be an issue specific to the Terraform AWS Provider codebase and the maintainers cannot investigate specific usage questions, I'm going to close this. If you have further questions or requests on the abilities of the EKS API or its documentation, please reach out to the service team via:

* Clicking the Feedback link in the upper right hand corner of the [API documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_RemoteAccessConfig.html#AmazonEKS-Type-RemoteAccessConfig-sourceSecurityGroups)
* Opening an issue in the [aws/containers-roadmap repository](https://github.com/aws/containers-roadmap/issues)
* Opening an AWS Support case
* Reaching out to your AWS technical account manager

You can also feel free to post this in the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help with potential usage questions.
