### ISSUE TITLE
make msk cluster provisioning timeout configurable

### ISSUE THREAD

**Issue by aarti** [hashicorp/terraform-provider-aws#11736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While provisioning MSK cluster it took longer than 60 minutes and errored with `error waiting for MSK cluster creation`

https://github.com/terraform-providers/terraform-provider-aws/blob/4a4d5eff26d4607f458913e73d574037c5a08cdb/aws/resource_aws_msk_cluster.go#L682

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by jjwwiodyne** [comment]
Any update on this? We're running into the same issue. And waiting until it does create before re-running Terraform isn't an option because it destroys the cluster first.

**Comment by mgusiew-guide** [comment]
In our case it usually takes approximately 30 minutes to create cluster, so the create timeout of 2 hours is good enough fro now. However Kafka version rolling upgrade takes more than 2 hours so the Terraform job fails because of hardcoded timeout. To workaround it we need to resort to local-exec with aws-cli commands to upgrade the cluster and that is something we would like to avoid. 

Therefore it would be great to be able to tune update timeout or at least extend the hardcoded value to something bigger than 2 hours so that Kafka version upgrade completes successfully.
