### ISSUE TITLE
Inconsistent hashes for large step_scaling_policy_configuration values

### ISSUE THREAD

**Issue by jamesmharvey** [hashicorp/terraform-provider-aws#12016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11

### Affected Resource(s)

* aws_appautoscaling_policy

### Terraform Configuration Files

```hcl
resource "aws_appautoscaling_policy" "foo-scale-policy" {
  name = "foo-scale-policy"

  resource_id = "foo"

  policy_type = "StepScaling"

  scalable_dimension = "ecs:service:DesiredCount"

  service_namespace = "ecs"

  step_scaling_policy_configuration {
    adjustment_type         = "ChangeInCapacity"
    cooldown                = 600
    metric_aggregation_type = "Average"

    step_adjustment {
      scaling_adjustment          = -1
      metric_interval_upper_bound = -1.0000001e+07
    }

    step_adjustment {
      scaling_adjustment          = 0
      metric_interval_lower_bound = -1.0000001e+07
      metric_interval_upper_bound = 1.0000001e+07
    }

    step_adjustment {
      scaling_adjustment          = 1
      metric_interval_lower_bound = 1.0000001e+07
    }
  }
}
```

(I originally tried this with 10 million, and added 1 just in case the issue was a weird rounding error. I've also tried both regular and scientific-notation representations in my .tf files.)

### Expected Behavior

After the first successful apply, subsequent `terraform plan` operations should produce an empty plan.

### Actual Behavior

I get a terraform plan like
```
~ aws_appautoscaling_policy.foo-scale-policy
    step_scaling_policy_configuration.0.step_adjustment.1727414556.metric_interval_lower_bound:   "" => "10000001"
    step_scaling_policy_configuration.0.step_adjustment.1727414556.scaling_adjustment:            "" => "1"
    step_scaling_policy_configuration.0.step_adjustment.1862275301.metric_interval_lower_bound:   "" => "-10000001"
    step_scaling_policy_configuration.0.step_adjustment.1862275301.metric_interval_upper_bound:   "" => "10000001"
    step_scaling_policy_configuration.0.step_adjustment.1862275301.scaling_adjustment:            "" => "0"
    step_scaling_policy_configuration.0.step_adjustment.27641362.metric_interval_upper_bound:     "" => "-10000001"
    step_scaling_policy_configuration.0.step_adjustment.27641362.scaling_adjustment:              "" => "-1"
    step_scaling_policy_configuration.0.step_adjustment.3421756365.metric_interval_upper_bound:   "-1.0000001e+07" => ""
    step_scaling_policy_configuration.0.step_adjustment.3421756365.scaling_adjustment:            "-1" => "0"
    step_scaling_policy_configuration.0.step_adjustment.572302683.metric_interval_lower_bound:    "1.0000001e+07" => ""
    step_scaling_policy_configuration.0.step_adjustment.572302683.scaling_adjustment:             "1" => "0"
    step_scaling_policy_configuration.0.step_adjustment.792828460.metric_interval_lower_bound:    "-1.0000001e+07" => ""
    step_scaling_policy_configuration.0.step_adjustment.792828460.metric_interval_upper_bound:    "1.0000001e+07" => ""
```

### Steps to Reproduce

1. Make an `aws_appautoscaling_policy` with a `step_scaling_policy_configuration` block with `metric_interval_upper_bound` (or lower bound) large enough that `fmt.Printf("%g", x)` uses scientific notation to represent the number (i.e. at least 1 million)
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

**Comment by jamesmharvey** [comment]
Notes on the above bug report:

• While it appears that part of the problem is that we're changing from "1.0000001e+07" to "10000001", it's worth noting that the .tf file uses the same scientific notation as the "from" side of the tf plan.
• I'm relatively new to this codebase, but initial investigation makes it look like we're hashing the input and output sides of these resources differently.

**Comment by bflad** [comment]
After a little more digging, this may also be caused by some implementation details of the Terraform resource itself. The schema has [the type for these attributes as `TypeString`](https://github.com/terraform-providers/terraform-provider-aws/blob/8bff27262128a7b14fae870b0687645115b8b0df/aws/resource_aws_appautoscaling_policy.go#L87-L94) and there's a little bit more information about this choice [later in the code](https://github.com/terraform-providers/terraform-provider-aws/blob/8bff27262128a7b14fae870b0687645115b8b0df/aws/resource_aws_appautoscaling_policy.go#L474-L479), even though the [API uses double/float](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_StepAdjustment.html). There's a chance that if this was `TypeFloat`/`TypeInt` in the schema, then this would translate scientific notation properly, however we cannot just change the type of the attributes like that without potentially breaking certain configurations.

One potential workaround here without changing the underlying types would be setting up the `step_adjustment` configuration block attribute `Set` so the hash values compared equal, then do difference suppression in each `metric_interval_*` attribute.
