### ISSUE TITLE
plan should check AMI permissions

### ISSUE THREAD

**Issue by vsecarin-ZZ** [hashicorp/terraform-provider-aws#12275]
This was a private AMI owned by a different AWS account; terraform plan succeeded and then terraform apply did not find the AMI; adding my AWS account number to the image permissions made it work; terraform plan should check this and fail appropriately.

**Comment by justinretzolk** [comment]
Hey @vsecarin-ZZ 👋 Thank you for taking the time to file this issue. So that we have all of the necessary information in order to reproduce this, can you update the issue description with the information found in the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
