### ISSUE TITLE
CloudWatch composite alarms

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#12272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon CloudWatch now allows you to combine multiple alarms.

### New or Affected Resource(s)

* `aws_cloudwatch_composite_alarm`

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_composite_alarm" "alarm" {
  alarm_name = "example"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-cloudwatch-now-allows-you-to-combine-multiple-alarms/).
[User guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Create_Composite_Alarm.html).

**Comment by roberth-k** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/15023

**Comment by jvisker** [comment]
There is a PR out for this. Any chance of getting that merged?

**Comment by breathingdust** [comment]
Hi all! :wave: Just wanted to direct you to our public [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/master/ROADMAP.md) for this quarter (Nov-Jan) in which this item has been mentioned.

Due to the significant community interest in support for this feature, we will be looking at merging existing contributions soon. 

We appreciate all the contributions and feedback thus far.

Look out for support in the provider soon!
