### ISSUE TITLE
AWS RDS Cluster Parameter Group changes are repeated every time

### ISSUE THREAD

**Issue by valll94** [hashicorp/terraform-provider-aws#12742]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform Version: 0.12.21
AWS Provider Version: 2.50.0

### Affected Resource(s)

aws_rds_cluster_parameter_group

### Terraform Configuration Files

```hcl
resource "aws_rds_cluster_parameter_group" "default" {
  name        = "test-param"
  description = "test-param"
  family      = "aurora-mysql5.7"
  dynamic "parameter" {
    for_each = var.parameter
    content {
      apply_method = lookup(parameter.value, "apply_method", "pending-reboot")
      name         = parameter.value["name"]
      value        = parameter.value["value"]
    }
  }
}

variable "parameter" {
  description = "List containing map of parameters to apply"
  type        = list(map(any))
  default     = [  
     {
      name = "binlog_cache_size"
      value = 32768
    }
    ]
}
```

### Expected Behavior

After apply no changes are expected.

### Actual Behavior

After apply the values wants to be changed every time. The values in the cluster parameter group in AWS are Integers but the provider applies them as String. This is causing the terraform to see a change every time. The values in parameter group can be: Integer, String, Bool. The same issue is appearing with Bool values. No issues with Strings. 

```hcl
   # aws_rds_cluster_parameter_group.default will be updated in-place
   ~ resource "aws_rds_cluster_parameter_group" "default" {
         arn         = "arn:aws:rds:eu-central-1:$ID:cluster-pg:$name"
         description = "test-param"
         family      = "aurora-mysql5.7"
         id          = "test-param"
         name        = "test-param"
         tags        = {}
       + parameter {
           + apply_method = "pending-reboot"
           + name         = "binlog_cache_size"
           + value        = "32768"
         }
     }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by willthames** [comment]
Also affects `aws_db_parameter_group` for the same reason (we're seeing it with `rds.pg_stat_ramdisk_size`)

**Comment by carlosjgp** [comment]
I'm seeing this with AWS provider `3.60.0`

It only affects parameters set with `dynamic` block parameters specified directly work just fine

**Comment by justinretzolk** [comment]
Hi everyone 👋 I took a bit of a deeper look at this, and it's looking like this may be a limitation of the underlying SDK. 

The `aws_rds_cluster_parameter_group` resource uses the [`resourceAwsRDSClusterParameterGroupUpdate` function](https://github.com/hashicorp/terraform-provider-aws/blob/651c0e24747cf7eccfb30b99a8c9a915a3396a3d/aws/resource_aws_rds_cluster_parameter_group.go#L126) in order to set the parameters (the full code for the function can be found [here](https://github.com/hashicorp/terraform-provider-aws/blob/651c0e24747cf7eccfb30b99a8c9a915a3396a3d/aws/resource_aws_rds_cluster_parameter_group.go#L201-L309). 

This function in turn uses the AWS Go SDK function [`ModifyDBClusterParameterGroup` function](https://github.com/hashicorp/terraform-provider-aws/blob/651c0e24747cf7eccfb30b99a8c9a915a3396a3d/aws/resource_aws_rds_cluster_parameter_group.go#L235) to do the actual work. The function takes a [`ModifyDBClusterParameterGroupInput` struct](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#ModifyDBClusterParameterGroupInput) as the input, which has two fields: 

- `DBClusterParameterGroupName`
- `Parameters`

...the latter of which is a pointer to a slice of type `Parameters`. Looking at the [struct definition for `Parameters`](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#Parameter), the relevant field is `ParameterValue`, which is defined as:

```go
    // Specifies the value of the parameter.
    ParameterValue *string `type:"string"`
```

Similarly, looking at the API documentation for [`ModifyDBClusterParameterGroup`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBClusterParameterGroup.html) and the associated [`Parameter`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_Parameter.html) object, the `ParameterValue` argument is defined as a string.

My read on this (admittedly, this is hitting the borders of my Golang knowledge) is that because of this constraint, the value passed to `parameter.value` will be converted to a `string` when Terraform applies, despite the definition in the configuration being a `bool` or `number`. When Terraform then reads on the next run, the `parameter.value` value from AWS is showing as a string rather than whatever type is defined in the configuration, leading to the persistent diff. What is not clear to me at the moment is why this would only affect Terraform configurations which use a `dynamic` block. 

If a `number` or `bool` is passed in directly rather than via a `dynamic` block, does the issue persist? And if the `parameter.value` is passed in as a `string` rather than another type, does that resolve the persistent diff?

**Comment by justinretzolk** [comment]
@carlosjgp Thank you for the additional information! With that in mind, I've marked this as a bug so that we can look into it more deeply as time allows.

**Comment by FarhanSajid1** [comment]
Any updates?

**Comment by justinretzolk** [comment]
Hey @FarhanSajid1 👋 Thank you for checking in on this. Unfortunately, I'm not able to provide an estimate on when this will be looked into due to the potential of shifting priorities (we prioritize work by count of ":+1:" reactions, as well as a few other things). For more information on how we prioritize, check out out [prioritization guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/prioritization.md).

**Comment by anGie44** [comment]
@justinretzolk We ran into this recently when trying to configure 2 parameters on an RDS Cluster Parameter Group and then realized AWS RDS considers these parameters as **"system" Source** but the provider only reads in the parameters considered **"user" Source** according to:

https://github.com/hashicorp/terraform-provider-aws/blob/1092267d84a47daadc69dadba6c5404cb4b173ce/internal/service/rds/cluster_parameter_group.go#L163-L167

(which i agree trying to handle all these default system params hasn't historically been easy)

Example config:
```terraform
locals {
  cluster_parameters = {
    "shared_preload_libraries" = { 
      value        = "pg_stat_statements"
      apply_method = "pending-reboot"
    },
    "track_activity_query_size" = {
      value        = "4096"
      apply_method = "pending-reboot"
    }
  }
}

resource "aws_rds_cluster_parameter_group" "param_group" {
  count       = var.postgres_cluster_parameter_group_name == null ? 1 : 0
  name_prefix = format("%s-aurora-postgresql%s-", var.cluster_short_name, local.family_version)
  description = format("%s cluster parameter group for aurora-postgresql%s", var.cluster_short_name, local.family_version)
  family      = format("aurora-postgresql%s", local.family_version)

  dynamic "parameter" {
    for_each = local.cluster_parameters
    content {
      name         = parameter.key
      value        = parameter.value["value"]
      apply_method = lookup(parameter.value, "apply_method", null)
    }
  }

  tags = local.tags

  lifecycle {
    create_before_destroy = true
  }
}
```

Confirming in the console the "Source" type for the params in question:
<img width="1298" alt="Screen Shot 2023-01-20 at 11 47 38 PM" src="https://user-images.githubusercontent.com/13805595/213843922-f37d60e3-f3b6-4ec1-8de5-1e46951929dd.png">


<img width="1296" alt="Screen Shot 2023-01-20 at 11 45 44 PM" src="https://user-images.githubusercontent.com/13805595/213843897-29e6223a-a44a-47fe-a13c-f157e2607659.png">

I _think_ others maybe experiencing the same thing if they're referencing **"engine-default" Source** params as well

**Comment by bleachbyte** [comment]
This has been coming up for us in the last week or two, as well. In our case, it was for the `rds.logical_replication` parameter, which defaults to **0** but can be set to **1** with Terraform, and we were setting it with a `local`, e.g.:

```terraform
# given a list of keys, which are passed into a `dynamic` block
# in an `aws_rds_cluster_parameter_group` resource:
...
  {
    name   = "rds.logical_replication"
    value  = var.enable_replication ? "1" : "0",
    method = "pending-reboot"
  },
...
```

As per this bug, leaving it at **0** means Terraform will always have it in its plan, e.g.:

```
 # module.rds_usw2.aws_rds_cluster_parameter_group.aurora will be updated in-place
 ~ resource "aws_rds_cluster_parameter_group" "aurora" {
   + parameter {
     + apply_method = "pending-reboot"
     + name = "rds.logical_replication"
     + value = "0"
```

The solution I found was to instead create that key in its own list, and then `flatten` it along with the custom parameters we always set, e.g.:

```
locals {
...
  cluster_pgroup_params = flatten([
    [
      {
        name   = "rds.force_ssl",
        value  = "1",
        method = "pending-reboot"
      },
      {
        name  = "max_standby_streaming_delay",
        value = "30000"
      },
    ],
    var.enable_replication ? [{
      name   = "rds.logical_replication",
      value  = "1",
      method = "pending-reboot"
    }] : []
  ])
...
}
```

It's a bit messy, but it works for now!
