### ISSUE TITLE
Add JSON file output to aws_ecs_task_definition

### ISSUE THREAD

**Issue by alkalinecoffee** [hashicorp/terraform-provider-aws#12874]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The ECS API currently exposes the complete JSON file after registering a task definition with the `aws ecs register-task-definition` command, ie

```
$ aws ecs register-task-definition ...

{
    "taskDefinition": {
        "volumes": [],
        "taskDefinitionArn": "arn:aws:ec2:us-east-1:aws_account_id:task-definition/sleep360:1",
        "containerDefinitions": [
        ...
```

This output does not appear to be exposed to the user in the current terraform provider.

The use-case for having this output available would be to assist users who wish to pass a complete task definition JSON to another process.  One example would be for users who wish to run the `ecs-cli local` commands to spin up a virtual ECS environment for local dev and testing.  The `ecs-cli` command requires a complete task definition JSON file to work.  Currently with terraform, we cannot create/expose this JSON file, as it is only compiled by ECS when registering a task.

### New or Affected Resource(s)

* aws_ecs_task_definition

### Potential Terraform Configuration

```hcl
output task_definition_json {
  value = aws_ecs_task_definition.mytask.json
}
```

**Comment by bflad** [comment]
Hi @alkalinecoffee 👋 Thank you for submitting this.

Returning the exact AWS CLI compatible JSON of an AWS infrastructure component is not currently a design goal or implementation detail of most, if not any, Terraform AWS Provider resources or data sources. Since the AWS CLI is automatically generated from the API models provided by the AWS service teams, there can be considerable naming and structural differences between the Terraform AWS Provider and the AWS CLI. There are also customizations made in the AWS Go SDK from the upstream API models that might change the generated code, even if we were to JSON marshal the AWS Go SDK structs directly into an attribute.

If there are downstream inputs that require the exact AWS CLI formatting, it might be best to use the AWS CLI itself to generate those prior to running the dependent command. There are a multitude of ways Terraform can help get that AWS CLI command ready, such as providing the relevant outputs that the command might need as input, e.g.

```hcl
output "task_definition_arn" {
  value = aws_ecs_task_definition.mytask.arn
}
```

And setting up your downstream handling to use this:

```console
$ terraform apply
$ aws ecs describe-task-definition --task-definition $(terraform output task_definition_arn) > task-definition.json
$ ecs-cli local create up
```

There are [limitations](https://github.com/hashicorp/terraform-provider-external/issues/13) in the [`external` data source](https://www.terraform.io/docs/providers/external/data_source.html) that prevent it being usable in this situation, but those limitations would need to be solved in that provider.

Its also possible to manually assemble a similar JSON string within Terraform without code changes to the provider:

```hcl
terraform {
  required_providers {
    aws = "2.58.0"
  }
  required_version = "0.12.24"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_ecs_task_definition" "example" {
  family = "example"

  container_definitions = jsonencode([{
    name      = "sleep"
    image     = "busybox"
    cpu       = 10
    command   = ["sleep", "360"]
    memory    = 10
    essential = true
  }])

  volume {
    name = "database_scratch"
  }
}

output "native_task_definition_json" {
  value = jsonencode({
    taskDefinition = {
      containerDefinitions = jsonencode(aws_ecs_task_definition.example.container_definitions)
      taskDefinitionArn    = aws_ecs_task_definition.example.arn
      volumes              = aws_ecs_task_definition.example.volume
    }
  })
}
```

Which outputs:

```console
$ terraform apply && terraform output native_task_definition_json | jq '.'
aws_ecs_task_definition.example: Refreshing state... [id=example]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

native_task_definition_json = {"taskDefinition":{"containerDefinitions":[{"command":["sleep","360"],"cpu":10,"environment":[],"essential":true,"image":"busybox","memory":10,"mountPoints":[],"name":"sleep","portMappings":[],"volumesFrom":[]}],"taskDefinitionArn":"arn:aws:ecs:us-east-1:123456789012:task-definition/example:1","volumes":[{"docker_volume_configuration":[],"efs_volume_configuration":[],"host_path":"","name":"database_scratch"}]}}
{
  "taskDefinition": {
    "containerDefinitions": [
      {
        "command": [
          "sleep",
          "360"
        ],
        "cpu": 10,
        "environment": [],
        "essential": true,
        "image": "busybox",
        "memory": 10,
        "mountPoints": [],
        "name": "sleep",
        "portMappings": [],
        "volumesFrom": []
      }
    ],
    "taskDefinitionArn": "arn:aws:ecs:us-east-1:123456789012:task-definition/example:1",
    "volumes": [
      {
        "docker_volume_configuration": [],
        "efs_volume_configuration": [],
        "host_path": "",
        "name": "database_scratch"
      }
    ]
  }
}
```

However as shown above, there may be slight differences in the output formatting, especially around empty arrays, strings, or numbers, and is dependent on the Terraform AWS Provider naming/structures.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd consider reviewing a pull request (creating a new attribute that contains the JSON string marshalization of the Go structure, if it requires no additional JSON handling code in the Terraform provider) if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to this comment), which we use as one of the inputs to prioritize work for the Terraform team.
