### ISSUE TITLE
Can't ignore changes for aws_ecs_service load_balancer.0.target_group_arn (for CodeDeploy blue-green deploys)

### ISSUE THREAD

**Issue by jfirebaugh** [hashicorp/terraform-provider-aws#13192]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.54.0
```

### Affected Resource(s)

* `aws_ecs_service`

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "service" {
  # ...

  load_balancer {
    target_group_arn = var.target_group_a_arn
    container_name   = var.load_balancer_container_name
    container_port   = 80
  }

  lifecycle {
    ignore_changes = [load_balancer.0.target_group_arn]
  }
}
```

### Expected Behavior

The `target_group_arn` key of the first load_balancer set should be ignored. This is necessary for using CodeDeploy blue-green deployments, which modify this property outside of terraform's control.

### Actual Behavior

When running `terraform plan`, the following error is output:

```
Error: Cannot index a set value

  on deploy/ecs_web_service/main.tf line 52, in resource "aws_ecs_service" "service":
  52:     ignore_changes = [desired_count, task_definition, load_balancer.0.target_group_arn]

Block type "load_balancer" is represented by a set of objects, and set
elements do not have addressable keys. To find elements matching specific
criteria, use a "for" expression with an "if" clause.
```

### References

This was previously reported in #9776. @bflad said there to open an issue in terraform core repository. @ryzr did so: https://github.com/hashicorp/terraform/issues/22504. Then _that_ issue was closed by @ryzr saying to open an issue here again. So that's what I'm doing. Please consider @jbardin's [suggestion of using a TypeList rather than a Set](https://github.com/hashicorp/terraform/issues/22504#issuecomment-522615551).

**Comment by chrysalis69** [comment]
I've just ignored the complete load_balancer block, because all 3 values (`target_group_arn`, `container_name`, `container_port`) are managed by the appspec in code-deploy.

In other words, my lifecycle looks like this:

```
  lifecycle {
    ignore_changes = [
      desired_count,   # Updated possibly by auto scaling
      task_definition, # Updated by deployments
      load_balancer,
    ]
  }
```

**Comment by fugitive90** [comment]
@chrysalis69  For task_definition , you could use this snippet:
`task_definition                   = "${aws_ecs_task_definition.this.family}:${max(aws_ecs_task_definition.this.revision, data.aws_ecs_task_definition.latest.revision)}"`

Just find with `data` resource current task definition revision and revision from your TF definition, this would be a way to get latest one.

I also experience this bug with CodeDeploy B/G deployments

**Comment by jfirebaugh** [comment]
It's still a provider issue, albeit one that has viable workarounds as others have noted.

**Comment by Sitole** [comment]
Any progress?

**Comment by aholthagerty** [comment]
this is an issue with more than just `aws_ecs_service load_balancer.0.target_group_arn`

this is an issue with any resource currently using a `Set` rather than a `TypeList`, correct?

**Comment by quinn** [comment]
any update here?

**Comment by d11-jwaring** [comment]
Still occurring in version 5.4 of the AWS provider.

**Comment by gdavison** [comment]
Thanks all for reporting the issue and participating in the discussion. The `lifecycle.ignore_changes` directive is managed by Terraform itself while generating a plan, and the provider is never aware of it. This means that any fixes to the general behaviour of `lifecycle.ignore_changes` need to be implemented in the Terraform project.

For this specific case, `load_balancer` is a Set because it can have multiple values and the order is not significant. Using the List type would not be appropriate for this parameter.

To ignore changes, you could ignore changes to the whole Set, using

```terraform
lifecycle {
  ignore_changes = [load_balancer]
}
```

as suggested above.

If the other values should not be ignored, I suggest requesting the feature from the Terraform project. In a previous report (https://github.com/hashicorp/terraform/issues/22504#issuecomment-522615551) they suggested that ignoring individual parameters of set members would be "a very limited use case". You could open a new issue with them and indicate how it is useful.
