### ISSUE TITLE
Error: Failed to modify RDS Cluster (xxxx): InvalidParameterCombination: The AllowMajorVersionUpgrade flag must be present when upgrading to a new major version.

### ISSUE THREAD

**Issue by harishdinne** [hashicorp/terraform-provider-aws#13389]
upgrading the aws rds postgres cluster from 9.6.12 to 10.11

when i tried to change the engine version and applied the changes i got this error

Error: Failed to modify RDS Cluster (xxx): InvalidParameterCombination: The AllowMajorVersionUpgrade flag must be present when upgrading to a new major version.

**Comment by justinretzolk** [comment]
Hey @harishdinne 👋 Thank you for taking the time to file this. Looking over the provider, it looks like the [necessary argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#allow_major_version_upgrade) has been added since you initially filed this. Can you confirm if this resolves your issue?

**Comment by justinretzolk** [comment]
Since we haven't heard back in a while, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue (referencing this one for context as needed).
