### ISSUE TITLE
service/rds: S3 Import acctest failure

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-provider-aws#13391]
Acceptance tests `TestAccAWSDBInstance_S3Import` and `TestAccAWSRDSCluster_s3Restore` both use an S3 import of a mysql backup and fail with the same error.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_db_instance
* aws_rds_cluster

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

acctests pass

### Actual Behavior

acctests fail:
```
Error: unexpected state 'incompatible-restore', wanted target 'available, storage-optimization'. last error: %!s(<nil>)

```

### Steps to Reproduce

1. run acctests

### References

* #13333

**Comment by YakDriver** [comment]
To sum up a discussion on this in #14778 

For an S3 import, AWS requires the use of the latest minor version (e.g., for MySQL, `5.6.44` rather than `5.6.35`). The latest minor version is, of course, always changing. Also, the GovCloud and commercial partitions currently have different latest versions (`5.6.44` and `5.6.35`, respectively) so it's not as easy to hardcode and occasionally update.

Even getting the version right (e.g., by not including `engine_version`), still leaves you with the `incompatible-restore` issue. I suspect the s3 problem is:

* the testdata/mysql-5-6-xtrabackup.tar.gz file is specific to a minor version of MySQL that is not the latest minor version
* AWS requires the latest minor version

The solution may be to create the backup file (i.e., `tar.gz`) as part of the test and then restore that backup so that they will always be minor-version compatible.
