### ISSUE TITLE
#11998 seems still not to work, although closed... same behaviour in 2.62.0

### ISSUE THREAD

**Issue by fritzrichter** [hashicorp/terraform-provider-aws#13405]

**Comment by justinretzolk** [comment]
Hi @fritzrichter 👋 Thank you for taking the time to submit this issue. Given that there's been a number of Terraform and AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this issue?

If you are, can you update the issue with the information from the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
