### ISSUE TITLE
Display Invalid Value for Aurora Serverless 

### ISSUE THREAD

**Issue by lays147** [hashicorp/terraform-provider-aws#13475]
### Description

While trying to create an `aws_rds_cluster_instance` I get the error:
`error creating RDS DB Instance: InvalidParameterValue: Instances cannot be added to Aurora Serverless clusters`
But there's no output of the invalid parameter.

### New or Affected Resource(s)
* aws_rds_cluster_instance

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster_instance" "cluster_instances" {
  count              = var.instances_amount
  identifier         = "${var.app_name}-aurora-instance-${count.index}"
  cluster_identifier = aws_rds_cluster.default.id
  apply_immediately            = false
  auto_minor_version_upgrade   = true
  copy_tags_to_snapshot        = true
  db_subnet_group_name         = aws_db_subnet_group.this.name
  engine                       = var.engine_type
  engine_version               = var.engine_version
  instance_class               = var.instance_class
  preferred_backup_window      = "03:00-04:00"
  preferred_maintenance_window = "Sun:04:01-Sun:05:00"
  publicly_accessible          = false
}
```

### References
This problem also happended with `aws_db_instance` and apparently was fixed on the following issue:

* #3626

**Comment by bflad** [comment]
Hi @lays147 👋 Thank you for raising this.

In this case, the `error creating RDS DB Instance: InvalidParameterValue: Instances cannot be added to Aurora Serverless clusters` is already fairly specific for this situation since with [Aurora Serverless you do not manage cluster instances](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.how-it-works.html). The only relevant parameter in this case would be including the `cluster_identifier`, to more easily identify which Cluster is Serverless and invalid for creating the instance, which should definitely be included in the error message for this resource and I'll submit the change for now.

For what its worth, we are generally a little hesitant to include the full API input parameters in error messaging as it tends to pollute the user interface with potentially irrelevant information, could have security implications that operators then cannot avoid, and since its already possible to see today when [debug logging](https://www.terraform.io/docs/internals/debugging.html) is enabled in Terraform.
