### ISSUE TITLE
EKS Created Security Group

### ISSUE THREAD

**Issue by v0ldemort** [hashicorp/terraform-provider-aws#13970]
I have created the EKS cluster using terraform's eks-getting-started chart.

 After deployment, there is an EKS created a security group to exposes ports to the web. 

I am not able to find the way that how I can add ports in that security group. Please help

**Comment by DrFaust92** [comment]
Hey @v0ldemort,

you can use https://www.terraform.io/docs/providers/aws/r/security_group_rule.html to add a rule to the EKS Cluster SG

**Comment by v0ldemort** [comment]
Thanks, @DrFaust92, 

Actually I am talking about the security group which will automatically create by the EKS, known as **cluster_security_group_id**. I am getting this group id only after the cluster deployment. In this case, I have to manually add the ingress ports in that security group.

**Comment by DrFaust92** [comment]
what i meant was to use the sg output of the eks cluster resource like so:

```
resource "aws_security_group_rule" "example" {
  type              = "ingress"
  from_port         = 0
  to_port           = 65535
  protocol          = "tcp"
  cidr_blocks       = ["1.1.1.1/16"]
  security_group_id = eks_cluster.vpc_config[0].cluster_security_group_id
}
```

**Comment by v0ldemort** [comment]
hey, while I am validating the code I am getting the error mentioned below 

```
Error: Reference to undeclared resource

  on eks-cluster.tf line 126, in resource "aws_security_group_rule" "example":
 126:   security_group_id = eks_cluster.vpc_config[0].cluster_security_group_id

A managed resource "eks_cluster" "vpc_config" has not been declared in the
root module.

```

**Comment by DrFaust92** [comment]
i had missed some thing see my full example:
```

resource "aws_eks_cluster" "this" {
  name                      = var.cluster_name
  version                   = var.k8s_version
  role_arn                  = join("", aws_iam_role.main.*.arn)
  enabled_cluster_log_types = var.enabled_cluster_log_types
  tags                      = var.tags

  vpc_config {
    subnet_ids              = flatten([var.public_subnets, var.private_subnets])
    endpoint_private_access = var.private_access
    endpoint_public_access  = var.public_access
    public_access_cidrs     = var.public_cidrs
  }
}

resource "aws_security_group_rule" "cluster_k8s_ingress" {
  cidr_blocks       = data.aws_subnet.private.*.cidr_block
  description       = "Allows ingress traffic from private subnets to Node Ports"
  from_port         = 30000
  to_port           = 32767
  protocol          = "tcp"
  security_group_id = aws_eks_cluster.this.vpc_config[0].cluster_security_group_id
  type              = "ingress"
}
```
it should be eks_cluster.**{resource_name}**.vpc_config[0].cluster_security_group_id

**Comment by bflad** [comment]
It looks like this was answered above (thank you, @DrFaust92). If you're looking for further general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.
