### ISSUE TITLE
RDS Cluster is no reattached to Global Cluster after failing deletion

### ISSUE THREAD

**Issue by marinsalinas** [hashicorp/terraform-provider-aws#13981]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

TFE - v202003-1
Terraform v0.12.26

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

```hcl

resource "aws_rds_global_cluster" "global" {
  global_cluster_identifier = "test-cluster"
  engine                    = "aurora-mysql"
  engine_version            = "5.7.mysql_aurora.2.07.1"
  storage_encrypted         = false
}

resource "aws_rds_cluster" "primary_cluster" {
  availability_zones              = var.primary_availability_zones
  cluster_identifier              = var.cluster_name
  database_name                   = "test"
  engine                    = "aurora-mysql"
  engine_version            = "5.7.mysql_aurora.2.07.1"
  engine_mode	  = "provisioned"
  global_cluster_identifier       = aws_rds_global_cluster.global.id
  master_password                 = "test"
  master_username                 = "test"
  skip_final_snapshot              = true
  storage_encrypted               = false
  deletion_protection             = true
  vpc_security_group_ids         = [var.primary_vpc]
}

resource "aws_rds_cluster_instance" "primary" {
  cluster_identifier           = aws_rds_cluster.primary_cluster.id
  engine                    = "aurora-mysql"
  engine_version            = "5.7.mysql_aurora.2.07.1"
  identifier                   = "${var.db_instance_name}"
  instance_class               = "db.r4.large"
}
```

### Debug Output

```
Error: Existing RDS Clusters cannot be added to an existing RDS Global Cluster
```

### Expected Behavior

RDS Cluster should reattach to the global cluster after failing deletion to be able to run a subsequent apply.

### Actual Behavior

RDS deletion fails due to `deletion protection = true`.

The RDS cluster is detached from the Global Cluster before deletion so the deletion fails and after that, it doesn't reattach causing the error (`Error: Existing RDS Clusters cannot be added to an existing RDS Global Cluster.`) in the subsequent apply (when we want to set `deletion_protection=false`).

See https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_rds_cluster.go#L1255 for more context.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3.  change `aws.rds_cluster.primary_cluster.deletion_protection = false`
4 `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @marinsalinas 👋  Thank you for raising this and sorry you ran into trouble here.

When in this particular scenario, where the DB Cluster has already been removed from the Global Cluster but an update needs to occur to fix the `deletion_protection` value, the configuration will need to be updated to work around the RDS API not having the ability to re-add the DB Cluster back into the Global Cluster to complete the desired update to match the updated configuration. Either commenting out the `global_cluster_identifier` argument of the `aws_rds_cluster` resource or adding `lifecycle` `ignore_changes = [global_cluster_identifier]` to the `aws_rds_cluster` resource should allow the update to occur without trying to perform the unavailable API operation, then allow the resource to be destroyed properly.

That being said, we _may_ be able to detect and report an error with the `deletion_protection = true` situation upfront in the `aws_rds_cluster` resource during destroy, however this new logic will require reliance on the `deletion_protection` state value to be correct. Any changes to the deletion protection outside of Terraform between the last refresh and the destroy of the resource could cause either erroneously fail the Terraform run (`deletion_protection = true` in state while it was disabled outside of Terraform) or fall into the same situation as this issue report (`deletion_protection = false` in state while it was enabled outside of Terraform). A potential solution could then be to forcibly refresh the deletion protection status at deletion time to check it, however we generally discourage adding reads into the deletion path of resources due to the added complexity, these API calls still leaving chances for race conditions, and the potential for other problematic behavior. 

Please reach out if you have any questions.

**Comment by marinsalinas** [comment]
Since global cluster deletion was fixed, I wasn't able to reproduce this error, so I'll close it and re-open it if I got the same issue again.

Thank @bflad  for your help.
