### ISSUE TITLE
Usage plans get disconnected from API stages on iterated re-applies

### ISSUE THREAD

**Issue by evanfuller** [hashicorp/terraform-provider-aws#14100]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.12.26

### Affected Resource(s)

* aws_api_gateway_deployment
* aws_api_gateway_usage_plan

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_deployment" "api_gateway" {
  rest_api_id = var.api_gateway_id
  stage_name  = var.stage_name
}

resource "aws_api_gateway_usage_plan" "customer_plan" {
  name        = "My-Plan"
  description = "Usage plan desc"
  api_stages {
    api_id = var.api_gateway_id
    stage  = var.stage_name
  }

  quota_settings {
    limit  = 1000
    period = "MONTH"
  }

  throttle_settings {
    burst_limit = 100
    rate_limit  = 10
  }
}

```

### Expected Behavior

Even if the API Stage is destroyed / re-created, the usage plans should be attached to the new stage on re-creation

### Actual Behavior

When going through iterative cycles of `terraform apply`, the usage plans alternate between being detached and re-attached. For example, if the usage plan is currently attached to stage `v1`, then after running `terraform apply`, the usage plan becomes detached. Running `terraform apply` again will cause the usage plan to be re-attached.

### Steps to Reproduce

1. Deploy an `api_gateway_deployment` resource alongside an `api_gateway_usage_plan`. The usage plan should have an `api_stages{ }` block which refers to the same stage name as the deployment.
1. `terraform apply` repeatedly to demonstrate the issue of detaching and re-attaching.

### Important Factoids

I noticed that in the terraform plan output, the usage plan stage name does appear as an expected update. However, during the actual apply phase, it seems like terraform just throws it away entirely, and never prints out a line to show that it's modifying the usage plan resource.

Example 1 (running apply when the usage plan is currently attached):
```hcl
  # module.api_gateway_usage_plans.aws_api_gateway_usage_plan.customer_plan will be updated in-place
  ~ resource "aws_api_gateway_usage_plan" "customer_plan" {
        arn         = "arn:aws:apigateway:us-west-2::/usageplans/abc123"
        description = "Usage plan for customers"
        id          = "abc123"
        name        = "API-Customers"
        tags        = {}

      ~ api_stages {
            api_id = "def456"
          ~ stage  = "v1" -> (known after apply)
        }

        throttle_settings {
            burst_limit = 100
            rate_limit  = 10
        }
    }

Plan: 1 to add, 1 to change, 1 to destroy.

...

module.api_gateway_deployment.aws_api_gateway_deployment.api_gateway: Destroying... [id=xxxxx]
module.api_gateway_deployment.aws_api_gateway_deployment.api_gateway: Destruction complete after 1s
module.api_gateway_deployment.aws_api_gateway_deployment.api_gateway: Creating...
module.api_gateway_deployment.aws_api_gateway_deployment.api_gateway: Creation complete after 1s [id=yyyyy]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

```

Example 2 (re-running apply when the usage plan is currently detached):

```hcl
  # module.api_gateway_usage_plans.aws_api_gateway_usage_plan.customer_plan will be updated in-place
  ~ resource "aws_api_gateway_usage_plan" "customer_plan" {
        arn         = "arn:aws:apigateway:us-west-2::/usageplans/abc123"
        description = "Usage plan for paid customers"
        id          = "abc123"
        name        = "API-Customers"
        tags        = {}

      + api_stages {
          + api_id = "def456"
          + stage  = (known after apply)
        }

        throttle_settings {
            burst_limit = 100
            rate_limit  = 10
        }
    }

Plan: 1 to add, 1 to change, 1 to destroy.

...

module.api_gateway_deployment.aws_api_gateway_deployment.api_gateway: Destroying... [id=xxxxx]
module.api_gateway_deployment.aws_api_gateway_deployment.api_gateway: Destruction complete after 1s
module.api_gateway_deployment.aws_api_gateway_deployment.api_gateway: Creating...
module.api_gateway_deployment.aws_api_gateway_deployment.api_gateway: Creation complete after 1s [id=yyyyy]
module.api_gateway_usage_plans.aws_api_gateway_usage_plan.customer_plan: Modifying... [id=abc123]
module.api_gateway_usage_plans.aws_api_gateway_usage_plan.customer_plan: Modifications complete after 1s [id=abc123]

Apply complete! Resources: 1 added, 1 changed, 1 destroyed.


```

**Comment by bflad** [comment]
Hi folks 👋 

This is due to Terraform configurations containing an `aws_api_gateway_deployment` resource using the `stage_name` argument. Behind the scenes when using the `stage_name` argument in the deployment resource, it is deleting and recreating the stage during resource recreation. This stage recreation will remove downstream resources such as `aws_api_gateway_method_settings` and `aws_api_gateway_usage_plan` associated with that stage which will then need to be created.

To fix this issue in your configuration, you should:

* Use the `aws_api_gateway_stage` resource instead of `aws_api_gateway_deployment` resource `stage_name` argument
* Ensure the `aws_api_gateway_deployment` resource has `create_before_destroy` enabled

To summarize these in a quick configuration example:

```
resource "aws_api_gateway_deployment" "example" {
  rest_api_id = aws_api_gateway_rest_api.example.id

  triggers = {
    redeployment = # ... references to upstream resources (see issue link below) ...
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "example" {
  deployment_id = aws_api_gateway_deployment.example.id
  rest_api_id   = aws_api_gateway_rest_api.example.id
  stage_name    = "example"
}

resource "aws_api_gateway_usage_plan" "example" {
  # ... other configuration ...

  api_stages {
    api_id = aws_api_gateway_rest_api.example.id
    stage  = aws_api_gateway_stage.example.stage_name
  }
}
```

* For a longer explanation with more guidance and example configurations: https://github.com/hashicorp/terraform-provider-aws/issues/11344#issuecomment-765138213
* Updates for the Terraform AWS Provider's API Gateway REST API documentation: https://github.com/hashicorp/terraform-provider-aws/pull/17230

Since the above issue and pull request should exhaustively cover this problem as well, I'm going to close this issue. If you are having further trouble with this functionality after applying these recommendations, please submit new GitHub issues following the [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) and [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) issue templates for further triage.
