### ISSUE TITLE
Add timeout support for aws_ebs_snapshot_copy

### ISSUE THREAD

**Issue by dbzm** [hashicorp/terraform-provider-aws#14354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for snapshot copies, specifically creation.  When copying large snapshots, especially between regions, it is virtually guaranteed that the default 10 minutes is inadequate. 

### New or Affected Resource(s)

* aws_ebs_snapshot_copy

### Potential Terraform Configuration

```hcl
resource "aws_ebs_snapshot" "snapshot" {
  volume_id   = "vol-fffffffffffffffff"
  description = "My Volume"

  # ...

  timeouts {
    create = "3h"
  }
}

resource "aws_ebs_snapshot_copy" "copy" {
  provider = "aws.virginia"

  source_snapshot_id = "${aws_ebs_snapshot.snapshot.id}"
  source_region      = "${data.aws_region.current.name}"

  description = "${aws_ebs_snapshot.snapshot.description}"
  encrypted   = "${aws_ebs_snapshot.snapshot.encrypted}"
  kms_key_id  = "${aws_ebs_snapshot.snapshot.kms_key_id}"
  tags        = "${aws_ebs_snapshot.snapshot.tags}"

  timeouts {
    create = "3h"
  }
}
```

**Comment by rba1-source** [comment]
I've done some testing and if you are creating an aws_ebs_snapshot_copy resource that has a different KMS key than the original, which would force it to do a Full Copy, this takes almost exactly 4 hours to process a 16TB snapshot.

This means that with the current 10 minute limit, you can only successfully create aws_ebs_snapshot_copy resources which are less than about 660GB.

There is a workaround: if you create the resource twice (i.e run your terraform apply, wait for it to timeout, wait 4 hours and then run it again), from my testing it seems that the snapshot copy will create in under 8 minutes - which is very fortuitous - as long as the snapshot you're copying still exists (because EBS recognises there is no change to contents of the source, so does a much faster copy_snapshot). But it also means your deployment takes twice as long and costs twice as much, and you have a tidy-up to do afterwards; and it depends on the other resources defined in your terraform supporting multiple deployments without redeploying them if inappropriate. It also means if, for some reason this faster copy were to edge over 10 minutes, the operation would become impossible with terraform - it's sheer luck that it manages to complete in just under the timeout period.

The timeouts block was added for aws_ebs_snapshot resource in v2.19 through #8043. It would be useful if, when making changes to the aws_ebs_snapshot resource in the future, the same changes are considered to be made in aws_ebs_snapshot_copy as part of the same enhancement/bugfix, where appropriate.

Hopefully, since the code already exists for the aws_ebs_snapshot resource, it should be much less effort to implement this into aws_ebs_snapshot_copy than if you were writing the code from scratch.

**Comment by devindice** [comment]
This crippled my company once we switched to encrypted volumes. I compiled changes from the source as a temporary fix and confirmed it worked well. My notes are here.
https://github.com/hashicorp/terraform-provider-aws/pull/20912

**Comment by rba1-source** [comment]
In the end, I also ended up having to copy the changes into the source code and compile my own binary. It worked perfectly.
