### ISSUE TITLE
aws_api_gateway_deployment - Stage already exists

### ISSUE THREAD

**Issue by oshea00** [hashicorp/terraform-provider-aws#14424]
Still a problem:
https://github.com/terraform-providers/terraform-provider-aws/issues/2918

AWS provider 2.7

aws_api_gateway_deployment.apideployment: Destroying... [id=aqxk2w]
aws_api_gateway_rest_api.wordapi: Modifying... [id=kgm4skl7fj]
aws_api_gateway_rest_api.wordapi: Modifications complete after 0s [id=kgm4skl7fj]
aws_api_gateway_deployment.apideployment: Destruction complete after 1s
aws_api_gateway_deployment.apideployment: Creating...
aws_api_gateway_deployment.apideployment: Creation complete after 1s [id=88om2m]
aws_api_gateway_stage.wordapistage: Creating...
Error: Error creating API Gateway Stage: ConflictException: Stage already exists
  on main.tf line 92, in resource "aws_api_gateway_stage" "wordapistage":
  92: resource "aws_api_gateway_stage" "wordapistage" {
ERROR: Job failed: command terminated with exit code 1

**Comment by bflad** [comment]
Hi folks 👋 

This is likely due to Terraform configurations containing an `aws_api_gateway_deployment` resource using a `stage_name` argument which matches a `aws_api_gateway_stage` resource `stage_name` argument. Behind the scenes when using the `stage_name` argument in the deployment resource, it is deleting and recreating the stage. When the `aws_api_gateway_stage` resource then attempts to create the stage itself, it will already exist.

Our recommends in this case are to:

* Use only `aws_api_gateway_stage` instead of `aws_api_gateway_deployment` resource `stage_name` argument
* Ensure the `aws_api_gateway_deployment` resource has `create_before_destroy` enabled

To summarize these in a quick configuration example:

```
resource "aws_api_gateway_deployment" "example" {
  rest_api_id = aws_api_gateway_rest_api.example.id

  triggers = {
    redeployment = # ... references to upstream resources (see issue link below) ...
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "example" {
  deployment_id = aws_api_gateway_deployment.example.id
  rest_api_id   = aws_api_gateway_rest_api.example.id
  stage_name    = "example"
}
```

* For a longer explanation with more guidance and example configurations: https://github.com/hashicorp/terraform-provider-aws/issues/11344#issuecomment-765138213
* Updates for the Terraform AWS Provider's API Gateway REST API documentation: https://github.com/hashicorp/terraform-provider-aws/pull/17230

Since the above issue and pull request should exhaustively cover this particular problem, I'm going to close this issue. If you are having further trouble with this functionality after applying these recommendations, please submit new GitHub issues following the [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) and [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) issue templates for further triage.
