### ISSUE TITLE
aws_cloudformation_stack failure causes output and data source resolution error due to missing output map entry. Prevents state destruction

### ISSUE THREAD

**Issue by mikhasd** [hashicorp/terraform-provider-aws#14537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.29
+ provider.aws v3.1.0
```

### Affected Resource(s)

* aws_cloudformation_stack

### Terraform Configuration Files

```hcl
resource "aws_cloudformation_stack" "failing_resource" {
  name = "FailingResource"

  template_body = jsonencode({
    AWSTemplateFormatVersion = "2010-09-09"

    Resources = {
      FailingResource = {
        Type = "Custom::FailingResource"
        Properties = {
          ServiceToken = "112233445566778899"
        }
        
      }
    }

    Outputs = {
      MissingOutput = {
        Value = "MissingValue"
      }
    }
  })
}

data "aws_cloudformation_stack" "missing_stack" {
  name = "TheStack${aws_cloudformation_stack.failing_resource.outputs["MissingOutput"]}"
}

output "missing_output" {
    value = "The the result is: ${aws_cloudformation_stack.failing_resource.outputs["MissingOutput"]}"
}
```

### Debug Output

https://gist.github.com/mikhasd/629bf341e73bfa78a4cb86c14a6d573a

### Expected Behavior

Outputs and data sources should not be resolved as its dependencies are not in a valid state.

I should be able to destroy the my state and underlying resources.

### Actual Behavior

The failure on executing the cloud formation stack cause its state to contains an empty map of outputs instead of the expected map.

It is causing the output and data source evaluation to fail, preventing it from destroying the invalid state.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by justinretzolk** [comment]
Hey @mikhasd 👋 Thanks for filing this. Looking at the errors, which I've pulled out below, I'm thinking this an issue with the configuration rather than the provider. As that's the case, I'm going to go ahead and close this issue out. If you feel I've done this is error, please do let me know.

Errors from the debug output: 

```
Error: Invalid index
The given key does not identify an element in this collection value.

Error: Invalid index
The given key does not identify an element in this collection value.
```

With that said, I know you've been waiting quite a bit of time for some input, and I needed to look into it anyways to verify my thoughts, so I'll include what I came up with below. I hope it helps!

While this is a bit ugly, a [conditional](https://www.terraform.io/docs/language/expressions/conditionals.html) may be combined with [contains()](https://www.terraform.io/docs/language/functions/contains.html) and [keys()](https://www.terraform.io/docs/language/functions/keys.html) to provide a "toggle" of sorts. This is a pretty common pattern used in a lot of Terraform modules. 

```
locals {
  # `local.has_missing_output` will be a boolean. Putting this here is strictly for ease of reading.
  #
  has_missing_output = contains(keys(aws_cloudformation_stack.failing_resource.outputs), "MissingOutput")
}

data "aws_cloudformation_stack" "missing_stack" {
  # Here's where the conditional comes in
  #
  count = local.has_missing_output ? 1 : 0
  name = "TheStack${aws_cloudformation_stack.failing_resource.outputs["MissingOutput"]}"
}

output "missing_output" {
  # Another conditional is used here 
  #
  value = local.has_missing_output ? "The the result is: ${aws_cloudformation_stack.failing_resource.outputs["MissingOutput"]}" : "Some other output string, based on your needs"
}
```
