### ISSUE TITLE
resource "aws_cloudformation_stack" cannot be updated

### ISSUE THREAD

**Issue by Thomas999999** [hashicorp/terraform-provider-aws#14824]
Hi,

I'm trying to update an already existing cloudformation stack via terraform aws_cloudformation_stack resource  but getting error message

aws_cloudformation_stack.eks-worker-nodes: Creating...

Error: Creating CloudFormation stack failed: AlreadyExistsException: Stack [eksctl-d021970-template-nodegroup-workers] already exists
        status code: 400, request id: 9615f52a-e3ea-4c66-aec2-e9b8734da41f

I assumed that I should enter the same stack in order to update it, correct?...as I could not find any hint in the aws_cloudformation_stack documentation of terraform...

My tf looks like this:

#########################################################################################################
  ###Inject existing worker stack with new proxy configuration

  resource "aws_cloudformation_stack" "eks-worker-nodes" {
  depends_on = [ null_resource.jump_proxy ]
  name         = "eksctl-${var.eks_cluster_name}-nodegroup-workers"
  capabilities = ["CAPABILITY_IAM"]
    
   parameters = {
    KeyName                             = "${var.key_name}"

    NodeImageIdSSMParam                 = "/aws/service/eks/optimized-ami/1.17/amazon-linux-2/recommended/image_id"
    NodeInstanceType                    = "${var.instance_type_cpu_worker}"
    NodeAutoScalingGroupMinSize         = "0"
    NodeAutoScalingGroupMaxSize         = "10"
    NodeAutoScalingGroupDesiredCapacity = "4"
    NodeVolumeSize                      = "${var.EKS_worker_space_GB}"
    NodeGroupName                       = "workers"

    ClusterName                         = "${var.eks_cluster_name}"

    ClusterControlPlaneSecurityGroup    = "sg-079814af394151f79"

    Subnets                             = "${aws_subnet.terraform[1].id},${aws_subnet.terraform[2].id}"
        
    VpcId                               = "${aws_vpc.terraform.id}"
    
  }

   template_url = "AWSTemplateFormatVersion_SLV.yml"
}

So how to update an stack with terraform now?

Thanks,
Thomas

**Comment by gdavison** [comment]
Sorry we're getting back to you so late, @Thomas999999. From the description, it sounds like you have an existing CloudFormation stack, and you want to start managing it using Terraform. Since Terraform doesn't have a record of the resource it state, it will try to create it. You're getting the error because the stack already exists.

If you want to manage existing resources using Terraform, you need to import the resources into Terraform first. Documentation for importing can be found at https://developer.hashicorp.com/terraform/cli/import.

I'm going to close this issue because of its age. If I interpreted he question incorrectly, please open a new issue.
