### ISSUE TITLE
Add Providers to support AWS IoT private CA

### ISSUE THREAD

**Issue by funnybirdman** [hashicorp/terraform-provider-aws#14949]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This feature request will add the registration code data source needed to verify
that you own a CA and the resource for importing the CA into AWS IoT Core.

### New or Affected Resource(s)

* aws_iot_ca
Arguments:
ca_certificate (required)
verification_certificate (required)
status: default "ACTIVE" ("INACTIVE", "ACTIVE")
auto_registration: default true

Attributes Reference:
certificate-id

* data.aws_iot_ca_registration_code
No arguments

Attributes Reference:
code
### Potential Terraform Configuration

```hcl
data "aws_iot_ca_registration_code" "example" {}

resource "tls_self_signed_cert" "ca" {
  private_key_pem   = tls_private_key.ca.private_key_pem
  ...
}

resource "tls_private_key" "ca" {...}

resource "tls_cert_request" "verification" {
  key_algorithm   = "RSA"
  private_key_pem = tls_private_key.verification.private_key_pem

  subject {
    common_name = data.aws_iot_ca_registration_code.code
  }
}

resource "tls_private_key" "verification" {...}

resource "tls_locally_signed_cert" "verification" {
  cert_request_pem   = tls_cert_request.verification.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem
  ...
}

resource "aws_iot_ca" "example" {
  ca_certificate            = tls_self_signed_cert.ca.cert_pem
  verification_certificate  = tls_locally_signed_cert.verification.cert_pem
  status                    = "ACTIVE"
  auto_registration         = true
}

```

### References

https://docs.aws.amazon.com/iot/latest/developerguide/register-CA-cert.html

* #0000

**Comment by gdavison** [comment]
Thanks for the issue, @funnybirdman. This looks like a good proposal.

I have a few changes to suggest:

1. Since there are both `GetRegistrationCode` and  `DeleteRegistrationCode` functions, `aws_iot_ca_registration_code` should be a resource instead of a data source.

2. I like how you used the string values `"ACTIVE"` and `"INACTIVE"` for the `status` attribute. `auto_registration` should also use `"ENABLE"` and `"DISABLE"`.

3. As an extra layer of security, `status` and `auto_registration` should default to `"INACTIVE"` and `"DISABLE"`, respectively. This way, these two options will only be enabled by the user explicitly requesting them. A default value may not be needed, if the API returns an appropriate value when the attributes are set to `Computed`.

4. To more closely match the name of the API resources, we should rename `aws_iot_ca` to `aws_iot_ca_certificate`. Strictly following this guideline, `aws_iot_ca_registration_code` would be `aws_iot_registration_code`, but leaving in `ca` makes it more explicit.

5. `aws_iot_ca_certificate` should have the following `Computed` output attributes
* `id`
* `arn`
* `certificate_pem`
* `certificate_validity`
* `creation_date`
* `last_modified_date`

Other fields from `CACertificateDescription` could be added as well.

6. I can't find documentation on how it's used, but `RegisterCACertificateInput` has a field `RegistrationConfig`. It could be included, or deferred for a future enhancement.

**Comment by tewing** [comment]
This would solve my issue as well.  Hoping to see this soon. 

Thank you.

**Comment by funnybirdman** [comment]
@gdavison Thank you for the suggestions!

> 1. Since there are both `GetRegistrationCode` and  `DeleteRegistrationCode` functions, `aws_iot_ca_registration_code` should be a resource instead of a data source.

I am hesitant to have it be a resource since no create apis were called when fetching it. Are you aware of any other resources that work that way?

**Comment by eldondevat** [comment]
I believe this is the same as #15840
