### ISSUE TITLE
aws_rds_cluster - postgres engine version can't be set to use only major version when already on latest version

### ISSUE THREAD

**Issue by teddylear** [hashicorp/terraform-provider-aws#15101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform version ->  v0.11.14
aws provider version -> v2.68.0

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files
Original
```hcl
resource "aws_rds_cluster" "foo" {
   name = "example-cluster"
   engine = "aurora-postgres"
   engine_version = "10.11"
   # Other configuration
}
```

New
```hcl
resource "aws_rds_cluster" "foo" {
   name = "example-cluster"
   engine = "aurora-postgres"
   engine_version = "10"
   # Other configuration
}
```

### Expected Behavior

Deployment of new code works successfully as with changing postgres cluster from engine version from '10.7' to '10', 

### Actual Behavior
Failed deploywith with error:
```
aws_rds_cluster.foo: Failed to modify RDS Cluster (example-cluster): InvalidParameterCombination: The specified new engine version is same as current version: 10.11
```

### Steps to Reproduce

Deploy old (with any other configuration required, then deploy new code (only change being engine version now '10' instead of '10.11'.

**Comment by anGie44** [comment]
Hi @teddylear, thank you for creating this issue. I believe this relates to how AWS interprets the `engine_version` behind the scenes i.e. if a major version is provided e.g. `10`, the db cluster will be created with the largest available minor version e.g. `10.11`. So in the case of `10.7` -> `10`, this works because the update will actually modify the `engine_version` to the next available minor version, `10.11`, but in the case of `10.11` -> `10`,  the largest available minor version is already in use. This can be confirmed if you look at the terraform state's value of the `engine_version` after applying the `10.7` -> `10` engine_version update.
