### ISSUE TITLE
Terraform plan is not showing change to DynamoDB pitr value

### ISSUE THREAD

**Issue by jbigtani** [hashicorp/terraform-provider-aws#15124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.29
+ provider.aws v3.4.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl

Step 1: Create Table with point_in_time_recovery enabled.
resource "aws_dynamodb_table" "jb-example" {
  name             = "jb-example"
  hash_key         = "TestTableHashKey"
  billing_mode     = "PAY_PER_REQUEST"
  attribute {
    name = "TestTableHashKey"
    type = "S"
  }
 
   point_in_time_recovery {
        enabled = true
    }
}

Step 2: Update Table with point_in_time_recovery disabled by removing the point_in_time_recovery block .
resource "aws_dynamodb_table" "jb-example" {
  name             = "jb-example"
  hash_key         = "TestTableHashKey"
  billing_mode     = "PAY_PER_REQUEST"
  attribute {
    name = "TestTableHashKey"
    type = "S"
  } 
}
```

### Expected Behavior

After running step 2 to disable point_in_time_recovery, plan should have shown below differences
 ~ point_in_time_recovery {
          ~ enabled = true -> false
        }

### Actual Behavior

No changes. Infrastructure is up-to-date.
### Steps to Reproduce

1. `terraform apply` to create a dynamodb table with pitr = true
2. `terraform apply` or `terraform apply`  after removing pitr block. It does not disable pitr.

####  Workaround
Instead of removing pitr block if you just turn the flag value to false, it works. 
```hcl 
point_in_time_recovery {
        enabled = false
    }
```

**Comment by anGie44** [comment]
Related: https://github.com/terraform-providers/terraform-provider-aws/issues/14476

**Comment by anGie44** [comment]
Hi @jbigtani, thank you for creating this issue. I'm able to reproduce this behavior and there does seem some related issues in the provider regarding changes to nearby attributes. This looks related to the implementation of a `CustomizeDiff` in the resource and will require further investigation to account for cases where the configuration block is removed; in the meantime, the workaround you provided is a good alternative to ensure differences are shown as expected.

**Comment by jbigtani** [comment]
#12334 is for changes in LSI
#14776 is for changes in GSI
#15124 is for changes in PITR (this one)

**Comment by anGie44** [comment]
Ahh "related" in the sense of the behavior 😅 , such that Terraform does not show changes at `plan` time, not necessarily the attribute in question

**Comment by YakDriver** [comment]
The crux of @jbigtani's question is, "Why isn't TF giving a diff when I remove the `point_in_time_recovery` argument?"

This issue can be closed because the behavior jbigtani noticed is as expected. The `point_in_time_recovery` argument does not have a default value and is `computed` and `optional`. This means, for example, when creating a new table, if you do _not_ include `point_in_time_recovery` in the configuration, TF will do nothing -- not mention PITR to AWS at all. AWS will do whatever it does in the absence of PITR info (PITR is not enabled). Since there is no default and PITR is `computed`/`optional`, removing the argument from the configuration is sort of like coverting `point_in_time_recovery` to a read-only attribute. You're saying, "don't manage PITR but tell me about it." Since TF is not going to manage it, no diffs are generated.

The workaround mentioned is actually not a workaround but the correct way to change `point_in_time_recovery`:

```terraform
point_in_time_recovery {
  enabled = false
}
```
