### ISSUE TITLE
resource/aws_app_cookie_stickiness_policy: Do not return error from Delete when resource not found

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15781]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When trying to delete a resource, we should not treat it as an error if the resource has already been deleted. In Terraform 0.12 and 0.13, this is not a problem, since state is refreshed and the resource is removed from state by the Read function. Starting with Terraform 0.14, the Read function is not called for resources removed from the configuration.

### Affected Resource

* aws_app_cookie_stickiness_policy

**Comment by bflad** [comment]
While this should still get fixed from a code correctness standpoint, I've dropped the `terraform-0.14` label since Terraform 0.14.0-beta2 still implements refresh before deletion. The out of band deletion and resource refresh without error testing is handled by disappears acceptance testing, so this only leaves this problem for race conditions where refresh doesn't occur automatically (may not be a thing after 0.14?) or due to an error in Terraform CLI ordering handling which should be filed as bug (e.g. if deposed instance handling doesn't refresh like it didn't previously as seen in https://github.com/terraform-providers/terraform-provider-aws/issues/12900).

**Comment by bflad** [comment]
Created a meta-tracking issue: https://github.com/terraform-providers/terraform-provider-aws/issues/15945
