### ISSUE TITLE
Include NLB private IP address list as output

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform-provider-aws#15920]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When defining a security group for a load balancer target group endpoint (EC2 for example), I want to be able to prevent access from anything except the load balancer. This is easy with an application load balancer: make sure the security group the ALB is linked to is allowed ingress into the security group of the EC2.

However, this is not possible with a network load balancer. What you can do is define the EC2 security group to limit CIDRs, but without the IP addresses, you're limited to the whole VPC CIDR. But it is possible to discover the IPs by querying for the ENIs of the load balancer based on the lb name (see reference below). It would be great if these IPs are available as output attributes.

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
aws_lb foo { }

aws_security_group foo {
  ingress {
    cidr_blocks = aws_lb.foo.primary_private_ip_addresses
  }
}
```

### References

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html#target-security-groups

* #0000

**Comment by ewbankkit** [comment]
@richardgavel Thanks for raising this issue.
Since [v3.1.0](https://github.com/terraform-providers/terraform-provider-aws/pull/11404) the [`subnet_mapping.private_ipv4_address`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#private_ipv4_address) attribute contains the NLB's ENI IP address(es). You should then be able to use a `for_each` t flatten to a list of strings. See for example https://www.terraform.io/docs/configuration/functions/flatten.html#flattening-nested-structures-for-for_each.

**Comment by bill-rich** [comment]
Thanks @ewbankkit for finding the solution!
