### ISSUE TITLE
Random password is shown in plan for elastikbeanstalk environment setting

### ISSUE THREAD

**Issue by jochenrichter** [hashicorp/terraform-provider-aws#15935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws v3.12.0

### Terraform Configuration Files

```hcl
resource "aws_elastic_beanstalk_application" "tftest" {
  name        = "tf-test-name"
  description = "tf-test-desc"
}

resource "aws_elastic_beanstalk_environment" "tfenvtest" {
  name                = "tf-test-name"
  application         = aws_elastic_beanstalk_application.tftest.name
  solution_stack_name = "64bit Amazon Linux 2018.03 v2.9.11 running PHP 7.3"

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "IamInstanceProfile"
    value     = "aws-elasticbeanstalk-ec2-role"
  }
  setting {
    namespace = "aws:elasticbeanstalk:application:environment"
    name      = "password"
    value     = random_password.password.result
  }
}

resource "random_password" "password" {
  length = 16
  keepers = {
    uuid = uuid()
  }
}
```

### Expected Behavior

A senstive value is expected for the value because random password was used.
    - setting {
          - name      = "password" -> null
          - namespace = "aws:elasticbeanstalk:application:environment" -> null
          - value     = (sensitive value) -> null
        }
      + setting {
          + name      = "password"
          + namespace = "aws:elasticbeanstalk:application:environment"
          + value     = (known after apply)
        }
### Actual Behavior

The password is shown in cleartext. 
We are using automatic pipelines and a lot of people are able to see the output of terraform plan.
The login to aws is restricted to only a few people.

     - setting {
          - name      = "password" -> null
          - namespace = "aws:elasticbeanstalk:application:environment" -> null
          - value     = "JGc3YdIi>#sZ" -> null
        }
      + setting {
          + name      = "password"
          + namespace = "aws:elasticbeanstalk:application:environment"
          + value     = (known after apply)
        }

### Steps to Reproduce

 For the first run everthing is ok because the password is not generated during first run.
If the elasticbeanstalk environment already exists and there is a change either for the password or any other setting, the password will be shown in cleartext
1. `terraform apply`
1. `terraform plan`

**Comment by ryanpodonnell1** [comment]
I can take a stab at this

**Comment by ryan-neff** [comment]
@bill-rich I think I can tackle this if possible. Which schema would you prefer I add a sensitive flag to? Or would you rather prefer and additional `sensitive_setting` field on the`resourceAwsElasticBeanstalkEnvironment` schema?

**Comment by ryan-neff** [comment]
Can we get any input from the maintainers on this one?

**Comment by bflad** [comment]
Hi folks 👋  Passing through attribute sensitivity in Terraform has been a longstanding feature request. To provide some background on this issue, I'll explain the current situation and recently available functionality in this regard.

Terraform Providers, such as the Terraform AWS Provider, currently only have the option (via the Terraform Plugin SDK) to fully enable or fully disable the sensitivity of individual schema attributes. Searching for `Sensitive: true` in the codebase can yield some examples of these implementations. Provider developers must choose between always hiding specific attribute values for all usage and operators or not at all.

In some cases, the choice of whether something should be marked "sensitive" is fairly trivial -- these include fields containing credentials, passwords, and other secret material. In this case though, due to the generic API schema for Elastic Beanstalk Application settings and their values, it becomes configuration and environment specific. Marking the `value` attribute as sensitive means that all configurations and all settings values for all operators will not show in Terraform plan outputs. Since there are plenty of non-sensitive values that operators would appreciate still being able to see, we have to choose between the user experience.

Luckily though, there has been some very good movement towards how sensitive values are handled in Terraform overall. The recent [Terraform 0.14 Adds the Ability to Redact Sensitive Values in Console Output](https://www.hashicorp.com/blog/terraform-0-14-adds-the-ability-to-redact-sensitive-values-in-console-output) blog post outlines some of the new behaviors and functionality possible in Terraform 0.14 (which had its first [general availability release](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-general-availability) yesterday 🎉 ). Configurations can mark variables as sensitive and this behavior will "flow" through all usage in the Terraform plan.

Another piece of this new functionality is the ability to enable it so Terraform CLI respects Terraform Provider attribute defined sensitivity also through all usage in the Terraform plan. Since the `hashicorp/random` provider `random_secret` resource marks the `result` attribute as sensitive, Terraform can hide its plan output in other places.

Here's an example end-to-end configuration that can show this in action:

```terraform
terraform {
  experiments      = [provider_sensitive_attrs]
  required_version = ">= 0.14.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.19.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.0.0"
    }
  }
}

provider "aws" {
  region = "us-east-2"
}

data "aws_elastic_beanstalk_solution_stack" "test" {
  most_recent = true
  name_regex  = "^64bit Amazon Linux (.*) Go (.*)$"
}

resource "random_password" "test" {
  length = 16
}

resource "aws_elastic_beanstalk_application" "test" {
  name = "15935-test"
}

resource "aws_elastic_beanstalk_environment" "test" {
  name                = "15935-test"
  application         = aws_elastic_beanstalk_application.test.name
  solution_stack_name = data.aws_elastic_beanstalk_solution_stack.test.name

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "IamInstanceProfile"
    value     = "aws-elasticbeanstalk-ec2-role"
  }
  setting {
    namespace = "aws:elasticbeanstalk:application:environment"
    name      = "password"
    value     = random_password.test.result
  }
}
```

And showing what it does:

```console
$ terraform init
$ terraform apply -target=random_password.text # just so its value is known and not (known after apply)
$ terraform plan
random_password.test: Refreshing state... [id=none]
aws_elastic_beanstalk_application.test: Refreshing state... [id=15935-test]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_elastic_beanstalk_environment.test will be created
  + resource "aws_elastic_beanstalk_environment" "test" {
      + all_settings           = (known after apply)
      + application            = "15935-test"
      + arn                    = (known after apply)
      + autoscaling_groups     = (known after apply)
      + cname                  = (known after apply)
      + cname_prefix           = (known after apply)
      + endpoint_url           = (known after apply)
      + id                     = (known after apply)
      + instances              = (known after apply)
      + launch_configurations  = (known after apply)
      + load_balancers         = (known after apply)
      + name                   = "15935-test"
      + platform_arn           = (known after apply)
      + queues                 = (known after apply)
      + solution_stack_name    = "64bit Amazon Linux 2018.03 v2.17.1 running Go 1.15.4"
      + tier                   = "WebServer"
      + triggers               = (known after apply)
      + version_label          = (known after apply)
      + wait_for_ready_timeout = "20m"

      + setting {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.


Warning: Experimental feature "provider_sensitive_attrs" is active

  on main.tf line 2, in terraform:
   2:   experiments      = [provider_sensitive_attrs]

Experimental features are subject to breaking changes in future minor or patch
releases, based on feedback.

If you have feedback on the design of this feature, please open a GitHub issue
to discuss it.
```

Given the history of previous Terraform CLI experiments, its possible that this will become enabled by default in Terraform 0.15 unless there is a large amount of feedback, which can be [submitted upstream](https://github.com/hashicorp/terraform/issues).

I will confer with the other maintainers, but I think that we may opt to leave this as-is in this particular resource schema to keep the full plan user experience for configurations that are not including sensitive values. It is also possible there will be other enhancements in this area, outside this particular codebase in the Terraform Plugin SDK or Terraform CLI, based on the feedback to the sensitive values experiment.
