### ISSUE TITLE
cognito identity pool / user pool: app client IDs not available to reference in code

### ISSUE THREAD

**Issue by nnovaes** [hashicorp/terraform-provider-aws#15972]
I'm using terraform to create an AWS elasticsearch domain with advanced_security_options enabled. The domain is created and i point it to terraform provisioned user_pool and identity_pool. However, i would like to use the app client ID that is created by the elasticsearch resource to map roles inside identify pool's authentication provider. to my knowledge, that is not available and can't be reference in code.

when provisioned the AWS ES should make available the app client id it creates (meaning this is would need to be fixed on  aws_elasticsearch_domain OR i should be able to reference app client IDs from the aws_cognito_user_pool/aws_cognito_identity_pool resources...

...therefore, when creating a aws_cognito_identity_pool_roles_attachment i could set the value of identity_provider under role mapping.

i'm pasting only the relevant pieces of code

```

resource "aws_elasticsearch_domain" "esdomain" {

...

  #SECURITY and FINE-GRAINED ACCESS CONTROL
  advanced_security_options {
    enabled = true
    master_user_options {
      master_user_arn = "${aws_iam_role.AWS_IHS_Automated_GN-Syslog-iamr-gnlaprodsme.arn}"

    }
  }

  // this must be enabled for fine-grained access control
  cognito_options {
    enabled          = true
    user_pool_id     = "${aws_cognito_user_pool.cogusamea-GN-syslog-cup.id}"
    identity_pool_id = "${aws_cognito_identity_pool.cogusamea-GN-syslog-cip.id}"
    role_arn         = "${aws_iam_role.AWS_IHS_Automated_GN-Syslog-iamr-cognitoAccess.arn}"

  }
...
```

```
...
resource "aws_cognito_identity_pool_roles_attachment" "AWS_IHS_Automated_GN-Syslog-cipra-gnlaprodnwuser" {
  identity_pool_id = aws_cognito_identity_pool.cogusamea-GN-syslog-cip.id

  role_mapping {
    identity_provider         = "cognito-idp.${var.gn_loganalytics_defaultRegion}.amazonaws.com/${aws_cognito_identity_pool.cogusamea-GN-syslog-cip.id}:${var.gn_loganalytics_appClientId}"
    ambiguous_role_resolution = "Deny"
    type                      = "Rules"

 ...
```

**Comment by bdellegrazie** [comment]
This is something we're struggling with as well. Looking at the API for AWS Elasticsearch, it doesn't look as though this information is presently available.

**Comment by awuetz** [comment]
Hello,

did someone have another solution which is currently working, other than a variable?

**Comment by bdellegrazie** [comment]
@awuetz : we used a "bootstrap" variable and explicitly recorded the ID in the terraform vars - it's the best we could do under the circumstances.

**Comment by keitharogers** [comment]
We've run into this same issue. I can see that the app client ID is returned on an AWS CLI call.

Does anyone know when / if this feature will be made available in Terraform? I'm making the assumption it's now available in the AWS APIs due to the AWS CLI tool retrieving it successfully, though I appreciate that maybe it's utilising a different method to do so.

**Comment by danquack** [comment]
@nnovaes I believe this may be related or duplicate of #9139, which is now resolved. Can you confirm?

**Comment by keitharogers** [comment]
@danquack : Thanks for this, it looks like it could be the answer but as it hasn't been released yet, I'm unable to test. Do you know when `3.71.0` of the AWS provider module will be available? I assume last Thursday's release didn't happen due to the holidays.

**Comment by danquack** [comment]
> Do you know when 3.71.0 of the AWS provider module will be available? 

@ewbankkit can you speak to this?

**Comment by keitharogers** [comment]
@danquack : It only got released last night (according to Github at least) (bear in mind, I'm also in the UK).

Thanks for your efforts on this. I've implemented your datasource and pulled down the list of ID's but unfortunately I don't think this is going to solve the problem for us. Reason being, we've told Amazon Elasticsearch to use an existing Cognito user pool, so it automagically creates an App Client within that user pool but then doesn't expose an attribute on the `aws_elasticsearch_domain` datasource that you can use to pull down the ID.

When I use your new datasource to pull down the ID's from an existing user pool, I get a list of ID's but I have no way to determine from that list which is the correct app ID to use (i.e. the one created by the `aws_elasticsearch_domain` resource).

If the new datasource returned the `ClientName` along with the ID, then we could probably do some filtering to match on this and make sure it uses the correct one but as it stands, it won't work in our use case.

If I run `aws opensearch describe-domain-config --domain-name <our_domain>` I get back all the config for it but the config *does not* show any reference to the app client ID that the Elasticsearch/Opensearch service automagically creates in our user pool. So I suspect this is an oversight in that the AWS API just isn't returning complete data and as such the Terraform provider won't be able to either (which I think someone else alluded to before).

So unless I've missed something or anyone else on this thread has anything to add, I would suggest this issue is probably still relevant but I doubt it'll be able to be fixed until AWS implement it in their APIs.

**Comment by danquack** [comment]
I opened up a PR that will allow you to lookup the client by id. This is extensible to other use cases, but then allows you to do additional filtering from the output of the remaining attributes.

**Comment by keitharogers** [comment]
@danquack : Wow, this looks like it'll do the trick. Thanks for taking the time to do this !

Once it's released, I'll get it tested and feedback on this issue with my findings :-)
