### ISSUE TITLE
Cannot deploy lambda and db instance on aws

### ISSUE THREAD

**Issue by eXist-FraGGer** [hashicorp/terraform-provider-aws#16274]
Hello. I've got an issue with my terraform apply. Reproducing my steps:
1. Configure all tf files correctly
2. Run terraform plan(plan create tfplan file correctly with all resources)
3. Then run terraform apply and got very strange issue. As your can see on screenshot, my db instance started to create, but that's all. No errors in console and TF_LOG file, just nothing. All depends_on resources already deployed on aws
4. Because of this, I cannot  deploy lambdas, because they depends on db instace.
So, what can i do to fix it? Where problem can be? If you need more screens or information about my configuration plz tell me about it. Hope on your answers!
![Снимок экрана от 2020-11-18 16-52-17](https://user-images.githubusercontent.com/13423093/99538803-8497d480-29be-11eb-886d-26220a33b881.png)

**Comment by gdavison** [comment]
Hi @eXist-FraGGer.

Does your Terraform execution stop responding, or does it complete? Some resources, including databases with large capacity, can take a long time to deploy. Normally, Terraform will output `Still creating...` and how long it's been waiting; do you see any of that?

It is a lot easier to debug issues with a configuration and actual output instead of a screen shot. Could you include those, please?
