### ISSUE TITLE
Documentation for s3_account_public_access_block import action incorrect

### ISSUE THREAD

**Issue by mbacchi** [hashicorp/terraform-provider-aws#16287]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The documentation for the `s3_account_public_access_block` resource [import action](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_account_public_access_block#import) is incorrect. It states that you can use the AWS Account ID as the 2nd argument, but this does not work, rather the bucket name must be provided in this location.

If I provide the AWS Account ID in this location, it returns the error:

```
TF_LOG=1 terraform import aws_s3_bucket_public_access_block.example 123456789012
...
2020-11-18T12:00:51.963-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: 	status code: 404, request id: NOTREAL, host id: NOTREAL=
2020-11-18T12:00:51.963-0500 [DEBUG] plugin.terraform-provider-aws_v2.35.0_x4: 2020/11/18 12:00:51 [WARN] S3 Bucket (123456789012) not found, removing from state
...
Error: Cannot import non-existent remote object
```

But if I run the import with the bucket name it does work:

```
terraform import aws_s3_bucket_public_access_block.example example
...
Import successful!

The resources that were imported are shown above.
```

The documentation must be corrected to indicate that the bucket name must be used as the 2nd argument to the import action.

**Comment by gdavison** [comment]
Hi @mbacchi, sorry for the confusion.

`aws_s3_account_public_access_block` is imported using the account id (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_account_public_access_block#import), since it specifies the default settings for the whole account.

However, in your example you're using `aws_s3_bucket_public_access_block` which is associated with a specific bucket, and is therefore imported using the bucket name (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block#import).
