### ISSUE TITLE
aws_ram_principal_association doesn't support AWS Organizations Organization ARN, or an AWS Organizations Organization Unit ARN.

### ISSUE THREAD

**Issue by jihed** [hashicorp/terraform-provider-aws#16321]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ram_principal_association

### Terraform Configuration Files

```hcl
#"arn:aws:organizations::12345678910:ou/o-XXXXXXXX/ou-XXXXXXXXXX" 
ram_principals   = [data.aws_organizations_organizational_units.ou.children.2.arn]

resource "aws_ram_principal_association" "this" {
  count = length(var.ram_principals) 

  principal          = var.ram_principals[count.index]
  resource_share_arn = aws_ram_resource_share.this[0].arn
}


```

### Expected Behavior

Create the resource ram principal association with OU arn.

### Actual Behavior

It was failed to apply: 

```bash

Error: Error associating principal with RAM resource share: UnknownResourceException: OrganizationalUnit ou-XXXX-XXXXXXXX in unknown organization could not be found.

```

### Steps to Reproduce

1. `terraform apply`

### References

* #7632

**Comment by ricardo-trevizo-b** [comment]
Ensure you have manually enabled RAM sharing within [**RAM** console](https://console.aws.amazon.com/ram/home#Settings), this is different from the Organizations + RAM integration.

```
To enable sharing with AWS Organizations (Console)

Open the Settings page of AWS RAM console at https://console.aws.amazon.com/ram/home#Settings.

Choose Enable sharing with AWS Organizations.
```
[Source from aws docs](https://docs.aws.amazon.com/ram/latest/userguide/getting-started-sharing.html#getting-started-sharing-orgs)

**Comment by jihed** [comment]
@ricardo-trevizo-b that's to enabled by default without having RAM invitation.

**Comment by dcernag** [comment]
I'm seeing the same issue as described above (with RAM  Org share enabled manually in RAM console)

I'm not completely convinced this is a provider issue as I see the same behavior while creating RAM share in the console. so i've contacted AWS support to get some more info on this. Will try to share the findings here once they respond in case it helps.

It's worth noting that we have strict org SCPs (ram is whitelisted).

**Comment by dcernag** [comment]
This was not a problem with the provider as first suspected.

It looks like we had the correct configuration after all, but AWS support mentioned the error usually happens when you enable RAM from the Organization web console instead of the RAM console, and the `AWSServiceRoleForResourceAccessManager` role is not created (RAM needs it to verify the Org information).

This is extremely weird as we enabled it from the CLI and the RAM console at first and didn't work for us, but re-enabling it did the trick:

1. Login to your master AWS account as root user.
2. Go to the Organizations console and click 'Settings'
3. 'Disable Access' for AWS Resource Access Manager from the 'Trusted access for AWS services' tab
4. Go to the RAM console, and Click on Settings.
5. Select  “Enable sharing within your AWS Organization”. 
6. Run tf again with `allow_external_principals` set to false for `aws_ram_resource_share`

Hope it helps someone facing this issue.

**Comment by breathingdust** [comment]
Thanks @dcernag for the update! As this wasn't a provider issue I will close it.
