### ISSUE TITLE
aws_eks_cluster_auth token is invalid

### ISSUE THREAD

**Issue by weberc2-tempus** [hashicorp/terraform-provider-aws#16320]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.29
+ provider.aws v3.16.0
+ provider.kubernetes v1.13.3

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* `data.aws_eks_cluster_auth`

### Terraform Configuration Files

```hcl
provider "aws" {
  version = ">= 3.16"
  region  = module.environment.region

  assume_role {
    role_arn     = local.role_arn
    session_name = local.session_name
  }
}

data "aws_eks_cluster" "this" {
  name = local.cluster_name
}

data "aws_eks_cluster_auth" "this" {
  name = local.cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
  load_config_file       = false
  token                  = data.aws_eks_cluster_auth.this.token
}

resource "kubernetes_service_account" "service_account" {
  metadata {
    name      = local.service_account_name
    namespace = local.service_account_namespace
    annotations = {
      "eks.amazonaws.com/role-arn" = local.service_account_role_arn
    }
  }
}
```

### Expected Behavior

`terraform apply` should have authenticated correctly with my cluster and created my resource.

### Actual Behavior

Returned `Error: Unauthorized` when trying to create my Kubernetes service account resource.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running `tf show -json | jq -r '.values.root_module.resources | .[] | select(.address == "data.aws_eks_cluster_auth.this") | .values.token'` yields a different value than `kubectl get secrets -o jsonpath=
"{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='default')].data.token}"|base64 --decode`. The latter allows me to auth correctly (confirmed via `curl -X GET $APISERVER/api --header "Authorization: Bearer $TOKEN" --insecure`) while the former doesn't.

Note that the token from the `aws_eks_cluster_auth` begins with `k8s-aws-v1.` while the correct token doesn't have any special prefix.

**Comment by agseijas** [comment]
Maybe you have an IAM issue, the role which created the eks cluster is not the same you're using in the apply, keep an eye on the assumed_role in the provider "aws" block

**Comment by rmendal** [comment]
This issue is also biting us. If I create a cluster and a coworker tries to modify it they will get `Error: Unauthorized`. We're both aws admins and can do anything within the account. 

I have an assumable role created and mapped to the `aws-auth` configmap in the cluster and assuming the role then trying to `terraform plan/apply` doesn't help. We have the role defined in our kube config for this context and have also tried the stuff in the `Assume Role with Profile` section of [this](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_profiles.html).

Can also confirm the discrepancy in tokens noted by the op.

**Comment by JacobJohansen** [comment]
create an alias for the aws provider and then reference it in your get access code

```
provider "aws" {
  version = ">= 3.16"
  region  = module.environment.region
  alias = kube

  assume_role {
    role_arn     = local.role_arn
    session_name = local.session_name
  }
}

data "aws_eks_cluster" "this" {
  name = local.cluster_name
}

data "aws_eks_cluster_auth" "this" {
  provider = aws.kube
  name = local.cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
  load_config_file       = false
  token                  = data.aws_eks_cluster_auth.this.token
}

resource "kubernetes_service_account" "service_account" {
  metadata {
    name      = local.service_account_name
    namespace = local.service_account_namespace
    annotations = {
      "eks.amazonaws.com/role-arn" = local.service_account_role_arn
    }
  }
}
```

**Comment by reschenburgIDBS** [comment]
@JacobJohansen saying "create an alias" is not helpful unless there is any indication that the original problem is due to the wrong role/credentials being used.

My terraform code is executed by the same user/IAM credentials which are creating the EKS cluster in the first place, so should have implicit permissions - yet I'm getting the same `Error: Unauthorized` or `[...] User "system:anonymous" cannot get resource [...]`, so creating an alias does not make any difference. 

I'm still experimenting, as I'm not 100% sure this is linked to the `data.aws_eks_cluster_auth` resource, but have a feeling that it has to do with the kubernetes provider, some version after  v1.9.0. as I've been upgrading my aws provider regularly, but only started to run into this problem after upgrading the k8s provider.

I've also tried to generate the token using the external provider or the exec {} block of the newer k8s provider - so far without much success. In fact, I'm at the point where I'm about to remove any k8s resources from terraform because of this issue and it's sad because of how convenient it was to have.

**Comment by reschenburgIDBS** [comment]
for my issue, I seem to be able to break authentication by upgrading the kubernetes provider to > 1.9.0, using the latest aws provider. I'll go raise an issue over there instead..

**Comment by rmendal** [comment]
After the fact, our work around at the time was to create a service account and that manage creation, modification, deletion of clusters. This isn't so much a terraform module issue (AWS or k8s) as it is a strictly AWS issue where only the cluster creator is able to change/delete it.
