### ISSUE TITLE
data.aws_workspaces_bundle incorrectly returns compute_type, root_storage, and user_storage as lists

### ISSUE THREAD

**Issue by dthvt** [hashicorp/terraform-provider-aws#16396]
The aws_workspaces_bundle incorrectly constructs a list for the compute_type, root_storage, and user_storage values.  These values are structs, not lists, per the API.  https://docs.aws.amazon.com/workspaces/latest/api/API_DescribeWorkspaceBundles.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
+ provider registry.terraform.io/hashicorp/vault v2.16.0

### Affected Resource(s)

* data.aws_workspaces_bundle

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_workspaces_bundle" "main" {
  bundle_id = "wsb-8vbljg4r6"
}

output "bundle" {
  value = data.aws_workspaces_bundle.main
}
```

### Debug Output

```
data.aws_workspaces_bundle.main: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

bundle = {
  "bundle_id" = "wsb-8vbljg4r6"
  "compute_type" = [
    {
      "name" = "STANDARD"
    },
  ]
  "description" = "Windows 10 Experience provided by Windows Server 2016 with PCoIP 2 vCPU 4GiB Memory 50GB Storage"
  "id" = "wsb-8vbljg4r6"
  "name" = "Standard with Windows 10"
  "owner" = "Amazon"
  "root_storage" = [
    {
      "capacity" = "80"
    },
  ]
  "user_storage" = [
    {
      "capacity" = "50"
    },
  ]
}

```

### Expected Behavior

Retrieved data should be structed as:

```
bundle = {
  "bundle_id" = "wsb-8vbljg4r6"
  "compute_type" = {
    "name" = "STANDARD"
  }
  "description" = "Windows 10 Experience provided by Windows Server 2016 with PCoIP 2 vCPU 4GiB Memory 50GB Storage"
  "id" = "wsb-8vbljg4r6"
  "name" = "Standard with Windows 10"
  "owner" = "Amazon"
  "root_storage" = {
    "capacity" = "80"
  }
  "user_storage" = {
    "capacity" = "50"
  }
}
```

### Actual Behavior

See output in example above.

### Steps to Reproduce

1. `terraform apply`

### References

* https://docs.aws.amazon.com/workspaces/latest/api/API_DescribeWorkspaceBundles.html

**Comment by bflad** [comment]
Hi @dthvt 👋  Thank you for raising this.

The [Terraform Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk), which defines the data model supported by HashiCorp Terraform Provider resources and their attributes, does not exactly support the proposed expected behavior for data modeling right now†. There is a long history in Terraform about why this is the case dating back to way before the SDK was split off from the core Terraform codebase (blocks versus attributes, if you are looking for the details). While we could theoretically implement this as a map with string keys and string values, since that is what the SDK does support in this case, that would represent a departure from how this type data is represented in the Terraform AWS Provider since typically we want more the more data rich types for the values (numbers, sets, lists, maps, deeper objects, etc). Changing this here would potentially cause issues in the future should those structures include additional data.

There is some forward looking work with [this recent announcement](https://www.hashicorp.com/blog/making-terraform-provider-development-more-accessible), but implementing full fledged resources and data sources with all the behaviors similar to the existing Terraform Plugin SDK is far off at this time and not applicable yet. If/when the new provider development framework matures into a more usable model for us, we can revisit this.

For now, continue to expect that where attributes will be coming back as a "structure" type (usually the documentation should be denoting these as "nested attributes" or "list/set of nested attributes"), that it will be represented as a list/set of objects.

† We could theoretically mark these attributes as a dynamic type, but this support is experimental in the existing Terraform Plugin SDK and removes many of the validations expected in configuration planning.

**Comment by dthvt** [comment]
Hmm, thanks for the thorough reply.  I didn't realize it was driven by an underlying terraform SDK design decision.  Thanks!
