### ISSUE TITLE
Terraform Concurrency Scaling Redshift Cluster (Parameter group) . We have created a TF module with "parameter {         name  = "max_concurrency_scaling_clusters"         value = "1"       }" even after apply these changes in the redshift cluster still concurrency scale id not enabled . 

### ISSUE THREAD

**Issue by t15kwic** [hashicorp/terraform-provider-aws#16409]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @t15kwic 👋  Thank you for opening this and sorry you are running into trouble here.

I am guessing you may have had trouble with the GitHub issue interface since the issue description is not filled in, however the maintainers here will need all the details requested to help troubleshoot your issue. Please open a new GitHub issue, filling in the requested information in the template including your configuration and the behaviors you are seeing, then we will be happy to take a look.
