### ISSUE TITLE
Terraform fails to alter subnet group if target subnets are in different VPC

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform-provider-aws#16419]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.17.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
```

### Affected Resource(s)

* aws_db_subnet_group

### Expected Behavior
Provider fails to alter db subnet group when target subnets are in different VPC. Provider should behave more smart and instead of attempting to change subnet group, destroy and recreate it according to the error message below

### Actual Behavior

Getting error:
```
Error: InvalidParameterValue: The new Subnets are not in the same Vpc as the existing subnet group
        status code: 400
```
### Steps to Reproduce

- Declare a subnet group resource
- Run terraform apply
- Change subnet IDs to one located in another VPC
- Run terraform apply

**Comment by bflad** [comment]
Hi @vladimirtiukhtin 👋  Thank you for raising this.

While this is a reasonable ask on the surface, there are some details about this particular case where we would shy away from introducing the extra logic necessary into the Terraform AWS Provider resource due to the higher chances of bugs or unexpected behaviors:

* The ability to potentially trigger the resource recreation requires using `CustomizeDiff` and this type of logic requires that all values incoming must be known to show a proper plan showing that resource recreation
* If the values are _not_ known until apply, the resource can potentially trigger recreation unexpectedly, which is different than the plan. This can trigger Terraform CLI errors about unexpected provider behavior.
* The lookup to determine the EC2 VPC associated with the EC2 Subnet is cross-service and in the codebase we try very hard to avoid these types of lookups as they may introduce unexpected operational issues in environments with restrictive IAM permissions or customized endpoints.
* From my previous operations experience, RDS Subnet Groups that have associated DB Instances cannot be deleted until they are unused since they can have active ENIs, which in many cases would not be caught at the right time and introduce more complexity to try and handle.

Generally in many cases due to the above, it is preferable to create new RDS DB Subnet Groups rather than trying to attempt in-place replacement. Using the `lifecycle` configuration block `create_before_destroy` argument may help alleviate some of these issues, but given the potential trouble here, I think we are going to opt out of making this change. In Terraform environments that require this type of change, the `terraform taint` command can be used to manually trigger the resource for recreation instead of update.

For maintainer reference, I was able to reproduce this with the following acceptance testing:

```go
func TestAccAWSDBSubnetGroup_SubnetIds_NewVpc(t *testing.T) {
	var v rds.DBSubnetGroup
	resourceName := "aws_db_subnet_group.test"
	rName := acctest.RandomWithPrefix("tf-acc-test")

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckDBSubnetGroupDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccDBSubnetGroupConfig_SubnetIds_NewVpc1(rName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckDBSubnetGroupExists(resourceName, &v),
				),
			},
			{
				Config: testAccDBSubnetGroupConfig_SubnetIds_NewVpc2(rName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckDBSubnetGroupExists(resourceName, &v),
				),
			},
		},
	})
}

func testAccDBSubnetGroupConfig_SubnetIds_NewVpc1(rName string) string {
	return composeConfig(
		testAccAvailableAZsNoOptInConfig(),
		fmt.Sprintf(`
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_subnet" "test" {
  count = 2

  cidr_block        = cidrsubnet(aws_vpc.test.cidr_block, 8, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  vpc_id            = aws_vpc.test.id

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_db_subnet_group" "test" {
  name       = %[1]q
  subnet_ids = aws_subnet.test[*].id
}
`, rName))
}

func testAccDBSubnetGroupConfig_SubnetIds_NewVpc2(rName string) string {
	return composeConfig(
		testAccAvailableAZsNoOptInConfig(),
		fmt.Sprintf(`
resource "aws_vpc" "test" {
  cidr_block = "10.1.0.0/16"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_subnet" "test" {
  count = 2

  cidr_block        = cidrsubnet(aws_vpc.test.cidr_block, 8, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  vpc_id            = aws_vpc.test.id

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_db_subnet_group" "test" {
  name       = %[1]q
  subnet_ids = aws_subnet.test[*].id
}
`, rName))
}
```

```
=== CONT  TestAccAWSDBSubnetGroup_SubnetIds_NewVpc
    resource_aws_db_subnet_group_test.go:210: Step 2/2 error: Error running apply: 2020/11/25 15:59:07 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0

        Error: InvalidParameterValue: The new Subnets are not in the same Vpc as the existing subnet group
        	status code: 400, request id: 40d683f2-f135-4aef-8f60-d8d76bb88e16


--- FAIL: TestAccAWSDBSubnetGroup_SubnetIds_NewVpc (37.97s)
```
