### ISSUE TITLE
[bug] data.aws_subnet_ids: existing resources are not enumerated at plan stage

### ISSUE THREAD

**Issue by technotaff-nbs** [hashicorp/terraform-provider-aws#16450]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Terraform Version: v0.13.5
AWS Provider Version: v3.18.0**

### Affected Resource(s)

```
data.aws_subnet_ids
data.aws_subnet (consuming data.aws_subnet_ids list) 
```

### Terraform Configuration Files

```hcl
data "aws_subnet_ids" "intra_subnet_ids" {
  vpc_id = var.vpc_id

  filter {
    name   = "tag:Name"
    values = ["${var.account_name}-intra*"]
  }
}

data "aws_subnet" "intra_subnets" {
  for_each = data.aws_subnet_ids.intra_subnet_ids.ids
  id       = each.value
}
```

### Panic Output
data/aws_subnet: for_each on aws_subnet_ids causes "value depends on resource attributes that cannot be determined" error:
```
Error: Invalid for_each argument

  on .terraform/modules/eks-epaas.eks-custom-vpc-cni/modules/eks-custom-vpc-cni/data.tf line 17, in data "aws_subnet" "intra_subnets":
  17:   for_each = data.aws_subnet_ids.intra_subnet_ids.ids

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

### Expected Behavior

A list of data.aws_subnet should have been created based on the filtered data.aws_subnet_ids list. The VPC and subnets already exists at the time the TF is planned/applied.

Plan and Apply stages fail

### Actual Behavior

Terraform reports that the resources cannot be determined  until apply, even though the resources already exist.

### Steps to Reproduce

1. Create code as above, passing VPC id and internal name as a variables.
1. `terraform apply`

**Comment by bflad** [comment]
Hi @technotaff-nbs 👋  Thank you for filing this and sorry you ran into trouble here.

This is very related to https://github.com/hashicorp/terraform-provider-aws/issues/16437, which was closed with the same response that is applicable here as well (and why I'm closing this):

The resources and data sources in Terraform AWS Provider codebase have little control over this particular behavior since it relates to the operation graph handling that is performed within the Terraform CLI codebase. Your best bet is to create an issue in that repository so that the people familiar with that handling can potentially triage this issue: https://github.com/hashicorp/terraform/issues

My best guess is that this is likely fixed in the upcoming Terraform 0.14 release since it better integrates data sources into the graph. The upstream maintainers would know best though. There is the Terraform 0.14.0-rc1 prerelease available if you have a development or test environment where you could potentially try that out.

There was a [Terraform CLI issue filed and responded to](https://github.com/hashicorp/terraform/issues/27044), which may provide some additional insight. You may want to chime in there or create a new issue in that repository. 👍
