### ISSUE TITLE
Data Source: aws_partition documentation not accurate

### ISSUE THREAD

**Issue by jevon71-work** [hashicorp/terraform-provider-aws#16464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_partition

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

data "aws_partition" "current" {}

data "aws_iam_policy_document" "s3_policy" {
  statement {
    sid = "1"

    actions = [
      "s3:ListBucket",
    ]

    resources = [
      "arn:${data.aws_partition.current.id}:s3:::my-bucket",
    ]
  }
}
```

### Expected Behavior

According to the [Attributes Reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/partition#attributes-reference), `id` and `partition` should provide the same values.

### Actual Behavior

`id` provided a date and time stamp and not the desired `aws` or `aws-cn` output

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by bflad** [comment]
Hi @jevon71-work 👋  Thank you for raising this and sorry you ran into trouble here.

Since you did not provide the Terraform AWS Provider version you are using, I cannot say for sure, but my guess is that you are using a Terraform AWS Provider older than version 3.10.0. The [value for this attribute changed](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md#3100-october-09-2020) due to some issues in Terraform CLI version 0.13 and later.

The latest version of the `aws_partition` data source (version 3.18.0 as of this writing; https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/partition) states:

> id - Identifier of the current partition (e.g. aws in AWS Commercial, aws-cn in AWS China).

While versions 3.9.0 and earlier (e.g. https://registry.terraform.io/providers/hashicorp/aws/3.9.0/docs/data-sources/partition) do not have documentation for the `id` attribute, since before it was the timestamp.

Please note you can use the versions dropdown (or adjust the URL) in the Terraform Registry documentation to switch the documentation to match your current version.

If you wish to still have time values factored into your Terraform configuration, please see the [time Provider](https://registry.terraform.io/providers/hashicorp/time/latest).
