### ISSUE TITLE
Building complete website locally

### ISSUE THREAD

**Issue by tomwerneruk** [hashicorp/terraform-provider-aws#16468]
Hi,

I'm trying to build a local copy of the terraform docs as the environment I'm in doesn't have direct internet access.

I have got the local build to work under the https://github.com/hashicorp/terraform-website repo but the aws provider is missing.

It appears the aws provider symlink doesn't exist under ext/providers/ and the terraform-provider-aws repo doesn't have an erb file in their repo if you mount it as a submodule.

In this issue - https://github.com/hashicorp/terraform-provider-aws/issues/14712 it is made reference that this is the legacy method and the docs have migrated. Is this still the right approach to build the terraform docs in completeness, or is it now in another repo?

Cheers,
Tom

**Comment by bflad** [comment]
Hi @tomwerneruk 👋  Thank you for reaching out about this. After the migration to the Terraform Registry for provider documentation, there is currently no way to run the full website locally. I will reach out to that team about any potential efforts in this area, however I do not believe there is a timeline for this right now.

**Comment by bflad** [comment]
Hi again,

I reached out to the Terraform Registry team and they noted that they are thinking about this, but have no timeline available yet. They also are thinking about ways to allow folks to create and subscribe to issues for public tracking. In the meantime though, you can reach out to them via terraform-registry@hashicorp.com to provide feedback or ask further questions. Since ultimately it would not likely be this team implementing or tracking this functionality, I think our best option here is to close this particular issue since its not necessarily actionable by us.

As an aside: we may also be able to leverage some potential functionality built on top of the provider schema itself (e.g. the output of `terraform providers schema -json`) to create a separate CLI based provider documentation tool as well. Not sure if the tooling being developed in https://github.com/hashicorp/terraform-plugin-docs may be interested.
