### ISSUE TITLE
Error: Provider produced inconsistent final plan for aws_ami_copy

### ISSUE THREAD

**Issue by grahamc** [hashicorp/terraform-provider-aws#16658]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.12.29
```

but I'm pretty sure 0.13 / 0.14 wouldn't make a difference.

### Affected Resource(s)

* `aws_ami`

### Terraform Configuration Files

```hcl
resource "aws_ami" "myami" {
  name                = "myami2"
  virtualization_type = "hvm"
  root_device_name    = "/dev/xvda"

  ebs_block_device {
    device_name = "/dev/xvda"
    snapshot_id = # pick a snapshot ID you have handy
    volume_size = 8
  }
}

resource "aws_ami_copy" "myami-regional-eu-north-1" {
  name = aws_ami.myami.name
  description = aws_ami.myami.description
  source_ami_id = aws_ami.myami.id
  source_ami_region = var.region
  tags = aws_ami.myami.tags
  provider = aws.regional-eu-north-1
}
```

### Debug Output

https://gist.github.com/grahamc/f655eaed51d11e952833db39f33644f3

### Expected Behavior

Terraform should let me refer to the description and other related fields of aws_ami from aws_ami_copy.

### Actual Behavior

```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_ami_copy.myami-regional-eu-north-1 to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .description: was null, but now
cty.StringVal("").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Thank you for reporting this, @grahamc 👍  From my first glance at this, it appears to be a subtle code issue in the `aws_ami_copy` resource here:

https://github.com/hashicorp/terraform-provider-aws/blob/7900b33d47fe9f26c0fb23f9672f3354dce7b734/aws/resource_aws_ami_copy.go#L201-L207

The `Description` field here is always being set with the value from `d.Get("description").(string)`, which will always include an empty string (`""`) if not provided in a Terraform configuration (or in this case, even if the upstream description was empty). To solve this, setting the `Description` needs to have that line removed, then immediately after doing a `d.GetOk("description")` conditional, e.g.

```go
	req := &ec2.CopyImageInput{
		Name:          aws.String(d.Get("name").(string)),
		SourceImageId: aws.String(d.Get("source_ami_id").(string)),
		SourceRegion:  aws.String(d.Get("source_ami_region").(string)),
		Encrypted:     aws.Bool(d.Get("encrypted").(bool)),
	}

	if v, ok := d.GetOk("description"); ok {
		req.Description = aws.String(v.(string))
	}
```

This will prevent a description that is an empty string or one that is not configured from unexpectedly causing an empty string to show up in the Terraform state after creation.

Looking at our testing, it seems that we are _close_ to covering this behavior, but we do not have an exact configuration including the `description = aws_ami.xxx.description` line. Adding a test and [running the acceptance testing](https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md) with this:

```go
// Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16658
func TestAccAWSAMICopy_Description_EmptyReference(t *testing.T) {
	var image ec2.Image
	rName := acctest.RandomWithPrefix("tf-acc-test")
	amiResourceName := "aws_ami.test"
	resourceName := "aws_ami_copy.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckAWSAMICopyDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccAWSAMICopyConfigDescriptionEmptyReference(rName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckAWSAMICopyExists(resourceName, &image),
					resource.TestCheckResourceAttrPair(resourceName, "description", amiResourceName, "description"),
				),
			},
		},
	})
}

func testAccAWSAMICopyConfigDescriptionEmptyReference(rName string) string {
	return composeConfig(
		testAccAWSAMICopyConfigBase(rName),
		fmt.Sprintf(`
resource "aws_ami" "test" {
  name                = "%[1]s-source"
  virtualization_type = "hvm"
  root_device_name    = "/dev/sda1"

  ebs_block_device {
    device_name = "/dev/sda1"
    snapshot_id = aws_ebs_snapshot.test.id
  }
}

resource "aws_ami_copy" "test" {
  description       = aws_ami.test.description
  name              = %[1]q
  source_ami_id     = aws_ami.test.id
  source_ami_region = data.aws_region.current.name
}
`, rName))
}
```

Was able to show the current problem:

```
=== CONT  TestAccAWSAMICopy_Description_EmptyReference
    resource_aws_ami_copy_test.go:72: Step 1/1 error: Error running apply:
        Error: Provider produced inconsistent final plan

        When expanding the plan for aws_ami_copy.test to include new values learned so
        far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
        invalid new value for .description: was null, but now cty.StringVal("").

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.

--- FAIL: TestAccAWSAMICopy_Description_EmptyReference (33.38s)
```

However applying the `aws_ami_copy` fix mentioned above did not get the testing passing. Looking upstream in the `aws_ami` resource, it appeared to also need the same fix applied. However, applying both these fixes still does not get the test passing (and ultimately the original issue resolved).

I'm out of timeboxed time to look into this further due to other pending priorities on our [Roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/master/ROADMAP.md), but maybe this information can provide someone looking into this further a starting point. The contributing guide has information on how to [run the acceptance testing](https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md) for anyone unfamiliar.
