### ISSUE TITLE
aws_msk_configuration failed during AWS MSK version upgrade

### ISSUE THREAD

**Issue by azhurbilo** [hashicorp/terraform-provider-aws#16691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

AWS Provider 3.18.0
Terraform 0.12.24

### Affected Resource(s)

* aws_msk_configuration

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_msk_configuration" "msk" {
  count                    = var.enabled ? 1 : 0
  kafka_versions           = [var.msk_version]
  name                     = "${var.msk_name}-${replace(var.msk_version, "/[.]/", "-")}-config"
  server_properties        = var.kafka_server_properties

}
```

### Expected Behavior

aws_msk_configuration updated together with new version of AWS MSK

### Actual Behavior

Error

Apply failed with error

```
Error: error deleting MSK Configuration XXX: BadRequestException: Configuration is in use by one or more clusters. Dissociate the configuration from the clusters.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "XXXX"
  },
  InvalidParameter: "arn",
  Message_: "Configuration is in use by one or more clusters. Dissociate the configuration from the clusters."
}
```

### Steps to Reproduce

1. change version of aws msk
2. tf plan

```
-/+ resource "aws_msk_configuration" "msk" {

kafka_versions    = [ # forces replacement
  - "2.4.1",
  + "2.4.1.1",
]
}
```
3. apply

### References

* #0000

**Comment by bill-rich** [comment]
Hi @azhurbilo! In order to change the version without creating a new config resource, you'll need to change the lifecycle behavior for your `aws_msk_configuration` resource. Adding the following should solve this for you:

```
  lifecycle {
    create_before_destroy = true
  }
```

The reason this is necessary is that normally Terraform will destroy a resource before creating a new one. In this case, the MSK configuration is still in use and cannot be deleted. Changing the lifecycle behavior will make Terraform create a new configuration and associate it with the cluster before deleting the old one. 

The big caveat to this is that if you have a static name for the configuration, the new one will conflict with the old one, so you need to make sure the name includes something dynamic and that will change between the two versions (which yours does).
