### ISSUE TITLE
aws_eks_node_group should propagate its tags to underlying ASG

### ISSUE THREAD

**Issue by casper-gh** [hashicorp/terraform-provider-aws#16825]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating EKS cluster with aws_eks_node_group (managed ng), the node group should propagate its tags to underlying Autoscaling Group.

### New or Affected Resource(s)

* ASG created by aws_eks_node_group

### Potential Terraform Configuration

```hcl
resource "aws_eks_node_group" "my-ng" {
  cluster_name                = aws_eks_cluster.my-cluster.name
  node_group_name       = "${var.cluster_name}-ng"
  node_role_arn               = var.eks_nodegroup_role_arn
  subnet_ids                    = var.subnets

  launch_template {
    id      = aws_launch_template.eks_nodegroup.id
    version = "$Latest"
  }

  scaling_config {
    desired_size            = var.eks_asg_desired
    max_size                  = var.eks_asg_max
    min_size                  = var.eks_asg_min
  }

  tags = merge(
    local.common_tags,
    map(
      "Name", "${var.tag_name}-ng",
    )
  )
}
```

### References

* #0000

**Comment by bflad** [comment]
Hi folks 👋  Thank you for your interest in this feature request. The EKS API does not implement this functionality, so it is not appropriate for it to be implemented in the Terraform AWS Provider at this time. Rather than keep this issue open and lingering with nothing actionable at the moment, we are going to opt to close this for now. When the API support exists, we will gladly implement it if any changes are necessary! 😄 

In terms of tracking of this functionality, you may be interested in:

- [AWS Containers Roadmap issue for Propagating EKS Node Group Tags](https://github.com/aws/containers-roadmap/issues/781)
- [AWS Containers Roadmap issue for Propagating EKS Cluster Tags](https://github.com/aws/containers-roadmap/issues/374)
- Filing an AWS Support Case with the feature request or talking to your AWS Technical Account Manager
