### ISSUE TITLE
Elastic IP tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now add tags to your Virtual Private Cloud (VPC) Elastic IP addresses while creating the resource. 

### New or Affected Resource(s)

* [`aws_eip`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip)

### Potential Terraform Configuration

```hcl
resource "aws_eip" "example" {
  tags = {
    Environment = "test"
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-virtual-private-cloud-vpc-supports-tag-on-create-elastic-ips-eip/).

Requires [AWS SDK v1.36.13](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.13):

* https://github.com/hashicorp/terraform-provider-aws/pull/16872

**Comment by rick-masters** [comment]
I submitted #17612 which implements tag-on-create for vpc EIPs. I just looked at the aws_ebs_volume resource to see how it does it because it already supports setting tags on create.
  
  I needed this to work because I have IAM policies that require ownership tags to be set to enforce access control and those tags can only be set when a resource is created. The last piece of the puzzle to get that working was fixing this issue. With this fixed, my IAM policies are able to enforce tags properly.
  
  @autotune -
  After reviewing #16909, I think you may have read the AWS announcement as indicating that AWS now supports setting tags on standard eips. And so you took the natural step of removing the check that prevented terraform from setting the tags on standard eips. And for that purpose, it looks right. I believe this was your first contribution so congrats on getting so far on the pull request! Unfortunately, I believe this issue is requesting something a bit different from what you implemented.
  
  I think a little background information can clarify what is being requested.
  
  AWS supports two "domains" of elastic ips: standard and vpc [1]. These EIPs are meant for use in the two "platforms" that AWS supports: EC2 and VPC [2].
  
  The EC2 platform is a legacy set of features that are available to older (circa 2013 and prior) accounts in use prior to the introduction of the VPC. One of those features is the ability to create a "standard" EIP (via the AllocateAddress API call with Domain set to "standard").
  
  Tags are *not* supported on standard EIPs [3]. You cannot set tags either at creation time or afterwards. The announcement is only stating that Amazon "VPC" now supports adding tags on an eip "while creating the resource". Previously you had to create the resource and *then* set the tags. You could not provide the tags in the initial AllocateAddress API call. Now you can.
  
  So this issue is requesting that for vpc EIPs, the tags should be included in the initial request instead of being set afterwards. For standard EIPs, presumably the current behavior can be left alone.
  
  1. https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateAddress.html (See Domain).
  2. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-classic-platform.html
  3. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-classic-platform.html#differences-ec2-classic-vpc (Row 7 of the table)
