### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by pe008235** [hashicorp/terraform-provider-aws#16893]
When expanding the plan for aws_s3_bucket.ts_bucket to include new values
learned so far during apply, provider "registry.terraform.io/-/aws" produced
an invalid new value for .replication_configuration[0].rules: planned set element
cty.ObjectVal(map[string]cty.Value{"destination":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"access_control_translation":cty.ListValEmpty(cty.Object(map[string]cty.Type{"owner":cty.String})),
"account_id":cty.StringVal(""), "bucket":cty.UnknownVal(cty.String),
"replica_kms_key_id":cty.StringVal(""),
"storage_class":cty.StringVal("STANDARD")})}),
"filter":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"prefix":cty.StringVal(""),
"tags":cty.MapVal(map[string]cty.Value{"replicateTo":cty.StringVal("MSI")})})}),
"id":cty.StringVal("MSI"), "prefix":cty.StringVal(""),
"priority":cty.NullVal(cty.Number),
"source_selection_criteria":cty.ListValEmpty(cty.Object(map[string]cty.Type{"sse_kms_encrypted_objects":cty.List(cty.Object(map[string]cty.Type{"enabled":cty.Bool}))})),
"status":cty.StringVal("Enabled")}) does not correlate with any element in
actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by bflad** [comment]
Hi @pe008235 👋  Sorry to hear you are running into trouble here. Given the information you provided it is not immediately clear to me how to best help. For example we will need to know the Terraform CLI and Terraform AWS Provider versions used, the configuration, and likely the output from debug logging of the API requests. I am going to close this issue and encourage you to open a new issue using the [Bug Report](https://github.com/hashicorp/terraform-provider-aws/issues/new?template=Bug_Report.md) template so that the maintainers can get a better understanding of the issue(s) and potentially try to reproduce the behavior.
