### ISSUE TITLE
Apple Silicon (M1) darwin_arm64 Support

### ISSUE THREAD

**Issue by fearoffish** [hashicorp/terraform-provider-aws#16948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The new Apple M1 chips use a `darwin_arm64` architecture and this provider does not work for that. I'd love to be able to use my new laptop with terraform but right now that's not possible.

**Comment by bflad** [comment]
Hi @fearoffish 👋  Thank you for raising this. It is certainly something we will support in the future.

There are a few pre-requisites necessary for adding the `darwin/arm64` port to our Go releases. A good starting list can be found upstream in https://github.com/hashicorp/terraform/issues/27257, but generally speaking what needs to happen here is:

* The Go language team supporting the port as "first class" (see also: https://github.com/golang/go/wiki/PortingPolicy) -- this is [expected with the release of Go 1.16](https://tip.golang.org/doc/go1.16) in the coming weeks. New kernel and CPU architecture combinations can have unknown quirks at runtime, so we opt to lean on this support model before including a new port. 
* Terraform CLI should have a release including the new port.
* Terraform AWS Provider release testing is updated (`.goreleaser.yml` configuration, which all builds are currently checked during pull requests)
* Terraform AWS Provider release process is updated (due to timing this may be either be just the above configuration or a HashiCorp internal configuration change)

In the meantime, using the x86 emulation support in macOS 11 should get you started in some cases. Please note though that the maintainer team here does not have the new Apple hardware for testing, so we cannot help troubleshoot any issues at this time.

**Comment by billinghamj** [comment]
Short term workaround if you want: https://github.com/hashicorp/terraform/issues/27257#issuecomment-754777716

For huge workspaces this does allow for substantially better performance than via Rosetta 2

**Comment by fearoffish** [comment]
You, my friend, are a saviour. Thank you!

**Comment by dmccaffery** [comment]
I'm happy to help test this (and any other provider) -- even if you need a Self-Hosted GitHub Actions Runner -- I don't have a ton of resources, but happy to dedicate 2 M1 Mac Minis to the cause if that's helpful.

Also happy to help triage/fix any m1 specific issues.

**Comment by bflad** [comment]
Hi folks 👋  Quick update here.

Go 1.16.0 was released this week. 🎉   We'll likely be upgrading this codebase to Go 1.16 after this week's release. Behind the scenes, we will also work on enabling `darwin/arm64` builds in our internal release process for Go 1.16+. If all goes well, version 3.30.0 of the Terraform AWS Provider should release next week with a `darwin/arm64` compatible binary.

In full transparency, releasing native `darwin/arm64` binaries of Terraform CLI will likely take a few weeks before it happens. We are trying to bootstrap efforts across the provider ecosystem to upgrade to Go 1.16 and include `darwin/arm64` releases before releasing that platform support of Terraform CLI. Otherwise, it is very likely that practitioners will encounter `Incompatible provider version` errors unless a pragmatic amount of the provider ecosystem supports the new platform. The best place to track that release effort will be upstream in https://github.com/hashicorp/terraform/issues/27257.

**Comment by ddup1** [comment]
> I'd love to be able to use my new laptop with terraform but right now that's not possible.

I have a mac with M1 chip and i can use terraform amd64 release. I think you have to install rosetta to be able too : https://support.apple.com/en-us/HT211861

But i can't say that it is stable as i have from time to time rpc error.

**Comment by bflad** [comment]
Initial updates to Go 1.16 in this codebase and adding `darwin/arm64` to the release process have been completed. The first official `darwin/arm64` binary will release with version 3.30.0 of the Terraform AWS Provider later this week. Please follow https://github.com/hashicorp/terraform/issues/27257 for further updates about native Terraform CLI releases with the new platform.

**Comment by billinghamj** [comment]
@ddup1 I've found it is barely usable at all - I find for me it only successfully runs around 3-5% of the time

**Comment by billinghamj** [comment]
Also in terms of the actual CLI, Homebrew has already been distributing native `darwin/arm64` binaries for months, so as soon as v3.30 of this provider goes out, if you're only using the AWS provider, you'll be good to go 👍
