### ISSUE TITLE
resource/aws_ecs_capacity_provider: Add support for ECS capacity provider update

### ISSUE THREAD

**Issue by shuheiktgw** [hashicorp/terraform-provider-aws#16943]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As described in https://github.com/aws/containers-roadmap/issues/633, the ECS capacity provider now supports updating its parameters. It would be nice if terraform-aws-provider supports it too.

### New or Affected Resource(s)

* aws_ecs_capacity_provider

### Potential Terraform Configuration

```hcl
N/A
```

### References

* https://github.com/aws/containers-roadmap/issues/633

**Comment by eddgrant** [comment]
I'm not literate in golang but I _think_ the AWS SDK that Terraform uses already has support for the updating of capacity providers [here](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ECS.UpdateCapacityProvider). Unlocking in-place (rather than replacing) updates to the `managed_scaling` properties would make capacity providers a viable prospect to use with Terraform.

**Comment by shuheiktgw** [comment]
Yes, I've already created a PR to add an update function to ecs_capacity_provider. It's been waiting for a review now!

- https://github.com/hashicorp/terraform-provider-aws/pull/16942
