### ISSUE TITLE
Add separated resource for configuring S3 bucket replication rules

### ISSUE THREAD

**Issue by fishpen0** [hashicorp/terraform-provider-aws#1704]
Add a separate resource `aws_s3_bucket_replication_rule` for supporting replication rules (http://docs.aws.amazon.com/AmazonS3/latest/dev/crr.html)

Current situation

Replication rules can be defined only inline in the aws_s3_bucket resource, but not as external resources than can be attached to the S3 bucket afterwards

Use Case

I have a module for generating S3 buckets from a dynamic list of regions.  The first bucket in the list should replicate to every other region's bucket.  Depending on the use case for the module, the list may only contain one region.  This would be easier to accomplish if the replication rule were a separate entity that I can apply a `count` to.

This is similar to the request laid out in #283

**Comment by jonjohnston** [comment]
I agree that this should be split out. My conundrum is I have 2 buckets that I want to replicate to each other. I cannot implement this in terraform because bucket A cannot be created with replication if bucket B doesn't exist and bucket B can't be created if bucket A doesn't exist. Having this split out can allow me to create bucket B without replication policy on the bucket, create bucket A with replication rule, then add replication rule to bucket B. Is there any progress on this?

**Comment by dtserekhman-starz** [comment]
Any update on this issue? Sounds like very frequent use case (for s3 buckets' bidirectional replication), and looks like no solution has been made available yet? I'm running into this now too. Big showstopper!

**Comment by anGie44** [comment]
Hi @fishpen0 and those following this issue, I believe this should be addressed with the addition of the `aws_s3_bucket_replication_configuration` resource added in `v3.66.0` of the provider (PR: https://github.com/hashicorp/terraform-provider-aws/pull/20777) so I'm going to close this issue but if you believe it's been done by mistake, please reach out!
