### ISSUE TITLE
Set ASG values via aws_eks_node_group attribute

### ISSUE THREAD

**Issue by kylecompassion** [hashicorp/terraform-provider-aws#17097]
### Description
Now that ASG's support MAX_INSTANCE_LIFETIME, I'd like to set that value via an attribute in aws_eks_node_group. 

### New or Affected Resource(s)
aws_eks_node_group

### Potential Terraform Configuration
```hcl
resource "aws_eks_node_group" "example" {
  cluster_name    = aws_eks_cluster.example.name
  node_group_name = "example"
  node_role_arn   = aws_iam_role.example.arn
  subnet_ids      = aws_subnet.example[*].id

  scaling_config {
    desired_size = 1
    max_size     = 1
    min_size     = 1
    max_instance_lifetime = (time in seconds)
  }
}
```

**Comment by bflad** [comment]
Hi @kylecompassion 👋  Thank you for suggesting this.

The EKS API does not appear to support this type of functionality at this time in the [CreateNodegroup](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html) or other API operations. Since the AWS service API doesn't directly support it and the [Terraform AWS Provider's boundaries are typically the AWS Go SDK for those service APIs](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#api-and-sdk-boundary), this unfortunately leaves us in a position where this is not something we would add to this particular codebase at this time. If the AWS service API does implement this type of functionality in the future, we would be happy to take a fresh look into implementing it! Until then, I'm going to close this issue as there is no action for us to take right now.

That being said, there are a few potential paths forward for everyone here in the meantime:

* Checking the [AWS Containers Roadmap issues](https://github.com/aws/containers-roadmap/issues) to ensure this feature request is covered in that public forum
* Submitting a feature request AWS Support case, which the service team can use to help prioritize the functionality
