### ISSUE TITLE
Terraform not ignoring changes in aws_network_interface

### ISSUE THREAD

**Issue by takashi-ito2020** [hashicorp/terraform-provider-aws#17101]
### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.26
+ provider.aws v3.3.0

Your version of Terraform is out of date! The latest version
is 0.14.4. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
* aws_network_interface
* aws_route_table

### Terraform Configuration Files

```hcl
resource "aws_network_interface" "eth0" {
  subnet_id   = aws_subnet.subnet-public-01a.id
  private_ips = [ "10.156.0.100" ]
  source_dest_check = false
  tags = {
    Name = "aws_eth0"
  }
}
resource "aws_route_table" "public-01" {
  vpc_id = aws_vpc.vpc-all-01.id
  route {
    cidr_block             = "0.0.0.0/0"
    egress_only_gateway_id = null
    gateway_id             = null
    instance_id            = null
    ipv6_cidr_block        = null
    nat_gateway_id         = null
    network_interface_id   = aws_network_interface.eth0.id
    transit_gateway_id     = null
  }
  lifecycle {
    ignore_changes = [ route[0].network_interface_id, ]
  }
  tags = {
    Name = "routetable-public-01"
  }
}

```
The code I tried for ignore_changes
```
    #route.network_interface_id
    #route.\%.["network_interface_id"]
    #route.0.network_interface_id
    #route["network_interface_id"]
    #site_config["scm_type"],
    #route.network_interface_id
    #route.[0].route.network_interface_id
    #route.*.route.network_interface_id
```

### Expected Behavior
I want to ignore the network_interface_id in the aws_route_table.

### Actual Behavior
Error occurs after running terraform plan

Error: Invalid index

  on main.tf line 61, in resource "aws_route_table" "public-01":
  61:     ignore_changes = [ route[0].network_interface_id, ]

This value does not have any indices.

### Steps to Reproduce
1. `terraform apply` or `terraform plan`

### References
https://github.com/hashicorp/terraform/issues/24719

* #0000

**Comment by rick-masters** [comment]
@takashi-ito2020 Thanks for raising this issue. Unfortunately, I do not believe it is possible to do what you want.

Terraform currently manages the route attribute as a Set rather than a List [1]. That means it considers order to be unimportant. If you only rearrange the order of the routes, terraform understands that nothing has changed. That is why it is declared as a Set. If it were declared a List then it would think something had changed and would try to reorder the routes. This would make removing and adding routes more disruptive. I think that is why it is a Set.

The downside is that when an attribute is a Set no indexing is allowed. [2]

1. https://github.com/hashicorp/terraform-provider-aws/blob/v3.30.0/aws/resource_aws_route_table.go#L64
2. https://github.com/hashicorp/hcl/blob/v2.9.0/ops.go#L52

**Comment by rick-masters** [comment]
@takashi-ito2020 Oops! While what I said is true, I neglected to explore an alternative.

You can break out the route as a separate object and then you can directly ignore the attribute without indexing in that object. 

```
resource "aws_route_table" "public_01" {
 vpc_id = aws_vpc.vpc-all-01.id
  tags = {
    Name = "routetable-public-01"
  }
}

resource "aws_route" "public-01-all" {
    route_table_id = aws_route_table.public_01.id
    destination_cidr_block             = "0.0.0.0/0"
    egress_only_gateway_id = null
    gateway_id             = null
    instance_id            = null
    destination_ipv6_cidr_block        = null
    nat_gateway_id         = null
    network_interface_id   = aws_network_interface.eth0.id
    transit_gateway_id     = null
    lifecycle {
      ignore_changes = [ network_interface_id ]
    }
}
```

I think this is the way to do it and the other way is unlikely to be supported. I hope the solution above works for you and if so please close this issue.

**Comment by takashi-ito2020** [comment]
thanks you. I was able to set it.
