### ISSUE TITLE
Terraform Feature Request for AWS Provider - Allow iam_access_key resource to output the keypair age

### ISSUE THREAD

**Issue by jd4883** [hashicorp/terraform-provider-aws#17294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I am developing a terraform based IAM keypair rotation framework for my organization. I found that the boto3 calls to the AWS API provide a few more details than the terraform state tracks for an **aws_iam_access_key** resource block. My automation framework will be using terraform with the **aws** and **vault**.

The current **aws_iam_access_key** resource block does not have matching functionality to the AWS API. Using the API, it is possible to get the age of an IAM access key, which for the purpose of creating tooling to rotate these, is a must. Since terraform supports creation / destruction of these via a resource block, it would be really awesome if we can get outputs that match the AWS API capabilities.

It would be awesome if there were more native terraform features related to key rotation here as well, but the main part I see as a barrier to moving forward with my project. The intended goal is to be able to use the keypair age against a user defined variable to determine when the key should be rotated (my exact technical implementation here is still to be determined). Any additional features / adjustments that could allow for easier key rotation automation would be appreciated but are not strictly what this feature request is intended for.

### New or Affected Resource(s)
* **aws_iam_access_key**

### Potential Terraform Configuration
Example state file entry for a keypair with redacted sensitive details:
```
{
	"module": "XXXXXXXX",
	"mode": "managed",
	"type": "aws_iam_access_key",
	"name": "keys",
	"provider": "provider[\"registry.terraform.io/hashicorp/aws\"].platform",
	"instances": [{
			"index_key": 0,
			"schema_version": 0,
			"attributes": {
				"encrypted_secret": null,
				"id": "XXXXXXXX",
				"key_fingerprint": null,
				"pgp_key": null,
				"secret": "XXXXXXXX",
				"ses_smtp_password": "XXXXXXXX",
				"status": "Active",
				"user": "test-user"
			}]
	}
```

### References
* IAM Keypair terraform - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key#status
* IAM Keypair boto3 - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#accesskey

**Comment by bflad** [comment]
Hi @jd4883 👋  Thank you for raising this.

Adding a `create_date` attribute to match the `CreateDate` field from the IAM API is certainly a valid feature request. Submitted this here: https://github.com/hashicorp/terraform-provider-aws/pull/17318

> It would be awesome if there were more native terraform features related to key rotation here as well, but the main part I see as a barrier to moving forward with my project. The intended goal is to be able to use the keypair age against a user defined variable to determine when the key should be rotated (my exact technical implementation here is still to be determined). Any additional features / adjustments that could allow for easier key rotation automation would be appreciated but are not strictly what this feature request is intended for.

The Terraform AWS Provider maintainers are not able to provide too much guidance here since that is outside our general scope, however you may want to check out the [`time_rotating` resource](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating) which can provide a naive rotation implementation within Terraform assuming that Terraform is run on a schedule or some of the other Terraform Time Provider resources. Asking in the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers), where there are far more people than the GitHub issues here, may provide better answers though.
