### ISSUE TITLE
issue while destroy eks cluster, so if i have deleted whole cluster including node-pool but still load balancer left and unable to destroy vpc network, looking for fix 

### ISSUE THREAD

**Issue by Ankita5892** [hashicorp/terraform-provider-aws#17315]

**Comment by bflad** [comment]
Sorry to hear you are running into trouble here. Given the information you provided it is not immediately clear to me how to best help. For example we will need to know the Terraform CLI and Terraform AWS Provider versions used, the configuration, and likely the output from debug logging of the API requests. I am going to close this issue and encourage you to open a new issue using the [Bug Report](https://github.com/hashicorp/terraform-provider-aws/issues/new?template=Bug_Report.md) template so that the maintainers can get a better understanding of the issue(s) and potentially try to reproduce the behavior.

The requested information within the Bug Request template is important so please try to provide as much information as possible, **excluding any sensitive information**, to reproduce the bug in question. If you are not sure if you are running into a Terraform AWS Provider bug and would like some guidance to determine that, you may want to visit the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) to start.
