### ISSUE TITLE
aws_eks_node_groups should allow supplying IAM Role mappings for aws-auth configmap

### ISSUE THREAD

**Issue by theothermike** [hashicorp/terraform-provider-aws#17333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Experimenting with using EKS and Managed Node Groups, I've noticed that when you use Managed Node Groups `aws_eks_node_group` resources, the `aws-auth` configmap is created for you without allowing you to specify other mappings of IAM Roles.

The community EKS Module then does not work properly because it would optionally allow you to set this using the kubernetes provider.  

There needs to be an attribute in either the `aws_eks_cluster` or `aws_eks_node_group` resources to set these mappings.  This also needs to be made to be ignored thru `ignore_changes` since this could change after the cluster has been provisioned

### New or Affected Resource(s)

* aws_eks_cluster
* aws_eks_node_group

### Potential Terraform Configuration

```hcl
resource aws_eks_node_group my-node-group {
  <snip>
  mapRoles = var.map_roles
  mapUsers = var.map_users
  mapAccounts = var.map_accounts  
  <snip>
}
```

### References

Community EKS Module: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/aws_auth.tf

* #0000

**Comment by bflad** [comment]
Hi folks 👋  Thank you for suggesting this and it would certainly be helpful to many people.

The EKS API does not appear to support this type of functionality at this time in the [CreateCluster](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html), [CreateNodegroup](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html) or other API operations. Since the AWS service API doesn't directly support it and the [Terraform AWS Provider's boundaries are typically the AWS Go SDK for those service APIs](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#api-and-sdk-boundary), this unfortunately leaves us in a position where this is not something we would add to this particular codebase at this time. If the AWS service API does implement this type of functionality in the future, we would be happy to take a fresh look into implementing it. Until then, I'm going to close this issue as there is no action for us to take right now.

That being said, there are a few potential paths forward for everyone here in the meantime:

* Checking the [AWS Containers Roadmap issues](https://github.com/aws/containers-roadmap/issues) to ensure this feature request is covered in that public forum
* Submitting a feature request AWS Support case, which the service team can use to help prioritize the functionality
