### ISSUE TITLE
Sagemaker Domain - Support retaining EFS File system

### ISSUE THREAD

**Issue by DrFaust92** [hashicorp/terraform-provider-aws#17349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add an argument to retain Sagemaker Domain EFS File system upon deletion. This change will revert current behaviour change introduced in https://github.com/hashicorp/terraform-provider-aws/pull/17123

### New or Affected Resource(s)

* aws_sagemaker_domain

### Potential Terraform Configuration

```hcl
resource "aws_sagemaker_domain" "example" {
  domain_name        = "example"
  auth_mode          = "IAM"
  vpc_id             = aws_vpc.test.id
  subnet_ids         = [aws_subnet.test.id]

  retain_policy {
    home_efs_file_system = "Delete|Retain" # Default: Retain
  }

  default_user_settings {
    execution_role = aws_iam_role.test.arn
  }
}
```

### References

* #17123

**Comment by bflad** [comment]
Since the [`DeleteDomain` API](https://docs.aws.amazon.com/sdk-for-go/api/service/sagemaker/#DeleteDomainInput) models this as a structure with a string parameter, we might want to do the same. 👍 

```terraform
resource "aws_sagemaker_domain" "example" {
  # ... other configuration ...

  retain_policy {
    home_efs_file_system = "Delete|Retain" # Default: Retain
  }
}
```

Then the logic can skip adding it if the block is not declared (essentially reverting it back to the default behavior):

```go
func resourceAwsSagemakerDomainDelete(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*AWSClient).sagemakerconn

	input := &sagemaker.DeleteDomainInput{
		DomainId: aws.String(d.Id()),
	}

	if v, ok := d.GetOk("retention_policy"); ok && len(v.([]interface{})) > 0 && v.([]interface{})[0] != nil {
		input.RetentionPolicy = expandSagemakerRetentionPolicy(v.([]interface{}))
	}
```

To prevent confusion we have seen in other resources with destroy-time configuration, it would also be good to include additional cues in the documentation that this configuration must be applied in the Terraform state before the resource destroy operation.
