### ISSUE TITLE
aws_security_group resource ingress egress rules definition expect optional parameter

### ISSUE THREAD

**Issue by JCarrascoF** [hashicorp/terraform-provider-aws#17356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.26.0

### Affected Resource(s)

* aws_security_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.26.0"
    }
  }
}

provider "aws" {
  region = "eu-west-1"
}

resource "aws_security_group" "ec2" {
  vpc_id      = "vpc-00000000000000000"
  description = "Test SG"
  tags = {
    "Name" = "Test SG"
  }

  ingress = [{
    self             = false
    description      = "ingress rule"
    protocol         = -1
    from_port        = 0
    to_port          = 0
  }]

  egress = [
    {
      self             = false
      description      = "egress rule"
      protocol         = -1
      from_port        = 0
      to_port          = 0
    }
  ]
}
```

### Debug Output

https://gist.github.com/JCarrascoF/8a69928374ca96905e009dc6de60715a

### Expected Behavior
Security group ingress and egress rules can be created as descibed in the docs

### Actual Behavior
```shell
Error: Incorrect attribute value type

  on ec2.tf line 8, in resource "aws_security_group" "ec2":
   8:   ingress = [{
   9:     self             = false
  10:     description      = "ingress rule"
  11:     protocol         = -1
  12:     from_port        = 0
  13:     to_port          = 0
  14:   }]

Inappropriate value for attribute "ingress": element 0: attributes
"cidr_blocks", "ipv6_cidr_blocks", "prefix_list_ids", and "security_groups"
are required.


Error: Incorrect attribute value type

  on ec2.tf line 16, in resource "aws_security_group" "ec2":
  16:   egress = [
  17:     {
  18:       self             = false
  19:       description      = "egress rule"
  20:       protocol         = -1
  21:       from_port        = 0
  22:       to_port          = 0
  23:     }
  24:   ]

Inappropriate value for attribute "egress": element 0: attributes
"cidr_blocks", "ipv6_cidr_blocks", "prefix_list_ids", and "security_groups"
are required.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

* #0000

**Comment by bflad** [comment]
Hi @JCarrascoF 👋  Thank you for raising this and sorry you ran into trouble here.

Can you please point out which documentation is showing this?

The expected Terraform configuration language syntax for the `ingress` and `egress` is [block syntax](https://www.terraform.io/docs/language/syntax/configuration.html#blocks), which is the style noted on the current [`aws_security_group` resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group). e.g. taking your configuration:

```terraform
resource "aws_security_group" "ec2" {
  vpc_id      = "vpc-00000000000000000"
  description = "Test SG"
  tags = {
    "Name" = "Test SG"
  }

  ingress {
    self             = false
    description      = "ingress rule"
    protocol         = -1
    from_port        = 0
    to_port          = 0
  }

  egress {
    self             = false
    description      = "egress rule"
    protocol         = -1
    from_port        = 0
    to_port          = 0
  }
}
```

If necessary, multiple of these blocks can be created with the [`dynamic` block](https://www.terraform.io/docs/language/expressions/dynamic-blocks.html) configuration language feature.

---

Some further technical details about this particular situation -- understanding this is not necessary except for advanced usage, but provided for additional insight. There is one confusing aspect to this particular resource and `ingress` / `egress` , which is why Terraform CLI does not provide the normal configuration error to suggest switching this to block syntax. The short explanation is that these support a special [attributes as blocks configuration mode](https://www.terraform.io/docs/language/attr-as-blocks.html) which was a compromise to ease operator adoption of Terraform 0.12 when it was released. When the value is as a list of objects like the original issue configuration, the validation requires all nested attributes. This special mode will potentially go away in the future (for consistency with all other Terraform resources), so it should not be relied on.

**Comment by JCarrascoF** [comment]
Hi @bflad! Thanks for your quick reply.

As you said I assume the required/optional parameters check will be the same in the block syntax and the individual ingress/egress declaration. Wrote as individual rules runs correctly and looks good to me so I'll adopt this way as the standard.

So interesting the technical info you added and the info about future actions in terraform.

**Comment by bflad** [comment]
No problem and glad you have a path forward. If you're looking for further general assistance, please check out the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.

If there is any https://learn.hashicorp.com, https://terraform.io/docs, or https://registry.terraform.io/providers/hashicorp/aws documentation that is still showing the older attribute syntax (`attribute = [{}]`) where is should be block syntax (`attribute {}`), happy to follow up with fixing it, just need to be pointed to the URL(s). 👍
