### ISSUE TITLE
aws_api_gateway_rest_api with no changes taking 10+minutes to run successfully.

### ISSUE THREAD

**Issue by rtorres280** [hashicorp/terraform-provider-aws#17361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

`0.14.5`

### Affected Resource(s)

* aws_api_gateway_rest_api

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.14.5"

  backend "remote" {
    organization = "phonedotcom"
    workspaces {
      name = "mypdc-stage"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.26.0"
    }
  }
}
variable "region" {
  type = string
}
variable "profile" {
  type = string
}
provider "aws" {
  region = var.region
  profile = var.profile
}
resource "aws_api_gateway_rest_api" "ApiGateway" {
  name        = "foo"
  description = "bar"
  endpoint_configuration {
    types = ["REGIONAL"]
  }
}
```

### Expected Behavior

finish a single resource <1m

### Actual Behavior

hangs for >10m before giving any logs or feedback

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @rtorres280 👋  Thank you for raising this and sorry you ran into trouble here.

Have you tried enabling [debug logging](https://www.terraform.io/docs/internals/debugging.html) (e.g. `TF_LOG=debug terraform apply`) to watch the Terraform and AWS Go SDK logging for additional information? There can be any number of issues occurring. Without an error message to go off of or logs to investigate, I'm not sure how to provide further assistance. If you feel this problem is specific to Terraform Cloud (seeing the remote backend usage there), please note it has its own support channel, which can be found by clicking the Support link at the bottom of that website.

**Comment by rtorres280** [comment]
apologies, this can be closed. This is probably a Terraform Cloud issue

**Comment by bflad** [comment]
@rtorres280 no need to apologize! There are certain pieces of using Terraform where it can be confusing where the operations happens and how to troubleshoot. Hopefully you are able to get your particular situation resolved.
