### ISSUE TITLE
Feature Request - Allow adding an ELB to the Managed Node Group

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform-provider-aws#17563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am looking for a way to add an existing ELB to the Managed Node Group. This can be done manually, want to do the same using Terraform.

### New or Affected Resource(s)
[aws_eks_node_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group)

### Potential Terraform Configuration

```hcl
resource "aws_eks_node_group" "example" {
  cluster_name    = aws_eks_cluster.example.name
  node_group_name = "example"
  node_role_arn   = aws_iam_role.example.arn
  subnet_ids      = aws_subnet.example[*].id

  load_balancers            = [aws_elb.eks.name]
}
```

**Comment by bflad** [comment]
Hi @kylecompassion 👋  Thank you for suggesting this.

The EKS API does not appear to support this type of functionality at this time in the [CreateNodegroup](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html) or other API operations. Since the AWS service API doesn't directly support it and the [Terraform AWS Provider's boundaries are typically the AWS Go SDK for those service APIs](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#api-and-sdk-boundary), this unfortunately leaves us in a position where this is not something we would add to this particular codebase at this time. If the AWS service API does implement this type of functionality in the future, we would be happy to take a fresh look into implementing it! Until then, I'm going to close this issue as there is no action for us to take right now.

That being said, there are a few potential paths forward for everyone here in the meantime:

* Checking the [AWS Containers Roadmap issues](https://github.com/aws/containers-roadmap/issues) to ensure this feature request is covered in that public forum
* Submitting a feature request AWS Support case, which the service team can use to help prioritize the functionality

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.
