### ISSUE TITLE
Need StringSet attribute type for DynamoDb table attributes

### ISSUE THREAD

**Issue by mohamednazarae** [hashicorp/terraform-provider-aws#17628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create DynamoDB attribute with StringSet type using terraform.

### New or Affected Resource(s)

aws_dynamodb_table
attribute

* aws_dynamodb_table

### Potential Terraform Configuration

```
resource "aws_dynamodb_table" "data" {
name = "Data-Index"
read_capacity = "5"
write_capacity = "5"
hash_key = "Data"
range_key = "Categories"

attribute {
name = "Data"
type = "S"
}

attribute {
name = "Categories"
type = "SS"
}
}
```
We are getting following error.
Error:
Error: expected attribute.0.type to be one of [B N S], got SS
### References

In AWS Console we have option to create attribute like StringSet, please refer the below URL to see various attribute type.
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html

But terraform supports only 3
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#type

Please suggest how to create StringSet attribute in DynamoDB through Terraform code.

Thanks
Mohamed Nazar

* #0000

**Comment by GavinWu1991** [comment]
@mohamednazarae 
I think you brought up a very good idea, but it should be noted that since AWS Dynamodb is a NoSQL database, only Key Attributes are allowed to be created in the create database, which is why the AWS CreateTable API currently only supports the creation of key fields for scalar types. For more details, please refer to https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#API_CreateTable_RequestSyntax
To

**Comment by borikanes** [comment]
Unfortunately, from what I understand, this isn't possible due to DynamoDB constraints. Right now you can only have Binary, String or Number (BSN) as the data types of your sort/hash keys. And since DynamoDB is schemaless, you don't need to define attributes outside the hash/sort keys, GSIs or LSIs - which all have to be BSN.  
If you go through the AWS console to create a table, you'll notice you can't define any other data type apart from BSN, neither can you through the [AWS go SDK](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.3.1/types#AttributeDefinition) nor the [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/create-table.html#options)
