### ISSUE TITLE
data source aws_vpc_endpoint_service not working as expect in AWS China partition (cn-north-1)

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform-provider-aws#17640]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.28.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/tls v3.0.0
```

### Affected Resource(s) + Terraform Configuration Files

```hcl
data "aws_vpc_endpoint_service" "ecr_dkr" {
  service_type = "Interface"
  service      = "ecr.dkr"
}
```

### Panic Output

```
Error: error reading VPC Endpoint Service (com.amazonaws.cn-north-1.ecr.dkr): InvalidServiceName: The Vpc Endpoint Service 'com.amazonaws.cn-north-1.ecr.dkr' does not exist
	status code: 400, request id: cad8f3f9-c8bf-466a-97b2-6d9201ba2b43
```

### Expected Behavior

Expected behaviour would be to correctly find service name which in "AWS China partition (cn-north-1)" should be `cn.com.amazonaws.cn-north-1.ecr.dkr`. Currently, this is not happening and in fact terraform fails at `plan` stage.

### Steps to Reproduce

1. `terraform plan`

**Comment by marcincuber** [comment]
I have managed to solve the problem by using filters:
```hcl
data "aws_vpc_endpoint_service" "s3" {
  service_type = "Interface"
  filter {
    name   = "service-name"
    values = ["*s3*"]
  }
}

output "aws_vpc_endpoint_service_s3" {
  value = data.aws_vpc_endpoint_service.s3.service_name
}

data "aws_vpc_endpoint_service" "ecr_dkr" {
  service_type = "Interface"
  filter {
    name   = "service-name"
    values = ["*ecr.dkr*"]
  }
}

output "aws_vpc_endpoint_service_ecr_dkr" {
  value = data.aws_vpc_endpoint_service.ecr_dkr.service_name
}
```
Results:

```
aws_vpc_endpoint_service_ecr_dkr = "cn.com.amazonaws.cn-north-1.ecr.dkr"
aws_vpc_endpoint_service_s3         = "cn.com.amazonaws.cn-north-1.s3"
```

**Comment by ewbankkit** [comment]
@marcincuber Thanks for raising this issue.

Instead of the `filter` with `name   = "service-name"` you could use the `service_name` attribute along with the [`aws_partition`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/partition) and [`aws_region`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region) data source:

```hcl
data "aws_partition" "current" {}
data "aws_region" "current" {}

data "aws_vpc_endpoint_service" "ecr_dkr" {
  service_type = "Interface"
  service      = "${data.aws_partition.current.reverse_dns_prefix}.${data.aws_region.current.name}.ecr.dkr"
}
```

although this will only succeed in the `cn-north-1` region.

This is the code at fault:

https://github.com/hashicorp/terraform-provider-aws/blob/c63960b8b9bc6a8890dced588075d480ed09cefd/aws/data_source_aws_vpc_endpoint_service.go#L92-L98

It should use the `ReverseDns` function added in #17142:

https://github.com/hashicorp/terraform-provider-aws/blob/c63960b8b9bc6a8890dced588075d480ed09cefd/aws/provider.go#L1528-L1537

**Comment by marcincuber** [comment]
@ewbankkit thanks for your response. I think that using `filter` until this is fixed is the better option (out of the two) that will work across different AWS partitions. 

Can you propose any time frames when this issue will be fixed or being worked on?
