### ISSUE TITLE
Lambda datasource that returns multiple functions and allows filters

### ISSUE THREAD

**Issue by srkiNZ84** [hashicorp/terraform-provider-aws#17701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment, for AWS Lambda, there only appears to be a "aws_lambda_function" datasource that returns a single function and that you have to know the name of the function for: 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_function

This issue is a proposal is for a new "aws_lambda_functions" datasource that returns zero or more lambda functions based on a filter, like the "aws_instances" datasource (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/instances) but for Lambda functions.

Why?

I would like to use this datasource to feed it into a CloudWatch alarms resources and create an "alarm per function" to make it simpler to diagnose issues (in the current state, we have alarms which trigger if _any_ lambda throws an error, which leaves the task of figuring out which Lambda it was to the unfortunate operator).

There are possible other use cases, basically any situation where you need a list of Lambda functions to create a "per function" resource as an example

### New or Affected Resource(s)

* aws_lambda_functions (new datasource)

### Potential Terraform Configuration

```hcl
data "aws_lambda_functions" "test" {
  lambda_tags = {
    Environment = "Test"
  }

  filter {
    name   = "lambda.runtime"
    values = ["Python 3.7"]
  }
}

resource "aws_cloudwatch_metric_alarm" "lambda_error_alarm" {
  count                     = length(data.aws_lambda_functions.test.ids)
  alarm_name                = "${data.aws_lambda_functions.test.name[count.index]}-lambda-error"
  comparison_operator       = "GreaterThanOrEqualToThreshold"
  evaluation_periods        = "2"
  threshold                 = "5"
  period                    = "60"
  alarm_description         = "Alarm triggers when the number of Lambda invocation errors goes above 5 in a one minute period for two consecutive minutes"
  alarm_actions             = [aws_sns_topic.system_alarms.arn]
  metric_name               = "Errors"
  namespace                 = "AWS/Lambda"
  dimensions = {
        FunctionName = data.aws_lambda_functions.test.name[count.index]
  }
  statistic                 = "Sum"
  insufficient_data_actions = []
}

```

### References

N/A

**Comment by DrFaust92** [comment]
While there is a "ListFunctions" operations thats supported by the SDK, there isnt a way to filter by tags.
Adding the custom logic to filter after fetching is usually a maintenance burden as the api may expose this functionality later and break the provider's behaviour.

i believe maintainers wouldn't be for adding this custom logic if a data source for multiple lambda functions is added but ill leave the final say to them. just giving my two cents here.

A possible better solution that doesnt require custom logic is to implement the tagging group data source (corresponding to this https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html) that allows a generic solution for fetching resource by tag instead of service specific datasource.
