### ISSUE TITLE
Receiving error when trying to create a firewall manager policy

### ISSUE THREAD

**Issue by jmyork** [hashicorp/terraform-provider-aws#17710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.5 AWS provider v3.28.0

### Affected Resource(s)

* aws_fms_policy

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fms_policy

### Debug Output

<script src="https://gist.github.com/jmyork/98c81bedbb5116909acddc880f0035cb.js"></script>

### Expected Behavior

Firewall Manager Policy should have been created

### Actual Behavior

Error creating policy

### Steps to Reproduce

Using the example code run `terraform apply`

* #0000

**Comment by anGie44** [comment]
Hi @jmyork, thank you for raising this issue. Looking at the gist content looks like the line to focus on is:
```
policy.securityServicePolicyData.managedServiceData&#39; failed to satisfy constraint: Member must satisfy regular expression pattern: .*
```

So since the argument doesn't allow for whitespace characters like carriage returns used in resource's `Example Usage` ,  I'd recommend using the terraform [jsonencode](https://www.terraform.io/docs/language/functions/jsonencode.html) function to get a JSON-friendly string e.g.
```hcl
resource "aws_fms_policy" "example" {
  # other config

  security_service_policy_data {
    type = "WAF"

    managed_service_data = jsonencode({
        type = "WAF",
        ruleGroups = [{
            id = "${aws_wafregional_rule_group.test.id}"
            overrideAction = {
              type = "COUNT"
            }
          }]
        defaultAction = {
          type = "BLOCK"
        }
        overrideCustomerWebACLAssociation = false
      })
  }
}
``` 

hope the above helps! if you encounter other issues, please reach out 👍  
i'll keep this issue open to track the need to update our documentation

**Comment by jmyork** [comment]
@anGie44 that worked!  Thank you so so very much!

**Comment by anGie44** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/17714
