### ISSUE TITLE
tests/api_gateway_domain_name: Inconsistent result on Terraform 0.15.0-alpha

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17776]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Acceptance Test

`TestAccAWSAPIGatewayDomainName_MutualTlsAuthentication` produces inconsistent results after apply on Terraform v0.15.0-alpha:

```
    resource_aws_api_gateway_domain_name_test.go:299: Step 1/3 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_s3_bucket_object.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        
--- FAIL: TestAccAWSAPIGatewayDomainName_MutualTlsAuthentication (102.25s)
```

### Affected Resources

* aws_api_gateway_domain_name

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_bucket" "test" {
  bucket = "yaket"

  force_destroy = true

  versioning {
    enabled = true
  }
}

resource "aws_s3_bucket_object" "test" {
  bucket = aws_s3_bucket.test.id
  key    = "yaket"
  source = "test-fixtures/apigateway-domain-name-truststore-1.pem"
}

resource "aws_api_gateway_domain_name" "test" {
  domain_name              = aws_acm_certificate.test.domain_name
  regional_certificate_arn = aws_acm_certificate_validation.test.certificate_arn
  security_policy          = "TLS_1_2"

  endpoint_configuration {
    types = ["REGIONAL"]
  }

  mutual_tls_authentication {
    truststore_uri     = "s3://${aws_s3_bucket_object.test.bucket}/${aws_s3_bucket_object.test.key}"
    truststore_version = aws_s3_bucket_object.test.version_id
  }
}
```

### References

* https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210

**Comment by apparentlymart** [comment]
Hi @YakDriver,

In the past when I've seen this error it's been caused by an eventual consistency problem where the provider tries to read back what it just created as part of returning from `Create` (the typical `return resourceS3BucketRead(...)` pattern) but the remote API doesn't have read-after-write consistency and so the read ends up producing a "not found", signaled to Terraform Core by returning a null object, which is what in turn causes Terraform to report the "now absent" in this error message.

Do you think that could be a possible explanation in this case? It does seem like this particular resource type is using the aforementioned pattern:

https://github.com/hashicorp/terraform-provider-aws/blob/7546a7f44d9e0c2a7420f11daba9f65b00f95655/aws/resource_aws_s3_bucket_object.go#L293-L294

Based on the other code I see in there, I think we could confirm it by capturing the provider logs prior to that error to see if we're entering this branch:

https://github.com/hashicorp/terraform-provider-aws/blob/7546a7f44d9e0c2a7420f11daba9f65b00f95655/aws/resource_aws_s3_bucket_object.go#L316-L320

I'm happy to look a bit deeper on the core side if it seems like something different is happening here, of course!

**Comment by bflad** [comment]
A simple resource change to show a Terraform AWS Provider error instead of the Terraform CLI error in this case is to implement `d.IsNewResource()` checks before potentially returning `d.SetId("")` on creation, e.g. https://github.com/hashicorp/terraform-provider-aws/issues/16796

To also mitigate the eventual consistency issues, a pattern such as [Resource Lifecycle Retries](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#resource-lifecycle-retries) can be adopted.

**Comment by YakDriver** [comment]
Cool. Thanks for the input! It looks like straightforward fixes needed on the AWS provider side.
