### ISSUE TITLE
data aws_s3_bucket_object doesn't read s3 object (inconsistent behaviour)

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform-provider-aws#17831]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
❯ terraform version
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.29.1
```

### Affected Resource(s)

* [data "aws_s3_bucket_object"](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/s3_bucket_object)

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_s3_bucket_object" "json_values" {
  bucket = var.s3_bucket

  # This does not work "ContentType": "binary/octet-stream" but work with "ContentType": "application/json"
  key = "folder/subfolder/outputs.json"

 # This works for both "ContentType": "binary/octet-stream" and "ContentType": "application/json"
  key = "outputs.json"
}
```

### Expected Behavior

The behaviour should be consistent with root level keys or nested keys in the s3 bucket

### Actual Behavior

`data.aws_s3_bucket_object.json_values.body` is empty when "ContentType": "binary/octet-stream" in nested keys.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

* #5248

**Comment by bflad** [comment]
Hi @vikas027 👋  Thank you for raising this and sorry you ran into trouble here.

This behavior is currently expected and noted in the [`aws_s3_bucket_object` data source documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/s3_bucket_object). Saving non-UTF-8 data into the Terraform State can corrupt it, which is why this restriction is in place. If we can improve the documentation, please let us know or feel free to submit a pull request to the `website/docs/d/s3_bucket_object.html.markdown` file.

It is worth noting that we could potentially do two other things here, which is why I marked this as an enhancement:

* Switch the resource implementation to Terraform Plugin SDK version 2 and return a warning diagnostic in this case. Caveat: Warning diagnostics behavior is only stable in Terraform 0.15.0 and later.
* Add a base64 attribute, which is always available and safe to save in the Terraform State. Caveat: Downloading large contents into the Terraform State could have performance and gRPC considerations that prevent the provider from working correctly.
