### ISSUE TITLE
aws_cloudfront_distribution.Nexus: PreconditionFailed: The request failed because it didn't meet the preconditions in one or more request-header fields.

### ISSUE THREAD

**Issue by shambhu9803** [hashicorp/terraform-provider-aws#17841]
Terraform v0.14.3

provider registry.terraform.io/hashicorp/aws v.29.1
Terraform destroy of cloudfornt gets precondition failed error wit 0.14.3 version but works fine with lower version like 0.12.24.

#14993 (comment) related to this

**Comment by shambhu9803** [comment]
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v.29.1

Terraform destroy of cloudfornt gets precondition failed error wit 0.14.3 version but works fine with lower version like 0.12.24.

**Comment by shambhu9803** [comment]
I tested with lower version of 14. The cloudfront have no problem with destruction up to the 14.2 version. From 14.3 to 14.7 it starts throwing the error above.

**Comment by yhrabovskyinomi** [comment]
faced same problem 
v0.14.8
aws provider v3.32.0

**Comment by antonbabenko** [comment]
Make sure to run `terraform refresh`, so that `Etag` property on CloudFront is not updating before Terraform tries to delete the resource.

**Comment by breathingdust** [comment]
Hi @shadabahmed 👋 If this is still an issue can you resubmit the issue using the issue template? The issue doesn't include enough information for the maintainers or community to help you with.

**Comment by SaulSilver** [comment]
> Make sure to run `terraform refresh`, so that `Etag` property on CloudFront is not updating before Terraform tries to delete the resource.

Note: Terraform has deprecated `terraform refresh` and doesn't recommend using it. As it says on their [docs](https://www.terraform.io/cli/commands/refresh)
> Warning: This command is deprecated, because its default behavior is unsafe if you have misconfigured credentials for any of your providers. See below for more information and recommended alternatives.

**Comment by enzolupia** [comment]
Same issue with terraform 0.15.5 also during updates, I can destroy the Cloudfront resource and re-create it, but I cannot perform any update.

> Error: error updating CloudFront Distribution (E2RGM05Q24PAMN): PreconditionFailed: The request failed because it didn't meet the preconditions in one or more request-header fields.

 ```terraform refresh ``` didn't help, nor ```terraform apply -refresh-only```.

**Comment by PanadeEdu** [comment]
Facing the same issue. Why is this closed without any resolving message?

**Comment by hawada96** [comment]
I am having the same problem as well.

**Comment by manospasj** [comment]
I believe this needs to be re-opened. AWS suggests to send a GetDistributionConfig request to get the current configuration and Etag header, before updating a CloudFront Distribution. Since this is a required step, I think it makes sense to implement it in the AWS Provider.

Please read
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_UpdateDistribution.html

**Comment by hawada96** [comment]
I've found that this error is only occurring if I have attached a (custom) cache policy to the `cache_policy_id` argument under the `default_cache_behavior` block. _Have not yet tested anything else at the moment_. Otherwise I can modify the distribution freely (apply new changes using terraform) if I just use the `forwarded_values` block in the `default_cache_behavior` block instead.

```
Terraform v.1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.12.1

```

**Comment by tl-keerthivasan** [comment]
Me facing the same error on performing updates in CloudFront!
