### ISSUE TITLE
terraform plan/apply does not detect drift in credit_specification

### ISSUE THREAD

**Issue by satyamsareen** [hashicorp/terraform-provider-aws#17856]
My configuration contains `ami`, `instance_type`, and `subnet_id`.
`instance_type`= t2.micro
`ami`= Amazon Linux 2 64bit x86

main.tf:

```
provider "aws" {
  region="ap-south-1"
}
 
resource "aws_instance" "tec3"{
    ami=var.image_id
    instance_type=var.instance_type
    subnet_id=var.default_subnet
}
```

When I add any `tags` from the AWS console; terraform apply removes them. 
When I enable `disable_api_termination`, terraform apply changes it back to `false`.
Which is justified, as they are not present in the desired configuration.
But when I change `credit_specification` to `unlimited`, terraform apply doesn't change it back to `standard` which is the default value.
It looks like a bug to me as terraform is not able to detect drift for `credit_specification`.

**Comment by bflad** [comment]
Hi @satyamsareen 👋  Thank you for raising this issue.

The `aws_instance` resource does not currently perform drift detection for the `credit_specification` block if it is not present in the configuration. This is to prevent all practitioners from needing to declare it for every burstable instance type, whether or not they are customizing the behavior.

Can you confirm that adding the block with the incorrect value, e.g.

```terraform
resource "aws_instance" "tec3"{
  ami           = var.image_id
  instance_type = var.instance_type
  subnet_id     = var.default_subnet

  credit_specification {
    cpu_credits = "standard"
  }
}
```

Will trigger the expected `terraform plan` difference? The documentation does not currently specify this requirement, so I am going to relabel this issue for that.

**Comment by satyamsareen** [comment]
Hello @bflad, thank you for the response.
`terraform plan` does detect drift in `credit_specification` when mentioned in the configuration explicitly.
Quick question; what could be the motivation behind `terraform plan` not detecting drift for certain attributes and if so
Such attributes should be mentioned in the documentation as they can create some blind spots in the infrastructure.

**Comment by bflad** [comment]
> Quick question; what could be the motivation behind terraform plan not detecting drift for certain attributes

This typically depends on the API implementation. Terraform Providers must tell Terraform CLI if an attribute, that is not configured by the practitioner, might receive a value to put into the Terraform State. Terraform Providers will typically always refresh all values into the Terraform State, whether configured or not. That is the case with `credit_specification`.

Two other considerations do come to mind as well:

* If the API has multiple default return values for an attribute based on other configuration, but the return value is optional to configure (such as unlimited versus standard being flipped between t2 and t3 instance types), then we typically will not enable drift detection for the attribute to prevent confusion.
* If the API response begins to return a structure (such as `CreditSpecification` in the `DescribeInstances` case) in the majority of cases for new functionality, we typically will not "break" existing configurations when implementing the new functionality. Disabling drift detection for the configuration block is the easiest way to ensure correctness for Terraform Providers to implement this type of change, otherwise the implementation must fully know and implement all scenarios when the block may be returned into the Terraform State to signal to Terraform CLI the final value after applying.

In general, the recommendation is that Terraform configurations should be explicitly filled in with values that are of concern. This will always enable drift detection on those values assuming they can be refreshed from the API.

**Comment by bflad** [comment]
@SatoruItaya is there anything else I can help answer? The documentation update for the `credit_specification` configuration block has been merged and will publish with our next release.

**Comment by SatoruItaya** [comment]
@bflad You seem to have mentioned me by mistake.:sweat_smile:

**Comment by satyamsareen** [comment]
@bflad, Thankyou for the help
Cheer!
