### ISSUE TITLE
aws_eks_cluster data source support for tag queries

### ISSUE THREAD

**Issue by taiidani** [hashicorp/terraform-provider-aws#17855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EKS clusters can sometimes be created with unique and random names or suffixes to ease the burden of recreation when properties are changed. This pattern can make it difficult to use those clusters in downstream or adjacent root modules without leveraging practices such as outputs and `terraform_remote_state`.

Currently the [aws_eks_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_cluster) data source supports `name`-based querying of existing clusters. Supporting a `tags` query as well would allow easier discovery of these clusters, enabling cross-root-module patterns without copy-pasting unique IDs or using outputs.

Examples of precedent here include:
* [aws_vpc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc)
* [aws_security_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/security_group)
* [aws_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/instance)

### New or Affected Resource(s)

* [aws_eks_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_cluster)

### Potential Terraform Configuration

```hcl

data aws_eks_cluster example {
  # name = "example-cluster-jcmqf" # Example of hardcoded name

  tags = {
    Name = "example-cluster"
  }
}

output endpoint {
  value = data.aws_eks_cluster.example.endpoint
}
```

**Comment by taiidani** [comment]
Note -- I plan to file a PR against this issue to try and close it.

**Comment by bflad** [comment]
Hi @taiidani 👋  Thank you for suggesting this and it would certainly be helpful to many people.

The EKS API does not appear to natively support this type of functionality at this time in the [ListClusters](https://docs.aws.amazon.com/eks/latest/APIReference/API_ListClusters.html) or other API operations. Since the AWS service API doesn't directly support it and the [Terraform AWS Provider's boundaries are typically the AWS Go SDK for those service APIs](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#api-and-sdk-boundary), this unfortunately leaves us in a position where this is not something we would add to this particular codebase at this time. If the AWS service API does implement this type of functionality in the future, we would be happy to take a fresh look into implementing it. Until then, I'm going to close this issue as there is no action for us to take right now.

While it may also be technically possible to implement client-side support within the provider logic, we are not accepting these types of implementations currently due to maintenance and behavior concerns.

That being said, there are a few potential paths forward for everyone here in the meantime:

* The Resource Groups Tagging API may offer a generic solution for APIs that do not natively implement tag-based filtering, which we could support as its own data source. Please see https://github.com/hashicorp/terraform-provider-aws/issues/17705 for more information about that.
* Checking the [AWS Containers Roadmap issues](https://github.com/aws/containers-roadmap/issues) to ensure this feature request is covered in that public forum
* Submitting a feature request AWS Support case, which the service team can use to help prioritize the functionality

**Comment by taiidani** [comment]
Hi @bflad, agreed on your conclusion -- my early research ended up showing me the same issue with the missing SDK features. I'd have had to implement it either by enumerating `ListClusters` (extremely expensive and, to your point, client-side) or using the Resource Groups Tagging API.

Looking at #17705 it seems this is already well on its way to being merged. Once in I would expect this issue's use case to be fulfilled with:

```tf
data aws_resourcegroupstaggingapi_resources filter {
  resource_type_filters = ["eks:cluster"]

  tag_filters {
    key = "Name"
    values = ["example-cluster"]
  }
}

locals {
  cluster_arn  = data.aws_resourcegroupstagging_resources.filter.resource_tag_mapping_list[0].resource_arn
  cluster_name = regex("^arn:aws:eks:.+:\\d+:cluster\\/(.+)$", local.cluster_arn)[0] # Or split() if you can be less strict
}

data aws_eks_cluster example {
  name = local.cluster_name
}

output endpoint {
  value = data.aws_eks_cluster.example.endpoint
}
```

It's not the most attractive Terraform I've written, but it should be able to translate an existing EKS Cluster looked up by `Name` tag to the cluster's actual AWS name so that it can pass into the `aws_eks_cluster` data source.
