### ISSUE TITLE
Add `vpc_security_group_ids` to `aws_eks_node_group`

### ISSUE THREAD

**Issue by bappr** [hashicorp/terraform-provider-aws#17863]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hey guys,

Currently there is no way to add a security group id on our eks node groups.
Meaning we lost the possibility to open our node groups to a full sg.
Since this is available for simple `aws_instance` and since node groups are ultimately just ec2 instances, I think we should be able to do so too. It is also possible to set it in `aws_eks_cluster` under `vpc_config.security_group_ids`.

Thanks,
Ben

### New or Affected Resource(s)

* aws_eks_node_group

**Comment by bflad** [comment]
Hi @bappr 👋  Thank you for suggesting this and it would certainly be helpful to many people.

The EKS API does not appear to support this type of functionality at this time in the [CreateNodegroup](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html) or other API operations. Since the AWS service API doesn't directly support it and the [Terraform AWS Provider's boundaries are typically the AWS Go SDK for those service APIs](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#api-and-sdk-boundary), this unfortunately leaves us in a position where this is not something we would add to this particular codebase at this time. If the AWS service API does implement this type of functionality in the future, we would be happy to take a fresh look into implementing it. Until then, I'm going to close this issue as there is no action for us to take right now.

That being said, there are a few potential paths forward for everyone here in the meantime:

* Checking the [AWS Containers Roadmap issues](https://github.com/aws/containers-roadmap/issues) to ensure this feature request is covered in that public forum
* Submitting a feature request AWS Support case, which the service team can use to help prioritize the functionality
