### ISSUE TITLE
Feature request: Add partner_event_bus_name as an argument for  "aws_cloudwatch_event_rule" & "aws_cloudwatch_event_target"

### ISSUE THREAD

**Issue by fadwamen** [hashicorp/terraform-provider-aws#17887]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description 
ADD a "partner_event_bus_name" argument that support the / character of the autogenerated name of partner_event_bus  " into ressource "aws_cloudwatch_event_rule"  & "aws_cloudwatch_event_target"  in order to make possible the association of these ressources with an existing **partner_event_bus** 

### New argument(s)
partner_event_bus_name

###Affected Resource(s)
- aws_cloudwatch_event_rule
- aws_cloudwatch_event_target

### Terraform CLI and Terraform AWS Provider Version
```hcl
> terraform -v 

Terraform v0.13.5 
+ provider registry.terraform.io/hashicorp/aws v3.30.0
```

### Potential Terraform Configuration
```hcl
resource "aws_cloudwatch_event_rule" "Example" {
  name        = "capture-aws-sign-in"
  partner_event_bus_name = "aws.partner/appflow/salesforce.com/example"
  description = "Capture each AWS Console Sign In"

  event_pattern = <<EOF
{
  "detail-type": [
    "AWS Console Sign In via CloudTrail"
  ]
}
EOF
}
```

### References
pull-requests
#16815
Issue:
#16431

**Comment by bflad** [comment]
Hi @fadwamen 👋  Thank you for raising this.

It appears that the underlying EventBridge API ([`PutRule`](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutRule.html) / [`PutTarget`](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutTargets.html)) supports only a single `EventBusName` field matching the `event_bus_name` argument in Terraform across the various `aws_cloudwatch_event_bus`, `aws_cloudwatch_event_rule`, and `aws_cloudwatch_event_target` resources. What seems to be missing is that the validation for the existing arguments in Terraform should allow `/` characters, so that `aws.partner/...` can be passed in.

This change appears to be covered already by #16431 and #16815, so to consolidate efforts and discussions on this topic and since this feature request would not match the design of the Terraform AWS Provider as written, I'm going to close this issue. Please 👍  react and subscribe to those for further updates on this. Thank you again for submitting this proposal.
