### ISSUE TITLE
Incorrect/misleading documentation

### ISSUE THREAD

**Issue by ablackrw** [hashicorp/terraform-provider-aws#17903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.30.0
```

### Affected Resource(s)

* data.aws_ami
* aws_instance

### Terraform Configuration Files

The following is a functional/valid terraform configuration which demonstrates the documentation/implementation mismatch.
```hcl
terraform {
  required_version = "~> 0.14.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.30"
    }
  }
}

data "aws_ami" "amzl2" {
  most_recent = true

  filter {
    name   = "name"
    values = ["amzn2-ami-minimal-hvm-*-arm64-ebs"]
  }

  filter {
    name   = "architecture"
    values = ["arm64"]
  }

  owners = ["amazon"]
}

resource "aws_instance" "template" {
  ami                    = data.aws_ami.amzl2.id
  instance_type          = "t4g.small"
  root_block_device {
    volume_size = max(8,data.aws_ami.amzl2.block_device_mappings.*.ebs.volume_size[0])
  }
}

output "size" {
  value = aws_instance.template.root_block_device.0.volume_size
}
```

### Important Factoids

Please note the somewhat awkward construct `foo.*.baz[0]` in the `resource aws_instance.template` block. The [documentation ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami)for data.aws_ami suggests that desired lookup being performed can be written as `data.aws_ami.amzl2.block_device_mappings.0.ebs.volume_size`, but attempting to do so will result in the following error when running `terraform plan`
```
Error: Invalid index

  on testcase.tf line 31, in resource "aws_instance" "template":
  31:     volume_size = max(8,data.aws_ami.amzl2.block_device_mappings.0.ebs.volume_size)

This value does not have any indices.
```
This error is a result of the `block_device_mappings` structure being a set rather than a list. 

A similar (though less noticeable) issue is found in the `output size` block. In that case, it is necessary to perform an index lookup on the root_block_device list, even though this is a simple object.

### References

* hashicorp/terraform#27949

**Comment by bflad** [comment]
Hi @ablackrw 👋  Thank you for raising this. The documentation can certainly be improved here and I will submit changes shortly.

To accomplish what you are trying to do with the [`max()` function](https://www.terraform.io/docs/language/functions/max.html), Terraform does also support collection expansion into function arguments via an ellipsis syntax, e.g.

```terraform
max(8, data.aws_ami.amzl2.block_device_mappings[*].ebs.volume_size...)
```

If you are certain that there is only 1 element to the set and you want to access it directly, you can use the [`tolist()` function](https://www.terraform.io/docs/language/functions/tolist.html) in that case, e.g.

```terraform
max(8, tolist(data.aws_ami.amzl2.block_device_mappings)[0].ebs.volume_size)
```

In practice though, it may be safer to not make assumptions about the details of result set from a data source and instead use a `for`-`if` construct to ensure you are fetching the root device, e.g.

```terraform
max(8, [for d in data.aws_ami.amzl2.block_device_mappings : d.ebs.volume_size if d.device_name == "/dev/xvda"]...)
```

For any further usage questions, the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) would be the recommended place to go. 👍 

> A similar (though less noticeable) issue is found in the output size block. In that case, it is necessary to perform an index lookup on the root_block_device list, even though this is a simple object.

With this in particular, this is a limitation of the current Terraform Plugin SDK. Terraform Providers cannot return back object types directly, only single-type maps or lists/sets of objects. The `aws_ami` data source `block_device_mappings` `ebs` attribute is a rare case in this provider which opted for a single-type map(string) result instead of the more expected list of 1 element containing an object. You can see that with `terraform state show`, all the values are strings and its heavily reliant on Terraform CLI automatically converting between types which is why we try to avoid it.

I will also include updating this to be more clear via the attribute description. In the future, the documentation will be generated from the code itself and automatically include type descriptions in some form. Tracking for that can be found here: https://github.com/hashicorp/terraform-provider-aws/issues/15365
