### ISSUE TITLE
aws_cloudformation_stack disable_rollback value changed in AWS

### ISSUE THREAD

**Issue by waiariki-koia** [hashicorp/terraform-provider-aws#17913]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
- provider registry.terraform.io/hashicorp/aws v3.30.0
### Affected Resource(s)

* aws_cloudformation_stack

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

I submitted a ticket with AWS Support and these are the config files they used to reproduce the bug.

**Step 1**
```hcl
resource "aws_cloudformation_stack" "sample-terraform-stack" {
  name = "sample-terraform-stack"
  disable_rollback = true
  template_body = <<STACK
AWSTemplateFormatVersion: 2010-09-09

Resources: 
  Application1:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: ECS
  STACK
}
```
Apply this.

**Step 2**
Notice the small change from `Application1` to `Application2`
```hcl
resource "aws_cloudformation_stack" "sample-terraform-stack" {
  name = "sample-terraform-stack"
  disable_rollback = true
  template_body = <<STACK
AWSTemplateFormatVersion: 2010-09-09

Resources: 
  Application2:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: ECS
  STACK
}
```
Apply this

**Step 3**
Notice the small change from `ComputePlatform: ECS` to `ComputePlatform: Server`
```hcl
resource "aws_cloudformation_stack" "sample-terraform-stack" {
  name = "sample-terraform-stack"
  disable_rollback = true
  template_body = <<STACK
AWSTemplateFormatVersion: 2010-09-09

Resources: 
  Application2:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server
  STACK
}
```
### Expected Behavior

Terraform doesn't want to destroy and recreate the Cloudformation resource, based on value change from AWS.

### Actual Behavior
It seems AWS has changed its functionality (still waiting on response from AWS Support for confirmation), where they automatically change the `DisableRollback` field to be `False` on their side, even though we have it set to `True`.

Due to this, Terraform wants to destroy and recreate the resource, causing underlying resources to be destroyed and created.

```shell
  ================================================================
  Terraform will perform the following actions:

    # aws_cloudformation_stack.sample-terraform-stack must be replaced
  -/+ resource "aws_cloudformation_stack" "sample-terraform-stack" {
        ~ disable_rollback = false -> true # forces replacement
        ~ id               = "arn:aws:cloudformation:eu-west-1:*****************:stack/sample-terraform-stack/*****************" -> (known after apply)
          name             = "sample-terraform-stack"
        ~ outputs          = {} -> (known after apply)
        ~ parameters       = {} -> (known after apply)
        + policy_body      = (known after apply)
        - tags             = {} -> null
        ~ template_body    = <<~EOT
              AWSTemplateFormatVersion: 2010-09-09
              
              Resources: 
                Application5:
                  Type: AWS::CodeDeploy::Application
                  Properties:
            -       ComputePlatform: ECS
            +       ComputePlatform: Server
          EOT
      }

  Plan: 1 to add, 0 to change, 1 to destroy.
  ================================================================
```

### Steps to Reproduce

1. Use config in Step 1
2. `terraform apply`
3. Update config to that in Step 2
4. `terraform apply`
5. Update config to that in Step 3
6. `terraform plan`

**Comment by MitchellGerdisch** [comment]
Note that this happens even if nothing is changed in the code.
If `disable_rollback = true` subsequent `terraform apply` calls with NO changes to the code will cause a destroy/create replacement action.

**Comment by pshuman-heb** [comment]
I'm fairly sure that this is an issue on the Provider. If I create a Cloudformation stack with the AWS CLI and use `--disable-rollback` it behaves as you'd expect, and the AWS API returns `"DisableRollback": true` on a Describe of the Stack. It seems to be that the Provider isn't correctly setting the flag in the first place in AWS.

**Comment by pshuman-heb** [comment]
So, I did a little more digging on this. It appears that the issue is around the `on_failure` flag being mutually exclusive with the `disable_rollback` flag. From what I can tell, `on_failure = "DO_NOTHING"` literally causes the same state in AWS as `disable_rollback = true`. Setting either in TF causes a state in AWS where a  `describe_stacks` call will return `"DisableRollback": true`. 

I'm thus seeing cases where the API, both in a bare `describe_stacks` call, and in the response that Terraform says it's getting from the Go SDK when logging in `DEBUG`, shows that the Stack has `"DisableRollback": true`, but Terraform will still say that it needs to redeploy the Stack because it thinks it's set to `false`. 

I'm not well-versed enough in how the provider works to understand why it's misreading the return from the Describe call, but potentially it has something to do with [this block](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_cloudformation_stack.go#L265-L269):

```go
	if stack.DisableRollback != nil {
		d.Set("disable_rollback", stack.DisableRollback)

		// takes into account that disable_rollback conflicts with on_failure and
		// prevents forced new creation if disable_rollback is reset during refresh
		if d.Get("on_failure") != nil {
			d.Set("disable_rollback", false)
		}
	}
```

Is that `on_failure` conditional somehow always evaluating to `true`, and thus leading to `disable_rollback` always being set to false?

**Comment by pshuman-heb** [comment]
So, doing a little more digging, I'm not sure exactly what the correct behavior is here. It appears that the MR that was merged here https://github.com/hashicorp/terraform-provider-aws/pull/10539 is essentially causing the issues we're seeing above, as I expected. This all stems from the fact that there's a 2 -> 1 mapping from input parameters to the state of the `disable_rollback` field on the stack. This leads to these desired scenarios:

1. The `disable_rollback` parameter behaves as you'd expect, the value passed in mapping to the value in AWS. 
2. If you use `on_failure` instead, you should expect the following:
  - `DO_NOTHING` becomes `disable_rollback = true`
  - `DELETE` and `ROLLBACK` become `disable_rollback = false`
3. The more complex case, seemingly the one that caused the original change: imports are non-deterministic. There's no actual way to tell during an import if `disable_rollback = true` is because someone set `disable_rollback = true` or if they set `on_failure = "DO_NOTHING"`

I'm not familiar with how this provider is structured to have a good plan to fix it at this point, but I'll keep looking into it in my free time.

That said, you can likely work around this by setting 

```terraform
lifecycle {
  ignore_changes = [
    disable_rollback
  ]
}
```

since it's unlikely you actually care about the value of `disable_rollback` after the stack is created.

**Comment by atheiman** [comment]
I dont think this should have been closed? I am still getting this forced replacement on any update when specifying `disable_rollback = true`.
