### ISSUE TITLE
aws_mq_broker RabbitMQ general logs cannot be enabled

### ISSUE THREAD

**Issue by larrytkl** [hashicorp/terraform-provider-aws#18067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.32.0

### Affected Resource(s)
* aws_mq_broker

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_mq_broker" "rabbitmq" {
  broker_name = "my-broker"
  engine_type = "RabbitMQ"
  engine_version = "3.8.6"
  // enabling cloudwatch logging
  logs {
    general = true
  }

```

### Debug Output

```
Terraform will perform the following actions:

  # aws_mq_broker.rabbitmq will be created
  + resource "aws_mq_broker" "rabbitmq" {
      + apply_immediately          = false
      + authentication_strategy    = "SIMPLE"
      + broker_name                = "my-broker"
      + deployment_mode            = "SINGLE_INSTANCE"
      + engine_type                = "RabbitMQ"
      + engine_version             = "3.8.6"

      + logs {
          + general = true
        }
```

### Panic Output

```
Error: BadRequestException: Audit logging is not supported for RabbitMQ brokers.
```

### Expected Behavior

General logging via CloudWatch should be enabled, given that `logs` configuration only specify `general` and omitted `audit`

### Actual Behavior

```
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "..."
  },
  ErrorAttribute: "logs.audit",
  Message_: "Audit logging is not supported for RabbitMQ brokers."
}
Audit logging is not supported for RabbitMQ brokers
```

### Steps to Reproduce

Create aws_mq_broker RabbitMQ resource enabling just logs `general`.

1. `terraform apply`

### Important Factoids

Specifying `audit = null` also yields same outcome.

### References

* #0000 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#logs

**Comment by anGie44** [comment]
Hi @larrytkl, thank you for raising this issue and apologies you came across unexpected behavior. 

The root cause here is related to 2 factors, 1 related to the underlying modeling of the configuration data and the other related to the AWS API's request validation. Possible solutions may include changing the `logs` nested fields' data types, i.e. represent the `audit` and `general` fields as Strings instead of booleans to be able to determine if the fields were configured since unset values will be identifiable as empty strings (`""`). Thus, we'll only send non-empty values in the request, making the AWS API request validation happy. 

For more details on the issue at hand:
(1) within the `aws_mq_broker` resource code, we're not able to distinguish if the nested boolean value was configured in a terraform configuration or if the boolean value is the "zero" value i.e. un-configured default (in this case, `false`).  so when the `logs` configuration values are expanded in the function below, the API request is always populated with both the `Audit` and `General` fields in the `mq.Logs` struct as the `logs` configuration block (internally represented as a map) has keys that are either mapped to what was configured in Terraform or the default when not configured.

https://github.com/hashicorp/terraform-provider-aws/blob/b4205b93ee3ae4c1398e1a5076f8e87fcb1b93ef/aws/resource_aws_mq_broker.go#L923-L941

so in the example provided, when `logs` is configured as 
```hcl
logs {
  general = true
}
```
the map being expanded with the func `expandMqLogs` is represented as
```go
map[string]interface{}{
    "audit" : false,
    "general": true,
}
```
resulting in an API request (which should be visible when running `terraform apply` with the environment variable `TF_LOG=debug`) that contains:
```go
"logs":{"audit":false,"general":true}
```
(2) given this data being sent in the AWS API request, it only is problematic when the engine_type is `RabbitMQ` even though technically the data being sent over does not imply enabling of `Audit` logging.

**Comment by larrytkl** [comment]
Thank you @anGie44 for the analysis. Switching to Strings may help in generating the API request payload without the audit field and that will satisfy the payload structure specified in https://docs.aws.amazon.com/amazon-mq/latest/api-reference/brokers.html#brokers-model-logs , and also should satisfy the validation we observed. By the same token that applies for `general`.
