### ISSUE TITLE
Imported aws_cloudformation_stack recreation forced when on_failure is set.

### ISSUE THREAD

**Issue by BlessJah** [hashicorp/terraform-provider-aws#1807]
### Terraform Version

v0.10.7

### Affected Resource(s)

- aws_cloudformation_stack

### Terraform Configuration Files
```hcl
variable "aws_access_key" {}
variable "aws_secret_key" {}

provider "aws" {
  access_key = "${var.aws_access_key}"
  region     = "eu-west-1"
  secret_key = "${var.aws_secret_key}"
}

resource "aws_cloudformation_stack" "storage" {
  name = "terraform-test"
  on_failure = "DELETE"
  template_body = "${ file("../cf/v1.yml") }"
}
```

```
$ terraform apply
    aws_cloudformation_stack.storage: Creating...
    [...]
    aws_cloudformation_stack.storage: Creation complete after 38s (ID: arn:aws:cloudformation:eu-west-1:629220...t/9fc286c0-a8f1-11e7-a0b8-50faeb5cc8d2)

    Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ rm terraform.tfstate 

$ terraform import aws_cloudformation_stack.storage "arn:aws:cloudformation:eu-west-1:629220244241:stack/terraform-test/9fc286c0-a8f1-11e7-a0b8-50faeb5cc8d2"

    aws_cloudformation_stack.storage: Importing from ID "arn:aws:cloudformation:eu-west-1:629220244241:stack/terraform-test/9fc286c0-a8f1-11e7-a0b8-50faeb5cc8d2"...
    aws_cloudformation_stack.storage: Import complete!
      Imported aws_cloudformation_stack (ID: arn:aws:cloudformation:eu-west-1:629220244241:stack/terraform-test/9fc286c0-a8f1-11e7-a0b8-50faeb5cc8d2)
    aws_cloudformation_stack.storage: Refreshing state... (ID: arn:aws:cloudformation:eu-west-1:629220...t/9fc286c0-a8f1-11e7-a0b8-50faeb5cc8d2)

    Import successful!

    The resources that were imported are shown above. These resources are now in
    your Terraform state and will henceforth be managed by Terraform.

$ terraform plan
    Refreshing Terraform state in-memory prior to plan...
    The refreshed state will be used to calculate this plan, but will not be
    persisted to local or remote state storage.

    aws_cloudformation_stack.storage: Refreshing state... (ID: arn:aws:cloudformation:eu-west-1:629220...t/9fc286c0-a8f1-11e7-a0b8-50faeb5cc8d2)

    ------------------------------------------------------------------------

    An execution plan has been generated and is shown below.
    Resource actions are indicated with the following symbols:
    -/+ destroy and then create replacement

    Terraform will perform the following actions:

    -/+ aws_cloudformation_stack.storage (new resource required)
          id:            "arn:aws:cloudformation:eu-west-1:629220244241:stack/terraform-test/9fc286c0-a8f1-
11e7-a0b8-50faeb5cc8d2" => <computed> (forces new resource)
           name:          "terraform-test" => "terraform-test"
           on_failure:    "" => "DELETE" (forces new resource)
           outputs.%:     "1" => <computed>
          parameters.%:  "0" => <computed>
          policy_body:   "" => <computed>
          template_body: "---\nAWSTemplateFormatVersion: 2010-09-09\n\nOutputs:\n  OldS3Bucket:\n    Value: !Ref OldS3Bucket\n\nResources:\n  OldS3Bucket:\n    Type: \"AWS::S3::Bucket\"\n    Properties:\n      AccessControl: Private\n" => "---\nAWSTemplateFormatVersion: 2010-09-09\n\nOutputs:\n  OldS3Bucket:\n    Value: !Ref OldS3Bucket\n\nResources:\n  OldS3Bucket:\n    Type: \"AWS::S3::Bucket\"\n    Properties:\n      AccessControl: Private\n"


    Plan: 1 to add, 0 to change, 1 to destroy.
[...]
```

### Expected Behavior
Subsequent `terraform plan` and `terraform apply` should not recreate imported stack.

### Actual Behavior
Subsequent `terraform plan` and `terraform apply` will remove imported stack and recreate it. The same behavior is also observed on `on_failure` parameter was changed. As per documentation 

    on_failure - (Optional) Action to be taken IF STACK CREATION FAILS.[...]

(https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html#on_failure)

The parameter changes should have no effect on already existing stack.

### Steps to Reproduce
1. `terraform apply`
1. `rm terraform.tfstate`
1. `terraform import aws_cloudformation_stack.storage arn[...]`
1. `terraform plan`

Or
1. `terraform apply`
1. `sed -i '/on_failure/s/DELETE/ROLLBACK/' master.tf`
1. `terraform plan`

### References
- https://github.com/terraform-providers/terraform-provider-aws/issues/1331
- https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html#on_failure
- https://github.com/terraform-providers/terraform-provider-aws/pull/1432

**Comment by radeksimko** [comment]
Hey @BlessJah 
this is complicated mainly because the CloudFormation API doesn't expose the `OnFailure` once the stack was already created: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Stack.html

If it did we wouldn't run into this situation at all.

To your PR - We can't quite remove the `ForceNew` because it's just not updatable field and it should be surfaced as such to the user - i.e. we _need_ to recreate the stack if user decides to change the value there.

My suggestion would be to not treat this as a bug after all and just make `on_failure = ""` or leave it out completely. Would this cause any particular issue to you?

**Comment by BlessJah** [comment]
The `OnFailure` has no effect on stack that was already created. Actually I think it's discarded as soon as `CREATE_COMPLETE` is reached, so it's not field at all.

Removing `ForceNew` seems to solve all cases I've manually tested.

https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html

> **OnFailure**
> Determines what action will be taken if stack creation fails. This must be one of: DO_NOTHING, ROLLBACK, or DELETE. You can specify either OnFailure or DisableRollback, but not both.

**Comment by radeksimko** [comment]
> The OnFailure has no effect on stack that was already created. Actually I think it's discarded as soon as CREATE_COMPLETE is reached, so it's not field at all.

That's exactly why it should remain as `ForceNew` - otherwise people might think it's updatable field, when it's not. If we made it "updatable" (by removing ForceNew) we'd be just ignoring the field during update and tell the user "it's ok, it's been updated" in green colour. That's not what Terraform users generally expect.

> Removing ForceNew seems to solve all cases I've manually tested.

It may look like it works, but it just updates the field in state, sending nothing to the API, so effectively you're making it no-op.

> My suggestion would be to not treat this as a bug after all and just make on_failure = "" or leave it out completely. Would this cause any particular issue to you?

I know it may not sound like a perfect solution, but I can't think of any better one (which wouldn't negatively affect other users).

**Comment by BlessJah** [comment]
Making `on_failure` changes no-op on all operations but stack creation (or recreation) is exactly what it should be IMO.

The argument answers question "What to do if stack creation failed?". The question is never asked on stack updates, unless other arguments force terraform to (re)create the stack in which case the new argument value will be sent to API.

Is there any other scenario in which `on_failure` would change stack behavior?

**Comment by radeksimko** [comment]
Hi @BlessJah 

> The argument answers question "What to do if stack creation failed?". The question is never asked on stack updates

That's an implementation detail of the API which (unfortunately) may not be always obvious to the user.

If I applied the same logic to any field "What to do when resource x is created" then we'd basically defeat the purpose of `ForceNew`. It is there to signal the user that the field is not updatable.

I believe there's a reasonable workaround - i.e. making `on_failure = ""` in the config as part of importing it.

We're aware that this is a wider problem when importing resources across providers. I just created https://github.com/hashicorp/terraform/issues/16494 so we don't loose track of it.

With all the above - do you mind me closing this issue and associated PR?

**Comment by BlessJah** [comment]
> If I applied the same logic to any field "What to do when resource x is created" then we'd basically defeat the purpose of ForceNew. It is there to signal the user that the field is not updatable.

Do you agree that stacks created with different `on_failure` values are identical? If no, could you help me understand what the difference is?

**Comment by lorengordon** [comment]
I'm seeing this problem _without_ needing to import the cloudformation stack. Run an apply to create a stack with on_failure set, then run another apply immediately after changing nothing, and terraform wants to delete/create the stack.

**Comment by sousmangoosta** [comment]
Hi guys,

This `on_failure` parameter should not be `ForceNew` because it will never be used after the stack creation, if I set it in modules after ones creates his stack, it will be deleted without needs, but I need everyone who make his first deployment with that module to set `on_failure` option to `DELETE`.

**Comment by andresvia** [comment]
Hi, I want to add that this happens also when trying to set later (after creation) other stack attributes that are not available for UpdateStack API, for example TimeoutInMinutes , this attribute is available only during stack creation in the CreateStack API, **I'm not sure what could be the best solution**. since the CloudFormation API is not the best... I could think about query the value of the attribute first before creation, and then match with the terraform/go defaults (0 == absent), and I think that would suck.

This is currently representing a problem for me to import existing CFN stacks and start managing them via Terraform configuration, and also specially when combining with re-used modules code that actually create the stacks because it makes difficult to not break other usages.

For some reasons that really don't matter I have module config that creates a among other things creates stack:

```
// important stuff
resource "aws_cloudformation_stack" "the_stack" {
// ... more important stuff
  timeout_in_minutes = "${var.timeout_in_minutes}"
// ... and more
}
// ... and moar
```

`var.timeout_in_minutes` has a default of 0 for this module. This module is being imported via git in several places, so making a change is difficult. I have imported an existing stack with:

```
terraform import module.mymodulepathetc.aws_cloudformation_stack.the_stack myexistingstackname
```

The resource is imported OK, and there are no actual changes that would force a destruction except for the timeout_in_minutes which the existingstack did not specify during creation, so is absent.

Thank you for taking your time reading my message, my details are:

```
terraform version 
Terraform v0.12.12
+ provider.aws v2.42.0

Your version of Terraform is out of date! The latest version
is 0.12.18. You can update by downloading from www.terraform.io/downloads.html
```

**Comment by andresvia** [comment]
I just discovered after writing that comment that you could pass now `null` values, so I guess that would be the solution for me.

**Comment by lorengordon** [comment]
There's a chance this is fixed by https://github.com/hashicorp/terraform-provider-aws/pull/10539...

**Comment by justinretzolk** [comment]
Given the amount of time that's passed since anyone seems to have run into this, closing.
