### ISSUE TITLE
documentation on r/elasticache_replication_group availability_zones is incomplete.

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform-provider-aws#18238]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

documentation on r/elasticache_replication_group availability_zones is incomplete based on looking at the AWS documentation at https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html#API_CreateReplicationGroup_RequestParameters

### New or Affected Resource(s)

* aws_elasticache_replication_group

### Potential Terraform Configuration

N/A

**Comment by grimm26** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/18239 submitted

**Comment by gdavison** [comment]
Hi @grimm26, thanks for submitting this issue and PR #18239. You're correct that the Terraform documentation doesn't match the AWS API documentation. Unfortunately, as noted in #5104, the resource does not correctly implement the `PreferredCacheClusterAZs` parameter in the AWS API, and the Terraform documentation reflects how the resource behaves.

Fully fixing this problem will involve potentially breaking changes, which means it will have to be done as part of v4.0 of the provider, though we may be able to address parts of the solution before then. We intend to release v4.0 in the summer of 2021.

Since the documentation will be updated along with the code fix, I'm going to close the issue and PR. Thanks again!
