### ISSUE TITLE
bug: Api Gateway "Integration Response" is not created

### ISSUE THREAD

**Issue by maanenh** [hashicorp/terraform-provider-aws#1832]
First create an ApiGateway with the provided configuration file.
When changing the the 'uri' of the aws_api_gateway_integration from one lambda function to another and than execute `terraform apply`, the `aws_api_gateway_integration_response` is not created. 

When `terraform apply` is executed another time, the `aws_api_gateway_integration_response` is created. 

### Terraform Version
0.9.8  ..  0.10.7

### Affected Resource(s)
Api Gateway:   aws_api_gateway_integration_response

### Terraform Configuration Files
```hcl
resource "aws_lambda_function" "test_lambda_1" {
  filename         = "test.zip"
  function_name    = "testLambda_1"
  role             = "${var.test_role}"
  handler          = "test.handler"
  runtime          = "nodejs6.10"
  source_code_hash = "${base64sha256(file("test.zip"))}"

}

resource "aws_lambda_permission" "test_lambda_1" {
  statement_id  = "AllowExecutionFromApiGateway"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.test_lambda_1.arn}"
  principal     = "apigateway.amazonaws.com"
}

resource "aws_lambda_function" "test_lambda_2" {
  filename         = "test.zip"
  function_name    = "testLambda_2"
  role             = "${var.test_role}"
  handler          = "test.handler"
  runtime          = "nodejs6.10"
  source_code_hash = "${base64sha256(file("test.zip"))}"

}

resource "aws_lambda_permission" "test_lambda_2" {
  statement_id  = "AllowExecutionFromApiGateway"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.test_lambda_2.arn}"
  principal     = "apigateway.amazonaws.com"
}

resource "aws_api_gateway_rest_api" "test_api" {
  name = "testAPI"
  description = "Test api"
}

resource "aws_api_gateway_resource" "test" {
  rest_api_id = "${aws_api_gateway_rest_api.test_api.id}"
  parent_id   = "${aws_api_gateway_rest_api.test_api.root_resource_id}"
  path_part   = "test"
}

resource "aws_api_gateway_method" "test" {
  authorization = "NONE"
  http_method   = "GET"

  resource_id = "${aws_api_gateway_resource.test.id}"
  rest_api_id = "${aws_api_gateway_rest_api.test_api.id}"

}

resource "aws_api_gateway_integration" "test" {
  http_method             = "${aws_api_gateway_method.test.http_method}"
  integration_http_method = "POST"
  resource_id             = "${aws_api_gateway_resource.test.id}"
  rest_api_id             = "${aws_api_gateway_rest_api.test_api.id}"
  type                    = "AWS"
  depends_on              = ["aws_lambda_function.test_lambda_1"]
  uri                     = "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${aws_lambda_function.test_lambda_1.arn}/invocations"
  passthrough_behavior    = "WHEN_NO_TEMPLATES"

}

resource "aws_api_gateway_method_response" "method_response_test_200" {
  http_method = "${aws_api_gateway_method.test.http_method}"
  resource_id = "${aws_api_gateway_resource.test.id}"
  rest_api_id = "${aws_api_gateway_rest_api.test_api.id}"

  status_code = "200"
}

resource "aws_api_gateway_integration_response" "integration_response_test" {
  depends_on = ["aws_api_gateway_integration.test"]
  http_method = "${aws_api_gateway_method.test.http_method}"
  resource_id = "${aws_api_gateway_resource.test.id}"
  rest_api_id = "${aws_api_gateway_rest_api.test_api.id}"
  status_code = "${aws_api_gateway_method_response.method_response_test_200.status_code}"
}

```

### Expected Behavior
`aws_api_gateway_integration_response` is created

### Actual Behavior
`aws_api_gateway_integration_response` is *NOT* created

![terraformissue](https://user-images.githubusercontent.com/4258519/31280576-1189f006-aaad-11e7-9d23-90cfde034332.PNG)

### Steps to Reproduce

1. `terraform apply`
2. Change the following lines,  replace `test_lambda_1` by `test_lambda_2`
  ```
depends_on              = ["aws_lambda_function.test_lambda_1"]
  uri                     = "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/${aws_lambda_function.test_lambda_1.arn}/invocations"
```

3. `terraform apply`

**Comment by mikethecoder** [comment]
I can confirm this issue since I bumped into it today with v0.9.11 using S3 integration with Gateway. If you change the `uri` field for the aws_api_gateway_integration resource and then `apply` your changes, terraform seemingly updates only the correct resource (1 added, 0 changed, 1 destroyed - with `uri` responsible for the add/destroy); however, if you check the AWS Console UI, the aws_api_gateway_integration_response resource shows as being deleted. If you then immediately execute another `plan` command, terraform will inform you "1 to add, 0 to change, 0 to destroy" with the aws_api_gateway_integration_response resource being what it wants to add. 

After the initial changing of the `uri` value, the tfstate file still shows the aws_api_gateway_integration_response resource as existing and unchanged despite it having been deleted as shown in the AWS Console UI. After executing another `apply` to restore the deleted aws_api_gateway_integration_response resource, the tfstate file again never shows any signs of that resource being changed. Interestingly enough, even the `id` of the resource is the same after it comes back again which seems a bit odd assuming its randomly generated like I believe it to be.

**Comment by Tirke** [comment]
@fantomc0der described it perfectly.
This is still an issue on Terraform v0.11.14, provider.aws v2.23.0.
