### ISSUE TITLE
Terraform recreates the MSK cluster on updating instance type

### ISSUE THREAD

**Issue by paramanandd** [hashicorp/terraform-provider-aws#18479]
@teamterraform 
@terraformbot 
We are using terraform aws_msk_cluster resource for spinning up MSK cluster, but while updating instance type in plan section it shows cluster to be destroyed and created.

replicated same through AWS console, and we were able to update instance type without destroying the cluster

`
       broker_node_group_info {
           instance_type   = "kafka.t3.small" -> "kafka.m5.large" # forces replacement
        }  `

Below is the snippet of versions.tf
`
terraform {
  required_version = ">= 0.13.4"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.30"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 2.2"
    }
  }
}
`

**Comment by ewbankkit** [comment]
@paramanandd Thanks for raising this issue.
The Terraform AWS Provider does not currently support in-place update of MSK cluster if the broker instance type changes.
It has already been noticed in #17264. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
