### ISSUE TITLE
acm_certificate data source id attribute is wrong (its returning arn value)

### ISSUE THREAD

**Issue by rjcoelho** [hashicorp/terraform-provider-aws#18483]
### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.34.0

### Affected Resource(s)
* aws_acm_certificate

### Terraform Configuration Files
```hcl
variable "hosted_zone" {
  type = string
}
data "aws_acm_certificate" "latest" {
  domain      = var.hosted_zone
  statuses    = ["ISSUED"]
  most_recent = true
}
output "acm_certificate_latest_id" {
  value = data.aws_acm_certificate.latest.id
}
```

### Expected Behavior

Return Id not ARN

### Actual Behavior

ID value is wrong. You are returning same value as the ARN

### Steps to Reproduce

1. `terraform apply`
acm_certificate_latest_id = "arn:aws:acm:XXX:certificate/YYY"

**Comment by anGie44** [comment]
Hi @rjcoelho , thank you for raising this issue. While the `acm_certificate` data source returns the ARN as its `id`, this is actually by design, though understandably the naming seems to suggest differently. In the code we can see that the ID is set with the following line:

https://github.com/hashicorp/terraform-provider-aws/blob/6f3b57f0094872eb879b64fc28df11d276afc232/aws/data_source_aws_acm_certificate.go#L171

For more background, within the provider data sources and resources, the ID can be synonymous with the resource's ARN to aid in lifecycle operations like Read and Delete where respective AWS API methods require an ARN in the request and we can retrieve that value from state with calls to `d.Id()`.

https://github.com/hashicorp/terraform-provider-aws/blob/6f3b57f0094872eb879b64fc28df11d276afc232/aws/resource_aws_acm_certificate.go#L297-L302

**Comment by rjcoelho** [comment]
@anGie44 that you for the explanation, but still makes no sense from the user side. You are exposing two fields an arn and an id both returning the same value. 

Now I have to regexp it because other resources I use expect an id not an arn. it's not a big deal but you should at least document it.
