### ISSUE TITLE
data_source_aws_ecs_cluster does not return the cluster name

### ISSUE THREAD

**Issue by SeanHood** [hashicorp/terraform-provider-aws#18498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`data_source_aws_ecs_cluster` does not return the cluster name. Initially you'd think why should it, you pass the cluster name to this resource. However, you can also pass in the cluster arn, and from this I'd like to get the cluster name.

#### Why would this be useful?

I have a Terraform module which I pass in the cluster arn, but to set up the `aws_appautoscaling_target` resource I need the cluster name and not the full arn.

Could I just used regex? Yes, but that's messy.

`resource_aws_ecs_cluster` already returns the cluster name: https://github.com/hashicorp/terraform-provider-aws/blob/1aedfc38c99400d0db6a11a13b736f521ed09ab3/aws/resource_aws_ecs_cluster.go#L234

I came across #9822 which refers to something similar.

I'm happy to attempt a PR to add this and write the tests.

### New or Affected Resource(s)

* data_source_aws_ecs_cluster

### Potential Terraform Configuration

```hcl
data "aws_ecs_cluster" "cluster" {
  cluster_name = "arn:aws:ecs:us-east-2:123456789012:cluster/my-cluster"
}

resource "aws_appautoscaling_target" "this" {
  ...
  resource_id = "service/${data.aws_ecs_cluster.cluster.cluster_name}/${aws_ecs_service.svc.name}"
  ...
}
```

### References

* #9822

**Comment by anGie44** [comment]
Hi @SeanHood , thank you for raising this issue. This is interesting b/c looking at the terraform provider documentation, I believe `cluster_name` was originally meant to be used with only the "name" of an ecs cluster and perhaps not the full ARN as you've come across. 

I think to support both a name and ARN (and be able to read those values from state), we can update the `cluster_name` to be `Optional and Computed` (instead of `Required`), and then set `arn` to also be `Optional` and `Computed`, that way they each represent the distinct input types such that a user can supply only one of the 2 or both. And then when reading the ECS cluster, the values can be set into state to their respective fields i.e. `d.Set("cluster_name", ...)`  and `d.Set("arn", ...)`. we currently do the latter, but omit from explicitly setting the "cluster_name".

**Comment by anGie44** [comment]
Related: https://github.com/hashicorp/terraform-provider-aws/issues/15378
