### ISSUE TITLE
aws_fms_policy validation does not contain full list of acceptable resource types

### ISSUE THREAD

**Issue by willbengtson** [hashicorp/terraform-provider-aws#18551]
When providing a list of resource types, the validator errors incorrectly on `AWS::ElasticLoadBalancing::LoadBalancer` and `AWS::EC2::EIP`

```hcl
resource "aws_fms_policy" "shiled" {
  name                  = "TestPolicy"
  exclude_resource_tags = false
  remediation_enabled   = false
  resource_type_list = ["AWS::ElasticLoadBalancingV2::LoadBalancer",
    "AWS::ElasticLoadBalancing::LoadBalancer",
  "AWS::EC2::EIP"]

  security_service_policy_data {
    type = "SHIELD_ADVANCED"

    managed_service_data = jsonencode({
      type = "SHIELD_ADVANCED",
    })
  }
}
```
### Panic Output

```Error: expected resource_type_list.1 to be one of [AWS::ApiGateway::Stage AWS::CloudFront::Distribution AWS::EC2::NetworkInterface AWS::EC2::Instance AWS::EC2::SecurityGroup AWS::EC2::VPC AWS::ElasticLoadBalancingV2::LoadBalancer], got AWS::ElasticLoadBalancing::LoadBalancer```

```Error: expected resource_type_list.0 to be one of [AWS::ApiGateway::Stage AWS::CloudFront::Distribution AWS::EC2::NetworkInterface AWS::EC2::Instance AWS::EC2::SecurityGroup AWS::EC2::VPC AWS::ElasticLoadBalancingV2::LoadBalancer], got AWS::EC2::EIP```

### Expected Behavior

Validation successful

### Actual Behavior

Validation error

### Steps to Reproduce

1. `terraform plan`

**Comment by bflad** [comment]
Thank you for submitting this, @willbengtson 😄  Our list of valid values in that list is currently manually managed, but according to the [FMS API Reference](https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_PutPolicy.html) the API model specifies the validation is a string regular expression. Especially with the addition of [Route 53 Resolver DNS Firewalls](https://github.com/hashicorp/terraform-provider-aws/issues/18520), which also is now a supported resource type, we should probably just adjust this validation to match the API modeled regular expression rather than continually updating the resource types manually with bug reports.
