### ISSUE TITLE
 v3.37.0 marks AMI names as sensitive

### ISSUE THREAD

**Issue by WhyNotHugo** [hashicorp/terraform-provider-aws#18925]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.12.0
+ provider registry.terraform.io/cyrilgdn/rabbitmq v1.5.1
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

`aws_instance`

### Terraform Configuration Files

I've a very basic EC2 instance using the AWS recommended image (this example has been shortened here; I use these images for an ECS cluster):

```hcl
data "aws_ssm_parameter" "ecs_optimised_ami" {
  # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html#ecs-optimized-ami-linux
  name = "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended"
}

resource "aws_instance" "Test" {
  ami           = jsondecode(data.aws_ssm_parameter.ecs_optimised_ami.value).image_id
  instance_type = "t2.large"

  network_interface {
    network_interface_id = aws_network_interface.Test.id
    device_index         = 0
  }
}

```

### Debug Output
```
  # aws_instance.Test will be updated in-place
  ~ resource "aws_instance" "Web" {
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ ami                          = (sensitive)

```

### Expected Behavior

`ami` name should be visible, there's nothing sensitive about it.

### Actual Behavior

`ami` value is now detected as "sensitive".

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing unusual.

**Comment by bflad** [comment]
Hi @WhyNotHugo 👋  Thank you for reporting this and sorry you ran into trouble here.

Terraform CLI version 0.15.0 and later includes additional behaviors around sensitive attribute values. For example, attributes marked sensitive by resource implementations will now trigger this behavior, where the sensitivity is explicitly passed around with the value to downstream references and outputs. More information about these changes can be found in the [Terraform v0.15 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-15.html#sensitive-output-values).

Since you know the value is safe to display in this situation, you can use the [`nonsensitive()` function](https://www.terraform.io/docs/language/functions/nonsensitive.html) to wrap the reference and allow the value to be displayed. e.g.

```terraform
data "aws_ssm_parameter" "ecs_optimised_ami" {
  # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html#ecs-optimized-ami-linux
  name = "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended"
}

resource "aws_instance" "Test" {
  ami           = jsondecode(nonsensitive(data.aws_ssm_parameter.ecs_optimised_ami.value)).image_id
  instance_type = "t2.large"

  network_interface {
    network_interface_id = aws_network_interface.Test.id
    device_index         = 0
  }
}
```

We do have a tracking issue for conditionally marking `String` type SSM Parameters as non-sensitive, https://github.com/hashicorp/terraform-provider-aws/issues/9090, however please note that this functionality is not currently possible to implement in the resource or data source without some enhancements outside of this provider codebase. That issue can be tracked for any potential updates in that regard.

**Comment by WhyNotHugo** [comment]
The problem here is that the provider assumes by default that an SSM value is sensitive. Yet SSM values are used by AWS for PUBLIC data like recommends AMI image.

The default should be non-sensitive and let anyone handling secrets mark them as such. The new 0.15 approach just adds an incredible amount boilerplate to normal values where it doesn't make sense.
