### ISSUE TITLE
Feature req: Data source for aws_api_gateway_stage

### ISSUE THREAD

**Issue by bishtawi** [hashicorp/terraform-provider-aws#19306]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very helpful to have a data source for `aws_api_gateway_stage`.

It looks like there was already a Pull Request (https://github.com/hashicorp/terraform-provider-aws/pull/8890) opened to add this exact feature but was closed and locked due to inactivity.

### New or Affected Resource(s)

* aws_api_gateway_stage

### References

* #8890

**Comment by brent-moffit** [comment]
In our deployment we have a single REST API in API Gateway that distributes the individual resource paths to different microservices via `HTTP_PROXY` integrations.  Each microservice has its own terraform scripts that manage their individual infrastructure, including the methods/integrations on API Gateway.

The problem is that no single microservice owns the REST API and stage in API Gateway, so while they can use terraform to add endpoints they cannot automatically deploy those endpoints without being able to get a data source reference to the stage as you hit [the warning described in the `aws_api_gateway_deployment` docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_deployment).
