### ISSUE TITLE
aws_cloudfront_distribution does not set Use Origin Cache Headers correctly on creation.

### ISSUE THREAD

**Issue by apogrebnyak** [hashicorp/terraform-provider-aws#19382]
This is related to https://github.com/hashicorp/terraform-provider-aws/issues/1994

If you do not specify these optional settings to these exact vallues
```
    default_ttl = 86400
    min_ttl = 0
    # 365 days
    max_ttl = 31536000
```

You are not getting `Use Origin Cache Headers`, but instead in AWS console you have `Customize` radio button with all TTLs of `0`

Setting this values to `null`, i.e.
```
    default_ttl = null
    min_ttl = null
    max_ttl = null
```
Also results in `Customize` setting

**Comment by gideonred** [comment]
I can confirm that this fixed an issue that took me way too long to figure out.

There is no mention of how to set "Use Origin Cache Headers" in Cloudfront in the official Hashicorp documentation. If you Google for it, the first (and really only) result you get is Issue [1994](https://github.com/hashicorp/terraform-provider-aws/issues/1994).

But, for some time now that proposed solution has stopped working.

Going forward setting the following explicitly enables "Use Origin Cache Headers":

```
default_ttl = 86400
min_ttl = 0
max_ttl = 31536000
```

Instead of "fixing" the code, it would be useful if the documentation was just updated to mention this.

**Comment by rufio1337** [comment]
Bumping this thread and mentioning that I've been having the exact same issue. The proposed fix from [1994](https://github.com/hashicorp/terraform-provider-aws/issues/1994) does not work, currently. Excluding those 3 TTL values, leaving them to default, instead sets the option to "Custom", and sets all 3 TTL values to 0.

Optionally excluding all 3 values should instead select "Use Origin Cache Headers".
Would be great for this to be fixed, instead of requiring us to set all 3 values to numbers that are only mentioned in an old issue thread.

**Comment by Haizzz** [comment]
This doesn't seem to work for me. When setting all values to null
```terraform
default_ttl = null
min_ttl = null
max_ttl = null
```
The behavior changed to custom like the comments above. Then changing the values to 
```terraform
default_ttl = 86400
min_ttl = 0
max_ttl = 31536000
```
Just changes the values inside custom and not use origin cache headers

**Comment by Haizzz** [comment]
My mistake, setting values to the above does set origin cache headers, Cloudfront took a while to update and reflect the changes

**Comment by tmccombs** [comment]
At the very least this behavior should be documented.  It is very unexpected that the default behavior is to set the maximum ttl of 0, which effectively disables the cache.

**Comment by tmccombs** [comment]
See also https://github.com/hashicorp/terraform-provider-aws/issues/21677

**Comment by jar-b** [comment]
It appears the default values for `default_ttl` and `max_ttl` were removed as part of #17336 (v3.28.0), meaning complete omission of the TTL arguments no longer resulted in the "Use origin cache headers" setting.

https://github.com/hashicorp/terraform-provider-aws/pull/17336/files#diff-e4558175a0c6a9b540ac7a9a1cf917d89212690aeb6c652b7d3e11eccfc39145L69
https://github.com/hashicorp/terraform-provider-aws/commit/1e07711e79d3e94a4248cd982bad044401dbe3d8#diff-e4558175a0c6a9b540ac7a9a1cf917d89212690aeb6c652b7d3e11eccfc39145L147

I suspect this was done to support the new `aws_cloudfront_cache_policy` resource by preventing default values set on the distribution resource from overriding any TTL values configured in a linked policy. The defaults _were_ migrated to to the new cache policy resource, so the TTL values to trigger the "Use origin cache headers" setting can be achieved by either:

1. Explicitly setting `default_ttl`, `max_ttl`, and `min_ttl` arguments on the `aws_cloudfront_distribution` resource to the necessary values (as documented above).
2. Omitting the `default_ttl`, `max_ttl`, and `min_ttl` arguments on a `aws_cloudfront_cache_policy` resource, then linking that policy with a distribution via the [`cache_policy_id` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#cache_policy_id). 
3. Linking an AWS managed caching policy (such as [CachingOptimized](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-caching-optimized), [CachingOptimizedForUncompressedObjects](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-caching-optimized-uncompressed)) to an existing distribution via the [`cache_policy_id` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#cache_policy_id). .

From the documentation it appears AWS prefers policy based configurations (option 2 or 3), but for completeness in the provider it makes sense to document option 1 as well. #26632 will accomplish this and will be merged once our v5 feature freeze ends.
