### ISSUE TITLE
Multiple AWS Providers results in: err="rpc error: code = Unavailable desc = transport is closing"

### ISSUE THREAD

**Issue by Doug-North** [hashicorp/terraform-provider-aws#19512]
In my workspace I am defining multiple AWS providers for different accounts.
```
provider "aws" {
  region = "eu-west-2"
  alias  = "example1"
  assume_role {
    role_arn = "arn:aws:iam::ACCOUNT-ID:role/ROLE-NAME"
  }
}
```

Everything works fine until i get to around 5 providers, when I receive the error:
```
Error: rpc error: code = Canceled desc = context canceled
```

Attached is an exert of the debug output, confirming it is indeed the AWS Provider that is failing
[debug-output.log](https://github.com/hashicorp/terraform-provider-aws/files/6537916/debug-output.log)

I have removed a few providers, and dependent resources from the state as a 'workaround'

**Comment by soleares** [comment]
I'm starting getting this error a lot with the latest version 3.43.0 as well.

**Comment by justinretzolk** [comment]
Hey @Doug-North 👋 Thank you for taking the time to raise this! In the past (when I used to support Terraform Cloud and Terraform Enterprise), when I've seen this type of error message, it usually was caused by the machine that Terraform was running on running out of memory. Given that this happened when you added additional instances of the AWS provider, and went away when you removed those, it seems as though that may be the case here. I realize it's been a while, but are you able to monitor the machine to see if that is indeed the case?
