### ISSUE TITLE
Typo in documentation Data Source aws_ecs_container_definition: memory_reservation vs meoryReservation

### ISSUE THREAD

**Issue by Lansorian** [hashicorp/terraform-provider-aws#19609]
![120317421-8f420780-c319-11eb-9f8a-9e982a2aa631](https://user-images.githubusercontent.com/22159928/120318038-4b033700-c31a-11eb-8c2c-a438dcdf181b.png)

As the image shows, I can use `memoryReservation` key to define the soft limit of an ecs task container (and I have tried that `memory_reservation` does not work).
However, in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecs_container_definition) it is said to be `memory_reservation`, which is confusing...

**Comment by sumodirjo** [comment]
Hi @Lansorian,
From the screenshot that you provided. You're using [ecs_task_definition](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition) resource instead of [ecs_container_definition](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecs_container_definition).

The [`container_definition`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#container_definitions) already provide reference to AWS documentation regarding the valid task definition parameter.

Do you mind to provide the terraform configuration so I can reproduce the error? Thank you.
