### ISSUE TITLE
RDS and secrets manager terraform - deadlock issue

### ISSUE THREAD

**Issue by Nimsgs** [hashicorp/terraform-provider-aws#19683]
I am creating secrets manager through the console and RDS using terraform. While creating RDS, it requires a username and password which needs to be retrieved from Secrets manager as below:
username                  = local.db_secret.username
password                  = local.db_secret.password

But while creating a secrets manager for storing the RDS credentials, it asks for the RDS host- This is mandatory while creating the secrets- _Select which RDS database this secret will access_
Now before creating the RDS how will I pass this host to secrets manager and for creating the rds, I need to access the secrets manager for username and password. This is a chicken egg problem. Is there any solution to handle this deadlock situation ?

**Comment by chrisbulgaria** [comment]
Yes , you have todo it on two steps - see here for cloud formation : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html

unfortunately terraform does not support such secret target attachment yet , otherwise you could do everything from terraform ( no console, starting with a random password and rotate then ) , see here:
https://github.com/hashicorp/terraform-provider-aws/issues/9183

Chris

**Comment by Nimsgs** [comment]
Thanks for the response Chris. Do you know when this capability will be enabled for Terraform ?

**Comment by chrisbulgaria** [comment]
No, the best you can do is vote on that issue  #9183  such that it may get prioritised higher by Hashicorp.
Until then you could use as a workaround  the terraform cloudformation stack resource to call cloud formation.

**Comment by anGie44** [comment]
Hi @Nimsgs , thank you for raising this issue. Just echoing @chrisbulgaria 's comment above to vote and follow #9183 to stay up-to-date with future terraform provider support. I'm going to close this issue to ensure we have one place to track community interest for the feature support, but thanks again!
