### ISSUE TITLE
Terraform error : Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by rajatb2** [hashicorp/terraform-provider-aws#19695]
![image](https://user-images.githubusercontent.com/84705947/121025848-72af3080-c75a-11eb-955c-71aa5810f457.png)
I am getting this issue on terraform. I am also getting role assignment already exists issue. 
![image](https://user-images.githubusercontent.com/84705947/121026333-dfc2c600-c75a-11eb-8d73-6f6f1cdc3a5c.png)
 when i run terraform apply it creates resources and and show unknown role assignments and on rerun it show resource exist error,
i am using count function on my aks module , can this be the cause of error

**Comment by anGie44** [comment]
Hi @rajatb2 , thank you raising an issue. Looking at the error message below `Provider produced inconsistent result after apply`, however, it seems it is triggered by the AzureRM provider's `role_assignment` resource, and perhaps this issue may better investigated as new issue here:  https://github.com/terraform-providers/terraform-provider-azurerm/issues .  If you still feel this issue is related to an AWS provider resource, please provide a terraform configuration/any additional debug logs.

thanks in advance!
