### ISSUE TITLE
sweeper/aws_apprunner_auto_scaling_configuration_version: Can't delete "DefaultConfiguration"

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#19840]
AWS defines a default Auto Scaling configuration for App Runner. This cannot be deleted.

When the sweeper tries, it gets the following error

> error deleting resource: error deleting App Runner AutoScaling Configuration Version (arn:aws:apprunner:us-east-1:*******:autoscalingconfiguration/DefaultConfiguration/1/00000000000000000000000000000001): InvalidRequestException: You can't delete a reserved auto scaling configuration: '%s'.

(Yes, with the literal `%s`)

Do not attempt to sweep `aws_apprunner_auto_scaling_configuration_version`s containing `autoscalingconfiguration/DefaultConfiguration` in the ARN

### Affected Resource

* aws_apprunner_auto_scaling_configuration_version

**Comment by anGie44** [comment]
🤔  I wonder if this is because we have dangling apprunner services (at least possibly by the time the sweepers run), given the tests in TC are failing w/
```
testing_new.go:63: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: error deleting App Runner Service (arn:aws:apprunner:us-west-2:*******:service/tf-acc-test-8082562876927284703/ace8a25147e74405937b19b99ede81bb): InvalidStateException: Service cannot be deleted in the current state: OPERATION_IN_PROGRESS.
```
The autoscaling config version sweeper has a dependency on the apprunner service sweepers so I would of thought once the service is gone, so is it's default autoscaling config but i'd have to double-check
