### ISSUE TITLE
ecs_cluster isn't preserving desired_count on update/recreation

### ISSUE THREAD

**Issue by samuelkdavis-mccarthyfinch** [hashicorp/terraform-provider-aws#20110]
### Issue

When updating aws_autoscaling_group, the desired_capacity isn't preserved when the resource needs to be deleted/created as part of the any change. This means that every time ecs is deployed, the ec2 agents are scaled in.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

0.13.3
### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```terraform
resource "aws_autoscaling_group" "worker" {
  name                      = "${aws_launch_configuration.worker.name}"
  min_size                  = "${var.ec2_min_size}"
  max_size                  = "${var.ec2_max_size}"
  min_elb_capacity          = "${var.ec2_min_size}"
  health_check_grace_period = 300
  health_check_type         = "ELB"
  # desired_capacity          = 1
  force_delete         = true
  launch_configuration = "${aws_launch_configuration.worker.name}"
  vpc_zone_identifier  = "${var.private_subnet_ids}"
  termination_policies = ["OldestLaunchConfiguration", "OldestInstance"]

  lifecycle {
    create_before_destroy = true

    ignore_changes = [
      "desired_capacity",
    ]
  }
```

### Expected Behavior

ecs_cluster desired count should remain the same

### Actual Behavior

ecs_cluster desired count is reset to the min_size, or the specified number in terraform.

### Steps to Reproduce

Change max_size value, make sure name is set to the aws_launch_configuration worker name, run terraform

**Comment by gdavison** [comment]
Hi @samuelkdavis-mccarthyfinch, this sounds like a useful enhancement. Unfortunately, it's not something that is handled in the AWS provider. Terraform Core handles the lifecycle when resources are re-created.

Please create an issue on the Terraform Core project https://github.com/hashicorp/terraform/issues

**Comment by samuelkdavis-mccarthyfinch** [comment]
I've created an issue here: https://github.com/hashicorp/terraform/issues/29141

**Comment by jbardin** [comment]
Hi,

The combination of the `desired_capacity` attribute with `ignore_changes` always determines the initial value for the resource, while still allowing changes outside of terraform once the resource has ben created. Replacing a resource will always create the new resource anew according to the configuration, which will must include the initial `desired_capacity` value. 

Attempting to modify the plan in order to incorporate values not in the configuration but known to the provider is usually best accomplished by the provider itself. Since the resource is statically named, and appears to be able to allow duplicate names as `create_before_destroy` is `true`, it may be possible for the provider to lookup a value on the existing resource and assign that to an attribute which overrides `desired_capacity` during the initial plan. I'm not familiar with the resource internals here, so there may be other issues hidden in that idea, or it may be hindered by the legacy SDK in some way. 

If this is a common enough use case, it may warrant a data source which could be used for the purpose as well, looking up the existing autoscaling_group `desired_capacity` and returning a default if it's not yet created. 

Again, I'm not all that familiar with the AWS provider details, so there may be a more direct solution I'm missing entirely, but the goal here would be to use the protocols given to the provider to implement a solution, which is much easier than imposing architectural changes to Terraform for this resource's use case. 

Thanks!

**Comment by samuelkdavis-mccarthyfinch** [comment]
Thanks for your reply. I believe this functionality should be supported, but obviously can't speak to its priority.

The changes to the resource is an 'update' so supporting carrying over the existing unchanged values is a natural solution. The fact that it creates a new resource before killing off the old one using a blue/green pattern is more of a technical detail/limitation.

The risk with not preserving desired_count is that if you deploy during heavy traffic, there is a risk of overloading the systems being deployed. In my case, I'd earlier assumed desired_count was preserved, so the terraform had set it to 1 as a starting point, and relied on autoscaling to determine the actual required amount. Temporarily I have just set the desired_count per environment and injected that in.

An alternate solution to this problem would be to replace the technical limitation with a pattern of terraform resources to solve it. As long as it's documented, this would be a fine solution - I've seen similar solutions/patches in terraforms documentation. Something like "in order to preserve the desired_capacity during updates that replace the resource, use an optional ecs_cluster data source and use its desired count if available" (are nullable data sources a thing?). If such a thing is supported, it wouldn't be a terrible solution if documented clearly, although would require this to be fixed: https://github.com/hashicorp/terraform-provider-aws/issues/20067
