### ISSUE TITLE
arn inconsistency for aws_cloudwatch_log_group between resource and data source

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform-provider-aws#20156]
aws_cloudwatch_log_group resource does not have ":*" appended to its arn, where as aws_cloudwatch_log_group data source does

**Comment by ewbankkit** [comment]
@lijok Thanks for raising this issue.
It has already been noticed in #15073 (although the title of that issue is misleading). I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

We intend to address this breaking change in the next major version, **v4.0.0**.
