### ISSUE TITLE
EKS Data Source to discover clusters without knowing names ahead of time

### ISSUE THREAD

**Issue by theothermike** [hashicorp/terraform-provider-aws#20251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There does not currently appear to be a way to discover EKS Clusters using a `data` source.  The current `data.eks_cluster` expects a `name` attribute.   We are wanting to discover all EKS Clusters to extract auth information for other jobs, and it is a major hindrance that we have to know the names ahead of time

### New or Affected Resource(s)

* aws_eks_clusters

### Potential Terraform Configuration

```hcl
data "aws_eks_clusters" "existing-clusters" { 
  filter {
    name = "eks_version"
    values = ["1.19", "1.20"]
  }

  filter {
    name = "cluster_name"
    values = ["mycluster-*"]
  }

  filter {
    name = "tag:State"
    values = "blue"
  }
}
```

### References

https://docs.aws.amazon.com/eks/latest/APIReference/API_ListClusters.html

**Comment by Vince-Chenal** [comment]
Hello here,

I created [this PR](https://github.com/hashicorp/terraform-provider-aws/pull/20315) to implement the datasource the way I explained [here](https://github.com/hashicorp/terraform-provider-aws/issues/13719#issuecomment-693492011).

I did not implement any kind of filtering because the ListClusters does not allow it for now (https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#ListClustersInput) and I wanted to keep it as simple as possible
