### ISSUE TITLE
Changing parameters in aws_elasticache_parameter_group causes a replacement, which fails.

### ISSUE THREAD

**Issue by azilber** [hashicorp/terraform-provider-aws#20264]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.50.0

### Affected Resource(s)

* aws_elasticache_parameter_group 

### Terraform Configuration Files

```hcl
resource "aws_elasticache_parameter_group" "default" {
  name   = "cpredis6x"
  family = "redis6.x"

  parameter {
    name = "maxmemory-policy"
    value = "allkeys-lru"
  }
  parameter {
      name = "repl-backlog-size"
      value = "1048576"
  }
  parameter {
      name = "lazyfree-lazy-eviction"
      value = "yes"
  }
 parameter {
      name = "lazyfree-lazy-expire"
      value = "yes"
  }
  tags = local.tags
}
```

### Panic Output

│ Error: error deleting ElastiCache Parameter Group (cpredis6x): InvalidCacheParameterGroupState: One or more cache clusters are still members of this parameter group cpredis6x, so the group cannot be deleted.
│       status code: 400, request id: f70d88ba-cf29-4036-a51e-3edb0b5b56b1

### Expected Behavior

Success (and a modification, not a replacement)

### Actual Behavior

```
Terraform will perform the following actions:

  # aws_elasticache_parameter_group.default is tainted, so must be replaced
```

### Steps to Reproduce

1. `terraform apply`
2. change a parameter
3. `terraform apply`

### Important Factoids

I'm using the aws_elasticache_replication_group resource with aws_elasticache_parameter_group to create the parameter group
for a Redis Elasticache replication group.  When changing parameters in the parameter group, it should modify, not replace
the parameter group.  Replacing will always fail because the parameter group is associated with a replication group(s).

### References

* #0000

**Comment by gdavison** [comment]
Hi @azilber, thanks for submitting this issue. In normal cases, `aws_elasticache_parameter_group` does not force replacement of the parameter group.

I see in your output that Terraform is trying to replace `aws_elasticache_parameter_group.default` because it is `tainted`. This can happen if a resource is partially created or if the [deprecated command `terraform taint`](https://www.terraform.io/cli/commands/taint) is called on the resource. If the resource was partially created, a previous `terraform apply` would have returned an error.

When a resource is `tainted`, it must be deleted and re-created. In your case, Terraform cannot delete the resource because it is in use.

The `tainted` state can be removed from a resource by using the [command `terraform untaint`](https://www.terraform.io/cli/commands/untaint).

Since this looks like the resource is `tainted`, and the provider is not causing the error, I'm going to close this issue. If you continue to see this problem, please create a new issue that shows the Terraform configuration both before and after the changes that you make and also include the Terraform debug log as described at https://www.terraform.io/internals/debugging.
