### ISSUE TITLE
Outdated example in API Gateway v2 Authorizer page

### ISSUE THREAD

**Issue by sallaben** [hashicorp/terraform-provider-aws#20304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

1.0.3

### Affected Resource(s)

* aws_apigatewayv2_authorizer

### Problem

hello, I wanted to share some documentation that I think should be updated. I'm just passing by, so maybe someone more involved can include this change in an existing docs PR to the aws provider, I don't know how you guys do things around here.

This current example for API Gateway v2 Authorizer on Documentation page will fail with the error below. 

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_authorizer

```hcl
resource "aws_apigatewayv2_authorizer" "example" {
  api_id           = aws_apigatewayv2_api.example.id
  authorizer_type  = "REQUEST"
  authorizer_uri   = aws_lambda_function.example.invoke_arn
  identity_sources = ["route.request.header.Auth"]
  name             = "example-authorizer"
}
```

### Debug Output

`Error: error creating API Gateway v2 authorizer: BadRequestException: AuthorizerPayloadFormatVersion is a required parameter for REQUEST authorizer`

### Solution

If we change 2 things, namely editing the identity sources and adding a new field  `authorizer_payload_format_version`, the apply passes and resources are created properly

```hcl
resource "aws_apigatewayv2_authorizer" "example" {
  api_id           = aws_apigatewayv2_api.example.id
  authorizer_type  = "REQUEST"
  authorizer_uri   = aws_lambda_function.example.invoke_arn
  identity_sources = ["$request.header.Authorization"]
  name             = "example-authorizer"
  authorizer_payload_format_version = "2.0"
}
```

### Expected Behavior

Authorizer should be created

### Actual Behavior

Failed on run

### Steps to Reproduce

1. `terraform apply`

### References

* #15232
* #15181

**Comment by rahul-amzn** [comment]
I will look into this.

**Comment by kuteninja** [comment]
Bump, almost a year later, the REQUEST example is still wrong at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_authorizer

I just bumped into this issue myself, please update the documentation to avoid further confusion

**Comment by rahul-amzn** [comment]
Tested it but could not reproduce the issue. If possible, can you please share TF template or steps to reproduce the issue?

**Comment by kuteninja** [comment]
That's the code with the issue right there, if you do a `terraform plan` it won't fail, since the terraform code doesn't notice what's wrong about it, but if you apply it, it will tell you these errors:


If you don't update the `identity_sources` format, it complains about it: 
```
Error: creating API Gateway v2 authorizer: BadRequestException: Invalid identity source expression: route.request.header.Auth. The source must be a request header, request querystring, stage variable or context parameter
```
Which pointed me to the AWS documentation when it mentions the [request parameter mapping](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-parameter-mapping.html) syntax.


Then, if you don't add the `authorizer_payload_format_version` it complains about it:
```
Error: creating API Gateway v2 authorizer: BadRequestException: AuthorizerPayloadFormatVersion is a required parameter for REQUEST authorizer
```
Which is explained on yet other link of the AWS documentation for [Payload format version](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html). Basically 1.0 is used for REST APIs only and 2.0 can be used for HTTP APIs. Apparently HTTP APIs can also handle the 1.0 version of the API but you need to explicitly state which one you'll be using, can not be left blank.

**Comment by kuteninja** [comment]
I'm attaching a full example: [api-gw-module.zip](https://github.com/hashicorp/terraform-provider-aws/files/10338010/api-gw-module.zip)

I've been using it with...
- terraform v1.3.6
- hashicorp/aws v4.48.0

**Comment by rahul-amzn** [comment]
Thanks @kuteninja. Submitted PR https://github.com/hashicorp/terraform-provider-aws/pull/28631
