### ISSUE TITLE
cloudwatch_log_group missing name output field

### ISSUE THREAD

**Issue by samuelkdavis-mccarthyfinch** [hashicorp/terraform-provider-aws#20365]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group

The Attributes Reference only shows 'arn' and 'tags_all', however you can also reference the name field. It works but is undocumented.

```terraform
resource "aws_cloudwatch_log_subscription_filter" "worker_log_subscription_filter" {
  for_each = var.filter_subscriptions
  # depends_on      = [module.cloudwatch_log_group]
  role_arn        = ""
  name            = "${var.name}${each.key}"
  log_group_name  = aws_cloudwatch_log_group.default.name
  filter_pattern  = each.value.filter_pattern
  destination_arn = each.value.destination_arn
}
```

**Comment by anGie44** [comment]
Hi @samuelkdavis-mccarthyfinch , thank you for raising this issue.  In general, items listed under `Attributes` are configurable and readable (can be referenced) so by design we don't duplicate the content in both the `Attributes` and `Arguments` sections of the docs. As a rule of thumb, you'll only find items in the `Attributes` section if they are read-only such that the AWS API computes the value and returns it as output and a user can not provide a value as input. 

Hope that helps clarify the distinction :)
