### ISSUE TITLE
Plugin crashed

### ISSUE THREAD

**Issue by kirubakaran25** [hashicorp/terraform-provider-aws#20461]
```
Stack trace from the terraform-provider-aws_v3.52.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 171 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupRead(0xc00194d000, 0x0, 0x0, 0xb728b00, 0xc0003ae000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lb_target_group.go:385 +0x967
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc001566000, 0x7e62e08, 0xc0027c2a40, 0xc00194d000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc001566000, 0x7e62e08, 0xc0027c2a40, 0xc00196c310, 0x0, 0x0, 0xc000387298, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000130498, 0x7e62e08, 0xc0027c2a40, 0xc0027c2a80, 0xc0027c2a40, 0x40b965, 0x6de3880)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc002238320, 0x7e62eb0, 0xc0027c2a40, 0xc001947c80, 0xc002238320, 0xc0027de4b0, 0xc000163ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x70c1ae0, 0xc002238320, 0x7e62eb0, 0xc0027de4b0, 0xc001947c20, 0x0, 0x7e62eb0, 0xc0027de4b0, 0xc0026fce00, 0x353)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00051f880, 0x7e84eb8, 0xc000160480, 0xc001b70600, 0xc0006abcb0, 0xb6e7110, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00051f880, 0x7e84eb8, 0xc000160480, 0xc001b70600, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0006ac810, 0xc00051f880, 0x7e84eb8, 0xc000160480, 0xc001b70600)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.52.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by kirubakaran25** [comment]
this is when running terraform destroy command on the latest AWS provider (v3.52.0) and TF version v1.0.3

**Comment by ewbankkit** [comment]
Similar:

* #20438
* #20131
* #20015
* #19807
* #19788
* #19740
* #19601

**Comment by gopikris83** [comment]
This was my own plugin and it displayed the below plugin error. Same as above

Error: Plugin did not respond
│ 
│   with module.appserver_vpc.aws_vpc.main_vpc,
│   on ../modules/aws/network/network.tf line 1, in resource "aws_vpc" "main_vpc":
│    1: resource "aws_vpc" "main_vpc" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.55.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 109 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsInstanceRead(0xc00072e580, 0x0, 0x0, 0xb892e00, 0xc0006c0000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_instance.go:885 +0x44a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a968c0, 0x7f56668, 0xc00071ae80, 0xc00072e580, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a968c0, 0x7f56668, 0xc00071ae80, 0xc002012150, 0x0, 0x0, 0xc000724bf8, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000314b88, 0x7f56668, 0xc00071ae80, 0xc00071aec0, 0xc00071ae80, 0x40b965, 0x6eb3340)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00220fd60, 0x7f56710, 0xc00071ae80, 0xc0007331a0, 0xc00220fd60, 0xc001f67a70, 0xc00196bba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7198320, 0xc00220fd60, 0x7f56710, 0xc001f67a70, 0xc000733140, 0x0, 0x7f56710, 0xc001f67a70, 0xc002010000, 0x740)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000225880, 0x7f787d8, 0xc00055e300, 0xc002006000, 0xc000a784b0, 0xb8513b0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000225880, 0x7f787d8, 0xc00055e300, 0xc002006000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0007af140, 0xc000225880, 0x7f787d8, 0xc00055e300, 0xc002006000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.55.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by manoatsas** [comment]
Faced this issue when trying out examples in https://github.com/terraform-aws-modules/terraform-aws-eks module with Terraform v1.0.0 and after running `terraform apply` got this stack trace from `terraform destroy`
```
│ Error: Plugin did not respond
│
│   with module.eks.module.self_managed_node_group["complete"].aws_iam_instance_profile.this[0],
│   on ../../modules/self-managed-node-group/main.tf line 533, in resource "aws_iam_instance_profile" "this":
│  533: resource "aws_iam_instance_profile" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v4.2.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *conns.AWSClient

goroutine 115 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/iam.resourceRolePolicyAttachmentRead(0x68, {0x0, 0x0})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/iam/role_policy_attachment.go:59 +0x59d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x95725bb, {0xa50a4b8, 0xc000b92280}, 0x24, {0x0, 0x0})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0009d88c0, {0xa50a4b8, 0xc000b92280}, 0xc000bb2410, {0x0, 0x0})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c960, {0xa50a4b8, 0xc000b92280}, 0xc000b92300)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001a0900, {0xa50a560, 0xc000b96000}, 0xc000b8a180)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x93235e0, 0xc0001a0900}, {0xa50a560, 0xc000b96000}, 0xc000b8a120, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fea80, {0xa5fd2a0, 0xc0005f4000}, 0xc002a10100, 0xc001b55920, 0xfb984d0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0001fea80, {0xa5fd2a0, 0xc0005f4000}, 0xc002a10100, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-aws_v4.2.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
However, after reviewing the comments here and in similar issues updated Terraform to latest v1.1.1, and that resolved the issue and now `terraform destroy` runs successfully.

**Comment by justinretzolk** [comment]
Hey @manoatsas 👋 Thank you for that additional report! Given your experience, I think it's safe to say that this issue has been resolved, so I'm going to go ahead and close it. If you feel I've done this in error, please do let me know!
