### ISSUE TITLE
aws_dynamodb_table_item stuck when not input range_key parameter

### ISSUE THREAD

**Issue by jianglei-els** [hashicorp/terraform-provider-aws#20988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hi @jianglei-els 👋 Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of your Terraform configuration file(s), and the other portions of the bug report template. We are going to close this issue - if you would like to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) please make sure that you fill out all the requested information so that we can try to reproduce the problem.
