### ISSUE TITLE
Terraform EC2 (Root Block device Encryption error failing to reach target state )

### ISSUE THREAD

**Issue by r-aju** [hashicorp/terraform-provider-aws#21006]
While creating an EC2 Instance in terraform the Instance won’t reach the target state and says

│ Error: Error waiting for instance (i-*************) to become ready: Failed to reach target state. Reason: Client.InternalError: Client error on launch
│

And also we have encryption of new EBS Volumes enabled in our EC2 dashboard.

* aws_instance

### Terraform Configuration Files
instance_type = “t2.micro”
availability_zone = “ap-south-1a”
root_block_device {
volume_size = “10”
volume_type = “gp2”
delete_on_termination = true
encrypted = true
kms_key_arn = "arn:aws:kms:*************”
}
}

```hcl

```

### Debug Output

│ Error: Error waiting for instance (i-*************) to become ready: Failed to reach target state. Reason: Client.InternalError: Client error on launch
│

### Panic Output

│ Error: Error waiting for instance (i-*************) to become ready: Failed to reach target state. Reason: Client.InternalError: Client error on launch
│

### Expected Behavior

Create EC2 Instance

### Actual Behavior

Not Creating EC2 Instance

### Steps to Reproduce

1. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @r-aju 👋 Thank you for taking the time to file this. So that we and the community are best able to look into this, can you update the issue with the full data from the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md); particularly the community note section and full debug output?
