### ISSUE TITLE
c5.4xlarge to c5d.4xlarge updates in place, but destroys the instance. No provisioning, IP output not updated.

### ISSUE THREAD

**Issue by magnayn** [hashicorp/terraform-provider-aws#21014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v2.25.0
+ provider registry.terraform.io/hashicorp/aws v3.59.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_instance" "prelive" {
  ami                    = "ami-0a98db1c4a78bcc78" # Instance with docker OOTB
  instance_type          = "c5.4xlarge"
associate_public_ip_address = "true"

  ... more config
}

output "ec2_server_ip" {
  value = "${aws_instance.prelive.public_ip}"
}
```

### Expected Behavior

The resource should be deleted and re-created, potentially with a new IP address reported in the output.

### Actual Behavior

The resource claims to be re-created in-place:

```
# aws_instance.prelive will be updated in-place
  ~ resource "aws_instance" "prelive" {
        id                                   = "i-0769c46c93fab9638"
      ~ instance_type                        = "c5.4xlarge" -> "c5d.4xlarge"
```

But this actually results in the EC2 instance being destroyed and re-created.
None of the provisioners run.
The public IP address changes, but does not get updated in the output variable.

### Steps to Reproduce

1. `terraform apply`
2. change the instance type to c5d.4xlarge
3. `terraform apply` again

### Important Factoids

The initial VM is EC2 only, the new VM has SSDs (which was the reason for upgrade). Not sure if this is important.

### References

* #0000

**Comment by xorxsan** [comment]
I have the same issue when updating the instance from `t3a.micro` to `t3a.small`. I need to run `terraform apply` again for my output to be updated:
```
output "host" {
  value = aws_instance.ubuntu.public_dns
}
```

I'm using the last version of the provider: registry.terraform.io/hashicorp/aws v3.66.0

**Comment by travisdowns** [comment]
@xorxsan @magnayn - the underlying cause is not that the instance is "destroyed" and "recreated" exactly (it's the same *instance* after apply, same ID, etc), but that the terraform provider thinks a stop/start is sufficient to change the instance type. It's true EC2 lets you change the instance type when it is stopped, but the IP address changes which the EC2 provider doesn't know about or handled. Other problems can arise too: e.g., stop/start will delete everything on an instance store drive, which is quite unexpected.

As a workaround, you can additionally encode the instance type into some _other_ property which will force a destroy/recreate. I used `user_data`, just have something like: `#!/bin/bash \n echo ${var.instance_type}` for `user_data` and any change to the instance type will force a recreation of the resource.

**Comment by xorxsan** [comment]
@travisdowns thanks for the information. I did as you suggested and it worked.
