### ISSUE TITLE
aws_subnet_ids filter available-ip-address-count should accept comparison operator

### ISSUE THREAD

**Issue by Arlington1985** [hashicorp/terraform-provider-aws#21038]
Currently aws_subnet_ids Datasource only can filter based on `available-ip-address-count ` if you set exact number or range. But this range can't be more than 200. Considering that fact, also `available-ip-address-count` is number it would more make sense if we could just use like that: 

```
data "aws_subnet_ids" "aws_subnets" {
  vpc_id = vpc-xxxxx

  filter {
    name   = "available-ip-address-count"
    values >1 
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_subnet_ids

### Potential Terraform Configuration

```hcl
data "aws_subnet_ids" "aws_subnets" {
  vpc_id = vpc-xxxxx

  filter {
    name   = "available-ip-address-count"
    values >1 
  }
}
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @Arlington1985 👋 Thank you for taking the time to file this. I took a look into it, and it seems this may be a limitation of the AWS API.

Looking at this data source, the [filter argument](https://github.com/hashicorp/terraform-provider-aws/blob/52ea31f0655af29907389c746ef3701f91f31561/aws/data_source_aws_subnet_ids.go#L16) uses the `ec2CustomFiltersSchema()` function, which [defines `values`](https://github.com/hashicorp/terraform-provider-aws/blob/52ea31f0655af29907389c746ef3701f91f31561/aws/ec2_filters.go#L139-L145) as a set of strings. 

With that in mind, looking at the [AWS API documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSubnets.html) for `DescribeSubnet` (as is linked to in the [aws_subnet_ids](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet_ids#name) documentation), it describes the filter parameter as a list of [filter objects](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Filter.html), which takes a `name` parameter (a string), and a `values` parameter (a list of strings). As this is the case, a comparison operator won't work due to the API requirements needing a string rather than a number.

That said, I did a bit of testing and I think I may have come up with a workaround that might work for you. Example configuration followed by some documentation and explanation for reference:

```hcl
data "aws_subnet_ids" "all" {
  vpc_id = var.vpc_id
}

data "aws_subnet" "all" {
  for_each = data.aws_subnet_ids.all.ids
  id = each.key
}

locals {
  subnets_more_than_one_ip_available = compact(flatten([
    for _, subnets in data.aws_subnet.all[*] : [
      for subnet, attributes in subnets : [
        attributes.available_ip_address_count > 1 ? subnet : ""
      ]
    ]
  ]))
}
```

This approach firsts gets an unfiltered list of subnet IDs using the `aws_subnet_ids` resource you're already using. It then uses `for_each` to iterate over the IDs and retrieve their full set of attributes using the [`aws_subnets`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets) data source. 

After collecting each of the subnet IDs and their attributes, it then uses a ternary operation within a `local` value to extract a list of the subnets the have a `available_ip_addresses_count` that is greater than 1. The [`compact()`](https://www.terraform.io/docs/language/functions/compact.html) and [`flatten()`](https://www.terraform.io/docs/language/functions/flatten.html) functions are then used to strip out the subnets that don't match the criteria (which we're able to do because of the ternary that will produce `""` if the condition does not match) and to flatten it into a nice flat list, respectively.

When using this approach, you'd reference the list of appropriate subnet IDs using `local.subnets_more_than_one_ip_available` (or whatever you decide to call the local) in place of the output of the `aws_subnet_ids` data source.

It's a bit uglier than the filter enhancement that you'd put forth, but given the API restrictions, I think this may be the best bet unless there are changes to the API itself.

**Comment by Arlington1985** [comment]
Hi, @justinretzolk thanks for your invested time to find the workaround. It's really helpful and seems promising. I will try this approach and let you know. But do you think it's worth escalating this enhancement to the  AWS API level?

**Comment by justinretzolk** [comment]
Hi @Arlington1985 I'm glad that the workaround seems promising.

As far as escalating the enhancement for the AWS API, it's a bit difficult for me to speak to that. I suspect that such a change may not be implemented given that the filter objects are used for more than just `DescribeSubnet`, and for the other operations, I'm not sure that a number would make sense over a string. That said, I wouldn't discourage you from escalating it through AWS if your organization has the means to do so - worst they can say is no :smile:

With that in mind, since this seems to be something that can be worked around, and doesn't seem to be a bug with the provider, I'm going to go ahead and close this issue out for now. If you feel I've done this in error, please do let me know.
