### ISSUE TITLE
Resource: aws_apigatewayv2_stage return incorrect invoke_url domain in AWS China

### ISSUE THREAD

**Issue by yongzhang** [hashicorp/terraform-provider-aws#21063]
provider version: latest

The invoke_url domain suffix of aws_apigatewayv2_stage in AWS China should be `amazonaws.com.cn`, but it's hardcoded with `amazonaws.com` in

https://github.com/hashicorp/terraform-provider-aws/blob/baac4b0338b0500475288cd4e14dc30674530e63/aws/resource_aws_apigatewayv2_stage.go#L317-L325

**Comment by ewbankkit** [comment]
We should be using the `RegionalHostname` method:

https://github.com/hashicorp/terraform-provider-aws/blob/baac4b0338b0500475288cd4e14dc30674530e63/aws/config.go#L405-L410

**Comment by mbklein** [comment]
This is a significant issue as well when trying to provision `apigatewayv2` resources using [LocalStack](https://localstack.cloud/). The API endpoint returned by the `CreateApi` or `GetApis` operation takes the form (for example) `73a7dc39.execute-api.localhost.localstack.cloud:4566`, but Terraform thinks it's `https://73a7dc39.execute-api.us-east-1.amazonaws.com/dev`.

A fix based on `RegionalHostname` wouldn't work in this case because the LocalStack endpoint doesn't include the region. (It can't, or the resulting URL would be one level too deep for their `*.localhost.localstack.cloud` wildcard SSL cert to work.)

Is there a reason the `aws_apigatewayv2_stage` can't just append its `stageName` to the `ApiEndpoint` reported by its associated `aws_apigatewayv2_api`?
