### ISSUE TITLE
Default restrictions.geo_restriction for Cloudfront Distributions

### ISSUE THREAD

**Issue by mcandre** [hashicorp/terraform-provider-aws#21070]
### Description

Terraform violates the zero configuration principle for Cloudfront Distributions, placing additional burdens to set a restrictions block, as well as a geo_restriction block inside the restriction block.

By contrast, Ansible modules allow the user to simply default the restrictions for Cloudfront Distributions.

### New or Affected Resource(s)

* aws_cloudfront_distribution

**Comment by justinretzolk** [comment]
Hey @mcandre 👋 Thank you for taking the time to file this issue. Am I correct in understanding that what you're looking for is essentially to not have to explicitly declare a `restrictions.geo_restrictions` block within a given `aws_cloudfront_distribution` resource, instead letting the resource adopt AWS' default values?

I believe this is a limitation of the Terraform SDK at the moment, but may be supported in the new framework. I am going to leave this issue open so that someone with more specific domain knowledge can chime in as possible. In the meantime, if you can provide a bit of clarification around the above question, as well as the rest of the information found in the [issue template](https://github.com/hashicorp/terraform-provider-aws/tree/main/.github/ISSUE_TEMPLATE)? That will help us to look into it a bit more.
