### ISSUE TITLE
Error: Creating metric alarm failed: ValidationError: MetricName must not contain Non-ASCII characters. Status code: 400, request id .... 

### ISSUE THREAD

**Issue by vitaliejicol** [hashicorp/terraform-provider-aws#21112]
Hi There,
I am redeploying one of my Terraform module, but I am getting and error, please see the title. Scope it is to create cloudwatch metric alarm for Cloudfront. I tried all possible scenarios but I am getting constantly the same error when I am changing the metric_name. Can you please advise.

Provider AWS.

          `resource "aws_cloudwatch_metric_alarm" "_5xxErrors" {
            alarm_name          = "${var.tag_app}_alarm_name"
            comparison_operator = "LessThanOrEqualThreshold"
            evaluation_periods  = "1"
            metric_name         = "5xxErrorRate"
            namespace           = "AWS/CloudFront"
            period              = "60"
            statistic           = "Average"
            threshold           = "1"
            alarm_description   = "Bla bla bla bla"
            alarm_actions       = ["${data.aws_sns_topic.blabla.arn}"]
          
            dimensions = {
              DistributionId  = "${aws_cloudfront_distribution.cloudfrontdistribution.id}"
              Region.            = "Global"
            }
          }`

**Comment by justinretzolk** [comment]
Hey @vitaliejicol 👋 Thank you for taking the time to file this issue. So that we have all of the information we need to investigate and reproduce, can you provide the rest of the information from the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by weitzjdevk** [comment]
I am seeing the same thing.

I am still unsure if this happens due to:

Either:
- a  "fast" connection from the machine executing the terraform code (i.e. an EC2 machine in the same AWS account)

Or:
- some kind of service-quota limit


Or both:
- There are some service quota limits how fast one create/delete CloudWatch alarms.


I will investigate the option "fast" vs. "slow" connection

**Comment by weitzjdevk** [comment]
My guess is a service quota limit:

## Rate of DescribeAlarms requests

![image](https://user-images.githubusercontent.com/52415337/154973283-fd5a687a-59c1-4fc7-a82b-9bf94dda902f.png)

## Rate of PutMetricAlarm requests
![image](https://user-images.githubusercontent.com/52415337/154973376-d0dd3ae2-b84d-49ce-ab06-2fa76f030758.png)

**Comment by weitzjdevk** [comment]
It is indeed a rate-limit from CloudWatch.

The parameter is adjustable, but the AWS support urged me to throttle terraform
