### ISSUE TITLE
aws_ses_event_destination.cloudwatch_destination.default_value validation is needless

### ISSUE THREAD

**Issue by YOwatari** [hashicorp/terraform-provider-aws#21150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ses_event_destination

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ses_event_destination" "example" {
  name                   = "test"
  configuration_set_name = aws_ses_configuration_set.example.name
  matching_types         = ["send"]
  enabled                = false

  cloudwatch_destination {
    default_value  = "example.com"
    dimension_name = "ses:from-domain"
    value_source   = "messageTag"
  }
} 
```

### Expected Behavior

I is wondering if cloudwatch_destination.0.default_value validation is needless.
It is also possible to input data that actually contains dots.

![SES Console Screenshot](https://user-images.githubusercontent.com/4982161/135967625-6e723a4d-27f7-43ab-9b7d-7a504a3883df.png)

### Actual Behavior

```
Error: invalid value for cloudwatch_destination.0.default_value (must contain only alphanumeric, underscore, and hyphen characters)
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/hashicorp/terraform-provider-aws/pull/13964

**Comment by justinretzolk** [comment]
Hey @YOwatari 👋 Thank you for filing this. I took a look and will outline what I found below. The gist of it is that this seems to be a restriction imposed by the underlying SDK.

The `cloudwatch_distribution` argument is processed in [these lines](https://github.com/hashicorp/terraform-provider-aws/blob/626859bb3a4be097426160209617d01e5132d2cb/aws/resource_aws_ses_event_destination.go#L171-L177) of the provider, which sets up a `ses.CloudWatchDestination`. This struct has one field; `DimensionConfigurations`. The value of which is set using the [generateCloudWatchDestination](https://github.com/hashicorp/terraform-provider-aws/blob/626859bb3a4be097426160209617d01e5132d2cb/aws/resource_aws_ses_event_destination.go#L298-L312) function.

This function returns a list of type `ses.CloudWatchDimensionConfiguration`. This struct is defined in the AWS Go SDK [here](https://github.com/aws/aws-sdk-go/blob/1c5e23be58e1457f8254e5ea6b37534d82440b4b/service/ses/api.go#L7227-L7261), and has the following note (to save you a click):

```go
	// The default value of the dimension that is published to Amazon CloudWatch
	// if you do not provide the value of the dimension when you send an email.
	// The default value must:
	//
	//    * This value can only contain ASCII letters (a-z, A-Z), numbers (0-9),
	//    underscores (_), or dashes (-).
	//
	//    * Contain less than 256 characters.
	//
	// DefaultDimensionValue is a required field
	DefaultDimensionValue *string `type:"string" required:"true"`
```

Additionally, looking at the [API documentation](https://docs.aws.amazon.com/ses/latest/APIReference/API_CloudWatchDimensionConfiguration.html) for `CloudWatchDimensionConfiguration`, we see that the API imposes the same validation.

Since this is something that's imposed by the underlying SDK, I'm going to go ahead and close this issue out for now. If you feel I've done this in error, please do let me know.

**Comment by YOwatari** [comment]
@justinretzolk 
I found the document content to be inconsistent.
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-add-event-destination-cloudwatch.html

> For Dimension Name, type the name of the dimension that you want to pass to CloudWatch. For Default Value, type the value of the dimension.
> Dimension names and values can only contain the letters A through Z, the numbers 0 through 9, underscores (_), at signs (@), hyphens (-), and periods (.). Spaces, accented characters, non-Latin characters, and other special characters are not allowed.
