### ISSUE TITLE
"aws_quicksight_user" resource doesn't allow custom namespace

### ISSUE THREAD

**Issue by YuriGal** [hashicorp/terraform-provider-aws#21166]
### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.8
on darwin_amd64
provider registry.terraform.io/hashicorp/aws v3.60.0

### Affected Resource(s)

* aws_quicksight_user

### Terraform Configuration Files

```hcl
resource "aws_quicksight_user" "author" {
  email         = "email@example.com"
  identity_type = "IAM"
  user_role     = "AUTHOR"
  iam_arn       = aws_iam_user.user.arn
  namespace     = "NewOrg"
  provider      = aws.us-east-1
}
```

### Expected Behavior

User should be created in the namespace "NewOrg"

### Actual Behavior

Error message: "expected namespace to be one of [default], got NewOrg"

### Steps to Reproduce

Just try to create a quicksight user in any namespace besides default.

AWS API (i.e. CLI `aws quicksight register-user --namespace`) does support registering user in a different namespace. Could you make this available in the provider as well?

**Comment by justinretzolk** [comment]
Hey @YuriGal 👋 Thank you for taking the time to file this issue. I took a look over the relevant [CLI](https://docs.aws.amazon.com/cli/latest/reference/quicksight/register-user.html), [API](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_RegisterUser.html#API_RegisterUser_RequestSyntax), and [Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/quicksight/#RegisterUserInput) documents for this, and it looks like this is a limitation of the underlying API. In each of the linked documents, it has a similar note for `namespace`:

> The namespace. Currently, you should set this to `default`.

Since this is a limitation of the API, I'm going to close this issue for now. If this becomes available in the API at a later date, we can look into adding the functionality to the provider.
