### ISSUE TITLE
SNS State Refreshes and Subscriptions Fail in us-iso-b due to Tagging Not Existing

### ISSUE THREAD

**Issue by countessellis** [hashicorp/terraform-provider-aws#21209]
Relates #18593

Because tagging doesn't currently exist for SNS in us-iso-b, and because when trying to refresh the state or do other operations against an SNS topic after creation tries pulling the tags, the operation fails.  The AWS platform returns a 400 with the following when trying to update the resource:

> InvalidAction: Unsupported Action

And a 403 with the following when trying to list tags:

> AuthorizationError: You are not authorized to perform tagging operations

As a result, further resources cannot be created as the provider gives no method to skip updating or listing tags, even when there are no tags specified in the terraform code.

**Comment by justinretzolk** [comment]
Hey @countessellis 👋 Thank you for taking the time to file this issue. So that we have all of the information necessary to investigate this, can you update the issue description with the additional information found in the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by YakDriver** [comment]
@countessellis Thank you for bring this to our attention!

Since this is difficult for a us to test, when the fix in #22511 is merged, we would appreciate your help verifying that this issue is resolved. (@lorengordon)
