### ISSUE TITLE
aws_s3_bucket_object not working with more than 10 default tags

### ISSUE THREAD

**Issue by chris922** [hashicorp/terraform-provider-aws#21273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When you define more than 10 default tags in your AWS provider it is not possible to use the `aws_s3_bucket_object` resource, because AWS doesn't allow more than 10 tags for S3 objects.

I guess this problem should be solved on a higher level, e.g. introduce a possibility to exclude certain or all default tags for any resource or exclude on AWS provider level certain resources for default tags.

Workaround: Creating an additional AWS provider with an alias that do not have any default-tags. :(

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.50.0
```

### Affected Resource(s)

* aws_s3_bucket_object

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "eu-central-1"
  
  default_tags {
    tags = {
      tag1 = "value1"
      tag2 = "value2"
      tag3 = "value3"
      tag4 = "value4"
      tag5 = "value5"
      tag6 = "value6"
      tag7 = "value7"
      tag8 = "value8"
      tag9 = "value9"
      tag10 = "value10"
      tag11 = "value11"
    }
  }
}

resource "aws_s3_bucket" "bucket" {
  name = "foo"
}

resource "local_file" "foo" {
  content = "Lorem ipsum"

  filename = "test_file.txt"
}

resource "aws_s3_bucket_object" "object" {
  bucket = aws_s3_bucket.bucket.bucket
  
  key = "bar"
  
  source = local_file.foo.filename
  etag = filemd5(local_file.foo.filename)
}
```

### Debug Output

Error: Error putting object in S3 bucket (foo): BadRequest: Object tags cannot be greater than 10

### Expected Behavior

It is possible to create the s3_object

### Actual Behavior

It is not possible to create the s3_object

### Steps to Reproduce

1. `terraform init && terraform apply`

**Comment by ollytheninja** [comment]
Would it be better to have a way to choose which default tags to choose or ignore?
i.e. the `ignore_default_tags` property takes a list of default tags to ignore?

I've come across this issue because I was looking for issues related to this Terraform provider validating how many tags are passed to AWS. Even without >10 default tags it is cumbersome to have `aws_s3_bucket_object` inherit the tags I want it to have (using a `merge()`).

Because of this I would suggest perhaps a `filter_tags` option to specify which tags should be included.
This would probably be more work to implement, happy to open a new ticket but interested to hear what others are thinking.

**Comment by ewbankkit** [comment]
Relates: #19895.

**Comment by chris922** [comment]
@ollytheninja : I would already be fine with a `ignore_default_tags` boolean flag that I can just set to true and no default tags will be included at all. Maybe there is a nice way to support both? e.g. allow wildcards like `*` so that you can define one of:

```hcl
ignore_default_tags = ["foo", "bar"]

ignore_default_tags = ["foo*"]

ignore_default_tags = ["*"]
```

As we often group tags via prefixes allowing wildcards would allow to ignore whole groups of prefixes :)

**Comment by ollytheninja** [comment]
@chris922 I think if the filter approach is used then the parameter needs to be `filter_default_tags` since `ignore_default_tags` implies a boolean.
I also think we should have the option to filter all tags, not just default tags.
Many organizations have a collection of tags they extend / apply into the tag parameter, being able to filter those also would be ideal.

I guess there are multiple possible solutions here, one or more of which could be applied:
- Static validation in the terraform provider to error sooner.
- Ability to not include default tags
- Ability to filter default tags
- Ability to filter all tags

I've never contributed to Terraform, I'll see if I can find the time in the next few weeks to dive in and understand what would be required to implement this.
Interested to hear others' thoughts on how to overcome this limitation in AWS!

**Comment by jwhitcraft** [comment]
has there been any movement on this?  We just got bit by this, and I'd like a way to just have this ignore the default_tags coming in and just take the tags passed into it.

**Comment by ericrichtert** [comment]
I missed this issue, so from #24692, I'd like to mention two possible options:
* don't apply default_tags on aws_s3_object if the number of tags > 10
* don't apply default_tags on aws_s3_object

**Comment by nvandermark** [comment]
We've also run into this issue where I work. Because of our tagging policy, which lists more than 10 required tags.

**Comment by dzierzanowski** [comment]
This issue is still very much relevant.

**Comment by jamespfluger-ava** [comment]
It's important to mention this is not mentioned in the Terraform documentation either, so it's upon the user to either read the exact AWS documentation or to (more likely) stumble across the error themselves.

**Comment by marcottedan** [comment]
I don't understand how this bug is still present and not prioritized. There is also no clean workaround...

**Comment by jamespfluger-ava** [comment]
The above MR would remove the default tags (good) but we need AWS to increase the S3 tagging limit for TF to have this fixed.

**Comment by ollytheninja** [comment]
@jamespfluger-ava while I zagerer this is on AWS to fix properly, given S3 object tagging [was introduced](https://aws.amazon.com/about-aws/whats-new/2016/11/revolutionizing-s3-storage-management-with-4-new-features/) in 2016, three months **after** [other tags were increased](https://aws.amazon.com/blogs/security/now-organize-your-aws-resources-by-using-up-to-50-tags-per-resource/) from 10 to 50. I for one won't be holding my breath on AWS fixing it anytime soon.
