### ISSUE TITLE
aws_service_discovery_service accept multiple namespace

### ISSUE THREAD

**Issue by Weigle** [hashicorp/terraform-provider-aws#21618]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

in my script terraform i need create miltiple namespace (Service instances) , but the resource accept only 1 namespace

### New or Affected Resource(s)

namespace_id = String
to
namespace_id = []

### Potential Terraform Configuration

```hcl
resource "aws_service_discovery_service" "service_discovery" {
  name = "service-discovery"

  dns_config {
    namespace_id = aws_service_discovery_private_dns_namespace.ecs_segment.id

    dns_records {
      ttl  = 60
      type = "A"
    }

    routing_policy = "MULTIVALUE"
  }

}
```
to

```hcl
resource "aws_service_discovery_service" "service_discovery" {
  name = "service-discovery"

  dns_config {
    namespace_id = [aws_service_discovery_private_dns_namespace.ecs_segment.id]

    dns_records {
      ttl  = 60
      type = "A"
    }

    routing_policy = "MULTIVALUE"
  }

}
```
### References

* https://docs.aws.amazon.com/cloud-map/latest/dg/creating-services.html

**Comment by justinretzolk** [comment]
Hey @Weigle 👋 Thank you for taking the time to file this issue. I took a look over the relevant struct definition in the [AWS Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/servicediscovery/#DnsConfig) and it looks like it expects a string here rather than a list, so I'm not certain that this is something the SDK would support.

With that in mind, unless I'm misunderstanding a key part of how this resource works, I suspect you could make this work via [`for_each`](https://www.terraform.io/docs/language/meta-arguments/for_each.html). Perhaps a configuration such as this?

```hcl
resource "aws_service_discovery_service" "service_discovery" {

  // for_each requires either a map or set of strings, so we use toset() here to make the list a map.
  // I'm unsure of how you'd want to gather this list, so I used a variable as an example.
  for_each = toset([var.your_list_of_namespaces])

  name = "service-discovery"

  dns_config {
    namespace_id = each.key

    dns_records {
      ttl  = 60
      type = "A"
    }

    routing_policy = "MULTIVALUE"
  }

}
```
