### ISSUE TITLE
Creating a Lambda Layer from the aws serverless repository

### ISSUE THREAD

**Issue by reply2srij** [hashicorp/terraform-provider-aws#21638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Serverless Repository provides us modules which can be deployed into lambda as layers. One such example is: 
https://github.com/serverlesspub/imagemagick-aws-lambda-2

How can we accomplish this using terraform resource: aws_lambda_layer_version? 

Would it be possible to have an attribute that can create a layer?
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version#argument-reference

**Comment by justinretzolk** [comment]
Hey @reply2srij 👋 Thanks for taking the time to submit this issue. It doesn't look like this is natively supported in the SDK, so you may need to work past that limitation in other ways. I'd recommend asking in the [AWS Provider Discuss forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) to see if anyone else has solved a similar challenge, however, I thought about it a bit to try to get you pointed in a couple of possible directions. 

**Full disclosure:** I haven't tested these methods myself; these are entirely hypothetical solutions. 

Since the `aws_lambda_layer_version` accepts a local `filename` path, you could potentially: 

- Pull in the source repository, zip the contents, and store them alongside your Terraform configuration
- Potentially use the [github_repository_file](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository_file) data source paired with the [archive_file](https://registry.terraform.io/providers/hashicorp/archive/latest/docs/data-sources/archive_file) data source in order to create the zip file at apply time. 
- In looking around, I also found a community provider called [zipper](https://registry.terraform.io/providers/ArthurHlt/zipper/latest/docs/resources/file) that seems like it could be promising.

Another option might be to asynchronously zip and upload the content of the repository to an S3 bucket so that you could use the `s3_` prefixed arguments.

**Comment by DanyC97** [comment]
👋  @reply2srij  you may want to also look at https://github.com/awslabs/aws-lambda-powertools-python/pull/716 which deploy the SAR app using CFN . hope that helps

**Comment by reply2srij** [comment]
Thanks for looking into this. You are right, I realized the sdk doesn't support it. 
For my requirement, I was able to use https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/serverlessapplicationrepository_cloudformation_stack and some conditional logic for layers in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function
