### ISSUE TITLE
ElasticSearch cluster instance is missed from the sate if provisioning failed

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform-provider-aws#21648]
### Terraform CLI and Terraform AWS Provider Version

tf version 1.0.9
aws plugin 3.63.0

I'm using local provisioning in the ES cluster definition:

```
resource "aws_elasticsearch_domain" "app" {
  domain_name = local.domain_name
  elasticsearch_version = "7.10"
  cluster_config {
    instance_type = "t3.medium.elasticsearch"
    instance_count = var.instance_count
  }
  provisioner "local-exec" {
    working_dir = "${path.module}/../provisioning/local"
    command = "./elasticsearch.sh ${aws_elasticsearch_domain.app.endpoint}"
  }
}
```

If the provisioning script fails, the resource remains created but TF doesn't save it to the state and on the next run it will always fail because the resource already exists:

```
Plan: 38 to add, 0 to change, 1 to destroy.
module.backend.module.es.aws_elasticsearch_domain.app: Creating...
╷╷
│ Error: ElasticSearch domain rev-f-m2-5200-optimi already exists
```

TF must store the cluster in the state and destroy it on the next run because it was not provisioned successfully.

**Comment by justinretzolk** [comment]
Hey @speller 👋 Thank you for taking the time to open this issue! So that we have all of the information that we need in order to look into this, can you update the issue description with the rest of the information requested in the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
