### ISSUE TITLE
data aws_network_interface bug

### ISSUE THREAD

**Issue by devopsrick** [hashicorp/terraform-provider-aws#21647]
Bug introduced in v3.64.1/v3.64.0.  This did not happen in v3.63.0

Terraform code:
```
data "aws_network_interface" "mongos_prod" {
  count = length(local.nlb_interface_ids_mongos)
  id    = local.nlb_interface_ids_mongos[count.index]
}
```

Error:
> Error: error setting attachment: Invalid address to set: []string{"attachment", "0", "instance"}
> 
>   on service_endpoints.tf line 925, in data "aws_network_interface" "mongos_prod":
>  925: data "aws_network_interface" "mongos_prod" {
> 
> 
> 
> Error: error setting attachment: Invalid address to set: []string{"attachment", "0", "instance"}
> 
>   on service_endpoints.tf line 925, in data "aws_network_interface" "mongos_prod":
>  925: data "aws_network_interface" "mongos_prod" {
> 
> 
> 
> Error: error setting attachment: Invalid address to set: []string{"attachment", "0", "instance"}
> 
>   on service_endpoints.tf line 925, in data "aws_network_interface" "mongos_prod":
>  925: data "aws_network_interface" "mongos_prod" {
>

**Comment by davepattie** [comment]
Identical issue, we've rolled back provider last night, I was just heading here to report.  Thanks

**Comment by ewbankkit** [comment]
##### Data Source

https://github.com/hashicorp/terraform-provider-aws/blob/7b653cf088c7c5522aa6a9430f1de19c677d6674/internal/service/ec2/network_interface_data_source.go#L58-L81

##### Resource

https://github.com/hashicorp/terraform-provider-aws/blob/7b653cf088c7c5522aa6a9430f1de19c677d6674/internal/service/ec2/network_interface.go#L36-L56

The underlying issue was present in **v3.63.0** (and earlier):

https://github.com/hashicorp/terraform-provider-aws/blob/fce7062f70caa92a78bca629ffe441c088456418/aws/data_source_aws_network_interface.go#L180-L183

and #21265 surfaced it with the addition of error checking 😢 😄 🤷.

I'll leave on the _regression_ label so that we prioritize the fix.
