### ISSUE TITLE
Data source aws_db_instance returns null value when db_instance_identifier is empty

### ISSUE THREAD

**Issue by marpada** [hashicorp/terraform-provider-aws#21663]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
terraform {
  required_version = "1.0.10"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.64.2"
    }
  }
}

provider "aws" {
}

data "aws_db_instance" "rds-instance" {
  db_instance_identifier = ""
}
output "arn" {
  value = data.aws_db_instance.rds-instance.db_instance_arn
}

```

### Expected Behavior

Data source should throw a "DBInstanceNotFound: DBInstance "" not found." error

### Actual Behavior

Data source returns a null object
```
terraform state show data.aws_db_instance.rds-instance
# data.aws_db_instance.rds-instance:
data "aws_db_instance" "rds-instance" {}
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform state show data.aws_db_instance.rds-instance`

**Comment by kamilturek** [comment]
It does raise an error for me.
```
$ terraform providers                                                                                                     4s

Providers required by configuration:
.
└── provider[registry.terraform.io/hashicorp/aws] 3.63.0

$ terraform plan
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_db_instance.rds-instance,
│   on main.tf line 37, in data "aws_db_instance" "rds-instance":
│   37: data "aws_db_instance" "rds-instance" {
```

**Comment by marpada** [comment]
The error can be reproduced if the region has an RDS instance.

Region with 1 RDS instance
```
AWS_DEFAULT_REGION=ap-southeast-2 terraform apply

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

On a region without any instance
```
AWS_DEFAULT_REGION=us-east-1 terraform apply
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│
│   with data.aws_db_instance.rds-instance,
│   on main.tf line 14, in data "aws_db_instance" "rds-instance":
│   14: data "aws_db_instance" "rds-instance" {
│
╵
```

**Comment by kamilturek** [comment]
@marpada Oh, you're right. Thanks!

It turns out that [DescribeDBInstances](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html) API call returns **all** DB instances when specified DB instance identifier is blank. That part is totally fine, that's how the API works. The problem is that in such case we set blank string (`db_instance_identifier = ""`) as the resource ID. I assume that's why all the resource attributes are then blank.
https://github.com/hashicorp/terraform-provider-aws/blob/9f36b9c2ffac705a4271722081723d49047f538f/internal/service/rds/instance_data_source.go#L243

Although this can be easily patched, I think that the better solution would be to just enforce `db_cluster_indentifier` argument to be non-empty. This can be a bit not in line with the AWS API but I'd assume that using `aws_db_instance` one expects exactly one matched instance.
