### ISSUE TITLE
aws_vpc creation with DHCP options set association results in suspicious state. Default DHCP options set not working.

### ISSUE THREAD

**Issue by marcinbelczewski** [hashicorp/terraform-provider-aws#21708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.9
on darwin_arm64
+ provider  hashicorp/aws v3.64.2
```

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

Here's a simple repository containin the sample Terraform code used: https://github.com/marcinbelczewski/terraform-dhcp-options

```hcl
terraform {
  required_version = "~> 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
  backend "local" {
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "172.19.0.0/21"
}

resource "aws_vpc_dhcp_options" "dhcp" {
    domain_name_servers = ["AmazonProvidedDNS"]
}

resource "aws_vpc_dhcp_options_association" "dhcp" {
  vpc_id          = aws_vpc.vpc.id
  dhcp_options_id = aws_vpc_dhcp_options.dhcp.id
}

output "vpc_dhcp_options_in_terraform_state" {
    value = aws_vpc.vpc.dhcp_options_id
}

output "vpc_dhcp_options_in_aws" {
    value = aws_vpc_dhcp_options.dhcp.id
}
```

### Debug Output

Terraform debug output for initial *terraform apply*: https://gist.github.com/marcinbelczewski/96a09a1812d0bbcb578814b9fe13aa72

### Expected Behavior

DHCP options set is created and assiciated with the VPC with this being recognized properly in *aws_vpc.dhcp_options_id* property in Terraform state.

Executing *terraform plan* after the *terraform apply* does not highlight any drift.

### Actual Behavior

*aws_vpc.dhcp_options_id* property is set to the id of default (Amazon provided) DHCP options set in AWS region rather than the newly created one in Terraform code (incorrect). 
In AWS Management Console it can be confirmed that the VPC indeed is associated with newly created DHCP options set rather than the default one (correct).

Executing *terraform plan* after the *terraform apply* highlights drift indicating that *aws_vpc.dhcp_options_id* should have different value.

### Steps to Reproduce

The steps below show an extended example where a revert to "default" DHCP option set is attempted and unsuccessful.

1. initialise and apply VPC alongside DHCP options set

    ```hcl
    terraform init
    terraform apply -auto-approve
    ```
    Notice different values of *vpc_dhcp_options_in_terraform_state* and *vpc_dhcp_options_in_aws* outputs, the latter being the value matching the one in AWS Management Console.

2. Execute 
    ```hcl
    terraform plan
    ```
    And notice the message *Note: Objects have changed outside of Terraform: Terraform detected the following changes made outside of Terraform since the last "terraform apply"* referring VPC's *dhcp_options_id* property.

3. To remove drift execute 
    ```hcl
    terraform apply -auto-approve
    ```
    And only now notice values of *vpc_dhcp_options_in_terraform_state* and *vpc_dhcp_options_in_aws* outputs matching.

4. To attempt reverting to default DHCP remove the following resources from main.tf
    * aws_vpc_dhcp_options
    * aws_vpc_dhcp_options_association
    * output vpc_dhcp_options_in_aws

5. Execute
    ```hcl
    terraform apply -auto-approve
    ```
    And notice the value of *vpc_dhcp_options_in_terraform_state* pointing to the id of DHCP options set just destroyed rather than the default one for AWS region.

6. Execute 
    ```hcl
    terraform plan
    ```
    And notice the message *Note: Objects have changed outside of Terraform: Terraform detected the following changes made outside of Terraform since the last "terraform apply"* referring VPC's *dhcp_options_id* property suggesting the change to "default" value.

7. To remove drift execute
    ```hcl
    terraform apply -auto-approve
    ```
    And notice the value of *vpc_dhcp_options_in_terraform_state* being "default".
    
    Verify in AWS Management Console that despite "default" value for *dhcp_options_id" in Terraform, the VPC has no default DHCP Options set associated.

**Comment by justinretzolk** [comment]
Hey @marcinbelczewski 👋 Thank you for taking the time to file this issue, and for the detailed reproduction. That was really helpful in understanding what's going on here. I apologize in advance, as this is going to be a bit of a lengthy reply.

Looking at the configuration, there's three main things that we need to consider the ordering for in order to better understand what's happening here. 

1. `aws_vpc.vpc`: This resource doesn't have any dependencies, so Terraform will get to work creating it pretty much immediately.
2. `aws_vpc_dhcp_options.dhcp`: This resource _also_ doesn't have any dependencies, so the same applies. Importantly, for later, this resource doesn't actually modify the VPC unless the `aws_vpc_dhcp_options_association` resource is used.
3. `aws_vpc_dhcp_options_association.dhcp`: This resource has two implied dependencies (the ones above), due to the use of interpolation, so will be created _after_ the other two, and is when the VPC is actually modified (after creation).

With the ordering in mind, we can then start to get a better idea of what is happening here. When the `aws_vpc.vpc` resource is created, the final part of that function is to perform [a read operation](https://github.com/hashicorp/terraform-provider-aws/blob/25a4e3423d98eb56ad7aeed52dfb11b077fff314/internal/service/ec2/vpc.go#L247) to read back the results of the creation call. Importantly, what is returned from this read call is what determines what is stored in the state for this resource.

Going back to the notion that `aws_vpc_dhcp_options_association.dhcp` is dependent on `aws_vpc.vpc`, the association of `aws_vpc_dhcp_options.dhcp` won't happen until after `aws_vpc.vpc` is created and saved to the state. Similar to the VPC creation, the `aws_vpc_dhcp_options_association` resource also [reads after creation](https://github.com/hashicorp/terraform-provider-aws/blob/25a4e3423d98eb56ad7aeed52dfb11b077fff314/internal/service/ec2/vpc_dhcp_options_association.go#L82) in order to determine what is stored in the state (this isn't special to these resources, but rather is a fairly common pattern).

Looking at what has happened so far in this timeline we're stepping through, we start to see where the difference in the state/outputs comes from -- before the association/modification of the VPC occurs, the state of `aws_vpc.vpc` has already been saved to the state. On the next run, however, Terraform will read `aws_vpc.vpc` again and detect the drift, leading to the "Objects have changed outside of Terraform" message.

Once you get to step 4 of your reproduction and are reverting the details, a similar thing happens, but in reverse. During the plan phase, `aws_vpc.vpc` is read and detects no changes (since the other resources haven't been destroyed yet). Since there were no changes, there's no reason to re-read the resource after the other resources are destroyed, ultimately leading to a difference in the state yet again; which needs to be rectified on the next run (as you're seeing with the recurrence of that "Objects have changed outside of Terraform" message).

I hope this helps shed a bit more light on what's happening here. If any of this is unclear, or you have follow up questions, I'll be happy to continue the conversation!

**Comment by marcinbelczewski** [comment]
Hi @justinretzolk !

Thank you very much for very detailed explanation on what is going on in this case. It is now clear to me what is happening however, I have two follow-up questions:

1. Do I understand correctly that this is not a bug and that Terraform is not aiming at idempotency in such cases? I'm sometimes working on my own modules and testing them with terratest using "ApplyAndIdempotent" terratest function which in the above case would result in a failure as the code is not idempotent. 
I simply thought that Terraform and its providers were to be idempotent (second apply results in 0 changes) and any lack of idempotency is potentially a bug worth reporting. I'm not arguing that it should be idempotent just trying to understand the constraints so that I can have better future judgment analyzing what might potentially be a bug and what might be not.

2. When the steps above are executed past step 7, so that the VPC's *dhcp_options_id* is assigned the value of "default", I'm not really sure what that means from the perspective of AWS configuration. The "default" behavior during VPC creation is to associate an Amazon provided DHCP options set with the VPC. 
But here, the association of "default" value with VPC in Terraform state, results in no such thing. In AWS the VPC is left with no DHCP options set associated. So I guess I do not really understand what "default" value of *dhcp_options_id* stands for in AWS provider. I was hoping it would associate the VPC with default DHCP options set especially since that's how I understood this document: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_dhcp_options_association which mentions: *Removing the DHCP Options Association automatically sets AWS's default DHCP Options Set to the VPC.*

Cheers!
Marcin
