### ISSUE TITLE
Add support for FARGATE Windows Containers and ARM based Containers

### ISSUE THREAD

**Issue by brendorfer** [hashicorp/terraform-provider-aws#21706]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Almost two weeks ago, AWS added support for FARGATE Windows containers.
https://aws.amazon.com/about-aws/whats-new/2021/10/aws-fargate-amazon-ecs-windows-containers/

### New or Affected Resource(s)

* aws_ecs_task_definition

### Potential Terraform Configuration

```hcl
resource "aws_ecs_task_definition" "service" {
  family                     = var.service_name
  network_mode               = "awsvpc"
  execution_role_arn         = var.role
  task_role_arn              = var.role
  requires_compatibilities   = ["FARGATE"]
  cpu                        = var.cpu
  memory                     = var.memory
  container_definitions      = templatefile("task-definitions/${var.service_name}.task")

  runtimePlatform {
    #Valid Values: WINDOWS_SERVER_2019_FULL | WINDOWS_SERVER_2019_CORE | WINDOWS_SERVER_2016_FULL | WINDOWS_SERVER_2004_CORE | WINDOWS_SERVER_2022_CORE | WINDOWS_SERVER_2022_FULL | WINDOWS_SERVER_20H2_CORE | LINUX
    operatingSystemFamily = "WINDOWS_SERVER_2019_CORE"
  
    #Valid Values: X86_64 | ARM64
    cpuArchitecture       = "X86_64"
  }
}
```

### References

* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RuntimePlatform.html
* https://aws.amazon.com/about-aws/whats-new/2021/10/aws-fargate-amazon-ecs-windows-containers/

**Comment by ChrisMcKee** [comment]
The task definition in the api https://docs.aws.amazon.com/AmazonECS/latest/userguide/task_definition_parameters.html (e.g. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/example_task_definitions.html) 
places platformFamily at the root of the definition.

I was looking at the mapping for this earlier but the api validation values seem to exceed the current available options via the AWS UI (core/full/linux), it also provides for the cpuarchitecture though my last check (a few hours ago) arm fargate was still on the roadmap. (https://github.com/aws/containers-roadmap/issues/793)

Following the spec would it make sense to match the task def param spec and keep it flat, mapped to platformFamily with the cpu defaulted initially to x86 untill the TD docs been updated to accomodate it and the 

```
resource "aws_ecs_task_definition" "service" {
  ...

  platformFamily = "WINDOWS_SERVER_2019_CORE"
  
  }
}
```

The provider would have to take in the platformFamily ala
```
			"platform_family": {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringInSlice(ecs.OSFamily_Values(), false),
			},
```

and the resourceTaskDefinitionCreate/resourceTaskDefinitionRead methods made to handle the awssdk api expectations

```
type RuntimePlatform struct {
	...

	// The CPU architecture.
	CpuArchitecture *string `locationName:"cpuArchitecture" type:"string" enum:"CPUArchitecture"`

	// The operating system.
	OperatingSystemFamily *string `locationName:"operatingSystemFamily" type:"string" enum:"OSFamily"`
}
```

and the setting against the existing type from the string input

I'd guess the final layout will depend on how close we are to graviton2 on fargate / and also the validation (assuming stopping arm-windows would happen at the provider rather than relying on the upstream api)

**Comment by riferrei** [comment]
Today Amazon launched the support for graviton on AWS Fargate, as you can read [here](https://aws.amazon.com/blogs/aws/announcing-aws-graviton2-support-for-aws-fargate-get-up-to-40-better-price-performance-for-your-serverless-containers/).

I wonder if this can unlock this issue to move forward. I'm happy to contribute with PR to address this.

**Comment by cageyv** [comment]
@brendorfer, I suggest renaming this issue to `Add support for FARGATE Windows Containers and ARM based Containers`
This will help others to find and avoid creating duplicates.

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/144448244-a8e2de5b-e60b-4028-8521-8fd6224ec38f.png)
![image](https://user-images.githubusercontent.com/83597/144448295-69b6a5f2-8f07-49dc-84c6-bc4c9f320762.png)

I've added the properties and mappings and tested it locally against the project I intended to use this on (thank god the local development setup is better in tf than it used to be) 

I'm a tad _overwhelmed_ by the amount of _stuff_ linked off the contribution docs; did no one look at that and think; jesus a few bullet points might cut it 😆 

Just looking at the existing tests to work out what the deal is

**Comment by ChrisMcKee** [comment]
is make fmt supposed to tidy the hcl strings in the tests as well?
Solution could do with a .editorconfig file to simplify consistency; go fmt is ok but the actual fmt check used seems more stringent

**Comment by ChrisMcKee** [comment]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html 

I've treated the properties as flat based on what was in the docs at the time (platformFamily at root taking LINUX/Win etc) 
but runtime has also been added to the tdp docs and covers the same + cpu. 

As these are only configurable once on an entry like memory/cpu/image I assume that's acceptable vs introducing a new object into the HCL?

**Comment by ChrisMcKee** [comment]
PR pushed^

**Comment by ChrisMcKee** [comment]
Format will be 
```
  runtime_platform {
    operating_system_family = "WINDOWS_SERVER_2019_CORE"
    cpu_architecture = "X86_64"
  }
```
