### ISSUE TITLE
AWS provider version 3.55 for DMS endpoint

### ISSUE THREAD

**Issue by eshnayder-trepp** [hashicorp/terraform-provider-aws#21816]
Hello,
with the AWS provider migration from prior to 3.55 to 3.55 (where new DMS endpoint parameters were introduced) or later version, the existing DMS endpoints are not updated properly or not updated at all. The issue mostly applies to the `extra_connection_attributes` property. We execute `terraform apply` and it finishes successfully but when you check the actual configuration in AWS console you can see that it doesn’t match the one in tf file. If we issue another `terraform apply`, it shows the difference and you can apply the configuration again but the changes are not applied either. You can do it over and over with the successful result reported by terraform and the incorrect configuration appearing on the resource.
Any thoughts?
Thanks.

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.7
provider registry.terraform.io/hashicorp/aws v3.55.0

### Affected Resource(s)

* aws_dms_endpoint

**Comment by justinretzolk** [comment]
Hey @eshnayder-trepp 👋 Thank you for taking the time to file this issue. So that we have all of the information necessary to look into this, can you update the issue description with the rest of the information found in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
