### ISSUE TITLE
resource/aws_route_table: route table is removed from state when it fails to be available (in 2m) on creation

### ISSUE THREAD

**Issue by ialidzhikov** [hashicorp/terraform-provider-aws#21829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform version - 0.12.31
provider-aws version - 3.63.0

### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  access_key = var.ACCESS_KEY_ID
  secret_key = var.SECRET_ACCESS_KEY
  region     = "eu-west-1"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.222.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_route_table" "routetable_main" {
  vpc_id = aws_vpc.vpc.id
}
```

### Expected Behavior

aws_route_table resource to be resilient to AWS EC2 consistency issues and to do not remove a route table from the state that will become present in the AWS API after some time.

### Actual Behavior

With the above partial configuration we notice that a aws_route_table leaks when it fails to be available (in 2m) on creation.

Here is the output from the first `terraform apply` run:

```
aws_route_table.routetable_main: Creating...
aws_route_table.routetable_main: Still creating... [10s elapsed]
aws_route_table.routetable_main: Still creating... [20s elapsed]
aws_route_table.routetable_main: Still creating... [30s elapsed]
aws_route_table.routetable_main: Still creating... [40s elapsed]
aws_route_table.routetable_main: Still creating... [50s elapsed]
aws_route_table.routetable_main: Still creating... [1m0s elapsed]
aws_route_table.routetable_main: Still creating... [1m10s elapsed]
aws_route_table.routetable_main: Still creating... [1m20s elapsed]
aws_route_table.routetable_main: Still creating... [1m30s elapsed]
aws_route_table.routetable_main: Still creating... [1m40s elapsed]
aws_route_table.routetable_main: Still creating... [1m50s elapsed]
aws_route_table.routetable_main: Still creating... [2m0s elapsed]

Error: error waiting for Route Table (rtb-1234) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)

  on tf/main.tf line 52, in resource "aws_route_table" "routetable_main"
  52: resource "aws_route_table" "routetable_main"
```

Running terraform apply once again yields the following ouput:

```
aws_route_table.routetable_main: Refreshing state... [id=rtb-1234]

# omitted

aws_route_table.routetable_main: Creating...
aws_route_table.routetable_main: Still creating... [10s elapsed]
aws_route_table.routetable_main: Still creating... [20s elapsed]
aws_route_table.routetable_main: Still creating... [30s elapsed]
aws_route_table.routetable_main: Still creating... [40s elapsed]
aws_route_table.routetable_main: Still creating... [50s elapsed]
aws_route_table.routetable_main: Still creating... [1m0s elapsed]
aws_route_table.routetable_main: Still creating... [1m10s elapsed]
aws_route_table.routetable_main: Still creating... [1m20s elapsed]
aws_route_table.routetable_main: Still creating... [1m30s elapsed]
aws_route_table.routetable_main: Still creating... [1m40s elapsed]
aws_route_table.routetable_main: Still creating... [1m50s elapsed]
aws_route_table.routetable_main: Still creating... [2m0s elapsed]

Error: error waiting for Route Table (rtb-5678) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)

  on tf/main.tf line 52, in resource "aws_route_table" "routetable_main":
  52: resource "aws_route_table" "routetable_main" {
```

In the second terraform apply run, you can notice that `rtb-1234` is most probably removed from the state.

The corresponding code on terraform-provider-aws side that remove the route table from the state if it is not found:

https://github.com/hashicorp/terraform-provider-aws/blob/fce7062f70caa92a78bca629ffe441c088456418/aws/resource_aws_route_table.go#L225-L229

After some time we actually notice that both `rtb-1234` and `rtb-5678` are present in the AWS API. But they are no longer present in the terraform state because they were most probably removed on refresh.

### Steps to Reproduce

See above

### References

* #0000

**Comment by ewbankkit** [comment]
@ialidzhikov Thanks for raising this issue.

I _think_ that Terraform is working as-designed here:
The `CreateRouteTable` API succeeds and the route table ID (`rtb-1234`) is recorded in state, but due to [AWS EC2 API eventual consistency](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency), we cannot successfully read it back within 2 minutes:

https://github.com/hashicorp/terraform-provider-aws/blob/6b0c51b40ce781e5607c71d9bf46aa3aa929becf/internal/service/ec2/route_table.go#L181-L191

The Terraform resource creation operation has now failed but as an ID was recorded, that resource (`rtb-1234`) is now marked as _tainted_ in state and will be destroyed the next time a Terraform operation is performed on it.
Quickly running `terraform apply` (or similar) again (which I am assuming you did) results in Terraform refreshing state, which involves attempting to read the tainted Route Table  (`rtb-1234`) so that Terraform knows whether to run the resource destroy operation on it. Again the EC2 API is returning that the Route Table is not found, so Terraform thinks _OK, this resource was deleted manually so I don't need to delete it_ and will then create a new Route Table (`rtb-5678`).
So both `rtb-1234` and `rtb-45678` exist at AWS (and eventually we should be able to successfully query for `rtb-1234` via the EC2 API), but only `rtb-45678` is recorded in state.

It think the real issue here is that 2 minute timeout. The documentation says:

> Confirm the state of the resource before you run a command to modify it. Run the appropriate `Describe` command using an exponential backoff algorithm to ensure that you allow enough time for the previous command to propagate through the system. To do this, run the `Describe` command repeatedly, starting with a couple of seconds of wait time, and increasing gradually up to five minutes of wait time.

So, strictly speaking that 2 minutes should be 5 minutes.

**Comment by ialidzhikov** [comment]
Thank you for your analysis @ewbankkit ! Last week I created https://github.com/hashicorp/terraform-provider-aws/pull/21847 . Let me know if you have comments on it.

**Comment by ialidzhikov** [comment]
> Thank you for your analysis @ewbankkit ! Last week I created #21847 . Let me know if you have comments on it.

Thank you very much @ewbankkit and all terraform-provider-aws maintainers for having a look into the above PR (sarcasm). Looks like the aws_route create timeout was increased from 2m to 5m with https://github.com/hashicorp/terraform-provider-aws/pull/21531. Hope that this helps with this issue.
