### ISSUE TITLE
AWS route53 record CNAME defaults to A record type

### ISSUE THREAD

**Issue by alleynec** [hashicorp/terraform-provider-aws#21908]
This occurs in version 1.0.2 to 1.0.11

resource "aws_route53_record" "frontend_alias_route53_record" {
  provider = aws.dns
  zone_id  = var.HOSTED_ZONE_ID
  name     =  aws_s3_bucket.WebsiteBucket.id
  type       = "CNAME"
  ttl           = "300"
  records  = ["${aws_s3_bucket.WebsiteBucket.id}.s3-website-us-east-1.amazonaws.com"]
}

After executing a plan and/or apply, terraform tries to create an A record instead of a CNAME type.

**Comment by justinretzolk** [comment]
Hi @alleynec 👋 Thank you for taking the time to raise this issue. So that we have all of the necessary information in order to look into and prioritize this, can you provide the rest of the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
