### ISSUE TITLE
data.aws_security_groups.terraform Error: Your query returned no results.

### ISSUE THREAD

**Issue by alexgdmx** [hashicorp/terraform-provider-aws#21938]
Error: Your query returned no results. Please change your search criteria and try again.
│
│   with data.aws_security_groups.terraform,
│   on main.tf line 145, in data "aws_security_groups" "terraform":
│  145: data "aws_security_groups" "terraform" {

This should not be an error. When we work with an existing infrastructure sometimes are expected to receive empty objects.

**Comment by justinretzolk** [comment]
Hey @alexgdmx 👋 Thank you for taking the time to raise this issue! So that we have all of the information necessary to prioritize and look into this, can you update the issue description with the rest of the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
