### ISSUE TITLE
 aws_spot_fleet_request: Error: error updating spot request InvalidParameterCombinationException: No attributes specified after updating to 3.67.0.

### ISSUE THREAD

**Issue by sirocode** [hashicorp/terraform-provider-aws#21944]
Hi,

Tried to update Terraform provider AWS from 3.42.0 to 3.67.0 for my project where "aws_spot_fleet_request"s are used , got:

```
[12:16:18]	[Step 4/8] Error: error updating spot request (sfr-0bbe536b-8b0d-4a00-9d92-4af91eccfdd0): InvalidParameterCombinationException: No attributes specified.
[12:16:18]	[Step 4/8] 	status code: 400, request id: a25e079b-b2bb-4a87-84dd-788ea5ef9e3d
```

The reason is "wait_for_fulfillment" parameter which can NOT be changed in 3.67.0 for already created aws_spot_fleet_request.

Once I set "wait_for_fulfillment = true" and stopped changing it - the problem is gone.

**Comment by justinretzolk** [comment]
Hey @sirocode 👋 Thank you for taking the time to raise this issue. So that we have all of the necessary information in order to prioritize and investigate this, can you update the issue description with the rest of the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
