### ISSUE TITLE
Add Object Ownership ACLs disabled for S3 buckets

### ISSUE THREAD

**Issue by praddc** [hashicorp/terraform-provider-aws#22069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add ability to disable S3 bucket ACLs for a given bucket, as announced [here](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/).

(Since the `rule` block in `aws_s3_bucket_ownership_controls` is currently required, to ensure it stays backwards compatible, we can add the new setting to the `rule` block.

### New or Affected Resource(s)

* [`aws_s3_bucket_ownership_controls`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_ownership_controls)

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket_ownership_controls" "example" {
  bucket = aws_s3_bucket.example.id
  rule {
    acls_disabled = true
  }
}
```

### References

* [https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/)

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/22010.
Relates #21980.

**Comment by ehuizar1028** [comment]
FYI, i got the ACL to be disabled setting object_ownership to "BucketOwnerEnforced"
`  
rule {
    object_ownership = "BucketOwnerEnforced"
  }
`

**Comment by lachlancooper** [comment]
This is effectively implemented via the `object_ownership = "BucketOwnerEnforced"` rule, which is already supported and was added to the provider documentation in #22010.

According to the upstream documentation, using the "enforced" setting has the effect of disabling ACLs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html

**Comment by KyleKotowick** [comment]
Relates #22271.

**Comment by StevieBowman** [comment]
@lachlancooper This Issue is slightly different to the one in #22010.   #22010 relates to the PutBucketOwnershipControls API (https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketOwnershipControls.html).  A different approach is that BucketOwnerEnforced can also be set on the CreateBucket API using x-amz-object-ownership header (https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html).  Where this becomes an issue is if you try implement the AWS Service Control Policy

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "RequireBucketOwnerFullControl",
            "Action": "s3:CreateBucket",
            "Effect": "Deny",
            "Resource": "*",
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-object-ownership": "BucketOwnerEnforced"
                }
            }
        }
    ]
}

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ensure-object-ownership.html

Since the Deny is done on the CreateBucket API then the PutBucketOwnershipControls will fail since the API is after CreateBucket API.  At it stands, it is not possible to implement this AWS Service Control Policy if using Terraform.

**Comment by lachlancooper** [comment]
This issue was raised against the `aws_s3_bucket_ownership_controls` resource specifically. Since it's already supported, I think this can be closed.

However, [as noted](https://github.com/hashicorp/terraform-provider-aws/issues/22069#issuecomment-1002753497) by @StevieBowman, being able to create a bucket with a specific object ownership setting from the beginning is necessary if a user wants to [disable ACLs on all buckets as AWS recommend](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ensure-object-ownership.html). This would need to be implemented as an argument on the `aws_s3_bucket` resource, so perhaps it's best to create a separate issue for that enhancement.

**Comment by gerardokaztro** [comment]
I put my comment on another issue: https://github.com/hashicorp/terraform-provider-aws/issues/22271#issuecomment-1107538893

**Comment by justinretzolk** [comment]
Since this was resolved (see https://github.com/hashicorp/terraform-provider-aws/issues/22069#issuecomment-1022981218 above), I'll mark this issue as closed and continue the additional discussions as needed over on #22271. If you feel I've done this in error, please do let me know.
