### ISSUE TITLE
Please add support for S3 Glacier Instant Retrieval storage class

### ISSUE THREAD

**Issue by roman8422** [hashicorp/terraform-provider-aws#22098]
### Description

Announcement: https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-glacier-instant-retrieval-storage-class/

### New or Affected Resource(s)

`aws_s3_bucket` and `aws_s3_bucket_object`

**Comment by ewbankkit** [comment]
The `GLACIER_IR` value was added to the

* `s3.ObjectStorageClass_Values()`
* `s3.StorageClass_Values()`
* `s3.TransitionStorageClass_Values()`

enumeration with [AWS SDK v1.42.16](https://github.com/aws/aws-sdk-go/releases/tag/v1.42.16), merged via https://github.com/hashicorp/terraform-provider-aws/pull/21999.
This means that the

* `aws_s3_bucket_object.storage_class`
* `aws_s3_bucket_replication_configuration.rule.destination.storage_class`
* `aws_s3_object_copy.storage_class` <-- Should use `ObjectStorageClass_Values()`, not `StorageClass_Values()`
* `aws_s3_bucket.replication_configuration.rules.destination.storage_class`

support the `GLACIER_IR` value as of **v3.68.0**.

Missing the support are

* `aws_s3_bucket.lifecycle_rule.transition.storage_class`
* `aws_s3_bucket.lifecycle_rule.noncurrent_version_transition.storage_class`

What is required is:

* Replace [`validBucketLifecycleTransitionStorageClass()`](https://github.com/hashicorp/terraform-provider-aws/blob/e49a19bd7ee20442822b6a3509c5a02cc1bb66f1/internal/service/s3/validate.go#L23) with `validation.StringInSlice(s3.TransitionStorageClass_Values(), false)`, so as to future-proof for additional S3 storage classes in  `aws_s3_bucket.lifecycle_rule.transition.storage_class` and `aws_s3_bucket.lifecycle_rule.noncurrent_version_transition.storage_class`
* Modify [`aws_s3_object_copy.storage_class`](https://github.com/hashicorp/terraform-provider-aws/blob/e49a19bd7ee20442822b6a3509c5a02cc1bb66f1/internal/service/s3/object_copy.go#L270) to use `ObjectStorageClass_Values()`
* Update the relevant documentation to preferably point to AWS documentation that lists the valid S3 storage classes rather than explicitly list them

**Comment by bendrucker** [comment]
Here's the documentation of storage classes that can be used in lifecycle transitions:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_Transition.html#AmazonS3-Type-Transition-StorageClass

And all available storage classes that can be passed when calling `PutObject`:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#AmazonS3-PutObject-request-header-StorageClass

Note that they are not the same, as transitions cannot target `REDUCED_REDUNDANCY` or `OUTPOSTS`. Presumably `StorageClass_Values` is around for backward compatibility and implementations should always specify either object or transition classes, as noted above.

Happy to work on a PR that addresses those 3 requirements.

**Comment by bendrucker** [comment]
Opened https://github.com/hashicorp/terraform-provider-aws/pull/22139. Ran out of time to run the relevant acceptance tests, but happy to do that later today. Opened as a draft in case you want to take it over or don't need to see acceptance output given the narrowness/simplicity of the change.
