### ISSUE TITLE
CloudWatch Log Metric Filter failed: InvalidParameterException: The specified filter pattern does not support dimensions

### ISSUE THREAD

**Issue by sudhakardavuluri** [hashicorp/terraform-provider-aws#22105]
module.mysql_error_metric_filter.aws_cloudwatch_log_metric_filter.this[0]: Modifying... [id=mysql_error_filter]

Error: Creating/Updating CloudWatch Log Metric Filter failed: InvalidParameterException: The specified filter pattern does not support dimensions

  on /Users/sdavuluri/git-clones/db-terraform/.terraform/modules/mysql_error_metric_filter/main.tf line 1, in resource "aws_cloudwatch_log_metric_filter" "this":
   1: resource "aws_cloudwatch_log_metric_filter" "this" {

**Comment by sudhakardavuluri** [comment]
- Finding hashicorp/aws versions matching "3.50.0"...
- Terraform v0.14.11

**Comment by justinretzolk** [comment]
Hey @sudhakardavuluri 👋 Thank you for taking the time to file this issue. So that we have all of the necessary information in order to look into this, can you update the issue description with the rest of the data requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by justinretzolk** [comment]
Since we've not received a response on this one in a bit, we'll close this issue out in favor of #28881.
