### ISSUE TITLE
error deleting Image Builder Componen as other resources depended on it

### ISSUE THREAD

**Issue by tiendungitd** [hashicorp/terraform-provider-aws#22127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.0.0
AWS version =3.68

### Affected Resource(s)

* aws_imagebuilder_image_recipe
* aws_imagebuilder_component

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_imagebuilder_component" "component_ansible_cis_hardening" {
...
  version = "10.1"
..
}

locals {
  image_component_linux = {
    ansible_cis = aws_imagebuilder_component.component_ansible_cis_hardening[0].arn
  }
}
resource "aws_imagebuilder_image_recipe" "recipe_linux" {
...
  version      = "1.0.1"
  dynamic "component" {
    for_each = local.image_component_linux
    content {
      component_arn = component.value
    }
  }

```

### Debug Output
When I change something in component such as increase version, Terraform require replacement of component and update in place of recipe
Terraform plan:
```hcl
Terraform will perform the following actions:
  # module.image_builder.aws_imagebuilder_component.component_ansible_cis_hardening[0] must be replaced
+/- resource "aws_imagebuilder_component" "component_ansible_cis_hardening" {
...
      ~ version               = "1.0.1" -> "1.0.0" # forces replacement
        # (5 unchanged attributes hidden)
    }
  # module.image_builder.aws_imagebuilder_image_recipe.recipe_linux will be updated in-place
  ~ resource "aws_imagebuilder_image_recipe" "recipe_linux" {
..
          ~ component_arn = "arn:aws:imagebuilder:eu-central-xxxxx:component/component-ansible-cis-hardening-dryrun/1.0.1/1" -> (known after apply)
        }
        # (3 unchanged blocks hidden)
    }
Plan: 1 to add, 1 to change, 1 to destroy.
```
### Expected Behavior
Terraform can force replace component and recipe.

### Actual Behavior

Component cannot be deleted due to recipe.
```
Error: error deleting Image Builder Component (arn:aws:imagebuilder:eu-central-xxxxxx:component/component-ansible-cis-hardening-dryrun/1.0.1/1): ResourceDependencyException: Resource dependency error: The resource ARN 'arn:aws:imagebuilder:eu-central-1xxxx:component/component-ansible-cis-hardening-dryrun/1.0.1/1' has other resources depended on it.
```
To workaround, i have to change version Recipe whenever Component updated
### Steps to Reproduce

1. `terraform apply`

**Comment by chrisgilmerproj** [comment]
I am also having this problem. Let me see if I can add some nuance to the issue. Image Builder expects to always keep any resources (Recipes, Components) if an Image Builder Image (which represents an AMI) was built from those AWS Resources. This means that any modification to either a Recipe or Component requires a version change. I believe this is enforced on the AWS side and cannot be modified by Terraform and might be driven by auditability of the AMI. 

The way I work around this is to have a lifecycle policy:

```
  lifecycle {
    create_before_destroy = true
  }
```

From there I can either use `terraform refresh` or use `terraform state rm ... && terraform import ...` to get back to a normal state.

Perhaps a different approach to this problem is to allow users to put `skip_destroy=true` on these resources. Because AWS wants you to leave the resources alone in AWS and the user no longer wants to manage the old resources in terraform. It leaves an audit trail but decouples the new terraform resources from the old resources. Better yet, this is a pattern used by terraform in other AWS modules such as [aws_volume_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/volume_attachment#skip_destroy).

I'd love to see this solved for both `aws_imagebuilder_recipe` and `aws_imagebuilder_component` to match what AWS intends.

**Comment by willgleich** [comment]
Just gave this a +1 - wanted to add that this bug looks awfully similar to https://github.com/hashicorp/terraform-provider-aws/issues/19642
