### ISSUE TITLE
aws_networkfirewall_rule_group: Cannot reference rule_variables in rule_variables

### ISSUE THREAD

**Issue by AL1060005** [hashicorp/terraform-provider-aws#22268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Provider version: 3.70.0

### Description

The aws_networkfirewall_rule_group module allows to define a rule_variables block of ip sets for suricata rules.

**The suricata format allows to reference other variables, and to negate them**. This is both valid in the AWS console and CloudFormation, but unfortunately doesn't work here.

In this module, IP sets are expected to be in CIDR format only (i.e. A.B.C.D/X) only, with no way to reference other variables.

### Expected working example

```hcl
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    rule_variables {
      ip_sets {
        key = "WEBSERVERS_HOSTS"
        ip_set {
          definition = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
        }
      }
      ip_sets {
        key = "EXTERNAL_HOSTS"
        ip_set {
          definition = ["!WEBSERVERS_HOSTS"]
        }
      }
    }
  }
}
```

### Actual Behavior

Error:
```
╷
│ Error: "!WEBSERVERS_HOSTS" is not a valid CIDR block: invalid CIDR address: !WEBSERVERS_HOSTS
│
│ with module.basic_example.aws_networkfirewall_rule_group.example,
│ on ../../main.tf line 28, in resource "aws_networkfirewall_rule_group" "example":
│ 28: rule_variables {
```

**Comment by anGie44** [comment]
Hi @AL1060005 , thank you for raising this issue. From the [API specs](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_IPSet.html), `definition` seems to be defined as `The list of IP addresses and address ranges, in CIDR notation.` but oddly enough the pattern is specified as `^.*$` which i believe should allow for referencing other variables like `WEBSERVERS_HOST`. This can be addressed by adjusting the validation to the new regex pattern instead of just checking for valid CIDR addresses as seen here in the resource code:

https://github.com/hashicorp/terraform-provider-aws/blob/1915c4c45ba00b98154e115459cce976c09c3181/internal/service/networkfirewall/rule_group.go#L81-L93

So ```ValidateFunc: validation.StringMatch(regexp.MustCompile(`^.*$`), ""),``` may be the better solution.
