### ISSUE TITLE
 Error while installing hashicorp/aws v3.70.0: unsuccessful request to  403 Forbidden

### ISSUE THREAD

**Issue by headincl0ud** [hashicorp/terraform-provider-aws#22325]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

    aws = {
      source = "hashicorp/aws"
      version = "3.70.0"
    }

```
terraform --version
Terraform v1.1.2
on darwin_amd64
```

### Panic Output

```
╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/aws v3.70.0: unsuccessful request to
│ https://releases.hashicorp.com/terraform-provider-aws/3.70.0/terraform-provider-aws_3.70.0_darwin_amd64.zip:
│ 403 Forbidden

```
### Expected Behavior

Terraform providers should be downloaded successfully. 

### Actual Behavior

During the install the new version I'm receiving 403 error. 

### Steps to Reproduce

1. `terraform init -upgrade`

**Comment by wedge-jarrad** [comment]
Could be a proxy blocking your download. Does your organization use Zscaler? I ran into this because it cannot scan files larger than 200MB and will block the download because "Not allowed to upload/download unscannable file formats." Note that the file size is after decompressing the zip. Try opening https://releases.hashicorp.com/terraform-provider-aws/3.70.0/terraform-provider-aws_3.70.0_darwin_amd64.zip with your browser to see if it gives you an indication of what is blocking the DL.

Versions 3.64 and newer of the Windows provider started having this issue for me because they exceed the 200MB limit. I haven't verified the Mac file sizes but you can try an older version to see if it works.

**Comment by pglezen** [comment]
I can vouch for having issues on a machine using zScaler as mentioned by @wedge-jarrad .  However, my immediate issue seems to be with *content filtering*.  Thanks for posting the explicit link so that the content filtering was clearer to me.

**Comment by headincl0ud** [comment]
I can confirm that the zScaler was blocking the access.
