### ISSUE TITLE
Error creating S3 bucket: BucketAlreadyOwnedByYou

### ISSUE THREAD

**Issue by mcqj** [hashicorp/terraform-provider-aws#22482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
TF CLI - 1.1.3
AWS Provider - 3.70.0

### Affected Resource(s)

* aws_aws_s3_bucket

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_bucket" "terraform" {
  bucket = var.s3_bucket

  tags = {
    Name        = var.s3_bucket_name
    Environment = var.env
  }

  versioning {
    enabled = true
  }
}
```

### Expected Behavior

An S3 bucket should be created and terraform state should be updated to reflect that

### Actual Behavior

The terraform script runs for hours without completion e.g. 
```
module.tfstate.aws_s3_bucket.terraform: Still creating... [4h55m14s elapsed]
```
On hitting <ctrl>-c to exit, a graceful shutdown is initiated. At the end of the shutdown, the bucket has been created.
However, terraform has not reflected that in the state. So, re-running `terraform apply` results in the error:
```
Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
```

And, running `terraform destroy` says there are no resources to destroy.

### Steps to Reproduce

1. `terraform apply`

- However the fault is intermittent, sometimes the bucket creation  succeeds.
- A bucket of the same name did previously exist in another account but was successfully deleted before this creation attempt

**Comment by justinretzolk** [comment]
Hey @mcqj 👋 Thank you for taking the time to file this. I realize that given the intermittent nature of this, this may be difficult, however, would it be possible to update the issue description with the (redacted as necessary) debug logs so that we have all of the necessary information in order to investigate this?

**Comment by gdavison** [comment]
This is expected behaviour when the `terraform apply` is interrupted. Terraform does not update the state in that circumstance.

Since the S3 Bucket is actually created and Terraform state has not been updated, the bucket will either need to be deleted from AWS or use the [`terraform import` command](https://www.terraform.io/cli/import).
