### ISSUE TITLE
Changing instance_type for "aws_eks_node_group" forces replacement

### ISSUE THREAD

**Issue by hajdukd** [hashicorp/terraform-provider-aws#22499]
Terraform Version
```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.11.3
+ provider registry.terraform.io/hashicorp/aws v3.61.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/hashicorp/vault v3.0.1
```

Terraform Configuration Files

```
resource "aws_eks_node_group" "node_group" {
  count           = local.availability_zones
  cluster_name    = var.cluster_name
  node_group_name = random_pet.node_groups_pets[count.index].id
  node_role_arn   = local.node_iam_role_arn
  subnet_ids      = flatten([
    local.private_subnet_ids[count.index]])
  instance_types  = local.instance_types
...
}
```

Debug Output

N/A

Expected Behavior

Instance Types will be modified on the fly the same way I can do that when modifying ASG manually via console..

Actual Behavior

Instance Type changes force recreation of whole node_group.

Steps to Reproduce

terraform init
terraform plan

Additional Context

N/A

References

Didn't find any.

**Comment by justinretzolk** [comment]
Hi @hajdukd 👋 Thank you for taking the time to file this issue. I took a look, and it looks like this is currently a limitation of the API/SDK. More information below:

The provider uses [`CreateNodegroup`](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#CreateNodegroupInput) (note: here, and for the other things I'll be referencing, I'm actually linking to the `CreateNodegroupInput`, since the type definition is a bit more helpful than the function definition in this case) to create the node group. This allows for passing in the `instance_types` argument.

On the other hand, when updating the resource, there are two options, based on the data that you're modifying; [UpdateNodegroupVersion](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#UpdateNodegroupVersionInput) and [UpdateNodegroupConfig](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#UpdateNodegroupConfigInput). Neither of these "update" functions provide a method for modifying the `instance_types`, which is why Terraform must recreate the resource when this argument is modified. Looking at the API ([...Version](https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateNodegroupVersion.html) and [...Config](https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateNodegroupConfig.html), respectively), the same options are present; there's no way to modify the `instance_types`.

Unfortunately, this means that unless the API/SDK are changed, Terraform will have to continue to replace the resource(s) when the `instance_types` argument is changed. Since that's the case, we'll close this issue for now, but would be happy to take another look in the event that things change on the AWS side.
