### ISSUE TITLE
Unable to pass arguments with tfvars file

### ISSUE THREAD

**Issue by amamidwar** [hashicorp/terraform-provider-aws#22491]
I am trying to pass arguments in tfvars file. Below is the tfvars file - 

```
awsAccessKey = "xxx" 
awsSecretKey = "xxx" 
awsPrimaryRegion = "xxx" 
awsSecondaryRegion = "" 
emrBootstrap2args = [${var.s3BucketRegion},${var.emrS3LogUri}]
```

But I am getting below error :

```
╷
│ Error: Invalid character
│
│   on dqplus.tfvars line 33:
│   33: emrBootstrap2args = [${var.s3BucketRegion},${var.emrS3LogUri}]
│
│ This character is not used within the language.
╵
╷
│ Error: Invalid expression
│
│   on dqplus.tfvars line 33:
│   33: emrBootstrap2args = [${var.s3BucketRegion},${var.emrS3LogUri}]
│
│ Expected the start of an expression, but found an invalid expression token.
╵
╷
│ Error: Invalid character
│
│   on dqplus.tfvars line 33:
│   33: emrBootstrap2args = [${var.s3BucketRegion},${var.emrS3LogUri}]
│
│ This character is not used within the language.
╵
Error occured, exiting with return code 1
```

I tried to use it with different way, but I am getting error for `emrBootstrap2args = [${var.s3BucketRegion},${var.emrS3LogUri}]` . 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

**Comment by guruprasad-afk** [comment]
The tfvars file does not support interpolated strings with variables. Refer [this issue](https://github.com/hashicorp/terraform/issues/17229) for a potential solution.

**Comment by justinretzolk** [comment]
Hey @amamidwar 👋 As the other commenter mentioned, the errors you are receiving are due to your attempt to interpolate strings within the `.tfvars` file, which is not supported. As the linked issue discusses, [Terraform local values](https://www.terraform.io/language/values/locals) are more likely the solution you're looking for.

Since this is a configuration issue, rather than a bug with the provider, we'll close this issue for now. If you feel we've done this in error, please do let us know.

**Comment by amamidwar** [comment]
@guruprasad-afk @justinretzolk Thank you ... Issue has resolved
