### ISSUE TITLE
Apprunner connection with git

### ISSUE THREAD

**Issue by Ram2322** [hashicorp/terraform-provider-aws#22496]
Hi Terraform team,
We are able to provision aws app runner using terraform, but getting pending handshake in git connection.
As per following note
NOTE:
After creation, you must complete the authentication handshake using the App Runner console.
When we tried to completed handshake it is trying to connect git again.
Please assist me.

**Comment by justinretzolk** [comment]
Hi @Ram2322 👋 Thank you for taking the time to file this issue. So that we have the necessary information in order to look into this, can you provide all of the information requested in the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by michael-stevens** [comment]
Hi, I'm also seeing this issue, here's my go at the template:

### Terraform CLI Version & provider version:

```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.5.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected resources:

`aws_apprunner_connection`

### Terraform config file:

```
resource "aws_apprunner_connection" "github" {
  connection_name = "github"
  provider_type   = "GITHUB"

}
```

### Terraform debug output:

this is super long and probably contains private data?

### Panic output:

n/a

### Expected behaviour:

Connection created, able to complete it in aws console

### Actual behaviour:

Unable to create in aws console, insists on creating new connection

### Steps to reproduce:

`terraform apply
`

Attempt to complete connection in console

### Important factoids:

Seeing as this fails in the console step is it actually a terraform issue?

**Comment by bryantbiggs** [comment]
duplicate of #19825 - I am not seeing this same behavior - I have been able to create several GitHub connections without issue
