### ISSUE TITLE
aws_ecr_lifecycle_policy doesn't maintain order/state well

### ISSUE THREAD

**Issue by jsharpe-ctm** [hashicorp/terraform-provider-aws#22639]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform -v
Terraform v1.1.3
on linux_arm64

### Affected Resource(s)

* aws_ecr_lifecycle_policy

### Terraform Configuration Files

```hcl
variable "expiration_prefixes" {
  default = [
    "phonetrac_app",
    "phonetrac_base",
    "rpm_builder",
    "core"
  ]
}
 
 resource "aws_ecr_lifecycle_policy" "default" {
  for_each = toset(var.expiration_prefixes)
  repository = "${var.env}-${var.repository_name}"

  policy = <<EOF
{
    "rules": [
        {
            "rulePriority": 1,
            "description": "Keep last 2 images",
            "selection": {
                "tagStatus": "tagged",
                "tagPrefixList": ["${each.key}"],
                "countType": "imageCountMoreThan",
                "countNumber": 2
            },
            "action": {
                "type": "expire"
            }
        }
    ]
}
EOF
}
```

### Debug Output

https://gist.github.com/josh-m-sharpe/6974e7a6ee23a5723b488dc46f6c056a

### Panic Output
na

### Expected Behavior

terraform shouldn't recreate the resource.

It seems that AWS is returning the objects in the wrong order, or maybe terraform is interpreting the order wrong?

I *always* see terraform trying to create/replace them in the correct order.  e.g. , in my example `phonetrac_app` is always resource `0` and `core` is resource `3`.   So it seems that when terraform requests the objects, it gets them back in the wrong order and then decides it needs to replace/update them.

I have also tried using:
`length(var.expiration_prefixes)` and ` ["${var.expiration_prefixes[count.index]}"]` but the behavior is the same.

### Steps to Reproduce

run terraform apply more than once

1. `terraform apply`

### Important Factoids

nope

**Comment by josh-m-sharpe** [comment]
Just noticed that the above codez don't create 4 policies.  It creates one.  So each iteration over count is clobbering the last policy.  Seems like there isn't a differentiator on the `aws_ecr_lifecycle_policy` object other than the policy itself.

AWS's UI allows me to create more than one policy though!

**Comment by josh-m-sharpe** [comment]
Beginning to think this has nothing to do with count/each and more to do with the resource doesn't allow creating more than one policy:

I update my resources to be two explicit stanzas instead of using count/each like in the original description:
```
resource "aws_ecr_lifecycle_policy" "core" {
  repository = aws_ecr_repository.default.name

  policy = jsonencode({
    "rules": [
      {
        "rulePriority": 1,
        "description": "Keep last 2 images",
        "selection": {
          "tagStatus": "tagged",
          "tagPrefixList": ["core"],
          "countType": "imageCountMoreThan",
          "countNumber": 2
        },
        "action": {
          "type": "expire"
        }
      }
    ]
  })
}


resource "aws_ecr_lifecycle_policy" "phonetrac_base" {
  repository = aws_ecr_repository.default.name

  policy = jsonencode({
    "rules": [
      {
        "rulePriority": 2,
        "description": "Keep last 2 images",
        "selection": {
          "tagStatus": "tagged",
          "tagPrefixList": ["phonetrac_base"],
          "countType": "imageCountMoreThan",
          "countNumber": 2
        },
        "action": {
          "type": "expire"
        }
      }
    ]
  })
}
```

and the resulting policies that were created:

![Amazon_ECR](https://user-images.githubusercontent.com/39473/149985598-f9c5f506-6888-48b2-b281-3e9369579fc8.jpg)

Seems like there should definitely be two policies.  No wonder subsequent applies have to recreate things.

**Comment by josh-m-sharpe** [comment]
this seems related: https://github.com/hashicorp/terraform-provider-aws/issues/22641

**Comment by justinretzolk** [comment]
Hey @josh-m-sharpe / @jsharpe-ctm 👋 Thanks for taking the time to raise this. I took a look over the [`aws_ecr_lifecycle_policy` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_lifecycle_policy) and noticed the following callout:

> The AWS ECR API seems to reorder rules based on `rulePriority`. If you define multiple rules that are not sorted in ascending `rulePriority` order in the Terraform code, the resource will be flagged for recreation every `terraform plan`.

Based on that, it seems like this is expected behavior based on how the API works. With that in mind, I think you could get around this by updating your Terraform config to use a `map` rather than a `set` for the `for_each` as I've detailed below. It's perhaps a bit kludgy, but I suspect it may resolve the issue.

**NOTE:** I _did_ run a `terraform plan` with this configuration (with the necessary variables added), but don't have the necessary infrastructure set up to run an actual `apply`. That said, the `plan` output looked as I would expect.

```hcl
variable "expiration_prefixes" {
  default = {
    0 = "phonetrac_app",
    1 = "phonetrac_base",
    2 = "rpm_builder",
    3 = "core"
  }
}
 
 resource "aws_ecr_lifecycle_policy" "default" {
  for_each = var.expiration_prefixes
  repository = "${var.env}-${var.repository_name}"

  policy = <<EOF
{
    "rules": [
        {
            "rulePriority": ${each.key},
            "description": "Keep last 2 images",
            "selection": {
                "tagStatus": "tagged",
                "tagPrefixList": ["${each.value}"],
                "countType": "imageCountMoreThan",
                "countNumber": 2
            },
            "action": {
                "type": "expire"
            }
        }
    ]
}
EOF
}
```

**Comment by josh-m-sharpe** [comment]
@justinretzolk hey! 👋  thanks for the reply!

I believe this ticket is related: https://github.com/hashicorp/terraform-provider-aws/issues/22641

I tried your suggestion and posted there - but I believe something else is going on.

**Comment by kamilturek** [comment]
Hey @josh-m-sharpe, thanks for the reply!

I believe the problem is that `expiration_prefixes` defines elements for lifecycle policy **rules** while the resource we use is `aws_ecr_lifecycle_policy` (a policy, not policy rule!).

Using `for_each` in `aws_ecr_lifecycle_policy` would mean that we want to create 4 different policies. And that's wrong. The goal is to have one policy with 4 rules (but unfortunately a service like `aws_ecr_lifecycle_policy_rule` does not exist 😄 ).

Please correct me if I'm wrong in my understanding.

Instead, we can loop over the expiration prefixes while creating the JSON policy. Please see my configuration:
```terraform
variable "expiration_prefixes" {
  default = {
    1 = "phonetrac_app",
    2 = "phonetrac_base",
    3 = "rpm_builder",
    4 = "core"
  }
}

resource "aws_ecr_lifecycle_policy" "default" {
  repository = "myrepo"

  policy = jsonencode({
    "rules" = [for key, value in var.expiration_prefixes :
      {
        "rulePriority" = tonumber(key)
        "description"  = "Keep last 2 images"
        "selection" = {
          "tagStatus"     = "tagged"
          "tagPrefixList" = [value]
          "countType"     = "imageCountMoreThan"
          "countNumber"   = 2
        }
        "action" = {
          "type" = "expire"
        }
      }
    ]
  })
}
```

The config above creates a single lifecycle policy with four different rules.
![image](https://user-images.githubusercontent.com/22010517/150864974-7f1cc95b-d516-4253-959a-ed96c28804c9.png)

No other changes are detected after applying it.

Please try out this approach.

**Comment by josh-m-sharpe** [comment]
Aha!  Looks like that did it - thank you!
