### ISSUE TITLE
aws_cloudwatch_metric_alarm should validate the spelling of dimensions in namespaces before provisioning

### ISSUE THREAD

**Issue by rankol** [hashicorp/terraform-provider-aws#22726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In [aws_cloudwatch_metric_alarm](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm) there should be a mechanism in place to validate the spelling of the dimension for a defined namespace is correct. The resource will still provision without a correctly spelled namespace. This results in the CloudWatch alarm staying in a state of `Insufficient Data`.

I came across this issue when using `InstanceID` instead of `InstanceId`.

When looking at the resource through the console the `InstanceId` field does get populated correctly but metric data is not associated properly with the alarm.

### New or Affected Resource(s)

* aws_cloudwatch_metric_alarm

**Comment by sjonpaulbrown** [comment]
Due to the fact that the dimensions can vary, I do not think it is a reasonable ask to validate the spelling of the available dimensions. Even if it were worthwhile to validate all of the possible AWS dimensions, this would require additional support for custom metrics or third-party services that log to CloudWatch. It is also not reasonable to validate the existence of the metric as alarms can be created even if the metric data does not exist.

Overall, I think this enhancement would increase the complexity of a resource that has been implemented to match the functionality of the AWS API.

**Comment by gdavison** [comment]
Hi @rankol. The AWS API doesn't provide any way to pre-validate the dimensions or other fields. Implementing custom validation could cause future problems if AWS makes changes. The points that @sjonpaulbrown makes above are also correct.
