### ISSUE TITLE
Data Source: aws_ssm_patch_baseline exposing ARN

### ISSUE THREAD

**Issue by jeroen-nijssen** [hashicorp/terraform-provider-aws#22751]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* Data Source: aws_ssm_patch_baseline

### Terraform Configuration Files

```hcl
data "aws_ssm_patch_baseline" "rh_aws_baseline" {
  owner            = "AWS"
  name_prefix      = "AWS-"
  operating_system = "REDHAT_ENTERPRISE_LINUX"
}

resource "null_resource" "set_as_default" {
  triggers = {
    Custom_Baseline_ID = "pb-002f9xxxxxx"
    AWS_Baseline_ID    = "${data.aws_ssm_patch_baseline.redhatenterprise_aws.id}"
  }

  provisioner "local-exec" {
    command = "aws ssm register-default-patch-baseline --baseline-id ${self.triggers.Custom_Baseline_ID}"
  }

  provisioner "local-exec" {
    when = destroy
    command = "aws ssm register-default-patch-baseline --baseline-id ${self.triggers.AWS_Baseline_ID}"
  }
}
```

### Expected Behavior

That as described within the documentation on [terraform's Site](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_patch_baseline) it would export the ID on the `.id` reference. the ARN is not mentioned but it would be good to export that on a `.arn` reference (New Feature?)

Concreet:
- Expecting: `pb-0f40e1898bd7e2ecx`
- Actual: `arn:aws:ssm:eu-central-1:41608960xxxx:patchbaseline/pb-0f40e1898bd7e2ecx`

### Actual Behavior

Currently the datasource exports the ARN of the Patching Baseline in the ID reference.

```HCL 
# null_resource.set_as_default
+ resource "null_resource" "set_as_default" {
      id       = "3993071616417118419" -> (known after apply)
      triggers = { # forces replacement
          "AWS_Baseline_ID"    = "arn:aws:ssm:eu-central-1:41608960xxxx:patchbaseline/pb-0f40e1898bd7e2ecx"
          "Custom_Baseline_ID" = "pb-002f9xxxxxx"
        }
    }
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_patch_baseline#attributes-reference

**Comment by justinretzolk** [comment]
Hey @jeroen-nijssen 👋 Thank you for taking the time to raise this! I took a look over the `aws_ssm_patch_baseline` data source to see if this was possible. Unfortunately, it looks like this isn't supported by the underlying API at this point.

Looking at the resource, it uses the [ssm.DescribePatchBaselines](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#SSM.DescribePatchBaselines) function of the AWS Go SDK. This function returns a [DescribePatchBaselinesOutput](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#DescribePatchBaselinesOutput) type, which includes an array of type [PatchBaselineIdentity](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#PatchBaselineIdentity), which does not return the ARN of the resource(s).

Since this is currently not supported by the underlying API at this point, we'll close this issue for now. If the API is updated in the future to allow this functionality, we'd be happy to take another look into this. If you feel we've come to this conclusion in error, please do let us know.
