### ISSUE TITLE
Replication for Amazon Elastic File System (EFS)

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#22770]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon EFS Replication provides you with an easy way to keep an up-to-date copy of your file system in a second AWS Region or within the same Region.

### New or Affected Resource(s)

* `aws_efs_replication_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_efs_replication_configuration" "example" {
  source_file_system_id = aws_efs_file_system.example.id

  ...
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/01/amazon-elastic-file-system-replication/).
[Blog post](https://aws.amazon.com/blogs/aws/new-replication-for-amazon-elastic-file-system-efs/).

Requires [AWS SDK v1.42.41](https://github.com/aws/aws-sdk-go/releases/tag/v1.42.41): https://github.com/hashicorp/terraform-provider-aws/pull/22766.

**Comment by edmundcraske-bjss** [comment]
I feel like this resource needs to work similarly to the `aws_rds_cluster` resource where you can optionally create it from another cluster or from a snapshot instead of from scratch, and then once it is created it is just another RDS cluster - similarly by creating an EFS replication configuration, you end up with an EFS file system, so should this not be some optional configuration that is part of an `aws_efs_file_system` resource, rather than a new resource?
