### ISSUE TITLE
Provider produced inconsistent final plan when crating lambda layer

### ISSUE THREAD

**Issue by Jakc78** [hashicorp/terraform-provider-aws#22794]
Hi,

Having the below error message when creating lambda layer :

                      When expanding the plan for aws_lambda_layer_version.nodejs_lambda_layer to
                        include new values learned so far during apply, provider
                       "registry.terraform.io/hashicorp/aws" produced an invalid new value for
                        .source_code_hash: was
                        cty.StringVal("N2VlOTQyYmM5ZWY4NTg5N2JhZjk0NWUyNzA5MjllMDQ="), but now
                        cty.StringVal("YmM2NzkxZDgyOTNjNzExZWMxYjRkOTBjMGQ1NDRlOTAtMjI=").
                        
                       This is a bug in the provider, which should be reported in the provider's own
                      issue tracker.
Terraform version : 1.0.0
hashicorp/archive v2.2.0
hashicorp/aws v3.73.0
hashicorp/template v2.2.0

I repaet the apply 10 time and having the same issue.

**Comment by justinretzolk** [comment]
Hey @Jakc78 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the rest of the information found in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
