### ISSUE TITLE
Add user_group_id to aws_elasticache_user

### ISSUE THREAD

**Issue by stevehipwell** [hashicorp/terraform-provider-aws#22870]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to be able to set the `user_group_id` when creating a `aws_elasticache_user` so I can create users in separate workspaces to the `aws_elasticache_user_group`.

I currently have to use a null resource and script a call to `aws elasticache modify-user-group --user-group-id "${USER_GROUP_ID}" --user-ids-to-add "${USER_ID}"`.

### New or Affected Resource(s)

* aws_elasticache_user

### Potential Terraform Configuration

```hcl
resource "aws_elasticache_user" "default" {
  engine = "REDIS"

  user_id       = "mycluster-test"
  user_name     = "test"
  access_string = ""
  passwords     = [var.password]

  user_group_id = "mycluster-group"
}
```

### References

n/a

**Comment by justinretzolk** [comment]
Hey @stevehipwell 👋 Thanks for taking the time to raise this. I see you mentioned you're using the [modify-user-group](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/modify-user-group.html) AWS CLI command via a `null_resource` + command. That command uses the same AWS API as the `aws_elasticache_user_group` resource ([relevant line from the resource definition](https://github.com/hashicorp/terraform-provider-aws/blob/a4bb224df5072f1d7a1624f8cfa8847d2ab67d7e/internal/service/elasticache/user_group.go#L166)). 

Perhaps I'm missing a key detail here, but is there something stopping you from using the `aws_elasticache_user_group` resource as follows (in addition to the `aws_elasticache_user` resource you referenced above, with the `user_group_id` removed)?

```hcl
resource "aws_elasticache_user_group" "mycluster-group" {
  engine        = "REDIS"
  user_group_id = "mycluster_group"
  user_ids      = [aws_elasticache_user.default.user_id]
}
```

**Comment by stevehipwell** [comment]
@justinretzolk it's in the description, I need to create the user in a separate workspace to the group.

**Comment by YakDriver** [comment]
Unfortunately, I do not think that adding `user_group_id` fits well with our general single responsibility design philosophy. When we violate this, we always tend to get in trouble.

However, a solution that would work as well and conforms to the philosophy is adding a new `aws_elasticache_user_group_association` resource. The biggest practical challenge with the resource is that it is changing users associated with the user group, which will lead to Terraform detecting changes. These can be ignored with `lifecycle` `ignore_changes`.

It would be convenient for the new resource to have a list of user IDs like `aws_elasticache_user_group`. But, this will not work well because it will want to exclusively manage the list, like `aws_elasticache_user_group`, and it becomes unworkable to accurately read and update the list when two non-exclusive resources are fighting to manage the list. A single user can be associated and deassociated without these problems - although still requiring `lifecycle` `ignore_changes`.

Let us know what you think and if this will work for your situation.

**Comment by stevehipwell** [comment]
@YakDriver thanks for your reply, the design and following merged PR. My request was based on the CLI commands but you've captured the IaC behaviour in a very similar way to how we were doing it will shell resources.
