### ISSUE TITLE
CloudWatch Log Group arn sometimes DOES need the trailing asterisk

### ISSUE THREAD

**Issue by scastria** [hashicorp/terraform-provider-aws#22957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is in regards to previously closed issue #13509.  I was trying to follow the directions listed [here](https://github.com/aws-samples/amazon-ecs-stopped-tasks-cwlogs) which requires the log group arn to be placed in a CloudWatch LogGroup resource policy document.  The intent of this is to get ECS task state change events to be logged to a CW log group which is useful for when a task unexpectedly exits, like for a OutOfMemory issue, and you need to find out the exit reason.

Anyway, I created my CW LogGroup resource policy like this:

    data "aws_iam_policy_document" "ECSTaskStateChangePolicy" {
      statement {
        actions = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        principals {
          identifiers = [
            "delivery.logs.amazonaws.com",
            "events.amazonaws.com"
          ]
          type = "Service"
        }
        resources = [
          aws_cloudwatch_log_group.ECSLogGroup.arn
        ]
      }
    }
    
and my CW event rule would receive a failed invocation.  I traced it down to this policy above and was forced to change the resource portion of the policy such that the CW log group arn contained the trailing ":*" like this:

    data "aws_iam_policy_document" "ECSTaskStateChangePolicy" {
      statement {
        actions = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        principals {
          identifiers = [
            "delivery.logs.amazonaws.com",
            "events.amazonaws.com"
          ]
          type = "Service"
        }
        resources = [
          "${aws_cloudwatch_log_group.ECSLogGroup.arn}:*"
        ]
      }
    }

Therefore, sometimes the ":*" is needed.  Maybe it shouldn't have been removed? 

OR

maybe a new property can be added to an aws_cloudwatch_log_group resource called "streams_arn" such that:

arn = what it is today
streams_arn = [arn]:*

### New or Affected Resource(s)

- aws_cloudwatch_log_group

**Comment by garysassano** [comment]
I've just sumpled upon the same exact issue after convert [this](https://github.com/aws-samples/amazon-ecs-stopped-tasks-cwlogs/blob/master/ecs-stopped-tasks-cwlogs.yaml) CloudFormation template to Terraform:

```hcl
resource "aws_cloudwatch_log_group" "log_group" {
  name              = "/aws/events/ECSStoppedTasksEvent"
  retention_in_days = 7
}

resource "aws_cloudwatch_event_rule" "ecs_stopped_tasks_event" {
  name        = "ECSStoppedTasksEvent"
  description = "Triggered when an ECS Task stops because of an error"

  event_pattern = jsonencode({
    "source" : ["aws.ecs"],
    "detail-type" : ["ECS Task State Change"],
    "detail" : {
      "desiredStatus" : ["STOPPED"],
      "lastStatus" : ["STOPPED"],
    }
  })
}

resource "aws_cloudwatch_event_target" "event_target" {
  target_id = "ECSStoppedTasks"
  rule      = aws_cloudwatch_event_rule.ecs_stopped_tasks_event.name
  arn       = aws_cloudwatch_log_group.log_group.arn
}

resource "aws_cloudwatch_log_resource_policy" "log_events_policy" {
  policy_name = "LogEventsPolicy"
  policy_document = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "LogEventsPolicy"
        Effect = "Allow"
        Principal = {
          Service = [
            "delivery.logs.amazonaws.com",
            "events.amazonaws.com"
          ]
        }
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = aws_cloudwatch_log_group.log_group.arn
      }
    ]
  })
}
```

Despite looking correct, it failed due to Terraform not appending `:*` to the CloudWatch Log Group ARN, leading to improper resource references. To resolve this, I updated the ARN reference in the Terraform code to include `:*` at the end, which corrected the issue.

```hcl
Resource = "${aws_cloudwatch_log_group.log_group.arn}:*"
```

It's important to notice that AWS Console includes the :* suffix in CloudWatch Log Group ARNs. Terraform's deviation from including this suffix in references contrasts with CloudFormation's accurate adherence, highlighting a discrepancy in resource referencing between these tools.

**Comment by garysassano** [comment]
I've just sumpled upon the same exact issue after convert [this](https://github.com/aws-samples/amazon-ecs-stopped-tasks-cwlogs/blob/master/ecs-stopped-tasks-cwlogs.yaml) CloudFormation template to Terraform:

```hcl
resource "aws_cloudwatch_log_group" "log_group" {
  name              = "/aws/events/ECSStoppedTasksEvent"
  retention_in_days = 7
}

resource "aws_cloudwatch_event_rule" "ecs_stopped_tasks_event" {
  name        = "ECSStoppedTasksEvent"
  description = "Triggered when an ECS Task stops because of an error"

  event_pattern = jsonencode({
    "source" : ["aws.ecs"],
    "detail-type" : ["ECS Task State Change"],
    "detail" : {
      "desiredStatus" : ["STOPPED"],
      "lastStatus" : ["STOPPED"],
    }
  })
}

resource "aws_cloudwatch_event_target" "event_target" {
  target_id = "ECSStoppedTasks"
  rule      = aws_cloudwatch_event_rule.ecs_stopped_tasks_event.name
  arn       = aws_cloudwatch_log_group.log_group.arn
}

resource "aws_cloudwatch_log_resource_policy" "log_events_policy" {
  policy_name = "LogEventsPolicy"
  policy_document = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "LogEventsPolicy"
        Effect = "Allow"
        Principal = {
          Service = [
            "delivery.logs.amazonaws.com",
            "events.amazonaws.com"
          ]
        }
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = aws_cloudwatch_log_group.log_group.arn
      }
    ]
  })
}
```

Despite looking correct, it failed due to Terraform not appending `:*` to the CloudWatch Log Group ARN, leading to improper resource references. To resolve this, I updated the ARN reference in the Terraform code to include `:*` at the end, which corrected the issue.

```hcl
Resource = "${aws_cloudwatch_log_group.log_group.arn}:*"
```

It's important to notice that AWS Console includes the `:*` suffix in CloudWatch Log Group ARNs. Terraform's deviation from including this suffix in references contrasts with CloudFormation's accurate adherence, highlighting a discrepancy in resource referencing between these tools.

**Comment by garysassano** [comment]
I've just sumpled upon the same exact issue after converting [this](https://github.com/aws-samples/amazon-ecs-stopped-tasks-cwlogs/blob/master/ecs-stopped-tasks-cwlogs.yaml) CloudFormation template to Terraform:

```hcl
resource "aws_cloudwatch_log_group" "log_group" {
  name              = "/aws/events/ECSStoppedTasksEvent"
  retention_in_days = 7
}

resource "aws_cloudwatch_event_rule" "ecs_stopped_tasks_event" {
  name        = "ECSStoppedTasksEvent"
  description = "Triggered when an ECS Task stops because of an error"

  event_pattern = jsonencode({
    "source" : ["aws.ecs"],
    "detail-type" : ["ECS Task State Change"],
    "detail" : {
      "desiredStatus" : ["STOPPED"],
      "lastStatus" : ["STOPPED"],
    }
  })
}

resource "aws_cloudwatch_event_target" "event_target" {
  target_id = "ECSStoppedTasks"
  rule      = aws_cloudwatch_event_rule.ecs_stopped_tasks_event.name
  arn       = aws_cloudwatch_log_group.log_group.arn
}

resource "aws_cloudwatch_log_resource_policy" "log_events_policy" {
  policy_name = "LogEventsPolicy"
  policy_document = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "LogEventsPolicy"
        Effect = "Allow"
        Principal = {
          Service = [
            "delivery.logs.amazonaws.com",
            "events.amazonaws.com"
          ]
        }
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = aws_cloudwatch_log_group.log_group.arn
      }
    ]
  })
}
```

Despite looking correct, it failed due to Terraform not appending `:*` to the CloudWatch Log Group ARN, leading to improper resource references. To resolve this, I updated the ARN reference in the Terraform code to include `:*` at the end, which corrected the issue.

```hcl
Resource = "${aws_cloudwatch_log_group.log_group.arn}:*"
```

It's important to notice that AWS Console includes the `:*` suffix in CloudWatch Log Group ARNs. Terraform's deviation from including this suffix in references contrasts with CloudFormation's accurate adherence, highlighting a discrepancy in resource referencing between these tools.
