### ISSUE TITLE
Key name of aws_key_pair is terraform-yyyyMMddhhmmssSSSS######## if key_name is an expression

### ISSUE THREAD

**Issue by fransf-wtax** [hashicorp/terraform-provider-aws#22992]
I have a module in directory `aws_key_pair`

```hcl
variable "environment" { 
  description = "Environment name. eg uat/prod" 
}

variable "label" { 
  description = "Instance Label / Name. eg analytics" 
}

locals {
  full_deployment_name = "${var.environment}-${var.label}"
}

resource "aws_key_pair" "ssh_public_key" {
  key_name   = try(var.key_name, "${local.full_deployment_name}-key")
  public_key = var.ssh_public_key
  tags = {
    Environment   = var.environment
    ManagedBy     = "terraform"
  }
}
```

The module is called as follows:
```hcl
variable "environment" {
  default = "nonprod"
}

module "db_ec2" {
  source      = "../../modules/aws_key_pair"
  environment = var.environment
  label = "db"
}
```

Expected is that the key pair is called `nonprod-db-key`. Instead it's called `terraform-20220207134918084800000001`.
This used to work until recently, probably when I upgraded to Terraform v1.0.2 (now on v1.1.5).

When I supply a literal key name it works fine, but when I supply an expression it somehow falls back to this weird behaviour of generating a unique key name based on the prefix `terraform-`, the current timestamp, and a sequence number.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.0
```

### Affected Resource(s)

* `aws_key_pair`

### Terraform Configuration Files

See [attached ZIP file](https://gist.github.com/fransf-wtax/7ec414fd10439aa853e3eb0f5295a70f/raw/1f77c4bdb7859bf2ec6e6578f162f8ae3ed96f4c/aws-key-pair-name-issue.zip) for a minimal project that reproduces this issue.

### Debug Output

[terraform.log](https://gist.github.com/fransf-wtax/7ec414fd10439aa853e3eb0f5295a70f/raw/1f77c4bdb7859bf2ec6e6578f162f8ae3ed96f4c/terraform.log)

### Panic Output

N/A

### Expected Behavior

AWS key pair is created with name `nonprod-db-key`. 

### Actual Behavior

AWS key pair is created with name `terraform-20220207134918084800000001` (includes date/time-stamp so changes depending on when the script is run).

### Steps to Reproduce

1. Configure AWS default credentials in `~/.aws/credentials`
1. Download and unzip [the attached ZIP file](https://gist.github.com/fransf-wtax/7ec414fd10439aa853e3eb0f5295a70f/raw/1f77c4bdb7859bf2ec6e6578f162f8ae3ed96f4c/terraform.log).
1. `cd env/sandbox`
1. `terraform init`
1. `terraform apply -auto-approve`

### Important Factoids

None.

**Comment by justinretzolk** [comment]
Hey @fransf-wtax 👋 Thank you for taking the time to raise this! I did a bit of digging and a simplified reproduction to try to get a better idea of what was happening here. It looks like this is coming down to how `try()` handles `null` values.

First, to touch on the naming that you're seeing. The key name is set [here](https://github.com/hashicorp/terraform-provider-aws/blob/e25e923e1438d4cf49cf54aa49e19c9f835cc8df/internal/service/ec2/key_pair.go#L90) and uses the [Name](https://github.com/hashicorp/terraform-provider-aws/blob/e25e923e1438d4cf49cf54aa49e19c9f835cc8df/internal/create/naming.go#L11-L14) helper function to determine what it should be set to. According to the comments for the `Name` function: 

> // Name returns in order the name if non-empty, a prefix generated name if non-empty, or fully generated name prefixed with terraform-

With that in mind, we can determine that when the function to determine `keyName` is called, `key_name` and `key_name_prefix` are both empty values (the latter of which is more clear due to not using the `key_name_prefix` argument, more on `key_name` below), so a generated name prefixed with `terraform-` is used, as you're seeing.

After tracking down what might cause the `terraform-` name to be used, I set up the aforementioned simplified reproduction based on the sample code you provided. That configuration is as follows:

```hcl
variable "key_name" {
	type = string
	default = null
}

variable "environment" {
	default = "nonprod"
}

variable "label" {
	default = "db"
}

locals {
	full_deployment_name = "${var.environment}-${var.label}"
}

output "key_name" {
	value = var.key_name
}

output "environment" {
	value = var.environment
}

output "label" {
	value = var.label
}

output "full_deployment_name" {
	value = local.full_deployment_name
}

output "end_result" {
	value = try(var.key_name, "${local.full_deployment_name}-key")
}
```

There are more outputs here than we really need, but I left them in for demonstration purposes. Upon running a `terraform apply`, the following is output: 

```shell
Outputs:

environment = "nonprod"
full_deployment_name = "nonprod-db"
label = "db"
```

Note that the `key_name` and `end_result` outputs are missing. This is due to the output holding a `null` value, so they are hidden. Since the `key_name` variable is a `null` value by default, that output being `null` makes sense, but the `end_result` output is the one we're more interested in for your use case.

From the [`try()` documentation](https://www.terraform.io/language/functions/try), I noted the following:

> `try` evaluates all of its argument expressions in turn and returns the result of the first one that does not produce any errors.

While `var.key_name` is `null`, it _doesn't_ produce any errors, so that is what is being returned, thus leading to the `end_result` value being set to `null`. I'm not certain if this behavior changed in recent Terraform versions; I wasn't able to locate any recent changes, but that codebase isn't where I spend most of my time, so I may have overlooked something. 

If the configuration is updated to use a [conditional expression](https://www.terraform.io/language/expressions/conditionals) instead, we can work around this issue:

```hcl
output "end_result" {
	value = var.key_name != null ? var.key_name : "${local.full_deployment_name}-key"
}
```

Output from apply: 

```shell
Outputs:

end_result = "nonprod-db-key"
environment = "nonprod"
full_deployment_name = "nonprod-db"
label = "db"
```

I hope this helps! If you have any follow up questions, please do let me know.

**Comment by fransf-wtax** [comment]
@justinretzolk Thanks so much for investigating this! I feel a bit silly now because it does look like this is a problem in my code - with `key_name` being defaulted to `null`.

Is the behaviour you described about the `key_pair` `name` defaulting to `resource.UniqueId()` described anywhere in the documentation? I don't see it on the `aws_ssh_key` doc page, but maybe there's a central page for common arguments. Otherwise it might be helpful to add; it might have pointed me in the right direction.

I would be happy to submit a PR to add this to https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/key_pair.html.markdown. Let me know if that's useful.

**Comment by justinretzolk** [comment]
Hey @fransf-wtax -- No reason to feel silly! I'm more than happy to look into things like this. It doesn't look like there's an explicit mention of how this naming behavior works. From reviewing the code, it goes in this order:

1. The name provided to `key_name`
2. The `key_name_prefix` followed by a generated name, when `key_name_prefix` is provided
3. If neither are provided, a fully generated name starting with `terraform-`

I think it would be totally worthwhile to add a note (perhaps below `key_name_prefix`?) that indicates that if neither `key_name` or `key_name_prefix` are passed, a fully generated name will be created. You mentioned you'd be happy to submit that documentation PR, but given that it's been a bit of time, I wanted to offer -- would you like to do so, or would you prefer that I do so? Either way, I'm more than happy to be involved insofar as that I'll do the PR review and merge 🙂.

**Comment by fransf-wtax** [comment]
Hey @justinretzolk ! I had a go at a PR: https://github.com/hashicorp/terraform-provider-aws/pull/23763 . Please review and make any changes as needed. Thanks!
