### ISSUE TITLE
Cognito error Callback_urls too character "1024"

### ISSUE THREAD

**Issue by Joelmono** [hashicorp/terraform-provider-aws#23020]
### Terraform CLI and Terraform AWS Provider Version
Terraform 0.12.7
providers {
aws = {
version = ">= 3.12.0"
}
}
### Affected Resource(s)

* aws_cognito_user_pool_client

### Debug Output

Error: "callback_urls.0" cannot be longer than 1024 character

  on userpool.tf line 91, in resource "aws_cognito_user_pool_client" "xxxx":
  91:   callback_urls                        = ["xxxx,xxx,xxx,xx...."]

I have more than 1024 character and i can't deploy because of this problem.
Is there a solution if i want to deploy my Cognito app client with more 1024 character in "callback_urls"?
Ps: "I make the action manually in the Console with 1024 and it's ok"

**Comment by justinretzolk** [comment]
Hey @Joelmono 👋 Thank you for taking the time to raise this! Unfortunately it looks like the 1024 character limit is imposed by the underlying [AWS API](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html):

> Length Constraints: Minimum length of 1. Maximum length of 1024.

Because this limitation is imposed at the API level, this isn't something that the provider will be able to navigate around unless the API itself is updated.
