### ISSUE TITLE
Documentation issue - aws_fsx_ontap_file_system

### ISSUE THREAD

**Issue by codescrawl** [hashicorp/terraform-provider-aws#23073]
There appears to be an issue with the documentation for the aws_fsx_ontap_file_system resource. The example usage block contains a line `throughput_capacity = 512` but `throughput_capacity` is not documented under the Argument Reference section. There are however two entries for `storage_type`, one a duplicate of the other. I wonder if there has been an error generating the documentation?

The link to the page is https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_file_system

**Comment by lvthillo** [comment]
This is true for [3.72.1](https://registry.terraform.io/providers/hashicorp/aws/3.74.1/docs/resources/fsx_ontap_file_system) but it's fixed in [4.0.0](https://registry.terraform.io/providers/hashicorp/aws/4.0.0/docs/resources/fsx_ontap_file_system) by [this PR](https://github.com/hashicorp/terraform-provider-aws/pull/22898/files).
