### ISSUE TITLE
error creating EC2 Network Interface: InvalidParameterValue: invalid value for parameter address:

### ISSUE THREAD

**Issue by roopeshpk** [hashicorp/terraform-provider-aws#23114]
HI I am Unable to attach private IP to ec2 instance 
aws_network_interface.hosted: Creating...
╷
│ Error: error creating EC2 Network Interface: InvalidParameterValue: invalid value for parameter address: XXXX
│ 	status code: 400, request id: b4669986-08e9-49e5-9c31-a5ee41ec7026
│ 
│   with aws_network_interface.hosted,

I have upgraded the terrafrom and provider 
# terraform -v
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
#

--
**Provider FIle** 
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.0.0"
    }
  }
}

provider "aws" {
  # Configuration options
  region  = "ap-southeast-2"
}

**Comment by justinretzolk** [comment]
Hey @roopeshpk 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the rest of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by roopeshpk** [comment]
hello @justinretzolk , the issue is  solved now,= the private IP which was assigned was incorrect  good to go  , we can close this issue , thanks a lot for the reply , was using the reserved Ips of the subnet
