### ISSUE TITLE
Create MSK connect custom plugins failed with InternalServerErrorException

### ISSUE THREAD

**Issue by umesh-kushwaha** [hashicorp/terraform-provider-aws#23122]
I am using the terraform MSK connect resource to create the custom plugins. Find the below msk-connect.tf file 

`msk-connect.tf`

```hcl
resource "aws_s3_bucket" "msk-connect-bucket" {
  bucket = "chegg-${var.environment}-msk-connect-zeebe-source"
}

resource "aws_s3_bucket_object" "connector-object" {
  bucket = aws_s3_bucket.msk-connect-bucket.id
  key    = "kafka-connector-zeebe-appl-all.jar"
}

resource "aws_mskconnect_custom_plugin" "zeebe-connector-plugin" {
  name         = "kafka-connector-zeebe-appl-${var.environment}"
  content_type = "JAR"
  location {
    s3 {
      bucket_arn = aws_s3_bucket.msk-connect-bucket.arn
      file_key   = aws_s3_bucket_object.connector-object.key
    }
  }
}

resource "aws_mskconnect_worker_configuration" "zeebe-source-connector-worker" {
  name                    = "zeebe-source-connector-worker-${var.environment}"
  properties_file_content = <<EOT
connector.class=com.chegg.kafka.connector.zeebe.ZeebeSourceConnector
job.variable.correlation.key=correlationKey
errors.log.include.messages=true
tasks.max=1
zeebe.client.requestTimeout=10000
zeebe.client.job.worker=kafka-connector
job.header.topics=kafka-topic
zeebe.client.job.pollinterval=2000
zeebe.client.worker.maxJobsActive=100
key.converter.schemas.enable=false
cloud.event.format.enable=false
zeebe.client.job.timeout=5000
value.converter.schemas.enable=false
zeebe.client.gateway.address=a7bb3c5a0d1b74de597235e73dd288c6-xxxxxxxxxxx.elb.us-west-2.amazonaws.com:26500
name=qc-kafka-source
errors.tolerance=all
value.converter=org.apache.kafka.connect.storage.StringConverter
errors.log.enable=true
key.converter=org.apache.kafka.connect.json.JsonConverter
job.types=sendMessage
zeebe.client.security.plaintext=true
EOT
}
```

When I applied the plan then it is throwing below error and stuck in creating mode vey long time.

`aws_mskconnect_custom_plugin.zeebe-connector-plugin: Still creating... [46m50s elapsed]
aws_mskconnect_custom_plugin.zeebe-connector-plugin: Still creating... [47m0s elapsed]
aws_mskconnect_custom_plugin.zeebe-connector-plugin: Still creating... [47m10s elapsed]
aws_mskconnect_custom_plugin.zeebe-connector-plugin: Still creating... [47m20s elapsed]
â·
â Error: error creating MSK Connect Custom Plugin (kafka-connector-zeebe-appl-dev): InternalServerErrorException: The request could not be processed because of an internal error. Try again.
â 
â   with aws_mskconnect_custom_plugin.zeebe-connector-plugin,
â   on msk-connect.tf line 15, in resource "aws_mskconnect_custom_plugin" "zeebe-connector-plugin":
â   15: resource "aws_mskconnect_custom_plugin" "zeebe-connector-plugin" {
â 
âµ
Operation failed: failed running terraform apply (exit 1)`

**Comment by justinretzolk** [comment]
Hey @umesh-kushwaha 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the rest of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by umesh-kushwaha** [comment]
Hey @justinretzolk 
Thanks for quick response, AWS support team helped to identify the root cause. There was an error in downloading the file from S3 bucket. This is resolved.

**Comment by 1968mnelson** [comment]
Can you please give details re: the issue downloading the file from s3? I think im having the same issue

**Comment by umesh-kushwaha** [comment]
@1968mnelson In my case, AWS support team helped to identify the root cause. JAR file was corrupted. I uploaded correct JAR file and it was working

**Comment by 1968mnelson** [comment]
Ahh ok interesting....I havent had issues creating the plugins...my issue is trying to create the actual connector in the console which points to the plugin and cluster. It spins in 'Creating' state for about 20-30 min, then transitions to a 'Failed' state with NO meaning ful error messages and no clues in CloudTrail. I suspect its an issue with the role policy for the connector that i am using but still trying to figure that out.

YOUR issue was creating the plugin correct? From what I can see....even to this day, Hashi hasnt given us a resource to create the actual connector. So im thining the only option to deploy MSK Connect via terraform would be to provision the **aws_mskconnect_custom_plugin** and the optional **aws_mskconnect_worker_configuration** using the hashi terraform resources but then would have to run a local-exec provisioner using boto3 to actually create the connector.

If im wrong, please help me out and point me in the right direction ! :-) 

Thanks!

**Comment by umesh-kushwaha** [comment]
@1968mnelson Yes, Create connector resource is not available yet. Currently, we can create worker configuration and custom plugins only. To create connector we need to use AWS CLI.
If you have premium support from AWS then support team can look into their backend system whats wrong going on. We  don't have much control on managed services.

**Comment by 1968mnelson** [comment]
Gotcha....Yes I have a support ticket open. FYI have you tried deleting the plugin via terraform? There is a bug. It says it deletes and also removes from state, but indeed never deletes the plugin. Subsequent applies fail because the resource already exists. I can create successfully using boto3/cli but the API makes it difficult to code any real logic around it because the describe and delete methods require an actual ARN...so no way to check if exists already and if it does, theres no way to fetch the ARN of it from the CLI or boto3

**Comment by umesh-kushwaha** [comment]
@1968mnelson Yes there was a bug in delete plugin resource. Day before yesterday, TF finally released, MSK connect create connector resource. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mskconnect_connector

I am not sure how much this is stable. You can give a try.
