### ISSUE TITLE
v4: Authentication not honoring AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#23131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Provider 4.0.0 does no longer respect the credentials set in the environment (`AWS_ACCESS_KEY_ID`,` AWS_SECRET_ACCESS_KEY`).

I run a number of project on GitLab CI/CD and have used the same approach for years, but today it broke.  I have the secrets stored on group account in environment variables.

When it does not find the credentials in the environment it looks for "profiles" in `~/.aws/credentials` etc. When that fails it tries the meta data service (which I do not have since I do not run on EC2 (I think GitLab runs on GCP)) and hence fails miserably.

My workaround was to put the creds in a file like:
`mkdir -p ~/.aws && echo -e "[profile-name]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials`

And finally carefully clean out these credentials `rm -rf ~/.aws/credentials`

Far from optimal but doing so it works, for me.

FWIW

(From @rexsuecia in this comment: https://github.com/hashicorp/terraform-provider-aws/issues/23110#issuecomment-1036354319)

### References

* #23110

**Comment by gdavison** [comment]
@rexsuecia, can you add the

```terraform
provider "aws" {
  ...
}
```

block here? And is there anything configured in the `~/.aws/config` file?

The reason I'm asking is that the order of resolution has changed to use the default for the AWS SDK for Go v2, but it will still read the environment variables if nothing overrides them.

For example, I'm testing with

```terraform
provider "aws" {
  region = "us-east-1"
}
```

and `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` set, and I am able to authenticate with AWS.

**Comment by rexsuecia** [comment]
@gdavison 
I have not checked but there is no reason there should exist any `~/.aws/config`

I did try exporting the `AWS_DEFAULT_REGION` but to no avail. 

My provider blocks generally looks as follows: 

```` 
provider "aws" {
  region  = var.region # Typically eu-west-1
  profile = "<name-of-profile-I-use-when-no-keys-in-env>"

  assume_role {
    role_arn = var.assume_role # The role on the remote account I want to assume to actually do terraforming
  }
}
```` 
Maybe the `assume_role` is what is different, or the fact that I am pointing to a profile (that I do not think should be regarded when there are credentials in the env??)

**Comment by swestcott** [comment]
This seems to match my experience when using Github Actions. I use static environment variables to provide the access key and secret. Since upgrading to v4, I get an authentication error.

```terraform
terraform {
  required_version = ">= 1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}
```

> Run terraform plan -out=plan
> ╷
> │ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
> │ 
> │ Please see https://registry.terraform.io/providers/hashicorp/aws
> │ for more information about providing credentials.
> │ 
> │ Error: no EC2 IMDS role found, operation error ec2imds: GetMetadata, failed to get API token, cannot get API token, operation error ec2imds: getToken, http response error StatusCode: 400, request to EC2 IMDS failed
> │ 
> │ 
> │   with provider["registry.terraform.io/hashicorp/aws"],
> │   on provder.tf line 1, in provider "aws":
> │    1: provider "aws" {
> │ 
> ╵
> Error: Process completed with exit code 1.

**Comment by gdavison** [comment]
@rexsuecia, is `profile` set to a non-empty value? If so, it will not check the environment variables, because it is explicitly being told to use the profile configuration. In order to use the environment variables, you will need to remove any non empty values from `profile`.

To optionally use a profile, you could use the `AWS_PROFILE` environment variable, or else use an input variable for the `profile`.

**Comment by gdavison** [comment]
@swestcott, could you share the provider block, please?

```terraform
provider "aws" {
  ...
}
```

**Comment by swestcott** [comment]
@gdavison I meant to include that in my initial message, but got the wrong block, oops!

```terraform
provider "aws" {
  region  = "eu-west-2"
  profile = "<name-of-profile-I-use-when-no-keys-in-env>"

  default_tags {
    tags = {
      "Managed-by" = "Terraform"
    }
  }
}
```

**Comment by gdavison** [comment]
@swestcott looks like the same problem that @rexsuecia was having with the `profile` overriding the environment variables.

**Comment by gdavison** [comment]
We will update the documentation to make it more clear that the order of resolution has been changed to use the default used by the AWS SDKs and CLI.

**Comment by arthurio** [comment]
Also, if you have `~/.aws/credentials` setup, it used to look for environment variables first, then the creds. Now it looks at the "default" profile in `~/.aws/credentials` first, and if no file is found, then it checks the environment variables. This is annoying because I can't have a default profile setup in`~/.aws/credentials` and override it with environment variables for different environments anymore... The only thing I could do was to delete `~/.aws/credentials` but it's less than ideal 😥 Any recommendation? Would it possible to choose the order for the resolution?

_Notes: I use aws-vault to run commands in different environments, hence the need to rely on environment variables being checked first..._

**Comment by rexsuecia** [comment]
@gdavison I understand my options. And yes the profile is set to a non-empty value. It has worked fenomenally well over the years (since terraform was `0.11.3` and aws provider was `<=2` ). And since it is a major version (`4.0.0`) I totally respect that you change the behavior. I originally posted to give others frantically googling the rather odd error message some clues.

The good thing about the old behavior was that I could let my devs set a profile for each different customer and the CI/CD would still use the configured envs. Very slim and hustle free. By populating the `~/.aws/credentials` I can keep the processes the same, though I am not a fan of writing secrets to disk. 

Setting `profile` to a varaiable that is left empty (e.g. `""`)

So great if you update the docs and I will adapt and adjust, looking forward to release 5 😃

**Comment by jgournet** [comment]
side-note to explain my use-case and my current workaround, in case it helps other people:
- we have terraform modules that we run from our laptops. Because of that, all the "provider "aws"" have a "profile" set (profiles are called "test" or "prod" ...etc)
- occasionally, some of those modules need to run from Jenkins server: from there, we can just use "withAWS" to assume a role. It used to work fine, as long as we create an empty profile "prod": terraform would get the env variables AWS_ACCESS_KEY_ID (etc...) and use those.

Of course, as seen in this ticket: aws provider 4.0 just broke all this...

I'm using this silly workaround for now:
```
                    withAWS(role: ASSUME_ROLE_ARN) {
                        // Create real aws profiles in ~/.aws/credentials from the ENV variables set by assuming ASSUME_ROLE_ARN
                        // This is mainly since the upgrade to TF aws provider 4.0: if a profile is set in "provider "aws"", it overrides any AWS_ACCESS_KEY variables
                        sh("""
                        mkdir -p ~/.aws/
                        cat <<EOF > ~/.aws/credentials
[default]
region = ${AWS_REGION}
aws_access_key_id = \$AWS_ACCESS_KEY_ID
aws_secret_access_key = \$AWS_SECRET_ACCESS_KEY
aws_session_token = \$AWS_SESSION_TOKEN

[prod]
region = ${AWS_REGION}
aws_access_key_id = \$AWS_ACCESS_KEY_ID
aws_secret_access_key = \$AWS_SECRET_ACCESS_KEY
aws_session_token = \$AWS_SESSION_TOKEN
                        """)
                    }
```

it works ... it's ugly and silly, but it works
