### ISSUE TITLE
aws_ecs_service does not support Operating system family for Fargate

### ISSUE THREAD

**Issue by irogers97** [hashicorp/terraform-provider-aws#23137]
Trying to add a ECS Service for launch type: Fargate and Operating system family: Windows Server 2019 Full.
I find no way to set the Operating system family and consequentyl get th efollowing errors:

Error: failed creating ECS service (_service name_): PlatformTaskDefinitionIncompatibilityException: One or more of the requested compatibilities are not supported.

**Comment by irogers97** [comment]
This may be a duplicate of #22033 which doesn't appear to be resolved

**Comment by justinretzolk** [comment]
Hey @irogers97 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to address this, can you update the issue description with the additional information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md)?
