### ISSUE TITLE
AWS Spot Instance Request Tags Won't Apply to Instance

### ISSUE THREAD

**Issue by twoheadedwolf** [hashicorp/terraform-provider-aws#23216]
**Terraform AWS Provider Version**

hashicorp/aws v4.0.0

I have an aws_spot_instance_request like this:

```hcl
resource "aws_spot_instance_request" "test" {
    ami = "${var.amitest}"
    key_name = "${var.key}"
    count = 5
    spot_price = "${var.price}"
    instance_type = "c5.18xlarge"
    subnet_id = "${var.subnet}"
    vpc_security_group_ids = [ "${var.securityGroup}" ]
    }

    tags {
      Name = "server100${count.index}"
    }
}
```

The tags are being applied only to the spot request itself, not to the underlying instance. How can I fix this?

Thanks!

**Comment by justinretzolk** [comment]
Hey @twoheadedwolf 👋 Thank you for taking the time to raise this! In the future, questions like this are generally better served by the [AWS Provider Discuss Forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) (and you may still consider posting over there based on what I was able to find).

I took a look around and it seems this is the expected behavior based on the AWS APIs. I found a rather old issue (https://github.com/hashicorp/terraform/issues/3263) that discusses this a bit more, and unfortunately it seems these APIs haven't changed in any meaningful way that would allow this. There are a few workaround suggestions in the linked issue that you may find helpful as well.
