### ISSUE TITLE
aws_kms_external_key: ARN is exported instead of ID

### ISSUE THREAD

**Issue by adamhorden** [hashicorp/terraform-provider-aws#23277]
`aws_kms_external_key` as per the documentation, this resource allows the key ID to be exported. During refactoring to the new S3 resources, we noticed that the ARN is exported instead of the ID. This has caused a few head scratching hours of debugging as at some point this was correct and the ID was exported.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_external_key

- [arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_external_key#arn) - The Amazon Resource Name (ARN) of the key.

- [id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_external_key#id) - The unique identifier for the key.

If we take an output of all key values of `aws_kms_external_key` we can see this behaviour. I have included the output of debugging below.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```shell
terraform -v
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.1.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/google v4.11.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.8
```

### Affected Resource(s)

* aws_kms_external_key

### Debug Output

```hcl
          "arn" = "arn:aws:kms:eu-west-2:REDACTED:key/REDACTED"
          "bypass_policy_lockout_safety_check" = false
          "deletion_window_in_days" = 10
          "description" = ": DEBUGGING"
          "enabled" = true
          "expiration_model" = "KEY_MATERIAL_DOES_NOT_EXPIRE"
          "id" = "arn:aws:kms:eu-west-2:REDACTED:key/REDACTED"
          "key_material_base64" = tostring(null)
          "key_state" = "Enabled"
          "key_usage" = "ENCRYPT_DECRYPT"
          "multi_region" = false
```

### Expected Behavior

The ID is returned and not ARN.

### Actual Behavior

The ARN is returned and not ID.

**Comment by justinretzolk** [comment]
Hey @adamhorden 👋 Thank you for taking the time to raise this! I'm marking this as a bug so that we can look into it. 

Looking at the provider, it seems the provider [is using the](https://github.com/hashicorp/terraform-provider-aws/blob/683516cac844fe13af5afbce2f4f8f11b1526263/internal/service/kms/external_key.go#L150) the correct value (`(*kms.CreateKeyOutput).KeyMetadata.KeyId`, [AWS Go SDK reference](https://docs.aws.amazon.com/sdk-for-go/api/service/kms/#KeyMetadata)), however, perhaps there's something I'm overlooking, or an upstream bug.

**Comment by Yoshiitaka** [comment]
I understood the cause. It seems that it has not been added to the schema.
Also, there were no assertions at the time of testing, which caused bugs.
However, since it is difficult to assert with the Id created automatically at the time of testing (may be solved by using the GetPublicKey method), only the existence check is performed.
