### ISSUE TITLE
ValidationError with Lambda fucntion

### ISSUE THREAD

**Issue by rajeshj-altus** [hashicorp/terraform-provider-aws#23360]
I have used terraform and getting  Error creating Lambda function: ValidationException:
        status code: 400, request id: 19aa91ff-2290-4e8a-bde6-6777c88ce0e5

When enabled trace 
 [ERROR] module.module_name_lambda: eval: *terraform.EvalApplyPost, err: Error creating Lambda function: ValidationException:
        status code: 400, request id: a698e1db-6e16-47f9-8504-233f4b0103e9
[ERROR] module.module_name_lambda: eval: *terraform.EvalSequence, err: Error creating Lambda function: ValidationException:
        status code: 400, request id: a698e1db-6e16-47f9-8504-233f4b0103e9

**Comment by justinretzolk** [comment]
Hey @rajeshj-altus 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to investigate, can you update the issue description with the rest of the information found in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
