### ISSUE TITLE
terraform plan - Issue with Secret Key having forward slashes

### ISSUE THREAD

**Issue by madhuridhone** [hashicorp/terraform-provider-aws#23370]
Hi All,
I am using Terraform 0.13 version .

I am getting an error of 
InvalidClientTokenId while executing Terraform script with plan command.

For me without slashes in aws secret key it got worked sometime before.

But now i have new credentials with slashes. With this,  terraform plan is not working and throwing the error.

May i know how terraform will read  credentials with slashes .

It will be great if some one provides the solution or some direction for this issue.

Thanks in advance.

**Comment by justinretzolk** [comment]
Hi @madhuridhone 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
