### ISSUE TITLE
aws_s3_bucket_ownership_controls returns BucketNotEmpty

### ISSUE THREAD

**Issue by alfredo-lopez-idealo** [hashicorp/terraform-provider-aws#23477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.6
avs provider 4.3.0

### Affected Resource(s)

* aws_s3_bucket_ownership_controls

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_bucket" "example" {
  bucket = "sample-bucket-1234-test"
}

resource "aws_s3_bucket_ownership_controls" "example" {
  depends_on = [aws_s3_bucket.example]
  bucket = aws_s3_bucket.example.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}
```

### Expected Behavior

The resources are destroyed without an error

### Actual Behavior

An error is received and the resources are not destroyed.

```sh
│ Error: error deleting S3 Bucket (soms): BucketNotEmpty: The bucket you tried to delete is not empty
│       status code: 409, request id: 8BF46D3AF1982E7E, host id: MzRISOwyjmnup8BF46D3AF1982E7E7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @alfredo-lopez-idealo 👋 Thank you for taking the time to raise this! I did a quick reproduction using the same configuration that you provided and was able to create/destroy the resources without issue. Based on the error, it looks like the issue is actually that there are objects in the S3 bucket you're trying to destroy, and the [`force_destroy` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#force_destroy) is not configured (so is defaulting to `false`). Note that when `force_destroy` is set to `true`, the bucket and all of its contents will be **irreversibly** destroyed when `terraform destroy` is called.

**Comment by alfredo-lopez-idealo** [comment]
@justinretzolk  I am not sure how I got this error. I tried it again and now I cannot reproduce anymore. This topic should be closed.
