### ISSUE TITLE
Import aws_db_parameter_group forces it to replace.

### ISSUE THREAD

**Issue by moleksyuk** [hashicorp/terraform-provider-aws#23505]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_db_parameter_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = "1.0.8"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.74.0"
    }
  }
}

provider "aws" {
  region = "eu-west-3"
}

resource "aws_db_parameter_group" "master" {
  name   = "mysql5-7-tf-bug"
  family = "mysql5.7"
}

```

### Expected Behavior

```
Plan: 0 to add, 0 to change, 0 to destroy. No changes.
```

### Actual Behavior

```hcl
  # aws_db_parameter_group.master must be replaced
-/+ resource "aws_db_parameter_group" "master" {
      ~ arn         = "arn:aws:rds:eu-west-3:794942263374:pg:mysql5-7-tf-bug" -> (known after apply)
      ~ description = "mysql5.7-tf-bug" -> "Managed by Terraform" # forces replacement
      ~ id          = "mysql5-7-tf-bug" -> (known after apply)
        name        = "mysql5-7-tf-bug"
      + name_prefix = (known after apply)
      - tags        = {} -> null
      ~ tags_all    = {} -> (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

### Steps to Reproduce

1. Create a new parameter group from AWS Console - `mysql5-7-tf-bug`.
2. Import it to terraform stage `terraform import aws_db_parameter_group.master mysql5-7-tf-bug`.
3. Run `terraform plan`.

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @moleksyuk 👋 It looks like Terraform is attempting to replace the resource due to an update to the `description` argument. The reasoning this is happening is because the resource currently has a description of `"mysql5.7-tf-bug"` in AWS. Since you're not setting the description explicitly in the Terraform configuration, it's [defaulting to `"Managed by Terraform"`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group#description). As noted in the linked document, updates to the `description` argument forces replacement of the resource.

If you were to explicitly set the `description` to `"mysql5.7-tf-bug"` in your configuration, you shouldn't see Terraform attempting to replace the resource anymore. Can you try that and verify that it clears up the issue?

**Comment by moleksyuk** [comment]
Hi @justinretzolk 
Thanks for so quick response. Yep, you are absolutely right. 
I've just added the description and got `No changes`. (I'm surprised because in many cases description is a field with `update in place` and don't causes such strange behaviour).

Closing this ticket 👍
