### ISSUE TITLE
Error: no schema available for "X" while reading state

### ISSUE THREAD

**Issue by pkhetrapal** [hashicorp/terraform-provider-aws#23576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.30.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_s3_*

### Debug Output

https://gist.github.com/pkhetrapal/1b58aec9a85a47a2b74131e548155938

### Expected Behavior

It should be possible to downgrade the provider from `v4.x` to `v3.x`

### Actual Behavior

I tried to apply/destroy but each time I got `Error: no schema available for "X" while reading state; this is a bug in terraform and should be reported` error. This started happening once I tried to downgrade the aws provider from `v4.3.0` to `v3.3.0`

### Steps to Reproduce

1. Downgrade from provider `v4.3.0` to `v3.3.0`
2. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @pkhetrapal 👋 Thank you for taking the time to raise this. Downgrading providers is something that isn't supported in Terraform overall; this isn't something that's specific to the AWS Provider. There doesn't currently exist a mechanism within Terraform Core to allow such downgrades, so our recommendation is always to back up the state file and ensure a successful `terraform plan` before moving forward with a `terraform apply` (which is when the provider upgrade is "locked in", so to speak). 

Since this isn't an issue specific to the AWS provider, I'm going to close this issue for now. If you feel I've done this in error, please do let me know.
