### ISSUE TITLE
Need aws_ebs_tag resource

### ISSUE THREAD

**Issue by jeremylafleur09** [hashicorp/terraform-provider-aws#23615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looking for the ability to have a resource  aws_ebs_tag just like how the AWS EC2 has a aws_ec2_tag. As apart of a naming convention we are looking for the ability to reference an ec2's availability zone as apart of a tag being applied to the ebs volume. Since the ec2 instance and ebs volume would be created together in a solution, tag value is known after apply but causes an issue with the default_tags in the environmment.

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @jeremylafleur09 👋 Thank you for taking the time to raise this. I'd be interested in seeing the configuration as you'd attempted to use it when filing this to get a better idea of what might be causing any errors. 

That said, I just did a bit of testing and verified that you _can_ use `aws_ec2_tag` resource(s) to tag `aws_ebs_volume` resources by passing the ID of the EBS volume to the `resource_id` argument of `aws_ec2_tag`. The caveat is that you'd need to add a [`lifecycle.ignore_changes` block](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes) to the `aws_ebs_volume` resource(s) to ignore changes to the `tags` and `tags_all` values for the resource. This will prevent Terraform from attempting to remove the tags on the next apply (since they're not defined in the `tags` block of the resource itself).
