### ISSUE TITLE
aws_ecs_service Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by fayas-akram** [hashicorp/terraform-provider-aws#23613]
### aws_ecs_service Provider produced inconsistent result after apply

Whenever I create ECS service Terraform return following error
`Error: Provider produced inconsistent result after apply
When applying changes to aws_ecs_service.ecs_service, provider
registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.`

### Terraform and Provider Version
`required_version = ">= 0.12"
version = ">= 2.65"
`

**Comment by justinretzolk** [comment]
Hey @fayas-akram 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to investigate this, can you update the issue description with the rest of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
