### ISSUE TITLE
Feature Request: FMS Centralized mode feature 

### ISSUE THREAD

**Issue by imoshik** [hashicorp/terraform-provider-aws#23626]
There is an update that allows to use of AWS Firewall Manager: AWS Network Firewall Centralized Deployment Model

https://aws.amazon.com/about-aws/whats-new/2022/02/aws-firewall-manager-centralized-deployment-model/

**Comment by justinretzolk** [comment]
Hey @imoshik 👋 Thank you for taking the time to raise this! So that we have all of the necessary information, can you update the issue description with the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md)?
