### ISSUE TITLE
aws_ssm_patch_baseline "global filter" issue with PATCH_ID + unclear docs

### ISSUE THREAD

**Issue by joemilacek** [hashicorp/terraform-provider-aws#23667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.74.3

### Affected Resource(s)

* aws_ssm_patch_baseline

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ssm_patch_baseline" "centos_7_9" {
  name                                 = "centos-7-9-baseline"
  operating_system                     = "CENTOS"
  approved_patches_enable_non_security = true
  #rejected_patches                     = ["docker-ce.x86_64"]
  rejected_patches_action = "BLOCK"

  global_filter {
    key    = "PATCH_ID"
    values = ["docker-ce.x86_64"]
  }

  approval_rule {
    approve_after_days  = 14
    compliance_level    = "HIGH"
    enable_non_security = true

    patch_filter {
      key    = "PRODUCT"
      values = ["CentOS7.9"]
    }

    patch_filter {
      key    = "CLASSIFICATION"
      values = ["*"]
    }

    patch_filter {
      key    = "SEVERITY"
      values = ["*"]
    }
  }
}
```

### Expected Behavior

Actually not sure. Global filter argument is described as:

> [global_filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_patch_baseline#global_filter) - (Optional) A set of global filters used to exclude patches from the baseline. Up to 4 global filters can be specified using Key/Value pairs. Valid Keys are PRODUCT | CLASSIFICATION | MSRC_SEVERITY | PATCH_ID

Couple of things:

1. What does this map to in, say, the AWS Console? When creating a patch baseline, there isn't anything called a global filter, or really anything that might be related to that. There are approval rules and, separately, a patch rejection section.
2. The description quoted above indicates that this _excludes_ patches, but where? There is another argument (commented out in my code above), called `rejected_patches` which seems redundant with this `global_filter` argument.
3. The real issue - "PATCH_ID" not being a valid key. Looking here: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DescribePatchProperties.html there is no "PATCH_ID" listed (perhaps I am looking in the wrong place).

### Actual Behavior

Error: error updating SSM Patch Baseline (pb-xxx): ValidationException: Unknown Filter Key: PATCH_ID
        status code: 400, request id: xxx

### Steps to Reproduce

Above.

###

**Comment by justinretzolk** [comment]
Hey @joemilacek 👋 Thank you for taking the time to raise this! It looks like perhaps there's room to improve this document, particularly around the "excludes" comment int he `global_filter` argument. Looking at the [related API call](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreatePatchBaseline.html) documentation, the global filters is defined as:

> A set of global filters used to include patches in the baseline.

Which is the _opposite_ of what the provider documentation currently says. As far as the `PATCH_ID` key, the same document linked above has a link under global filters to find the valid values. After following it, you'll land on the [PatchFilters](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchFilter.html) documentation, which lists `PATCH_ID` as a valid key. I'm not overly familiar with this are of AWS, but I suspect based on this that `PATCH_ID` would allow you to specify a specific patch, rather than needing to filter based on OS, severity, classification, etc.
