### ISSUE TITLE
does not have an attribute named "enable_glacier_transition" error using var.enable_glacier_transition in module

### ISSUE THREAD

**Issue by JRichlen** [hashicorp/terraform-provider-aws#23675]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
<img width="170" alt="Screen Shot 2022-03-14 at 6 18 21 PM" src="https://user-images.githubusercontent.com/9574264/158276243-9a37cc07-fb03-44c9-8af8-eab78b002b27.png">

Provider version `~> 4`

### Affected Resource(s)

This affects the use of a variable `var.enable_glacier_transition`.

### Terraform Configuration Files

Link to terraform module [cloudposse/alb/aws](https://github.com/cloudposse/terraform-aws-alb)
* Line where variable causes error - https://github.com/cloudposse/terraform-aws-alb/blob/master/main.tf#L47
* Line where variable is defined - https://github.com/cloudposse/terraform-aws-alb/blob/master/variables.tf#L259

##### Output with AWS provider ~> 4
<img width="792" alt="Screen Shot 2022-03-14 at 6 10 36 PM" src="https://user-images.githubusercontent.com/9574264/158275492-c01cead0-62f9-4de6-92b2-6769031e4351.png">

##### Output with AWS provider ~> 3
<img width="437" alt="Screen Shot 2022-03-14 at 6 11 14 PM" src="https://user-images.githubusercontent.com/9574264/158275575-f83e1c83-ecc8-4f55-afcd-937931a90bc6.png">

### Expected Behavior

`terraform validate` should succeed, and not error on variable defined by the module. Was working in provider version 3.

### Actual Behavior

Provider version 4 causes the `terraform validate` to fail.

### Steps to Reproduce

1. Create a module that implements `cloudposse/aws/alb`. 

2. Run `terraform validate` with provider `~> 4`

**Comment by justinretzolk** [comment]
Hey @JRichlen 👋 Thank you for taking the time to raise this! I did a bit of digging, and it looks like this is going to wind up being an issue with the module that you're using rather than an issue with the AWS Provider, so you'll need to open an issue within the repository of the module itself.

To give you a quick rundown of how I came to this conclusion:

- `cloudposse/terraform-aws-alb` [passes that variable](https://github.com/cloudposse/terraform-aws-alb/blob/5578d81fc8aa80cbf1295a4472195392ff0e89a0/main.tf#L41-L55) to a submodule, `cloudposse/lb-s3-bucket/aws` (pinned to version `0.14.1`).
- `cloudposse/lb-s3-bucket/aws` version `0.14.1` then [passes that variable](https://github.com/cloudposse/terraform-aws-lb-s3-bucket/blob/2ae430e3f0ff87e0e381912abd6ae1e9e7b2daf0/main.tf#L59-L77) to another submodule, `cloudposse/s3-log-storage/aws` (pinned to version `0.24.0`).
- `cloudposse/s3-log-storage/aws` added support for v4 of the AWS Provider in versions `0.27.0` and `0.28.0`.

Since this is an issue with the module(s), and not with the AWS Provider, I'm going to mark this issue as closed. If you feel I've done this in error, please do let me know.

**Comment by hjander** [comment]
For future reference, AWS Provider  v4 (in its early versions) is the problem: 
https://github.com/cloudposse/terraform-aws-s3-website/issues/71
