### ISSUE TITLE
Error refreshing state

### ISSUE THREAD

**Issue by sanjeevim** [hashicorp/terraform-provider-aws#23700]
Hello Team,

I am working on the terraform 0.1.5 version.

I am using Jenkins pipeline to create AWS infrastructure like kms,s3,iam,ec2 stage by stage.

When I tried to deploy a new EC2 with help of the remote state file which is stored in the backend S3. I am getting the below error on the EC2 deploy stage. I never experienced this kind of issue in the past since, I deployed many infrastructure using Jenkins pipeline.

Please review and share your suggestions.

Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 10341.
- Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.[0m[0m
+ echo 'Get the reference modules with the latest updated references'
Get the reference modules with the latest updated references

Thanks,
Sanjeevi

**Comment by justinretzolk** [comment]
Hey @sanjeevim 👋 Thank you for taking the time to raise this! It looks like this might actually be more of a Terraform Core issue, as it appears to be an issue with the Terraform state file itself. In this case, you'll likely receive more pointed assistance by opening an issue in the [Terraform Core](https://github.com/hashicorp/terraform) repository. 

Since this isn't an issue with the AWS Provider, we'll close this issue for now. If you feel we've done this in error, please do let us know.
