### ISSUE TITLE
feature: support `aws_vpc_ipam` `cascade` for easier deletes

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#23714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS IPAM released a new argument `cascade` which works like a `force_delete`. Add argument to the resource schema

Default should be false

### New or Affected Resource(s)

* aws_vpc_ipam

### Potential Terraform Configuration

```hcl
resource "aws_vpc_ipam" "test" {
  operating_region {
    region_name = "us-east-1"
  }
  cascade = true
}
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteIpam.html

**Comment by bigmikes** [comment]
Anybody working on this?

**Comment by drewmullen** [comment]
@bigmikes not me!

**Comment by AurelienNober** [comment]
Hello @drewmullen ,
I wanted to have a first look at the internals and thought that this feature could be a good way to do that. Just fyi I use the aws provider on a weekly basis and not for IPAM.
I locally added the cascade option and made it work but I had a few thoughts about the use case. If everything is defined within terraform state, the option is quite useless because all the vpc_ipam dependencies will be destroyed before the vpc_ipam is itself destroyed. Then the main use case for the cascade option would be to ensure resources created outside of terraform are destroyed too. Am I correct? If yes then for the acceptance test, does calling the create ipam scope api directly (to make sure there is a scope created outside of terraform state) sound like a good idea?

**Comment by AurelienNober** [comment]
Thanks for you reply!

> No if the feature is included in the provider then it should mimic the API behaviors. Scopes are not the only resource that can be a blocker to deleting: pools, provisioned CIDRs in those pools, or allocations to VPCs can also be a hinder an IPAM deletion.

Ok if I understand correctly, for the acceptance test, creating a scope by api (to create a potential deletion blocker) is ok but not enough as **all** blockers should be part of the test.

**Comment by drewmullen** [comment]
Oh, i'm sorry I misunderstood! Yes an extra scope is a perfectly valid test of the functionality! You should only need to test 1 type so Scope is valid

**Comment by AurelienNober** [comment]
Thanks for your input, tried to do something consistent
