### ISSUE TITLE
ECS Fargate Task Definition "forces replacement" for no reason

### ISSUE THREAD

**Issue by kotowick** [hashicorp/terraform-provider-aws#23726]
### Terraform CLI and Terraform AWS Provider Version

For some reason, Terraform insists on force replacing ECS Fargate task definition. If you look at the photo attached, there is **NO** +/- in the planned changes. Only `~`.

Why is terraform behaving like this?

VERSION:
Terraform v1.1.4
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.1.7. You can update by downloading from https://www.terraform.io/downloads.html

![Screen Shot 2022-03-16 at 11 11 47 PM](https://user-images.githubusercontent.com/1714316/158750702-dab69c3f-efb0-4988-8d97-c7a24f80e17a.png)

**Comment by justinretzolk** [comment]
Hey @kotowick 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the rest of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by md5** [comment]
If you look at the underlying ECS API, there is no `ecs:UpdateTaskDefinition` action, only `ecs:RegisterTaskDefinituon` and `ecs:DeregisterTaskDefinition`.

I believe the only in-place modification that is possible is through `ecs:TagResource` whereby you can update the tags on an existing task definition revision.
