### ISSUE TITLE
Please add support for JSONSchemaDraft4 in resource aws_schemas_schema

### ISSUE THREAD

**Issue by deepakgupta229** [hashicorp/terraform-provider-aws#23753]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I need to define my Schema in "JSON Schema Draft 4" format. Currently the "aws_schemas_schema" resource does not support the value "JSONSchemaDraft4" for the type argument.

Currently, when I run terraform plan with the value of "JSONSchemaDraft4" for the type argument, I get the following error message : 

```
"Error: expected type to be one of [OpenApi3], got JSONSchemaDraft4"
```

This should be supported, since Boto3 supports "JSONSchemaDraft4" https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/schemas.html#Schemas.Client.create_schema

### New or Affected Resource(s)

aws_schemas_schema

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @deepakgupta229 👋 Thank you for taking the time to raise this! The `type` argument is [validated](https://github.com/hashicorp/terraform-provider-aws/blob/7b4ea14367e7191232a4e3eb6addcd8f68cf31d6/internal/service/schemas/schema.go#L72) using the `schemas.Type_Values()` function from the AWS Go SDK. Looking at current state of the SDK, [that function is still returning](https://github.com/aws/aws-sdk-go/blob/9c5944cfe9cbf8128046b7ddaae5f7af942e5f95/service/schemas/api.go#L7462-L7467) only `OpenApi3`.

Because of the way that the provider is configured, as soon as the AWS Go SDK is updated and the new version is pulled into the provider, this should resolve itself.

**Comment by md5** [comment]
https://github.com/aws/aws-sdk-go/issues/4057 is the relevant SDK issue.

**Comment by deepakgupta229** [comment]
Hi @justinretzolk thanks for the explanation. Much appreciated !

**Comment by deepakgupta229** [comment]
Hi @md5 thanks also for the link to the AWS GO SDK issue.

**Comment by BardiaN** [comment]
The AWS golang SDK added `JSONSchemaDraft4` support but I can't still use it in Terraform, when could we expect this fix to be released please ? 

https://github.com/aws/aws-sdk-go/issues/4057 is closed/fixed.

**Comment by black-snow** [comment]
I second this - the upstream fix happened half a year ago @justinretzolk - looks like it didn't resolve itself :/

**Comment by giacoman** [comment]
Our team has been waiting for this update for about 1 1/2 years. Hopefully, it can get resolved soon.

**Comment by pmarko1711** [comment]
Hi, is there any update on this one, please?
