### ISSUE TITLE
 register-on-premises-instance  / add-tags-to-on-premises-instances

### ISSUE THREAD

**Issue by nbari** [hashicorp/terraform-provider-aws#23940]
Add a way to register on-premises instances, `register-on-premises-instance` so that they can be included in codedeploy 

Example using was:

    aws deploy register-on-premises-instance --instance-name AssetTag12010298EX --iam-user-arn arn:aws:iam::444455556666:user/CodeDeployUser-OnPrem

for adding tags:

    aws deploy add-tags-to-on-premises-instances --instance-names AssetTag12010298EX --tags Key=Name,Value=CodeDeployDemo-OnPrem

### References

https://docs.aws.amazon.com/codedeploy/latest/userguide/register-on-premises-instance-iam-user-arn.html

**Comment by justinretzolk** [comment]
Hey @nbari 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md?plain=1)?
