### ISSUE TITLE
Missing ability to tag SES resources (aws_ses_domain_identity and possibly aws_ses_email_identity) supporting tags

### ISSUE THREAD

**Issue by michaelsmoody** [hashicorp/terraform-provider-aws#23955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It appears that aws_ses_domain_identity does not support tags, despite AWS allowing tags for this resource type:

No tags
No tags are associated with this domain identity.

```
│ Error: Unsupported argument
│
│   on test-prd-app-static.tf line 2252, in resource "aws_ses_domain_identity" "testdomain_dot_com":
│ 2252:   tags = merge(
│
│ An argument named "tags" is not expected here.
```

I checked boto, and it appears I'm also able to tag this type of resource with boto as well.

### New or Affected Resource(s)

Any newly created or modified SES Domain Identity using aws_ses_domain_identity.
It seems that aws_ses_email_identity may also be affected).

### Potential Terraform Configuration

```hcl
## SES Domain Identity for testdomain.com
resource "aws_ses_domain_identity" "testdomain_dot_com" {
  domain = "testdomain.com"

## Tags are not currently supported for this resource type as of 2022-03-03 in the AWS provisioner, but ARE in AWS.
#   tags = merge(
#     {
#       Name = format("%s-%s-APP-SES-TESTDOMAIN", local.cust, local.env),
#     },
#     local.common_tags
#   )
}
```

Using this, we would get various tags, such as creation date, environment, etc. Even without it, and a simple "name" tag doesn't work.

### References

I checked both open and closed GitHub issues, and didn't find any referencing tagging for SES, looking back several years. However, it is possible it was missed.

* #0000

**Comment by gmx-git** [comment]
I guess this also depends on the use of SESv2 AWS SDK. I see there's a plan and a pull request for that.
Maybe we'll need to vote them up so they can pick up some traction.
Here are the links:
[https://github.com/hashicorp/terraform-provider-aws/issues/26796](url)
[https://github.com/hashicorp/terraform-provider-aws/pull/26846](url)

Hope this helps move this one forward as well!

**Comment by gmx-git** [comment]
Thanks for the update. Great work on having the base for sesv2 added to the provider!

There are no domain or email identity in the sesv2 section of the aws provider documentation, so they still don't accept tags.
For now, I can only see 2 resources added to the SESv2 aws provider.
It would be great to have all the sesv2 resources added into the provider. This will allow us to migrate the configurations one time, instead of migrating resource type by resource type individually, when they get implemented.

Here's a screenshot of what I see. I've highlighted the 2 resources reported in this issue in blue. They only show on the v1 side. As mentioned, these are just examples, we'd love if all v2 resources could be added to the provider.

![image](https://user-images.githubusercontent.com/22165229/197963841-27ddd008-63e2-43ea-9f86-c9876a05b6b4.png)

**Comment by kamilturek** [comment]
Hey @gmx-git, thank you! 🙌  The `aws_sesv2_email_identity` (supporting both domains and email addresses) will be released in version 4.37.0.

**Comment by gmx-git** [comment]
That's great news! Thanks Kamil!

**Comment by kamilturek** [comment]
Hey @justinretzolk, could we close this issue?
