### ISSUE TITLE
aws_prometheus_workspace is missing the remote write URL in its output

### ISSUE THREAD

**Issue by wattdave** [hashicorp/terraform-provider-aws#23957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

An AWS Managed Prometheus instance has several potentially useful parameters that could be communicated to callers, that are visible in the AWS console UI:

ARN
workspaceId
queryUrl
remoteWriteUrl

At the moment, the aws_prometheus_workspace resource only exports the ARN, the Id, and, erm, one of the other two, but it's not clear from the documentation which it is. Actually, now that I look at the output, I see it's the start of an endpoint; and you need to add to it either /api/v1/query or /api/v1/remote_write to get to the two URLs above. I'm having a 'don't-make-me-think' reaction to that - I think providing the full urls and their names would be more helpful to the consumers of this resource.

### New or Affected Resource(s)

* aws_prometheus_workspace

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

**Comment by justinretzolk** [comment]
Hey @wattdave 👋 Thank you for taking the time to raise this! After creating the workspace, Terraform reads the resulting resource using [`DescribeWorkspace`](https://docs.aws.amazon.com/sdk-for-go/api/service/prometheusservice/#PrometheusService.DescribeWorkspace). This returns a type of [`DescribeWorkspaceOutput`](https://docs.aws.amazon.com/sdk-for-go/api/service/prometheusservice/#DescribeWorkspaceOutput), which contains a field called `Workspace` with a type of [`WorkspaceDescription`](https://docs.aws.amazon.com/sdk-for-go/api/service/prometheusservice/#WorkspaceDescription). This `WorkspaceDescription` type is ultimately where Terraform pulls the information about the newly created resource, and notably does not contain the extra fields you mentioned.

I started to look into this a bit, and found that there are no calls from the API/SDK that allow for retrieving the query/remote write URLs. I'd considered that since you mentioned it's typically `/api/v1/remote_write` and `/api/v1/query`, we could simply append this to the end of the `prometheus_endpoint`, however, since these values are customizable (reference [AWS documentation](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics.html) and related [Prometheus documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write)), that won't work in all cases.

Unfortunately, this seems to be something that we're limited by the underlying API/SDK. Given that's the case, we'll close this issue for now. If things change in the future and reading those values is possible, we'd be more than happy to look into this again.
