### ISSUE TITLE
EC2 instance is always recreating on any change

### ISSUE THREAD

**Issue by aravindkoniki** [hashicorp/terraform-provider-aws#24016]
---
name: 🐛 Bug Report
about: EC2 Instance is always recreating on any change

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/tls v3.2.0

### Affected Resource(s)

* EC2 Instance
* EBS Volumes

### Terraform Configuration Files

Sharing my complete terraform EC2 module with examples, where you can reproduce the error by running the examples
https://1drv.ms/u/s!AiUI_aDDC1qLiOxIOxJoF81GNbDlvQ?e=PE43lf

### Expected Behavior

1. EC2 should not recreate when i add an EBS volume or Security group id in "vpc_security_group_ids"
2.  Existing EBS volume is deleted and recreating 

### Actual Behavior

I have written terraform EC2 module written, which will take inputs as EBS, NIC and security groups

What ever change i do, EC2 is always recreated by destroying EBS, EC2, NIC and recreates again

Sharing screen shots from plan, complete code is shared

![image](https://user-images.githubusercontent.com/38941211/161546705-617f74e9-5c1a-47fb-bff3-eefa6b0f564d.png)

![image](https://user-images.githubusercontent.com/38941211/161546983-9ff0dcf4-7e68-4943-988f-b2f48592a697.png)

![image](https://user-images.githubusercontent.com/38941211/161560503-f7ae9442-e740-4da4-9872-738fea5afdb8.png)

Adding new EBS, again my instance is doing force creation 
![image](https://user-images.githubusercontent.com/38941211/161563142-fa765b12-c148-41e4-984a-796efb50b7df.png)

![image](https://user-images.githubusercontent.com/38941211/161563729-ad1159d1-6fcf-42ff-861f-bb15e9d1ed86.png)

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
4. `terraform apply`

### Important Factoids

No

* #0000

**Comment by devopsrick** [comment]
There must be more to that plan.  Terraform should show exactly why it is replacing the instance.  Look for a single attribute that shows 'forces replacement' somewhere in the plan.

**Comment by mbotmcc** [comment]
I've seen this before with incorrect EBS settings

**Comment by aravindkoniki** [comment]
Thank you for responding, actually i have added one more security group to the primary nic, but nor sure my EC2 is force replacement

![image](https://user-images.githubusercontent.com/38941211/161560503-f7ae9442-e740-4da4-9872-738fea5afdb8.png)

**Comment by justinretzolk** [comment]
Hey @aravindkoniki 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by aravindkoniki** [comment]
Hi  @justinretzolk , i updated according to the bug report,  stuck up with this issue for couple of days, kindly help me to resolve

**Comment by aravindkoniki** [comment]
Any luck for me, its a very critical issue for me to go a head @justinretzolk 

Can any one help me to get workaround

**Comment by justinretzolk** [comment]
Hey @aravindkoniki 👋 I downloaded your sample configuration and started to take a look at it and the screenshots you provided. Based on the screenshots, it appears that the `aws_instance` is being replaced due to a change in the `root_block_device.kms_key_id`. The `aws_volume_attachment.ebs_volume` resources are then forced to be replaced because they reference the `aws_instance.instance.id` (`instance_id = aws_instance.instance.id`).

I'm not seeing anywhere in the screenshots where the EBS volumes themselves are being recreated -- it appears the volume attachments are the only EBS-related thing being recreated, for the reason outline above. Full debug logs, or even a full plan log (both redacted as necessary) may provide additional insight here. As it stands at the moment, the only thing that I can say for certain is that the `aws_instance.instance.root_block_device.kms_key_id` change may be the culprit for at least part of the behavior you're experiencing.

**Comment by aravindkoniki** [comment]
Hi @justinretzolk 

As you said i have changed my code from `kms_key_id  = var.root_block_device_encrypted == true && var.root_volume_kms_key_arn == null ? data.aws_ebs_default_kms_key.current.key_arn : var.root_volume_kms_key_arn` to 
`kms_key_id            = var.root_block_device_encrypted == true ? var.root_volume_kms_key_arn : null` then the issue has been resolved.

Im not sure what's the problem in apply default KMS key to the volume, if there is no key provided

Anyways, thank you for your input and you have saved me 👍
