### ISSUE TITLE
aws_guardduty_publishing_destination prefix for destination_arn not working

### ISSUE THREAD

**Issue by AzySir** [hashicorp/terraform-provider-aws#24037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hi there - 

I am following this: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_publishing_destination

**Information from Docs** 

```
destination_arn - (Required) The bucket arn and prefix under which the findings get exported. Bucket-ARN is required, the prefix is optional and will be AWSLogs/[Account-ID]/GuardDuty/[Region]/ if not provided
```

**Desired Result:**

I want a destination_arn set as an S3 Bucket **WITH** a custom prefix which would be - `guardduty/` 

**Actual Result**

```
resource "aws_guardduty_publishing_destination" "logging_publishing_destination" {
  detector_id      = data.aws_guardduty_detector.security_detector.id
  destination_arn  = "arn:aws:s3:::${var.central_logging_bucket}/guardduty"
  kms_key_arn      = var.central_logging_bucket_kms
  destination_type = "S3"
}
```

**Error**

```
│ Error: Updating GuardDuty publishing destination '0478yasdajsdk' failed: BadRequestException: The request failed because you do not have the required permissions for the s3:GetObject or s3:ListBucket actions.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "838b7b06-9655-459c-b43c-8aeed9ba5cd9"
│   },
│   Message_: "The request failed because you do not have the required permissions for the s3:GetObject or s3:ListBucket actions.",
│   Type: "InvalidInputException"
│ }
│
│   with aws_guardduty_publishing_destination.logging_publishing_destination,
│   on guardduty.tf line 14, in resource "aws_guardduty_publishing_destination" "logging_publishing_destination":
│   14: resource "aws_guardduty_publishing_destination" "logging_publishing_destination" {
│
```

If i have no prefix at the end of the destination_arn i.e `  destination_arn  = "arn:aws:s3:::${var.central_logging_bucket}"` this works fine.

My KMS is obviously working as I've tied that policy for `kms:*` for `guardduty.amazonaws.com` 

My S3 Policy are very open right now also on the bucket - 

```
  {
            "Sid": "AllowGuardDutygetBucketLocation",
            "Effect": "Allow",
            "Principal": {
                "Service": "guardduty.amazonaws.com"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::mybucket",
                "arn:aws:s3:::mybucket/*"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:SourceAccount": "123123123123"
                }
            }
```

Am I handling this wrong? Have I misunderstood the documentation - could someone please assist?

**Comment by justinretzolk** [comment]
Hey @AzySir 👋 Thank you for taking the time to raise this! If I'm reading [this AWS document](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_exportfindings.html) (under the "Permissions required to configure findings export" header), I believe this may be an issue of permissions for the credentials used to authenticate with the AWS Provider, rather than the permissions granted to GuardDuty itself. Can you verify that the credentials used to authenticate with the provider have the necessary permissions as outlined in that document?

**Comment by AzySir** [comment]
Hi @justinretzolk it's been a while since i've done this mate - but I'm pretty sure i had administrator access so policy was `*` for everything.

Is there a unit test here that proves this to work or something along those lines?

**Comment by justinretzolk** [comment]
Hey @AzySir 👋 [It looks like](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/guardduty/publishing_destination_test.go) there's not a test that covers the scenario of there being a a prefix. I took a few minutes to review the code and wanted to note a couple of things:

The resource is taking the value of `destination_arn` and [passing it straight to](https://github.com/hashicorp/terraform-provider-aws/blob/3cf15a22d8e393d5e7439c2f4d2cb75ed92d6ceb/internal/service/guardduty/publishing_destination.go#L58-L65) the input for the `CreatePublishingDestination` call (rather than processing that data in any way). That Go struct's documentation is found [here](https://docs.aws.amazon.com/sdk-for-go/api/service/guardduty/#DestinationProperties) and says:

```plaintext
// The ARN of the resource to publish to.
//
// To specify an S3 bucket folder use the following format: arn:aws:s3:::DOC-EXAMPLE-BUCKET/myFolder/
```

...which seems to match up with what you're using aside from the trailing slash -- I don't imagine that's the issue, but perhaps something to try if you're still trying to track down a fix/workaround while this waits to be prioritized. Debug logs might also help once this gets picked up (redacted as needed), if you're able to grab those still.

**Comment by AzySir** [comment]
@justinretzolk I should have shared those DEBUG logs - i will be trying this again in the next month or two with the new Landing Zone I'm building - I'll accelerate myself to guardduty first to see if i can rectify the issue with your suggested fix.

I believe I tried many variations - let me provide an update on this if okay with you can we live this issue open ?

**Comment by justinretzolk** [comment]
Sounds great to me @AzySir! Thank you for being willing to test it again and report back with what you find! Always love to see that, in case anyone down the road runs into this. Here's hoping you're able to get past the issue this time around 🤞.
