### ISSUE TITLE
Support ordering of SES receipt rules within rule set

### ISSUE THREAD

**Issue by mxxk** [hashicorp/terraform-provider-aws#24067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to specify the order of SES receipt rules? (See screenshot.) As far as I can tell, the AWS provider only supports the ordering of actions within a single receipt rule (via the [`position` argument of an action block within `aws_ses_receipt_rule`](https://registry.terraform.io/providers/hashicorp/aws/4.8.0/docs/resources/ses_receipt_rule#position)), but not the ordering of receipt rules within a rule set.

In the example below, the order of `rule_a`, `rule_b`, `rule_c` appears arbitrary after `terraform apply` (though may be because Terraform sets are unordered?)

### New or Affected Resource(s)

* `aws_ses_receipt_rule_set`
* `aws_ses_receipt_rule`

### Potential Terraform Configuration

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.5.0"
    }
  }
}

locals {
  ses_rules = toset(["a", "b", "c"])
}

resource "aws_ses_receipt_rule_set" "rule_set" {
  rule_set_name = "rule_set"
}

resource "aws_ses_receipt_rule" "rule" {
  for_each = local.ses_rules

  rule_set_name = aws_ses_receipt_rule_set.rule_set.rule_set_name
  name          = "rule_${each.key}"
  enabled       = true

  add_header_action {
    position     = 1
    header_name  = "X-Processed-By-Rule"
    header_value = "rule_${each.key}"
  }
}
```

### References

- SES receipt rule ordering in AWS console

    ![image](https://user-images.githubusercontent.com/2456381/162312348-13591b0d-1146-4696-94e5-3d3e2c67633c.png)

**Comment by justinretzolk** [comment]
Hey @mxxk 👋 It looks like the argument you're looking for is [`after`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_receipt_rule#after). To save you a click:

- [`after`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_receipt_rule#after) - (Optional) The name of the rule to place this rule after

As far as why the rules seemed arbitrarily ordered, the documentation from the related [AWS Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/ses/#CreateReceiptRuleInput) type definition gives a better idea as to why:

```go
    // The name of an existing rule after which the new rule will be placed. If
    // this parameter is null, the new rule will be inserted at the beginning of
    // the rule list.
```

Referencing your screenshot and configuration, `rule_a` is was created first and put in position 1, then `rule_b` was created and set to position 1, moving `rule_a` down to position 2, etc.

With that in mind, I think you could order them in the same order that your `local.ses_rules` is ordered in fairly easily. I haven't tested the below code with `aws_ses_receipt_rule` resources yet, but it should be most of the way there, if that's what you're looking to do.

Note: in order for this to work, you'll need to remove `toset()` from your `local.ses_rules` definition and move it to the `for_each` declaration in `aws_ses_receipt_rule`, since you can't use the `index()` function against sets, and calling `tolist()` against it may not order things exactly how you'd expect.

```hcl
after = index(local.ses_rules, each.value) == 0 ? null : "rule_${element(local.ses_rules, index(local.ses_rules, each.value) - 1)}"
```

To break this down, it uses a [conditional expression](https://www.terraform.io/language/expressions/conditionals) to:

- `index(local.ses_rules, each.value) == 0 ?`: check to see if the current item in the set is the first element in the list. If so...
-  `null :` - don't set `after`, so that the given rule is put at the top of the list, else...
- `"rule_${element(local.ses_rules, index(local.ses_rules, each.value) - 1)}"` - set `after` to a string prefixed with `rule_` (since that's what you're using as the name for rules in your example), followed by getting the value for the element in the list that is one position before the current element. This will mean that the rules will get ordered sequentially based on their position in the list.

I tested this using a `random_pet` resource, since setting up the rules wasn't really necessary to determine how to make this work (since it's more of a "how could I achieve this with HCL" issue). I'll put my sample configuration and sample output below so you can see what this looks like in practice.

**Test configuration:**

```hcl
locals {
  test = ["one", "two", "three"]
}

resource "random_pet" "string" {
  for_each = toset(local.test)
  prefix   = index(local.test, each.value) == 0 ? null : "after_rule_${element(local.test, index(local.test, each.value) - 1)}"
}
```

**Sample output from a plan:**

```plaintext
  # random_pet.string["one"] will be created
  + resource "random_pet" "string" {
      + id        = (known after apply)
      + length    = 2
      + separator = "-"
    }

  # random_pet.string["three"] will be created
  + resource "random_pet" "string" {
      + id        = (known after apply)
      + length    = 2
      + prefix    = "after_rule_two"
      + separator = "-"
    }

  # random_pet.string["two"] will be created
  + resource "random_pet" "string" {
      + id        = (known after apply)
      + length    = 2
      + prefix    = "after_rule_one"
      + separator = "-"
    }
```

Note that for each index (`random_pet.string["three"]`), the `prefix` is set to `after_rule_` + the element that's offset by -1 in the source list. Since `"one"` is the first element in the list, the `prefix` was set to `null`, and so doesn't appear in the plan output. 

I realize this is quite a length reply -- this was an interesting challenge for me and I got a bit carried away with it 🙂. If you have any follow up questions, I'd be happy to continue the conversation.

**Comment by mxxk** [comment]
Thanks so much for the detailed reply @justinretzolk! Looks like I completely missed the `after` argument in the initial question. I appreciate the example and explanation. 🙌

**Comment by LuisMuniz** [comment]
Hi, I know this issue is closed, and it looks like this solves the problem for statically specified rules, but it does not work in the case of for_each.

I have tried your solution, and It does create the first rule, and fails when creating the second, and all subsequent rules, because te first rule does not exist yet (the one with after=null).

If I re-run the apply, then the second rule is created, but all the other rules fail.

my `recipients_by_position` map is indexed by 0-padded position (i.e. "01", "02", etc):

This is my code 


```
resource "aws_ses_receipt_rule" "store" {
  for_each = local.recipients_by_position
  after   = each.value.position == 1 ? null : "${format("%02s",each.value.position - 1)}"

#  name          = "${each.value.short_name}-store_on_s3-${each.value.recipient}"
  name          = each.key
  rule_set_name = aws_ses_receipt_rule_set.main.rule_set_name
  recipients    =  ["${each.value.recipient}@${each.value.domain}"]
  enabled       = true
  scan_enabled  = true

  s3_action {
    bucket_name = aws_s3_bucket.mailboxes[each.value.domain].bucket
    object_key_prefix = each.value.recipient
    position    = 1
  }
}
```

**Comment by LuisMuniz** [comment]
This issue being closed, a more complete example (with some locals) in SO question here https://stackoverflow.com/questions/71980373/create-aws-ses-receipt-rule-in-predefined-order-with-for-each-loop
