### ISSUE TITLE
`data.aws_iam_server_certificate` in template causes endless loop during `terraform plan`

### ISSUE THREAD

**Issue by rirze** [hashicorp/terraform-provider-aws#24184]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `data.aws_iam_server_certificate`

### Terraform Configuration Files

JSON code:

```json
"data": {
    "aws_iam_server_certificate": {
      "default-domain": {
        },
        "name": "some.domain.com"
      }
    },

```

### Debug Output

The following is repeating endlessly:
```
2022-04-11T16:13:11.890Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
2022-04-11T16:13:13.584Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "data.aws_iam_server_certificate.default-domain (expand)"
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Using latest provider.

**Comment by irshad116** [comment]
getting the exact same issue with version = "~> 3.71.0" . 


-----------------------------------------------------: timestamp=2022-04-11T17:08:12.656+0100
2022-04-11T17:08:12.657+0100 [INFO]  plugin.terraform-provider-aws_v3.71.0_x5: 2022/04/11 17:08:12 [DEBUG] [aws-sdk-go] {"Tags":[]}: timestamp=2022-04-11T17:08:12.656+0100
2022-04-11T17:08:12.658+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-04-11T17:08:12.662+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/aws/3.71.0/darwin_amd64/terraform-provider-aws_v3.71.0_x5 pid=33611
2022-04-11T17:08:12.662+0100 [DEBUG] plugin: plugin exited

Error: AccessDenied: Access Denied
	status code: 403, request id: XXXXXX, host id: XXXXXXXX

**Comment by justinretzolk** [comment]
Hey @rirze 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include the versions of Terraform and the AWS Provider that you're using, as well as the full debug logs (redacted as necessary)?

**Comment by rirze** [comment]
I've given a good amount of info in order to replicate this issue. I can get you full details tomorrow, but you will find this error fully reproducible.

**Comment by justinretzolk** [comment]
Hey @rirze 👋 I attempted to reproduce this with the given information, but have not been able to do so. One difference in my test was that the JSON presented didn't seem to work for this resource, given that the `name` argument was outside of the `default-domain` block, so an error was thrown. After changing this, my configuration looked as follows:

```json
{
  "data": {
    "aws_iam_server_certificate": {
      "default-domain": {
        "name": "jretzolk-test"
      }
    }
  }
}
```

When attempting an `apply` with this configuration, I received:

```plaintext
➜ terraform apply

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

This is the output I'd expect, since the configuration is _only_ a data source -- the state file was still updated with the information retrieved from the data source.

**Comment by irshad116** [comment]
Hello Guys, 

I now know my issue which I raised here and will try to explain the cause and I think I would still call it a terraform bug. I had a faulty code which does the tfstate lookup from a separate workspace : 
data "terraform_remote_state" "remote_state" {
  backend = "s3"
  config = {
    bucket = "XXXX-core-${var.env}-tfstate"
    region = "eu-west-2"
    key    = "env:/core-${var.env}/env.tfstate"
  }
} 
where in the correct lookup code should look like - 
data "terraform_remote_state" "remote_state" {
  backend = "s3"
  config = {
    bucket = "security-core-${var.env}-XXXXX-tfstate"
    region = "eu-west-2"
    key    = "env:/core-${var.env}/env.tfstate"
  }
}
However, while I was running terraform ( because of this faulty code ) the plugin exited with some error nowhere related to above, error description was - 

-----------------------------------------------------: timestamp=2022-04-12T11:04:47.402+0100
2022-04-12T11:04:47.402+0100 [INFO]  plugin.terraform-provider-aws_v3.71.0_x5: 2022/04/12 11:04:47 [DEBUG] [aws-sdk-go] {"Tags":[]}: timestamp=2022-04-12T11:04:47.402+0100
2022-04-12T11:04:47.403+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-04-12T11:04:47.409+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/aws/3.71.0/darwin_amd64/terraform-provider-aws_v3.71.0_x5 pid=35466
2022-04-12T11:04:47.409+0100 [DEBUG] plugin: plugin exited

Error: AccessDenied: Access Denied
2022/04/12 11:04:47 [DEBUG] [aws-sdk-go] DEBUG: Request dynamodb/GetItem Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-west-2.amazonaws.com
User-Agent: aws-sdk-go/1.31.9 (go1.14.7; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.13.7
Content-Length: 202
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXX/20220412/eu-west-2/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=9XXXXXXXXXXXXX
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20220412T100447Z
X-Amz-Target: DynamoDB_20120810.GetItem

{"ConsistentRead":true,"Key":{"LockID":{"S":"XXXXXX-security-dev-XXXX-tfstate/env:/dev/env.tfstate"}},"ProjectionExpression":"LockID, Info","TableName":"XXXXX-security-tflock-dev-XXXXX"}
-----------------------------------------------------
	status code: 403, request id: XXXXXXXXX, host id: XXXXXXXXXXXXXXXXX


Releasing state lock. This may take a few moments...
2022/04/12 11:04:47 [DEBUG] [aws-sdk-go] DEBUG: Response dynamodb/GetItem Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 389
Content-Type: application/x-amz-json-1.0
Date: Tue, 12 Apr 2022 10:04:47 GMT
Server: Server
X-Amz-Crc32: 1778004550
X-Amzn-Requestid: XXXXXXXXXXXXXX

In my view the plugging should say - "Error: AccessDenied: Access Denied"  (on the tfstate bucket) and not -  plugin: plugin exited which was really hard to locate what is wrong where.

**Comment by irshad116** [comment]
and also this is present in aws provide ~4.8.0 as well

**Comment by justinretzolk** [comment]
Hey @irshad116 👋 It looks like you're running into issues when using a `terraform_remote_state` data source. That would be related to Terraform Core rather than the AWS Provider. You may want to open an issue in the [Terraform Core repository](https://github.com/hashicorp/terraform) to have someone take a better look into that particular issue.

**Comment by rirze** [comment]
Hi @justinretzolk, thanks for the informative reply. 

I've been isolating the issue for a few hours now and it seems the original issue is related to Terraform not being able to complete the associated AWS IAM API calls. I first was able to notice this when the full plan command ran successfully on a different machine with a different networking configuration where it was able to talk to the IAM endpoint directly. 

The issue arose when running Terraform on a CI runner where that IAM endpoint wasn't exposed to the CI server. And since the 25 retries would take longer than the max duration of the CI job, I wasn't able to get to the point where Terraform would (potentially?) gracefully exit with an error. 

I'm not sure if this is something that Terraform could improve so I'll close this for now.
