### ISSUE TITLE
Error: error configuring Terraform AWS Provider:

### ISSUE THREAD

**Issue by RamanRathore08** [hashicorp/terraform-provider-aws#24197]
Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
status code: 403

**Comment by justinretzolk** [comment]
Hey @RamanRathore08 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?
