### ISSUE TITLE
error configuring Terraform AWS Provider: Error creating AWS session: LoadCustomCABundleError:

### ISSUE THREAD

**Issue by saisenghein** [hashicorp/terraform-provider-aws#24191]
Hello Team, 
I am facing this issue. 

error configuring Terraform AWS Provider: Error creating AWS session: LoadCustomCABundleError: failed to open custom CA bundle PEM file
│ caused by: open C:\data\ca-certs\ca-bundle.pem: The system cannot find the path specified.
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 12, in provider "aws":
│   12: provider "aws" {

**Comment by justinretzolk** [comment]
Hey  👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?
