### ISSUE TITLE
Setting keyvault reference for azure function app failing

### ISSUE THREAD

**Issue by gurudatth** [hashicorp/terraform-provider-aws#24243]
I am getting error while referencing zip package path of function app from key vault secret reference via "WEBSITE_RUN_FROM_PACKAGE" field

![Inkedterraformerror_LI](https://user-images.githubusercontent.com/15104747/163415001-e6e3d305-c8fe-46fd-ac07-ac1d95126217.jpg)
.

**Comment by justinretzolk** [comment]
Hey @gurudatth 👋 It looks like this is an issue with the AzureRM provider. In order to have someone look at this, you'll want to open an issue in the AzureRM [provider repository](https://github.com/hashicorp/terraform-provider-azurerm).

Since this doesn't pertain to the AWS Provider, I'm going to close this issue out as well. Please let me know if you feel I've done this in error.
