### ISSUE TITLE
error configuring Terraform AWS Provider Windows - refers to random paths

### ISSUE THREAD

**Issue by csetzkorn** [hashicorp/terraform-provider-aws#24279]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I appear to have an issue with this [line of code](https://github.com/hashicorp/terraform-provider-aws/blob/bf896df654b121a8066dc66087aea3df6ac8feaa/internal/conns/conns.go#L681):

```
cfg, err := awsbase.GetAwsConfig(ctx, &awsbaseConfig)
	if err != nil {
		return nil, diag.Errorf("error configuring Terraform AWS Provider: %s", err)
	}
```

I am using the following either in elevated or non elevated mode in Windows:

```
provider "aws" {
    region = "eu-west-2"
    shared_config_files = ["C:\\Users\\blabla\\.aws\\config"]
    shared_credentials_files = ["C:\\Users\\blabla\\.aws\\credentials"]
    profile = "default"
}  

resource "aws_s3_bucket" "b" {
    bucket = "amazing-bucket"
}
```

If I run as admin I get:

```
│ Error:  Error: error configuring Terraform AWS Provider: loading configuration: read C:\Users\blabla\env\Lib\site-packages\pip\_vendor\certifi: The handle is invalid.
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on Main.tf line 1, in provider "aws":
│    1: provider "aws" {
``` 

If I run it as myself I get:

```
│ Error:  Error: error configuring Terraform AWS Provider: loading configuration: read C:\data\: The handle is invalid.
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on Main.tf line 1, in provider "aws":
│    1: provider "aws" {
``` 
I am pretty sure the AWS credentials are picked up as I deliberately changed the shared_credentials_files + shared_config_files entries and got a sensible error. So why does the code refer to these odd/random folders/paths? Maybe the issue is further upstream in GetAwsConfig? I also posted this on SO [here](https://stackoverflow.com/questions/71817424/pip-vendor-certifi-handle-is-invalid?noredirect=1#comment127033981_71817424).

**Comment by justinretzolk** [comment]
Hey @csetzkorn 👋 Thank you for taking the time to raise this! So that we have all of the necessary information to look into this, can you supply the Terraform and AWS Provider versions you're using, as well as debug logs (redacted as necessary)?

**Comment by csetzkorn** [comment]
Thanks for the reply. The requested information is as follows:

aws-cli/2.5.5 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

Terraform v1.1.8 on windows_amd64

**Comment by justinretzolk** [comment]
Hey @csetzkorn 👋 Thank you for sending that information over! It looks like you sent the version of AWS CLI that you have installed -- can you also send over the AWS Provider version that you're using? That can be found by running the following command in the configuration directory after Terraform has been initialized.

```shell
$ terraform --version
```

**Comment by csetzkorn** [comment]
Thanks. Is the above:

Terraform v1.1.8 on windows_amd64

not what you need? Guess that's the Terraform not the AWS provider version.

Oddly enough I now get:

error configuring S3 Backend: Error creating AWS session: LoadCustomCABundleError: failed to open custom CA bundle PEM file
│ caused by: open C:\Users\blabla\env\Lib\site-packages\pip\_vendor\certifi: The system cannot find the path specified

even when I do terraform init. There must be something totally screwed up on my machine. Having said that, I can now use github actions to run terraform so I am not at the mercy of my windows machine. So maybe just close this? Thanks.

**Comment by csetzkorn** [comment]
I may be missing something but is the above:

Terraform v1.1.8 on windows_amd64

not what you need? I get the same in the folder after running terraform init.

**Comment by justinretzolk** [comment]
Hey @csetzkorn 👋 I see what's happening here now: `terraform --version` will only give you the AWS Provider version as well after you've run a `terraform init`. Since you're not able to init, the provider isn't being downloaded, and so you're not getting the output for the provider version. Apologies that I didn't catch that before.

Given you've got a workaround in the form of using GitHub Actions, I don't want to waste your time, but if you'd like to continue looking into this, I'm more than happy to keep working with you. I'll detail my next thought below, but if you'd prefer to close this issue and move on, I understand completely.

Are you [pinning the version of the provider](https://www.terraform.io/language/providers/requirements) at all? If so, that block should give me enough info to try to determine which provider version you're running. Alternatively, when you run the `terraform init`, it should give an output similar to the following:

```plaintext
> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 4.0"...
- Installing hashicorp/aws v4.12.1...
- Installed hashicorp/aws v4.12.1 (signed by HashiCorp)
```

**Comment by csetzkorn** [comment]
No pinning - I think I have used in a previous version though. This is the output from init:

Initializing the backend...

```
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v4.12.1...
```

**Comment by gdavison** [comment]
Hi @csetzkorn, do you happen to have any `AWS_*` environment variables set that might be overriding your settings? Are you running Terraform directly from the command line, or using a wrapper script for authentication, etc.?

One step that may help rule out some sources of the problem is to use forward slashes instead of back slashes. Terraform (and Go) can handle them correctly.
