### ISSUE TITLE
Add resource aws_ses_receipt_rule to a rule set using the rule set ARN

### ISSUE THREAD

**Issue by v1nc3n4** [hashicorp/terraform-provider-aws#24310]
Hello,

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Actually, the `aws_ses_receipt_rule` resource can only be added in a rule set using the name of the rule set (argument `rule_set_name`). This does not work if the rule set is defined in a region which is not the region currently "set" in the provider. To be working in all situations, I guess adding a rule to a rule set should be based on the rule set ARN and not its name.
This would also be great when SES is used to receive emails in 2 regions where both rule sets have the same name.

### New or Affected Resource(s)

* aws_ses_receipt_rule

Thanks in advance for your help, and this great tool!
BR

**Comment by justinretzolk** [comment]
Hey @v1nc3n4 👋 Thank you for taking the time to raise this, and for your kind words! Unfortunately, it looks like this is a limitation of the underlying API. This resource uses [`ses. CreateReceiptRule`](https://docs.aws.amazon.com/sdk-for-go/api/service/ses/#CreateReceiptRuleInput) to create the receipt rule (which ultimately uses the [CreateReceiptRule](https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateReceiptRule.html) API call). This function / API expects the the `RuleSetName` argument to be a string value matching the name of a rule set.

Since this is a limitation of the underlying API, we'll close this issue for now. If the API is changed at a later date, we'd be more than happy to take another look!

**Comment by v1nc3n4** [comment]
Hi @justinretzolk,
Thank you for your reactive support and this clarification. As a workaround, I understand that managing the rule set must be entirely done with a provider in the target region. I update my configuration accordingly.
