### ISSUE TITLE
Releases 3.75.0 and 3.75.1 are missing in "GitHub Releases" and CHANGELOG.md

### ISSUE THREAD

**Issue by arogulin** [hashicorp/terraform-provider-aws#24345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Releases `3.75.0` and `3.75.1` are available in the registry (https://registry.terraform.io/providers/hashicorp/aws/3.75.1), but I wasn't able to find any release notes for them in https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md or on  https://github.com/hashicorp/terraform-provider-aws/releases page. The only place they exist is the Tags page:
* https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.75.0
* https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.75.1

**Comment by justinretzolk** [comment]
Hey @arogulin 👋 Thank you for taking the time to raise this and point that out! I'm working internally to figure out what we'll need to do to add `3.75.0` and `3.75.1` to the main changelog. In the meantime, they can be found at the [changelog for 3.x](https://github.com/hashicorp/terraform-provider-aws/blob/release/3.x/CHANGELOG.md) if you're looking for the release notes immediately.

As far as the releases page, since these versions were released _after_ some of the `4.x` releases, the ordering is a bit off, but both releases are on the [releases page](https://github.com/hashicorp/terraform-provider-aws/releases) -- just above (`3.75.1`) and below (`3.75.0`) the `4.6.0` release.

**Comment by arogulin** [comment]
Thank you Justin for looking into that issue. You're right, they are present on the Releases, I don't understand how I could not find them that day by using `CMD+f` in the browser and searching for "3.75", but now I do see them. I also used "Find a release" input on that page, but it did not find anything using "3.75" string, whereas "v3.75" does work, but that is 100% GitHub's behavior. Thanks again for your help!
