### ISSUE TITLE
Version requirements are not clear

### ISSUE THREAD

**Issue by sivanagireddyb** [hashicorp/terraform-provider-aws#24375]
My Current Terraform & AWS Provider versions are : **0.12.19** &  **2.38.0**

I am trying to upgrade the AWS provider version from 2.38.0 to 3.74.0 by following this [doc](https://registry.terraform.io/providers/hashicorp/aws/3.74.0/docs).

I made the change in provider.tf as the document says for ```Terraform 0.12 and earlier```:
```
provider "aws" {
  version = "3.74.0"
}
````
Output of terraform providers command:
```
├── provider.aws 3.74.0
├── provider.external
├── provider.terraform
├── module.alb_alarms
│   └── provider.aws (inherited)
├── module.beanstalk_alb
│   └── provider.aws (inherited)
└── module.boron2_alb
    └── provider.aws (inherited)
```
Below is the error i am getting:
```
No provider "aws" plugins meet the constraint "3.74.0".

The version constraint is derived from the "version" argument within the
provider "aws" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout 
the configuration.

Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512



Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 
vimal k5:16 PM
 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512



Error: no suitable version is available


exit status 1
Error: exit status 1
```
Expect the document to be clear about the version requirements as it only says 0.12 or earlier.

**Comment by AdamJCavanaugh** [comment]
I don't think I see any lack of clarity in the documentation regarding the AWS provider and Terraform 0.12 in general, necessarily. I see a warning in your output about updating Terraform from 0.12.19 to at least 0.12.31 due to the outdated GPG key, which appears to be what is breaking the provider version update.

Can you update Terraform to at least 0.12.31 and try again?

**Comment by justinretzolk** [comment]
Hey @sivanagireddyb 👋 In addition to what Adam said above, I do see that you're receiving a message that no provider meets the constraints of `3.74.0`. This is due to later versions of the provider being incompatible with older versions of Terraform. If you instead switch to using [pessimistic constraints](https://www.terraform.io/language/expressions/version-constraints#version-constraint-syntax), e.g. `~> 3.0`, the latest compatible `3.x` version will be used. Based on my testing, for Terraform `0.12.19`, the latest available version is `3.37.0`.

I'd still recommend upgrading to a later version of Terraform due to the GPG key issue, but if you are unable to for whatever reason, switching to the pessimistic constraint would at least allow you to upgrade to a slightly newer version of the AWS Provider.

**Comment by sivanagireddyb** [comment]
Hey @justinretzolk, I am aware of [pessimistic constraints](https://www.terraform.io/language/expressions/version-constraints#version-constraint-syntax).  if I use it then it is downloading 3.26.x but the requirement is 3.74.

And I understand the issue from the warning and I updated terraform to version 0.12.31. What I am looking for is where in the document it says if you want to use provider 3.74  terraform version must be above 0.12.31?

All it says is ```0.12 and earlier ```.And how useful and easy it would be if we can have a table of compatible provider & terraform versions in one place instead of looking over each version docs !!.

**Comment by justinretzolk** [comment]
Hey @sivanagireddyb 👋 We don't generally publish a table indicating what versions of providers are compatible with a given version of Terraform. I don't have official word as to why, but I _suspect_ it's because generally speaking, unless a particular provider uses a feature released in a later version of Terraform, there should be compatibility. This is discussed a bit in the [v1.0 Compatibility Promises](https://www.terraform.io/language/v1-compatibility-promises) document (though that only refers to the promises made when Terraform officially went 1.0).

That said, the specific issue you're seeing here is related to the GPG rotation I mentioned in my previous comment. The details of that may be found in the link that is output in the error message, [found here](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512). More specific information around the impact to Terraform (which covers what you're seeing here) may be found in [this post](https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570) that's linked from the aforementioned post.

**Comment by sivanagireddyb** [comment]
Hwy @justinretzolk  Understood the reason why there is no table of compatible versions ``` unless a particular provider uses a feature released in a later version of Terraform```. My point is in this case I had to run the terraform apply after updating the version(provider) and search for the error then fix it by updating terraform version. If we could have these warnings in the doc saying to update to this provider version terraform version should be x.x then we don't need to go through these debugging and multiple changes right ..! (Cleanliest way possible)
