### ISSUE TITLE
adjustment_type, cooldown and metric_aggregation_type parameters in step_scaling_policy_configuration of aws_appautoscaling_policy resource behaves differently on AWS CLI and terraform.

### ISSUE THREAD

**Issue by MayuriD89** [hashicorp/terraform-provider-aws#24411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- Terraform v0.12.31
- AWS Provider v3.70.0

### Affected Resource(s)

- aws_appautoscaling_policy

### Terraform Configuration Files

- Please refer following code, I have used same kind of configuration :

```hcl
resource "aws_appautoscaling_target" "ecs_target" {
  max_capacity       = 4
  min_capacity       = 1
  resource_id        = "service/clusterName/serviceName"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_policy" "ecs_policy" {
  name               = "scale-down"
  policy_type        = "StepScaling"
  resource_id        = aws_appautoscaling_target.ecs_target.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.ecs_target.service_namespace

  step_scaling_policy_configuration {
    adjustment_type         = "ChangeInCapacity"
    cooldown                = 60
    metric_aggregation_type = "Maximum"

    step_adjustment {
      metric_interval_upper_bound = 0
      scaling_adjustment          = -1
    }
  }
}
```

### Expected Behavior

Cooldown parameter should be required as mentioned in terraform documentation. adjustment_type and metric_aggregation_type parameter should be required from AWS CLI too but it shows different behavior.

### Actual Behavior

In terraform documentation all these parameters adjustment_type, cooldown, and metric_aggregation_type are marked as Required, Required, and Optional respectively. 

These parameters show different behavior from AWS CLI and terraform. 

1. **From AWS CLI -** 

-               All these parameters are Optional.

2. **From Terraform** - 

-            cooldown is an optional parameter (terraform document show it as Required)
-            adjustment_type is Required from terraform (terraform document show it as Required)
-            metric_aggregation_type is Required from terraform (terraform document show it as Optional)

### Steps to Reproduce

- terraform apply

**Comment by justinretzolk** [comment]
Hey @MayuriD89 👋 Thank you for taking the time to raise this! I took a look over the three arguments you mentioned and found the following information:

#### `adjustment_type`:

Looking at the [AWS CLI reference](https://docs.aws.amazon.com/cli/latest/reference/application-autoscaling/put-scaling-policy.html), it calls out that:

> `AdjustmentType` is required if you are adding a new step scaling policy configuration.

Given that with the configuration supplied, on first run you'll be adding a new step scaling policy configuration, it seems like having this value marked as required is more or less accurate, despite it being not immediately intuitive based solely on comparing the CLI behavior to Terraform's behavior.

#### `cooldown`:

This appears to be something that can be updated in the provider documentation to no longer read as required. I was able to test without using the `cooldown` argument and had no issues.

#### `metric_aggregation_type`

This appears as though it may be a bug in the provider. The AWS CLI documentation (linked under `adjustment_type`) mentions that leaving this value as `null` will default to using `Average`, which is also called out in the provider documentation. Unfortunately in my testing, removing this argument led to errors.

I'd like to leave this issue open so that we can take a deeper look into the behavior of `adjustment_type` and `metric_aggregation_type` and determine if changes need to be made to more appropriately handle the values.

**Comment by MayuriD89** [comment]
Thanks for the reply @justinretzolk ! Understood what you have explained, I am glad that you will be looking into this issue more deeply. Will wait till the issue is resolved.
