### ISSUE TITLE
aws_secretsmanager_secret_rotation missing the option to create the lambda rotator automatically

### ISSUE THREAD

**Issue by nitinsh99** [hashicorp/terraform-provider-aws#24439]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As par hashicorp hashicorp aws [provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret_rotation#rotation_lambda_arn), rotation_lambda_arn is a required field.

However, AWS UI shows the option to which creates a rotator lambda on your behalf and uses it. I don't see any such option in the terraform provider. Am I missing anything? Is this a missing feature or bug in the terraform provider?

![Screen Shot 2022-04-27 at 4 22 46 PM](https://user-images.githubusercontent.com/1389212/165626777-26d0f2fa-ab95-4e23-92fd-09b60155bc03.png)

### New or Affected Resource(s)

* aws_secretsmanager_secret_rotation
* latest version (4.11.0)

### Potential Terraform Configuration

```hcl
resource "aws_secretsmanager_secret_rotation" "example" {
  secret_id           = aws_secretsmanager_secret.example.id
  rotation_lambda_arn {
  rotator_lambda_name = "test-rotator" <--similar to UI, this should create lamba automatically 
  }

  rotation_rules {
    automatically_after_days = 30
  }
}
```

**Comment by justinretzolk** [comment]
Hey @nitinsh99 👋 Thank you for taking the time to raise this! The `aws_secretsmanager_secret_rotation` resource [uses `secretsmanager.RotateSecret`](https://github.com/hashicorp/terraform-provider-aws/blob/7ffaab8a328264f3c988f4c0f8506a19660b728a/internal/service/secretsmanager/secret_rotation.go#L75) to create the resource in AWS. That function takes a type of [`secretsmanager.RotateSecretInput`](https://docs.aws.amazon.com/sdk-for-go/api/service/secretsmanager/#RotateSecretInput), which has a `RotationLambdaARN` field, which requires a string. Unfortunately, this means that a specific ARN is required to be passed, and there doesn't appear to be support from the SDK to automatically generate a Lambda in the same way that you can do in the UI.

What this means in practice is that to achieve the same functionality, you'd need to create the Lambda function using the [`aws_lambda_function` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function) (or perhaps source one using the [`aws_lambda_function` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_function)) in order to pass the resulting ARN to `aws_secretsmanager_secret_rotation.rotation_lambda_arn`.

**Comment by Maxwe11** [comment]
`Use separate credentials to rotate this secret`

Would be nice to have TF configuration for this as well

**Comment by gdavison** [comment]
Hi @nitinsh99, as @justinretzolk mentioned, the AWS API doesn't support this option. The ability to automatically create the rotator function is a convenience that the AWS Console provides.

In the AWS Provider, we match our implementation to what the AWS API provides, and this is one of the [principles of provider development](https://developer.hashicorp.com/terraform/plugin/hashicorp-provider-design-principles#resource-and-attribute-schema-should-closely-match-the-underlying-api).

AWS provides sample rotation function templates at https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html
