### ISSUE TITLE
Create `aws_acmpca_certificate` using a `certificate_chain` and `private_key` inputs

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#24451]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS ACM PCA certs are expensive. They cost 400/mo/cert. We want to create certs per region (2 or 3 regions) without ballooning costs. We spoke with AWS Support and they suggested that we export our subordinate certificate and import it into a separate region.

We use the following command to do this

```console
aws --region us-east-2 acm export-certificate \
     --certificate-arn arn:aws:acm:region:account:certificate/certificate_ID \
     --passphrase fileb://path-to-passphrase-file  \
     | jq -r '"\(.Certificate)\(.CertificateChain)\(.PrivateKey)"'

aws --region us-west-2 acm import-certificate --certificate fileb://Certificate.pem \
      --certificate-chain fileb://CertificateChain.pem \
      --private-key fileb://PrivateKey.pem
```

It would be nice to do this in terraform

### New or Affected Resource(s)

* aws_acmpca_certificate

### Potential Terraform Configuration

```hcl
resource "aws_acmpca_certificate" "example" {
  certificate_chain = "CertificateChain.pem"
  private_key       = "PrivateKey.pem"
}
```

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate

**Comment by mattburgess** [comment]
This should already be possible according to the [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#existing-certificate-body-import). That example uses the `tls_private_key` and `tls_self_signed_cert` from the [hashicorp/tls](https://registry.terraform.io/providers/hashicorp/tls/latest/docs) provider, but you should be able to use the [file()](https://www.terraform.io/language/functions/file) function to read any key material you may have generated outside of Terraform's control.

Note that, specifically, AWS' guidance was to use `acm` to import the certs, not `acmpca` hence my suggestion that you use `aws_acm_certificate` for this purpose to mirror their suggestion. If you haven't done so already, you'll also want to take a look at https://www.terraform.io/language/state/sensitive-data#recommendations and additionally make sure wherever those private keys are held prior to Terraform getting its hands on them (e.g. source control, CI machines, etc.) they're adequately protected.

I don't think it would make sense for `aws_acmpca_certificate` to support importing certificates because then it would be housing certs that it hadn't signed. Hence why the [acmpca API](https://docs.aws.amazon.com/sdk-for-go/api/service/acmpca/#ImportCertificateAuthorityCertificateInput) doesn't support importing certificates.

I guess this really comes down to the core question of whether you have a specific need to run your own CA? If so, you're going to have a cost somewhere (either in on-prem CA management and the security thereof, or a managed service like AWS ACMPCA). Note that the $400/mo cost is _only_ for running the CA itself; the certs that the CA signs are an additional $0.75 each (but it's a one-off cost at creation time, not a monthly charge).
