### ISSUE TITLE
aws_iam_user_policy: User creation / policy attachment race condition

### ISSUE THREAD

**Issue by stmarier** [hashicorp/terraform-provider-aws#2449]
### Terraform Version
```
Terraform v0.11.0
+ provider.aws v1.3.1
+ provider.template v0.1.1
```

### Affected Resource(s)
aws_iam_user, aws_iam_user_policy, data.template_file

### Terraform Configuration Files
Unnecessary / too large or complex

### Expected Behavior
Terraform can create an IAM user and associate a policy with it.

### Actual Behavior
Terraform creates the IAM user but attempts to associate the policy immediately afterwards, user creation takes a few seconds, so the policy association fails with:
```
* aws_iam_user_policy.policy_attachment: Error putting IAM user policy {}: NoSuchEntity: The user with name {} cannot be found.
    status code: 404, request id: {}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a user with a policy applied to it
2. Terraform apply

### Important Factoids
This has been happening to us for ~4 months or so.  Some important things to note:
- These are created by a module that we call dozens of times to stamp out some boilerplate
- The module uses the `template_file` data source to drop a bunch of variables into the policy document
- Some of those variables are interpolated through `jsonencode()`

We can probably resolve this issue entirely by switching the template_file to an aws_iam_policy_document, but that would trigger changes on our end which is not great.

I imagine that this is an edge case (or else it would have been picked up by the test suite ~4 months ago), so this is mostly a FYI issue I guess.  I would suspect the edge case is related to template_file.

If there is interest here I can provide an example, but I imagine this is either trivial to repro or not worth fixing.  Thanks a bunch.

**Comment by bflad** [comment]
For reference, this bug was also offhandedly mentioned in #781.

While fixing some of the code for that issue, it looks like this resource does not have logic around retrying on `NoSuchEntity`. Given that IAM is an eventually consistent service, I think it would be prudent to add the retry logic in there.

> We can probably resolve this issue entirely by switching the template_file to an aws_iam_policy_document

Personally, I don't think anything relating to the policy itself is affecting this.

> I imagine that this is an edge case (or else it would have been picked up by the test suite ~4 months ago)

Eventual consistency issues of third party services are hard to replicate. 😄 If you happen to know of a provider release where this might have started, please let us know!

**Comment by jurajseffer** [comment]
I've seen this kind of behaviour in at least two cases:
* deleting a IAM user and trying to create it again - it fails saying it already exists even though AWS would confirm the deletion, it takes several minutes
* trying to reference a newly created IAM server certificate - again, AWS gives terraform an ARN but when using it, the certificate isn't available yet, 30 seconds wait was enough.

Given the multitude of cases, I think retrying within terraform should be implemented with an optional timeout. I got around these cases for now with
```
provisioner "local-exec" {
    command = "sleep 30"
  }
```
within the resource that is eventually consistent, e.g. IAM user, certificate etc.

**Comment by apparentlymart** [comment]
Agreed with @bflad that this smells like an "eventual consistency"-type error, which is very common with the IAM resources.

Our usual pattern to address this is to have each resource poll for a while after its creation to wait for the API to start returning the resource that was just created. This works okay for many cases, but is not always sufficient because eventually-consistent APIs do not tend to propagate atomically and so Terraform may see a successful response from _its_ polling but then see failures when the same data is accessed indirectly via other API acctions.

To solve this, we'll need to dig into what the resources are already doing here (I expect there's already _some_ attempts at polling in this area, due to how notorious these endpoints are for needing it) and figure out if some additional polling in a _different_ place could help make this work better.

**Comment by bflad** [comment]
@apparentlymart unfortunately there is no `resource.StateChangeConf`/retry logic currently in `aws_iam_user_policy`. In fact looking in its related `aws_iam_user_policy_attachment`, not seeing anything there either. I wouldn't mind adding some after #2450 is reviewed and merged.

**Comment by dlin128** [comment]
Mentioned here as well but closed on the terraform side. Was there any activity or fix anywhere else?

https://github.com/hashicorp/terraform/issues/1885
