### ISSUE TITLE
resource: aws_cloudformation_stack_set_instance

### ISSUE THREAD

**Issue by Galvin-wjw** [hashicorp/terraform-provider-aws#24520]
In the official doc:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set_instance

Actually, it must name **call_as** parameter to create stack_set instance and this doc missed it, otherwise, it returns:
`error creating CloudFormation StackSet () Instance: StackSetNotFoundException: StackSet () not found`

Referring to the AWS Cli doc:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/create-stack-instances.html

**Comment by justinretzolk** [comment]
Hey @Galvin-wjw 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
