### ISSUE TITLE
Plugin not responding while creating Lambda Functions

### ISSUE THREAD

**Issue by dubhardwaj-deloitte** [hashicorp/terraform-provider-aws#24698]
I am using terraform to create lambda function, EventBridge rules, IAM role and DynamoDB tables. It deployed all resources except lambda function. For all lambda functions, I got the below error for 'terraform apply'. I tried multiple times destroying and applying, but it was the same result each time.
````
Error: Plugin did not respond

with module.defaultSecurityGroupAcl.aws_lambda_function.lambda_function[0]
on modules/user_story/main.tf line 1, in resource "aws_lambda_function" "lambda_function":
resource "aws_lambda_function" "lambda_function" {

The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
````

Terraform -v output
```
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.12.1
```

Expected Behavior
To deploy all resources successfully

Actual Behavior
Plugin stopped responding to requests for creating lambda functions

The error message suggests to look at plugin logs, we use internally hosted terraform enterprise version. How can I find plugin logs?
Also I saw similar issue with previous versions of AWS provider ([here](https://discuss.hashicorp.com/t/terraform-aws-provider-panic-plugin-did-not-respond/23396)). I didn't saw a fix for this either. Can you please help?

**Comment by justinretzolk** [comment]
Hey @dubhardwaj-deloitte 👋 Thank you for taking the time to raise this! In order to get logs from Terraform Enterprise, you would first want to enable debug logging using the steps outlined in [this support document](https://support.hashicorp.com/hc/en-us/articles/360001113727-Enabling-debug-and-trace-run-logs-in-Terraform-CLI-Cloud-or-Enterprise). After doing so and reproducing the issue, the logs may be downloaded by navigating to the run in the Terraform Enterprise UI and clicking the "Download raw log" button.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
