### ISSUE TITLE
description support for resource = aws_fms_policy

### ISSUE THREAD

**Issue by SBB-Miguel** [hashicorp/terraform-provider-aws#24703]
### Community Note 

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add description support for aws_fms_policy

### New or Affected Resource(s)

`aws_fms_policy`

### Potential Terraform Configuration

```hcl
resource "aws_fms_policy" "example" {
  name = "example"
  description                 = "lorem ipsum"  # not supported yet. 
  delete_all_policy_resources = ... 
```

### References
[wafv2_web_acl](
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl)

```hcl
resource "aws_wafv2_web_acl" "example" {
  name        = "managed-rule-example"
  description = "Example of a managed rule." # aws_fms_policy needs to support this informational field.
  scope       = "REGIONAL"
```

**Comment by justinretzolk** [comment]
Hey @SBB-Miguel 👋 Thank you for taking the time to raise this! The `aws_fms_policy` resource uses the `fms.PutPolicy` function from the AWS Go SDK in order to create policies, the [input for which](https://docs.aws.amazon.com/sdk-for-go/api/service/fms/#PutPolicyInput) does not have a `Description` field. This can also be seen by reviewing the [documentation](https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_PutPolicy.html) for the underlying API call, which does not take a `description` input. Unfortunately, since this isn't supported by the API, we're not able to add a `description` argument to the resource. With that in mind, we'll close this issue for now, but if the underlying API changes in the future, we'd be happy to take another look!
