### ISSUE TITLE
Create new instance everytime I apply

### ISSUE THREAD

**Issue by bhargav2427** [hashicorp/terraform-provider-aws#24785]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

I have created my EC2 instance in a VPC ( which is not default ). Now every time I apply my changes it destroy instance and create new instance.

**Comment by justinretzolk** [comment]
Hey @bhargav2427 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?
