### ISSUE TITLE
delete_resource_share

### ISSUE THREAD

**Issue by Venkat-Srinivasan-23** [hashicorp/terraform-provider-aws#24850]
Hello All,

Any one please help me how to delete the "Resource Share" in the AWS via terraform.

Here I'm attaching the reference we can do by boto - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ram.html#RAM.Client.delete_resource_share

Please guide me how to do this via terraform.

Thanks in advance!!

**Comment by justinretzolk** [comment]
Hey @Venkat-Srinivasan-23 👋 Thanks for opening this issue. This forum is intended to be used for feature enhancements and bugs in the AWS Provider - so that we can maintain focus on that, we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue, but I believe you should be able to get an answer for this using one of the Community Resources (such as [the AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws) or StackOverflow).
