### ISSUE TITLE
Release 3.75.2 not available on releases.hashicorp.com

### ISSUE THREAD

**Issue by obourdon** [hashicorp/terraform-provider-aws#24901]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Subject says it all

**Comment by ewbankkit** [comment]
@obourdon Thanks for raising this issue 👏.
We hot a problem with the **v3.75.2** release yesterday - https://github.com/hashicorp/terraform-provider-aws/runs/6515664728?check_suite_focus=true - due to the migration from TeamCity to GitHub Actions for the release process: https://github.com/hashicorp/terraform-provider-aws/pull/23895.
This is addressed via https://github.com/hashicorp/terraform-provider-aws/pull/24891 and we should get the release out today.

**Comment by obourdon** [comment]
@ewbankkit thanks for the quick answer (long time no talk ;-))

I guessed something like this could have happened but as I received the email saying it was released I tried to use it in my
own environment but was unable to do so

Thanks again

**Comment by ewbankkit** [comment]
The release was "nearly there" - I think the binaries are in the registry but a missing metadata file means they won't be served.

**Comment by ewbankkit** [comment]
**v3.75.2** has been released: https://registry.terraform.io/providers/hashicorp/aws/3.75.2.
