### ISSUE TITLE
Couldn't retrieve the secret from aws secret manager using terraform

### ISSUE THREAD

**Issue by Nagendran2807** [hashicorp/terraform-provider-aws#24932]
Trying to retrieve the secret from aws secret manager using terraform

`data "aws_secretsmanager_secret" "emr" {
  name = format("certificate/%s/emr.jks", "us-east-1")
  provider = aws.secrets
}`
`data "aws_secretsmanager_secret_version" "emr" {
  secret_id = data.aws_secretsmanager_secret.emr.id
}`

`resource local_file "test" {
  content = base64decode(data.aws_secretsmanager_secret_version.emr.secret_binary)
  filename = "./new_emr.jks"
}`

Getting below error
`Call to function "base64decode" failed: failed to decode base64 data (sensitive value).`

Tried with sensitive function but same issue

Expectation: 
Retrieve the secret from secret manager

Note: Able to retrieve the secret using aws cli commana
`aws secretsmanager get-secret-value --profile qa --region us-west-1 --secret-id certificate/us-east-1/emr.jks --query SecretBinary | base64 --decode > ./emr.jks`

**Comment by justinretzolk** [comment]
Hey @Nagendran2807 👋 Thank you for taking the time to raise this! I did a bit of reproduction and found that the documentation for the `aws_secretsmanager_secret_version` data source appears to be incorrect. The `secret_binary` appears to _not_ be Base64 encoded, which is why the call to `base64decode` is failing. I'll look into this a bit more and work on a documentation update, but wanted to give you an update here to hopefully unblock you. Here's my reproduction and the resulting file:

Reproduction configuration:

```hcl
resource "random_password" "pw" {
  length = 15
}

resource "aws_secretsmanager_secret" "secret" {
  name = "jretzolk-test-secret"
}

resource "aws_secretsmanager_secret_version" "version" {
  secret_id     = aws_secretsmanager_secret.secret.id
  secret_binary = base64encode(random_password.pw.result)
}

data "aws_secretsmanager_secret_version" "dataversion" {
  secret_id  = aws_secretsmanager_secret.secret.id
  version_id = aws_secretsmanager_secret_version.version.version_id
}

resource "local_file" "file" {
  filename = "testfile.txt"
  content  = "from_datasource: ${data.aws_secretsmanager_secret_version.dataversion.secret_binary}\nfrom_random_password: ${random_password.pw.result}"
}
```

Contents of output file:

```plaintext
from_datasource: {Ybt<du-n?-@rBm
from_random_password: {Ybt<du-n?-@rBm
```

**Comment by Nagendran2807** [comment]
Thanks @justinretzolk... In my case, I used below command to create the secret

create the secret:
`aws secretsmanager create-secret --name certificate/us-east-1/emr-server.jks --secret-binary fileb://emr-server.jks --profile qa --region us-west-1`

Retrieve the secret:
aws secretsmanager get-secret-value --profile qa --region us-west-1 --secret-id certificate/us-east-1/emr-server.jks --query SecretBinary | base64 --decode > ./test1.jks

Want to retrieve the secret atleast using terraform

**Comment by Nagendran2807** [comment]
Able to retrieve the secret using terraform but when comes to retrieve the jks file from secret manager using terraform getting failed

**Comment by justinretzolk** [comment]
Hey @Nagendran2807 👋 Apologies for the accidental closure there. I've reopened the issue so we can keep looking into this. So that we have all of the necessary information in order to look into this further, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?
