### ISSUE TITLE
Documentation issue: Data Source aws_subnet exported attribute missing

### ISSUE THREAD

**Issue by jjgalleg** [hashicorp/terraform-provider-aws#24940]
According to the Example Usage, it is clear Data Source aws_subnet returns the vpc_id attribute, however the list of exported attributes doesn't mention it.

Thanks!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @jjgalleg 👋 Thank you for taking the time to raise this! In this case, `vpc_id` is listed as an argument, which is why it's not in the attributes section (which states: "In addition to the attributes above, the following attributes are exported:").

Since this won't require any further action, I'll close this issue. If you feel I've done this in error, please do let me know!
