### ISSUE TITLE
DB option groups failed with error "Error creating DB Option Group: InvalidParameterValue: Cannot create more than 20 option groups".

### ISSUE THREAD

**Issue by raobilalkhalid** [hashicorp/terraform-provider-aws#25025]
Hi while creating db option group got the following error

- Error creating DB Option Group: InvalidParameterValue: Cannot create more than 20 option groups

```
variable env {
  type    = string
  default = "kc"
}

variable region {
  type    = string
  default = "eu-west-2"
}

variable engine {
  type    = string
  default = "sqlserver-ex"
}

variable major_engine_version{
  type = string
  default = "14.00"
}

variable engineVersion {
  type    = string
  default = "14.00.3281.6.v1"
}

variable dbInstance {
  type    = string
  default = "db.t3.small"
}
```

```
resource "aws_db_option_group" "sql-server-options" {
  name = "tt${var.env}-option"
  option_group_description = "SQL Server backup options"
  engine_name              =  "${var.engine}"
  major_engine_version     = "${var.major_engine_version}"
  option {
    option_name = "SQLSERVER_BACKUP_RESTORE"
      option_settings {
        name = "IAM_ROLE_ARN"
        value = "${aws_iam_role.rds_add_to_db.arn}"
      }
  }
}
```
here is the screenshot of error
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/41730250/170209624-fb043c26-f201-4e72-ba4f-f1988845ee94.png)

**Comment by justinretzolk** [comment]
Hey @raobilalkhalid 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?
