### ISSUE TITLE
Elastic search node to node encryption 

### ISSUE THREAD

**Issue by Mdeshmukh93** [hashicorp/terraform-provider-aws#25026]
Hi,

   we are performing ES node to node encryption via terraform but when we run terragrunt plan it is recreating whole ES domain.
but as per terraform document (ref-1)
any ES cluster version  greater than 6.7, it should not re-create  domain.need your assistance on how to proceed further.

here is the domain its been re-creating  entirely

`-/+ resource "aws_elasticsearch_domain" "this" {
      ~ arn                   = "arn:aws:es:us-west-2:897****7:domain/prod-ce-elk" -> (known after apply)
      ~ domain_id             = "89****47/prod-ce-elk" -> (known after apply)
      ~ endpoint              = "vpc-prod-ce-elk-yh*********kq.us-west-2.es.amazonaws.com" -> (known after apply)
      ~ id                    = "arn:aws:es:us-west-2:89*******47:domain/prod-ce-elk" -> (known after apply)
      ~ kibana_endpoint       = "vpc-prod-ce-elk-yh**********kq.us-west-2.es.amazonaws.com/_plugin/kibana/" -> (known after apply)
        tags                  = {
            "CostCenter"        = "207"
            "Data"              = "Confidential"
            "Environment"       = "prod-ce"
            "Stack"             = "prod-ce"
            "terraform_managed" = "true"
        
 ~ node_to_node_encryption {
          ~ enabled = false -> true # forces replacement
        }
}`

Note: we have Elastic search/open search  version 7.7 running  

ref1:https://urldefense.com/v3/__https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain*node_to_node_encryption__;Iw!!BHlfX_zbyOAjqHI!0FiwyGhdMXwpB8b1MOp1M9OEZua8WpDiaSEt7x7mixFxxPS6TvM3PVMeWi7PW4l4mlmnJMILXXIiFm9MHn8_TwPo-h12v14bzjI$

**Comment by justinretzolk** [comment]
Hey @Mdeshmukh93 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by RITESHBRID** [comment]
The mentioned issue has been fixed in provider version 4.11

**Comment by justinretzolk** [comment]
Hey @Mdeshmukh93 👋 As mentioned above, it looks like this was fixed with AWS Provider version `4.11` (changelog can be found [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4110-april-22-2022)). Given that's the case, we'll close this issue. If you feel we've done this in error, please do let me know.
