### ISSUE TITLE
Add option to specify a KMS key for root_block_device in launch_configuration

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/terraform-provider-aws#25069]
The `root_block_device` property in the [EC2 launch configuration](https://registry.terraform.io/providers/hashicorp/aws/2.59.0/docs/resources/launch_configuration) does not allow a custom KMS key. 

I need to encrypt the root volume with my own KMS key. Any workarounds?

**Comment by justinretzolk** [comment]
Hey @paololazzari 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md?plain=1)?
