### ISSUE TITLE
use the proper data structure for secure data

### ISSUE THREAD

**Issue by jason-easterday** [hashicorp/terraform-provider-aws#25121]
Hello, thanks for the report!

In short, we do not consider this to be a security issue. Protecting against memory analysis of a running Terraform process or provider is outside of Terraform's threat model. If an attacker is able to inspect the memory state of a running Terraform process then the confidentiality of data may be compromised, Terraform does not attempt to defend against this particular threat.

The ability to access Terraform's process memory implies that the attacker is already in a highly privileged position. In this position, there would be multiple avenues for accessing sensitive data, variables, or configuration. We recommend only running Terraform in an environment where you are confident about the security of the underlying host.

_Originally posted by @eastebry in https://github.com/hashicorp/terraform-provider-aws/issues/24794#issuecomment-1142409403_

That's a terrible way to think of it. Mishandling data in code is absolutely the position of the programmer to fix it. Access to the memory location doesn't have to be granted by the terraform admin, example, if another process is running on the machine say, java, and someone doesn't patch/fix a java vulnerability, it grants access to the terraform application from another program... USE THE PROPER data structures. there is a reason why they exists, and there's reasons why other programming languages protect against it.

**Comment by eastebry** [comment]
Hey @a108439 - it seems like you are a bit frustrated with our response. My apologies, I didn't mean to come off as terse or apathetic. Let me explain our position in a little more detail, to hopefully ease your concerns.

First let's start with the high level. All our products take the same stance regarding process memory - protecting against attackers with the ability to read memory is explicitly outside our threat model (Vault, for example, explicitly states this in its [security model](https://www.vaultproject.io/docs/internals/security)). If an attacker is able to read Terraform's process state, they are in highly privileged position and could likely accomplish the same or similar objective in a number of other ways - read the same secrets from `/proc/*/environ`, read secrets from the Terraform statefile, read or modify the Terraform configuration, etc. Rather than introducing a false sense of security by attempting to defend against these threats we prefer to draw a clear boundary - Terraform (and Vault, Packer, Consul, Nomad) can not ensure the security of its data if the underlying host is compromised.

Zooming into this specific case, I'm curious what you data structure you would recommend we use instead of string? Perhaps you are a C# programmer, and are looking for something equivalent to a [securestring](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-6.0)? To my knowledge, there is no first party equivalent of this on Go. Because Golang manages its own memory, we aren't able to tightly control when the string is held and released from memory. Even if we used a different data type, its all a moot point because the underlying SDK also uses strings for storing secret keys. https://github.com/aws/aws-sdk-go-v2/blob/main/aws/credentials.go#L78

**Comment by eastebry** [comment]
Hey @a108439, seems like you are a bit frustrated by our response. My apologies, I didn't mean to sound terse or apathetic. Let me explain our stance in more detail, to hopefully address your concerns. 

First starting at a high level, our products all have the same stance regarding process memory - access to memory is explicitly outside the threat model (Vault, for example, explains this in its [security model](https://www.vaultproject.io/docs/internals/security)). An attacker with the ability to access the Terraform processes' memory would be in a highly privileged position, and could access sensitive data in a number of ways (reading environment variables out of /proc, reading data out of the terraform state file, etc). It's not possible for Terraform to defend against all threats from  an attacker in this position.

Diving into the specifics of this issue, I'm curious what alternative data structure you are recommending? Are you thinking of something analogous to C#'s [securestring](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-6.0)? To my knowledge, there isn't an equivalent in Golang. Even if we store the secret in something mutable and overwrote it as soon as possible, its a moot point because the underlying SDK stores this secret as a string: https://github.com/aws/aws-sdk-go-v2/blob/cbd1bab25397591da5983f6a598df23a8daa67c6/aws/credentials.go#L78

**Comment by eastebry** [comment]
Hey @a108439 , let me explain our reasoning in a little more detail to hopefully ease your concerns.

First, starting with the high level. All of our products have the same stance regarding the security of sensitive in-memory data: protecting against memory analysis is explicitly outside the threat model (Vault, for example, explains this in its [security model document](https://www.vaultproject.io/docs/internals/security)). An attacker who can inspect the Terraform processes’ memory is already in a highly privileged position, and would have multiple avenues for accessing sensitive data provided to Terraform (reading it from the statefile, dumping environment variables, modifying TF config, etc.). Attempting to defend against memory analysis requires introducing a lot of complexity to our software, and (especially in a language like Go where we are not explicitly managing memory) provides marginal protection at best.

Zooming into this specific case, I’m curious what alternative data structure you are recommending? Perhaps you are looking for something like C#’s [securestring](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-6.0)? To my knowledge, there are no first party equivalents to this library in Golang. Even if we were to store the value in a mutable object and overwrite it when we are finished, it’s a moot point because the underlying SDK also uses a string for holding credentials: https://github.com/aws/aws-sdk-go-v2/blob/cbd1bab25397591da5983f6a598df23a8daa67c6/aws/credentials.go#L78.

Hopefully this clarifies our thinking.. please let us know if we've misunderstood your concerns!
