### ISSUE TITLE
aws_vpc_ipv6_cidr_block_association only accepts IPAM pool

### ISSUE THREAD

**Issue by sanjeevgopal** [hashicorp/terraform-provider-aws#25136]
aws_vpc_ipv6_cidr_block_association only accepts IPAM pool, whereas via the console/CLI, one can request an Amazon provided block. Allows import though, with `ipv6_ipam_pool_id = ""`

**Comment by justinretzolk** [comment]
Hey @sanjeevgopal 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md?plain=1)?
