### ISSUE TITLE
Support for advanced features for Amazon DynamoDB backups

### ISSUE THREAD

**Issue by anik3t** [hashicorp/terraform-provider-aws#25150]
### Description

Currently we dont have an option to enable [Advanced Feature for Dynamodb backups](https://docs.aws.amazon.com/aws-backup/latest/devguide/advanced-ddb-backup.html?icmpid=docs_console_unmapped).
We are looking forward to have this feature to be able to use cold storage tiering & cost allocation tags enabled.
Problem is with on-demand backup of dynamodb as they are non-incremental & the size of the backup keeps on increasing as on production.
I neither find this feature in [aws_backup_plan](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_plan) resource & nor in [aws_dynamodb_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table) 

### New or Affected Resource(s)

* aws_backup_plan

**Comment by justinretzolk** [comment]
Hey @anik3t 👋 Thank you for taking the time to raise this! I took a look around and I believe the functionality that you're looking for exists in the provider today.

In order to set up cold storage tiering, you'd want to configure the [`aws_backup_plan.rule.lifecycle`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_plan#lifecycle-arguments) block.

As far as cost allocation tags, based on the [AWS document](https://aws.amazon.com/blogs/database/announcing-tagging-for-amazon-dynamodb/) around cost allocation tags for DynamoDB, you'd just need to add [tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#tags) to the DynamoDB resource and then set up user defined cost allocation tags.

Can you verify whether these features accomplish what you're looking to do?

**Comment by tommoyang** [comment]
If I understand correctly, this is not the act of configuring the cold storage tiering and cost allocation tags (which as you correctly pointed out already exists), but enabling them for DynamoDB to begin with. Specifically for DynamoDB there are advanced features that need to be enabled (per backup configuration for a single account) to have them working: https://docs.aws.amazon.com/aws-backup/latest/devguide/advanced-ddb-backup.html?icmpid=docs_console_unmapped

This issue also means Advanced Backup needs to be manually enabled to allow for cross-region cross-account copy, which while policies can be set in various places they won't actually work - the copy jobs simply fail with a "can't be done" message, and you can't manually copy via Backup nor DynamoDB

Hopefully that helps clarify the issue. I ran into this today too and would love to avoid having to manually enable this for individual accounts we need backups for.

**Comment by ankon** [comment]
Would this be covered by https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_region_settings ?

**Comment by tommoyang** [comment]
I had the chance to come back to test this issue - turns out it is, thanks for the pointer @ankon ! Specifically setting `resource_type_management_preference` for `DynamoDB` corresponds to the Advanced features for DynamoDB Backups, which I didn't realise until I looked up the corresponding parameter in the AWS API docs: https://docs.aws.amazon.com/aws-backup/latest/devguide/API_UpdateRegionSettings.html#API_UpdateRegionSettings_RequestSyntax

I think it would be nice to get a mirror/pointer to this in the Terraform docs, since they're so barebones

**Comment by jrkarnes** [comment]
As @tommoyang said in his previous post:

> I think it would be nice to get a mirror/pointer to this in the Terraform docs, since they're so barebones

I would like to second this. I've had a blocker up for months thinking that this feature wasn't supported only to find out that it _is_.

:+1: for documentation updates.
