### ISSUE TITLE
Data source aws_launch_configuration causing failure when upgrade aws provider version from 4.16.0 to 4.17.0

### ISSUE THREAD

**Issue by ronronshaiko** [hashicorp/terraform-provider-aws#25204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

aws provider version 4.17.0

### Affected Resource(s)

* aws_launch_configuration data source

### Description

When upgrading aws provider version from 4.16.0 to 4.17.0, an existing data source `aws_launch_configuration` causing terraform to fail on `terraform plan`

### Expected Behavior

In our terraform code there were no changes, so the expected behavior should be no changes in terraform plan.

### Actual Behavior

When upgrading the version from 4.16.0 to 4.17.0 the plan is failing: 
```
╷
│ Error: .root_block_device[0].throughput: number is required
│ 
│ 
╵
╷
│ Error: .root_block_device[0].throughput: number is required
│ 
```
What we suspect that happens, is that in the existing state file the `root_block_device` has an attribute `"throughput": false`, but it was changed in the new release and the provider expects to integer and not bool.

You can see here the full `root_block_device` block from the state:

```
            "root_block_device": [
              {
                "delete_on_termination": true,
                "encrypted": false,
                "iops": 0,
                "throughput": false,
                "volume_size": 125,
                "volume_type": "gp2"
              }
            ],
```

### Steps to Reproduce

1. set workspace provider to 4.16.0
2. add `aws_launch_configuration` data source 
3. `terraform apply`
4. upgrade aws provider version from 4.16.0 to 4.17.0 
5. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @ronronshaiko 👋 Thank you for taking the time to raise this! This was an intentional change that is mentioned in the [changelog for `v4.17.0`](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4170-june--3-2022), as the data type for `root_block_devices.throughput` was previously incorrectly set to a `bool`, whereas the API requires an `integer`. In order to correct the errors, you will need to update the configuration accordingly.

Since this was an intended change, we'll close this issue. If you feel we've done this in error, please do let me know.
