### ISSUE TITLE
v1.2.2 destroys aws_route53_zone when it shouldn't

### ISSUE THREAD

**Issue by igor-borisoglebski** [hashicorp/terraform-provider-aws#25223]
### Terraform CLI and Terraform AWS Provider Version

com.hashicorp.terraform.version=1.2.2

* aws_route53_record or aws_route53_zone

### Terraform Configuration Files

```
data "aws_route53_zone" "selected" {
  name         = "somealreadyexistingzone.com"
  private_zone = false
}

resource "aws_route53_record" "record1" {
  zone_id = data.aws_route53_zone.selected.zone_id
  name    = "anewsubdomain"
  type    = "A"
  ttl     = "300"
  records = ["8.8.8.8"]
}
```

### Expected Behavior

A record to be created and zone not to be destroyed

### Actual Behavior

A record is created and zone is destroyed  _# (because aws_route53_zone.domain is not in configuration)_

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This is not the behavior seen with terraform v1.2.1 or v1.2.0 (just tested). With any of these versions, the a record is created and the zone is not destroyed.

**Comment by justinretzolk** [comment]
Hey @igor-borisoglebski 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by igor-borisoglebski** [comment]
Can't reproduce with 

Terraform v1.2.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.17.1
