### ISSUE TITLE
Unable to import aws managed prefix lists as max_entries cannot be updated.

### ISSUE THREAD

**Issue by vipulparashar** [hashicorp/terraform-provider-aws#25235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform_version = 0.14.7

| Name | Version |
|------|---------|
| <a name="provider_aws"></a> [aws](#provider\_aws) | 4.16.0 |

### Affected Resource(s)

* aws_ec2_managed_prefix_list

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

resource "aws_ec2_managed_prefix_list" "s3_prefix" {

  name           = var.s3_prefix_list_name
  address_family = "ipv4"
  max_entries    = length(var.s3_prefix_list_cidr_block)
}

Plan output -

  ~ resource "aws_ec2_managed_prefix_list" "cdn_prefix" {
        id             = "pl-********"
      **~ max_entries    = 0 -> 44**
        name           = "com.amazonaws.global.cloudfront.origin-facing"
        tags           = {}
        # (5 unchanged attributes hidden)

        # (44 unchanged blocks hidden)
    }

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: error updating EC2 Managed Prefix List (pl-****): UnsupportedOperation: The action is not supported for an AWS-managed prefix list.
	status code: 400, request id: ******-***-****-****-*********

  on ../../../modules/vpc/main.tf line 147, in resource "aws_ec2_managed_prefix_list" "s3_prefix":
 147: resource "aws_ec2_managed_prefix_list" "s3_prefix" {

### Expected Behavior

Argument **max_entries** should be optional, As it's been managed by aws & We cannot import If the value of max_entries are changing while importing the resource.

This resource was manually created & while creating it, The user did not provide any vale for max_entry. When we try to import this resource, We have to provide max_entry argument as it is required. In my case the value of max_entry is null in the aws console, But while importing it, I am unable to provide any null value as it throws an error.

<img width="1218" alt="Screenshot 2022-06-08 at 2 33 46 PM" src="https://user-images.githubusercontent.com/11701865/172578827-8281a37a-41b0-4a6f-b897-601db152eeab.png">

### Actual Behavior

Terraform was updating the value of max_entries.

### Steps to Reproduce

Add an aws_ec2_managed_prefix_list and then try to import it - terraform import aws_ec2_managed_prefix_list.default prefix_list_id

1. `terraform apply`
### References

* #0000

**Comment by vipulparashar** [comment]
I also tried to provide *null* value to the argument, It also fails.

Error: Incorrect attribute value type

  on ../../../modules/vpc/main.tf line 151, in resource "aws_ec2_managed_prefix_list" "s3_prefix":
 151:   max_entries    = "null"

Inappropriate value for attribute "max_entries": a number is required

**Comment by vipulparashar** [comment]
@justinretzolk What's the ETA on this, I'm asking this question as we have a dependency to import this in our tf. If not, Do we have a workaround.

**Comment by justinretzolk** [comment]
Hey @vipulparashar 👋 Thank you for checking in on this. Unfortunately, I'm not able to provide an estimate on when this will be looked into due to the potential of shifting priorities (we prioritize work by count of ":+1:" reactions, as well as a few other things). For more information on how we prioritize, check out out [prioritization guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/prioritization.md).

That said, I took a brief glance over your initial issue report, and it looks like you're using an [AWS-managed prefix list](https://docs.aws.amazon.com/vpc/latest/userguide/working-with-aws-managed-prefix-lists.html#use-aws-managed-prefix-list) rather than a [customer-managed prefix list](https://docs.aws.amazon.com/vpc/latest/userguide/working-with-managed-prefix-lists.html). Given that's the case, you aren't going to be able to "create" this managed prefix list (since it's already created and managed by AWS), as called out in the linked AWS-managed prefix list document: 

> AWS-managed prefix lists are created and maintained by AWS and can be used by anyone with an AWS account. You cannot create, modify, share, or delete an AWS-managed prefix list.

Instead, you can use the [`aws_ec2_managed_prefix_list` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_managed_prefix_list) to retrieve information about this AWS-managed prefix list.

**Comment by vipulparashar** [comment]
thank you for your reply @justinretzolk - I'm trying to import this resource into our terraform code which is already available in our aws account.

**Comment by drewmullen** [comment]
the prefix list youre attempting to `import` is managed by AWS and cannot be modified except for tags. These are fundamentally different resources than the customer-managed prefix lists and should possibly be entirely new resources if there is value in having terraform manage them (again, you can only update tags to the aws managed prefix list)

**Comment by kevindashton** [comment]
related to #26639

**Comment by drewmullen** [comment]
@kevindashton does import issue occur on customer-managed prefix lists? The issue example is an _aws-managed_ prefix lists and thus i suspect the issues (and solutions) are different if you're also unable to import a **customer** managed prefix list

**Comment by kevindashton** [comment]
> @kevindashton does import issue occur on customer-managed prefix lists? The issue example is an _aws-managed_ prefix lists and thus i suspect the issues (and solutions) are different if you're also unable to import a **customer** managed prefix list

Ah, I see.  I was confused by the title as the customer-defined resources are actually called "Managed Prefix Lists".  I'll test on the import side, but I suspect it might not run into the same error if the `aws_ec2_managed_prefix_list` resource hasn't been created yet.  I'd agree with your earlier comment that an AWS Managed resource shouldn't be imported into your Terraform state to begin as they cannot be modified by AWS customers.  If the intention was to refer to the AWS managed resource's properties, the [aws_ec2_managed_prefix_list Data Source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_managed_prefix_list) should be used instead.

**Comment by drewmullen** [comment]
Np. I suspect import is working on customer-managed, theres actually a acceptance test for it:

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/vpc_managed_prefix_list_test.go#L44-L48

If your testing finds something else, please lmk!

**Comment by drewmullen** [comment]
The initial post was regarding attempting to import a non- user managed prefix list. That is not supported because the resource is default in an account by the AWS service itself.

if you have a need to import the aws managed prefix lists that are created by the service (ex: `com.amazonaws.us-east-1.dynamodb`) then please open another issue for an enhancement. I believe thats not a useful feature because the only valid action on AWS managed prefix list is `{Create,Delete}Tags`
