### ISSUE TITLE
IPAM Data Source issues

### ISSUE THREAD

**Issue by erkwish** [hashicorp/terraform-provider-aws#25248]
Terraform v1.2.2
hashicorp/aws v4.17.1

aws_data.aws_vpc_ipam_pool

data "aws_vpc_ipam_pool" "pooleu-west-2" {
  filter {
    name = "arn"
    values = ["some-arn-to-a-pool"]
  }
  filter {
    name = "address_family"
    values = ["ipv4"]
  }
}

### Debug Output

Error: InvalidFilter: The filter 'address_family' is invalid

### Expected Behavior

Should filter the data based on the address_family

### Actual Behavior

Throwing Error seen above

### Steps to Reproduce

1. Set up a ipam pool
2. load the data with a data source and try to filter on most of the attributes

I have only mange to filter on locale and tags.

**Comment by justinretzolk** [comment]
Hey @erkwish 👋 Thank you for taking the time to raise this! I took a quick look over the `aws_vpc_ipam_pool` data source documentation, and it looks like the filter name is `address-family` rather than `address_family`. Can you verify that that filter name works for you?

**Comment by erkwish** [comment]
Hi, yes it works with address-family. I see that I haven't been on the latest version for the IPAM pool data source page. But it's still little weird the this page https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc_ipam_pool have `address-family` stated in the fileter example and `address_family` under the attribute section. And I get the the same kin of error when i try to filter in `arn`.

I am new to TF so I may have miss understand something, but how I read the docs all attribute should be able to use in the filter for the data source. And why is the example using a dash instead of a underline?

**Comment by justinretzolk** [comment]
Hey @erkwish 👋 The difference in use for `-` vs `_` is related to what those two values are used for. In the example, `address-family` is passed to the `filter` block because that is what the AWS API expects, and what you specify in the `filter` block is what gets passed directly to the underlying API.

The attribute, on the other hand, is entirely on the Terraform side. Terraform is opinionated in how these attributes should be named (if you're interested, this is discussed in the [provider development docs](https://www.terraform.io/plugin/sdkv2/best-practices/naming#attribute-names)), so rather than using `address-family`, it gets named to `address_family`. When the API responds with data around the resource(s) that you're defining, the response gets parsed and translated to the Terraform values.

I hope that helps clear up some of the confusion. I'd be more than happy to answer any additional questions you might have! I know you mentioned something about having issues with the `arn` filter as well -- were you able to sort that out?
