### ISSUE TITLE
4.17.0 broke public subnets in eks

### ISSUE THREAD

**Issue by MatthewFagan** [hashicorp/terraform-provider-aws#25252]
You incorporated a change 6 days ago. It breaks public subnet handling. We have spent the last week tearing our hair out trying to understand why our eks nodes no longer join the eks cluster. Despite the nodes being created in a public subnet, the new change stops them from getting a public ip. This will affect anyone using the terraform-aws-modules/eks/aws, at a minimum.

**Comment by justinretzolk** [comment]
Hey @MatthewFagan 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by dghubble** [comment]
This is the same as https://github.com/hashicorp/terraform-provider-aws/issues/25244

**Comment by MatthewFagan** [comment]
We fixed by pinning all of our versions to 4.16.0

The problem is this change: https://github.com/hashicorp/terraform-provider-aws/pull/17695

I can see the reason for the change, but it is a breaking change
