### ISSUE TITLE
aws_efs_mount_target datasource doesn't list mount targets based on filesystem id 

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#2525]
Hi Team,

I trying to add mount target to a efs filesystem which would already already exists in certain cases. Terraform fails with an error throwing mount target already exists in the AZ which is expected. So I decided to list all the mount-targets for a filesystem and decide to create mount targets based on the results but there is no option right now to query all mount targets based on filesystem id using aws_efs_mount_target datasource. This datasources only take mount-target id as input.

Enhancing the aws_efs_mount_target to query based on filesystem-id would be a great help.

Error Snip : 

 aws_efs_mount_target.efs-targets.2: MountTargetConflict: mount target already exists in this AZ
	status code: 409

WorkAround : 

I am trying to workaround by creating a null resource with local-exec provisioner which will use aws cli to query to the mount-targets based on fs-id but obviously not straight forward one .

Thanks
Magesh

**Comment by mengesb** [comment]
I imagine the root of this would be to expose the `mount_target_ids` from the `aws_efs_file_system` data source.

Additionally, @mashanm , is there a reason you cannot use the result of `aws_efs_file_system.<id>.dns_name` as your target mount point or do you require an actual IP (which you could of course also work around with an `/etc/hosts` entry too) - because while it would be nice to get direct access to the mount target... then you'd also properly want to have filters so that you're likely mounting within-AZ instead of across AZ. The DNS name solves for this...

**Comment by mashanm** [comment]
@mengesb I agree that exposing the mount_target_ids from the aws_efs_file_system data source would solve it .  

I use the dns_name to mount it in the instances. But we would need to create mount targets to have network access to the efs filesystem. We dont currently have a way to list all the mount targets for a EFS. Without getting this list, If I go ahead and create a mount target for my subnets to this EFS , the script fails  if the mount targets already exists. 

It would be great to expose the mount target ids from aws_efs_file_system data source and this would solve this problem .

**Comment by apparentlymart** [comment]
Hi @mashanm! Thanks for sharing this use-case.

In general Terraform does not support use-cases like "either use an existing resource or create it if it does not exist", and we generally advise against such usage because it can obscure the intent of some configuration.

Instead a more common pattern is to split infrastructure across multiple configurations so that each resource is explicitly managed by one configuration and then other configurations may access that resource (which is, in this case, _required_ to already exist) using data sources or explicit input variables.

If there are two use-cases with different needs -- such as a production environment where certain elements are managed centrally and multiple dev environments that each have their own local resources -- then this can be achieved by factoring the different parts into re-usable modules and then creating a number of separate configurations that instantiate those resources _separately_ for production, and then a single configuration that instantiates the resources _all together_ for development. This dependency-injection-style usage leads to modules that expect to be provided with the ids of other resources but don't concern themselves with how those resources got created and who else is using them.

With all of that said, if the mount target ids are logically a property of an EFS filesystem and are available to that data source then there's no reason why we wouldn't want to export them, and if that solves your problem then great! Your conditional-creation approach is not what I would recommend in the general case, but some situations warrant unusual approaches.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by ankitosh** [comment]
+1!

**Comment by anupash147** [comment]
i observed that if you have 3 regions and machines in only 2 the mount point gives the error "mMountTargetConflict: mount target already exists in this AZ
	status code: 409, request id:"  but as soon as i am able to create single machine per AZ the error never comes. Conclusion the error becomes reproducible if all machines are there in AZ. This is simply wrong.
