### ISSUE TITLE
AWS network firewall: Ability to attach a firewall rule group to a firewall policy within the same resource

### ISSUE THREAD

**Issue by ramramhariram** [hashicorp/terraform-provider-aws#25351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Primary feature request - For AWS network firewall provider, need the ability to attach a firewall rule group to a firewall policy within the same resource. For example, while using TF to create a firewall rule group (stateful or stateless), include an option to provide the firewall policy ID to which this firewall group needs to be attached

### New or Affected Resource(s)

Resource: aws_networkfirewall_firewall_policy
Resource: aws_networkfirewall_rule_group

### Potential Terraform Configuration

Option to specify firewall policy ID in the firewall rule_group resource as follows - 

```
resource "aws_networkfirewall_rule_group" "sful-http" {
  capacity = 1000
  name     = "sful-http"
  type     = "STATEFUL"
  rule_group {
    rules_source {
      stateful_rule {
        action = "PASS"
        header {
          destination      = "ANY"
          destination_port = "80"
          direction        = "FORWARD"
          protocol         = "TCP"
          source           = "ANY"
          source_port      = "ANY"
        }
        rule_option {
          keyword = "sid:2"
        }
      }
    }
  }
  firewall_policy_arn = aws_networkfirewall_firewall_policy.hcp-nia-fw-policy.arn
}
```

### References

An existing example is when creating a security group rule, we have the option to specify the security group id. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#example-usage

**Comment by justinretzolk** [comment]
Hey @ramramhariram 👋 Thank you for taking the time to raise this! Looking at the `aws_security_group_rule` resource, the underlying API is set up a bit differently, which is why that resource is able to associate to a specific group ID within the same resource.

To elaborate on that a bit, `aws_security_group_rule` uses either [`ec2.AuthorizeSecurityGroupIngress`](https://github.com/hashicorp/terraform-provider-aws/blob/6e72b85e86fb693a36110081360340205bf04706/internal/service/ec2/vpc_security_group_rule.go#L198) or [`ec2.AuthorizeSecurityGroupEgress`](https://github.com/hashicorp/terraform-provider-aws/blob/6e72b85e86fb693a36110081360340205bf04706/internal/service/ec2/vpc_security_group_rule.go#L209), (depending on the configuration) to configure rules on the security group. I'll focus on `ec2.AuthorizeSecurityGroupEgress` from here on out for the sake of brevity.

`ec2.AuthorizeSecurityGroupEgress` takes an [`ec2.AuthorizeSecurityGroupEgressInput`](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#AuthorizeSecurityGroupEgressInput), which has a field called `GroupId` for passing the Security Group ID. This is what allows Terraform to have the `security_group_id` argument for the `aws_security_group_rule` resource.

Looking at the `aws_networkfirewall_rule_group` on the other hand, it uses [`networkfirewall.CreateRuleGroupWithContext`](https://github.com/hashicorp/terraform-provider-aws/blob/6e72b85e86fb693a36110081360340205bf04706/internal/service/networkfirewall/rule_group.go#L442) to create the resource. This function takes a [`networkfirewall.CreateRuleGroupInput`](https://docs.aws.amazon.com/sdk-for-go/api/service/networkfirewall/#CreateRuleGroupInput) type, which does _not_ have a field for specifying a policy ID to associate the rule group with. Unfortunately, this means that it's not currently possible to modify the `aws_networkfirewall_rule_group` resource to have a `firewall_policy_arn` argument, as you've requested here.

If the `aws_networkfirewall_firewall_policy` is being created outside of Terraform, one option would be to define the configuration for the `aws_networkfirewall_firewall_policy` that you're looking to associate the rule group with, [import it](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_firewall_policy#import), and then update the configuration to include the reference to the `aws_networkfirewall_rule_group` that you're looking to associate with it.

I realize this is not the answer you're looking for, but unfortunately, the underlying API does not currently allow us to achieve that functionality. With that in mind, we'll close this issue, but if there are changes to the underlying API in the future, we'd be happy to take another look.
