### ISSUE TITLE
Glue Streaming Job timeout = null not working

### ISSUE THREAD

**Issue by SkylarLNH** [hashicorp/terraform-provider-aws#25442]
Hi, I am trying to set up an continuously running Glue streaming job by setting timeout = null. However, TF automatically assigns the default value of 2880 min to the job. What would be the best solution to this issue?

I noticed that from another issue topic: https://github.com/hashicorp/terraform-provider-aws/issues/16797
The newer release of Terraform AWS Provider removed timeout default value, would updating my TF AWS Provider version be the right/only solution? If so, I am worrying it might affect the current TF for my pipeline since we are using TF 3.x version. Is there a solution that does not require me to change the version? Thank you!

**Comment by justinretzolk** [comment]
Hey @SkylarLNH 👋 Thank you for taking the time to raise this! The reason that Terraform is setting the default value of `2880` in this case is because setting a `null` value is functionally equivalent to not setting the argument at all (more information in the [types and values documentation](https://www.terraform.io/language/expressions/types#null)), and so the default value is used.

Unfortunately, in your case, this will mean that in order to support the streaming job type, you'll need to use at least version `4.4.0` of the provider. Alternatively, if it's workable, you could break the definition of this resource out into a separate configuration that uses at least version `4.4.0` of the provider, so that you don't have to go through the migration process to upgrade the rest of your configuration to use `v4`.

**Comment by michel-98** [comment]
Hi @justinretzolk,
I'm using as provider hashicorp/aws v4.53.0, but it doesn't work, my aws_glue module is like this:

resource "aws_glue_job" "glue_job" {
  name              = local.job_name
  description       = var.description
  role_arn          = aws_iam_role.glue_job_role.arn
  max_capacity      = var.worker_type == "Standard" ? var.dpu : null
  max_retries       = var.max_retries
  **timeout           = var.timeout == "" ? null : var.timeout**
...
}
But with timeout = null, it creates a job with timeout=1, even if it's a streaming job. In fact it starts but then after a minute it goes in timeout.
Do you have any hint? Thanks

**Comment by DenisMurakhovskiy** [comment]
Hi @michel-98!
I found the solution. Based on AWS Glue documentation [https://docs.aws.amazon.com/glue/latest/dg/add-job.html.](url) 
_For streaming jobs that run indefinitely, leave the value blank, which is the default value for streaming jobs._
Do not use `timeout =`, remove that row. Instead write something like this:
```
resource "aws_glue_job" "glue_job" {
name          = local.job_name
description   = var.description
role_arn      = aws_iam_role.glue_job_role.arn
max_capacity  = var.worker_type == "Standard" ? var.dpu : null
max_retries   = var.max_retries
command {
    name = "gluestreaming"
  }
}
```

**Comment by michel-98** [comment]
HI @DenisMurakhovskiy,
The problem with your solution is that I have a parametrized glue job that can be a normal job or a streaming job, so the "variable=" should be there anyway. That's why I thought that passing it blank or with 0 could be a good solution, but unfortunately, it doesn't work.

**Comment by justinretzolk** [comment]
Hey @michel-98 👋 That's not the behavior I'd expect, given that setting the value to `null` is functionally equivalent to not passing the argument at all. That said, I think what you're experiencing is a bit different from the initial issue report here. We like to try to keep GitHub issues scoped to a single issue, so would you mind raising a [new issue](https://github.com/hashicorp/terraform-provider-aws/issues/new/choose) so we can gather all of the necessary information to look into this?

Given that the initial question here has been answered, I'll close this issue out and keep an eye open for the fresh one.
