### ISSUE TITLE
Error: error creating Kinesis Stream (sample-stream): SerializationException: Invalid message body: Could not decode JSON 

### ISSUE THREAD

**Issue by anekar3416** [hashicorp/terraform-provider-aws#25497]
I am trying to create a Kinesis Stream using the terraform in localstack endpoint. But I am getting this below exception:
` Error: error creating Kinesis Stream (sample-stream): SerializationException: Invalid message body: Could not decode JSON: {
   "StreamModeDetails" : {
     "StreamMode" : "ON_DEMAND"
   },
   "StreamName" : "sample-stream"
 }
       status code: 400, request id: XXXXXXXX
`

My sample terraform resource looks like this below:

```
resource "aws_kinesis_stream" "stream_sample" {
  name             = "sample-stream"
  retention_period = 24

  stream_mode_details {
    stream_mode = "ON_DEMAND"
  }

  tags = {
    Name        = "sample-stream"
    Environment = "Test"
    ManagedBy   = "Terraform"
  }
}

provider "aws" {
  version = "~> 3.0"
}
```

Can someone help me with this?

**Comment by justinretzolk** [comment]
Hey @anekar3416 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
