### ISSUE TITLE
Unable to retrieve Organizations Account based on Tags

### ISSUE THREAD

**Issue by vamsikrishna-v** [hashicorp/terraform-provider-aws#25664]
Hello,

I am unable to retrieve aws accounts(organizations accounts) in terraform based on tags.There is no datasource available as well. 
Please advise. 
I am looking something like below 

 data "aws_organizations_account" "account" {
 
   filter {
     name   = "tag:Name"
     values = ["PROD"]
   }
 }

Thanks,

**Comment by justinretzolk** [comment]
Hey @vamsikrishna-v 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md?plain=1)?
