### ISSUE TITLE
Assume Role With Web Identity configuration is not being passed during Client creation

### ISSUE THREAD

**Issue by VictorCovalski** [hashicorp/terraform-provider-aws#25680]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform -v
Terraform v1.2.3
on darwin_amd64

### Affected Resource(s)

web_identity_assume

* aws_XXXXX

### Terraform Configuration Files

terraform.hcl
```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.21.0"
    }
  }
}

provider "aws" {
  region                  = "us-east-1"
 
  assume_role_with_web_identity {
    role_arn = "arn:aws:iam::123456789012:role/MyRole
    web_identity_token = var.id_token  
  }
}
```

account.hcl
```hcl
data aws_iam_account_alias this {
}

output alias {
  value = data.aws_iam_account_alias.this.account_alias
}
```

IAM Role Trust Relationship
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123456789012:oidc-provider/gitlab.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "gitlab.com:sub": [
                        "project_path:mygroup/myproject/:ref_type:branch:ref:main",
                    ]
                }
            }
        }
    ]
}
```

### Debug Output

[Debug logs](https://gist.github.com/VictorCovalski/4ee8d8987ffc4b1821f18d6e4375af89)

### Expected Behavior

The provider should assume the IAM Role with the Web Identity method. 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

None.

* #0000

**Comment by azec-pdx** [comment]
@VictorCovalski, I believe that there has been regression with `v4.22.0` of the provider in terms of how credentials chain behaves when `assume_role_with_web_identity{}` is present in provider config.

### Behavior before `v4.22.0`
I have a Terraform module with these files: 

`versions.tf`
```hcl
terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0"
    }
  }
}
```

`providers.tf`
```hcl
provider "aws" {
  region              = var.region
  allowed_account_ids = [var.account_id]
  # Web Identity Role Federation only used in CI/CD
  assume_role_with_web_identity {
    role_arn           = var.ci_cd_role_ARN
    session_name       = var.ci_cd_sts_session_name
    duration           = var.ci_cd_sts_session_duration
    web_identity_token = var.ci_cd_web_identity_token
  }

  default_tags {
    tags = {
      # redacted
    }
  }
}
```

`devops-account-globals.yaml` (this is my top level YAML config that feeds TF root module variables)
```hcl
terraform:
  vars:
    # Defines the order of labels which constitute name for all resources stacked:
    # {namespace}-{tenant}-{environment}-{stage}-{name}-{attributes}
    label_order:
     - "namespace"
     - "tenant"
     - "environment"
     - "stage"
     - "name"
     - "attributes"
    account_id: "REDACTED"
    ci_cd_role_ARN: "REDACTED"
    ci_cd_sts_session_name: "Terraform-CI-CD"
    ci_cd_sts_session_duration: "1h"
    # To be provided as TF_VAR_ci_cd_web_identity_token through CI/CD.
    # Setting empty string value breaks credentials chain lookup when OIDC IdP is not used (e.g.engineer workstations and
    # using Administrator SAML-federated IAM Role)
    ci_cd_web_identity_token: "FAILSAFE"
```

Before `v4.22.0` with having `ci_cd_web_identity_token` set to value FAILSAFE, provider would attempt to 1st get STS session using `STS: AssumeRoleWithWebIdentity` and once that fails (because obviously "FAILSAFE" is not valid JWT token, intentionally), provider would proceed with other mechanisms to get AWS credentials. In scenario where I run `terraform` commands from my developer workstation, it would use my already persisted STS session saved in `AWS_` environment variables.

### Behavior after `v4.22.0`

All files above unchanged.
After upgrade to `v4.22.0`, with having `ci_cd_web_identity_token` set to value FAILSAFE, provider would attempt to 1st get STS session using `STS: AssumeRoleWithWebIdentity`  and once that fails, provider doesn't even attempt further to continue with other methods to find AWS credentials (credentials chain stops).
I get the error: 
```txt
Error: error configuring Terraform AWS Provider: IAM Role (REDACTED) cannot be assumed with web identity token.
│
│ There are a number of possible causes of this - the most common are:
│   * The web identity token used in order to assume the role is invalid
│   * The web identity token does not have appropriate permission to assume the role
│   * The role ARN is not valid
│
│ Error: failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 1, https response error StatusCode: 400, RequestID: 78672982-935a-4758-bd50-0f8a4c96f301, InvalidIdentityToken: The ID Token provided is not a valid JWT. (You may see this error if you sent an Access Token)

```

**Comment by azec-pdx** [comment]
I have just locked down my provider version with `version = "~> 4.21.0"` and confirmed above is true, just to double verify.

**Comment by VictorCovalski** [comment]
> I have just locked down my provider version with `version = "~> 4.21.0"` and confirmed above is true, just to double verify.

I fixed it right after writing this issue. Check #25681
