### ISSUE TITLE
aws_iam_role_policy generates plans without statements that was already attached when I attach an additional statement

### ISSUE THREAD

**Issue by teru01** [hashicorp/terraform-provider-aws#25769]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0

### Affected Resource(s)

* aws_iam_role_policy
* aws_s3_bucket

### Terraform Configuration Files

source A
```
data "aws_iam_policy_document" "codepipeline" {
  statement {
    actions = [
      "elasticloadbalancing:*",
    ]

    resources = [
      "*",
    ]
  }
}

resource "aws_iam_role" "codepipeline" {
  name               = "codepipeline"
  path               = "/service-role/"
  assume_role_policy = data.aws_iam_policy_document.assume_codepipeline.json
}

resource "aws_iam_role_policy" "codepipeline" {
  name   = "codepipeline-policy"
  role   = aws_iam_role.codepipeline.name
  policy = data.aws_iam_policy_document.codepipeline.json
}

data "aws_iam_policy_document" "assume_codepipeline" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["codepipeline.amazonaws.com"]
    }
  }
}
```
source B（`data.aws_iam_policy_document.codepipeline` is same as source A)
```
data "aws_iam_policy_document" "codepipeline" {
  statement {
    actions = [
      "elasticloadbalancing:*",
    ]

    resources = [
      "*",
    ]
  }
  statement {
    actions = [
      "s3:*",
    ]

    resources = [
      "${aws_s3_bucket.cp.arn}/*",
    ]
  }
}

resource "aws_s3_bucket" "cp" {
  bucket = "artifacts-2421252"
}
```

### Expected Behavior

```
  # aws_iam_role_policy.codepipeline will be updated in-place
  ~ resource "aws_iam_role_policy" "codepipeline" {
        id     = "codepipeline:codepipeline-policy"
        name   = "codepipeline-policy"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                    {
                        Action   = "elasticloadbalancing:*"
                        Effect   = "Allow"
                        Resource = "*"
                        Sid      = ""
                    },
                  + {
                      + Action   = "s3:*"
                      + Effect   = "Allow"
                      + Resource =  (known after apply)
                      + Sid      = ""
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }
```

### Actual Behavior

```
  # data.aws_iam_policy_document.codepipeline will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "codepipeline"  {
      ~ id      = "3768218025" -> (known after apply)
      ~ json    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "elasticloadbalancing:*"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
      - version = "2012-10-17" -> null

      ~ statement {
          - effect        = "Allow" -> null
          - not_actions   = [] -> null
          - not_resources = [] -> null
            # (2 unchanged attributes hidden)
        }
      + statement {
          + actions   = [
              + "s3:*",
            ]
          + resources = [
              + (known after apply),
            ]
        }
    }

  # aws_iam_role_policy.codepipeline will be updated in-place
  ~ resource "aws_iam_role_policy" "codepipeline" {
        id     = "codepipeline:codepipeline-policy"
        name   = "codepipeline-policy"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "elasticloadbalancing:*"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }
```

(aws_s3_bucket is omitted)

### Steps to Reproduce

1. apply source A
2. plan source B

### Important Factoids

* The generated iam_role_policy plan looks like the original statements will be removed, but it wasn’t after applied.
* This issue cannot be reproduced when I add s3 bucket and apply, and then add statement to `data.aws_iam_policy_document.codepipeline`.

**Comment by justinretzolk** [comment]
Hey @teru01 👋 Thank you for taking the time to raise this! After reading this over, I think I see what you're pointing out. If I understand correctly, the bit of the plan that you're looking at that's making it seem like the original statements are going to be removed are these bits, correct (specifically the `data.aws_iam_policy_document.codepipeline.json` and `aws_iam_role_policy.codepipeline.policy`)?

```shell
  # data.aws_iam_policy_document.codepipeline will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "codepipeline"  {
   ...
      ~ json    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "elasticloadbalancing:*"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
   ...
   }

  # aws_iam_role_policy.codepipeline will be updated in-place
  ~ resource "aws_iam_role_policy" "codepipeline" {
   ...
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "elasticloadbalancing:*"
                      - Effect   = "Allow"
                      - Resource = "*"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
   ...
   }
```

If I have understood that correctly, that in addition to your second note in the "important factoids" section seems to indicate this is a matter of [how data sources behave](https://www.terraform.io/language/data-sources#data-resource-behavior) when the given arguments aren't known until apply time.

In the described situation, the `aws_s3_bucket.cp.arn` won't be known until apply time (since the bucket is not yet created), so the `data.aws_iam_policy_document.codepipeline` can't be read until apply time. Since the data source can't be known until apply time, two things will occur:

1. `data.aws_iam_policy_document.codepipeline.json` will show as `(known after apply)`. Since this data source is already in the state, this shows up as "removing" the `json` attribute from the state and replacing what is in the state with what is read during apply time. This is why you're seeing what looks like the previous statements being removed at plan time.
2. Since `aws_iam_role_policy.codepipeline` is interpolating `data.aws_iam_policy_document.codepipeline.json` (which can't be known until apply time) for the `policy` argument, this also shows in the plan as `(known after apply)`, which has the same effect, visually, as above.

When you create the S3 bucket first, as described in your second bullet in "important factoids", `aws_s3_bucket.cp.arn` _is_ known at plan time, and so you don't run into the same `(known after apply)` situation. I would also expect that this would be the outcome on subsequent applies (after the S3 bucket has been created) for both scenarios.

I hope this provides a bit more clarity as to what you're seeing here. If I've misinterpreted your question, or if you have any follow up questions, please do let me know!

**Comment by teru01** [comment]
Thank you for the detailed reply. I understood why the data source looks like removed.
However, only `resources` arguments of the second `statement` of `data.aws_iam_policy_document.codepipeline` is originally  “known after apply” because other arguments is hard coded.
I think it is a candidate for improvement to make only `Resources` partially known after apply as the following snippet, but is that difficult to do in the current specification?

```
~ Statement = [
    {
        Action   = "elasticloadbalancing:*"
        Effect   = "Allow"
        Resource = "*"
        Sid      = ""
    },
  + {
      + Action   = "s3:*"
      + Effect   = "Allow"
      + Resource =  (known after apply)
      + Sid      = ""
    },
]
```

**Comment by justinretzolk** [comment]
Hey @teru01 👋 That type of enhancement would be something that would have to be done at the Terraform Core level, rather than the provider level. I can't speak to how difficult that would be to implement, but my recommendation would be to submit a feature request to the [Terraform Core repository](https://github.com/hashicorp/terraform) to see if that might be something that could be altered 🙂.

With that in mind, since this doesn't appear to be an issue with the AWS Provider itself, I'll close this issue for now. If you feel I've done this in error, or have any follow up questions, please do let me know.
