### ISSUE TITLE
AWS_CLOUDWATCH_METRIC_ALARM DIMENSIONS BLOCK NOT SUPPORTED

### ISSUE THREAD

**Issue by MatteoT9890** [hashicorp/terraform-provider-aws#25788]
I'm trying to create an `aws_cloudwatch_metric_alarm`:

```
resource "aws_cloudwatch_metric_alarm" "cloudwatch_metric_alarm_rpm_low" {
  count               = var.request_autoscaling_policy ? 1 : 0
  alarm_name          = "${var.service_name}-${var.environment}-RequestCountPerTarget-Low"
  alarm_actions       = ["${aws_appautoscaling_policy.appautoscaling_policy_rpm_scale_down[0].arn}"]
  comparison_operator = "LessThanOrEqualToThreshold"
  evaluation_periods  = 1
  metric_name         = "RequestCountPerTarget"
  namespace           = "AWS/ApplicationELB"
  period              = 60
  statistic           = "Average"
  threshold           = -var.request_target_value

  dimensions {
    LoadBalancer = var.alb_listener_arn
    TargetGroup  = aws_alb_target_group.main.arn_suffix
  }
}
```

**ERROR**
 Error: Unsupported block type
│ 
│   on modules/ecs/service/main.tf line 223, in resource "aws_cloudwatch_metric_alarm" "cloudwatch_metric_alarm_rpm_low":
│  223:   dimensions {
│ 
│ Blocks of type "dimensions" are not expected here. Did you mean to define argument "dimensions"? If so, use the equals sign to assign it a value.

**VERSION**
```
Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
```

**Comment by justinretzolk** [comment]
Hey @MatteoT9890 👋 Thank you for taking the time to raise this! It looks like you're missing the equals sign (`=`), meaning that, as defined, you're passing a _block_ of `dimensions` rather than an _argument_ of `dimensions` (more information on the difference may be found in the [Syntax](https://www.terraform.io/language/syntax/configuration#arguments-and-blocks) documentation).

To fix this, can you update your configuration to pass `dimensions` as an argument rather than a block and verify that that resolves your issue? That would like something like:

```hcl
  dimensions = {
    LoadBalancer = var.alb_listener_arn
    TargetGroup  = aws_alb_target_group.main.arn_suffix
  }
```

**Comment by MatteoT9890** [comment]
Solved! Thank you!
