### ISSUE TITLE
Wording of aws_rds_cluster backup window error is misleading

### ISSUE THREAD

**Issue by surpriseassociate** [hashicorp/terraform-provider-aws#25876]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.0.11
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.2.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_rds_cluster
* aws_rds_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

resource "aws_rds_cluster" "rds_cluster" {
  engine = "aurora-postgresql"
  ...
  preferred_backup_window = "16:00-18:00"
  ...
}

resource "aws_rds_cluster_instance" "rds_instance"{
  ...
  preferred_backup_window = "15:00-18:00"
  ...
}

```

### Debug Output

```
╷
│ Error: error creating RDS Cluster (qtac-int-db) Instance: InvalidParameterCombination: The requested DB Instance will be a member of a DB Cluster. Set backup window for the DB Cluster.
│       status code: 400, request id: 6f547509-92bb-45fb-a909-dca8f566e520
│
│   with aws_rds_cluster_instance.rds_instance[0],
│   on main.tf line 375, in resource "aws_rds_cluster_instance" "rds_instance":
│  375: resource "aws_rds_cluster_instance" "rds_instance"{
```

### Expected Behavior

I expected the error message to point me in the direction of the error.

The error message lead me to believe that there was an *issue* with the backup window configured for the rds cluster. I believe that the wording is meant to indicate that the backup window should be set on the db cluster *and not the db instance*. Adding this tidbit of informatino would assist others in their own debugging.

### Actual Behavior

The error message is ambiguously worded.

### Steps to Reproduce

1. Set a backup window on an aws_db_instance that is configured to be inside an aws_rds_cluster
2. `terraform apply`

### Important Factoids

I'm really sorry if this is such a petty issue to have, however I could not find any information on the internet about this issue and the wording lead me to waste way too much time not knowing what was possibly broken. By creating this issue I am hoping for two things; firstly, for there to be a Google result relevant to someone in my position and two, that maybe we could have this error message reworded for clarification to save someone a Google search.

To avoid this issue, you just remove the backup window from the instance and configure it for the cluster; there's no need for it to be on both.

### References

* nil that I could find

**Comment by justinretzolk** [comment]
Hey @surpriseassociate 👋 Thank you for taking the time to raise this! I love the idea of opening an issue so that there will be a Google result in case someone else experiences this 🙂. I've definitely been in that situation before, and this a really great way to help, so kudos to you!

As far as the error message, unfortunately that error is coming directly from AWS -- the provider is just [returning the error that was received on creation](https://github.com/hashicorp/terraform-provider-aws/blob/135dcc40af9835b7ed7dcd3eaf408d84174813ab/internal/service/rds/cluster_instance.go#L331-L333). That said, one idea I had was to add a note to the [relevant argument in the `aws_rds_cluster_instance` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#preferred_backup_window) to note that if the instance is configured to be in an `aws_rds_cluster`, that the `preferred_backup_window` should be set at the cluster level instead. Do you think that would have helped you in this situation?

**Comment by mansooj001** [comment]
To add to this conversation; YES! @justinretzolk that would help tremendously. It took me so long to find out once a cluster already has a preferred backup window. The preferred backup window of the **cluster instance** should be omitted.

**Comment by justinretzolk** [comment]
Hey y'all 👋 I've opened a PR to add a note about this. I'd love your feedback, if possible, to make sure that I've accurately described the scenario.
