### ISSUE TITLE
aws_organizations_policy Invalid parameter: minimum field size of 1, CreatePolicyInput.Content.

### ISSUE THREAD

**Issue by alexhaycock** [hashicorp/terraform-provider-aws#25977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform version: v1.0.8
AWS Provider versions: v4.22.0 to v4.23.0

### Affected Resource(s)

* aws_organizations_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

oraganisation.tf
```hcl
resource "aws_organizations_policy" "test_backup_policy" {
  name        = "TestBackupPolicy"
  type        = "BACKUP_POLICY"
  description = "This is a test backup policy."
  content     = file("${path.module}/templates/backuppolicies/testpolicy.json.tpl")
}

resource "aws_organizations_policy_attachment" "test_backup_policy" {
  policy_id = aws_organizations_policy.test_backup_policy.id
  target_id = aws_organizations_organizational_unit.workloads.id
}
```

testpolicy.json.tpl
```hcl
{
  "plans": {
    "TestPlan": {
      "regions": {
        "@@assign": [
          "eu-west-2"
        ]
      },
      "rules": {
        "TestRule": {
          "schedule_expression": {
            "@@assign": "cron(0 5 ? * * *)"
          },
          "start_backup_window_minutes": {
            "@@assign": "480"
          },
          "complete_backup_window_minutes": {
            "@@assign": "10080"
          },
          "lifecycle": {
            "delete_after_days": {
              "@@assign": "35"
            }
          },
          "target_backup_vault_name": {
            "@@assign": "TEST"
          },
          "copy_actions": {},
          "enable_continuous_backup": {
            "@@assign": false
          }
        }
      },
      "selections": {
        "tags": {
          "ResourceName": {
            "iam_role_arn": {
              "@@assign": "arn:aws:iam::$account:role/service-role/AWSBackupDefaultServiceRole"
            },
            "tag_key": {
              "@@assign": "Name"
            },
            "tag_value": {
              "@@assign": [
                "ResourceName"
              ]
            }
          }
        }
      }
    }
  }
}
```

### Expected Behavior

Create organization policy.

### Actual Behavior

```
│ Error: error creating Organizations Policy (TestBackupPolicy): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, CreatePolicyInput.Content.
```

### Steps to Reproduce

1. 'terraform apply'

### Important Factoids

This seems to be an issue when deploying as a new resource using 'terraform apply' with the AWS provider version v4.23.0. If the policies are already in place and then the provider is upgraded it doesn't seem to cause an issue or try to change the resource.

**Comment by OrlinOne** [comment]
Encountered this yesterday. Seems the new provider is expecting a Version key in the policy, but this is not part of the AWS Backup policy schema.

**Comment by jan-ludvik** [comment]
I also have a problem with `aws_organizations_policy` but `TAG_POLICY` in my case. New tag values are not detected on 4.23.0 and terraform says `No changes. Your infrastructure matches the configuration.`. On 4.22.0 I get planned changes without code changes in plan: `Plan: 0 to add, 2 to change, 0 to destroy.`

Let me know if I should make a separate issue but sounds quite possibly related.

**Comment by RonaldTechnative** [comment]
@jan-ludvik Your issue stems from this issue as well. Any other policy other than SCP will not be handled properly.

The issue is very tricky and it occurred when awspolicyequivalence was upgraded from v1.5.0 to v1.6.0 between v4.22.0 and v4.23.0. This external library is responsible for handling changes on JSON level that are not affecting changes in the policy (e.g. ordering).

1) However, it appears that this library was never programmed to handle any other policy than IAM policies (which SCP conform to as well).

The library was upgraded from 1.5.0 to 1.6.0 and the change in behaviour is this:

awspolicy.PoliciesAreEquivalent() behaviour changed:

`package main

import (
	"fmt"

	newlib "github.com/hashicorp/awspolicyequivalence"
)

func main() {
	fmt.Println(newlib.PoliciesAreEquivalent("", "{ \"plans\": {} }"))
}
`

`ronald@Ronalds-MacBook-Pro testapp % go mod edit -require github.com/hashicorp/awspolicyequivalence@v1.5.0
ronald@Ronalds-MacBook-Pro testapp % go mod tidy
ronald@Ronalds-MacBook-Pro testapp % go run ./main.go
false Error unmarshaling policy: unexpected end of JSON input
ronald@Ronalds-MacBook-Pro testapp % go mod edit -require github.com/hashicorp/awspolicyequivalence@v1.6.0
ronald@Ronalds-MacBook-Pro testapp % go mod tidy                                                          
ronald@Ronalds-MacBook-Pro testapp % go run ./main.go                                                     
true <nil>
`

2) So awspolicyequivalence started to consider changes as no changes and then TerraForm outputs "" as most of the other changes are then set to "" as well so the object is skipped. But this does not happen. We end up offering "" to the API which is obviously rejected.

Concluding:
1) -> 1) In terraform-provider-aws we are going to handle all policies as regular JSON policies. I don't know if this will break anything the awspolicyequivalence must have some significance but I don't know.

2) -> 2) Is actually a change in behaviour that made everything just work for policies other than SCPs.

3) Unittests were not working because they did not start with capital T. So this is fixed.

4) Unittests don't appear to test DiffSuppressFunc: They always succeed after 3) was resolved. Can someone help me with testing this as well?
