### ISSUE TITLE
Support for AWS Transfer Service AS2 Protocol

### ISSUE THREAD

**Issue by jay4e** [hashicorp/terraform-provider-aws#26007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Transfer Family released support for the AS2 protocol.  https://aws.amazon.com/about-aws/whats-new/2022/07/aws-transfer-family-support-applicability-statement-2-as2/

This should be added to the aws_transfer_family/aws_transfer_server options.

### New or Affected Resource(s)

* aws_transfer_server
* aws_transfer_user
* aws_transfer_mailbox (AS2 mailbox if not part of user?)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @jay4e 👋 Thank you for taking the time to raise this! The `aws_transfer_server` resource [uses `transfer.Protocol_Values()`](https://github.com/hashicorp/terraform-provider-aws/blob/7d9e9b84e39904a1a8d35ad6dfb55095851b2cbc/internal/service/transfer/server.go#L176) from the AWS Go SDK to validate the value supplied to the `protocol` argument. This enum was updated in [AWS Go SDK `v1.44.63`](https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#release-v14463-2022-07-26) to include `AS2`, and the provider has [already been bumped to use this version in the next release](https://github.com/hashicorp/terraform-provider-aws/pull/25993), so this should automatically work when AWS Provider version `4.24.0` is released 🎉. 

I've opened a PR to update the documentation as well, so that the docs will reflect properly when the next release happens.
