### ISSUE TITLE
vSphere -Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by krishz10** [hashicorp/terraform-provider-aws#26014]
When expanding the plan for vsphere_folder.web to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/vsphere" produced an invalid new value

This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by justinretzolk** [comment]
Hey @krishz10 👋 Thank you for taking the time to raise this! It looks like this is an issue with the vSphere provider rather than the AWS Provider. For issues with the vSphere provider, please open an issue in the [vSphere provider repository](https://github.com/hashicorp/terraform-provider-vsphere). With that in mind, we'll close this issue.
