### ISSUE TITLE
Missing link for the simple-vpc

### ISSUE THREAD

**Issue by napestershine** [hashicorp/terraform-provider-aws#26042]
https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest/examples/complete-vpc

On this page a link is missing where it's talking about simple-vpc.

section of document:

```
### Complete VPC

Configuration in this directory creates set of VPC resources which may be sufficient for staging or production environment (look into [simple-vpc](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest/simple-vpc) for more simplified setup).

There are public, private, database, ElastiCache, intra (private w/o Internet access) subnets, and NAT Gateways created in each availability zone.
```

https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest/simple-vpc

it goes to 404 page.

**Comment by justinretzolk** [comment]
Hey @napestershine 👋 Thank you for taking the time to raise this! The documentation for that module will exist within the module repository, so you'll need to open an issue in [that repository](https://github.com/terraform-aws-modules/terraform-aws-vpc/). Since this is separate from the AWS Provider itself, we'll close this issue.
