### ISSUE TITLE
aws_imagebuilder_component forcing replacement when data changes

### ISSUE THREAD

**Issue by ricardosouzamorais** [hashicorp/terraform-provider-aws#26117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

*  Terraform CLI version 0.15.0
* AWS Provider version 4.23.0

### Affected Resource(s)

* aws_imagebuilder_component

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_image_builder_component" "this" {
  name = var.component_name
  version = var.semantic_versioning
  platform = var.platform
  data = yamlencode(var.data)
}
```

### Expected Behavior

When changing the `version` and also `data`, terraform should create a new version of the component instead of forcing its replacement, removing it.

#### AWS CLI Behavior

If you have the same `version` and `data`, AWS CLI it bring us the error `ResourceAlreadyExistsException`. 
If you have the same `version` with a different `data`, AWS CLI it bring us the error `ResourceAlreadyExistsException`. 
If you have the same `data` with a different `version`, AWS CLI creates a new version.
If you have the new `data` and `version` values, AWS CLI creates a new version.

### Actual Behavior

When changing both `data` and `version` to new values, Terraform destroys the previous version and creates a new one.

### Steps to Reproduce

1. Specify `name`, `version`, `platform`, and `data`.
2. `terraform apply` will create the resource with informed version.
3. Change both `version` and `data` to new values.
4. `terraform apply` will destroy existing version, and then, will create the resource with new informed version and data.

### References

* #0000

**Comment by kamilturek** [comment]
The problem is that the `aws_image_builder_component` resource actually references a component version (e.g. ARN: `arn:aws:imagebuilder:us-west-2:123456789012:component/examplecomponent/1.2.3/1`).

Looking at how it's handled in other versioned resources (`aws_ecs_task_definition`, `aws_lambda_layer_version `), the issue could be solved by introducing a `skip_destroy` argument. Setting it to `true` would make the provider behave exactly as the CLI does - creating a new version would make the provider retain the old version.

An important point is that after updating the component, it'll be pointing to the newest version and therefore all other resources depending on it (e.g. image or container recipes) will automatically switch to this version causing a replacement of them (unless we also add `skip_destroy` argument to them).

https://github.com/hashicorp/terraform-provider-aws/pull/22269
https://github.com/hashicorp/terraform-provider-aws/pull/11997

@ricardosouzamorais What do you think?

**Comment by ricardosouzamorais** [comment]
The `skip_destroy` does not exist right now.
What we have done was to ignore the component replacement, incrementing the version number, ALWAYS, and making the recipe pointing to `x.x.x` version.

The bug is still in place.

**Comment by kamilturek** [comment]
Yes, it does not exist. I wanted to know if that could solve your problem.

**Comment by ricardosouzamorais** [comment]
Hello @justinretzolk , would you have any news on that?

Thanks a ton.

**Comment by justinretzolk** [comment]
Hey @ricardosouzamorais 👋 Thank you for checking in on this. Unfortunately, I'm not able to provide an estimate on when this will be looked into due to the potential of shifting priorities (we prioritize work by count of ":+1:" reactions, as well as a few other things). For more information on how we prioritize, check out out [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/).

That said, I'm also curious about Kamil's question above; would a `skip_destroy` argument (similar to how `aws_ecs_task_definition` and `aws_lambda_layer_version` work) work for your use case?

**Comment by lvthillo** [comment]
@ricardosouzamorais, just a question about this, if you have a component 0.0.1 and you upgrade it to 0.0.2 and use skip_destroy. Then both will exist, but will 0.0.1 still be managed by TF in some way?
