### ISSUE TITLE
aws_route_table resource need coorrect "CIDR block" validade mensage

### ISSUE THREAD

**Issue by Itiho** [hashicorp/terraform-provider-aws#26187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v1.2.6
* hashicorp/aws 4.25.0

### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "us-east-1"
}

terraform {
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 4.25.0"
    }
  }
}

resource "aws_route_table" "route_table" {
  vpc_id = "vpc-00ac5d3ee4909bebd"

  route {
      cidr_block                = "0.0.0.0/0" 
      ipv6_cidr_block           = "" 
      nat_gateway_id            = "nat-03f6f935508ea33f8"
  }
}
```

### Debug Output

```
terraform plan 
╷
│ Error: "" is not a valid CIDR block: invalid CIDR address: 
│ 
│   with aws_route_table.route_table,
│   on main.tf line 15, in resource "aws_route_table" "route_table":
│   15: resource "aws_route_table" "route_table" {

```

### Expected Behavior

The provider should show the following error
```
│ Error: "" is not a valid IPv6 CIDR block: 
```

### Actual Behavior

The provider should show the following error
```
│ Error: "" is not a valid CIDR block: invalid CIDR address: 
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

If I use ` ipv6_cidr_block  = "0.0.0.0/0"` the message is correct. I know I should be using null instead of empty string. I'm working on it right now in my code.

**Comment by justinretzolk** [comment]
Hey @Itiho 👋 Thank you for taking the time to raise this! I can see you argument, however, in investigating this, I believe this is expected behavior. The `ipv6_cidr_block` is ultimately passed to [`verify.ValidateIPv6CIDRBlock`](https://github.com/hashicorp/terraform-provider-aws/blob/1f4e2784b88c9b784afd136924c4357d88683884/internal/verify/validate.go#L136-L156) to validate whether the string passed to this argument is a valid IPv6 CIDR block. That function has the following note:

>// ValidateIPv6CIDRBlock validates that the specified CIDR block is valid:
>// - The CIDR block parses to an IP address and network
>// - The IP address is an IPv6 address
>// - The CIDR block is the CIDR block for the network

In your example, the supplied string fails at the first check -- it is not a valid CIDR block _at all_, so you received an error indicating that. If you instead passed an IPv4 CIDR block here, you'd fail at the second check, and would receive the `...is not a valid IPv6 CIDR block` error that you initially expected. I hope that provides a bit more clarity as to why you received what you did!

In this case, the current behavior provides additional information that the proposed change would not, so I think leaving it as is is the correct call. With that in mind, I'll close this issue out. If you feel I've done so in error, please do let me know.

**Comment by Itiho** [comment]
Hello @justinretzolk 

My propose is change only error text in [verify.ValidateIPv6CIDRBlock](https://github.com/hashicorp/terraform-provider-aws/blob/1f4e2784b88c9b784afd136924c4357d88683884/internal/verify/validate.go#L143) from 
```
return fmt.Errorf("%q is not a valid CIDR block: %w", cidr, err)
```
to
```
return fmt.Errorf("%q is not a valid IPv6 CIDR block: %w", cidr, err)
```

This change improve debug velocity. Today validate erro in ValidateIPv6CIDRBlock is the same in  ValidateIPv4CIDRBlock
