### ISSUE TITLE
aws_storagegateway_cached_iscsi_volume.volume_size_in_bytes cannot create drives more than 1GB

### ISSUE THREAD

**Issue by jlongo62** [hashicorp/terraform-provider-aws#26376]
I am creating an AWS Volume Storage Gateway. I can create the Gateway, Cache and Upload Buffer. However, I cannot create a volume larger than 1GB. It looks like an overflow problem.

volume_size_in_bytes = 1 * 1024 * 1024 * 1024 creates a 1GB drive (I need 1024 GB)
volume_size_in_bytes = 9 * 1024 * 1024 * 1024 fails and returns: Attribute must be a whole number, got 9.663676416e+09
volume_size_in_bytes = 1099511627776 (1TiB->Bytes) returns: Attribute must be a whole number, got 1.099511627776e+12
.

resource "aws_storagegateway_gateway" "apm" {
  gateway_ip_address = data.aws_instance.storagegateway.private_ip # "172.29.29.207" --need to define VM
  gateway_name       = "Pracice Management Volume Gateway"
  gateway_timezone   = "GMT"
  gateway_type       = "CACHED"  
  gateway_vpc_endpoint = data.aws_vpc_endpoint.storagegateway.dns_entry[0].dns_name
  cloudwatch_log_group_arn = data.aws_cloudwatch_log_group.storagegateway.arn  
} 

data "aws_storagegateway_local_disk" "cache" {
  disk_node   = "/dev/xvdc"
  gateway_arn = aws_storagegateway_gateway.apm.arn
}
resource "aws_storagegateway_cache" "apm" {
  disk_id     = data.aws_storagegateway_local_disk.cache.disk_id
  gateway_arn = aws_storagegateway_gateway.apm.arn
}

data "aws_storagegateway_local_disk" "buffer" {
  disk_node   = "/dev/xvdb"
  gateway_arn = aws_storagegateway_gateway.apm.arn
}
resource "aws_storagegateway_upload_buffer" "apm" {
  disk_id     = data.aws_storagegateway_local_disk.buffer.disk_id
  gateway_arn = aws_storagegateway_gateway.apm.arn
}

variable "Gb512" {
  type    = string
  default = 9 * 1024 * 1024 * 1024
}
resource "aws_storagegateway_cached_iscsi_volume" "volume01" {
  gateway_arn          =aws_storagegateway_cache.apm.gateway_arn

**Comment by justinretzolk** [comment]
Hey @jlongo62 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by jlongo62** [comment]
I think the field is defined as "number", but "number" has a limit on digits. FYI:  volume_size_in_bytes = 5368709120 (from documentation page fails;  volume_size_in_bytes = 1 * 1024 * 1024 * 1024 works;   volume_size_in_bytes = 2 * 1024 * 1024 * 1024 fails; this is time critical for our project.

I have the latest in environment:
Terraform v1.2.7
on windows_386
+ provider registry.terraform.io/hashicorp/aws v4.26.0

**Comment by justinretzolk** [comment]
Hey @jlongo62 👋 Thank you for the additional information. Upon looking at this more, I believe the issue here is that it appears that you're running a 32 bit version of Terraform and the integers that you're looking to use are larger than 32 bit systems can handle. Is it possible for you to switch to a 64 bit version of Terraform to verify that that clears up the issue?

**Comment by jlongo62** [comment]
64 Bit version did fix this. Seems like a bug in the x386 Terraform release unless it is a bug in the AWS CLI. Either number needs to float OR value needs to be defined as string and passed to AWS API in whatever form it needs.
