### ISSUE TITLE
Unstable behaviour of S3 bucket policies

### ISSUE THREAD

**Issue by Yashwant0108** [hashicorp/terraform-provider-aws#26478]
It has been observed that the Terraform deletes and adds bucket policy statement in every consecutive builds even when nothing has changed.
* #0000
It has been observed that the Terraform deletes and adds bucket policy statement in every consecutive builds even when nothing has changed.
For every odd build number it is removing the policy statements on its own and for every even build number it is adding the removed policy statments again.

**Comment by justinretzolk** [comment]
Hey @Yashwant0108 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
