### ISSUE TITLE
Resource: aws_instance private_ip is not listed in Attributes Reference

### ISSUE THREAD

**Issue by star3am** [hashicorp/terraform-provider-aws#26593]
On https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#attributes-reference `private_ip` is not listed in the Attributes References. 

It is available though and working, ref: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ec2_instance.go#L548 

It's just not documented. 

It's also referenced in the Terraform Foundations course ref: https://hashicorp-services.github.io/enablement-terraform-slides/markdown/tf-provisioners/#3

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* Hashicorp website https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#attributes-reference

**Comment by justinretzolk** [comment]
Hey @star3am 👋 Thank you for taking the time to raise this! It looks like `private_ip` is not listed under the attributes due to it being a [configurable argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#private_ip). This follows the standard approach where read-only attributes are separate from configurable arguments. This is mentioned just under the attributes reference header with:

> In addition to all arguments above, the following attributes are exported: 

With that in mind, I'll close this issue for now. If you feel I've done this in error, please do let me know.
