### ISSUE TITLE
[aws_flow_log]: log_destination parameter is marked as ‘Optional’ in terraform documentation, but it behaves as a required parameter

### ISSUE THREAD

**Issue by Nachiket-K** [hashicorp/terraform-provider-aws#26664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform 0.12.31
AWS Provider 3.70.0

### Affected Resource(s)

* aws_flow_log

### Details
•	On AWS Console, the Log destination is defined as Required.
•	On the AWS CLI also, the log_destination behaves as required parameter. If this parameter is not specified, then it gives an error (“LogDestination can't be empty if LogGroupName is not provided”).
![image](https://user-images.githubusercontent.com/96296568/188657439-cd175b01-01aa-4093-9dfd-74a26de0e85c.png)

•	In terraform also, the same behaviour is observed i.e. when this parameter is not specified then it gives the same error as CLI because it is required parameter.
•	But terraform documentation is incorrect wherein log_destination parameter is mentioned as Optional, so we think that the documentation needs to be updated.

### Terraform Configuration Files

```hcl
resource "aws_flow_log" "this" {
  eni_id                   = "eni-xxxxxxxxxxxxxxxxx"
  traffic_type             = "ALL"
  log_destination_type     = "s3"
}
```
### Expected Behavior

The resource aws_flow_log should get successfully created even if log_destination parameter is not specified because as per terraform documentation it is ‘Optional’.

### Actual Behavior

•	As per terraform documentation, 'log_destination' parameter is Optional and if it is not specified, then terraform throws an error as “LogDestination can't be empty if LogGroupName is not provided”.
•	log_group_name is a deprecated parameter and it cannot be specified, so instead log_destination parameter must be specified, as per terraform documentation, but since this parameter is marked as Optional and if we don't specify the same, terraform throws following error:

![image](https://user-images.githubusercontent.com/96296568/188574226-a99bef7b-d378-44c9-aa6f-3b0bcc9e1654.png)

### Steps to Reproduce

1. `terraform apply`

### References
https://registry.terraform.io/providers/hashicorp/aws/3.70.0/docs/resources/flow_log

**Comment by justinretzolk** [comment]
Hey @Nachiket-K 👋 Thank you for taking the time to raise this! I've opened a PR to make the documentation a bit more clear. In this case, **either** `log_group_name` or `log_destination` (and `log_destination_type`) must be set. The latter is preferred, since `log_group_name` has been deprecated. To allow backwards compatibility, `log_group_name` hasn't been removed from the provider entirely yet.

As you can't specify both, but one or the other is required, the arguments must be marked as optional in the documentation. This is what's defined as best practices in the [plugin development guide](https://www.terraform.io/plugin/sdkv2/best-practices/deprecations#renaming-a-required-attribute). My PR corrects the missing bit there (step 7), where it wasn't made clear that one or the other was required. Thank you for catching this and pointing it out!
