### ISSUE TITLE
Datasource aws_opensearch_domain fails when advanced_security_options is enabled

### ISSUE THREAD

**Issue by fmartinou** [hashicorp/terraform-provider-aws#26668]
### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.29.0
```

### Affected Resource(s)

* Datasource `aws_opensearch_domain`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.29.0"
    }
  }
}

provider "aws" {
  region = "eu-west-3"
}

resource "aws_opensearch_domain" "bug" {
  domain_name = "bug"

  cluster_config {
    instance_type            = "t3.small.search"
    instance_count           = 1
    dedicated_master_enabled = false
  }
  ebs_options {
    ebs_enabled = true
    volume_size = 10
    volume_type = "gp2"
  }
  node_to_node_encryption {
    enabled = true
  }
  encrypt_at_rest {
    enabled = true
  }
  domain_endpoint_options {
    enforce_https       = true
    tls_security_policy = "Policy-Min-TLS-1-2-2019-07"
  }
  advanced_security_options {
    enabled                        = true
    internal_user_database_enabled = true
    master_user_options {
      master_user_name     = "elastic"
      master_user_password = "Eel@st1c"
    }
  }
}

data "aws_opensearch_domain" "my_domain" {
  domain_name = aws_opensearch_domain.bug.domain_name
}

```

### Debug Output
```
...
aws_opensearch_domain.bug: Creation complete after 16m16s [id=arn:aws:es:eu-west-3:560417158718:domain/bug]
data.aws_opensearch_domain.my_domain: Reading...
╷
│ Error: error setting advanced_security_options: Invalid address to set: []string{"advanced_security_options", "0", "anonymous_auth_enabled"}
│ 
│   with data.aws_opensearch_domain.my_domain,
│   on main.tf line 47, in data "aws_opensearch_domain" "my_domain":
│   47: data "aws_opensearch_domain" "my_domain" {
│ 
╵
```

[See full log in attachment](https://github.com/hashicorp/terraform-provider-aws/files/9498573/terraform.log)

### References

**This configuration is perfectly working with provider version `4.28.0`**

**Maybe related [to this PR](https://github.com/hashicorp/terraform-provider-aws/pull/26503)?**

**Comment by dpattmann** [comment]
Hi @fmartinou, you are right. The PR #26503 is related to this issue. The function `flattenAdvancedSecurityOptions` now tries to set `anonymous_auth_enabled` to a boolean value but the field is missing in the data resource model. I'm going to create a PR to fix this.

**Comment by fmartinou** [comment]
Any news regarding this fix? 😢

**Comment by xfournet** [comment]
This issue is a regression because it's preventing to reference an opensearch domain that has been created by terraform in another configuration. That is our case, and it prevent us to update, we are stuck to 4.28.0 since 2 months.

As this bug is a regression and the PR available (#26746 which is quite small), would be possible to prioritize it? It's really really annoying not be able to update, we are missing functionnalities that are in newer realeases

**Comment by tgeo-cambrian** [comment]
any news on this?
creates an issue in our setup too.

**Comment by axi43** [comment]
We just upgraded and got impacted.
Thanks so much for working on fixing this!

**Comment by Wyifei** [comment]
Any update for this?

**Comment by kevinashaw** [comment]
Updates?

**Comment by neovatar** [comment]
We encountered the same problem and are stuck with an old provider version - a merge and release of the PR would really be appreciated!

**Comment by barthel** [comment]
Any updates?

**Comment by spliskamatyshak-w3** [comment]
@YakDriver, it seems this has fallen on deaf ears. This affecting more and more each day, now including my company.

**Comment by leonardolacerdaatlantico** [comment]
Any updates? I had same problem here. In really this is affecting more and more each day. Now, I'm blocked too in a old version.

**Comment by mmcmaster-seek** [comment]
I also encountered this issue today on 4.54.0. I got past it by downgrading to 4.28.0.

**Comment by xfournet** [comment]
We are about to hit the wall in few days...
We are stuck to v4.28.0 due to this regression. Since we are also deploying WAF rules with Terraform we will be blocked at the end of the month since at that time AWS will require WAF rules to specify Oversize Handling which is only possible starting from v4.52.0 (see #25545)

It's very questioning to me why Terraform, unlike the vast majority of open source project, don't prioritize regressions over bugs and features. Prioritization just using 'like' vote is quite worrying, do i need to write a bot to get attention on this 6 month old regression ?
Community help didn't work too, since the proposed PR has not been merged since months, multiple comments about the impact of this regression didn't resonate too.

@YakDriver help would be appreciated, thanks.

**Comment by kai-ten** [comment]
Best thing you can do is give the PR #26746 a like, and hopefully Terraform finds it worthwhile to fix this broken aspect of their tool. 

Also impacting my organization

**Comment by barthel** [comment]
@justinretzolk  help would be appreciated, thanks.
