### ISSUE TITLE
Confusing : Cookie name being set if not needed.

### ISSUE THREAD

**Issue by everops-miked** [hashicorp/terraform-provider-aws#26735]
I have a case where the cookie name got set somehow but it is not used. 

The plan shows a drift  
`cookie_name     = "lb_cookie" -> null`

But looking at the console this is not even visible. 

This following line sets the cookie name and will cause a change that is not needed. 
https://github.com/hashicorp/terraform-provider-aws/blob/d4aae9242ad71229bc43bebe8a0145f9f0861f6a/internal/service/elbv2/target_group.go#L1040

We should only set the cookie name attribute if the stickiness["type"] == "app_cookie" as well.

Describe of the attributes shows 
`{   "Key": "stickiness.app_cookie.cookie_name",         "Value": "lb_cookie" },`

but looking at the console that attribute is not set and changing it does cause the save to be activated unless the app_cookie type is set.

**Comment by timothyjrogers** [comment]
I picked this up and have a pull request open.

**Comment by timothyjrogers** [comment]
@everops-miked I asked this on the PR but it probably makes more sense to ask it here.

Was this target group previously using app_cookie and updated at some point to use lb_cookie, or has it always used lb_cookie? I'm trying to determine how the cookie name could have been set to begin with on a target group using `lb_cookie`, since that shouldn't be valid.

**Comment by everops-miked** [comment]
I think at some point someone manually set the app_cookie and switched to back setting the name. so start with lb_cookie and switch to app, set the name and switch back in the console.

**Comment by Chris-Softrams** [comment]
Same issue.

**Comment by timothyjrogers** [comment]
I apologize for the long delay, I got pulled away from this after picking it up and then just absolutely forgot about it.

I've been digging back into this for a couple hours here and I think I've convinced myself what you're seeing is actually correct behavior based on the AWS APIs. If I create a new Target Group with no stickiness and then update the settings in this order:

1. Enable stickiness w/ lb_cookie
2. Update stickiness w/ app_cookie, name=TESTCOOKIE
3. Update stickiness back to lb_cookie

And I describe that Target Group's Attributes via the AWS CLI between each step, I get back these cookie details. I've omitted the unrelated attributes for brevity.

```
//After enable stickiness w/ lb_cookie
{
    "Attributes": [
        {
            "Key": "stickiness.enabled",
            "Value": "true"
        },
        {
            "Key": "stickiness.type",
            "Value": "lb_cookie"
        },
        {
            "Key": "stickiness.app_cookie.cookie_name",
            "Value": ""
        }
    ]
}

//After update stickiness w/ app_cookie, name=TESTCOOKIE
{
    "Attributes": [
        {
            "Key": "stickiness.enabled",
            "Value": "true"
        },
        {
            "Key": "stickiness.type",
            "Value": "app_cookie"
        },
        {
            "Key": "stickiness.app_cookie.cookie_name",
            "Value": "TESTCOOKIE"
        }
    ]
}

//After update stickiness back to lb_cookie
{
    "Attributes": [
        {
            "Key": "stickiness.enabled",
            "Value": "true"
        },
        {
            "Key": "stickiness.type",
            "Value": "lb_cookie"
        },
        {
            "Key": "stickiness.app_cookie.cookie_name",
            "Value": "TESTCOOKIE"
        }
    ]
}
```

From that we can see that behind the scenes AWS persists `stickiness.app_cookie.cookie_name` even if you switch back to lb_cookie, despite it not being used, and in fact creates that attribute as an empty string even if you start with `lb_cookie`. If that is the case then I think the drift you are seeing is correct in order to maintain accurate state -- your target group has an (unused) value of `stickiness.app_cookie.cookie_name=lb_cookie` behind the scenes and Terraform is correcting that to be empty since you aren't maintaining a value in your code. This is unclear from the data available in the console as you noted, but it seems apparent in the APIs.

I do question why it is saying `lb_cookie -> null` instead of `lb_cookie -> ""`, as that is the default empty value when I create my target group but perhaps that's just how it is represented in the state.

Based on the digging I've done here today I think my open PR is actually invalid and contradicts the behavior and state maintained by the API.

**Comment by timothyjrogers** [comment]
Of course as soon as I look further into the `lb_cookie -> null` question in my own post I find something relevant.

https://github.com/hashicorp/terraform-provider-aws/blob/d4aae9242ad71229bc43bebe8a0145f9f0861f6a/internal/service/elbv2/target_group.go#L705-L749

It appears that when a Target Group update is applied, if the stickiness type is `lb_cookie`, Terraform drops the `stickiness.app_cookie.cookie_name` attribute entirely. This would explain your drift whereas the original code we were looking at does not -- the code I initially changed should be finding the value because it is based on a live read of the Target Group attributes.

My thinking is that, because AWS tracks `stickiness.app_cookie.cookie_name` in the backend even if you switch to `lb_cookie`, Terraform should also track that value when you switch between them to be consistent. If we agree on that point I will open a fresh PR (and close the current one) to make the code change in the section I linked above. Please let me know your thoughts.

**Comment by timothyjrogers** [comment]
I have submitted a new pull request for this (here: https://github.com/hashicorp/terraform-provider-aws/pull/31436) addressing the details above.

**Comment by pineros** [comment]
Currently having this issue as I update my terraform scripts from v0.12.23 to v1.6.2 on darwin_arm64
