### ISSUE TITLE
aws_ssoadmin_account_assignment and others won't create because of a failed provisioning

### ISSUE THREAD

**Issue by aviau** [hashicorp/terraform-provider-aws#26807]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ssoadmin_account_assignment
* aws_ssoadmin_permission_set_inline_policy

### Terraform Configuration Files

These two resources don't work at all on a new account.

```hcl

data "aws_ssoadmin_instances" "all" {}

locals {
  aws_iam_identity_center_instance = {
    id  = tolist(data.aws_ssoadmin_instances.all.identity_store_ids)[0]
    arn = tolist(data.aws_ssoadmin_instances.all.arns)[0]
  }
}


data "aws_identitystore_group" "developers" {
  identity_store_id = local.aws_iam_identity_center_instance.id
  filter {
    attribute_path  = "DisplayName"
    attribute_value = "developers"
  }
}

resource "aws_ssoadmin_permission_set" "developers" {
  name         = "developers"
  instance_arn = local.aws_iam_identity_center_instance.arn
}

resource "aws_ssoadmin_account_assignment" "developers" {
  instance_arn       = aws_ssoadmin_permission_set.developers.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.developers.arn

  principal_id   = data.aws_identitystore_group.developers.group_id
  principal_type = "GROUP"

  target_id   = xxxxx
  target_type = "AWS_ACCOUNT"
}

```

### Expected Behavior

- No error.

### Actual Behavior

```
aws_ssoadmin_account_assignment.developers: Creating...
╷
│ Error: error waiting for SSO Account Assignment for GROUP (c4084468-e081-70e9-67db-b19c3a225188) to be created: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)
│
│   with aws_ssoadmin_account_assignment.developers,
│   on aws_iam_identity_center.tf line 38, in resource "aws_ssoadmin_account_assignment" "developers":
│   38: resource "aws_ssoadmin_account_assignment" "developers" {
```

This same error happens when creating a number of sso-related resources. The docs say that the terraform module attempts to trigger a provisioning when some of them change, which is not possible when the permissions sets were not yet assigned to an account. I feel like this triggers a catch-22 where its impossible to actually use the terraform module without having created stuff manually in the ui before.

**Comment by frankpengau** [comment]
What I've seem to have found, is that there seems to be quite a strict flow for the aws sso resources.

1. Create Permission Set
2. Attach Managed/Inline Policy to Permission Set
3. Assign Permission Set to Account (Account Assignment) 

The parallelism (parallel processing) nature of terraform would sometimes cause problems if it tries to attach policies when a permission set doesn't exist or if a permission set is already assigned to an account and then when you attach policies, it would trigger the ProvisionPermissionSet API Call, due to the way that ssoadmin works for updating permission sets.

**Comment by dynnamitt** [comment]
version '1.2.7'
- Installed hashicorp/aws v4.64.0 (signed by HashiCorp)

Same error , there is only one api call:
**aws_ssoadmin_account_assignment**.
Since permission-set + policy exist + account.

Oddly in my case: The Issue only arise in ONE account in our organization: Master Account 

`aws_ssoadmin_account_assignment.a["KH.App.AWS.CMP/master/AWSSecurityHubReadOnlyAccess"]: Creating...
aws_ssoadmin_account_assignment.a["KH.App.AWS.CMP/master/AWSSecurityHubReadOnlyAccess"]: Still creating... [10s elapsed]
╷
│ Error: waiting for SSO Account Assignment for GROUP (93671bac31-4f5b72cc-2e6b-4501-b450-8b6e8991[69](https://gitlab.com/ruter-as/cmp/eks/unique-team-policies/-/jobs/4164302930#L69)d0) to be created: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)
│ 
│   with aws_ssoadmin_account_assignment.a["KH.App.AWS.CMP/master/AWSSecurityHubReadOnlyAccess"],
│   on assignments.tf line 57, in resource "aws_ssoadmin_account_assignment" "a":
│   57: resource "aws_ssoadmin_account_assignment" "a" {
│ 
╵`

**Comment by joestump** [comment]
I have seen this error pop up if the target account does not have the permission boundary referenced in the permission set already in the account.

**Comment by Almenon** [comment]
Note that this error could also be because of a invalid IAM policy. See https://github.com/hashicorp/terraform-provider-aws/issues/31456

**Comment by uname223** [comment]
I had the same issue, here's how I found out the solution.

My setup:
Deployment account -> Assume role in organization root

- Tried to assign permissionset to all accounts within org
- There were no issues overall, but it failed for the **org root account**
- Run terraform in debug mode, find out, my role in organization is missing permissions for "iam:CreateRole", "iam:PutRolePolicy" so I added those permissions for that role
- Added even more permissions to not play a whack-a-mole
- Profit!

The tricky part is, that in my setup it was failing, but no meaningful cloudtrail log could be found. Even when using AWS CLI I have not found any error (even in debug mode). Only terraform in debug mode showed what is going on!

Hope that helps! Be aware of additional permisssions you need to add to the role that is executing the changes when you want to assign permissionsets to the **org root account** or  the SSO management account (in my case they are the same).

PS. 
I was getting 403 errors when I did not specify region in the provider ([usefull thread](https://discuss.hashicorp.com/t/aws-sso-error-error-reading-sso-instances-accessdeniedexception/30880)) that is the same as the region my SSO is deployed.
