### ISSUE TITLE
aws_mskconnect_connector: missing required field, CreateConnectorInput.KafkaCluster.ApacheKafkaCluster.BootstrapServers

### ISSUE THREAD

**Issue by jslusher** [hashicorp/terraform-provider-aws#26828]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform: `1.2.6`
`Using previously-installed hashicorp/aws v4.30.0`

### Affected Resource(s)
`aws_mskconnect_connector`
### Terraform Configuration Files

```hcl
resource "aws_mskconnect_connector" "mm2" {
  name = "mirrormaker"

  depends_on = [
    aws_msk_cluster.msk2,
    aws_iam_role.mm2
  ]

  kafkaconnect_version = "2.7.1"

  capacity {
    autoscaling {
      mcu_count        = 1
      min_worker_count = 1
      max_worker_count = 2

      scale_in_policy {
        cpu_utilization_percentage = 20
      }

      scale_out_policy {
        cpu_utilization_percentage = 80
      }
    }
  }

  connector_configuration = {
    "connector.class" = "org.apache.kafka.connect.mirror.MirrorSourceConnector"
    "tasks.max"       = "1"
    "topics"          = ".*"
    "name" = "mm2-test"
    "source.cluster.alias" = "msk-test-source"
    "source.cluster.bootstrap.servers" = aws_msk_cluster.msk1.bootstrap_brokers_tls
    "target.cluster.bootstrap.servers" = aws_msk_cluster.msk2.bootstrap_brokers_tls
    "offset-syncs.topic.replication.factor" = "1"
  }

  kafka_cluster {
    apache_kafka_cluster {
      bootstrap_servers = aws_msk_cluster.msk2.bootstrap_brokers_tls

      vpc {
        security_groups = [
          aws_security_group.kafka-clients.id
        ]

        subnets         = [
          var.msk-subnet-a-id,
          var.msk-subnet-b-id,
          var.msk-subnet-c-id,
        ]
      }
    }
  }

  kafka_cluster_client_authentication {
    authentication_type = "NONE"
  }

  kafka_cluster_encryption_in_transit {
    encryption_type = "TLS"
  }

  plugin {
    custom_plugin {
      arn      = data.aws_mskconnect_custom_plugin.mm2.arn
      revision = data.aws_mskconnect_custom_plugin.mm2.latest_revision
    }
  }

  service_execution_role_arn = aws_iam_role.mm2.arn
}
```

### Debug Output
https://gist.github.com/jslusher/2b7c52c0f4d9f14bff9ee942d4842180#file-terraform-apply-debug-txt

### Expected Behavior
Terraform should apply my MSK connector using the `kafka_cluster` arguments provided, including the broker information.

### Actual Behavior
```
│ Error: error creating MSK Connect Connector (mirrormaker): InvalidParameter: 1 validation error(s) found.
│ - missing required field, CreateConnectorInput.KafkaCluster.ApacheKafkaCluster.BootstrapServers.
│   with aws_mskconnect_connector.mm2,
│   on mm2-connector.tf line 28, in resource "aws_mskconnect_connector" "mm2":
│   28: resource "aws_mskconnect_connector" "mm2" {
```
### Steps to Reproduce

1. `terraform apply`

**Comment by yotam-h** [comment]
Hi
I'm getting the same error.
```
aws provider = 4.32.0
terraform = 1.1.3
```

```
resource "aws_mskconnect_connector" "db-connector" {
  name = "${var.name}-db-connector"

  kafkaconnect_version    = "2.7.1"
  service_execution_role_arn = aws_iam_role.msk-debezium-secret-access-role.arn

  connector_configuration = {
    "connector.class"       = "io.debezium.connector.postgresql.PostgresConnector"
    "tasks.max"             = "1"
    "database.hostname"     = "${var.db_enpoint}"
    "database.port"         = "5432"
    "database.user"         = "${jsondecode(data.aws_secretsmanager_secret_version.db-debezium.secret_string).username}"
    "database.password"     = "${jsondecode(data.aws_secretsmanager_secret_version.db-debezium.secret_string).password}"
    "database.server.name"  = "XXXXX"
    "name"                  = "${var.name}-db-connector"
    "database.dbname"       = "XXXXXX"
    "plugin.name"           = "pgoutput"
    "decimal.handling.mode" = "double"
  }
  capacity {
    provisioned_capacity {
      mcu_count    = 1
      worker_count = 1
    }
  }
  kafka_cluster {
    apache_kafka_cluster {
      bootstrap_servers = aws_msk_cluster.msk_cluster.bootstrap_brokers_tls

      vpc {
        security_groups = [aws_security_group.msk_sg.id]
        subnets         = var.vpc_private_subnets
      }
    }
  }
  kafka_cluster_client_authentication {
    authentication_type = "IAM"
  }
  kafka_cluster_encryption_in_transit {
    encryption_type = "TLS"
  }
  plugin {
    custom_plugin {
      arn      = aws_mskconnect_custom_plugin.debezium-msk-plugin.arn
      revision = aws_mskconnect_custom_plugin.debezium-msk-plugin.latest_revision
    }
  }
}
}
```

when running apply I'm getting
```

╷
│ Error: error creating MSK Connect Connector (dev-db-connector): InvalidParameter: 1 validation error(s) found.
│ - missing required field, CreateConnectorInput.KafkaCluster.ApacheKafkaCluster.BootstrapServers.
│
│
```

**Comment by justinretzolk** [comment]
Hey @jslusher 👋 Thank you for taking the time to raise this! In reviewing the debug logs, I had an idea of what might be happening here, but I'm missing a bit of information in order to confirm. I noticed that both you and the additional report are setting the value of the `kafka_cluster.apache_kafka_cluster.bootstrap_servers` argument by interpolating the value of `aws_msk_cluster.<name>.bootstrap_brokers_tls`. In reviewing the documentation for the [`aws_msk_cluster` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster#bootstrap_brokers_tls), I noticed the following note:

> This attribute will have a value if `encryption_info.0.encryption_in_transit.0.client_broker` is set to `TLS_PLAINTEXT` or `TLS`.

I also noticed that in the debug logs you supplied, while there wasn't a `aws_msk_cluster` resource named `msk2`, as I would expect from the sample configuration you supplied, there were other `aws_msk_cluster` resources, whose `bootstrap_brokers_tls` values were blank (see lines 874 and 1021 in your debug logs). I also noticed you have an output set to the value of each of the `aws_msk_cluster.<name>.bootstrap_brokers_tls` values, each of which is showing an empty string (lines 635-643 of the debug logs).

Is it possible that the `aws_msk_cluster` resource that you're attempting to pull the `bootstrap_brokers_tls` value from don't have `encryption_info.0.encryption_in_transit.0.client_broker` set to either `TLS_PLAINTEXT` or `TLS`, and thus an empty string is being passed to the `aws_mskconnect_connector`'s `kafka_cluster.apache_kafka_cluster.bootstrap_servers` argument?

**Comment by yotam-h** [comment]
Hello @justinretzolk 
Thank you for taking the time and looking into the issue.
I've gone over your reply, and you're right on the first part in my case where there is no output for `bootstrap_brokers_tls`. Of course, this caused the error I'm getting.

But the issue is, that I do have `encryption_info.0.encryption_in_transit.0.client_broker` set to TLS. As seen here in my code sinnpet. So I;m not really sure why am I getting a blank output for `bootstrap_brokers_tls`
```
resource "aws_msk_cluster" "msk_cluster" {
  cluster_name           = "${var.name}-msk"
  kafka_version          = "2.6.2"
  number_of_broker_nodes = var.number_of_broker_nodes
  enhanced_monitoring    = var.enhanced_monitoring


  broker_node_group_info {
    instance_type = var.instance_type
    client_subnets = var.vpc_private_subnets
    security_groups = [aws_security_group.msk_sg.id]

    storage_info {
      ebs_storage_info {
        volume_size = var.ebs_storage_volume_size
      }
    }

  }

  encryption_info {
    encryption_in_transit {
      client_broker = "TLS"
      in_cluster    = true
    }
  }

  open_monitoring {
    prometheus {
      jmx_exporter {
        enabled_in_broker = true
      }
      node_exporter {
        enabled_in_broker = true
      }
    }
  }

  client_authentication  {
    sasl {
      iam = true
      scram = true
    }
  }

  logging_info {
    broker_logs {
      cloudwatch_logs {
        enabled   = true
        log_group = aws_cloudwatch_log_group.cloudwatch_msk.name
      }
    }
  }
}
```

**Comment by yotam-h** [comment]
I also see this on the documentation for the [aws_msk_cluster resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster#bootstrap_brokers_tls)
`AWS may not always return all endpoints so the values may not be stable across applies.`

**Comment by justinretzolk** [comment]
Hey @yotam-h 👋 It's starting to look like this is more of a configuration thing than a bug with the provider. You may have better luck asking in the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws), as we try to keep GitHub scoped to feature requests and bugs within the provider.

**Comment by xxd-frever** [comment]
Depending on the MSK configuration, it could be "[bootstrap_brokers_sasl_iam](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster#bootstrap_brokers_sasl_iam)", if `client_authentication` is set to use `iam`.

**Comment by GreggSchofield** [comment]
Hi @yotam-h  👋 Just wanted to confirm that the root-cause of the issue(s) above are from a misconfiguration rather than a bug with this terraform provider.

Given that both i) the `aws_msk_cluster` resource has iam authentication enabled with the following argument:
```terraform
client_authentication  {
  sasl {
    iam = true
    scram = true
  }
}
```

and the `aws_mskconnect_connector` resource has the following argument:

```terraform
kafka_cluster_client_authentication {
  authentication_type = "IAM"
}
```

the `aws_msk_cluster.msk_cluster.bootstrap_brokers_public_sasl_iam` attribute value should be used as input to the `aws_mskconnect_connector. kafka_cluster. apache_kafka_cluster. bootstrap_servers`.

Note that the `aws_msk_cluster.msk_cluster.bootstrap_brokers_tls` value currently being used is suitable for client applications writing messages directly to brokers over an SSL/TLS.

Let me know if you have any more issues - more than happy to debug with you!
