### ISSUE TITLE
Save the eks cluster creator role/user in tfstate

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#26829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please save the eks cluster creator role/user in the tfstate so when the kube auth config map is deleted, we'll know exactly which role to assume to recreate the auth config map.

Right now, we have to dig through ancient cloudtrail logs for `ClusterCreator` to find the role or create an aws support ticket per cluster.

### New or Affected Resource(s)

* aws_eks_cluster

### Potential Terraform Configuration

```hcl
resource "aws_eks_cluster" {
  # ...
}
```

### References

- N/A

**Comment by mattburgess** [comment]
Looking at your linked ticket, I think the proposal there is pretty good! The trouble with implementing this on the `aws_cluster` resource is that there isn't API support for holding this kind of information.

The other option is for you to store that information in the tags of the aws cluster rather than having a separate resource. Sure, they'll obviously disappear when the cluster is deleted, but presumably you're using a Terraform state backend with versioning/backups so you could retrieve the old tag values from those?

**Comment by bryantbiggs** [comment]
FYI - This will not be necessary once https://github.com/aws/containers-roadmap/issues/185#issuecomment-1569048009 has arrived

**Comment by bryantbiggs** [comment]
@nitrocode can we close this out now given that using cluster access entries will give you full control over viewing and editing who has permission within the cluster?

**Comment by nitrocode** [comment]
Sounds good to me. Thank you
