### ISSUE TITLE
[Bug]: EKS Master Node is unreachable on existing VPC but works perfectly fine on any other VPC

### ISSUE THREAD

**Issue by GGSHAH** [hashicorp/terraform-provider-aws#26842]
### Terraform Core Version

~> 1.2.0

### AWS Provider Version

~> 4.0

### Affected Resource(s)

I'm basically trying to spin up EKS using Terraform on my VPC which is having a CIDR of 10.0.0.0/16. When defining the EKS through terraform, I'm also defining the K8's network config and assigning it a CIDR of 172.16.0.0/12 . But the issue is that it creates the cluster though but nodegroups are unable to join the cluster and also I'm not able to issue kubectl commands from my terminal as it gets timeout error.

But if I try everything same with any other VPC, everything works perfectly fine. Is it because of my VPC CIDR clashing with k8's CIDR ? I read terraform EKS documentation and it said that k8 is assigned a default CIDR from one of these CIDRS : 10.0.0.0/8, 172.16.0.0/12, or 192.168.0.0/16.

When EKS gets created and when i check it through the console, it shows K8 CIDR is the same which i have passed it i.e 172.16.0.0/12 . I'm just not sure what exactly the issue is. DNS support is also enabled. We have many other resources in same VPC so we dont really want a new VPC for this and want to deploy EKS on this VPC of CIDR 10.0.0.0/16 .

Using Kubernetes version 1.22.

Can anyone help with this ?

### Expected Behavior

It should have been able to create the cluster without any issues just like in any other vpc

### Actual Behavior

Worker Nodes are not able to join the cluster.  Also, Cant issue kubectl commands from my terminal as i get timeout error when i issue any kubectl command.  Everything works perfectly fine if any other VPC CIDR is used.

### Terraform Configuration Files

# Snippet of Cluster.tf File

  version = 1.22

  vpc_config {
    subnet_ids = [var.cluster_sn,var.cluster_sn2]   #these are private subnets variables being passed to it.

    endpoint_private_access = true
    endpoint_public_access  = false
    public_access_cidrs     = ["0.0.0.0/0"]

  }

  kubernetes_network_config {
    service_ipv4_cidr = "172.16.0.0/12"
    ip_family         = "ipv4"
  }

### Steps to Reproduce

Use VPC CIDR as 10.0.0.0/16 and define any k8 CIDR outside VPC CIDR and then try to spin up EKS cluster

**Comment by justinretzolk** [comment]
Hey @GGSHAH 👋 Thanks for taking the time to open this issue. It looks like this may be more of a configuration issue, rather than a bug with the provider. This forum is intended to be used for feature enhancements and bugs in the AWS Provider - so that we can maintain focus on that, we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue, but I believe you should be able to get an answer for this using one of the Community Resources, such as Stack Overflow or [the AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws).
