### ISSUE TITLE
Please add support for S3 Glacier Flexible Retrieval storage class

### ISSUE THREAD

**Issue by GonzaloHirsch** [hashicorp/terraform-provider-aws#26874]
### Description

Right now the Terraform S3 resources for buckets and lifecycle configuration rules do not support the S3 Glacier Flexible Retrieval storage class.

You can see more details about the configuration for lifecycle policies using that storage class [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-transition-general-considerations.html).

Right now I have a use case where that storage class would be useful but we cannot do it via Terraform because it's not present. Or at least not present in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration#storage_class).

**Comment by tkyocum** [comment]
Since "Glacier Flexible Retrieval" is just the old Glacier tier, [renamed](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-glacier-storage-class-amazon-s3-glacier-flexible-retrieval/), would it not be feasible for you to use `GLACIER`? The `storage_class` should probably be renamed `GLACIER_FR` to avoid confusion , but that's outside the scope of this issue.

**Comment by GonzaloHirsch** [comment]
@tkyocum I believe you are right, the different names might've confused me. Apologies and thanks for clearing that up.
