### ISSUE TITLE
[Bug]: Unable to save `IgnoreHeaderRows` setting in aws_dms_endpoint

### ISSUE THREAD

**Issue by polyamide** [hashicorp/terraform-provider-aws#26957]
### Terraform Core Version

1.2.0

### AWS Provider Version

4.31.0

### Affected Resource(s)

- aws_dms_endpoint

### Expected Behavior

Be able to apply `IgnoreHeaderRows` setting in a s3 DMS endpoint.

### Actual Behavior

`IgnoreHeaderRows` setting did not saved.

### Relevant Error/Panic Output Snippet

```shell
# aws_dms_endpoint.source_s3_demo_data_source will be updated in-place
  ~ resource "aws_dms_endpoint" "source_s3_demo_data_source" {
        id                          = "source-s3-demo-data-source"
        tags                        = {}
        # (7 unchanged attributes hidden)

      ~ s3_settings {
          ~ ignore_headers_row               = 0 -> 1
            # (30 unchanged attributes hidden)
        }
    }
```

### Terraform Configuration Files

```
resource "aws_dms_endpoint" "source_s3_demo_data_source" {
  endpoint_id   = "source-s3-demo-data-source"
  endpoint_type = "source"
  engine_name   = "s3"

  s3_settings {
    bucket_name               = "demo-bucket"
    bucket_folder             = ""
    ignore_headers_row        = 1
    compression_type          = "NONE"
    data_format               = "csv"
    csv_delimiter             = ","
    external_table_definition = jsonencode({
      "TableCount" = 0,
      "Tables" = []
    })
    service_access_role_arn   = aws_iam_role.dms_s3_demo_data_source.arn
  }
}

resource "aws_iam_role" "dms_s3_demo_data_source" {
  assume_role_policy = data.aws_iam_policy_document.dms_assume_role.json
  name               = "dms-s3-demo-data-source"
}

data "aws_iam_policy_document" "dms_assume_role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      identifiers = ["dms.amazonaws.com"]
      type        = "Service"
    }
  }
}
```

### Steps to Reproduce

1. Apply the resource
2. Apply the resource, again.
3. Output will always showing `ignore_headers_row` will be updated. Viewing that endpoint on AWS Console also says that `IgnoreHeaderRows` is not present.

### Important Factoids

I'm pretty sure there's a typo in `s3_settings`'s schema:

https://github.com/hashicorp/terraform-provider-aws/blob/3c691a0a3f6ae42c95e502fd6dd58270067921fc/internal/service/dms/endpoint.go#L561-L566

It is supposed to be `ignore_header_rows`, NOT `ignore_headers_row`. Code below that all use ignore_header_rows correctly.

"IgnoreHeaderRows" is the correct name for this setting, according to [AWS documataions](https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html).

**Comment by justinretzolk** [comment]
Hey @polyamide 👋 Thank you for taking the time to raise this, and for pointing out that typo; I believe that is indeed the issue here. For whoever picks this up:

- [Schema definition](https://github.com/hashicorp/terraform-provider-aws/blob/3c691a0a3f6ae42c95e502fd6dd58270067921fc/internal/service/dms/endpoint.go#L561-L566) -- (`"ignore_headers_row"`)
- [expander definition](https://github.com/hashicorp/terraform-provider-aws/blob/3c691a0a3f6ae42c95e502fd6dd58270067921fc/internal/service/dms/endpoint.go#L1872-L1874) - (`"ignore_header_rows"`)
- [flattener definition](https://github.com/hashicorp/terraform-provider-aws/blob/3c691a0a3f6ae42c95e502fd6dd58270067921fc/internal/service/dms/endpoint.go#L1991-L1993) -- (`"ignore_header_rows"`)
