### ISSUE TITLE
Add AWS Lightsail DNS Entry Support

### ISSUE THREAD

**Issue by tankertuf** [hashicorp/terraform-provider-aws#2731]
Hi there,

Would it be possible to add support for adding/removing DNS records to Lightsail domains?

API references:
https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_CreateDomainEntry.html
https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_DeleteDomainEntry.html

Thank you,
John

**Comment by bflad** [comment]
Hi @tankertuf, thanks for submitting the feature request! Double checking the AWS Go SDK, its certainly supported: https://docs.aws.amazon.com/sdk-for-go/api/service/lightsail/

Given the holidays and other priorities, the Terraform team at HashiCorp won't be able to work on this in the near future, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to this comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by dereknex** [comment]
Does anyone working it?

**Comment by arenstar** [comment]
Yes please!!! id like to see this feature too

**Comment by joakiboxxx** [comment]
I'm considering putting in some effort towards implementing better Lightsail support. Should Lightsail be a part of the AWS provider, or perhaps split into a separate provider? @bflad?

**Comment by benfortuna** [comment]
@joakiboxxx  As lightsail product is competing with the likes of Digital Ocean I think splitting to separate provider could be justified.

**Comment by imansilla** [comment]
i'm waiting for this :)

**Comment by Rendanic** [comment]
Are there any news?

**Comment by brittandeyoung** [comment]
@Rendanic 
For Awareness I have begun work on creating a separate AWS lightsail provider in order to help with Speeding up contributions and to give it dedicated attention. 

The Github repo is located here: https://github.com/DeYoungTech/terraform-provider-awslightsail

The provider and documentation is published here: https://registry.terraform.io/providers/DeYoungTech/awslightsail/latest

With the most recent version, I have added support for the `domain_entry`  resource.

If you want to start using this resource now, feel free to check it out and provide feedback.

**Comment by jackivanov** [comment]
no more updates?
