### ISSUE TITLE
[Bug]: aws_sns_platform_application will be updated in-place after a successful terraform import

### ISSUE THREAD

**Issue by edbighead** [hashicorp/terraform-provider-aws#27423]
### Terraform Core Version

1.2.9

### AWS Provider Version

4.36.1

### Affected Resource(s)

* aws_sns_platform_application

### Expected Behavior

Tried to `terraform import` manually created resources after https://github.com/hashicorp/terraform-provider-aws/pull/23147 was implemented. 

After a successful terraform import, expected `No changes. Your infrastructure matches the configuration.`

### Actual Behavior

Resource will be modified in place, `platform_credential` and `platform_principal` are trying to be added

### Terraform Configuration Files

```hcl
resource "aws_sns_platform_application" "apple_push_notification" {
  name                             = "my_app"
  platform                         = "APNS"
  platform_credential              = file("./AppKey.p8")
  platform_principal               = "XXX"
  apple_platform_team_id           = "XXXXX"
  apple_platform_bundle_id         = "com.xxx.app"
}
```

### Steps to Reproduce

Run import
```
terraform import aws_sns_platform_application.apple_push_notification "arn:aws:sns:xxx:yyy:app/APNS/my_app"
```
Import ran successful
```
aws_sns_platform_application.apple_push_notification: Import prepared!
  Prepared aws_sns_platform_application for import
aws_sns_platform_application.apple_push_notification: Refreshing state... [id=arn:aws:sns:xxx:yyy:app/APNS/my_app]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

Run plan
```
terraform plan
...
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_sns_platform_application.apple_push_notification will be updated in-place
  ~ resource "aws_sns_platform_application" "apple_push_notification" {
        id                               = "arn:aws:sns:xxx:yyy:app/APNS/my_app"
        name                             = "my_app"
      + platform_credential              = (sensitive value)
      + platform_principal               = (sensitive value)
        # (8 unchanged attributes hidden)
    }
```

### Important Factoids

Token-based authentication was just recently added in `4.36.0`
https://github.com/hashicorp/terraform-provider-aws/pull/23147

### Would you like to implement a fix?

No

**Comment by edbighead** [comment]
maybe @mdrobny or @ewbankkit want to take a look since they implemented it 👀

**Comment by ewbankkit** [comment]
@edbighead Thanks for raising this issue 👏.

This behavior occurs because the AWS API does not return `platform_credential` or `platform_principal` when [retrieving platform application attributes](https://docs.aws.amazon.com/sns/latest/api/API_GetPlatformApplicationAttributes.html) and hence the values of those attributes cannot be set in Terraform state during resource import.
Our import acceptance tests get around this by [ignoring those attributes](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/import#importstateverifyignore-1).
Practitioners should use the [`lifecycle`/`ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) "meta-argument" to prevent resource update.

**Comment by edbighead** [comment]
@ewbankkit thanks for checking! I will use [lifecycle/ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes)

Closing this issue as this comes from AWS API
