### ISSUE TITLE
[Bug]: Error: unexpected format for ID (arn:aws:events:eu-west-1:xxx:event-bus/aws.partner/auth0.com/xxx/auth0.logs/terraform-20221024154539698300000003), expected EVENTBUSNAME/RULENAME or RULENAME

### ISSUE THREAD

**Issue by dascar5** [hashicorp/terraform-provider-aws#27457]
### Terraform Core Version

1.3.3

### AWS Provider Version

4.36.1

### Affected Resource(s)

aws_cloudwatch_event_rule

### Expected Behavior

Expected behavior is for it to actually deploy properly.

### Actual Behavior

Every other resource deploys fine, except the rules themselves.
They throw the error snippet I posted below, complaining about format. There was this issue (https://github.com/hashicorp/terraform-provider-aws/issues/18431) that implies this was solved with a newer version, but using the latest of everything (TF, auth0 provider, aws provider) - doesn't fix this problem - and I tried various version. The format is correct, as I have tried leaving the name field blank (so it autogenerates), and I also used my own custom name (sign-up-rule). The results are the same.

### Relevant Error/Panic Output Snippet

```shell
│ Error: unexpected format for ID (arn:aws:events:eu-west-1:xxx:event-bus/aws.partner/auth0.com/xxx/auth0.logs/terraform-20221024154539697900000002), expected EVENTBUSNAME/RULENAME or RULENAME
│ 
│   with aws_cloudwatch_event_rule.successful_sign_up_rule,
│   on auth0-log-stream.tf line 95, in resource "aws_cloudwatch_event_rule" "successful_sign_up_rule":
│   95: resource "aws_cloudwatch_event_rule" "successful_sign_up_rule" {
```

### Terraform Configuration Files

```
resource "aws_cloudwatch_event_rule" "successful_sign_up_rule" {
  name           = "Auth0-Successful-Sign-up-Rule"
  description    = "Auth0 User Successfully signed up"
  event_bus_name = aws_cloudwatch_event_bus.event_bridge_event_bus.name
  event_pattern  = <<EOF
  {
    "detail-type": [
      "ss"
    ]
  }
EOF
}
```

### Steps to Reproduce

`terraform apply`

### Important Factoids

There is nothing special about my configuration.

**Comment by vitorf7** [comment]
@kaisermario my PR fixes this issue. Once it gets approved and merged in it should hopefully help you get everything sorted. If you are however in a pinch and wanna solve your problem sooner, then you could clone my branch locally and follow the guidelines on how to do local development from here https://hashicorp.github.io/terraform-provider-aws/development-environment/

I was personally facing some trouble when trying to use it since at work we had the terraform plan and terraform apply run from the docker image provided by hashicorp and my own machine is an Mac M1 which means the make build command from the makefile (in the terraform-provider-aws repo) would build an arch64 instead of a linux amd64.

After running env GOOS=linux GOARCH=amd64 go build ., then moving the built binary to the $GOPATH/bin and making sure that both the $GOPATH/bin and my ~/.terraformrc were both mounted to the correct places in the docker image, it all worked fine.

I was able to finally finish the work I was doing and it also meant that I not longer go the error you and I faced.
Hopefully someone like @ewbankkit will be able to pick up that PR and merge that in soon.
