### ISSUE TITLE
[Enhancement]: Terraform only allowing me to add up to 4 additional security groups

### ISSUE THREAD

**Issue by nusaputra137** [hashicorp/terraform-provider-aws#27582]
### Description

Running into this error when applying with terraform

│ Error: error running EMR Job Flow: ValidationException: Maximum number(4) of security groups exceeded for AdditionalMasterSecurityGroups.
│ 	status code: 400, request id: 28be5008-17b9-422a-86a6-daa5785ba584

Code:
additional_master_security_groups = tostring(join(",", [sg_1, sg_2, sg_3, sg_4, sg_5]))

I checked with my SG team and we have a maximum of 11 allowed. I am wondering if there is an error on the terraform EMR side that doesn't allow users to add more than 4 security groups.

### Affected Resource(s) and/or Data Source(s)

aws_emr_cluster

**Comment by justinretzolk** [comment]
Hey @nusaputra137 👋 Thank you for taking the time to open this! It looks like the error you're receiving is coming from the AWS API, rather than from Terraform. In looking into it, I found [this document](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-additional-sec-groups.html) that mentions:

> You can apply up to four additional security groups for the master instance, four for core and task instances, and four for service access (in private subnets).

I'm not familiar with these limits, but based on that document and the error coming from the API, I suspect this isn't a bug with the provider, but rather an AWS limitation.

**Comment by nusaputra137** [comment]
Oh I see. Thanks for finding that. Will go ahead and close out this ticket!
