### ISSUE TITLE
VPC Endpoint service principal

### ISSUE THREAD

**Issue by robh007** [hashicorp/terraform-provider-aws#27599]
### Description

AWS introduced tagging on VPC endpoint service principals & connections recently. The tags are implemented via the `ec2_tags` resource, they are not present on the `aws_vpc_endpoint_service_allowed_principal` resource API call. The ID generated by the initial implementation of this resource looks now to be incorrect.

https://github.com/hashicorp/terraform-provider-aws/blob/f9f3756613066b678044829321a08184bc9795a0/internal/service/ec2/vpc_endpoint_service_allowed_principal.go#L52

I think the original API didn't return a valid ID to be used for the resource. When you create an association within an endpoint principal now a `servicePermissionId` is returned in the response. This ID can be used via `ec2_tags` to apply tags to the allowed principal resource. 

I didn't know either to log this as a bug or a feature request. So I choose neither :smi

### Would you like to implement a fix?

Yes

**Comment by robh007** [comment]
@justinretzolk is there any chance this could be reviewed. It's a really really small change. Thanks.

**Comment by justinretzolk** [comment]
Hey @robh007 👋 Thank you for checking in on this! Unfortunately I can't provide an ETA on when this will be reviewed/merged due to the potential of shifting priorities. We prioritize by count of :+1: reactions and a few other things (more information on our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) if you're interested).
