### ISSUE TITLE
[Enhancement]: aws_codebuild_project to support build_status_config for primary source

### ISSUE THREAD

**Issue by bob-rohan** [hashicorp/terraform-provider-aws#27619]
### Description

aws_codebuild_project to support build_status_config for primary source. This can be used to set the context attribute, which is posted back to source provider and shows as name for status check (I'm using Github Enterprise).

### Affected Resource(s) and/or Data Source(s)

* aws_codebuild_project

### Potential Terraform Configuration

```terraform
resource "aws_codebuild_project" "example" {
  name          = "test-project"
  [...]
  source {
    type            = "GITHUB"
    location        = "https://github.com/mitchellh/packer.git"
    git_clone_depth = 1

    git_submodules_config {
      fetch_submodules = true
    }
    build_status_config = {
      context = "test-project-lint"
      # optional target_url
    }
  }
```

### References

https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSource.html

**Comment by DrFaust92** [comment]
im missing something because i see `build_status_config` is already supported

**Comment by justinretzolk** [comment]
Hey @bob-rohan 👋 Thank you for taking the time to raise this! As @DrFaust92 mentioned above, support for `build_status_config` was [introduced with version 3.38.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3380-april-30-2021) of the provider, so you'll need to be running at least that version in order to use the `build_status_config` argument.

Given that this argument exists in the resource already, we'll close this issue out. If you feel we've done this in error, please do let us know.

**Comment by bob-rohan** [comment]
@justinretzolk  @DrFaust92  thanks for your replies, I missed this notification.

Please see here, as explained above, the request relates to the primary `source` block where `build_status_config` is not supported. It's available for `secondary_sources` block(s) only.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project#source

Please may you point out my error, or reopen request for enhancement. Thanks
