### ISSUE TITLE
[Docs]: `aws_dms_endpoint.cdc_min_file_size` should be in Megabytes and stated default should be 32,000

### ISSUE THREAD

**Issue by alordthorsen** [hashicorp/terraform-provider-aws#27688]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#cdc_max_batch_interval

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#cdc_max_batch_interval

### What is the docs issue?

[cdc_min_file_size is listed in megabytes with a default of](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#cdc_max_batch_interval) 32. My team set the value to 400 (in an attempt to get 400 MB files) and we ended up with 400 KB file sizes. If you look at the [AWS Docs for cdcMinFileSize](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.Configuring) under the configuration page you'll see 

> Minimum file size condition as defined in kilobytes to output a file to Amazon S3.

> Default Value: 32000 KB

> When cdcMinFileSize is specified and cdcMaxBatchInterval is specified, the file write is triggered by whichever parameter condition is met first.

Which is a strong contradiction from the Terraform docs on this option.

### Proposal

Change `kilobytes` to `megabytes` and `32` to `32000`.

Specifically

```
[cdc_min_file_size](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#cdc_min_file_size) - (Optional) Minimum file size, defined in kilobytes, to reach for a file output. Default is 32000.
```

### References

https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.Configuring

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
This is an interesting issue that I think might warrant more than a documentation change, so I'm glad you brought it up! In looking into this I found some interesting discrepancies; I think something may have changed with the API at some point.

The `aws_dms_endpoint` resource [sets a default setting of](https://github.com/hashicorp/terraform-provider-aws/blob/8cf3fa1a336a366c960110647f8d043aa09f4c12/internal/service/dms/endpoint.go#L461-L466) `32` for the the `cdc_min_file_size` argument, and the documentation calls out that this is in megabytes. It does this because [the Go SDK documents the same value as the default](https://docs.aws.amazon.com/sdk-for-go/api/service/databasemigrationservice/#S3Settings): 

```go
    // Minimum file size, defined in megabytes, to reach for a file output to Amazon
    // S3.
    //
    // The default value is 32 MB.
    CdcMinFileSize *int64 `type:"integer"`
```

Looking at the [API documentation](https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html) is what clued me in that this may be a situation where the API has changed. It states:

```plaintext
CdcMinFileSize
Minimum file size, defined in kilobytes, to reach for a file output to Amazon S3.

The default value is 32 MB.
```

Note that it says "kilobytes" in the first line, but still shows a default value of `32 MB`. Moving on to the [reference you linked](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.Configuring), we see what you mentioned:

```plaintext
cdcMinFileSize
Minimum file size condition as defined in kilobytes to output a file to Amazon S3.

Default Value: 32000 KB
```

I suspect that what will need to happen is that the default value (for the Terraform resource) should be updated to `32000` and the documentation should be updated to say `kilobytes` rather than `megabytes`. I'd like to leave that determination to whomever picks this up to investigate it.
