### ISSUE TITLE
[Bug]: aws_kinesis_firehose_delivery_stream destroy doesn't clear created ENI's when used with elasticsearch

### ISSUE THREAD

**Issue by RestfulBlue** [hashicorp/terraform-provider-aws#27696]
### Terraform Core Version

1.0.8

### AWS Provider Version

3.66.0

### Affected Resource(s)

aws_kinesis_firehose_delivery_stream

### Expected Behavior

We manage our entire infra in aws using terraform, starting from vpcs/subnets. Recently we tried to use `aws_kinesis_firehose_delivery_stream` to index data to es. `aws_kinesis_firehose_delivery_stream` creates a bunch of ENI's in our VPC, which is expected. But during destroy these ENI's aren't destroyed and they block destroy of vpcs/subnets :(

### Actual Behavior

ENI's created by aws_kinesis_firehose_delivery_stream with elasticsearch vpc aren't destroyed during destroy 

As far as i understand, that problem makes it impossible to use `aws_kinesis_firehose_delivery_stream` with es vpc right now :( 

### Terraform Configuration Files

```
resource "aws_kinesis_firehose_delivery_stream" "kinesis-es-firehose" {
  name        = var.stream_name
  destination = "elasticsearch"

  kinesis_source_configuration {
    kinesis_stream_arn = aws_kinesis_stream.this.arn
    role_arn           = aws_iam_role.firehose_role.arn
  }

  s3_configuration {
    role_arn           = aws_iam_role.firehose_role.arn
    bucket_arn         = var.s3_backup_bucket_arn
    buffer_size        = var.es_buffering_size
    buffer_interval    = var.es_buffering_interval
    compression_format = "GZIP"
  }

  elasticsearch_configuration {
    domain_arn            = var.es_domain_arn
    role_arn              = aws_iam_role.firehose_role.arn
    index_name            = var.index_name
    buffering_interval    = var.es_buffering_interval
    buffering_size        = var.es_buffering_size
    index_rotation_period = "NoRotation"

    vpc_config {
      subnet_ids         = var.subnet_ids
      security_group_ids = var.security_group_ids
      role_arn           = aws_iam_role.firehose_role.arn
    }
  }
}
```

### Steps to Reproduce

just create kinesis firehose with es

**Comment by sgrmz** [comment]
I ran into exactly the issue described here. Differences in my scenario:

- destination = "opensearch"
- Terraform version = 1.4.5
- AWSProvider version = 4.67.0

I was wondering why there were only quite few thumbs-up on this issue. So I did more investigation. On my side I was able to fix the issue by making sure that the needed permissions are really kept until the full completion of the deprovisioning of the `aws_kinesis_firehose_delivery_stream`. These permissions are at least:
- "ec2:DescribeVpcs",
- "ec2:DescribeVpcAttribute",
- "ec2:DescribeSubnets",
- "ec2:DescribeSecurityGroups",
- "ec2:DescribeNetworkInterfaces",
- "ec2:CreateNetworkInterface",
- "ec2:CreateNetworkInterfacePermission",
- "ec2:DeleteNetworkInterface"

I just added an explicit respective RolePolicyAttachment dependency to the `aws_kinesis_firehose_delivery_stream`. Since then ENIs are cleanly removed by Terraform.

I just wanted to share this, as it may help someone facing the issue. Also, possibly there is no bug at all.

**Comment by RestfulBlue** [comment]
yes, indeed :) 
fixed it the same way, forgot to update issue
thanks for your answer!
