### ISSUE TITLE
[Bug]: `associate_public_ip_address` in `aws_launch_template` has string type but docs state boolean

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-provider-aws#27716]
### Terraform Core Version

1.2.8

### AWS Provider Version

4.38.0

### Affected Resource(s)

`aws_launch_template`

### Expected Behavior

[Docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#associate_public_ip_address) state this attribute is a boolean, but Terraform provider schema returns string.

### Actual Behavior

Schema specifies type as string instead of boolean.

### Terraform Configuration Files

```
terraform {
  required_providers {
    name = {
      source = "aws"
      version = "4.38.0"
     }
  }
}
```

### Steps to Reproduce

```
> terraform init
# ...
> terraform providers schema -json | jq '.provider_schemas["registry.terraform.io/hashicorp/aws"].resource_schemas.aws_launch_template.block.block_types.network_interfaces.block.attributes.associate_public_ip_address'
{
  "type": "string",
  "description_kind": "plain",
  "optional": true
}
```

### References

* https://github.com/hashicorp/terraform-cdk/issues/2263

**Comment by douglasflagg** [comment]
After re-reading the issue I came away with the idea that to fix we would need to update the implementation to match the docs so changing the string -> bool. Let me know if that is not a reasonable interpretation or approach to the issue and I would be happy to change the approach.

**Comment by pauly4it** [comment]
Ran into this bug recently. Is there anything blocking getting the bugfix PR approved and merged?

**Comment by gdavison** [comment]
The field `associate_public_ip_address` is an optional Boolean value (see https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateInstanceNetworkInterfaceSpecification.html), so we need to account for three states: unset, `true`, or `false`. Because of an implementation detail with the `terraform-plugin-sdk/v2`, we can't differentiate between `false` and unset, as described at https://developer.hashicorp.com/terraform/plugin/framework-benefits#significantly-improved-data-access.

The code currently "simulates" a nullable Boolean value by using a string value that can be either empty, `"true"`, or `"false"`, and treating the empty string as an unset value.

Once we are able to update this resource implementation to use `terraform-plugin-framework`, we will be able to use an actual boolean value for this field.

We will update the documentation to more clearly indicate that the field is optional.
