### ISSUE TITLE
[Bug]: InvalidParameterCombination: The requested instance class is not supported by global databases: db.t4g.medium

### ISSUE THREAD

**Issue by anuwarrier** [hashicorp/terraform-provider-aws#27736]
### Terraform Core Version

1.3.3

### AWS Provider Version

4.38.0

### Affected Resource(s)

aws_rds_cluster_instance:

I am creating a new Global Aurora postgres cluster and selected the instance class supported by AWS. One of the example instance class i selected is db.t4g.medium.

### Expected Behavior

I should be able to create Global Aurora instance postgres with db.t4g.medium class machine

### Actual Behavior

When i run terraform apply it is erroring out with below error message 
 Error: creating RDS Cluster (auroratest1-first) Instance (auroratest1-first-1): InvalidParameterCombination: The requested instance class is not supported by global databases: db.t4g.medium
│       status code: 400, request id: f17432ac-3692-4435-9c76-3b7de2c85c1f

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: creating RDS Cluster (auroratest1-first) Instance (auroratest1-first-1): InvalidParameterCombination: The requested instance class is not supported by global databases: db.t4g.medium
│       status code: 400, request id: f17432ac-3692-4435-9c76-3b7de2c85c1f
│ 
│   with aws_rds_cluster_instance.global_primary[0],
│   on aurora.tf line 141, in resource "aws_rds_cluster_instance" "global_primary":
│  141: resource "aws_rds_cluster_instance" "global_primary" {
│
```

### Terraform Configuration Files

```terraform
resource "aws_rds_cluster_instance" "global_primary" {
  count                             = var.primary_pgsql_count
  provider                          = aws.primary
  engine                            = aws_rds_cluster.global_primary.engine
  engine_version                    = aws_rds_cluster.global_primary.engine_version
  identifier                        = "${local.primary_cluster_identifier}-${count.index + 1}"
  cluster_identifier                = aws_rds_cluster.global_primary.id
  auto_minor_version_upgrade        = var.pgsql_minor_upgrade
  instance_class                    = "db.t4g.medium"
  db_parameter_group_name           = aws_db_parameter_group.global_primary_pgsql.id
  db_subnet_group_name              = aws_db_subnet_group.primary_pgsql_subnet_group.name
  tags                              = local.tags
}
```

### Steps to Reproduce

Try to create a new Global Aurora Postgres instance with instance class db.t4g.medium and run terraform apply

**Comment by justinretzolk** [comment]
Hey @anuwarrier 👋 Thank you for taking the time to raise this! It looks like the error you're receiving is coming from the AWS API, rather than a bug with the AWS Provider for Terraform. In looking into it a bit, I found that AWS states that [Aurora global databases require memory optimized instance classes](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-getting-started.html#aurora-global-database.configuration.requirements), while `db.t4g` are [burstable instance classes](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Types), which I believe is the issue here.
