### ISSUE TITLE
[Docs]: Ingress/Egress Rule (In Security Group) Not Created Without Optional CIDR Block Parameter

### ISSUE THREAD

**Issue by DC4JG** [hashicorp/terraform-provider-aws#27820]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group

### Description

If you create a security group with ingress/egress inside but without the CIDR block parameter (which is marked as optional) Terraform will create a security group in AWS without any ingress/egress rules. This results in blocking all traffic.

I couldn't find this behavior documented on the page and my assumption was that it defaults to allow all traffic or use the specified VPC's CIDR block. Maybe this parameter is optional in another use case but I'd suggest adding a note to avoid other people encountering this issue.

Normally "required" correlates with "resource can't be created without" and if something is missing to create a resource Terraform will complain. In this scenario neither applies and the written ingress/egress gets ignored.

**Comment by dev-slatto** [comment]
Hey @DC4JG! 

I've created a PR #28239 that adds a note informing that without a CIDR block the traffic will be blocked. This is intended behavior, and the reason for it being an optional parameter is so that you're not required to have a IPv4 CIDR creating a security group only doing IPv6 or referencing other security groups. 

Hopes this gives some insight and please have a look at ´NOTE on Egress rules` in the documentation to see the explanation of why this is happening 😃
