### ISSUE TITLE
resource/aws_dynamodb_table: Perpetual diff for encrypted replicas with default keys

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#27850]
### Terraform Core Version

N/A

### AWS Provider Version

4.39.0

### Affected Resource(s)

* aws_dynamodb_table

### Expected Behavior

When a DynamoDB is created with replicas and encryption enabled with default keys, a perpetual diff is reported for the `kms_key_arn`

### Actual Behavior

No diff is reported

### Terraform Configuration Files

```terraform
resource "aws_dynamodb_table" "example" {
  name             = "example"
  hash_key         = "TestTableHashKey"
  billing_mode     = "PAY_PER_REQUEST"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "TestTableHashKey"
    type = "S"
  }

  replica {
    region_name = data.aws_region.alternate.name
  }

  server_side_encryption {
    enabled = true
  }
}
```

### Steps to Reproduce

* `terraform apply`
* `terraform plan`

### References

May be related to #25812 and #26552

**Comment by YakDriver** [comment]
The problem here came from a sort of perfect storm:
1. `replica` is a set of schema, making custom diff handling tricky if you're looking at schema elements specifically (clearing diff on a block argument in a set is non-trivial)
1. The overall `replica` is _not_ computed so a diff cannot be cleared at the block level.
1. The diff is caused because if you enable server side encryption and send nothing to AWS in `aws_key_arn`, which means to use the default AWS-managed DynamoDB KMS key `alias/aws/dynamodb`, then AWS responds with ARN of _that_ key in `aws_key_arn`.
1. `replica` cannot be changed to `computed` because then when `replica` is absent, the provider will not update in the specific situation where you remove all `replica` blocks when you previously had some, as was the previous behavior (breaking change).

The solution: Don't populate `aws_key_arn` with default keys.

**Comment by ankon** [comment]
Thanks a lot for the clear explanation, @YakDriver -- this helps a lot for reviewing changelogs when updating the provider in production!

**Comment by virtualdom** [comment]
Hi, I'm still seeing this issue on 4.55 -- has this been fixed?
