### ISSUE TITLE
[Enhancement]: aws_elasticache_replication_group redis 7 support

### ISSUE THREAD

**Issue by chrisjungsw** [hashicorp/terraform-provider-aws#27918]
### Description

When I try to add a aws_elasticache_replication_group with engine_version = 7.0, I get this error
"Error: engine_version: Redis versions must match major.minor when using version 6 or higher". (hashicorp/aws v4.40.0)

When will support for redis 7 be added? It's already supported by AWS's elasticache.

For now we don't need the 7 features in terraform, we only need to add v7 clusters. So maybe the fix is just changing a regex or so for now?

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/27709.

**Comment by JustinPlute** [comment]
any traction on this?

**Comment by avinashbhatv** [comment]
IAM auth with redis 7 is possible from terraform? I couldn't succeed with the latest version of terraform. 
pls let us know when this will be available?

Thanks

**Comment by kwong0222** [comment]
I think the issue here is with AWS API:

Using the AWS CLI, `aws elasticache describe-cache-engine-versions --engine redis --region us-west-2` returns the list of supported Redis engine versions and we can see redis 7 is listed. 

However, when we specifically ask for the latest redis7 version, we get an empty array:

`aws elasticache describe-cache-engine-versions --engine redis --region us-west-2 --engine-version 7.x` 

Changing `7.x` to `6.x` in the above command returns the latest redis6 version as expected.

**Comment by gdavison** [comment]
Hi @chrisjungsw, can you share your terraform configuration, please? I'm not able to reproduce this when I set `engine_version = "7.0"`

**Comment by robburger** [comment]
Just ran into this now as well - can confirm it seems to be an AWS API inconsistency/design.

Setting `engine_version = "7.x"` in the `aws_elasticache_replication_group` resource results in:

```
Error: error creating ElastiCache Replication Group (redis): InvalidParameterCombination: Cannot find version 7.x for redis
```

Seems like the *only* version that returns the latest minor version when supplying `.x` is Redis v6. Likely because Redis v6 is the only version available that has more than one minor version available.

AWS CLI:
```
$ aws elasticache describe-cache-engine-versions --engine redis --engine-version 3.x
{
  "CacheEngineVersions": []
}

$ aws elasticache describe-cache-engine-versions --engine redis --engine-version 4.x
{
  "CacheEngineVersions": []
}

$ aws elasticache describe-cache-engine-versions --engine redis --engine-version 5.x
{
  "CacheEngineVersions": []
}

$ aws elasticache describe-cache-engine-versions --engine redis --engine-version 6.x
{
  "CacheEngineVersions": [
    {
      "Engine": "redis",
      "EngineVersion": "6.2",
      "CacheParameterGroupFamily": "redis6.x",
      "CacheEngineDescription": "Redis",
      "CacheEngineVersionDescription": "redis version 6.2.6"
    }
  ]
}

$ aws elasticache describe-cache-engine-versions --engine redis --engine-version 7.x
{
  "CacheEngineVersions": []
}

$ aws elasticache describe-cache-engine-versions --engine redis --engine-version 7.0
{
  "CacheEngineVersions": [
    {
      "Engine": "redis",
      "EngineVersion": "7.0",
      "CacheParameterGroupFamily": "redis7",
      "CacheEngineDescription": "Redis",
      "CacheEngineVersionDescription": "redis version 7.0.5"
    }
  ]
}
```

I don't have the provider set up on my local to test, but I suspect that adding `7.x` to the [engine_version_test](https://github.com/hashicorp/terraform-provider-aws/blob/c955f35fefaa142b39266a1a4bb34c3319b4acc1/internal/service/elasticache/engine_version_test.go#L79), despite being valid, won't pass. The [engine_version](https://github.com/hashicorp/terraform-provider-aws/blob/c955f35fefaa142b39266a1a4bb34c3319b4acc1/internal/service/elasticache/engine_version.go#L32-L37) validation regex (and docs) will need to be updated...again.

**Comment by nealzheng** [comment]
same here, get 400 error when using 
engine_version = 7.x on terraform

> Unexpected error occurred while executing terraform plan. (
  Error: error creating ElastiCache Replication Group (prod-xxx-cache): InvalidParameterCombination: Cannot find version 7.x for redis
  	status code: 400, request id: 09778ce4-f7f4-430a-8494-b95d6a6c46a4
Warning: Experimental feature "variable_validation" is active

**Comment by madolson** [comment]
Engineer from the AWS service team here. Starting with Redis 6, we stopped allowing users to specify the "patch" version (in x.y.z, the z is the patch version) when creating clusters. We initially thought it made sense to specify an ".x" instead of a minor version, but ultimately it was confusing to our customers so we changed it to specify the minor version, so 6.0 and 6.2 work. Moving forward, we will support specifying the major + minor. So 7.0 or 7.2. will work for Redis 7. For compatibility reasons we still support 6.x, since some customers are likely still using it in the API.

Hopefully this will be the end of the churn.

**Comment by griffinbaker12** [comment]
Can confirm that 7.x and 7.0 threw errors for me, but 7.2 worked

**Comment by lmbleandro** [comment]
I can also confirm that 7.x, 7.0, and 7.2 threw errors for me.

**Comment by elrob** [comment]
I've had a go at this after hitting the same issue myself today.
https://github.com/hashicorp/terraform-provider-aws/pull/31264

**Comment by josegonzalez** [comment]
`7.x` doesn't work for me, but I was able to use `7.0` and it appears to be provisioning.

**Comment by elrob** [comment]
PR is still awaiting review: https://github.com/hashicorp/terraform-provider-aws/pull/31264
