### ISSUE TITLE
[Enhancement]: Support for .NET 7 for Lambda Functions

### ISSUE THREAD

**Issue by Hecedu** [hashicorp/terraform-provider-aws#28152]
### Description

With the recent announcement of [support for .NET 7 Lambda Functions in AWS ](https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/) many benefits are brought to the table, most notably [AOT compilation for .NET lambda functions which decrease both cold start times and costs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/build-dotnet7.html#build-dotnet7-prerequisites).

The current version of Terraform has runtime support in Lambda up to "dotnet6"

### Affected Resource(s) and/or Data Source(s)

aws_lambda_function

### Potential Terraform Configuration

```terraform
resource "aws_lambda_function" "dotnetSevenFunction" {
  filename      = "dotnetSevenFunction.zip"
  function_name = "dotnetSevenFunction"
  role          = aws_iam_role.dotnetSevenFunction.arn
  runtime       = "dotnet7"
  handler       = "dotnetSevenFunction::dotnetSevenFunction.Function::FunctionHandler"
  architectures = ["x86_64"]
}
```

### References

- https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/build-dotnet7.html#build-dotnet7-prerequisites

### Would you like to implement a fix?

No

**Comment by JamesJJ** [comment]
Hello @Hecedu, As I understand, ahead-of-time compilation allows you to compile your .NET 7 project to a native executable which can then be deployed to Lambda with the existing `provided.al2` runtime -- The existing `aws_lambda_function` Terraform resource should be able to do that. Lambda does not have a separate `dotnet7` runtime.

------
Reference:
https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/

### Lambda runtime

Use the `provided.al2` custom runtime with the `x86_64` architecture to deploy a Lambda function that you build with native AOT compilation. When you use a .NET Lambda runtime, your application is compiled into Intermediate Language (IL) code. At runtime, the just-in-time (JIT) compiler takes the IL code and compiles it into machine code as needed. _With a Lambda function that is compiled ahead of time with native AOT, the runtime environment doesn't include the .NET SDK or .NET runtime. You compile your code into machine code before it runs._

------

Reference:
https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/

### Overview

Customers can use .NET 7 with Lambda in two ways. First, Lambda has released a base container image for .NET 7, enabling customers to build and deploy .NET 7 functions as [container images](https://docs.aws.amazon.com/lambda/latest/dg/csharp-image.html). Second, you can use Lambda’s [custom runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html) support to run functions compiled to native code using .NET 7 native AOT. _Lambda has not released a managed runtime for .NET 7, since it is not a long-term support (LTS) release._

------
