### ISSUE TITLE
[Docs]: Duplicate in attribute reference

### ISSUE THREAD

**Issue by nigel-f-wilson** [hashicorp/terraform-provider-aws#28217]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_account_alias

### Description

In https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_account_alias#attributes-reference there is an `account_alias` and an `id` and both have the same description. It looks like there is a typo in the second, like it was just copied from above and not updated. It should say "id" not "alias".

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @nigel-f-wilson 👋 Thank you for taking the time to raise this! In this case, it appears that the `id` and `account_alias` [are indeed the same value](https://github.com/hashicorp/terraform-provider-aws/blob/014422f71f50ca5fbfa69f4c3412c7322cd3d740/internal/service/iam/account_alias_data_source.go#L42-L45), so I think it's safe to leave the documentation as is. This is a fairly common pattern in other resources/data source, but definitely looks a bit more strange when there's only two argument/attributes 😅. Since this matches the data source schema, I'll close this issue. If you feel I've done that in error, please do let me know.
