### ISSUE TITLE
Feature Request: Automatically subscribing to DynamoDB autoscaling alarms

### ISSUE THREAD

**Issue by armanshan12** [hashicorp/terraform-provider-aws#2829]
Hi there,

I was wondering if we could enhance aws_appautoscaling_policy to support adding actions (e.g. post to SNS topic) for alarms that are automatically created by AWS when creating an autoscaling policy.

If you check out this tutorial by AWS for creating DynamoDB autoscaling through their CLI, https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.CLI.html, you can see that when you create the policy through the CLI, the CLI returns information about 2 Cloudwatch alarms that it automatically created. It would be great if we could add custom actions to those alarms when creating the policy through Terraform.

Here is the CLI command:
```
aws application-autoscaling put-scaling-policy \
    --service-namespace dynamodb \
    --resource-id "table/TestTable" \
    --scalable-dimension "dynamodb:table:WriteCapacityUnits" \
    --policy-name "MyScalingPolicy" \
    --policy-type "TargetTrackingScaling" \
    --target-tracking-scaling-policy-configuration file://scaling-policy.json
```

### Terraform Version
Terraform v0.11.1
+ provider.aws v1.6.0

### Affected Resource(s)
- aws_appautoscaling_policy

**Comment by armanshan12** [comment]
@jen20 @bflad @radeksimko

**Comment by bflad** [comment]
@armanshan12 definitely an interesting idea here! 😄  If I am gathering your thoughts correctly, you're in a bind due to automatically created resources in AWS that you would like to be augmented with your own management. I can certainly see why you're looking for this and in fact, this is starting to become a more common issue with the provider as AWS increases the number of "higher level" services and resources that automatically build underlying infrastructure on your behalf.

Architecturally speaking, we generally try to keep each of the resources within the confines of their own AWS service, so I do not think we would want to start breaking that consistency. This helps simplify the provider code as well as error handling. Here are some general questions I would have in this case:
* Does AWS allow you to manage pieces of the automatically created alarms? Does doing so cause other failure conditions later on?
* Do we fail creating the Application Autoscaling resource if the CloudWatch parts fail?
* What if we want to implement the same for OK actions?
* If we accept this cross-service handling in this resource, where do we draw the line for other similar enhancements?

None of these are certainly a hard no, though. 👍 

Even today, we can actually implement something close to what you are looking to do within the existing provider architecture since we do get the CloudWatch alarm ARNs from the Application Autoscaling resource.

### Easier Route

Create a resource that can attach an alarm action to a given alarm, e.g.

```hcl
# Not implemented at the current time
resource "cloudwatch_metric_alarm_action_attachment" "example" {
  count = "${length(aws_appautoscaling_policy.example.alarms)}"

  alarm_action = "..."
  cloudwatch_metric_alarm_arn = "${aws_appautoscaling_policy.example.alarms[count.index]}"
  # ok_action = "..."
}
```

### Harder Route

Add an optional attribute to the CloudWatch alarm resource to not require the "creation" of the alarm but still manage it. We generally force operators to import existing resources, but in this case, its automated, so that workflow doesn't work. There are a lot of caveats to this that likely make it unfeasible though, since AWS owns the resource lifecycle, actions, etc.

**Comment by armanshan12** [comment]
Thanks @bflad for your detailed response!

I definitely do agree with everything you said. I had been struggling to find a way to do this in a "non-ugly" way.

The reason I did not think about your `Easier Route` was because I thought each Terraform Resource has to mirror an AWS resource. But if what you are suggesting is perfectly valid to add, then I think that is the best solution to this problem.

So:
1. let `aws_appautoscaling_policy` take care of autoscaling setup and output alarm ARNs
2. let `cloudwatch_metric_alarm_action_attachment` capture the outputted alarm ARNs and add actions to them (OK or alarm actions)

In future runs,
1. `aws_appautoscaling_policy` is read, including the alarm ARNs
2. `cloudwatch_metric_alarm_action_attachment` fetches the alarm and checks if the actions are there and whether anything needs to be modified.

**Comment by armanshan12** [comment]
So shall I go ahead with implementing the new `aws_cloudwatch_metric_alarm_action_attachment` resource?

**Comment by armanshan12** [comment]
I have been thinking about this resource for a bit, and I think there are some challenges we did not think about.

Going with the design you have above:
```
# Not implemented at the current time
resource "cloudwatch_metric_alarm_action_attachment" "example" {
  count = "${length(aws_appautoscaling_policy.example.alarms)}"

  alarm_action = "..."
  cloudwatch_metric_alarm_arn = "${aws_appautoscaling_policy.example.alarms[count.index]}"
  # ok_action = "..."
}
```

It would be hard to stick to the CRUD abstraction. For example, read would be hard to implement because you would have to fetch the cloudwatch alarm, and then figure out which alarm/ok actions in the list are the ones this resource is responsible for.

In case of autoscaling, there would be one item in the `alarm_actions` list automatically created when autoscaling was created. When you do the read operation for the `attachment` resource, you need to filter that out.

So maybe the solution is to include 2 other keys in the schema: `alarm_actions_to_ignore` and `ok_actions_to_ignore`? But then how are you going to set those keys in the autoscaling case (i.e. how to get them from `aws_appautoscaling_policy`?

Maybe going with your "Harder route" suggestion makes more sense?

Please let me know what you think.

**Comment by bflad** [comment]
From a Terraform perspective, the easiest implementation is a 1:1 mapping. We can set the `alarm_action` (singular string, not a set) and `ok_action` (singular string, not a set) attributes so they are defined in the schema with `ConflictsWith` for each other so they only focus on one action and whether its in the upstream alarm/ok action list of the alarm. 

As long as the alarm exists, all the resource needs to do is:
* On Create: check CloudWatch alarm for resource's action in appropriate alarm action list, error if present, add if not present
* On Read: check CloudWatch alarm for resource's action in appropriate alarm action list, remove from state if not present (triggers re-creation)
* There is no Update. All changes are `ForceNew`
* On Delete: check CloudWatch alarm for resource's action in appropriate alarm action list, return immediately if missing, remove if present

Now having said that, I went and looked at the CloudWatch API, and that is actually what prevents this implementation from being easy. `PutMetricsAlarmInput` requires you to basically resubmit the entire alarm configuration, not just update certain elements of an alarm (like its alarm action list). We would not want any sort of "sub" resource to have that level of responsibility and management so that immediately removes its viability.

Even with the harder route:
* Operators need to manage _all_ aspects of an automatically generated alarm (e.g. for target tracking updates, always update the CloudWatch alarm thresholds at the same time, and know what those new thresholds should be like if it should be +/- some number/% to match AWS's logic)
* AWS may change their implementation unexpectedly and break everyone's configuration (certainly within their rights, its their alarm)
* AWS may introduce new alarm parameters required for their automatic alarms not yet available in Terraform (e.g. Terraform will remove if it updates the alarm and break AWS's automatic alarm functionality)

For these reasons, I would be extremely hesitant to even implement an "easy" flag attribute to allow management of automatically created alarms. It could be fine or it could be a world of hurt/bugs/catchup. If folks really want to do want this in Terraform, its maybe worth some other opinions and having a few people try it out first (via normal import). Or better yet, ask AWS to improve their API so folks can manage only certain aspects of alarms in a world where some are automatically created on their behalf.

Do you have a support plan with AWS? If you do, I would really suggest opening a case asking their opinion about managing actions of an automatically managed CloudWatch alarm via the API. If nothing else, they can put in a feature request for API improvements so we can manage alarm actions separately. If you don't have a support plan, I may be able to submit a case on your behalf, but I cannot offer any timeline or guarantees.

**Comment by armanshan12** [comment]
I opened a support ticket with AWS. I will let you know what comes out of it.

**Comment by armanshan12** [comment]
@bflad I was told by AWS support that the feature is not on their roadmap, but he filed a feature request and their team will review it.
