### ISSUE TITLE
[Enhancement]: Resource: aws_elasticache_cluster dose not have "description" field

### ISSUE THREAD

**Issue by paikend** [hashicorp/terraform-provider-aws#28323]
### Description

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster
can't not found "description" field on Document and code at Resource: aws_elasticache_cluster

### Affected Resource(s) and/or Data Source(s)

Resource: aws_elasticache_cluster

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @paikend 👋 Thank you for taking the time to raise this! I took a look and the `aws_elasticache_cluster` resource doesn't have a `description` argument in the schema either. The resource schema maps to the [`elasticache.CreateCacheClusterInput` type](https://github.com/hashicorp/terraform-provider-aws/blob/bfcd55c7cde9b2190aa0a18e6110c967e1ad5458/internal/service/elasticache/cluster.go#L352), which [does not have a `description` field](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#CreateCacheClusterInput), which is why the resource lacks this argument.

If the AWS Go SDK changes in the future to include a description field, we'd be happy to take another look into this, but for now I'll close this issue out. If you feel I've done this in error, please do let me know.

**Comment by paikend** [comment]
thank you for your kind reply 😀
