### ISSUE TITLE
[Enhancement]: I want download file from S3 bucket and create SSM_document without using aws cli commands

### ISSUE THREAD

**Issue by ashokbura** [hashicorp/terraform-provider-aws#28387]
### Description

I want download file from S3 bucket and create SSM_document without using aws cli commands

### Affected Resource(s) and/or Data Source(s)

i tested 

 attachments_source {
    key    = "SourceUrl"
    values = ["s3://${aws_s3_bucket.object_bucket.bucket}/test.zip"]
  }

but it is not working without content block 

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @ashokbura 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
