### ISSUE TITLE
[Docs]: aws_subnets 'ids' attribute not documented (or mis-documented?)

### ISSUE THREAD

**Issue by bugfood** [hashicorp/terraform-provider-aws#28645]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#attributes-reference

### Description

In the documentation for aws_subnet, there is no documentation for an `ids` attribute. This attribute is referenced in a few places and seems to exist. It works when I try it. I'm very new to using terraform, but a colleague of mine thinks this is a probably a documentation bug rather than an expected idiom.

Perhaps the documented `id` parameter should instead be `ids`.

### References

A couple usage examples:
https://www.reddit.com/r/Terraform/comments/t16nw5/comment/hye4ldy/
https://github.com/hashicorp/terraform-provider-aws/issues/25160

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @bugfood 👋 Thank you for taking the time to raise this! It looks like the Reddit user that you linked to is using either the [`aws_subnet_ids`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet_ids) (deprecated) or [`aws_subnets`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets) data sources; each of which do have an `ids` attribute.

Is it possible that in your working examples that referenced an `ids` attribute, you were using one of these data sources rather than the `aws_subnet` resource that you linked to the documentation of?

**Comment by bugfood** [comment]
@justinretzolk , you're right, sorry, that was confusion on my side. I can tell you how it happened, though.

I hit the deprecation message for `aws_subnet_ids`:
```
│ The aws_subnet_ids data source has been deprecated and will be removed in a
│ future version. Use the aws_subnets data source instead.
```

...so I searched google:
https://www.google.com/search?q=terraform+aws_subnets

For me, right now, the first result is for the `aws_subnet` resource, and the naming is so similar that I didn't realize I was looking at the wrong thing.

I suggest adding a URL to the deprecation message. I can submit a PR for that.
