### ISSUE TITLE
REST API Gateway method_response response_parameters values

### ISSUE THREAD

**Issue by jeffery** [hashicorp/terraform-provider-aws#28760]
### Description

In the following block of code:

```terraform
resource "aws_api_gateway_method_response" "any_response_200" {
  rest_api_id = var.APIGateway_id
  resource_id = aws_api_gateway_resource.lambda.id
  http_method = aws_api_gateway_method.any.http_method
  status_code = "200"

  response_parameters = {
    "method.response.header.Access-Control-Allow-Origin" = true
  }

  response_models = {
    "application/json" = "Empty"
  }
}
```

What does

```terraform
  response_parameters = {
    "method.response.header.Access-Control-Allow-Origin" = true
  }
```

The value true/false depict? I cannot seeing any flags being toggled in the console when the method_response resource is created.

Anyone have an idea what the flag is used for?

I know for `aws_api_gateway_method` resource the header with true/false toggles if the header is required. But I am not seeing anything for the above resource.

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method_response#response_parameters

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jeffery 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). As such I'm going to close this issue.

That said, I think the information you're looking for may be found in one of the following AWS documents:
- [Set up method response parameters](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-settings-method-response.html#setup-method-response-parameters)
- [`responseParameters` API reference](https://docs.aws.amazon.com/apigateway/latest/api/API_MethodResponse.html#responseParameters) (this one is a bit more detailed, in my opinion)
