### ISSUE TITLE
AWS Aurora Blue/Green Update 

### ISSUE THREAD

**Issue by PackiarajSakkananGW** [hashicorp/terraform-provider-aws#28956]
### Description

`blue_green_update` is valid only for `aws_db_instance` and does not work with `aws_rds_cluster_instance` . As per the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance) `aws_rds_cluster_instance` is the recommended way to manage aurora instance. If that is the case, `blue_green_update` should work with Auroa. (aws_rds_cluster_instance)

### Affected Resource(s) and/or Data Source(s)

aws_rds_cluster, aws_rds_cluster_instance

### Would you like to implement a fix?

None

**Comment by danielkza** [comment]
Additionally, support for manually managing blue-green deployment resources would be nice, for longer-running validation or more complex scenarios.

**Comment by cameronattard** [comment]
It would be great to get this prioritised. Major version upgrades with Terraform are currently incredibly painful without this feature.

**Comment by ribejara-te** [comment]
Yup, big thumbs up to this.

**Comment by autotune** [comment]
I'm volunteering to work on this issue, this is number 7 of my hundred days of Terraform contributions challenge.

**Comment by autotune** [comment]
Can you all start voting on https://github.com/hashicorp/terraform-provider-aws/pull/33812 in order to prioritize PR? It is working now just need to figure out how to add tests for it.

**Comment by autotune** [comment]
I had initially tried to build it in as part of a mapping within the `aws_rds_cluster` resource, but I think I am going to have to re-work this to be its own resource. Think something like:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_role_association

```console
resource "aws_rds_cluster_blue_green" "example" {
  db_cluster_identifier = aws_rds_cluster.example.id
  enabled               = true
}
```

Then we can have a depends_on block to the instances that need to be created first in order for this to work. That's the simplest route to getting this working in a way that makes sense.

**Comment by autotune** [comment]
@gdavison 

This is about 75 percent done, but given RDS Aurora takes 40 minutes or so for a full deployment on each run, it has taken some time to create the resource and test. If you could evaluate what I've got so far that would be great, if you plan to take it over and do your own version/rewrite it would be greatly appreciated if you could let me know.

**Comment by Priyank-Vaghela** [comment]
I am in the same boat. Big thumbs up to this functionality. This feature would be a significant improvement and prioritizing it would be beneficial, as DB/maintenance upgrades are currently quite challenging without `aws_rds_cluster_instance` - `blue_green_update` with Terraform.

**Comment by gdavison** [comment]
Thank you all for the discussion here.

Unfortunately, Blue/Green Deployments would not work the same with with Aurora clusters as they do with `aws_db_instance`. With `aws_db_instance`, they work because it is a single, self-contained resource, so the Blue/Green Deployment can be created, apply its updates, be switched over, and deleted all in one step. Aurora clusters, however, are made up of one `aws_rds_cluster` and at least one `aws_rds_cluster_instance`. A Blue/Green Deployment created for one resource would have to complete before the other related resources are updated.

A stand-alone resource for RDS Blue/Green Deployments does not fit with the Terraform model of declarative infrastructure: Using the resource would require multiple iterations of editing the Terraform configuration, applying the configuration, or importing resources. A separate tool that can manage the orchestration steps would be a better fit.

For more details, see https://github.com/hashicorp/terraform-provider-aws/pull/34551
