### ISSUE TITLE
[Bug]: changing tags on aws_vpc resource results in subnet recreation when using data.aws_vpc.vpc_selected.cidr_block

### ISSUE THREAD

**Issue by jmolnar-zscaler** [hashicorp/terraform-provider-aws#29023]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.50.0

### Affected Resource(s)

aws_vpc
aws_subnet

### Expected Behavior

resource tags should update in-place

### Actual Behavior

aws_subnet resource forces a recreation

### Terraform Configuration Files

https://github.com/zscaler/terraform-aws-cloud-connector-modules/tree/main/examples/base

code example:

global tags defined with locals mapping and passed to child modules

```terraform
################################################################################
# Map default tags with values to be assigned to all tagged resources
################################################################################
locals {
  global_tags = {
    Owner                                                                                 = "jmolnar6@zscaler.com"#var.owner_tag
    ManagedBy                                                                             = "terraform"
    Vendor                                                                                = "Zscaler"
    "zs-edge-connector-cluster/${var.name_prefix}-cluster-${random_string.suffix.result}" = "shared"
  }
}

module "network" {
  source            = "../../modules/terraform-zscc-network-aws"
  global_tags       = local.global_tags
```

VPC resource is created along with a data source for the resource

```terraform
################################################################################
# VPC
################################################################################
# Create a new VPC
resource "aws_vpc" "vpc" {
  count                = var.byo_vpc == false ? 1 : 0
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true

  tags = merge(var.global_tags,
    { Name = "${var.name_prefix}-vpc-${var.resource_tag}" }
  )
}

# Or reference an existing VPC
data "aws_vpc" "vpc_selected" {
  id = var.byo_vpc == false ? aws_vpc.vpc[0].id : var.byo_vpc_id
}
```

Subnets are then created that reference the aws_vpc data source for cidr_block

```terraform
resource "aws_subnet" "workload_subnet" {
  count             = var.workloads_enabled == true ? length(aws_subnet.cc_subnet[*].id) : 0
  availability_zone = data.aws_availability_zones.available.names[count.index]
  cidr_block        = var.workloads_subnets != null ? element(var.workloads_subnets, count.index) : cidrsubnet(data.aws_vpc.vpc_selected.cidr_block, 8, count.index + 1)
  vpc_id            = data.aws_vpc.vpc_selected.id

  tags = merge(var.global_tags,
    { Name = "${var.name_prefix}-workload-subnet-${count.index + 1}-${var.resource_tag}" }
  )
}
```

### Steps to Reproduce

make a change to any name value pair of local.global_tags and terraform apply.

The subnet resource(s) are force replaced. This only happens if aws_subnet cidr_block argument references the aws_vpc cidr_block from data source `cidrsubnet(data.aws_vpc.vpc_selected.cidr_block)`. If changed to `cidrsubnet(aws_vpc.vpc[0].cidr_block)` the subnet recreation correctly does not occur

```shell
 # module.network.aws_subnet.workload_subnet[0] must be replaced
-/+ resource "aws_subnet" "workload_subnet" {
      ~ arn                                            = "arn:aws:ec2:us-west-2:223544365242:subnet/subnet-08d30345f9a46d70a" -> (known after apply)
      ~ availability_zone_id                           = "usw2-az2" -> (known after apply)
      ~ cidr_block                                     = "10.1.1.0/24" -> (known after apply) **# forces replacement**
      ~ id                                             = "subnet-08d30345f9a46d70a" -> (known after apply)
      + ipv6_cidr_block_association_id                 = (known after apply)
      - map_customer_owned_ip_on_launch                = false -> null
      ~ owner_id                                       = "223544365242" -> (known after apply)
      ~ private_dns_hostname_type_on_launch            = "ip-name" -> (known after apply)
      ~ tags                                           = {
          ~ "Owner"                                             = "jmolnar6@zscaler.com" -> "jmolnar7@zscaler.com"
            # (4 unchanged elements hidden)
        }
      ~ tags_all                                       = {
          ~ "Owner"                                             = "jmolnar6@zscaler.com" -> "jmolnar7@zscaler.com"
            # (4 unchanged elements hidden)
        }
        # (8 unchanged attributes hidden)
    }

Plan: 10 to add, 18 to change, 10 to destroy.
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jmolnar-zscaler 👋 Thanks for taking the time to raise this! Can you give me an idea of what `data.aws_vpc.vpc_selected` looks like in the plan when the resources are being recreated?

I suspect that the read for `data.aws_vpc.vpc_selected` is being deferred until apply time, which is causing the `(known after apply)` for the `cirdr_block` argument of the `aws_subnet. workload_subnet[*]` resources, and thus the recreation. This behavior is described a bit in the [data resource behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior) and [data resource dependencies](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-dependencies) sections of the documentation. It's a little unclear to me what would cause the deferral based on your configuration, but I'm hoping the logs will help me understand a bit further.

**Comment by jmolnar-zscaler** [comment]
Hey Justin, 

Please see the attached full terraform plan. I also enabled tf_log debug with the run as well. For reference, I pulled a snippet of the 2 aws_vpc resource and data resources from the run.


 # module.network.aws_vpc.vpc[0] will be updated in-place
  ~ resource "aws_vpc" "vpc" {
        id                                   = "vpc-0de6415e1a5f3affa"
      ~ tags                                 = {
          ~ "Owner"                                             = "jmolnar7@zscaler.com" -> "jmolnar8@zscaler.com"
            # (4 unchanged elements hidden)
        }
      ~ tags_all                             = {
          ~ "Owner"                                             = "jmolnar7@zscaler.com" -> "jmolnar8@zscaler.com"
            # (4 unchanged elements hidden)
        }
        # (16 unchanged attributes hidden)
    }


# module.network.data.aws_vpc.vpc_selected will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_vpc" "vpc_selected" {
      + arn                                  = (known after apply)
      + cidr_block                           = (known after apply)
      + cidr_block_associations              = (known after apply)
      + default                              = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_dns_hostnames                 = (known after apply)
      + enable_dns_support                   = (known after apply)
      + enable_network_address_usage_metrics = (known after apply)
      + id                                   = "vpc-0de6415e1a5f3affa"
      + instance_tenancy                     = (known after apply)
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + state                                = (known after apply)
      + tags                                 = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }
[terraform_debug.log](https://github.com/hashicorp/terraform-provider-aws/files/10492113/terraform_debug.log)
[terraform_apply.log](https://github.com/hashicorp/terraform-provider-aws/files/10492114/terraform_apply.log)

**Comment by justinretzolk** [comment]
Hey @jmolnar-zscaler 👋 Thanks for that logging, that's extremely helpful! With that, I can see more clearly why this is happening.

With data sources, whether the data source can be read during the plan phase, or must be deferred until the apply phase [depends on a few factors](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior). One of these factors is:

> The data resource depends directly on a managed resource that itself has planned changes in the current plan.

In your case, the `aws_vpc.vpc_selected` data source is dependent upon the `aws_vpc.vpc` resource by way of:

```terraform
id = var.byo_vpc == false ? aws_vpc.vpc[0].id : var.byo_vpc_id
```

Because of this, when there are changes to the `aws_vpc.vpc` resource (in this case, adjusting the tags), Terraform must defer reading the `aws_vpc.vpc_selected` data source until apply time, which means the value for the `cidr_block` argument of `aws_subnet.workload_subnet` cannot be determined until apply time. Because changes to the `cidr_block` argument of the `aws_subnet` resource forces a new resource, these resources must be recreated.

There is, fortunately, a fairly straightforward way around this. My suggestion would be to change up the configuration slightly to eliminate use of the data source when not needed. This would require a few steps, which I'll outline below. For what it's worth, while I did look at the repository that you linked, I do consider these suggestions as my personal opinion, and would very much recommend that you consider organizational requirements before moving forward with any of them. 

### Step 1: Conditionally using the `aws_vpc.vpc_selected` data source

You are already conditionally creating the `aws_vpc.vpc` resource based on whether a VPC is being supplied via the `var.byo_vpc` argument, however, you're not currently doing the same for the `data.aws_vpc.vpc_selected` data source. I would recommend switching this behavior up by adding the following to that data source:

```terraform
count = var.byo_vpc ? 1 : 0
```

(**Note:** Since `var.byo_vpc` is itself a boolean, you can use it directly rather than needing to do a comparison like `var.byo_vpc == false`)

This will mean that the data source is only used if `var.byo_vpc` is true. Otherwise, the data source is not used at all. Because it is not used at all in this case, the `id` argument can refer directly to `var.byo_vpc_id`, such as:

```terraform
id = var.byo_vpc_id
```

### Step 2: Use a `local` to select the CIDR block

Since there are two sources that the CIDR block may come from (`data.aws_vpc.vpc_selected` or `aws_vpc.vpc`), it would make things a bit more readable to select between them using a local. This will make it easier to reference in the `cidrsubnet` function within the `aws_subnet.workload_subnet` resource definition. To do so, you can again leverage the `var.byo_vpc` variable:

```terraform
local {
  selected_cidr_block = var.byo_vpc ? data.aws_vpc.vpc_selected[0].cidr_block : aws_vpc.vpc[0].cidr_block
}
```

This means that if `var.byo_vpc` is `true`, it will use the data source's `cidr_block`, otherwise, it will use the `aws_vpc.vpc` resource's `cidr_block`. This eliminates the reliance on the data source when the VPC is being being created by Terraform.

### Step 3: Update the `aws_subnet.workload_subnet.cidr_block` reference to use the local value

Now that the `data.aws_vpc.vpc_selected` data source and `aws_vpc.vpc` resource are not interconnected, the final piece is to update the reference in the `aws_subnet.workload_subnet.cidr_block` to eliminate the dependence on the `aws_vpc.vpc_selected` data source (when not needed). This can be done by updating the `cidr_block` argument as follows:

```terraform
cidr_block  = var.workloads_subnets != null ? element(var.workloads_subnets, count.index) : cidrsubnet(local.selected_cidr_block, 8, count.index + 1)
```

### Final round up

With these changes in configuration, the following possible pathways are taken (I'm intentionally ignoring the `var.workloads_subnets` ternary bit in the `cidr_block` argument of `aws_subnet` because it's not really relevant in this moment):

`var.byo_vpc` is `false`:

- `aws_vpc.vpc` resource is created
- `aws_vpc.vpc_selected` data source is **not** created/used
- `local.selected_cidr_block` is equal to `aws_vpc.vpc[0].cidr_block`
- `aws_subnet.workload_subnet.cidr_block` is set to use the `cidrsubnet` function to calculate the subnet CIDR based on `aws_vpc.vpc[0].cidr_block`
- Because tag changes to `aws_vpc` resources do not force recreation or changes to it's `cidr_block` attribute, you will not run into the issue of `aws_subnet.workload_subnet` being recreated on tag changes.
  
`var.byo_vpc` is `true`:

- `aws_vpc.vpc` resource is **not** created
- `aws_vpc.vpc_selected` data source is created/used, looks up the VPC based on `var.byo_vpc_id`
- `local.selected_cidr_block` is equal to `data.aws_vpc.vpc_selected[0].cidr_block`
- `aws_subnet.workload_subnet.cidr_block` is set to use the `cidrsubnet` function to calculate the subnet CIDR based on `data.aws_vpc.vpc_selected[0].cidr_block`
- Because the data source is not dependent on the `aws_vpc.vpc` (or any other conditions mentioned in the Data Resource Behavior document linked above), it will be read at plan time rather than apply time, and will only force recreation of the `aws_subnet.workload_subnet` resources if the `cidr_block` attribute changes for some reason (the behavior you'd generally expect)

I hope this information helps. If you have any follow up questions, please do let me know.

**Comment by jmolnar-zscaler** [comment]
Hey Justin,

Thanks for the thorough response! I am reviewing the proposed solution and documentation. My question though is the crux of the issue ultimately related to the cidrsubnet function having to do a calculation with the data source read?

My reason is if the problem was just for data source dependencies (that I am nesting quite a bit as you can tell with byo variables), I would expect to see this with other resource dependency changes. For example, aws_route_table.public_rt has a reference to data.aws_internet_gateway.igw_selected.internet_gateway_id

# Create a public Route Table towards IGW. This will not be created if var.byo_ngw is set to True
resource "aws_route_table" "public_rt" {
  count  = var.byo_ngw == false ? 1 : 0
  vpc_id = data.aws_vpc.vpc_selected.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = data.aws_internet_gateway.igw_selected.internet_gateway_id
  }

  tags = merge(var.global_tags,
    { Name = "${var.name_prefix}-public-rt-${var.resource_tag}" }
  )
}

I have the same logic for aws_internet_gateway resource/data source

# Create an Internet Gateway
resource "aws_internet_gateway" "igw" {
  count  = var.byo_igw == false ? 1 : 0
  vpc_id = data.aws_vpc.vpc_selected.id

  tags = merge(var.global_tags,
    { Name = "${var.name_prefix}-igw-2${var.resource_tag}" }
  )
}

# Or reference an existing Internet Gateway
data "aws_internet_gateway" "igw_selected" {
  internet_gateway_id = var.byo_igw == false ? aws_internet_gateway.igw[0].id : var.byo_igw_id
}


If I make the same tag change to aws_internet_gateway_igw it has no affect on the aws_route_table resource that is dependent on it??



tls_private_key.key: Refreshing state... [id=0147c38e124f57d49fb8413622870c6ff1914d6e]
random_string.suffix: Refreshing state... [id=eqj1xyeo]
local_file.private_key: Refreshing state... [id=029221887f10e29a38cc89673c85f499f6ade151]
module.bastion.data.aws_ssm_parameter.amazon_linux_latest: Reading...
module.network.data.aws_availability_zones.available: Reading...
aws_key_pair.deployer: Refreshing state... [id=zsdemo-key-eqj1xyeo]
module.bastion.data.aws_iam_policy_document.bastion_instance_assume_role_policy: Reading...
module.workload.data.aws_ssm_parameter.amazon_linux_latest: Reading...
module.network.aws_vpc.vpc[0]: Refreshing state... [id=vpc-0de6415e1a5f3affa]
module.workload.aws_iam_role.node_iam_role: Refreshing state... [id=zsdemo-workload-node-iam-role-eqj1xyeo]
module.bastion.data.aws_iam_policy_document.bastion_instance_assume_role_policy: Read complete after 0s [id=1903849331]
module.bastion.aws_iam_role.bastion_iam_role: Refreshing state... [id=zsdemo-bastion-iam-role-eqj1xyeo]
module.bastion.data.aws_ssm_parameter.amazon_linux_latest: Read complete after 0s [id=/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2]
module.workload.data.aws_ssm_parameter.amazon_linux_latest: Read complete after 0s [id=/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2]
module.network.data.aws_availability_zones.available: Read complete after 0s [id=us-west-2]
module.bastion.aws_iam_role_policy_attachment.ssm_managed_instance_core: Refreshing state... [id=zsdemo-bastion-iam-role-eqj1xyeo-20230124162102177700000002]
module.workload.aws_iam_instance_profile.server_host_profile: Refreshing state... [id=zsdemo-workload-server_host_profile-eqj1xyeo]
module.bastion.aws_iam_instance_profile.bastion_host_profile: Refreshing state... [id=zsdemo-bastion-host-profile-eqj1xyeo]
module.workload.aws_iam_role_policy_attachment.ssm_managed_instance_core: Refreshing state... [id=zsdemo-workload-node-iam-role-eqj1xyeo-20230124162102174100000001]
module.network.data.aws_vpc.vpc_selected: Reading...
module.network.data.aws_vpc.vpc_selected: Read complete after 1s [id=vpc-0de6415e1a5f3affa]
module.network.aws_subnet.cc_subnet[0]: Refreshing state... [id=subnet-0d15cf232a7f26835]
module.network.aws_internet_gateway.igw[0]: Refreshing state... [id=igw-02ffae0dfbdffd27c]
module.network.aws_subnet.cc_subnet[1]: Refreshing state... [id=subnet-07eb36c328a541179]
module.workload.data.aws_vpc.selected: Reading...
module.bastion.data.aws_vpc.selected: Reading...
module.network.aws_route_table.public_rt[0]: Refreshing state... [id=rtb-062975b9fcadf51f4]
module.network.data.aws_subnet.cc_subnet_selected[0]: Reading...
module.network.data.aws_subnet.cc_subnet_selected[1]: Reading...
module.network.aws_subnet.workload_subnet[1]: Refreshing state... [id=subnet-06d5e75fb7a7a8e7c]
module.network.aws_subnet.workload_subnet[0]: Refreshing state... [id=subnet-04e2c3bd161fbdf22]
module.network.data.aws_subnet.cc_subnet_selected[0]: Read complete after 0s [id=subnet-0d15cf232a7f26835]
module.network.data.aws_subnet.cc_subnet_selected[1]: Read complete after 0s [id=subnet-07eb36c328a541179]
module.network.aws_subnet.public_subnet[1]: Refreshing state... [id=subnet-06308508bc2a838ad]
module.network.aws_subnet.public_subnet[0]: Refreshing state... [id=subnet-0a91bd98c879d1096]
module.network.aws_route_table_association.public_rt_association[0]: Refreshing state... [id=rtbassoc-0154f0870e2e8e968]
module.network.aws_route_table_association.public_rt_association[1]: Refreshing state... [id=rtbassoc-0bea8a9d9bd991084]
module.network.aws_eip.eip[0]: Refreshing state... [id=eipalloc-07f12d82057638146]
module.network.aws_eip.eip[1]: Refreshing state... [id=eipalloc-073247bf93ede6f03]
module.workload.data.aws_vpc.selected: Read complete after 0s [id=vpc-0de6415e1a5f3affa]
module.workload.aws_security_group.node_sg: Refreshing state... [id=sg-0f2b65e569fd23e50]
module.bastion.data.aws_vpc.selected: Read complete after 0s [id=vpc-0de6415e1a5f3affa]
module.bastion.aws_security_group.bastion: Refreshing state... [id=sg-097e7b46116f053d4]
module.network.aws_nat_gateway.ngw[1]: Refreshing state... [id=nat-0d5cff814d50f1cbf]
module.network.aws_nat_gateway.ngw[0]: Refreshing state... [id=nat-0532b50d00879dec1]
module.workload.aws_security_group_rule.server_node_ingress_ssh: Refreshing state... [id=sgrule-538914733]
module.workload.aws_security_group_rule.server_node_ingress_self: Refreshing state... [id=sgrule-1602949026]
module.workload.aws_instance.server_host[0]: Refreshing state... [id=i-0123ceac0dba1feda]
module.bastion.aws_security_group_rule.intranet: Refreshing state... [id=sgrule-187949088]
module.bastion.aws_instance.bastion: Refreshing state... [id=i-00fc25d1afc8eb1a5]
module.bastion.aws_security_group_rule.internet: Refreshing state... [id=sgrule-163205829]
module.bastion.aws_security_group_rule.ssh: Refreshing state... [id=sgrule-2097478177]
module.network.data.aws_nat_gateway.ngw_selected[1]: Reading...
module.network.data.aws_nat_gateway.ngw_selected[0]: Reading...
module.network.data.aws_nat_gateway.ngw_selected[1]: Read complete after 0s [id=nat-0d5cff814d50f1cbf]
module.network.data.aws_nat_gateway.ngw_selected[0]: Read complete after 0s [id=nat-0532b50d00879dec1]
module.network.aws_route_table.workload_rt[0]: Refreshing state... [id=rtb-0d1c508556a947e0f]
module.network.aws_route_table.workload_rt[1]: Refreshing state... [id=rtb-0fd5183564dc6c247]
module.network.aws_route_table.cc_rt[1]: Refreshing state... [id=rtb-002efdf828d4de751]
module.network.aws_route_table.cc_rt[0]: Refreshing state... [id=rtb-08f64939b834b538c]
module.network.aws_route_table_association.workload_rt_association[0]: Refreshing state... [id=rtbassoc-0786441f6ea526a58]
module.network.aws_route_table_association.workload_rt_association[1]: Refreshing state... [id=rtbassoc-011f4b77a8868a118]
module.network.aws_route_table_association.cc_rt_asssociation[1]: Refreshing state... [id=rtbassoc-0e391740b09a7fb47]
module.network.aws_route_table_association.cc_rt_asssociation[0]: Refreshing state... [id=rtbassoc-012e0ee61327d1c1e]
local_file.testbed: Refreshing state... [id=2f11cf814601073371dbb98fd2777e017aaa3c07]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

  # module.network.data.aws_internet_gateway.igw_selected will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_internet_gateway" "igw_selected" {
      + arn                 = (known after apply)
      + attachments         = (known after apply)
      + id                  = (known after apply)
      + internet_gateway_id = "igw-02ffae0dfbdffd27c"
      + owner_id            = (known after apply)
      + tags                = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.network.aws_internet_gateway.igw[0] will be updated in-place
  ~ resource "aws_internet_gateway" "igw" {
        id       = "igw-02ffae0dfbdffd27c"
      ~ tags     = {
          ~ "Name"                                              = "zsdemo-igw-eqj1xyeo" -> "zsdemo-igw-2eqj1xyeo"
            # (4 unchanged elements hidden)
        }
      ~ tags_all = {
          ~ "Name"                                              = "zsdemo-igw-eqj1xyeo" -> "zsdemo-igw-2eqj1xyeo"
            # (4 unchanged elements hidden)
        }
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

**Comment by jmolnar-zscaler** [comment]
And as a follow-up regarding the suggested solution, is there a best practices or concern with utilizing something like a try function rather than locals conditional? I tested the following which seems to also do the job, but wanted input if there are any additional caveats with using try instead?


resource "aws_vpc" "vpc" {
  count                = var.byo_vpc == false ? 1 : 0
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true

  tags = merge(var.global_tags,
    { Name = "${var.name_prefix}-vpc-${var.resource_tag}" }
  )
}

# Or reference an existing VPC
data "aws_vpc" "vpc_selected" {
  count = var.byo_vpc ? 1 : 0
  id    = var.byo_vpc_id
}

resource "aws_subnet" "public_subnet" {
  count             = var.byo_ngw == false ? length(data.aws_subnet.cc_subnet_selected[*].id) : 0
  availability_zone = data.aws_availability_zones.available.names[count.index]
  cidr_block        = var.public_subnets != null ? element(var.public_subnets, count.index) : cidrsubnet(try(data.aws_vpc.vpc_selected[0].cidr_block, aws_vpc.vpc[0].cidr_block), 8, count.index + 101)
  vpc_id            = try(data.aws_vpc.vpc_selected[0].id, aws_vpc.vpc[0].id)

  tags = merge(var.global_tags,
    { Name = "${var.name_prefix}-public-subnet-${count.index + 1}-${var.resource_tag}" }
  )
}

**Comment by justinretzolk** [comment]
Hey @jmolnar-zscaler 👋 Looking at the `data.aws_internet_gateway` and associated `aws_route_table` resource and logs that you mentioned, the `aws_internet_gateway` data source is also being read at apply time, similar to what is happening with the `aws_vpc` data source, however, the attribute of the `aws_internet_gateway` that you're referencing in the `aws_route_table` resource is the one thing that _is_ known at plan time (the `internet_gateway_id` argument, which is what you're using to perform the lookup). This can be seen in your example log output here:

```shell
  # module.network.data.aws_internet_gateway.igw_selected will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_internet_gateway" "igw_selected" {
      + arn                 = (known after apply)
      + attachments         = (known after apply)
      + id                  = (known after apply)
      + internet_gateway_id = "igw-02ffae0dfbdffd27c"
      + owner_id            = (known after apply)
      + tags                = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }
```

Notice that in the logs, it mentions that the data source will be read during apply time. If you were interpolating any other attributes of this data source, you'd have the same experience as you're having with the `aws_vpc` data source and `aws_route_table` interaction (though in that case, it would show as "Update in place", since changes to the `route.gateway_id` argument [do not force replacement][1]), since those values wouldn't be known until apply time.

As far as using `try()`, that's absolutely valid, and something I see a lot in some of the excellent `terraform-aws-modules` modules; for example, [here][2] (this was just a random example of using `try` that I found, not one that is in any way related to this issue). My use of `locals` is more related to my forgetfulness that the `try()` function exists now 🙂.

[1]: https://github.com/hashicorp/terraform-provider-aws/blob/26dfd62cac8efb815aa37b16d1ddeca0cc0f6bbf/internal/service/ec2/vpc_route_table.go#L120-L123
[2]: https://github.com/terraform-aws-modules/terraform-aws-rds/blob/7a15fb3f7cf5f3ea0c66f6a8c06843dffe422d08/modules/db_instance/outputs.tf#L41-L44

**Comment by jmolnar-zscaler** [comment]
thanks again for the response and explanation!
