### ISSUE TITLE
InvalidParameterCombinationException: The specified network type 'IPV4' is not supported by replication subnet group

### ISSUE THREAD

**Issue by eugenyuk** [hashicorp/terraform-provider-aws#29198]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.52.0

### Affected Resource(s)

* aws_dms_replication_instance

### Expected Behavior

DMS replication instance should be created.

### Actual Behavior

DMS replication instance creation is failed.

### Relevant Error/Panic Output Snippet

```shell
module.dev_dms.aws_dms_replication_instance.dms_replication_instance: Creating...
╷
│ Error: creating DMS Replication Instance: InvalidParameterCombinationException: The specified network type 'IPV4' is not supported by replication subnet group 'data-vpc-replication-subnet-group'.
│       status code: 400, request id: 3c5a0ca8-ad23-4666-b245-c08139012605
│ 
│   with module.dev_dms.aws_dms_replication_instance.dms_replication_instance,
│   on ../../../../modules/dms/main.tf line 16, in resource "aws_dms_replication_instance" "dms_replication_instance":
│   16: resource "aws_dms_replication_instance" "dms_replication_instance" {
```

### Terraform Configuration Files

```terraform
resource "aws_dms_replication_subnet_group" "dms_replication_subnet_group" {
  replication_subnet_group_id           = var.repl_subnet_group_name
  replication_subnet_group_description  = "DMS replication subnet group with Data VPC subnets"
  subnet_ids                            = var.repl_subnet_group_subnets

  tags = {
    Environment = var.environment
  }

  depends_on = [aws_iam_role_policy_attachment.dms-vpc-role-policy-attachment]
}

resource "aws_dms_replication_instance" "dms_replication_instance" {
  replication_instance_id      = var.repl_inst_name
  replication_instance_class   = var.repl_inst_class
  allocated_storage            = var.repl_inst_alloc_storage
  apply_immediately            = false
  availability_zone            = "eu-west-1"
  engine_version               = var.repl_inst_engine_version
  kms_key_arn                  = var.dms_kms
  multi_az                     = false
  replication_subnet_group_id  = aws_dms_replication_subnet_group.dms_replication_subnet_group.id

  tags = {
    Name = "Dev-Test RDS replicator 2"
    Environment = var.environment
  }

  vpc_security_group_ids = var.repl_inst_vpc_sg

  depends_on = [
    aws_iam_role_policy_attachment.dms-cloudwatch-logs-role-policy-attachment,
    aws_iam_role_policy_attachment.dms-vpc-role-policy-attachment
  ]
}
```

### Steps to Reproduce

terraform apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Based on [this AWS document](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReplicationInstance.IPAddressing.html), it looks like the `aws_dms_replication_instance` resource needs to have a `network_type` argument added. I'll mark this as an enhancement so that we can take a look at this as soon as it can be prioritized.

Note for future visitors: [AWS Go SDK reference](https://docs.aws.amazon.com/sdk-for-go/api/service/databasemigrationservice/#CreateReplicationInstanceInput)

**Comment by SongGithub** [comment]
I have got same issue as well. The error is blocking my project. Please fix asap.

**Comment by SongGithub** [comment]
> I'll mark this as an enhancement

Can you please label it as Bug instead? I feel it needs an urgent fix and be prioritised as such. 

This is a **bug** that prevents it from working. Enhancement means it makes an already working function better.

**Comment by SongGithub** [comment]
hi @eugenyuk, I met same issue then managed to solve the issue with help from AWS help desk guys. 
Root cause is this line:
`availability_zone            = "eu-west-1"`

Please note `eu-west-1` is referring to the whole Region instead of a particular AZ. Actually TF official document correctly states that with `availability_zone            = "us-west-2c"`

So I think your error should be resolved if you specify a particular AZ in the Region. i.e. ``availability_zone            = "eu-west-1a"`

**Comment by SongGithub** [comment]
@justinretzolk Would you like to resolved this Github issue because it doesn't seem to have anything to do with Terraform but a syntax error?

**Comment by tobinmori** [comment]
Thanks for posting the fix @SongGithub. That worked for me.

**Comment by mat-machado** [comment]
I am using Pulumi and works as well!! Thank you @SongGithub
