### ISSUE TITLE
[Bug]: aws_transfer_server: 'As2Transport must be specified to enable AS2 protocol'

### ISSUE THREAD

**Issue by jgohlke1** [hashicorp/terraform-provider-aws#29332]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.53.0

### Affected Resource(s)

* aws_transfer_server

### Expected Behavior

When deploying a transfer server and specifying `AS2` as a protocol, the provider should provide AWS with an  `As2Transports` value of `HTTP`. 

https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateServer.html

### Actual Behavior

The apply is failing with the following error:

```
│ Error: creating Transfer Server: InvalidRequestException: As2Transport must be specified to enable AS2 protocol
│
│   with aws_transfer_server.server,
│   on all.tf line 5, in resource "aws_transfer_server" "server":
│    5: resource "aws_transfer_server" "server" {
```

### Terraform Configuration Files

```
provider "aws" {
  region = "us-east-1"
}

resource "aws_transfer_server" "server" {
  protocols = ["AS2"]
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
There seems to be a mismatch between Terraform and CloudFormation

https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateServer.html#TransferFamily-CreateServer-request-ProtocolDetails

The ProtocolDetails configuration is missing from Terraform. I suspect AWS want Terraform to set the equivalent of:-

ProtocolDetails:
        As2Transports: 
           - HTTP

in order to be able to set AS2 as one of the protocols enabled. 

In any case whether this is related or not Terraform is missing the ability to configure ProtocolDetails
