### ISSUE TITLE
[Enhancement]: workspace saml integration

### ISSUE THREAD

**Issue by smitche1** [hashicorp/terraform-provider-aws#29359]
### Description

AWS Workspaces now supports integrating SAML 2.0 with your WorkSpaces for desktop session authentication allows your users to use their existing SAML 2.0 identity provider (IdP) credentials and authentication methods through their default web browser. By using your IdP to authenticate users for WorkSpaces, you can protect WorkSpaces by employing IdP features like multi-factor authentication and contextual access policies.

### Potential Terraform Configuration

```terraform
resource "WorkspacesSamlProperties" { 
   "SamlProperties": { 
      RelayStateParameterName = "string",
      Status: "string",
      UserAccessUrl: "string"
   }
```

### References

https://docs.aws.amazon.com/workspaces/latest/adminguide/setting-up-saml.html#enable-integration-saml
https://docs.aws.amazon.com/sdk-for-go/api/service/workspaces/#WorkSpaces.ModifySamlProperties

### Would you like to implement a fix?

No

**Comment by matthewbarreiro** [comment]
> ### Potential Terraform Configuration
> 
> ```terraform
> resource "WorkspacesSamlProperties" { 
>    "SamlProperties": { 
>       RelayStateParameterName = "string",
>       Status: "string",
>       UserAccessUrl: "string"
>    }
> ```


All other configuration settings for the WorkSpaces Directory are currently part of the `aws_workspaces_directory` resource. This includes settings that have their own API calls, such as [ModifySelfservicePermissions](https://docs.aws.amazon.com/workspaces/latest/api/API_ModifySelfservicePermissions.html) and [ModifyWorkspaceAccessProperties](https://docs.aws.amazon.com/workspaces/latest/api/API_ModifyWorkspaceAccessProperties.html).

For consistency, it would likely make more sense to expand that resource instead of adding a new one. 

e.g.
 
```terraform
resource "aws_workspaces_directory" "example" {
  directory_id = aws_directory_service_directory.example.id
  # ...

  workspace_access_properties {
    # ...
  }

  workspace_saml_properties {
    relay_state_parameter_name = "string"
    status                     = "string"
    user_access_url            = "string"
  }

}
```
