### ISSUE TITLE
[Bug]: Doesn't detect changes when dynamically specifying inline rules for aws_security_group

### ISSUE THREAD

**Issue by kaito3desuyo** [hashicorp/terraform-provider-aws#29501]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.49.0

### Affected Resource(s)

* aws_security_group

### Expected Behavior

If you specify an empty array in for_each in the dynamic clause, the rule should be removed

### Actual Behavior

No changes detected

### Terraform Configuration Files

```terraform
resource "aws_security_group" "for_ecs_instance" {
  name        = "${local.prefix}-instance-sg"
  description = "Security Group for ${title(var.target)} ${title(replace(var.role, "-", " "))} Instance"
  vpc_id      = var.vpc_id

  dynamic "ingress" {
    for_each = toset(var.ingress_sg_ids)
    content {
      from_port       = var.container_port
      to_port         = var.container_port
      protocol        = "tcp"
      security_groups = [ingress.value]
      description     = "Allow TCP ${var.container_port} from Specified Security Group IDs"
    }
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow ALL to ANY"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = merge(
    local.module_tags,
    {
      "Name" = "${local.prefix}-instance-sg"
    }
  )
}
```

```terraform
variable "ingress_sg_ids" {
  type        = list(string)
  description = "Ingress Security Group IDs"
}
```

```terraform
ingress_sg_ids                  = [] // [module.internet_loadbalancer.alb_sg_id]
```

### Steps to Reproduce

Toggles the array of `ingress_sg_ids`. You can see that nothing happens when you set it to an empty array.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @kaito3desuyo 👋 Thank you for taking the time to raise this! This is happening due to a scenario I recently described in [this comment](https://github.com/hashicorp/terraform-provider-aws/issues/31004#issuecomment-1526237294). When your `ingress_sg_ids` list is empty, the `dynamic` block will produce no `ingress` blocks, leading to the resource ignoring any existing rules, rather than removing them. In order to remove any existing rules, you'd instead need to explicitly pass `ingress = []`, which will delete all rules, as described in the aforementioned comment.

**Comment by severity1** [comment]
My work around here is to use attribute-as-block mode, although it would be nice to see this working nicely when using dynamic blocks.

I found a clean way of doing this if you are using map of objects while using optional() to simplify setting of default values for  optional resources.

NOTE: the example below uses network_acl but it should be applicable substitute to any dynamic block implementation.

here is my example main.tf
```
# inside main.tf
variable "configuration" {
  type = map(object({
    cidr_block           = string
    availability_zone    = optional(string)
    availability_zone_id = optional(string)
    ingress_rules        = optional(map(object({
      from_port       = number
      to_port         = number
      action          = string
      protocol        = string
      cidr_block      = optional(string, null)
      ipv6_cidr_block = optional(string, null)
      icmp_type       = optional(number, null)
      icmp_code       = optional(number, null)
    })), {})
  }))
  default = {}
}

resource "aws_network_acl" "this" {
  for_each   = var.configuration
  vpc_id     = aws_vpc.this.id
  subnet_ids = [aws_subnet.this[each.key].id]

  # this is using attribute-as-blocks instead of dynamic blocks
  ingress = [
    for key, value in each.value.ingress_rules : {
      rule_no         = tonumber(key)
      from_port       = value.from_port
      to_port         = value.to_port
      action          = value.action
      protocol        = value.protocol
      cidr_block      = value.cidr_block
      ipv6_cidr_block = value.ipv6_cidr_block
      icmp_type       = value.icmp_type
      icmp_code       = value.icmp_code
    }
  ]

  tags = {
    Name = format("%s-acl", each.key)
  }
}
```

and here is my example terraform.tfvars
```
configuration = {
  my-demo1-snet = {
    cidr_block        = "10.0.1.0/24"
    availability_zone = "ap-southeast-2b"
    ingress_rules = {
      100 = {
        action      = "allow"
        protocol    = "tcp"
        cidr_block  = "10.3.0.0/18"
        from_port   = 80
        to_port     = 80
      },
      200 = {
        action      = "allow"
        protocol    = "tcp"
        cidr_block  = "10.3.0.0/18"
        from_port   = 443
        to_port     = 443
      },
    }
  }
  my-demo2-snet = {
    cidr_block        = "10.0.2.0/24"
    availability_zone = "ap-southeast-2a"
  }
  my-demo3-snet = {
    cidr_block           = "10.0.3.0/24"
    availability_zone_id = "apse2-az3"
  }
}
```

This effectively allows me to leave ingress_rules = {} or fully ommit it and all the ingress rules gets removed.
Although, you still hit that issue where in it recreates the whole block whenever you add or remove items from your collection because the underlying dynamic block is of list type.

**Comment by justinretzolk** [comment]
With the previous comments and the [`aws_network_acl_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl_rule) resource in mind, I'll close this issue. If you run into any other issues with the provider, please do let us know!
