### ISSUE TITLE
add account alias support to backend

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform-provider-aws#2965]
### Terraform Version
Terraform v0.11.2
+ provider.aws v1.7.0

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    bucket = "terraform-state"

    role_arn = "arn:aws:iam::ACCOUNTALIAS:role/OrganizationAccountAccessRole"
    acl      = "bucket-owner-full-control"
    key      = "test/terraform.tfstate"
    region   = "eu-west-1"
  }
}

provider "aws" {
  region = "eu-west-1"

  assume_role {
    role_arn     = "arn:aws:iam::ACCOUNTID:role/OrganizationAccountAccessRole"
    session_name = "POC"
  }
}
```

### Debug Output
```
terraform init

Initializing the backend...

Error configuring the backend "s3": The role "arn:aws:iam::yopa-poc:role/OrganizationAccountAccessRole" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

### Expected Behavior
for init to run as it would if there was a numeric account id in the backend role_arn parameter

### Actual Behavior
error message of "cannot be assumed."

### Steps to Reproduce
terraform init

**Comment by MrGossett** [comment]
AWS doesn't support the use of account aliases in ARNs. You'll need to use the Account ID instead.

Some more info: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html

**Comment by FernandoMiguel** [comment]
Terraform has no problem using it in the provider block, nor has aws issues with it in aws cli config file or cli commands.
I have a shell script to create accounts with AWS Orgs and it works fine with account alias.

**Comment by FernandoMiguel** [comment]
Terraform has no problem using it in the provider block, nor has aws issues with it in aws cli config file or cli commands.
I have a shell script to create accounts with AWS Orgs and it works fine with account alias.

**Comment by FernandoMiguel** [comment]
I've reread that doc and couldn't find any note stating that account alias should not be used.
Could you please point me to such documentation? 

Cheers

**Comment by apparentlymart** [comment]
Hi @FernandoMiguel,

Most of the authentication code is common between Terraform Core and the AWS provider, but Terraform Core sometimes lags behind new faetures in the AWS provider because it is not released as often and the referenced code must be explicitly updated in Terraform Core.

With that said, I'm not sure off the top of my head if support for aliases here was a recent addition to the provider or not. It might also be a change to the underlying SDK, which again is often newer in the AWS provider than it is in Terraform Core.

I think a first step here would be to try upgrading the AWS provider code and AWS SDK code in Terraform Core and see if account aliases then work as expected. If that fixes it, then we can hopefully just update those vendored codebases in Terraform Core and get this support in the next release.

**Comment by FernandoMiguel** [comment]
I can forward you that this has been an issue from tf core 0.10.x all the way till today.
AWS provider worked since at least v1... I didn't test before

**Comment by JoostSaanen** [comment]
Is this still not possible?

**Comment by FernandoMiguel** [comment]
Just check-in if there is any update for this
