### ISSUE TITLE
[Docs]: Add Configuration for runtime_environment_secrets

### ISSUE THREAD

**Issue by fracampit** [hashicorp/terraform-provider-aws#29681]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_service#runtime_environment_secrets

### Description

There are no configuration details for these values, which are not intuitive and need to be given very specific values to get the desired behavior.

The documentation should for example illustrate that if you want the app to get values from Secrets Manager instead of SSM Parameter Store, you need to provide the ARN of the secret instead of the name of the secret, or the app will interpret the variable as a SSM Parameter Store parameter and fail.

### Would you like to implement a fix?

None

**Comment by Antvirf** [comment]
@fracampit  Did you find a way to make this work with secrets manager? You mention having to provide "ARN of the secret instead of name of the secret"?

Let's say we have a secret called `API_KEY`, value `88888888`, arn `arn:XXXXXXXX`, created in a TF resource called `key` - how should one fill `runtime_environment_secrets`?

So far I've tried
```
runtime_environment_secrets = {
 aws_secretsmanager_secret.key.arn = "" # assuming it was the name of the secret we had to replace with ARN
}

runtime_environment_secrets = {
 API_KEY = aws_secretsmanager_secret.key.arn # if we provide the ARN as value
}

runtime_environment_secrets = {
 aws_secretsmanager_secret.key.arn # this isn't accepted by terraform since it has to be a map
}

```


I'm running into this right now, happy to submit a fix if I can find a working solution.

**Comment by fracampit** [comment]
yes, I do have this working with both SSM and Secrets Manager.
I cannot access the code at the moment, but I'm pretty sure the format is along the lines of your second example.
I will come back to this tomorrow with an example code that works on my setup.

**Comment by Antvirf** [comment]
> @Antvirf yes, I do have this working with both SSM and Secrets Manager. I cannot access the code at the moment, but I'm pretty sure the format is along the lines of your second example.
> 
> ```
> runtime_environment_secrets = {
>  NAME_OF_THE_ENV_VAR_YOU_APP_EXPECTS = arn_of_the_secret
> }
> ```
> 
> I will come back to this tomorrow with an example code that works on my setup.

This was indeed correct - the problem was that I was using the AWS App Runner terraform **module** which didn't have this feature at the time of writing. I've submitted a [PR to extend the module for this use case](https://github.com/terraform-aws-modules/terraform-aws-app-runner/pull/5) and will have a look at this docs one now.
