### ISSUE TITLE
[Enhancement]: Erratic behavior on different commands on environment variables

### ISSUE THREAD

**Issue by saulortega** [hashicorp/terraform-provider-aws#29693]
### Description

```
Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.56.0
```

```terraform
# main.tf

variable "AWS_ACCESS_KEY_ID" {
  type = string
}

variable "AWS_SECRET_ACCESS_KEY" {
  type = string
}

variable "AWS_SESSION_TOKEN" {
  type = string
}

provider "aws" {
  access_key = var.AWS_ACCESS_KEY_ID
  secret_key = var.AWS_SECRET_ACCESS_KEY
  token      = var.AWS_SESSION_TOKEN
}
```

## Scenario 1: Those three variables ARE set on environment.

On `terraform plan` it ask for the variables. It seems **wrong** to me.

```
var.AWS_ACCESS_KEY_ID
    Enter a value:
```

On `terraform state push errored.tfstate` it DOESN'T ask for the variables. It seems **OK** to me.

## Scenario 2: Those three variables AREN'T set on environment.

On `terraform plan` it ask for the variables. It seems **OK** to me.

```
var.AWS_ACCESS_KEY_ID
    Enter a value:
```

On `terraform state push errored.tfstate` it DOESN'T ask for the variables. It seems **wrong** to me. The command doesn't work, it returns an error. 

### Potential Terraform Configuration

```terraform
Expected behavior:

If variables are set in environment it should never ask for them.
If variables aren't set in environment it should always ask for them.
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @saulortega 👋 Thank you for taking the time to raise this! In order to give an exact answer as to what is happening, we'll need a bit more information. That said, I've got a bit of general information that might lead to an answer in the meantime. Can you clarify:

- Am I correct in assuming you're using the [S3 backend](https://developer.hashicorp.com/terraform/language/settings/backends/s3) and are not passing the authentication arguments within the backend configuration? Supplying the backend configuration (redacted as needed) could help me to visualize this.
- Am I correct in assuming that you're exporting the environment variables as `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN` respectively?

If I'm correct in my assumption that you're exporting the environment variables as mentioned above, and that you're using the S3 backend, Terraform is behaving as I would expect. To explain why, I'll start with the S3 backend.

When [configuring the S3 backend](https://developer.hashicorp.com/terraform/language/settings/backends/s3#configuration), the environment variables that can be used to authenticate the backend are as you would expect; `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`. These can also be set using the `access_key`, `secret_key`, and `session_token` arguments of the backend block as well, which is where knowing how your backend is configured would be helpful. I am uncertain off of the top of my head of the ordering in which these are prioritized, but can check into that.

When [configuring the AWS Provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration), the authentication configuration is picked up first by parameters in the provider configuration, then by environment variables, and so on. In your case, you have parameters in the configuration (e.g. `access_key = var.AWS_ACCESS_KEY_ID`), so this will be preferred. That Terraform is asking for these variables when you run a `terraform apply` indicates that the value for these variables has not been set at run time. The value for Terraform variables _can_ be picked up automatically from environment variables, however, there is a [specific naming scheme](https://developer.hashicorp.com/terraform/language/values/variables#environment-variables) required to do so.

If all of these assumptions are correct, what is happening is that Terraform (core) is able to authenticate due to the environment variables being present, and so you're able to push the state to S3. However, the AWS Provider is not able to authenticate, as the values for the authentication configuration have not been set.

I hope this helps clear things up. If you have any lingering questions, and are able to provide the info I mentioned above, that may help me to clarify a bit further.
