### ISSUE TITLE
[Enhancement]: Stopping an Amazon RDS DB instance temporarily

### ISSUE THREAD

**Issue by erz4** [hashicorp/terraform-provider-aws#29757]
### Description

RDS has a capability that the terraform module does not cover - the ability to temporarily stop an RDS cluster.

### Affected Resource(s) and/or Data Source(s)

* aws_db_instance

### Potential Terraform Configuration

```terraform
resource "aws_db_instance" "example" {
  # ... other configuration ...

  stop_temporarily = true
}
```

### References

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_StopInstance.html

### Would you like to implement a fix?

No

**Comment by atobaum** [comment]
I need this feature too.

**Comment by hnsvill** [comment]
Quick link to the docs: this was implemented as a separate resource [aws_rds_instance_state](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_instance_state) instead of a property of the [aws_db_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance) resource.

Thanks for raising this and to all who contributed to this functionality! ✨
