### ISSUE TITLE
[Bug]:  Neputne_cluster. Fix Major Version Upgrade from 1.1.1.0 to 1.2.0.0

### ISSUE THREAD

**Issue by kastlbo** [hashicorp/terraform-provider-aws#29785]
### Terraform Core Version

1.3.8

### AWS Provider Version

4.55.0

### Affected Resource(s)

aws_neptune_cluster

### Expected Behavior

I am trying to upgrade the neptune cluster version from 1.1.1.0 to 1.2.0.0.

I am expecting it to remove the instances and upgrade the cluster to the newer version and then recreate the instances.

### Actual Behavior

It is removing the instances but not upgrading the cluster.
I get the following error.

InvalidDBClusterStateFault: Cannot modify engine version without a healthy primary instance in DB cluster:

I previously had the same problem when upgrading from 1.0.4.1 to 1.1.1.0.
You fixed this with provider 4.55.0
The previous  issue was r/neptune_cluster - fix major version upgrade #28051
Looks like the same thing is happening when you try to upgrade from 1.1.1.0 to 1.2.0.0

### Terraform Configuration Files

n/a

### Steps to Reproduce

n/a

### Would you like to implement a fix?

None

**Comment by hanlong-chen-1047** [comment]
Is there any update on this issue?

**Comment by kastlbo** [comment]
There seems to be a glich when upgrading you clusters with terraform.  I found that if you have an instance declartion in your  terraform you must leave that version as the previous version and only update the main cluster resource.  It needs to have the instances available to upgrade the cluster.  So if you leave the instances as the old version number it will work.  Once upgraded it will automatically update the instances.  Also, will upgrading to newer versions of neptune the parameter groups change as well.  It wasn't fun trying to upgrade to 1.2 from 1.04.1.  You have to step up to 1.1.0 and then when you go to 1.2 the parameter group changes.  I also found an issue with the size of cluster some sizes where removed in never versions.  Enjoy

**Comment by triggan** [comment]
I actually see what the issue here is.  Neptune engine versions are applied at a cluster level and all instances within the cluster get upgraded at the same time.  The logic in the Terraform AWS Provider is attempting to replace instances if an `engine_version` is specified per `aws_neptune_cluster_instance` resource.  Ultimately, the `engine_version` parameter should be ignored when applied to an instance, as you cannot have a Neptune cluster with instances on different engine versions.  If you comment out the `engine_version` parameter on the `aws_neptune_cluster_instance` resources, the engine upgrade gets applied without replacing the instances and the instances are restarted with the specified `engine_version` applied at the `aws_neptune_cluster` resource, as expected.
