### ISSUE TITLE
[Bug]: Upgrading Aurora DB engine version produces an error

### ISSUE THREAD

**Issue by yoav-klein** [hashicorp/terraform-provider-aws#29861]
### Terraform Core Version

1.3.8

### AWS Provider Version

4.57.0

### Affected Resource(s)

* aws_rds_cluster
* aws_rds_instance

### Expected Behavior

I've created a Aurora MySQL DB cluster with no problems, with engine version `2.07.8`, and then changed the version in the Terraform configuration to 2.11.1, and received an error

### Actual Behavior

An error is produced, see the below snippet

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.mysql_cluster.aws_rds_cluster_instance.this[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced
│ an invalid new value for .engine_version: was cty.StringVal("5.7.mysql_aurora.2.11.1"), but now cty.StringVal("5.7.mysql_aurora.2.07.8").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Terraform Configuration Files

Please browse to my GitHub repo:
https://github.com/yoav-klein/terraform/tree/695797c77868c1ed85fe069289f7ea59843e7b06

In there, we have the `aws/modules/aurora-mysql` which is a module that creates a Aurora MySQL cluster.
We also have the `aws/configurations/aurora-mysql`, which is a configuration which uses the above module, along with
some other modules, to create a VPC, a cluster, an EC2 instance.

### Steps to Reproduce

* Run the configuration with `terraform apply` with the `2.07.8` version. this should work fine
* Change the version to `2.11.1`, and apply the configuration again.

### Would you like to implement a fix?

None

**Comment by Mrunu07** [comment]
Hello Team ,
We are also facing simmilar issue when trying to upgrade the minor version of MySQL engine , our configurations are as below:
Terraform v1.4.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.58.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.microservices_stage_rds.aws_rds_cluster_instance.aurora_cluster_instances[0] to include new
│ values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .engine_version: was cty.StringVal("8.0.mysql_aurora.3.03.0"), but now cty.StringVal("8.0.mysql_aurora.3.02.2").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

**Comment by tstraley** [comment]
Facing this with aurora postgresql as well:

Terraform 1.3.9
provider registry.terraform.io/hashicorp/aws 4.58.0

Tried to upgrade postgres from 13.7 to 13.9 by changing engine_version on the `aws_rds_cluster` resource, and received the following error on each `aws_rds_cluster_instance` resource associated with the cluster:

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.db.aws_rds_cluster_instance.aurora_postgres[1] to include new values
│ learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
│ produced an invalid new value for .engine_version: was
│ cty.StringVal("13.9"), but now cty.StringVal("13.8").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

This error did not show up in our dev environments, possibly because we use `apply_immediately` setting there, but for this environment we want the upgrade to take place during next RDS maintenance window.


Configuration is roughly as follows:

```
resource "aws_rds_cluster" "aurora_postgres" {
  cluster_identifier     = var.cluster_name
  engine                 = "aurora-postgresql"
  engine_version         = "13.9"
  engine_mode            = "provisioned"
  vpc_security_group_ids = [aws_security_group.db_cluster_sg.id]
  db_subnet_group_name   = aws_db_subnet_group.cluster_sn_group.name
  database_name          = var.init_database_name

  allow_major_version_upgrade = false

  apply_immediately   = var.apply_immediately # false for this env
  deletion_protection = true
  storage_encrypted   = true
  ...
}

resource "aws_rds_cluster_instance" "aurora_postgres" {
  count                = var.num_instances
  identifier           = "${var.cluster_name}-instance-${count.index}"
  cluster_identifier   = aws_rds_cluster.aurora_postgres.id
  engine               = aws_rds_cluster.aurora_postgres.engine
  engine_version       = aws_rds_cluster.aurora_postgres.engine_version
  db_subnet_group_name = aws_rds_cluster.aurora_postgres.db_subnet_group_name

  auto_minor_version_upgrade   = false
  apply_immediately            = var.apply_immediately # false for this env
  instance_class               = var.instance_size
  publicly_accessible          = false
  preferred_maintenance_window = var.maintenance_window
}
``` 

Note that the `aws_rds_cluster_instance` `engine_version` is defined using the `aws_rds_cluster`'s attribute per the documentation here https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance

**Comment by tstraley** [comment]
Looks related https://github.com/hashicorp/terraform-provider-aws/issues/28659

**Comment by tstraley** [comment]
Related to:

* https://github.com/hashicorp/terraform-provider-aws/issues/22022
* https://github.com/hashicorp/terraform-provider-aws/issues/15377

Suggested workarounds include setting `apply_immediately` to `true` or specifying the engine_version explicitly rather than as a reference to the cluster resource. I'm not clear on what happens if engine_version is just removed from the instance resource - it is documented as optional, and I'd assume it must auto-sync with the rds_cluster version?
