### ISSUE TITLE
Support tags for aws_db_instance data source

### ISSUE THREAD

**Issue by joshma** [hashicorp/terraform-provider-aws#2988]
### Terraform Version
`0.11.2.`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_db_instance (data source)

### Expected Behavior
When using an `aws_db_instance` data source, I'd like to filter by tags to find the instance.

### Actual Behavior
Only db_instance_identifier is currently supported.

**Comment by atamgp** [comment]
yes pls add this

**Comment by sean-zou** [comment]
I'm surprised that it is still not supported. Please add this.

**Comment by bflad** [comment]
Ah looking at the original issue here, it appears the ask is for `tags` as an argument (to filter results), not just returning the tags associated with a database instance. The latter will be supported in version 2.35.0 of the Terraform AWS Provider releasing next Thursday, but reopening for the original ask.

**Comment by marcoacierno** [comment]
I am trying to implement it (here: https://github.com/hashicorp/terraform-provider-aws/compare/main...marcoacierno:implement-data-source-aws-db-instance-filter?expand=1) but I am getting

```
aws/data_source_aws_db_instance.go:228:16: cannot use buildAwsDataSourceFilters(v.(*schema.Set)) (type []*"github.com/aws/aws-sdk-go/service/ec2".Filter) as type []*rds.Filter in assignment
```

buildAwsDataSourceFilters returns this ec2.Filter

```
func buildAwsDataSourceFilters(set *schema.Set) []*ec2.Filter {
```

checking at all other codes that does the same thing, it doesn't seem to have any issue, is it not working for RDS because rds filter also have additional filters such as engine and so on? 🤔 

I am not a go expert so any help is welcome :)

**Comment by hemzet** [comment]
Especially when hex values are automatically added to db snapshot identifiers, as done in the TF RDS modules, the actual name of a snapshot is unknown so any data resource request fails. The tag filter extension is highly needed.
