### ISSUE TITLE
Dinamically retrieve all second level OU

### ISSUE THREAD

**Issue by giapoce** [hashicorp/terraform-provider-aws#29898]
### Description

Hi guys,

I'm trying to dinamically retrieve all second level organizational units in an AWS organization and map a specific Service Control Policy to each one of them but I'm having some difficulties to find the right sintax.
I managed to map all first level organizational units, that is all OUs whose parent is root, but there doesn't seem to be any data source data.aws_organizations_organizational_unit ( no ending "s" ....) to go one level down and without that I can't see any way to achieve the result.

Can someone help me?

Thank you

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @giapoce 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
