### ISSUE TITLE
[Bug]: Cognito User Pool can't use deletion_protection argument

### ISSUE THREAD

**Issue by eechien** [hashicorp/terraform-provider-aws#30059]
### Terraform Core Version

0.15.0

### AWS Provider Version

4.58.0

### Affected Resource(s)

* aws_cognito_user_pool

### Expected Behavior

```
# aws_cognito_user_pool.user_pool will be created
 + resource "aws_cognito_user_pool" "user_pool" {
 + arn                        = (known after apply)
 + creation_date              = (known after apply)
 + custom_domain              = (known after apply)
 + deletion_protection        = "ACTIVE"
 ...
}
```

### Actual Behavior

```
│ Error: Unsupported argument
|
│   on main.tf line 22, in resource "aws_cognito_user_pool" "user_pool":
│   22:   deletion_protection        = "ACTIVE"
│ 
│ An argument named "deletion_protection" is not expected here.
|
time=2023-03-16T13:21:43Z level=error msg=1 error occurred:
	* exit status 1
 [INFO] [infrastructure-deploy-script] 2023-03-16 13:21:43  "terragrunt plan" exited with code 1
 Error: Could not run "terragrunt plan"
 exit status 1
 ERROR: exit status 1
```

### Terraform Configuration Files

```
terraform {
  # This module is now only being tested with Terraform 1.1.x. However, to make upgrading easier, we are setting 1.0.0 as the minimum version.
  required_version = ">= 0.15.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.58.0"
    }
  }
}

resource "aws_cognito_user_pool" "user_pool" {
  name                      = "example_pool"
  deletion_protection       = "ACTIVE"
}
```

### Steps to Reproduce

Run `terragrunt plan` using the above resource

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @eechien 👋 Thank you for taking the time to raise this! I see that you supplied the version of Terraform and the AWS Provider that you're using, and are using `required_version` and `required_providers` with a `version` set, however, the `deletion_protection` argument was added in [version `4.38.0`](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4380-november--3-2022) of the provider, and is [in the schema](https://github.com/hashicorp/terraform-provider-aws/blob/c47c5d27a0e66d8a02613aae81fe4cb080f0e380/internal/service/cognitoidp/user_pool.go#L141-L146), so I wouldn't expect that error message with the supplied version of the provider.

Can you run `terraform -v` so that we can see what versions Terraform is reporting? It may also be helpful to supply debug logs (redacted as necessary) if you're finding that the versions that you initially reported are the same as what you get when running `terraform -v`.

**Comment by eechien** [comment]
Our provider version is lower than I thought. Closing this ticket.
