### ISSUE TITLE
[Bug]: aws_controltower_control is not idempotent 

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform-provider-aws#30141]
### Terraform Core Version

1.4.1

### AWS Provider Version

v4.59.0

### Affected Resource(s)

When a control is already enabled for a target ID, `aws_controltower_control` fails saying that it is already enabled: 
```
ValidationException: Control AWS-GR_DETECT_CLOUDTRAIL_ENABLED_ON_MEMBER_ACCOUNTS is already enabled on organizational unit ou-py6g-blahblahblah
```

### Expected Behavior

I would expect the resource to behave in an idempotent fashion by ignoring the error and carrying on. 

### Actual Behavior

It fails with 

```
ValidationException: Control AWS-GR_DETECT_CLOUDTRAIL_ENABLED_ON_MEMBER_ACCOUNTS is already enabled on organizational unit ou-py6g-blahblahblah
```

### Terraform Configuration Files

```hcl
resource "aws_controltower_control" "security" {
  for_each = toset(
    flatten([
      var.strongly_recommended_policies, [
        # Stopped EC2 instances should be removed after a specified time period
        # https://docs.aws.amazon.com/config/latest/developerguide/ec2-stopped-instance.html
        "CVCROVPNPPCG",
      ]
    ])
  )
  control_identifier = "arn:aws:controltower:${data.aws_region.current.name}::control/${each.value}"
  target_identifier = [
    for x in data.aws_organizations_organizational_units.redpanda.children :
    x.arn if x.name == "Security"
  ][0]
}
```

### Steps to Reproduce

1. Create a `aws_controltower_control` resource applying any policy that's already enabled out of band for a given organizational unit
2. terraform apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @c4milo 👋 Thank you for taking the time to raise this! You can get around this by [importing](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/controltower_control#import) the control into the Terraform state. Once imported, on the next Terraform run, you shouldn't receive the error you noted.

**Comment by c4milo** [comment]
hey! sure, yes, we are aware of being able to import resources. Does that mean this is not a bug, though?

**Comment by justinretzolk** [comment]
Hey @c4milo 👋 Unless I'm missing a key piece of data here, I would not consider this to be a bug. When the resource is declared in the configuration, and the first `terraform apply` happens, Terraform does not "know" (it's not in the state) that the control is enabled. Due to this, Terraform will attempt to enable it using the requisite API call, which errors due to the control being enabled already. This is why the import functionality exists -- to allow Terraform to assume management of resources that already exist, but are not yet known to Terraform.

It may be more helpful to think of this in terms of something other than a setting such as this -- let's say an S3 bucket. Suppose a scenario where there is an existing S3 bucket named "MyS3Bucket". If I were to write a Terraform configuration that aimed at creating an S3 bucket, and I happened to name it "MyS3Bucket", Terraform would throw an error that the bucket already exists. This is preferable to Terraform assuming that I want to assume managing the existing S3 bucket with this Terraform configuration and thus importing it into the state, as Terraform has no way of knowing whether or not that was my intent. If I did, in fact, wish to assume managing the existing S3 bucket with this Terraform configuration, I'd just need to run a `terraform import` to explicitly tell Terraform that that's what I wished to do.

I recognize that this isn't exactly an apples to apples comparison, but I hope it helps illustrate my point a bit.

**Comment by mbevc1** [comment]
I can see you point of defining a resource and this is probably awkwardly exposed API upstream in AWS as well (as not part of something like AWS Control Tower :) ). Nevertheless I'm not sure it makes sense, as you are technically not creating a Control, but rather attaching it to specific OU. Perhaps that's why it could be confusing to people and it feels indeed it should detect outside changes/drift in case Control was already enabled or that changes outside of the state. Are there any technical reasons why this is not the case, please mind I haven't checked provider implementation or upstream API endpoint capabilities yet?

**Comment by c4milo** [comment]
@justinretzolk, that makes sense if we consider the existing Terraform behavior is correct. If a resource already exist and my declaration of intent is for it to exist, Terraform should act idempotently and not return an error, importing the resource into its state. Similar situation with destroy operations, if the resource does not exist and my intent is to remove it, it should not error out if it is already deleted. That said, I know this is a fundamental change on Terraform core, out of the scope of this provider, so please feel free to close the issue.

**Comment by justinretzolk** [comment]
Hey @c4milo 👋 Thanks for your understanding, and for chatting with me about this! With that in mind, I'll go ahead and close this one out. For what it's worth, Terraform [version 1.5.0 will introduce an `import` block](https://github.com/hashicorp/terraform/blob/v1.5/CHANGELOG.md) that may wind up being useful in these types of scenarios.

**Comment by c4milo** [comment]
@justinretzolk, ohh! interesting, I may help. We are basically having to: 

* **Apply**: Import when the resource should be tracked but it is not
* **Destroy**: Remove from the state when the resource was already deleted
