### ISSUE TITLE
Grating read permissions to aws s3 object with private bucket

### ISSUE THREAD

**Issue by ahmad1508** [hashicorp/terraform-provider-aws#30818]
### Description

Hello,
I'm trying to create an aws private s3 bucket using terraform and store some files in it. I want the files to be accessible by everyone.
I've tryed using "aws_s3_bucket_public_access_block" with 

```terraform
  block_public_acls       = false
  block_public_policy     = false
  ignore_public_acls      = false
  restrict_public_buckets = false
```

and adding "aws_s3_bucket_acl" with acl set to "public-read" and tryed using access _control_policy.

I can't seem to find a way but i know i did something wrong somewhere. Here's my code

```terraform
resource "aws_s3_bucket" "s3" {
  bucket = var.bucket_name
  tags = {
    Name        = var.bucket_name
    Environment = "Dev"
  }
}

data "aws_canonical_user_id" "current" {}

resource "aws_s3_bucket_ownership_controls" "s3_ownership" {
  bucket = aws_s3_bucket.s3.id
  rule {
    object_ownership = "BucketOwnerPreferred"
  }
}

resource "aws_s3_bucket_public_access_block" "s3_public_access" {
  bucket = aws_s3_bucket.s3.id

  block_public_acls       = false
  block_public_policy     = false
  ignore_public_acls      = false
  restrict_public_buckets = false
}

resource "aws_s3_bucket_acl" "s3_acl" {
  depends_on = [
    aws_s3_bucket_ownership_controls.s3_ownership,
    aws_s3_bucket_public_access_block.s3_public_access,
  ]

  bucket = aws_s3_bucket.s3.id
  acl = "public-read"
}
```

**Comment by justinretzolk** [comment]
Hey @ahmad1508 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
