### ISSUE TITLE
[Bug]: aws_api_gateway_vpc_link doesn't support ALB

### ISSUE THREAD

**Issue by ystoneman** [hashicorp/terraform-provider-aws#30910]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.63.0

### Affected Resource(s)

aws_api_gateway_vpc_link

### Expected Behavior

It should support ALB.

### Actual Behavior

It expects NLB.

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating API Gateway VPC Link (example_vpc_link): waiting for completion: FAILED: NLB ARN is malformed
│ 
│   with aws_api_gateway_vpc_link.example_vpc_link,
│   on main.tf line 139, in resource "aws_api_gateway_vpc_link" "example_vpc_link":
│  139: resource "aws_api_gateway_vpc_link" "example_vpc_link" {
│ 
╵
```

### Terraform Configuration Files

```terraform
locals {
  vpc_id         = "vpc-123456789123"
  subnet_ids     = ["subnet-98765432", "subnet-12346789"]
}

resource "aws_api_gateway_vpc_link" "example_vpc_link" {
  name        = "example_vpc_link"
  target_arns = [aws_lb.example_lb.arn]
}

resource "aws_lb" "example_lb" {
  name               = "example-lb"
  internal           = true
  load_balancer_type = "application"
  security_groups    = [aws_security_group.example_sg.id]
  subnets            = local.subnet_ids
}

resource "aws_security_group" "example_sg" {
  name        = "example_sg"
  description = "Example security group for ECS service"
  vpc_id      = local.vpc_id

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

### Steps to Reproduce

1. Include your VPC ID and Subnet IDs in the locals.
2. `terraform apply`

### Important Factoids

The [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_vpc_link) includes `load_balancer_type = "network"` in the example usage, but doesn't include `load_balancer_type` in the Argument reference.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ystoneman 👋 Thank you for taking the time to raise this! I believe the resource you're looking for in this case is the [`aws_apigatewayv2_vpc_link` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_vpc_link). If I'm recalling correctly, the `aws_apigateway_vpc_link` resource does not support ALBs (this is a limitation on the AWS side).

In regards to the `load_balancer_type` argument in the example that you linked, that argument is for the `aws_lb` resource rather than the `aws_apigateway_vpc_link` resource, which is why it's not documented on that page.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
