### ISSUE TITLE
[Bug]: aws_lambda_invocation overrides the passed arn to the function_name

### ISSUE THREAD

**Issue by sakula4** [hashicorp/terraform-provider-aws#30913]
### Terraform Core Version

1.2.6

### AWS Provider Version

4.29.0

### Affected Resource(s)

* aws_lambda_invocation

### Expected Behavior

when a lambda ARN is passed to the `function_name`, it should have executed the defined lambda without overriding the `account_id`

### Actual Behavior

Usecase - Trigger a lambda in a target(222222222) account from the source(111111111) account. Created a lambda and added the source account user/role as authorized to invoke lambda. Able to test it with aws cli. However when I tried to perform the same with terraform, I got the `AccessDeniedException` with a 403 error. 

For triage, I used the data "aws_lambda_function"
```
data "aws_lambda_function" "existing" {
  function_name = "testLambdaS3"
  arn           = "arn:aws:lambda:us-east-1:222222222:function:testLambdaS3"
}
```
**Output**
```
╷
│ Error: error getting Lambda Function (testLambdaS3) Code Signing Config: ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:111111111:function:testLambdaS3
│ {
│   RespMetadata: {
│     StatusCode: 404,
│     RequestID: "9db3963b-2216-4dca-9e27-99c0816dc1e8"
│   },
│   Message_: "Function not found: arn:aws:lambda:us-east-1:111111111:function:testLambdaS3",
│   Type: "User"
│ }
│
│   with data.aws_lambda_function.existing,
│   on main.tf line 35, in data "aws_lambda_function" "existing":
│   35: data "aws_lambda_function" "existing" {
```

### Relevant Error/Panic Output Snippet

```shell
│ Error: AccessDeniedException: 
│       status code: 403, request id: 96b4b49a-9fc5-4cb9-b2f2-809b0f9e515e
│
│   with data.aws_lambda_invocation.example
```

### Terraform Configuration Files

NA

### Steps to Reproduce

As stated above

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @sakula4 👋 Thank you for taking the time to raise this! For the `aws_lambda_function` data source, the `arn` is an attribute rather than an argument. This means that in the example provided, the data source will only use the `function_name` to try to retrieve the information around the existing Lambda function. If you'd like to look up a Lambda function in a separate account, you can utilize an [aliased provider](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations) to do so.
