### ISSUE TITLE
[Docs]: terraform cli reports`excluded_rule` block under `rule_group_reference_statement` is deprecated while the `aws_wafv2_web_acl` does not mention this.

### ISSUE THREAD

**Issue by 0xabdi** [hashicorp/terraform-provider-aws#31042]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html#rule_group_reference_statement

### Description

terraform cli reports `excluded_rule` block under `rule_group_reference_statement` is deprecated while the terraform `aws_wafv2_web_acl` resource documentation does not mention this. It only specifies that this block is optional.

```

Warning: Argument is deprecated
...
with module.web_acl_example.aws_wafv2_web_acl.web_acl[0]
...
Use rule_action_override instead
```

### References

https://docs.aws.amazon.com/waf/latest/APIReference/API_RuleGroupReferenceStatement.html

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @armenr 👋 Can you give me a better idea of how you're currently stuck? I'd like to try to help if I can, but need a bit more context so that I can know which direction to head in.

**Comment by justinretzolk** [comment]
@armenr -- I appreciate the kind words and the follow up with a solution in case anyone else stumbles across this! Since you're in the clear as well, I'll go ahead and close this issue back out.

Note: If anyone else runs into this, and the information above doesn't help, please do open a new issues so that we can get eyes on it.
