### ISSUE TITLE
Amazon MSK multi-VPC private connectivity and cross-account access

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#31062]
Amazon MSK now offers multi-VPC private connectivity and cross-account access.

[Announcement](https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-msk-multi-vpc-private-connectivity-cross-account-access/).
[Blog post](https://aws.amazon.com/blogs/big-data/connect-kafka-client-applications-securely-to-your-amazon-msk-cluster-from-different-vpcs-and-aws-accounts/).

#### New Resources

* `aws_msk_vpc_connection`
* `aws_msk_cluster_policy`

Requires [AWS SDK for Go v1.44.252](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.252): https://github.com/hashicorp/terraform-provider-aws/pull/31028.

**Comment by universalvishwa** [comment]
I'm so looking forward to this feature. Thank you.

**Comment by jmengoni** [comment]
Those changes have been implemented in awscc:
- The security policy is added as a new attribute in the [aws_msk_cluster/broker_node_group_info.connectivity_info](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/msk_cluster#nested-schema-for-broker_node_group_infoconnectivity_info)
- The vpc connection is a new resource [aws_msk_vpc_connection](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/msk_vpc_connection)

It seems to match the current implementation of the AWS provider, so wouldn't it be better to follow this solution rather than to create a new aws_msk_cluster_policy?

**Comment by universalvishwa** [comment]
We will need to create a new resource for that as per my experiments. Because ability to set the resource policy for MSK cluster only enabled (in the AWS console and AWS CLI) after I enabled multi-VPC connectivity in the cluster.
It would be good if someone can verify what I noticed when I was experimenting on this.

Also why can't they implement it on normal TF aws provider instead of this `awscc` provider? Is there a specific reason for doing it like this?

**Comment by markoskandylis** [comment]
Hi, i will start working with this, this week

**Comment by kp-tom-sc** [comment]
> It would be good if someone can verify what I noticed when I was experimenting on this.

This is my experience as well, you have to start by setting things to false, and then enabling them.

**Comment by vishwa-trulioo** [comment]
@ewbankkit  Thank you very much for getting the `aws_msk_vpc_connection` resource and the respective updates on `aws_msk_cluster` in `5.12.0` release. Looking forward to the `aws_msk_cluster_policy` resource soon. You rock!
