### ISSUE TITLE
[Bug]: s3_bucket_lifecycle_configuration rule id squashing

### ISSUE THREAD

**Issue by ripesensor** [hashicorp/terraform-provider-aws#31409]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.66.1

### Affected Resource(s)

aws_s3_bucket_lifecycle_configuration

### Expected Behavior

Two completely separate Terraform configurations pointing to the same bucket will squash each other when it comes to `aws_s3_bucket_lifecycle_configuration`'s. You'd think this would be okay if the rule `id` for each was unique.

### Actual Behavior

`aws_s3_bucket_lifecycle_configuration` will completely remove any configs created by another Terraform template.

### Terraform Configuration Files

```
# Configuration A
resource "aws_s3_bucket_lifecycle_configuration" "bucket" {
  bucket = var.s3_bucket_name

  rule {
    id = "id_A"

    noncurrent_version_expiration {
      noncurrent_days = var.non_current_version_expiration_after_days
    }

    status = "Enabled"
  }
}
```
```
# Configuration B
resource "aws_s3_bucket_lifecycle_configuration" "bucket" {
  bucket = var.s3_bucket_name

  rule {
    id = "id_B"

    transition {
      days = var.glacier_instant_retrieval_transition_after_days
      storage_class = "GLACIER_IR"
    }

    status = "Enabled"
  }
}
```

### Steps to Reproduce

With two separate Terraform configurations, ask each to add a `aws_s3_bucket_lifecycle_configuration`, each with unique rule `id`'s, pointing to the same S3 `bucket`. One config will remove and replace the other's rules.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ripesensor 👋 Thank you for taking the time to raise this! This is called out in the `aws_s3_bucket_lifecycle_configuration` [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration) with the following note:

> S3 Buckets only support a single lifecycle configuration. Declaring multiple `aws_s3_bucket_lifecycle_configuration` resources to the same S3 Bucket will cause a perpetual difference in configuration.

This is a difference between the lifecycle configuration as a whole vs a rule within the configuration. Each S3 bucket lifecycle configuration may have multiple rules within it, but each S3 bucket may only have one lifecycle configuration (which is what this resource ultimately manages). The [AWS Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/) currently only has a function for putting a lifecycle configuration (`PutBucketLifecycleConfiguration`); there is no function for only adding a rule to an existing lifecycle configuration. This is why the resource behaves the way that it does today.

Due to this upstream limitation, we'll close this issue out, but if the upstream limitation changes at some point, we'd be happy to look at this again.
