### ISSUE TITLE
[Enhancement]: aws_rds_cluster: Support for Aurora I/O-Optimized Storage

### ISSUE THREAD

**Issue by aviau** [hashicorp/terraform-provider-aws#31431]
### Description

Allow for enabling Aurora I/O-Optimized Storage as described in this article:
- https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-aurora-i-o-optimized/

### Affected Resource(s) and/or Data Source(s)

* aws_rds_cluster

### Would you like to implement a fix?

No

**Comment by aviau** [comment]
Nvm, looks like this is already available as follows:
```hcl
storage_type = "aurora-iopt1"
```

**Comment by bengotow** [comment]
Hey gang! This looks like it works great but for Aurora Serverless v2, changing the storage type to I/O optimized does not require instance replacement and Terraform thinks that it does. I modified my existing deployment manually in AWS and then updated Terraform to match because I didn't want to tear down and replace the databases.
