### ISSUE TITLE
[Bug]: Existing directory is not found when creating a new workspace via Terraform

### ISSUE THREAD

**Issue by i0na-k** [hashicorp/terraform-provider-aws#31482]
### Terraform Core Version

0.14.5

### AWS Provider Version

4.67.0

### Affected Resource(s)

I created a Simple AD directory using Terraform in eu-west-1 region. Later, I copy the ID when creating a new workspace. When running an apply I am seeing this error:

`Error: creating WorkSpaces Workspace: ResourceNotFound.Directory: The specified directory could not be found in the specified region.`

### Expected Behavior

I expect the directory ID to be recognised and valid, so Terraform can then create the applicable workspace.

### Actual Behavior

The Directory is not found:
`
Error: creating WorkSpaces Workspace: ResourceNotFound.Directory: The specified directory could not be found in the specified region.`

### Terraform Configuration Files

I have a backend.tf provider file where I am providing the configuration for storing state:

```
terraform {
  backend "remote" {
    hostname     = "hostname"
    organization = "my-org"
    workspaces {
      name = "my-workspace"
    }
  }
}
```
I am also using a provider.tf file, specifying regions and aliases:

```
provider "aws" {
  alias  = "eu-west-1"
  region = "eu-west-1"
}

provider "aws" {
  region = "us-east-1"
}

```

### Steps to Reproduce

Create a directory using this code:

```
data "aws_subnet" "private-subnet" {
  id = "subnet-040668cece81cbaa6"
}

data "aws_subnet" "private-subnet2" {
  id = "subnet-0244919ea2960a101"
}

resource "aws_directory_service_directory" "simple-ad" {
  name        = "workspaces.directory.test"
  description = "AWS Workspaces"
  password    = "blabla" 
  size        = "Small"

  vpc_settings {
    vpc_id     = module.vpc.id
    subnet_ids = [data.aws_subnet.private-subnet1.id, data.aws_subnet.private-subnet2.id]
  }

}

```
Verify the directory exists using the AWS console. Once created, proceed to create the AWS workspace with Terraform by using this code:

```
data "aws_workspaces_bundle" "windows10" {
  bundle_id = "windows10bundleid"
}

resource "aws_workspaces_workspace" "test-workspace" {
  provider     = aws.eu-west-1
  directory_id = "directoryidexactlyasitmatches"
  bundle_id    = data.aws_workspaces_bundle.windows10.id
  user_name    = "test"

  root_volume_encryption_enabled = true
  user_volume_encryption_enabled = true
  volume_encryption_key          = "alias/aws/workspaces"

  workspace_properties {
    compute_type_name                         = "VALUE"
    user_volume_size_gib                      = 10
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 60
  }

  tags = {
    Department = "my-dept"
  }
}

```
Plan is fine with no errors, however seeing error above when applying. 

### Important Factoids

Upon seeing this error, I explicitly set the region however Im unsure if this is even a valid field when creating a workspace with Terraform. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_workspace

The status of the directory is `available`. I should also mention when running `aws ds describe-directories --region=eu-west-1` it shows the expected directory.

**Comment by justinretzolk** [comment]
Hey @i0na-k 👋 Thank you for taking the time to raise this! While I'm not particularly familiar with this area of AWS, I took a look around and found [this document](https://docs.aws.amazon.com/workspaces/latest/adminguide/register-deregister-directory.html), which seems to indicate that the directory needs to be registered with Workspaces in order to be used. Based on that, I found the [`aws_workspaces_directory` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_directory), which appears to be the missing link here.

There may also be some work to do in terms of being cross-region, but I'm not familiar enough with this service to know for certain. Generally speaking, most resources do not have a `region` argument, and instead rely on provider aliasing to cope with separate regions, like you've done in your example configuration.

If you take a look at this info and still feel this is a bug, I'd be happy to leave this open so that we can take a look when possible.

**Comment by brittandeyoung** [comment]
One thing I would add to this is that the `aws_directory_service_directory` needs to live in the same region as the `aws_workspaces_directory ` and `aws_workspaces_workspace` resource. In your provided configuration, the `aws_directory_service_directory` is in a separate region. This is because your default provider is using `us-east-1` and all resources except your `aws_workspaces_workspace` are using this default provider config.

**Comment by i0na-k** [comment]
This has now been resolved, thank you.
