### ISSUE TITLE
[Enhancement]: lifecycle - ignore_changes with condition

### ISSUE THREAD

**Issue by eladlevi-dy** [hashicorp/terraform-provider-aws#31788]
### Description

We would like to see an option to use `lifecycle` `ignore_changes` with condition.
At the moment there is no option to use anything beside static argument on the `ignore_changes` field.
This change is much needed to specify when to use the `lifecycle` `ignore_changes`.

### Affected Resource(s) and/or Data Source(s)

None, just a new option to use with resources lifecycles. 

### Potential Terraform Configuration

```terraform
# Conditionally ignore changes to the web_acl_id based on the variable
  lifecycle {
    ignore_changes = var.ignore_web_acl_id_changes ? [web_acl_id] : []
  }

variable "ignore_web_acl_id_changes" {
  description = "Flag to determine if changes to web_acl_id should be ignored."
  type        = bool
  default     = false
}
```

### Would you like to implement a fix?

None

**Comment by ascopes** [comment]
Isn't this a Terraform related issue rather than an AWS provider issue, since the details of this is documented at https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes as core Terraform behaviour.

**Comment by justinretzolk** [comment]
Hey @eladlevi-dy 👋 Thank you for taking the time to raise this! As mentioned above, this would be better suited as a report in the Terraform Core repository. That said, this is not currently possible due to the way that the `lifecycle` block is interpreted by Terraform. This is called out in the [`lifecycle` documentation](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#literal-values-only) here: 

> The `lifecycle` settings all affect how Terraform constructs and traverses the dependency graph. As a result, only literal values can be used because the processing happens too early for arbitrary expression evaluation.

With that in mind, I'll close this issue out.
