### ISSUE TITLE
Changing aws_ssm_parameter.overwrite trigger a resource update

### ISSUE THREAD

**Issue by kid** [hashicorp/terraform-provider-aws#3181]
### Terraform Version
Terraform v0.10.6

### Affected Resource(s)
- aws_ssm_parameter

### Expected Behavior
Changing the `overwrite` parameter from `true` to `false` or vice versa should not trigger an update

### Actual Behavior
Changing `overwrite` from `true` to `false` trigger an update which then fails because the value can not be updated with `overwrite` set to `false`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a `aws_ssm_parameter` with `overwrite` set to `true`
2. Run `terraform apply`
3. change `overwrite` set to `false`
4. Run `terraform apply` again

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1481
- GH-1556

**Comment by ernoaapa** [comment]
Temporary workaround:
```
  lifecycle {
    ignore_changes  = ["overwrite"]
  }
```

**Comment by bflad** [comment]
Is this still an issue on v1.11.0 of the AWS provider? Thanks!

**Comment by bflad** [comment]
It looks like this functionality made it in via #1520, which was previously released in [version 1.11.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by jleclanche** [comment]
@bflad This is a bug report on the added functionality, it's more recent than the PR.

**Comment by bflad** [comment]
The PR in question was merged in March and this issue is from January. I'll reopen it though.

**Comment by avoidik** [comment]
Currently we're affected by the overwrite edge-case issue. We had initially created SSM value with Terraform, then we have been rewriting the same SSM key with another automation script. In this case subsequent Terraform provisioning leads to the error below

```
* aws_ssm_parameter.secret: error creating SSM parameter: ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
```

Lifecycle rule hasn't helped us much

```
  lifecycle {
    ignore_changes = ["value", "overwrite"]
  }
```

**Comment by rmclaughlin-nelnet** [comment]
Is there an update on this? I am running into the same issue. I am trying to move control of SSM parameters to Terriform, but have them updated through another process. This does not seem possible currently because Terraform always complains `ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.`

**Comment by beanaroo** [comment]
We'd like to switch to `overwrite = false` to prevent potential conflicting parameters but this is getting in the way.

**Comment by avoidik** [comment]
This issue hasn't been resolved
