### ISSUE TITLE
[Bug]: aws_transfer_server Resource Not Passing Tags to VPC Endpoint.

### ISSUE THREAD

**Issue by abaileyDC** [hashicorp/terraform-provider-aws#31855]
### Terraform Core Version

1.3.3

### AWS Provider Version

5.1.0

### Affected Resource(s)

aws_transfer_server

### Expected Behavior

Tags should apply to VPC Endpoints created as part of the resource call.

### Actual Behavior

The transfer server created has the appropriate tags, yet the VPC endpoints have none.

### Relevant Error/Panic Output Snippet

```shell
There is no actual error.
```

### Terraform Configuration Files

```
resource "aws_transfer_server" "transfer_server" {
  endpoint_type = "VPC"

  identity_provider_type = "API_GATEWAY"
  url                    = "https://${var.custom_identity_provider_id}.execute-api.${var.aws_region}.amazonaws.com/${var.aws_api_gateway_stage_name}"

  protocols       = var.transfer_server_protocols
  invocation_role = var.invocation_role
  logging_role    = var.logging_role

  endpoint_details {
    subnet_ids             = var.transfer_server_subnet_ids
    vpc_id                 = var.transfer_server_vpc_id
    #address_allocation_ids = ["${aws_eip.transfer_server_eip.id}"]
    address_allocation_ids = [for eip in aws_eip.transfer_server_eip : eip.id]
  }

  workflow_details {
    on_upload {
      execution_role = var.execution_role
      workflow_id = var.workflow_id
    }
  }

  tags = {
    "transfer:customHostname" = var.transfer_server_name
  }
}

resource "aws_eip" "transfer_server_eip" {
  count = length(var.transfer_server_subnet_ids)
  domain = "vpc"
}
```

### Steps to Reproduce

Building a transfer server with an  `endpoint_type = "VPC"` regularly produces the issue.

### Debug Output

n/a

### Panic Output

n/a

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @abaileyDC 👋 Thank you for taking the time to raise this! Because the VPC endpoints are not directly managed by Terraform, this is the behavior I would expect at the moment. I'm trying to connect some of the issues related to this (hence the related comment below), as I think in the future we may be able to help enable this via either changes to the provider, or by documenting ways to accomplish this natively in Terraform. 

In the meantime, one approach would be to define an [`aws_vpc_endpoint` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint) in the configuration after creating the `aws_transfer_server` and importing it into the state. The `aws_vpc_endpoint` resource could then be used to apply the appropriate tag(s).

Related #31775

**Comment by justinretzolk** [comment]
With the above in mind, closing this issue.
