### ISSUE TITLE
[Docs]: aws_db_instance does not document the new `identifier` parameter

### ISSUE THREAD

**Issue by jwoytek** [hashicorp/terraform-provider-aws#31854]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#attributes-reference

### Description

PR #31232 changed the ID configuration for RDS resources. There is a new (and currently undocumented) parameter named `identifier` which returns the instance identifier. This was formerly returned by `id`, which now returns the same thing as `db_resource_identifier`. 

### References

PR #31232

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jwoytek 👋 Thank you for taking the time to raise this! I took a look, and it looks like the `identifier` argument [is indeed documented](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#identifier); it's in the arguments section rather than attributes, since it can optionally be set in the Terraform configuration. This used to be the same value as what was set for `id`, but that's what changed with version 5.0.0 -- the `id` attribute is now the same value as the `resource_id` attribute.

**Comment by jwoytek** [comment]
I'm sorry I missed that--I was looking in the attributes section while looking at a bug I found in terraform-aws-modules/terraform-aws-rds. Thank you for looking into this!

**Comment by justinretzolk** [comment]
No worries, it happens @jwoytek! 🙂 I'll go ahead and close this one out. Have a great weekend!
