### ISSUE TITLE
[Docs]: terraform import doesn't work for aws_ecs_task_set

### ISSUE THREAD

**Issue by zshen-figma** [hashicorp/terraform-provider-aws#31882]
### Documentation Link

https://registry.terraform.io/providers/-/aws/latest/docs/resources/ecs_task_set#import

### Description

I tried to do an import on aws_ecs_task_set resource base on the example given in the doc, but it threw InvalidParameterException, and also the ID being displayed contain the whole comma separate string, which implies that terraform doesn't seem to recognize a comma-separate list of parameters

```
$ terraform import module.<SERVICE>.module.service.aws_ecs_task_set.template ecs-svc/3794523159210700627,arn:aws:ecs:us-west-2:<ACCOUNT_ID>:service/<SERVICE>,arn:aws:ecs:us-west-2:<ACCOUNT_ID>:cluster/staging
module.<SERVICE>.module.service.aws_ecs_task_set.template: Importing from ID "ecs-svc/3794523159210700627,arn:aws:ecs:us-west-2:<ACCOUNT_ID>:service/<SERVICE>,arn:aws:ecs:us-west-2:<ACCOUNT_ID>:cluster/staging"...
module.<SERVICE>.module.service.aws_ecs_task_set.template: Import prepared!
  Prepared aws_ecs_task_set for import
module.<SERVICE>.module.service.aws_ecs_task_set.template: Refreshing state... [id=ecs-svc/3794523159210700627,arn:aws:ecs:us-west-2:<ACCOUNT_ID>:service/<SERVICE>,arn:aws:ecs:us-west-2:<ACCOUNT_ID>:cluster/staging]
╷
│ Error: InvalidParameterException: Cluster can not be blank.
│
│
╵
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @zshen-figma 👋 Thank you for taking the time to raise this! I took a quick look, and the [`id` for this resource](https://github.com/hashicorp/terraform-provider-aws/blob/ba85a49cff1591afb34b58cc14c13fc0d365eb2c/internal/service/ecs/task_set.go#L332) does indeed appear to be the full comma separated string (which is parsed by a [parser function](https://github.com/hashicorp/terraform-provider-aws/blob/ba85a49cff1591afb34b58cc14c13fc0d365eb2c/internal/service/ecs/task_set.go#L514-L522)), so I don't suspect that this is an issue of Terraform not recognizing the comma-separated list of parameters.

Are you able to supply the Terraform configuration and debug logs (redacted as needed) as well, so that we have the information necessary to take a look at this?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
