### ISSUE TITLE
aws_lambda_event_source_mapping, attribute  `queues` is misleading         

### ISSUE THREAD

**Issue by Tuzosdaniel12** [hashicorp/terraform-provider-aws#31919]
### Description

Small observation after spending a day trying to understand validation failure when creating `aws_lambda_event_source_mapping`. After going back and carefully reading the docs I found that issue came from `queues` attribute.

At first glance one can assumed that `queues           = ["example"]` will accept an array of strings with different queue

In result I created my resource in the following format.

```
resource "aws_lambda_event_source_mapping" "mq_triggers" {
  batch_size       = 10
  event_source_arn = var.broker_arn
  enabled          = true
  function_name    = aws_lambda_function.message_handler.arn
  queues           = ["START", "STOP", "STATUS"]

  source_access_configuration {
    type = "BASIC_AUTH"
    uri  = aws_secretsmanager_secret.broker_credentials.arn
  }
}
```
Which resulted in the following error.
```
Error: error creating Lambda Event Source Mapping (arn:aws:mq:....): ValidationException: 
	status code: 400
```

After banging my head I reread the docs and I soon understood that I could only send in a single string in the array.

```
queues - (Optional) The name of the Amazon MQ broker destination queue to consume. Only available for MQ sources. A single queue name must be specified
```
So I changed my code to do each queue in a loop.

```
resource "aws_lambda_event_source_mapping" "mq_triggers" {
  for_each = toset(local.queues)
  batch_size       = 10
  event_source_arn = var.broker_arn
  enabled          = true
  function_name    = aws_lambda_function.message_handler.arn
  queues           = [each.key]

  source_access_configuration {
    type = "BASIC_AUTH"
    uri  = aws_secretsmanager_secret_version.broker_credentials_secret.arn
  }
}
```
Is this the intended behavior? If yes, should the attribute name change to `queues =  "example"`since is only accepts single value?

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Tuzosdaniel12 👋 Thank you for taking the time to raise this! The `aws_lambda_event_source_mapping` resource uses the [`lambda.CreateEventSourceMapping` function](https://docs.aws.amazon.com/sdk-for-go/api/service/lambda/#CreateEventSourceMappingInput) from the AWS Go SDK. I've linked to `lambda.CreateEventSourceMappingInput`, which is the Go type used as an input to said function, since it's a bit more relevant in this case. The input for this function has a `Queues` field, which correlates to the `queues` argument for the resource in Terraform. To save you a click, the field has the following definition:

> // (MQ) The name of the Amazon MQ broker destination queue to consume.
    Queues []*string `min:"1" type:"list"`

In this case, the AWS Provider has followed the [design principle](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles#resource-and-attribute-schema-should-closely-match-the-underlying-api) of closely matching the underlying API, which is why the argument is a list type with a maximum size of one item, despite my  agreeing with you that it's a bit of an odd case (though not entirely unique in the context of the AWS API), and definitely see how it could cause confusion.

With that in mind, I would say that this is indeed expected behavior, and that the argument should be left as is.

**Comment by Tuzosdaniel12** [comment]
Thank you for the support!
