### ISSUE TITLE
r/aws_lambda_function: Remove `replace_security_groups_on_destroy` attribute

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#31911]
### Description

The `replace_security_groups_on_destroy` and `replacement_security_group_ids` attributes were deprecated in #31904. These should be removed, along with acceptance tests referencing these attributes.

### References

Relates #31904
Relates #31520

### Would you like to implement a fix?

None

**Comment by theipster** [comment]
Rather than **removing** these two attributes, `replace_security_groups_on_destroy` and `replacement_security_group_ids`, can we instead consider **re-implementing** them using the alternative approach described in https://github.com/hashicorp/terraform-provider-aws/issues/31520#issuecomment-1564294438?

In other words, rather than the now deprecated (read: now non-functional) approach whereby the provider looks up all related ENIs and changes _each individual ENI's_ security groups (which AWS no longer allows, for understandable reasons), instead the provider should simply modify the _Lambda function_'s nominated security groups (and let Lambda deal with re-creating the new ENIs, which it can actually do very quickly in practice).

The overall concept (i.e. ending up with ENIs in a different security group, one way or another) and the overall objective (i.e. speeding up the Lambda function destroy) is still the same as before. So, the naming of these two attributes, `replace_security_groups_on_destroy` and `replacement_security_group_ids`, is still fairly accurate and doesn't need to change - which is convenient for backwards compatibility too.

Even today (at the time of writing this), we've confirmed that this approach works, and in fact makes a huge difference for us. If anyone is curious, we are adopting this approach in all our `*.tftest.hcl` test suites that involve VPC-enabled Lambda functions. We've effectively implemented it by adding an additional pre-teardown `run { ... }` block, whose sole purpose is to modify the `aws_lambda_function.vpc_config.security_group_ids` attribute, just before allowing `terraform test` to undo its stack as usual. Adopting this approach consistently reduces our ~30m destroy to ~3m. Without this, our `terraform test` command would sporadically cause our CI pipeline jobs to time-out, leaving behind all the test suite resources for us to manually clean up (because, remember, resources created via `terraform test` have no persisted state and therefore there's no way to simply run `terraform destroy` on them! 😉), which is obviously a real pain.

If the `aws_lambda_function` resource could (continue to!) just handle all of this natively and transparently, this would simplify things on so many levels!

**Comment by jar-b** [comment]
Hey @theipster 👋 - Thanks for the detailed request, and especially for the context on how you're implementing this within Terraform test suites!

For some reason my previous understanding was that modifying the lambda security groups prior to deletion did not yield significant reductions in destroy times of the associated security groups. However, given you (and the commenter linked above) have evidence of significant time reductions, it seems my test configuration was too limited (and therefore missed the observed advantages), or AWS has made some internal changes which now make this more viable. Either way, this feels like a feature worth revisiting given the potential benefits. 

I'm going to assign myself to this to investigate.

**Comment by jar-b** [comment]
First pass at this has yielded some definitive improvements on run time of acceptance tests (previously on the order of `1500s`). 

```console
% make testacc PKG=lambda TESTS="TestAccLambdaFunction_VPC_replaceSGWithDefault|TestAccLambdaFunction_VPC_replaceSGWithCustom"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaFunction_VPC_replaceSGWithDefault|TestAccLambdaFunction_VPC_replaceSGWithCustom'  -timeout 360m

--- PASS: TestAccLambdaFunction_VPC_replaceSGWithDefault (424.23s)
--- PASS: TestAccLambdaFunction_VPC_replaceSGWithCustom (615.75s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lambda     620.855s
```

I also discovered my mistake with the previous attempt at this alternative - I missed waiting for the VPC configuration update to take effect prior to calling the delete operation. This effectively left the security groups intended to be "removed" still assigned to the lambda function during deletion, and therefore resulted in the same long-running destroy operations observed when this argument is not configured at all.

Thanks again for bringing this proposal up, @theipster ! I'm planning to get the full test suite run and a PR up shortly.

**Comment by theipster** [comment]
Thanks @jar-b for looking at this so promptly - much appreciated!

Yes, it seems to hinge on the timing of when the Lambda function gets deleted... or _potentially_ (just a thought) more specifically when the Lambda function's IAM execution role gets deleted, given that execution roles for VPC-enabled Lambdas require those additional `ec2:*NetworkInterface*` permissions.

Let me know if there's anything I can help with; otherwise, I look forward to the improvement! 👍
