### ISSUE TITLE
[Bug]: aws_acm_certificate is eventually consistent, causes direct dependencies to fail

### ISSUE THREAD

**Issue by dmurvihill** [hashicorp/terraform-provider-aws#32025]
### Terraform Core Version

1.5.0

### AWS Provider Version

5.3.0

### Affected Resource(s)

`aws_api_gateway_domain_name` (tested today)

not tested, but was reported as not working in 2018, in #4687:
`aws_lb_listener`
`aws_lb_listener_certificate`
`aws_elb` (through the listener property)
`aws_elastic_beanstalk_environment` (AWS supports ACM certs here)

### Expected Behavior

Can successfully provision `aws_api_gateway_domain_name` and `aws_acm_certificate` at the same time

### Actual Behavior

Fails to create domain name, but subsequent attempt succeeds

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating API Gateway v2 Domain Name (tmp.directdemocracysolutions.com): BadRequestException: Certificate arn:aws:acm:us-west-1:330392339445:cer
tificate/ff4d7a8b-d849-4381-bb4a-bef1a17fc31f in account 330392339445 not yet issued (Service: AWSCertificateManager; Status Code: 400; Error Code: Requ
estInProgressException; Request ID: 87dbe12b-b2c6-404b-b8b7-d0ebc4aaef4f; Proxy: null)
```

### Terraform Configuration Files

https://github.com/direct-democracy-solutions/terraform-aws-http-proxy/releases/tag/1.0.0-rc2

### Steps to Reproduce

Download the code (make sure to get 1.0.0-rc2, as I worked around the issue in later commits), then:

```bash
cd terraform-aws-http-proxy/examples/proxy_to_example_dot_com
touch my.tfvars
```

Add the two required parameters to `my.tfvars`:
```
domain_name="domain-name-for-the-test-api-gateway"
route53_hosted_zone_id = "your-hosted-zone-id"
```

Finally:
```bash
terraform apply -var-file="my.tfvars"
```

### Debug Output

[terraform.log](https://github.com/hashicorp/terraform-provider-aws/files/11764028/terraform.log)

### Important Factoids

I was able to work around the issue using a custom provisioner following a [suggestion](https://github.com/hashicorp/terraform/issues/2499#issuecomment-125292740) in [Terraform #2499](https://github.com/hashicorp/terraform/issues/2499):

```
resource "aws_acm_certificate" "proxy" {
  domain_name       = local.domain_name
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }

  provisioner "local-exec" {
    command = "sleep 120"
  }
}
```

### References

https://github.com/hashicorp/terraform/issues/2499
#4687

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dmurvihill 👋 Thank you for taking the time to raise this! I see that you're already using the [`aws_acm_certificate_validation` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation) in other places in the configuration. This is the method that I would recommend using to validate that the certificate has been issued and can be used.

To do so, you'd switch your `aws_apigatewayv2_domain_name.proxy.domain_name_configuration.certificate_arn` to use `aws_acm_certificate_validation.proxy.certificate_arn` rather than `aws_acm_certificate.proxy.arn`. This will mean that the API Gateway will be dependent on the certificate being available before creation, and should get you past these errors.

**Comment by dmurvihill** [comment]
Thanks! That workaround solved our issue perfectly.
