### ISSUE TITLE
Deploying service with task definition  I'm getting below error in service Events

### ISSUE THREAD

**Issue by TGsapla** [hashicorp/terraform-provider-aws#32068]
**Hello Team**
Please i need help with below issue.

### Description
Unable to place a task because no container instance met all of its requirements.

### References
The closest matching container-instance exxxxxxxxxxx5xxxxxxxxxxxxxxf is missing an attribute required by your task. For more information, see the Troubleshooting section

### Would you like to implement a fix?
Please help

**Comment by justinretzolk** [comment]
Hey @TGsapla 👋  Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
