### ISSUE TITLE
[Enhancement]: Support custom response codes in aws_fms_policy default action 

### ISSUE THREAD

**Issue by emmett008** [hashicorp/terraform-provider-aws#32109]
### Description

When creating a firewall manager policy using the Terraform AWS provider, specifying a custom response code does not seem to be supported.

The syntax has been added as per the documentation for the security service policy data at the below link 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fms_policy#security_service_policy_data-configuration-block

This part of the documentation links out directly to the AWS site 
https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_SecurityServicePolicyData.html#fms-Type-SecurityServicePolicyData-Type

in all attempts the custom response code was not set in AWS 

### Affected Resource(s) and/or Data Source(s)

aws_fms_policy

### Potential Terraform Configuration

```terraform
defaultAction = {
      type               = "block"
      customResponseCode = "401"
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @emmett008 👋 Thank you for taking the time to raise this! As the `managed_service_data` argument just takes JSON data, I don't believe this will take any modification from the AWS provider, and is rather a matter of configuring the data in the block in the way that the AWS API expects. In this case, based on the link you provided and the [FMS developer guide](https://docs.aws.amazon.com/waf/latest/developerguide/customizing-the-response-for-blocked-requests.html), it appears that this may not be working for you currently due to a configuration issue. My read on this would be that the following change to your configuration may yield what you're looking for (note that there are likely other bits of the configuration that you may need to add in addition to this; I'm mainly looking at the response code, since that's what you initially asked about).

```terraform
defaultAction = {
  type = "block"
}

customResponse = {
  responseCode = 401
}
```

**Comment by emmett008** [comment]
Hi @justinretzolk, thanks for the quick response. I had added the code as per your snippet without success unfortunately.

After retesting and looking at the structure saved in state and also the AWS UI, the correct configuration became apparent.
The structure of the custom repsonse object in the state file is as per below 

```
    "customResponse":
    {
        "enableCustomResponse": null,
        "customResponseBodyKey": null,
        "responseCode": null,
        "responseHeaders": null,
        "customResponseBodies":null
}
```

Just setting the `responseCode` returned an error that `customResponseBodies` could not be null 
Setting this to `{} `did not raise an error, however the changes did not take effect in deployed resources.
`enableCustomerResponse` must be set to true in order to have the configuration correctly deployed, unfortunately this is not very clear from documentation supplied by AWS but may be helpful for users of the provider 

For information purposes - we are using 5.4.0 of the provider

**Comment by emmett008** [comment]
Closing this as initial ask is now invalid
