### ISSUE TITLE
How to copy a file from one folder in a s3 bucket to another folder in s3 bucket ,cross - region , using AWS GLUE TERRAFORM

### ISSUE THREAD

**Issue by Sowmya-aws** [hashicorp/terraform-provider-aws#32163]
### Description

Hi Team,

I am new to this aws glue, terraform. I wanted to know how to copy a file in AWS-GLUE, using Terraform, How to copy file from one folder in s3 bucket to another folder in s3 bucket ,cross - region , based on either file name or time based..

Guidelines

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Sowmya-aws 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
