### ISSUE TITLE
how to concatenate eks security_group_ids and cluster_security_group_id in terraform to assign to EC2 instance in terraform

### ISSUE THREAD

**Issue by kunal-parsewar** [hashicorp/terraform-provider-aws#32168]
### Description

Hi ,

I have an existing EKS cluster which is created using terraform. So this EKS is having two security groups one is Cluster Security Group and another is Additional security groups . 

Now when I am trying to create an EC2 instance using terraform and trying to assign the above security groups to the EC2 , I am resulting in different errors like 

"Error: Incorrect attribute value type"
or 
" .security_group_ids is set of string with 1 element"
or 
"Invalid value for "seqs" parameter: all arguments must be lists or tuples;"  --- > when I try to concat above two .

let me know if you have faced the same issue  and resolved the issue.

Do let me know how you have resolved the same.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @kunal-parsewar 👋  Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
