### ISSUE TITLE
[Enhancement]: Additional attributes for sso users

### ISSUE THREAD

**Issue by novekm** [hashicorp/terraform-provider-aws#32211]
### Description

Currently there are some user attributes that are available for sso users that are not currently supported by the `aws_identitystore_user` resource. The ones I noticed are missing:

- **employee_number** 
- **cost_center**
- **organization**
- **division** 
- **department** 
- **manager**

### Affected Resource(s) and/or Data Source(s)

`aws_identitystore_user`

### Potential Terraform Configuration

```terraform
resource "aws_identitystore_user" "sso_user" {
  identity_store_id = "1234abcd-efg"

  employee_number = ""
  cost_center = ""
  organization = ""
  division = ""
  department = ""
  manager = ""

}
```

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @novekm 👋 Thank you for taking the time to raise this! The `aws_identitystore_user` resource uses the [`identitystore.CreateUser` function](https://github.com/hashicorp/terraform-provider-aws/blob/a745b5ccb780746e9ad15e21e8b3f3cd439c7ce3/internal/service/identitystore/user.go#L306) from the AWS Go SDK. This function takes a type of [`identitystore.CreateUserInput`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/identitystore#CreateUserInput), which does not appear to have the necessary fields in order to support adding these additional attributes.

Since this is a limitation of the upstream API, we'll close this request for now. If the underlying API changes in the future, we'd be happy to take another look.
