### ISSUE TITLE
[Enhancement]: Regularly monitor peak and resident memory usage of the provider

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#32289]
### Description

Recent issue #31722 has demonstrated that the increasing size of the provider, combined with the recent addition of resources with a deep and complex schema has significantly increased the peak memory requirements of using the provider. This has put pressure on memory requirements in practitioner infrastructure deploy pipelines and has resulted in OOM errors when making changes to their infrastructure.

While we work on optimizing memory requirements, we should also begin to actively monitor the memory footprint of the provider as it evolves. This is likely to consist of a scheduled GitHub action to obtain a memory profile of the running provider via an acceptance test, and visualizing the results via [pprof](https://github.com/google/pprof).

We should also define thresholds for what is considered an acceptable, vs an anomalous increase. This should allow us to more proactively respond to provider changes which result in outsized memory requirements.

### Affected Resource(s) and/or Data Source(s)

All

### References

- https://github.com/google/pprof
- https://github.com/hashicorp/terraform-provider-aws/issues/31722
- https://github.com/hashicorp/terraform-provider-aws/issues/26742
- See memory use over time: https://github.com/YakDriver/awsprovmemprof
- Regex cache: https://github.com/YakDriver/regexache
- #33553

### Would you like to implement a fix?

None

**Comment by gavinelder** [comment]
@breathingdust can https://github.com/hashicorp/terraform-provider-aws/issues/26742 please be added as a reference , this is the provider in which we have observed the largest increase in memory consumption

**Comment by YakDriver** [comment]
We are regularly monitoring memory use now and have accomplished reducing memory to an extent. For future travelers, here is a sum up.

### What we've done

For this issue, we have:
- Implemented regular expression caching (de-duplicating), which reduces memory allocation by ~15-20%.
- Created a daily job in TeamCity that reports changes in memory allocation, use, and CPU time from current to the most recent build. Below is an example of the output. Note: The bottom-line numbers do not themselves relate perfectly to running Terraform in the real world because they involve running in the test environment and running specific example tests, the average of one VPC and one SSM. However, they are useful in comparing iterations of the AWS provider to each other.

```
Performance changes from latest version (v5.17.0) to main
Allocated memory: 1.7% (5744.1MB to 5841.2MB) (Worse)  
In-use memory: 9.4% (24.0MB to 26.2MB) (Worse) (wide-fluctuations normal)
CPU time: 4.8% (29.0s to 30.4s) (Worse)
```

### What remains to be done

See issue #35000.
