### ISSUE TITLE
[Bug]: Resource aws_quicksight_data_set incorrect input_columns definition

### ISSUE THREAD

**Issue by ricomasgu** [hashicorp/terraform-provider-aws#32438]
### Terraform Core Version

1.5.2

### AWS Provider Version

5.7.0

### Affected Resource(s)

aws_quicksight_data_set input_columns

### Expected Behavior

aws_quicksight_data_set input_columns should be an array/list, not an object. I understand the misunderstanding because of the AWS documentation.
But let me show you what I mean. If you go to [AWSQuicksightDatasetRelationalTableProperty](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-dataset-relationaltable.html) you can see the InputColumns as an array of [InputColumn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-dataset-inputcolumn.html) objects.
So, to me is clear I should be able to pass an array/list instead of a single object. Thanks!
Here the actual terraform definition for the resource: [ResourceAWSQuicksightDataSet](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_set)

### Actual Behavior

If I pass an array, I get an error (logic, because I am not following the terraform schema)
`An argument named "input_columns" is not expected here. Did you mean to define a block of type "input_columns"?`

But if I pass a block, I can only specify one element.

### Terraform Configuration Files

No need to config files

### Steps to Reproduce

Try to create a data set that needs input_columns with more than one column.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ricomasgu 👋 Thank you for taking the time to raise this! I took a quick look at the resource schema, and noted that `input_columns` [is indeed](https://github.com/hashicorp/terraform-provider-aws/blob/5ce64c172eff331b0de12e9e86b8773b75eb30a1/internal/service/quicksight/data_set.go#L731-L750) a list of objects. Based on the error message, it appears that you may have passed it as an [argument rather than a block](https://developer.hashicorp.com/terraform/language/syntax/configuration). Since `input_columns` itself has nested arguments, it is represented as a block. Since it is a list type, multiple `input_columns` blocks may be specified. This would look something like:

```terraform
resource "aws_quicksight_data_set" "example" {
  # unrelated configuration arguments have been omitted for brevity
  physical_table_map {
    relational_table {
      input_columns {
        name = "example0"
        type = "sometype"
      }
      input_columns {
        name = "example1"
        type = "sometype"
      }
    }
  }
}
```

**Comment by ricomasgu** [comment]
Perfect! This makes the configuration a bit difficult because I can not pass directly a list, but fair enough. Thanks!
Would be nice to add an example easy to follow in the docs to avoid further misunderstandings.
