### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by matschundbrei** [hashicorp/terraform-provider-aws#32475]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance

### Description

The documentation refers to an exported attribute `name` but when I try and use it, I get:

```shell
This object has no argument, nested block, or exported attribute named "name".
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @matschundbrei 👋 Thank you very much for taking the time to raise this! I've opened a pull request to remove the reference to the `name` attribute, since it's not in the resource schema. In the meantime, I believe that the `db_name` attribute will contain the information that you were looking for.
