### ISSUE TITLE
[Bug]: Service managed stacksets with delegated admin not working

### ISSUE THREAD

**Issue by popsicleslayer** [hashicorp/terraform-provider-aws#32536]
### Terraform Core Version

1.4.6

### AWS Provider Version

5.6.2

### Affected Resource(s)

aws_cloudformation_stack_set, aws_cloudformation_stack_set_instance

### Expected Behavior

The StackSets should be deployed in the account that is the delegated admin for CloudFormation. Deploying the same StackSet (without the call_as  = "DELEGATED_ADMIN") in the root account of the organization deploys these resources without any problem.

### Actual Behavior

Terraform throws an error: You must be the management account or delegated admin account of an organization before operating a SERVICE_MANAGED stack set

### Terraform Configuration Files

```terraform
resource "aws_cloudformation_stack_set_instance" "xxx" {
  deployment_targets {
    organizational_unit_ids = [local.organization.ou.xxx_id]
  }
  region         = data.aws_region.current.name
  stack_set_name = aws_cloudformation_stack_set.xxx.name
}

resource "aws_cloudformation_stack_set" "xxx" {
  name             = "xxx"
  description      = "xxx"
  permission_model = "SERVICE_MANAGED"
  template_body    = file("./files/CloudFormation.yaml")
  call_as          = "DELEGATED_ADMIN"
  capabilities = [
    "CAPABILITY_NAMED_IAM",
    "CAPABILITY_IAM"
  ]
  auto_deployment {
    enabled = true
  }
  parameters = {
    Route53Id   = local.zone_id
    Route53Name = local.zone_name
    DynamoDBName        = local.dynamodb_table_name
    RoleArn           = local.ole_arn
  }
  # Related issue: https://github.com/hashicorp/terraform-provider-aws/issues/23464
  lifecycle {
    ignore_changes = [
      administration_role_arn
    ]
  }
}
```

### Steps to Reproduce

Deploy the CloudFormation StackSet resources to an account that is a delegated admin for CloudFormation.

### Would you like to implement a fix?

None

**Comment by popsicleslayer** [comment]
Hi @justinretzolk! Unfortunately, I can't provide any logs. If this is any help the Terraform code is deployed using GitHub Actions, there's no jump host in this deployment and we use [this](https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/) approach to connect to AWS. I also found a similar issue with a comment that has what looks like exactly the same problem [here](https://github.com/hashicorp/terraform-provider-aws/issues/22867).

**Comment by ewbankkit** [comment]
@popsicleslayer Thanks for raising this issue 👏 
Have you tried adding `call_as = "DELEGATED_ADMIN"` to the `aws_cloudformation_stack_set_instance` resource configuration?

**Comment by MichaelAicher** [comment]
Thats what solved it for me! Thanks a ton!

> @popsicleslayer Thanks for raising this issue 👏 Have you tried adding `call_as = "DELEGATED_ADMIN"` to the `aws_cloudformation_stack_set_instance` resource configuration?

**Comment by gdavison** [comment]
Hi @popsicleslayer. Are you still seeing this error using an updated version of the AWS Provider? We're currently on version 5.46.0. If so, can you include the whole error message, please? It looks like the error is coming from the `aws_cloudformation_stack_set`, so the `aws_cloudformation_stack_set_instance` is not tried.

I've tried reproducing the error locally, and I'm not seeing it, unless I don't have the account registered as a delegated administrator.

As an example, my Organization root account is 123456789012 and my delegated administrator is 987654321012. When I run the configuration

```terraform
resource "aws_cloudformation_stack_set" "example" {
  name             = "example"
  permission_model = "SERVICE_MANAGED"
  call_as          = "DELEGATED_ADMIN"

  auto_deployment {
    enabled                          = true
    retain_stacks_on_account_removal = false
  }

  template_body = <<TEMPLATE
...
TEMPLATE

  lifecycle {
    ignore_changes = [administration_role_arn]
  }
}
```

 in account 987654321012, it completes successfully.

However, if I remove 987654321012 as delegated administrator and run Terraform in 987654321012, I get the error

> Error: creating CloudFormation StackSet (example): ValidationError: Account used is not a delegated administrator

Are you using Terraform to configure the account as a delegated administrator? If so, try adding `depends_on = [aws_organizations_delegated_administrator.<resource name>]` to your `aws_cloudformation_stack_set`. Otherwise, the account may not be registered by the time the `aws_cloudformation_stack_set` is tried.
