### ISSUE TITLE
 aws_dms_s3_endpoint Resource Adds add_trailing_padding_character = false

### ISSUE THREAD

**Issue by grifonas** [hashicorp/terraform-provider-aws#32698]
### Description

Hi,
It appears that the aws_dms_s3_endpoint resource adds `add_trailing_padding_character=false` to the JSON settings of the endpoint. However this option is not supported in replication instances below the version 3.4.7. This results in DMS errors.
It appears that it's not enough to set `add_trailing_padding_character` to `false`. The option `add_trailing_padding_character` should not be present at all. 
Is there a way to work around this?

### Would you like to implement a fix?

None

**Comment by sodle** [comment]
I believe this can be fixed by changing the `Get` call [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/dms/s3_endpoint.go#L579) to a `GetOk`. I'm verifying that assumption as we speak.

This will prevent Terraform from inserting a `false` value for this option when it is not specified for a resource. It will instead rely on [AWS's default behavior](https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html), which also defaults to `false`. Therefore, this should have no side effects apart from fixing the error.

I'll note that the DMS engine version 3.4.5 is already deprecated, and 3.4.6 will be deprecated in a couple of months. The underlying DMS issue is fixed in 3.4.7, at which point this bug will no longer be reproducible.
