### ISSUE TITLE
Terraform module EKS -> EC2 tags

### ISSUE THREAD

**Issue by medusaalb** [hashicorp/terraform-provider-aws#32731]
### Description

Is it possible to change the EC2 Name tag in"eks_managed_node_groups" inside module eks?
because it takes always the "group_name" 

```terraform
module eks {
....
 eks_managed_node_groups = {
    green = {
      min_size     = 1
      max_size     = 10
      desired_size = 1

      instance_types = ["t3.large"]
      capacity_type  = "SPOT"
     tags = {
       name = "${cluster_name}-worker-nodes"
     }
   } # end group green end
   tags = {
       name = "${cluster_name}-worker-nodes"
   }
 } #end eks_node_group
} #end eks module
```

i have a tag inside "eks_managed_node_groups" and takes de group name
i have the same tag at the end of eks_managed_node_groups and the same result

Thanks in advance

### Would you like to implement a fix?

None

**Comment by medusaalb** [comment]
Hi @justinretzolk,
i'm using in aws -> module eks version [19.15.4]
(https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest)

Thanks in advance

**Comment by justinretzolk** [comment]
Hey @medusaalb 👋 Thanks for getting back to me with that information! You'll want to file an issue in the following repository to get assistance with that module:

https://github.com/terraform-aws-modules/terraform-aws-eks

Given that this issue relates to that module and not the AWS Provider itself, we'll close this issue out. If you encounter additional issues with the AWS Provider, please open a new issue so that we can take a look at it and triage it appropriately.
