### ISSUE TITLE
[Enhancement]: S3 DSSE-KMS support

### ISSUE THREAD

**Issue by davinerd** [hashicorp/terraform-provider-aws#32951]
### Description

S3 buckets support dual-layer encryption (DSSE-KMS) from June 2023 but it's still unsupported by Terraform.

### Affected Resource(s) and/or Data Source(s)

aws_s3_bucket_server_side_encryption_configuration

### Potential Terraform Configuration

```terraform
resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
  bucket = aws_s3_bucket.mybucket.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.mykey.arn
      sse_algorithm     = "aws:dsse"
    }
  }
}
```

### References

https://aws.amazon.com/blogs/aws/new-amazon-s3-dual-layer-server-side-encryption-with-keys-stored-in-aws-key-management-service-dsse-kms/

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @davinerd 👋 Thank you for taking the time to raise this! It looks like the documentation needed updating, but this has been supported since AWS Provider version `5.4.0` due to updates to the AWS SDK that were automatically pulled in. I've opened a pull request to update the documentation as needed.
