### ISSUE TITLE
[Bug]: current Organization ID (0-xxxxxxxxxx) does not match (r-xxxx)

### ISSUE THREAD

**Issue by dannyibishev** [hashicorp/terraform-provider-aws#33083]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.13.0

### Affected Resource(s)

I bumped the AWS provider on my workspace from `5.12.0` to `5.13.0` and was greeted by an error for the `aws_organizations_organization` resource. 

The error 

<img width="829" alt="Screenshot 2023-08-18 at 11 34 24" src="https://github.com/hashicorp/terraform-provider-aws/assets/29864680/04f2d4df-8bab-4988-9543-edb0357c2c39">

I believe this to be a bug that was introduced possibly by commit https://github.com/hashicorp/terraform-provider-aws/pull/31796

resource affected
* aws_organizations_organization

## What
There should have been no change in the id within the state for the affected resource.

## Why
I have not made any changes myself other than bump the AWS provider.

### Actual Behavior

The error provided from earlier

### Terraform Configuration Files

```hcl
resource "aws_organizations_organization" "org" {
  aws_service_access_principals = ["account.amazonaws.com", "cloudtrail.amazonaws.com"]
  feature_set                   = "ALL"
}
```

### Steps to Reproduce

1. Provision a `aws_organizations_organization` resource on aws provider `5.12.0`.
2. Apply the resource.
3. Bump the aws provider to `5.13.0`.
4. Run a plan.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31796.

**Comment by ewbankkit** [comment]
@dannyibishev Thanks for raising this issue 👏.
Looking at the code, my guess is that the `aws_organizations_organization` resource was previously imported with the _r-xxxx_ root identifier and that became the resource's `id` in state. Since the import ID wasn't checked prior to https://github.com/hashicorp/terraform-provider-aws/pull/31796, this was a valid scenario.
I've marked this bug as a regression -- I'll move the `id`-checking code into the importer rather than resource Read.
