### ISSUE TITLE
[Enhancement]: improve error message "Unsupported argument"

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#33278]
### Description

![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/b35ff937-812d-4390-a96b-4cee43391847)

it is not clear here that I should replace `data` with `resource`:
```diff
-data "aws_route53_zone" "base_domain" {
+resource "aws_route53_zone" "base_domain" {
  name = "staging.example.com"

  delegation_set_id = aws_route53_delegation_set.ns_set.id
}
```

I expect something like `you can not use delegation_set_id with "data"`

**Comment by justinretzolk** [comment]
Hey @EugenKon 👋 Thank you for taking the time to raise this! This messaging comes is at the Terraform Core level, rather than an error from the provider itself. Terraform Core isn't aware of how individual resources within providers may relate to each other, so it's not able to make the determination that you may be using an argument from the related resource, rather than the data source. Given that this would need to change at the Terraform Core level, you'd want to open a feature request in [that repository](https://github.com/hashicorp/terraform). With that in mind, I'll close this issue out. If you feel I've done this in error, please do let me know!
