### ISSUE TITLE
[Enhancement]:  support for `MANUAL_DISCOUNT_COMPATIBILITY` on `aws_cur_report_definition`

### ISSUE THREAD

**Issue by cob16** [hashicorp/terraform-provider-aws#33308]
### Description

Hi all :wave: 

This issue asked for support for 2 enums https://github.com/hashicorp/terraform-provider-aws/issues/30813
`SPLIT_COST_ALLOCATION_DATA` and  `MANUAL_DISCOUNT_COMPATIBILITY` 

The above issue was closed from a SDK update release in 1.5.0 the `MANUAL_DISCOUNT_COMPATIBILITY` enum was never actually added.

 At the time of this post this enum is now returned by the API (and is able to be set in the AWS console by checking manual discount compatible checkbox when edting a cost and usage report https://us-east-1.console.aws.amazon.com/billing/home?region=us-east-1#/reports )

The result here is unfixable drift when running Terraform apply. I understand this is will be a problem upstream with the aws go SDK but thought it would be good to reference here so signpost to any other users with the same issue 

### Affected Resource(s) and/or Data Source(s)

aws_cur_report_definition

### Potential Terraform Configuration

```terraform
resource "aws_cur_report_definition" "example_cur_report_definition" {
  report_name                = "example-cur-report-definition"
  time_unit                  = "HOURLY"
  format                     = "textORcsv"
  compression                = "GZIP"
  additional_schema_elements = ["RESOURCES", "MANUAL_DISCOUNT_COMPATIBILITY"]
  s3_bucket                  = "example-bucket-name"
  s3_region                  = "us-east-1"
  additional_artifacts       = ["REDSHIFT", "QUICKSIGHT"]
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @cob16 👋 Thank you for taking the time to raise this, and for the great contextual information (I like the idea of creating it as a signpost for future visitors)!

Since this is an upstream change that needs to be made, and doesn't represent any work that the team behind the AWS Provider will need to do, I'll close this one out. This helps us to keep open issues scoped to things that the team will need to address.

As an aside, it looks like [someone within AWS](https://github.com/aws/aws-sdk-go/issues/4802) also noticed the lack of support for this in the SDK, and it looks like may be working internally to remedy it (note: I have no visibility into any internal AWS things, so this is based solely on the linked issue).
