### ISSUE TITLE
[Enhancement]: Adding unit tests

### ISSUE THREAD

**Issue by akhateeb22** [hashicorp/terraform-provider-aws#33423]
Hi, Can i contribute in adding unit tests for terraform modules ?

**Comment by justinretzolk** [comment]
Hey @akhateeb22 👋 Thank you for taking the time to raise this, and for being interested in contributing to the provider! I saw that you already contributed one documentation change (thank you!), but if you'd like to contribute some tests as well, check out our [contribution guide](https://hashicorp.github.io/terraform-provider-aws/) for some tips on doing so!

Since there's no further action to be taken here, I'm going to close this issue out. I hope to see you around!
