### ISSUE TITLE
[New Resource]: `aws_rds_integration`

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#34179]
### Description

This resource would support management of zero-ETL integrations between Amazon Aurora and Amazon Redshift.

### Requested Resource(s) and/or Data Source(s)

- `aws_rds_integration`

### Potential Terraform Configuration

```terraform
resource "aws_rds_integration" "example" {
  integration_name = "example"
  source_arn       = aws_rds_cluster.example.arn
  target_arn       = aws_redshift_cluster.example.arn
  kms_key_id       = ""
  tags             = {}
}
```

### References

- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/zero-etl.html
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateIntegration.html
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeIntegrations.html
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DeleteIntegration.html
- Depends on #34173 

### Would you like to implement a fix?

None

**Comment by mnfusaro** [comment]
It would be greatly appreciated if you would consider this implementation. Regards.

**Comment by showwin** [comment]
I'm trying to implement this. So far, I'm about 50% done, but since this is my first contribution, it looks like it'll take about another week. If there's anyone who can implement it faster, they are welcome ✋.

**Comment by showwin** [comment]
Update: I almost finished writing code, but stacked at writing test code. This is because it's difficult to prepare [prerequisites of Zero-ETL](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/zero-etl.html#zero-etl.reqs-lims) with Terraform. One of the requirement is to add "authorized principals" and "authorized integration sources" on the target RedShift ([ref](https://docs.aws.amazon.com/redshift/latest/mgmt/zero-etl-using.setting-up.html#zero-etl-using.redshift-iam)). 
The above document says:
>You can configure authorized principals and authorized integration sources from the Resource Policy tab on the Amazon Redshift console or using the Amazon Redshift `PutResourcePolicy` API operation.

However, the `PutResourcePolicy` does not have the capability to add those resource policies. [The API document of PutResourcePolicy](https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_PutResourcePolicy.html) says:
>Currently, you can use policies to share snapshots across AWS accounts.

I also confirmed the API can work only for snapshot resources but not the namespace resources to which we want to add resource policy.
I'm currently asking AWS support about the limitation of the `PutResourcePolicy` API.

**Comment by showwin** [comment]
PR is ready -- https://github.com/hashicorp/terraform-provider-aws/pull/35199.
Please track this PR for more details.|

**Comment by showwin** [comment]
Regarding the `PutResourcePolicy` API issue reported above, I found it could work correctly with Redshift API instead of Redshift-serverless API. So I could write acceptance test cases.
I reported the issue to AWS support.

**Comment by MihalisW** [comment]
Can I suggest that the resource's name is aws_zero_etl - it would be good for the resource's name to closely match how it is marketed by AWS.

**Comment by pc-js** [comment]
> Can I suggest that the resource's name is aws_zero_etl - it would be good for the resource's name to closely match how it is marketed by AWS.

yes indeed or aws_zero_etl_integration

**Comment by prafulauto1** [comment]
what about the filtering rules, are we going to have a separate resource for it
