### ISSUE TITLE
Need clarity on ignore_failed_scaling_activities behavior

### ISSUE THREAD

**Issue by jimitkr** [hashicorp/terraform-provider-aws#34223]
Given that there are many different error messages that could be ignored I suggest that we add a new ["virtual attribute"](https://hashicorp.github.io/terraform-provider-aws/raising-a-pull-request/#resource-contribution-guidelines) `ignore_failed_scaling_activities` which, if configured to `true`, would cause `statusGroupCapacity` to ignore any `Failed` autoscaling activities and wait for the configured `wait_for_capacity_timeout`.

_Originally posted by @ewbankkit in https://github.com/hashicorp/terraform-provider-aws/issues/29753#issuecomment-1658924166_

**Comment by jimitkr** [comment]
@ewbankkit Need clarity on the behavior of `ignore_failed_scaling_activities`.

What will the result be in the following scenario?

- `ignore_failed_scaling_activities=true`
- terraform apply operation reaches `wait_for_capacity_timeout`
- and the scaling activity still has errors

Will the apply operation fail or succeed?

**Comment by justinretzolk** [comment]
Hey @jimitkr 👋 Thank you for taking the time to raise this, and apologies for the delay in getting back to you. We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.

That said, I've got a bit of information that might help. The [`aws_autoscaling_group` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#wait_for_capacity_timeout) has this to say:

> Maximum [duration](https://golang.org/pkg/time/#ParseDuration) that Terraform should wait for ASG instances to be healthy before timing out.

So in your scenario, the apply would fail due to the timeout. This would be separate from what `ignore_failed_scaling_activities` is tracking, which is failures on the AWS side that would otherwise cause Terraform to fail the apply.
