### ISSUE TITLE
[Bug]: VPC Not Aware of IPAM Pool on Import

### ISSUE THREAD

**Issue by kjenney** [hashicorp/terraform-provider-aws#34304]
### Terraform Core Version

1.3.7

### AWS Provider Version

5.24.0

### Affected Resource(s)

* aws_vpc

### Expected Behavior

I expect that if I import `aws_vpc` that its attributes should be accounted for in terraform state.

### Actual Behavior

The VPC is imported, but there is no VPC IPAM pool information imported in state. 

### Terraform Configuration Files

https://github.com/kjenney/aws_vpc_ipam_test/blob/main/main.tf - code to provision the VPC
https://github.com/kjenney/aws_vpc_ipam_test/blob/main/import/main.tf - code to re-provision it after the import

## Provision

```
terraform init
terraform apply
```
Save `vpc_id` from `Outputs` of apply. Use this in the next step:

Example: `VPC_ID="vpc-122523421532"`

## Test import

```
cd import
terraform init
terraform import aws_vpc.test $VPC_ID
terraform plan
```

### Debug Output

``` 
# aws_vpc.test must be replaced
-/+ resource "aws_vpc" "test" {
      ~ arn                                  = "arn:aws:ec2:us-east-1:161101091064:vpc/vpc-0811a6d672906cfe6" -> (known after apply)
      - assign_generated_ipv6_cidr_block     = false -> null
      ~ cidr_block                           = "172.20.0.0/28" -> (known after apply)
      ~ default_network_acl_id               = "acl-0f2f3a3c06fef68b4" -> (known after apply)
      ~ default_route_table_id               = "rtb-0e32b49fd27dd51da" -> (known after apply)
      ~ default_security_group_id            = "sg-0312d9e8ec677f032" -> (known after apply)
      ~ dhcp_options_id                      = "dopt-5391c82b" -> (known after apply)
      ~ enable_dns_hostnames                 = false -> (known after apply)
      ~ enable_network_address_usage_metrics = false -> (known after apply)
      ~ id                                   = "vpc-0811a6d672906cfe6" -> (known after apply)
      + ipv4_ipam_pool_id                    = "ipam-pool-06fcc2048925bd472" # forces replacement
      + ipv4_netmask_length                  = 28 # forces replacement
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      - ipv6_netmask_length                  = 0 -> null
      ~ main_route_table_id                  = "rtb-0e32b49fd27dd51da" -> (known after apply)
      ~ owner_id                             = "161101091064" -> (known after apply)
      - tags                                 = {} -> null
      ~ tags_all                             = {} -> (known after apply)
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Changes to Outputs:
  + pool_id = "ipam-pool-06fcc2048925bd472"
```

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
From what I can see, the AWS API has a param mismatch between the [CreateVpc](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpc.html) action request and the [Vpc](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Vpc.html) data type. When reading (or importing) the `aws_vpc` resource, info about `ipv4_ipam_pool_id` is not part of the datatype. Whereas for IPv6, a bit more can be deduced from the [VpcIpv6CidrBlockAssociation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VpcIpv6CidrBlockAssociation.html) nested data type, which I see the resource code to be processing:

https://github.com/hashicorp/terraform-provider-aws/blob/5ff7eada83dbf3c7617a59072d0960d619816f2f/internal/service/ec2/vpc_.go#L337-L374

However, even if that is the case, `ipv6_ipam_pool_id` is just fill-in-the-blank from the TF state data. [VpcCidrBlockAssociation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VpcCidrBlockAssociation.html) has even less info. So there's no way to reliably fetch and set the required info from the VPC data type alone.

The replacement action in your test config is technically expected because `ipv4_ipam_pool_id` forces a replacement when the value is changed (from null to the value you are setting).

You could possibly mess with the state file and add the value in manually, but there might still be issues with the state read code not setting `ipv4_ipam_pool_id` to what's in the state after reading from AWS. Probably someone more experienced can chime in and see what a possible proper solution might be.

This is all the PD I can do so far, hope this helps a little in explaining the situation.

**Comment by kjenney** [comment]
Manually editing the state did get the plan/apply to good state, however this should never be considered a solution. This seems like something is missing in the VPC import.

**Comment by drewmullen** [comment]
Hello and thanks for opening this issue!

> The replacement action in your test config is technically expected because ipv4_ipam_pool_id forces a replacement when the value is changed (from null to the value you are setting).

This is correct, when calling `describe-vpcs` the ipam pool id is not a returned value. Essentially, once the VPC is created, the VPC is completely unaware of the IPAM service. For imports you **should not set the ipam related parameters**

As an example:

```hcl
data "aws_region" "current" {}

module "ipam" {
  source  = "aws-ia/ipam/aws"
  version = ">= 2.0.0"

  top_cidr = ["172.0.0.0/8"]

  pool_configurations = {
    (data.aws_region.current.name) = {
      description = "${data.aws_region.current.name} top level pool"
      cidr        = ["172.2.0.0/16"]
      locale      = data.aws_region.current.name
    }
  }
}

resource aws_vpc test {
  # params uncommented: deploy, rm from state
  # params commented: during import and before the next apply
  # ipv4_ipam_pool_id = "ipam-pool-0b7b35df5fad30a41"
  # ipv4_netmask_length = 26
}
```

Once the VPC is imported the parameters above are no longer necessary. This is a known limitation around resources that are both not returned by a resource describe call & are ForceNew when actually changed

I hope this helps!

**Comment by kjenney** [comment]
Is the only "workaround" to modify the state manually?

**Comment by drewmullen** [comment]
No state manipulation is required. Just remove the values from your HCL and that will resolve the detected drift

**Comment by kjenney** [comment]
Replace IPAM values with the assigned CIDR block?

**Comment by drewmullen** [comment]
Actually, funny enough, you don't even have to configure the CIDR since it was computed by IPAM. Simply remove the ipam related parameters and you should see no detected drift :)

Lmk if you have any problems
