### ISSUE TITLE
[Bug]: space_setting is not excepted in aws_sagemake_space

### ISSUE THREAD

**Issue by Kantinofficiel** [hashicorp/terraform-provider-aws#34412]
### Terraform Core Version

0.13

### AWS Provider Version

5.25

### Affected Resource(s)

* aws_sagemaker_space

### Expected Behavior

I want to use space_settings argument like above :

```
resource "aws_sagemaker_space" "example" {
  domain_id  = var.domain_id
  space_name = var.space_name
  tags       = var.tags

  space_settings = {
    jupyter_server_app_settings = {
      code_repository = [
        {
          repository_url = var.code_repository_link
        }
      ]
    }
  }
}
```

### Actual Behavior

I get an error while using space_settings argument

```
╷
│ Error: Unsupported argument
│ 
│   on sagemaker.tf line 8, in resource "aws_sagemaker_space" "this_space":
│    8:   space_settings = {
│ 
│ An argument named "space_settings" is not expected here. Did you mean to
│ define a block of type "space_settings"?
```

### Terraform Configuration Files

```
terraform {
  required_version = ">= 0.13"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.25"
    }
  }
}
```

### Steps to Reproduce

Create a aws_sagemaker_resource with space_settings arguments

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Kantinofficiel 👋 Thank you for taking the time to raise this! This error indicates that you've passed `space_setting` as an argument (`space_setting = {`) rather than as a block (`space_setting {`). For more information on the differences, see the [Configuration Syntax](https://developer.hashicorp.com/terraform/language/syntax/configuration#arguments-and-blocks) documentation.

Updating your example to the following should resolve the issue:

```tf

resource "aws_sagemaker_space" "example" {
  domain_id  = var.domain_id
  space_name = var.space_name
  tags       = var.tags

  space_settings {
    jupyter_server_app_settings {
      code_repository {
        repository_url = var.code_repository_link
      }
     // ...omitted for brevity...
    }
  }
}
```
