### ISSUE TITLE
[Enhancement]: Support for "Max capacity" in Redshift Serverless workgroup

### ISSUE THREAD

**Issue by dima-naboka** [hashicorp/terraform-provider-aws#34440]
### Description

it is possible to set `base_capacity` but not "Max capacity" (perhaps it's not yet available in Amazon API though)

p.s. this is separate from "Maximum RPUs" usage limits

### Affected Resource(s) and/or Data Source(s)

aws_redshiftserverless_workgroup

### Potential Terraform Configuration

hashicorp/aws: 5.27.0

### Would you like to implement a fix?

None

**Comment by timorthi** [comment]
Chiming in to add: 

> (perhaps it's not yet available in Amazon API though)

Setting the `maxCapacity` is possible through the [UpdateWorkgroup API](https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_UpdateWorkgroup.html#API_UpdateWorkgroup_RequestSyntax).

**Comment by pramodpawade** [comment]
Hi @justinretzolk , can we add this as a feature request in Redshift Serverless Terraform? It's currently a major blocker for our serverless implementation.

**Comment by justinretzolk** [comment]
Hey @pramodpawade 👋 Thanks for checking in here! We use issues in this repository as a place to track bugs in the providers and enhancement requests. With that in mind, this issue is where we're tracking feedback for this particular enhancement. For more information on how we prioritize, check out our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/).
