### ISSUE TITLE
[Enhancement]: Terraform destroy of instances is slow compared to AWS Management Console

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform-provider-aws#34469]
### Description

AWS management console shows instances disappearing almost immediately after you destroy them.  I'm guessing thats because they have high confidence the instance is actually being destroyed.

But terraform takes a while to do this:

aws_instance.neb_lighthouse[0]: Still destroying... [id=i-0bee4c9329ed07801

Would it be possible for the AWS API that takes care of this to operate more quickly and assume the instance will be destroyed?

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @queglay 👋 Thank you for taking the time to raise this! I can definitely see where you're coming from, and you're exactly right on the reasoning. Since AWS can take time to destroy those resources, and can validate their destruction asynchronously, they're removed from the UI almost immediately. Terraform, on the other hand, can't validate that the resource was actually destroyed after a run has completed. Because of this, the AWS provider waits for confirmation that the resource has been successfully destroyed before moving on, thus the perceived slowness.

Consider an example where some anomaly occurs, and the instance isn't brought down as expected. If Terraform were to request the destruction of the instance and then moved on without verifying, the instance would have been removed from Terraform's state. In the scenario, the instance is no longer managed by Terraform, but is still running -- something most people using Terraform tend not to desire.
