### ISSUE TITLE
[New Data Source]: aws_cloudfront_origin_access_control

### ISSUE THREAD

**Issue by jtyrus** [hashicorp/terraform-provider-aws#34489]
### Description

Noticed when I was working on docs in #34416 that there wasn't a data source for `aws_cloudfront_origin_access_control`. Not as useful as the Origin Access Identity since the new version doesn't require building an arn and attaching that to the S3 policy, but could still be used as a template or something along those lines.

There's no v2 Cloudfront service yet so could be an easy first feature? Did the PR in v1 but can change it if needed.

### Requested Resource(s) and/or Data Source(s)

`aws_cloudfront_origin_access_control`

### Potential Terraform Configuration

```terraform
data "aws_cloudfront_origin_access_control" "default" {
  id = "E2T5VTFBZJ3BJB"
}

resource "aws_cloudfront_origin_access_control" "new" {
  name                              = "Access Control for Dist 5"
  origin_access_control_origin_type = data.aws_cloudfront_origin_access_control.default.origin_access_control_origin_type
  signing_behavior                  = data.aws_cloudfront_origin_access_control.default.signing_behavior
  signing_protocol                  = data.aws_cloudfront_origin_access_control.default.signing_protocol
}
```

### Would you like to implement a fix?

Yes

**Comment by quinyx-tjeerd** [comment]
Being able to fetch a `aws_cloudfront_origin_access_control` by name could be really powerful. especially when using a single bucket in multipe distro's.

if you look at an example where a single S3 bucket is used by multiple Cloudfront distributions (using different origin paths), all those distro's could reuse the same OAC, instead of having to create separate ones all the time.

bucket:
```
/apps/app1/sha123456/*
/apps/app2/sha123456/* <-- old versions can be kept in s3 bucket
/apps/app2/sha123457/*
```
cloudfronts:
```
app1 -> /apps/app1/sha123456
app2 -> /apps/app2/sha123457
```
performing a new release is then just a path change on the cloudfront.
