### ISSUE TITLE
[Bug]: Projection and Map Task types in Terraform appflow not working

### ISSUE THREAD

**Issue by tusharpandit18** [hashicorp/terraform-provider-aws#34482]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.26.0

### Affected Resource(s)

AWS Appflow

### Expected Behavior

Hi,

I am trying to find some documentation for the different task types AppFlow can have
The aws documentation doesnt provide enough details
https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Task.html

I am trying to use the Map task type, 
when I use

```terraform
  task {
    task_type = "Map"
    source_fields = ["id"]
    destination_field = "id"
  }

  task {
    task_type = "Map"
    source_fields = ["name"]
    destination_field = "name"
  }
```

I get a terraform error of

```console
zr-dev at 11/20/2023 9:45:09 AM: ERROR: CREATING APPFLOW FLOW (LEAD): VALIDATIONEXCEPTION: CREATE FLOW REQUEST FAILED: [TASK VALIDATION ERROR: YOU MUST SPECIFY A PROJECTION TASK OR A MAP_ALL TASK] (16 LINES)
```

and when I use Projection (which is not even a task type in the aws documentation), I get

```terraform
  task {
    task_type = "Projection"
    source_fields = ["id", "name"]
  }

  task {
    task_type = "Map"
    source_fields = ["id"]
    destination_field = "id"
  }

  task {
    task_type = "Map"
    source_fields = ["name"]
    destination_field = "name"
  }
```

```console
│ Error: reading AppFlow Connector Profile (arn:aws:appflow:us-west-2:734371315114:connectorprofile/salesforce-connector-profile): AccessDeniedException: User: arn:aws:sts::734371315114:assumed-role/developers/tusharp@ziprecruiter.com is not authorized to perform: appflow:DescribeConnectorProfiles on resource: arn:aws:appflow:us-west-2:734371315114:connectorprofile/*
│ 
│   with aws_appflow_connector_profile.salesforce-connector-profile,
│   on appflow.tf line 6, in resource "aws_appflow_connector_profile" "salesforce-connector-profile":
│    6: resource "aws_appflow_connector_profile" "salesforce-connector-profile" {
│ 
╵
[ERROR] terraform exited with code 1
infra-global|tusharp-EMP-11927-appflow-terraform-import-flow ⇒ zr-terraform plan -e zr-dev                                      
╷
│ Error: expected task.2.task_type to be one of ["Arithmetic" "Filter" "Map" "Map_all" "Mask" "Merge" "Passthrough" "Truncate" "Validate" "Partition"], got Projection
│ 
│   with aws_appflow_flow.lead,
│   on lead.tf line 1, in resource "aws_appflow_flow" "lead":
│    1: resource "aws_appflow_flow" "lead" {``` 
```

### Terraform Configuration Files

```terraform
  task {
    task_type = "Projection"
    source_fields = ["id", "name"]
  }

  task {
    task_type = "Map"
    source_fields = ["id"]
    destination_field = "id"
  }

  task {
    task_type = "Map"
    source_fields = ["name"]
    destination_field = "name"
  }
```

### Steps to Reproduce

terraform plan

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @tusharpandit18  👋 Thank you for taking the time to raise this! In this case, it looks like the AWS API is expecting you to either pass `Map_all` as the value of the [`task_type` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appflow_flow#task_type), or use `PROJECTION` as the value of one of the [`connector_operator` fields](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appflow_flow#connector-operator). 

If that doesn't work, and since this is more of a usage question, we'd ask that you ask in one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). We use Issues in this repository to track feature enhancements and bugs in the AWS Provider itself. So that we can maintain focus on that, we ask that broader questions are directed that way. With that in mind, I'm going to close this issue.
