### ISSUE TITLE
[Bug]: Default tags on provider does not set tags on DHCP option set and default route table

### ISSUE THREAD

**Issue by vmanikes** [hashicorp/terraform-provider-aws#34537]
### Terraform Core Version

1.6.4

### AWS Provider Version

5.26.0

### Affected Resource(s)

When creating a new VPC with default tags set on provider like below
```provider "aws" {
  region  = "us-west-2"
  profile = "default"
  default_tags {
    tags = {
      Owner = "chaitanya-cloud"
      Name  = "chaitanya-cloud"
    }
  }
}
```
It sets tags on VPC but does not set tags on the DHCP option set and default route table created using the VPC resource
```
resource "aws_vpc" "main" {
  cidr_block                           = "10.0.0.0/16"
  enable_dns_support                   = true
  enable_network_address_usage_metrics = true
  enable_dns_hostnames                 = true
  assign_generated_ipv6_cidr_block     = true
}
```

### Expected Behavior

Should actually set tags on all the underlying resource created

### Actual Behavior

Tags are only set on VPC but not the resources created by the VPC resource

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  required_version = "~> 1.6"
}

provider "aws" {
  region  = "us-west-2"
  profile = "default"
  default_tags {
    tags = {
      Owner = "chaitanya-cloud"
      Name  = "chaitanya-cloud"
    }
  }
}

resource "aws_vpc" "main" {
  cidr_block                           = "10.0.0.0/16"
  enable_dns_support                   = true
  enable_network_address_usage_metrics = true
  enable_dns_hostnames                 = true
  assign_generated_ipv6_cidr_block     = true
}
```

### Steps to Reproduce

`terraform apply` on the above snippet will help repro this issue

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @vmanikes 👋 Thank you for taking the time to raise this! While I agree that this would be a nice feature,  the AWS Go SDK doesn't currently support specifying that kind of inheritance (SDK `CreateVPCInput` reference [here](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#CreateVpcInput). Since it's not something that the SDK supports, we won't be able to add that functionality to the provider at this time, so we'll close this issue for now. If support for this kind of thing is added to the SDK in the future, we'd be happy to take another look!

I'd be remiss if I didn't mention that there are some other resources that might help you out, such as [`aws_vpc_dhcp_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_dhcp_options), [`aws_default_vpc_dhcp_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_vpc_dhcp_options), and [`aws_default_route_table`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table).
