### ISSUE TITLE
[Bug]: Unable to empty `aws_network_acl` inline rules - at least 1 will remain

### ISSUE THREAD

**Issue by Stretch96** [hashicorp/terraform-provider-aws#34540]
### Terraform Core Version

1.6.4

### AWS Provider Version

5.26.0

### Affected Resource(s)

aws_network_acl

### Expected Behavior

When creating an `aws_network_acl`, with inline rules, I should be able to remove those rules, and the ACL be empty.
However, it will leave the first rule remaining

### Actual Behavior

If `egress` or `ingress` rules are empty, it should remove all the rules

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

```terraform
locals {
  acl_egress_rules = [
    {
      protocol   = "tcp"
      from_port  = 80
      to_port    = 80
      action     = "allow"
      cidr_block = "0.0.0.0/0"
    }
  ]
  acl_ingress_rules = [
    {
      protocol   = "tcp"
      from_port  = 80
      to_port    = 80
      action     = "allow"
      cidr_block = "0.0.0.0/0"
    }
  ]
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "bug-report-acl-rules"
  }
}

resource "aws_network_acl" "main" {
  vpc_id = aws_vpc.main.id

  dynamic "egress" {
    for_each = local.acl_egress_rules

    content {
      protocol        = egress.value["protocol"]
      from_port       = egress.value["from_port"]
      to_port         = egress.value["to_port"]
      action          = egress.value["action"]
      cidr_block      = egress.value["cidr_block"]
      rule_no         = egress.key + 1
    }
  }

  dynamic "ingress" {
    for_each = local.acl_ingress_rules

    content {
      protocol        = ingress.value["protocol"]
      from_port       = ingress.value["from_port"]
      to_port         = ingress.value["to_port"]
      action          = ingress.value["action"]
      cidr_block      = ingress.value["cidr_block"]
      rule_no         = ingress.key + 1
    }
  }

  tags = {
    Name = "bug-report-acl-rules"
  }
}
```

### Steps to Reproduce

```
terraform apply
```
Then change the locals `acl_egress_rules` and `acl_ingress_rules` to `[]`
```
terraform apply
```
The rule isn't removed

Changing the rule will however correctly overwrite it

### Debug Output

N/A

### Panic Output

N/A

### Would you like to implement a fix?

None

**Comment by Stretch96** [comment]
Using the `aws_network_acl_rule` resource works as expected, eg.

```terraform
locals {
  acl_egress_rules = [
   {
    protocol   = "-1"
    from_port  = 0
    to_port    = 0
    action     = "allow"
    cidr_block = "0.0.0.0/0"
  }
  acl_ingress_rules = [
  {
      protocol   = "-1"
      from_port  = 0
      to_port    = 0
      action     = "allow"
      cidr_block = "0.0.0.0/0"
    }
  ]
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "bug-report-acl-rules"
  }
}

resource "aws_network_acl" "main" {
  vpc_id = aws_vpc.main.id

  tags = {
    Name = "bug-report-acl-rules"
  }
}

resource "aws_network_acl_rule" "egress" {
  count = length(local.acl_egress_rules)

  network_acl_id = aws_network_acl.main.id
  rule_number    = count.index + 1
  egress         = true
  protocol       = local.acl_egress_rules[count.index]["protocol"]
  rule_action    = local.acl_egress_rules[count.index]["action"]
  cidr_block     = local.acl_egress_rules[count.index]["cidr_block"]
  from_port      = local.acl_egress_rules[count.index]["from_port"]
  to_port        = local.acl_egress_rules[count.index]["to_port"]
}

resource "aws_network_acl_rule" "ingress" {
  count = length(local.acl_ingress_rules)

  network_acl_id = aws_network_acl.main.id
  rule_number    = count.index + 1
  egress         = false
  protocol       = local.acl_ingress_rules[count.index]["protocol"]
  rule_action    = local.acl_ingress_rules[count.index]["action"]
  cidr_block     = local.acl_ingress_rules[count.index]["cidr_block"]
  from_port      = local.acl_ingress_rules[count.index]["from_port"]
  to_port        = local.acl_ingress_rules[count.index]["to_port"]
}
```

Perhaps depreciate inline egress/ingress for `aws_network_acl`?

Perhaps depreciate the `egress` and `ingress` parameters?

**Comment by justinretzolk** [comment]
Hey @Stretch96  👋 Thank you for taking the time to raise this! This is happening due to something I described in [this comment](https://github.com/hashicorp/terraform-provider-aws/issues/31004#issuecomment-1526237294). 

The quick version is that when you set the `acl_egress_rules` and `acl_ingress_rules` to `[]`, the `dynamic` block will produce no `ingress` blocks at all. Due to attributes-as-blocks mode, this leads to the resource ignoring any existing rules, rather than removing them. In order to remove any existing rules, you'd need to explicitly pass `ingress = []`, which will delete all rules.

I'd definitely recommend the `aws_network_acl_rule`, like you'd mentioned in your follow up comment. There tends to be a bit of mixed reactions when it comes to completely removing things like `ingress` and `egress` from `aws_network_acl` in favor of only supporting standalone resources, but if there was appetite from the community to do so, we'd certainly consider it.

Since this comes down to the configuration, rather being being a bug with the provider itself, I'll close this issue. If you run into any other issues with the provider, please do let us know!
