### ISSUE TITLE
[New]: AWS Cost Optimization Hub

### ISSUE THREAD

**Issue by bebold-jhr** [hashicorp/terraform-provider-aws#34588]
### Description

Cost Optimization Hub is a new AWS Billing and Cost Management feature that helps you consolidate and prioritize cost optimization recommendations across your AWS Organizations member accounts and AWS Regions, so that you can get the most out of your AWS spend.

### Requested Resource(s) and/or Data Source(s)

* aws_cost_optimization_hub_config

### References

Announcement: https://aws.amazon.com/about-aws/whats-new/2023/11/cost-optimization-hub/
Product Page: https://aws.amazon.com/aws-cost-management/cost-optimization-hub/
AWS CLI since 1.30.7: https://github.com/aws/aws-cli/blob/0f81aeeda03b78d9b6eb9d439cc6213c49ad15b9/.changes/1.30.7.json#L14

### Would you like to implement a fix?

No

**Comment by madhavvishnubhatta** [comment]
I am trying to work on creating resources for this, but I feel it is better to have two different resources. One for EnrollmentStatus and one for Preferences as that is how the API is structured - https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_Operations_Cost_Optimization_Hub.html

**Comment by madhavvishnubhatta** [comment]
After working on this a bit more and thinking about it, I feel a single resource makes more sense. But calling the resource as aws_costoptimizationhub_enrollment seems to make more sense because, then it aligns neatly with the definition of a resource. That is, when the enrollment resource is "Created" then the account enrolls for cost optimization hub, with the provided preferences. When the enrollment resource is "Destroyed" and then the account unenrolls.

**Comment by lblazewski** [comment]
Looking forward for this one!

**Comment by vponoikoait** [comment]
+
