### ISSUE TITLE
[Enhancement]: support to expose file_system_id attribute for aws_efs_file_system data block

### ISSUE THREAD

**Issue by fetchkarthikkasarapu** [hashicorp/terraform-provider-aws#34613]
### Description

Similar to how `aws_efs_file_system` resource block exposes "id" [attribute](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#id) (The ID that identifies the file system). It would be nice to have the same attribute supported for `aws_efs_file_system` data block as well.

### Affected Resource(s) and/or Data Source(s)

- data.aws_efs_file_system

### Potential Terraform Configuration

```terraform
data.aws_efs_file_system.my-fs.id
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @fetchkarthikkasarapu 👋 Thank you for taking the time to raise this! It looks like what you're looking for currently exists by way of the [`file_system_id` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/efs_file_system#file_system_id) of the `aws_efs_file_system` data source.

As far as Terraform is concerned, "arguments" and "attributes" are the same thing. We separate them in the documentation to make it more clear which ones can be set by the user ("arguments"), and which ones are read-only ("attributes"). Since they're the same thing as far as Terraform is concerned, you can interpolate the arguments the same way:

`data.aws_efs_file_system.my-fs.file_system_id`
