### ISSUE TITLE
[Docs]: Missing arguments for attribute reference of data.aws_key_pair

### ISSUE THREAD

**Issue by y-sera** [hashicorp/terraform-provider-aws#34857]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/key_pair

### Description

In a document of Data Resource aws_key_pair, "key_name" argument  dose not exiest at Attribute Reference.
But, it actually exits.

We need to add this 1 line at Attribute Reference.
* `key_name` - The key pair name.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @y-sera 👋 Thank you for taking the time to raise this! In this case, the `key_name` and `key_pair_id` attributes don't show up in the "Attributes" section because they are also arguments. We try to call this out just under the "Attributes" header with this comment:

> This data source exports the following attributes in addition to the arguments above:

The terms "arguments" and "attributes" are often used interchangeably, but we use them mostly to distinguish between things you can supply a value to ("arguments") and things that are read only ("attributes"). [This section](https://developer.hashicorp.com/terraform/language/syntax/configuration#arguments) of the Terraform documentation touches on this a bit:

> Note: Terraform's configuration language is based on a more general language called HCL, and HCL's documentation usually uses the word "attribute" instead of "argument." These words are similar enough to be interchangeable in this context, and experienced Terraform users might use either term in casual conversation. But because Terraform also interacts with several other things called "attributes" (in particular, Terraform resources have attributes like id that can be referenced from expressions but can't be assigned values in configuration), we've chosen to use "argument" in the Terraform documentation when referring to this syntax construct.

With the above in mind, closing.
