### ISSUE TITLE
[Docs]: ecs_cluster attribute reference

### ISSUE THREAD

**Issue by rwe-dtroup** [hashicorp/terraform-provider-aws#34927]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster#attribute-reference

### Description

There seems to be an attribute missing from the aws_cluster resource (.name) it's still possible to use this but it seems that it's just using the input for the name in an output, it's very odd.

```hcl
output "name" {
  description = "The name of the ECS cluster"
  value       = aws_ecs_cluster.this.name
}
```

Seems to work, is this a bug or is it missing the documentation??

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @rwe-dtroup 👋 Thank you for taking the time to raise this! With the way that Terraform works, all "arguments" and "attributes" are handled the same way. We make a distinction in the documentation to more clearly delineate between values that are user-configurable and values that are read-only.

With that in mind, `name` is listed under the arguments section (since it's configurable), but can still be interpolated, as you're seeing in your output. This becomes useful when you need to reference the resource by name in other resources.

Since this is functioning as expected, and `name` is documented, I'm going to close this issue out. If you notice anything else amiss in the documentation, please do let us know! We're always looking to improve.
