### ISSUE TITLE
[Enhancement]: Add RotateImmediately to aws_secretsmanager_secret_rotation

### ISSUE THREAD

**Issue by sakojun** [hashicorp/terraform-provider-aws#34961]
### Description

aws_secretsmanager_secret_rotation must accept the RotateImmediately parameter.
If this parameter is not specified, immediate rotation will be performed.
The SDK supports this parameter, but Terraform does not.

### Affected Resource(s) and/or Data Source(s)

aws_secretsmanager_secret_rotation

### Potential Terraform Configuration

```terraform
resource "aws_secretsmanager_secret_rotation" "example" {
  secret_id           = aws_secretsmanager_secret.example.id
  rotation_lambda_arn = aws_lambda_function.example.arn

  rotate_immediately = false

  rotation_rules {
    automatically_after_days = 30
  }
}
```

### References

https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_RotateSecret.html
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/secretsmanager#Client.RotateSecret
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/secretsmanager#RotateSecretInput

### Would you like to implement a fix?

None

**Comment by galiceau** [comment]
Hello

I add my issue because I think that it could be the same topic : disable the password rotation (in AWS secret ) of RDS in terraform. It is only possible from console or API.
In this [answer](https://github.com/hashicorp/terraform-provider-aws/issues/4349 it was precised that if ](https://github.com/hashicorp/terraform-provider-aws/issues/4349#issuecomment-384422834))  "As noted in the [aws_secretsmanager_secret resource rotation example](https://www.terraform.io/docs/providers/aws/r/secretsmanager_secret.html#rotation-configuration), adding rotation_lambda_arn will enable rotation. Removing that argument will disable rotation." 
=> **It doesn't work.** 

`
module "difa-rds" {
  source  = "terraform-aws-modules/rds/aws"
  version = "6.1.0"
..
}

resource "aws_secretsmanager_secret_rotation" "db_instance_master_user_secret_rotation" {
  secret_id               = module.difa-rds.db_instance_master_user_secret_arn
  rotation_rules {
    automatically_after_days = 30
  } 
}`


regards

**Comment by cbhoffman** [comment]
I wouldn't mind having a look at this and see if I can get something in to fix.
