### ISSUE TITLE
[Bug]: When `terraform import` is used the absolute path is generated for `path.module`

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#35055]
### Terraform Core Version

Terraform v1.6.4

### AWS Provider Version

registry.terraform.io/hashicorp/aws v4.67.0

### Affected Resource(s)

data "archive_file" "dnsUrlRedirects"
resource "aws_lambda_function" "dnsUrlRedirects"

### Expected Behavior

The path should be relative

### Actual Behavior

The path is absolute

### Relevant Error/Panic Output Snippet

![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/a00c1c43-96ab-4451-aa1e-79e01f15cf31)

### Terraform Configuration Files
```
data "archive_file" "dnsUrlRedirects" {
  type        = "zip"
  source_file = "${path.module}/lambda-function/index.js"
  output_path = "${path.module}/lambda-function/urlRedirects.zip"
}
```
### Steps to Reproduce
```
terraform plan -generate-config-out=billing_policy.tf.import
terraform import aws_iam_group_policy_attachment.billing_s3_read_only Billing/arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
...
```
I also did many other imports, but this one cause issue.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @EugenKon 👋 Thanks for taking the time to raise this! We [don't recommend `path.module`](https://developer.hashicorp.com/terraform/language/expressions/references#path-module) because it can have different results, much like you're seeing here. The document I linked has a couple of other suggestions, but since this is related to Terraform Core rather than the AWS Provider itself, I'll be closing this issue.
