### ISSUE TITLE
[Docs]: Import aws_key_pair

### ISSUE THREAD

**Issue by interone-ms** [hashicorp/terraform-provider-aws#35118]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/key_pair

### Description

The docs state that:

> The AWS API does not include the public key in the response, so terraform apply will attempt to replace the key pair. There is currently no supported workaround for this limitation.

However, there is a workaround... manually editing the state:

1. Pull the current state: `terraform state pull > current.tfstate`
2. Locate the `aws_key_pair` resource in question and manually change the `public_key` value from `null` to the string one wants
3. Increment the `serial` value at the top of the state file
4. Push the new state: `terraform push current.tfstate`
5. Delete the temporary file to avoid leakage of secrets

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @interone-ms 👋 Thank you for taking the time to raise this! You're totally correct that manipulating the state this way would allow you to "import" the `aws_key_pair` (or any other "non-importable" resources). That said, we generally [discourage directly editing the state](https://developer.hashicorp.com/terraform/language/state#inspection-and-modification) due to it's sensitivity, so it's not something we'd want to outline in the documentation here.

Regardless, thank you for the suggestion, and your desire to improve our documentation! Given that we won't be moving forward with this one, I'm going to close it out. If you have any other suggestions, please do open a new issue and let us know.
