### ISSUE TITLE
[Enhancement]: lambda_function should not validate the runtime parameter

### ISSUE THREAD

**Issue by obones** [hashicorp/terraform-provider-aws#35159]
### Description

Right now, the lambda_function.runtime parameter is checked by the provider to be one of the values it knows about.
The [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#runtime), however, gives a link to the appropriate AWS [page](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime) which leads anyone to believe that any value in that page is supported.
Sadly, this is not the case, and there is always a delay between availability at AWS and support in terraform. See #31510 and #34360 for instance.
In my case, I would like to use `nodejs20.x` but it's not supported by any version, and I doubt it would even be ported to the v4 provider.

My request is thus to stop managing a list of supported runtimes and rely on the AWS servers to return an error when the given value is not supported at their side.

### Affected Resource(s) and/or Data Source(s)

aws_lambda_function

### Potential Terraform Configuration

```terraform
resource aws_lambda_function lambda_function {
    function_name       = "myFunction"
    role                = var.role.arn
    runtime             = "nodejs20.x"
    handler             = "index.handler"
    filename            = "source.zip"
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/4.67.0/docs/resources/lambda_function
https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime
#31510 
#34360 

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
The code for the `aws_lambda_function` code uses the data types from the AWS SDK for Go v2 for the validation. So you would need a AWS Terraform Provider version that depends on a version of the AWS SDK for Go v2 with the new runtime support. According to [the Lambda service CHANGELOG](https://github.com/aws/aws-sdk-go-v2/blob/main/service/lambda/CHANGELOG.md), it would be v1.44.0 (2023-11-08). I can then see from #34324 that the AWS SDK dependency update went into v5.25.0 which was release 2023-11-10. That's actually a pretty good turnaround time!

As such, please check whether you are using v5.25.0 or latter version of the provider. For reference, I tested your config (provided my own role and source.zip) with v5.31.0 and I am able to create the function using nodejs20.x as the runtime.

As for the validation, even if it's removed from the Terraform code, the AWS SDK would still validate the runtime. In general, more validation is desirable so long as the dependencies are kept frequently up to date with reasonable turnaround time. The documentation issue is tricky since it should point to a snapshot instead of a continuously evolving document with this type of technical settings. I would recommend adding a note or a disclaimer on the lag in supporting new runtimes so at least there is some awareness.

Hope this explains the situation. I am just a volunteer contributor so perhaps the maintainers can provide more insights as needed.

**Comment by obones** [comment]
Except that I'm currently stuck on the v4 provider for the foreseeable future.
And what I was expecting in my initial message is that there wouldn't be a need to upgrade anything should the provider leave it to the SDK for GO to do the validation which I believed was done server side, not inside the SDK itself.
However, I went looking for the code and saw the enumeration which indeed is inside the SDK.
So yes, in the end, it's a documentation issue but it's a bit sad this will not make it into the v4 SDK
