### ISSUE TITLE
[Docs]: How to get all the solution stacks in Elastic bean stack terraform aws

### ISSUE THREAD

**Issue by raghunathreddy** [hashicorp/terraform-provider-aws#35183]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/5.31.0/docs/data-sources/elastic_beanstalk_solution_stack

### Description

How to get all the solution stacks in Elastic bean stack terraform aws

this is not working
data "aws_elastic_beanstalk_solution_stacks" "all_stacks" {}

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
The `elastic_beanstalk_solution_stack` data source is meant to fetch a single Elastic Beanstalk stack based on the name regex, so it cannot do what you are looking for.

**Comment by raghunathreddy** [comment]
Thanks for your reply.

Is their a way to get all the solution stack details in Elastic bean stack
using terraform

Kindly could you help me with this concern.

Best Regards,
Raghunath

**Comment by justinretzolk** [comment]
Hey @raghunathreddy 👋 I took a quick look, and it doesn't look like we currently have a data source that accomplishes what you're looking for. That said, we use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). Someone in the community may have some details that help point you in the right direction. Otherwise, please feel free to open a feature request ticket for a plural version of this data source so that we can triage it appropriately. With those things in mind, I'm going to close this issue.
