### ISSUE TITLE
[Enhancement]: Add `-auto-approve` to `init -migrate-state`

### ISSUE THREAD

**Issue by silopolis** [hashicorp/terraform-provider-aws#35329]
### Description

To be able to provision the S3 backend bucket for my projects with the same configuration, I came to a solution where I'm switching from and to local backend.

This is working nicely except that I can't make the state migration steps unattended :cry: 

Could the `init` command have the same `-auto-approve` flag as its siblings, please ?

TY in advance
J

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @silopolis 👋 Thank you for taking the time to raise this! It looks like this is a request to alter the behavior of Terraform itself, rather than with the AWS Provider. In order to reach the appropriate team, you'll want to open an issue in the [Terraform Core repository](https://github.com/hashicorp/terraform). With that in mind, I'm going to close this issue.

**Comment by silopolis** [comment]
Hey @justinretzolk !
Shame on me :blush: 
Had reported another one before and just kept on here like a robot :/
Sorry for the noise and thanks for your work :pray:
