### ISSUE TITLE
[Enhancement]: Share exiting the RDS snapshot

### ISSUE THREAD

**Issue by ChauAnhTuan** [hashicorp/terraform-provider-aws#35424]
### Description

I manage a lot of RDS snapshots, and I want to use Terraform to share the RDS snapshots with other accounts without the RDS instance or cluster. 

Like the AMI launch permission: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_launch_permission

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ChauAnhTuan 👋 Thanks for taking the time to raise this! Does the [`aws_db_snapshot` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot) provide the functionality you're looking for?

**Comment by ChauAnhTuan** [comment]
The [aws_db_snapshot resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot) requires an RDS instance and [aws_db_cluster_snapshot resource] https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_cluster_snapshot require the RDS cluster to create a snapshot and then share it. But I want to share RDS snapshots (No RDS instances or clusters).

**Comment by ChauAnhTuan** [comment]
I saw a guild on the AWS document. It uses the AWS CLI.

`aws rds modify-db-snapshot-attribute \
--db-snapshot-identifier db7-snapshot \
--attribute-name restore \
--values-to-add 123456789012`

**Comment by justinretzolk** [comment]
@ChauAnhTuan So in your case, you already have snapshots created, you just want to update them to add accounts to share with? If that's the case, you could still use `aws_db_snapshot` by creating a Terraform configuration with the desired state, [importing the existing snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot#import), and then running Terraform as normal.

Apologies if I'm overlooking something here, I just want to make sure we're on the same page 🙂.

**Comment by ChauAnhTuan** [comment]
I already have snapshots on my AWS account. It hasn't been shared with other accounts, so I want to use Terraform to share or revoke permissions for the snapshots.

**Comment by justinretzolk** [comment]
@ChauAnhTuan That sounds like the perfect use case for importing those existing resources using the document that I linked to in my last comment. Were you able to review that to verify that it covers your use case?

**Comment by ChauAnhTuan** [comment]
I want to share the RDS snapshots, Not import anything. You can read on this page. https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBSnapshotAttribute.html

The AWS provider does not support this function.

**Comment by justinretzolk** [comment]
@ChauAnhTuan Thanks for that info -- I see where we're missing each other now. The [`aws_db_snapshot` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot) is the resource that the AWS Provider currently has that's used to manage RDS snapshots. 

When that resource is used, it's [update function](https://github.com/hashicorp/terraform-provider-aws/blob/f49fa3d292a3aab4f690e09dd8cb09d2260c9c68/internal/service/rds/snapshot.go#L227-L254) (what's called if Terraform recognizes a change in the configuration, like adding another account to share to) [uses the `rds.ModifyDBSnapshotAttributeWithContext` function](https://github.com/hashicorp/terraform-provider-aws/blob/f49fa3d292a3aab4f690e09dd8cb09d2260c9c68/internal/service/rds/snapshot.go#L239-L246) from the AWS Go SDK to make that modification -- the same function you've linked to. This is the resource you'll need in order to manage the RDS snapshots in the way you're wanting.

If you were to just add `aws_db_snapshots` to your Terraform configuration, however, Terraform would create new RDS snapshots. In order to bring your existing snapshots under Terraform's management (i.e. map them to the `aws_db_instance` resources declared in your Terraform configuration), you'll need to import them into Terraform's state file. You can do this using Terraform's [`import` command](https://developer.hashicorp.com/terraform/cli/import) or (In Terraform 1.5.0 or later) with [`import` blocks](https://developer.hashicorp.com/terraform/language/import).

We have an [import tutorial](https://developer.hashicorp.com/terraform/tutorials/state/state-import) with a more detailed walkthrough that's remarkably similar to what you're trying to accomplish (import existing resources into the Terraform state file, generate a configuration for those resources, update them to modify them in some way, etc.). I'd definitely recommend reading that over for more information.

Now that I understand where you're coming from, and with the information above that this is something that can be accomplished today, closing. If you have any other enhancement requests or bugs to report in the future, please do let us know!
