### ISSUE TITLE
[Bug]: Issue With AWS EKS aws_eks_access_policy_association An argument named "access_scope" is not expected here.

### ISSUE THREAD

**Issue by cbean310** [hashicorp/terraform-provider-aws#35459]
### Terraform Core Version

1.7.0

### AWS Provider Version

5.33.0

### Affected Resource(s)

aws_eks_access_policy_association

### Expected Behavior

to complete a terraform apply

### Actual Behavior

Getting these errors

<img width="915" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/115193257/0f357ab2-1aee-40b0-b3a2-b654238ddf28">

### Terraform Configuration Files

<img width="272" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/115193257/76194567-25da-4634-94a9-f3304e09cf40">

### Steps to Reproduce

configuring a resource listed in the terraform configuration file and running a terraform apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @cbean310 👋 Thank you for taking the time to raise this! This error is due to passing `access_scope` as an argument rather than a block (the difference of which is described [in this document](https://developer.hashicorp.com/terraform/language/syntax/configuration#arguments-and-blocks)). The correct syntax would remove the `=`, as in:

```terraform
resource "aws_eks_access_policy_association" "example" {
  # omitted for brevity
  access_scope {
    type       = "namespace"
    namespaces = ["example-namespace"]
  }
}
```

It looks like the documentation has this incorrect, so I'll work on getting that fixed.
