### ISSUE TITLE
Update of "client_subnets" causing recreation of msk cluster

### ISSUE THREAD

**Issue by PeteMac88** [hashicorp/terraform-provider-aws#35641]
### Description

Hey,
I need to add subnets to our existing VPC which is the base for the `client_subnets`. In most modules this causes an update of the existing resource but for the `aws_msk_cluster` it causes the aws resource to be deleted and recreated. Is there a way to avoid this?

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @PeteMac88 👋 Thank you for taking the time to raise this! The `client_subnets` argument of the `aws_msk_cluster` resource are marked as [`ForceNew` in the codebase](https://github.com/hashicorp/terraform-provider-aws/blob/1957a85c96368cf47fecdd00f1272060466ee932/internal/service/kafka/cluster.go#L118-L125), so changes to that argument will always trigger recreation of the resource. This is generally due to a lack of API support for updating the argument in question, which seems to be the case here. Since there's no way to update it via the API, the only option Terraform has is to trigger recreation. Unfortunately this means that there's no way around it for your case. With that in mind, I'll close this issue, but if the necessary API changes are made in the future, we'd be happy to take another look.
