### ISSUE TITLE
[Bug]: Not possible to define empty `throttle_settings`

### ISSUE THREAD

**Issue by cpinamtz** [hashicorp/terraform-provider-aws#35766]
### Terraform Core Version

1.7.3

### AWS Provider Version

5.36.0

### Affected Resource(s)

aws_api_gateway_usage_plan

### Expected Behavior

I'd like to create the `throttle_settings` attribute passing default params. Like the following:
```
throttle_settings {
  burst_limit = lookup(each.value, "quota_burst_limit", null)
  rate_limit  = lookup(each.value, "quota_rate_limit", null)
}
```

I'm using here the `lookup` approach due to I'm using a custom map to provide the data to each resource created.

### Actual Behavior

The `terraform plan` does not allow this. You need to pass at least `burst_limit` or `rate_limit`. 
Output:
```
│ Error: Missing required argument
│ 
│   with module.modules.module.api.aws_api_gateway_usage_plan.usage_plans["my_provider1"],
│   on modules/api/main.tf line 227, in resource "aws_api_gateway_usage_plan" "usage_plans":
│  227:     burst_limit = lookup(each.value, "quota_burst_limit", 9999999)
│ 
│ "throttle_settings.0.burst_limit": one of `throttle_settings.0.burst_limit,throttle_settings.0.rate_limit` must be specified
```

### Terraform Configuration Files

```
locals {
  # Custom structure to create resources dynamically
  api_keys_settings = {
    my_provider1 = {
      enable_throttling = false
      // quota_burst_limit = 9999999
      // quota_rate_limit  = 9999999
    },
    my_provider2 = {
      enable_throttling = false
      // quota_burst_limit = 9999999
      // quota_rate_limit  = 9999999
    }
  }
}

# API keys and usage plans
resource "aws_api_gateway_api_key" "api_keys" {
  for_each = { for key, value in local.api_keys_settings : key => value }

  name        = "${each.key}_api_key"
  description = "API key used by ${title(each.key)} 3rd party"
}

resource "aws_api_gateway_usage_plan" "usage_plans" {
  for_each = { for key, value in local.api_keys_settings : key => value }

  name        = each.key
  description = "Usage plan created specifically for ${title(each.key)}"

  api_stages {
    api_id = aws_api_gateway_rest_api.api_k8s_gw.id
    stage  = aws_api_gateway_stage.api_k8s_gw.stage_name
  }

  throttle_settings {
    burst_limit = lookup(each.value, "quota_burst_limit", null)
    rate_limit  = lookup(each.value, "quota_rate_limit", null)
  }
}
```

### Steps to Reproduce

1. `terraform plan`
2. Enjoy

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @cpinamtz  👋 Thank you for taking the time to raise this! This error is being thrown because you're explicitly supplying `null` for both `burst_limit` and `rate_limit`, rather than leaving them as the default value. To do what you're looking for, you'd want to not have a `throttle_settings` block at all if you were looking to leave both values at their defaults, which you could do with [`dynamic` blocks](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks). The `for_each` could be set to conditionally create the block using a [conditional expression](https://developer.hashicorp.com/terraform/language/expressions/conditionals) only when a non-default value is desired.

Since this is more configuration related than a bug with the provider, we'd ask that you direct any follow up questions to one of the [community resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.

**Comment by cpinamtz** [comment]
In case you're in the same situation, I finally solved it with the following way:
```
dynamic "throttle_settings" {
  for_each = each.value.enable_throttling == true ? [1] : []
  content {
    burst_limit = each.value.quota_burst_limit
    rate_limit  = each.value.quota_rate_limit
  }
}
```
[Reference](https://reespozzi.medium.com/conditional-nested-configuration-blocks-for-terraform-resources-57d8ce372bad)
