### ISSUE TITLE
[Enhancement]: sagemaker app_image_config JupyterLab missing FileSystemConfig properties

### ISSUE THREAD

**Issue by damianslee** [hashicorp/terraform-provider-aws#35826]
### Description

FileSystemConfig is missing from sagemaker app image config for JupyterLab type image.

https://docs.aws.amazon.com/cli/latest/reference/sagemaker/update-app-image-config.html

--jupyter-lab-app-image-config (structure)

The JupyterLab app running on the image.

FileSystemConfig -> (structure)

The Amazon Elastic File System storage configuration for a SageMaker image.

MountPath -> (string)

The path within the image to mount the user's EFS home directory. The directory should be empty. If not specified, defaults to /home/sagemaker-user .
DefaultUid -> (integer)

The default POSIX user ID (UID). If not specified, defaults to 1000 .
DefaultGid -> (integer)

The default POSIX group ID (GID). If not specified, defaults to 100 .

### Potential Terraform Configuration

```terraform
JupyterLab FileSystemConfig is exact same as KernelGateway FileSystemConfig 
```

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
I was working on adding support for `file_system_config` for `jupyter_lab_image_config` but the API is always returning a 400 error with the following message when `file_system_config` is provided:

```
Error: creating SageMaker App Image Config test: ValidationException: FileSystemConfig parameters are not supported for provided AppImageConfig
```

The same is true when calling the same API using AWS CLI. Looking at the network traffic from the GUI, it seems that the FileSystemConfig info is not sent to the backend even when supplied. The settings also don't seem to persist when creating or updating the image properties. So I am guessing that although the API contract says the attribute is "supported", it might not make sense to provide it.

If you happen to have a test case that works using the AWS CLI, let me know and I can look more into it. Alternatively you can perhaps open an AWS Support ticket to inquire further about while file system config isn't accepted for Jupyter Lab app image.

For now, since file system config isn't accepted by the backend, there is no point to add that support.

**Comment by damianslee** [comment]
I checked with AWS support, this seems to be a error in the documentation.   FileSystemConfig is not availble for JupyterLab

**Comment by acwwat** [comment]
Thanks for confirming. Since this is not supported, please feel free to close this ticket.
