### ISSUE TITLE
[Bug]: Behaviour change for aws_subnet data call

### ISSUE THREAD

**Issue by dms1981** [hashicorp/terraform-provider-aws#35911]
### Terraform Core Version

1.7.2

### AWS Provider Version

5.38.0

### Affected Resource(s)

data.aws_subnet.*

### Expected Behavior

In Terraform `1.5` and below the `aws_subnet` data call could be fed with a `for_each` declaration and used to feed a resource through a separate `for_each`. In Terraform `1.6` and above this is no longer successful, and requires a targeted apply against the data calls to be executed, or a statically defined map to be supplied.

### Actual Behavior

`terraform plan` fails with message like so:
```
Invalid for_each argument
on main.tf line _x_, in data "aws_subnet" "example":
_x_: for_each = toset(data.aws_subnets.example.ids)
data.aws_subnets.example.ids is a list of string, known only after apply
```

### Terraform Configuration Files

```
data "aws_subnets" "example" {
  filter {
    name   = "vpc-id"
    values = [var.vpc_id]
  }
}

data "aws_subnet" "example" {
  for_each = toset(data.aws_subnets.example.ids)
  id       = each.key
}

resource "aws_ec2_tag" "subnets" {
  for_each = data.aws_subnet.example
  resource_id = each.value.id
  key         = "Name"
  value       = each.value.tags.Name
}
```

### Steps to Reproduce

Run a `terraform plan`.

### Important Factoids

With just three data calls - `aws_vpc`, `aws_subnets`, and `aws_subnet` - the data calls all execute successfully, but in Terraform `1.6` and above when `data.aws_subnet` is used to feed a for_each loop elsewhere, the plan does not complete.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dms1981 👋 Thank you for taking the time to raise this! I'm not certain this is something that would have been a result of any AWS Provider changes; was the Terraform version change the only difference in the configuration? I'd also be interested in how you're providing the value for `var.vpc_id` as well. Is that a static value?

**Comment by dms1981** [comment]
Hi @justinretzolk - the `var.vpc_id` ID was provided through a data call as the live used of this code was in a module. You can see the module [here](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/modules/ram-ec2-retagging/main.tf). It's called for each account we host, with the template [here](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/templates/modernisation-platform/subnet_share.tf#L25).

We tracked this is our repo as a bug [here](https://github.com/ministryofjustice/modernisation-platform/issues/6048).

**Comment by justinretzolk** [comment]
This may have been a result of [this change](https://github.com/hashicorp/terraform/blob/acb80b7745cf90f43391b4d45cfb1473e4c2efa2/CHANGELOG.md?plain=1#L97) mentioned in the Terraform Core changelog, but I can't be certain. Since this is related to how Terraform itself operates, you'd want to open an issue in the [Terraform Core repository](https://github.com/hashicorp/terraform) if you believe that the behavior is incorrect. 

For what it's worth, my read is that this is working as expected, and the issue you're seeing may be a result of the behavior noted in [Data Resource Behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior).
