### ISSUE TITLE
[Bug]: multiple aws_ecr_registry_policy overwrite each other

### ISSUE THREAD

**Issue by ArturZurawski** [hashicorp/terraform-provider-aws#35940]
### Terraform Core Version

1.6.3

### AWS Provider Version

5.37

### Affected Resource(s)

aws_ecr_registry_policy

### Expected Behavior

Create multiple Registry permissions

### Actual Behavior

Only one Registry permission is created and each TF run overwrites previously created policy 

### Terraform Configuration Files

.

### Steps to Reproduce

create multiple `aws_ecr_registry_policy` with different sids. Run TF multiple times

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
The underlying AWS API manages ECR registry policies as a singleton at the regional level. Although you can define multiple statements in the AWS Management Console, it's actually combining the statements into a single policy because sending the update request to the backend. Thus you should use only one `aws_ecr_registry_policy` per region and define all the statements you need in that single policy. I have submitted a PR to add a note/warning about this behavior.
