### ISSUE TITLE
[AWS SDK for Go Migration] Verified Access Service

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#36218]
### Description
To align with the dates described on #32976 the Verified Access Service requires migration to rely fully on [AWS SDK for Go v2](https://github.com/aws/aws-sdk-go-v2). This change should be mechanical in nature and not introduce any behavior changes.

The maintainer team will be working on these migrations but as always, help from the community is always appreciated. We would require passing acceptance tests for the entire set of resources being migrated. (We will also validate on review)

For further information about the migration, please see the parent issue #32976.

### Resources In Scope for Migration
```
"aws_verifiedaccess_endpoint"
"aws_verifiedaccess_group"
"aws_verifiedaccess_instance"
"aws_verifiedaccess_instance_logging_configuration"
"aws_verifiedaccess_instance_trust_provider_attachment"
"aws_verifiedaccess_trust_provider"
```

### Data Sources In Scope for Migration
```

```

### References

- #32976

**Comment by DanielRieske** [comment]
@breathingdust I believe we can close this issue, I double-checked them and all these resources have been created using SDKv2 since the start.

https://github.com/hashicorp/terraform-provider-aws/pull/33297
https://github.com/hashicorp/terraform-provider-aws/pull/33459
https://github.com/hashicorp/terraform-provider-aws/pull/33734
https://github.com/hashicorp/terraform-provider-aws/pull/33864
https://github.com/hashicorp/terraform-provider-aws/pull/34156

**Comment by johnsonaj** [comment]
Verified Access service is already on AWS SDKv2
