### ISSUE TITLE
[Bug]: Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by GomathiMa** [hashicorp/terraform-provider-aws#36302]
### Terraform Core Version

1.5.4

### AWS Provider Version

5.8

### Affected Resource(s)

aws_iam_policy_attachment

### Expected Behavior

No error for the first apply itself

### Actual Behavior

Terraform apply fails with below error for fist time.However it is successful second time. Every time, when we deploy any components,  this error pops up. 

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.ingest.aws_iam_policy_attachment.xx_role_policy_attachment,
│ provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Relevant Error/Panic Output Snippet

```shell
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.ingest.aws_iam_policy_attachment.xx_role_policy_attachment,
│ provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Terraform Configuration Files

      - uses: hashicorp/setup-terraform@v2
        name: Setup Terraform
        with:
          terraform_version: 1.5.4

### Steps to Reproduce

Create new s3 bucket policy and assign to a iam role and run the GitHub Actions to deploy the infrastructure for aws, above error pops up every time

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @GomathiMa 👋 Thank you for taking the time to raise this! Can you provide a Terraform configuration that can be used to reproduce this? If it's possible to supply them, debug logs (redacted as needed) are often helpful as well.

**Comment by GomathiMa** [comment]
We run terraform via GitHub Actions, we are currently using below version.
 - uses: hashicorp/setup-terraform@v2
    name: Setup Terraform
    with:
      terraform_version: 1.5.4

**Comment by justinretzolk** [comment]
@GomathiMa thanks for getting back to us. When I say "Terraform configuration" in this case, I'm referring more to a sample configuration of the resource in question that can be used to reproduce the issue. With this type of error, it's often necessary to know exactly how the resource is being used in order to understand why the error is occurring. Are you able to supply an example of an `aws_iam_policy_attachment` resource configuration that leads to the error?

[Debug logging](https://developer.hashicorp.com/terraform/internals/debugging) can also help when looking into errors like this, but we understand these aren't always easy to provide in a public forum like this.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
