### ISSUE TITLE
[Bug]: Terraform doesn't correctly reference a CloudWatch Log Group ARN

### ISSUE THREAD

**Issue by garysassano** [hashicorp/terraform-provider-aws#36678]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.43.0

### Affected Resource(s)

* `aws_cloudwatch_log_group`

### Expected Behavior

I expected Terraform to follow the ARN standard nomenclature, the same used also by AWS Console and CloudFormation.

### Actual Behavior

Terraform doesn't correctly reference a CloudWatch Log Group ARN since it doesn't include the `:*` which is part of the ARN.

### Terraform Configuration Files

See [here](https://github.com/hashicorp/terraform-provider-aws/issues/22957#issuecomment-2030470781)

### Steps to Reproduce

See [here](https://github.com/hashicorp/terraform-provider-aws/issues/22957#issuecomment-2030470781)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @garysassano 👋 Thank you you for taking the time to raise this! According to the [AWS documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html#CWL_ARN_Format), log groups have two formats for their ARNs -- with and without the `:*`. The trimmed version is used for most APIs, and is the more consistent format with other parts of the provider, so with version 3 of the provider, a decision was made to automatically trim the `:*`.

 This was discussed more in depth by the engineer who implemented the change in [this comment](https://github.com/hashicorp/terraform-provider-aws/pull/14214#issuecomment-669304936) on the pull request that introduced the changes, and is [documented](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#arn) in the provider documentation:

> Any `:*` suffix added by the API, denoting all CloudWatch Log Streams under the CloudWatch Log Group, is removed for greater compatibility with other AWS services that do not accept the suffix.

With that information in mind, and that the `:*` can be re-added via interpolation, I'll be closing this issue as this is expected behavior.
