### ISSUE TITLE
[Bug]: EKS Access Entries have non-functional drift detection; apply errors

### ISSUE THREAD

**Issue by joshuaking-madtech** [hashicorp/terraform-provider-aws#36742]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.44.0

### Affected Resource(s)

aws_eks_access_entry
aws_eks_access_policy_association

### Expected Behavior

When a change is made out of band to access entries, the drift should be detected and the state updated correctly.

This scenario is particularly troublesome as it exactly captures "let me make a quick change to access manually and PR in the same change in TF when I get a moment"

### Actual Behavior

Terraform provider is oblivious to access entries added outside terraform.  It will attempt to create again existing entries.  The initial/default access entry for the terraform service account has additional odd behavior around drift.

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating EKS Access Entry (access-entry-bug-test:arn:aws:iam::<snip>:user/test_user_2_eks_access_entry_bug_report): operation error EKS: CreateAccessEntry, https response error StatusCode: 409, RequestID: ac2d3975-809d-4611-a6e0-caa7f1f1ff08, ResourceInUseException: The specified access entry resource is already in use on this cluster.
│ 
│   with aws_eks_access_entry.access-entry3,
│   on eks-cluster-access-entries.tf line 43, in resource "aws_eks_access_entry" "access-entry3":
│   43: resource "aws_eks_access_entry" "access-entry3" {
```

### Terraform Configuration Files

eks-cluster.tf will spin up a fairly minimal EKS cluster on 2 t3a.small instances, including a VPC
eks-cluster-access-entries.tf includes the IAM users and access entries under test
Adjust local variables as needed to avoid IP overlap and ensure you can administrate the cluster normally, including through the AWS console
Standing up the cluster for the first time is expected to take 10-20 minutes.   Cluster will be made in us-east-2 unless changed
[eks-access-entry-bug-report.zip](https://github.com/hashicorp/terraform-provider-aws/files/14878838/eks-access-entry-bug-report.zip)

### Steps to Reproduce

- Terraform apply; ensure the cluster starts normally and you can access
  - State: first and second users added, third not created (commented out)
- Make the manual edits as specified in eks-cluster-access-entries.tf
  - State: first and third users exist; you made the 3rd user access entry and deleted the 2nd through AWS console
- Terraform apply again
  - Result: Second user is re-created, drift not detected on the added 3rd user
- Uncomment 3rd user; terraform apply again
  - Result: Plan attempts to add the 3rd user again; apply errors with the output logged

### Important Factoids

Cluster and VPC both created with these popular modules:
"terraform-aws-modules/vpc/aws"
"terraform-aws-modules/eks/aws"
This is otherwise straight out of the official docs

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @joshuaking-madtech 👋 Thank you for taking the time to raise this, and for providing such detailed reproduction notes. 

You mentioned that you added the 3rd user manually via the AWS console and then uncommented that section of the Terraform configuration, at which point you received an error on the next apply. After uncommenting the section of the configuration, did you import `aws_eks_access_entry.access-entry3` and `aws_eks_access_policy_association.policy-association3` before attempting the next `apply`? If they weren't imported, I'd expect Terraform to attempt to create those resources again, since they're not tracked in Terraform's state.

I'm not sure I follow you with regards to the oddities with the second user. Am I correct that after deleting the user via the console, you saw the user recreated on the next `terraform apply`? That's the behavior that I'd expect from Terraform, since the resource was still present in the configuration.

**Comment by joshuaking-madtech** [comment]
> Hey @joshuaking-madtech 👋 Thank you for taking the time to raise this, and for providing such detailed reproduction notes.
> 
> You mentioned that you added the 3rd user manually via the AWS console and then uncommented that section of the Terraform configuration, at which point you received an error on the next apply. After uncommenting the section of the configuration, did you import `aws_eks_access_entry.access-entry3` and `aws_eks_access_policy_association.policy-association3` before attempting the next `apply`? If they weren't imported, I'd expect Terraform to attempt to create those resources again, since they're not tracked in Terraform's state.
> 
> I'm not sure I follow you with regards to the oddities with the second user. Am I correct that after deleting the user via the console, you saw the user recreated on the next `terraform apply`? That's the behavior that I'd expect from Terraform, since the resource was still present in the configuration.

Yep, all broadly correct.  I had not done anything with the import commands.  Nothing odd with the second user - I had seen some oddness there that made me test it but couldn't reproduce (presumably either user error and/or fixed in prior update).

Where this is seeming like a bug to me is that the config drift isn't being identified at all.  E.g. that middle apply should have suggested removing the 3rd user's entry that isn't defined, and/or at least pointed out that the running state isn't the defined state.

Worth noting that the access entries are enforced 1:1 with user principles; it's always an error to add another entry for an existing ARN.

**Comment by justinretzolk** [comment]
> that middle apply should have suggested removing the 3rd user's entry that isn't defined, and/or at least pointed out that the running state isn't the defined state.

The `aws_eks_access_entry` resource pertains to a singular access entry, and so unless the state contains information about a particular access entry, Terraform won't "know" about it. That information would only be in the state if Terraform created the resource, or it was imported into the state.

Since the 3rd user's access entry wasn't created by Terraform, hasn't been imported, and isn't in the configuration, Terraform has no knowledge of its existence, and won't attempt to manage it in any way. Similarly, with regards to your original report, attempting to add the configuration for the 3rd user without importing the resource would report in errors, since the resource already exists.

**Comment by justinretzolk** [comment]
Since we haven't heard back here, and this looks to be behaving as I would expect, I'm going to close this issue. If you have any further issues, please do let us know!
