### ISSUE TITLE
[Enhancement]: Tagging support for `aws_iot_authorizer`

### ISSUE THREAD

**Issue by PeterBurner** [hashicorp/terraform-provider-aws#36834]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.44.0

### Affected Resource(s)

* `aws_iot_authorizer`

### Expected Behavior

Resource block should accept `tags` property.

### Actual Behavior

Resource block does not accept `tags` property.

### Relevant Error/Panic Output Snippet

```shell
│ Error: Unsupported argument
│ 
│   on main.tf line 115, in resource "aws_iot_authorizer" "this":
│  115:   tags = {
│ 
│ An argument named "tags" is not expected here.
```

### Terraform Configuration Files

```hcl
resource "aws_iot_authorizer" "this" {
  authorizer_function_arn = module.custom_authorizer.lambda_function_arn
  enable_caching_for_http = true
  name                    = "authorizer"
  signing_disabled        = true
  status                  = "ACTIVE"

  tags = { test = "blaaa" }
}
```

### Steps to Reproduce

1. Add `tags` property to resource block
2. Run `terraform plan`

### References

 - https://docs.aws.amazon.com/iot/latest/apireference/API_CreateAuthorizer.html#API_CreateAuthorizer_RequestSyntax

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @PeterBurner 👋 Thanks for taking the time to raise this! We consider additions to existing resources to be an enhancement, rather than a bug. With that in mind, I'm going to update a few things about this issue. There's no further action needed from you at this point, I just like to let people know before making these kinds of modifications.

**Comment by DanielRieske** [comment]
👋 I'll gladly pick this up as part of the IOT SDKv2 migration.
