### ISSUE TITLE
[Enhancement]: Argument for Replication starting position in `aws_msk_replicator`

### ISSUE THREAD

**Issue by michaelgeorgeattard** [hashicorp/terraform-provider-aws#36850]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.44.0

### Affected Resource(s)

aws_msk_replicator

### Expected Behavior

We are expecting the ability to customize *Replication starting position*, either EARLIEST or LATEST

### Actual Behavior

*Replication starting position* value is not overridable, forcing and defaulting the value to LATEST

### Terraform Configuration Files

N/A

### Steps to Reproduce

N/A

### Would you like to implement a fix?

None

![image](https://github.com/hashicorp/terraform-provider-aws/assets/5755302/4f197512-04f1-4437-96c2-b67bf2bbb1ad)

**Comment by justinretzolk** [comment]
Hey @michaelahern 👋 Thanks for taking the time to raise this! We consider additions to existing resources (like adding an argument for specifying the starting position) to be an enhancement, rather than a bug. With that in mind, I'm going to update a few things about this issue. There's no further action needed from you at this point, I just like to let people know before making these kinds of modifications.

**Comment by michaelgeorgeattard** [comment]
Hi @justinretzolk is there a plan to merge the PR that is adding this enhancement?
