### ISSUE TITLE
[Enhancement]: Add 'Egress_Only_Internet_Gateway_ID' to 'aws_route_table_associationa' Resource

### ISSUE THREAD

**Issue by bwright86** [hashicorp/terraform-provider-aws#37005]
### Description

It appears the Route Table Association resource isn't able to accept Egress-Only Internet Gateway ID's. This is an issue if the EIGW is created after the VPC/Route Tables are created. It would be helpful to be able to add an EIGW to an existing Route Table.

### Affected Resource(s) and/or Data Source(s)

'aws_route_table_association' Resource

### Potential Terraform Configuration

```terraform
resource "aws_egress_only_internet_gateway" "example" {
  vpc_id = data.terraform_remote_state.vpc.outputs.id
}

resource "aws_route_table_association" "example" {
  for_each = toset(data.terraform_remote_state.vpc.outputs.route_table_ids)

  egress_gateway_id = aws_egress_only_internet_gateway.example.id
  route_table_id = each.value
}
```

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
I could be wrong, but I don't think you can associate a route table to an EIGW (via edge association). This is by design because there is no traffic going in from the internet to the EIGW. I checked the AWS Management Console and it is not doable.

The only thing you can do is to create routes to the EIGW in a route table that gets associated with a subnet. In Terraform that is done with the [`egress_only_gateway_id` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/route#egress_only_gateway_id) of the `aws_route` resource.

**Comment by bwright86** [comment]
Thanks for the input on this. You might be correct, and using the `aws_route` resource would allow associating an EIGW after the route table is created. Let me confirm this on Monday, and I’ll close this issue.

Also, I noticed thru the console that there are other options to add resources into a route table, it seems `aws_route` resource handles those as well. So this may fill in my knowledge gap on this :-)

**Comment by justinretzolk** [comment]
Since we haven't heard back, I think it's a safe assumption that Anthony's comment did the trick 🙂. With that in mind, I'm going to go ahead and close this issue.
