### ISSUE TITLE
[Enhancement]: Missing ServiceDiscovery for IPPreference for AWS Appmesh Mesh Object

### ISSUE THREAD

**Issue by kangsheng89** [hashicorp/terraform-provider-aws#37034]
### Terraform Core Version

0.13

### AWS Provider Version

5.46.0

### Affected Resource(s)

aws_appmesh_mesh

### Expected Behavior

support for service discovery ip preference object

### Actual Behavior

missing service discovery ip preference object

### Terraform Configuration Files

NA

### Steps to Reproduce

NA

### References

Below is the AWS API for Mesh related object
https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_CreateMesh.html
https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_DescribeMesh.html
https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_UpdateMesh.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @kangsheng89 👋 Thanks for taking the time to raise this! We consider additions to existing resources to be an enhancement, rather than a bug. With that in mind, I'm going to update a few things about this issue. There's no further action needed from you at this point, I just like to let people know before making these kinds of modifications.
