### ISSUE TITLE
[Enhancement]: Provide possibility to use lambda version in aws_api_gateway_integration

### ISSUE THREAD

**Issue by ekropotkin** [hashicorp/terraform-provider-aws#37083]
### Description

In resource "aws_api_gateway_integration" we can't use lambda version

this works fine:
uri = "${aws_lambda_function.postdata.invoke_arn}"

uri to lambda version - this not works, but it's valid:
uri = "${aws_lambda_function.postdata.invoke_arn}:3"

### Affected Resource(s) and/or Data Source(s)

aws v4.67.0

### Potential Terraform Configuration

```terraform
resource "aws_api_gateway_integration" "post" {
  rest_api_id = aws_api_gateway_rest_api.api.id
  resource_id = aws_api_gateway_resource.res.id
  http_method = aws_api_gateway_method.res-post.http_method
  type        = "AWS_PROXY"

  integration_http_method = "POST"
  uri                     = "${aws_lambda_function.test.invoke_arn}:4"
  timeout_milliseconds    = 29000
}
```

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
@ekropotkin 

>uri to lambda version - this not works, but it's valid:
uri = "${aws_lambda_function.postdata.invoke_arn}:3"

This is probably incorrect because `invoke_arn` from `aws_lambda_function` is not the same format as the function ARN. Here is an example from the state when I load one of my existing functions using the `aws_lambda_function` data source:

```
"invoke_arn": "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:action-group-quick-start-ha7di-i3nhk/invocations",
```

You can try appending the version before `/invocations`, or use and alias with `aws_lambda_alias`. The latter's data source also provides the proper `invoke_arn` value - see example for the "beta" alias I created for the same function:

```
"invoke_arn": "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:action-group-quick-start-ha7di-i3nhk:beta/invocations",
```

Please test the above and report back on the results. Thanks.

**Comment by ekropotkin** [comment]
So, it's only way to use external script for lambda versions?

**Comment by justinretzolk** [comment]
Hey @ekropotkin 👋 I think what @acwwat was getting at is that you could use the [`aws_lambda_alias` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_alias), which has an `invoke_arn` attribute that can be used for `aws_api_gateway_integration.uri`, or that you may be able to do some string interpolation to construct the ARN appropriately. This should be possible using the provider as it is, with not external scripts.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
