### ISSUE TITLE
[Bug]: Dedicated Mac hosts take 1hr timeout to give back an insufficient capacity error

### ISSUE THREAD

**Issue by bengaywins** [hashicorp/terraform-provider-aws#37137]
### Terraform Core Version

1.7.x

### AWS Provider Version

5.46.0

### Affected Resource(s)

* aws_ec2_host

### Expected Behavior

Terraform to bail out faster than the 1hr timeout when getting this error.

### Actual Behavior

Terraform takes 1hr to timeout and fail

### Relevant Error/Panic Output Snippet

```shell
│ Error: allocating EC2 Host: InsufficientHostCapacity: Insufficient capacity.
│ 	status code: 500, request id: 55adceb6-08ae-4141-9117-f097ead92b91
```

### Terraform Configuration Files

```hcp
resource "aws_ec2_host" "this" {
  availability_zone = "us-west-2"
  instance_type     = "mac2.metal"
}
```

### Steps to Reproduce

1. Try to create a dedicated host in AWS via Terraform that has no capacity in the Oregon region. Example: mac2.metal

### Important Factoids

Context: AWS has soft-deprecated mac2.metal dedicated hosts (but not told anyone). Once capacity is exhausted, that's all that's available. The console gives an _immediate_ `no capacity` error.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @bengaywins 👋 Thank you for taking the time to raise this! I saw this issue while triaging and wonder if adding a [`timeout` configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_host#timeouts) might help in your case.

**Comment by bengaywins** [comment]
Hey @justinretzolk! While that would technically work, to me that's hacky. I am aware of these timeout configuration abilities, but I generally prefer to avoid them for maintenance burden reasons. I _have_ had to use them in the past in these kinds of situations, and found that neither anyone on my team nor myself remembers to come back for it. Sure we could create an internal ticket, but testing this is always hard months/years later after you maybe can't even spin up that instance type anymore.

**Comment by justinretzolk** [comment]
Hey @bengaywins 👋 Thanks for the additional information! Our goal is to match the underlying API as closely as possible, so that the AWS Provider matches the experience of directly interacting with the API, or using the CLI or other tools. In an attempt to adhere to that standard, we generally avoid adding code that would alter that behavior in ways that would be unexpected (even if I do agree with where you're coming from in this case). With that and the ability to use custom timeouts in mind, I'm going to close this issue as "expected behavior".

I haven't tested this to validate that it works, but a thought that came to mind was the idea of using a `dynamic` block to set timeouts only when `mac2.metal` are used. Ideally that'd make circling back to it a non-issue.

**Comment by bengaywins** [comment]
@justinretzolk The thing is, if I ctrl+c out of it, _it spits out the error_ that there's no capacity. So this does not feel like it's related to the API not acting the way you describe. I don't think this should be closed as complete.
