### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by prowlaiii** [hashicorp/terraform-provider-aws#38029]
### Description

I often use a `for_each` statement as an "if" to conditionally deploy resources or modules based on feature flags or other options, but then each resource when its used needs to be presented as if it had an iterator  eg. `my_resource["yes"]`.
Would it be possible to implement an "if" operator instead, which would make the code more readable and also remove the pseudo iterator from calls to it (and also terraform output).
Something like:
`deploy_if = <condition>`
rather than:
`for_each = <condition> ? {deploy="yes"} : {}`
or:
`count = <condition> ? 1 : 0`

### Affected Resource(s) and/or Data Source(s)

(none)

### Potential Terraform Configuration

```terraform
resource "xxxxxx" "my_blah" {
   deploy_if = var.options.i_want_my_blah
   .....
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @prowlaiii 👋 Thank you for taking the time to raise this! For changes to how Terraform operates at its core, you'll want to open a feature request in the [Terraform Core repository](https://github.com/hashicorp/terraform), rather than at the AWS provider level (this repository). With that in mind, I'm going to close this issue.
