### ISSUE TITLE
[Enhancement]: Terraform can not destroy resouce when switched to another aws provider

### ISSUE THREAD

**Issue by magzim21** [hashicorp/terraform-provider-aws#38079]
### Description

Resource X was created with A provider.
If switch provider on this resource to B provider, terraform fails to access delete this resource with error `AccessDenied` though both providers are defined.

```hcl
resource "aws_iam_openid_connect_provider" "github" {
  provider = aws.shared-services #  it was aws.infrastructure
  url      = "https://token.actions.githubusercontent.com" # tokens issuer

  client_id_list = [
    "sts.amazonaws.com",
  ]

  thumbprint_list = [data.tls_certificate.github.certificates[0].sha1_fingerprint]
}

```
```
╷
│ Error: reading IAM OIDC Provider (arn:aws:iam::905418406112:oidc-provider/token.actions.githubusercontent.com): operation error IAM: GetOpenIDConnectProvider, https response error StatusCode: 403, RequestID: 11c4cdf4-ed6f-417c-b216-81b1d3bd7662, api error AccessDenied: User: arn:aws:sts::339712874042:assumed-role/OrganizationAccountAccessRole/aws-go-sdk-1719095981366631788 is not authorized to access this resource
│
│   with aws_iam_openid_connect_provider.github,
│   on aws-infra-iam-gh-oidc.tf line 6, in resource "aws_iam_openid_connect_provider" "github":
│    6: resource "aws_iam_openid_connect_provider" "github" {
│
╵
```
As a result, I have to delete a resource, by commenting it and only then apply with a new provider.
### Affected Resource(s) and/or Data Source(s)

Seems like all resources are affected. 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @magzim21 👋 Thank you for taking the time to raise this! Based on the error, the issue in this case is that the credentials supplied to the new instantiation of the provider don't have access to read the resource that you're attempting to manage:

> │ Error: reading IAM OIDC Provider (<arn>): operation error IAM: **GetOpenIDConnectProvider**, https response error StatusCode: 403, <omitted>, api error **AccessDenied: User: <assumed_role> is not authorized to access this resource**

Outside of that I believe this should work, but if it didn't, it would be a limitation of Terraform Core. With that in mind, since there's no action for the AWS Provider team to take, I'm going to close this issue. If you run into issues in the future, please do let us know!

**Comment by magzim21** [comment]
This is not a permissions error. This is a provider switch. Both providers are functional with their credentials.
