### ISSUE TITLE
[Enhancement]: `aws_codebuild_webhook` - Add `scope_configuration` property

### ISSUE THREAD

**Issue by garysassano** [hashicorp/terraform-provider-aws#38091]
### Terraform Core Version

1.8.5

### AWS Provider Version

5.55.0

### Affected Resource(s)

- `aws_codebuild_webhook`

### Expected Behavior

An equivalent to `ScopeConfiguration` of [this CloudFormation template](https://docs.aws.amazon.com/codebuild/latest/userguide/github-global-organization-webhook.html#github-organization-webhook-events-cfn).

### Actual Behavior

No way to configure the scope.

### Terraform Configuration Files

see above

### Steps to Reproduce

see above

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @garysassano 👋 Thanks for taking the time to raise this! We consider additions to existing resources to be an enhancement, rather than a bug. With that in mind, I'm going to update a few things about this issue. There's no further action needed from you at this point, I just like to let people know before making these kinds of modifications.
