### ISSUE TITLE
[Bug]: Investigate why IMDSv2 are required if Ubuntu 24.04 is run on aws_instance

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#38294]
### Terraform Core Version

v1.8.5

### AWS Provider Version

v5.55.0

### Affected Resource(s)

* aws_instance

### Expected Behavior

IMDSv2 should be optional:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#http_tokens

### Actual Behavior

It was switched to required.

More details:
https://github.com/hashicorp/consul/issues/21525#issuecomment-2215433543

### Terraform Configuration Files

n/a

### Steps to Reproduce

Run EC2 instance with installed Ubuntu 24.04 instead of 22.04

### Would you like to implement a fix?

None

**Comment by EugenKon** [comment]
So when no value is explicitly provided then instance is deployed with `required` value for Ubuntu 24.04 type of instance. 
![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/b145cec2-a44e-423e-8a5d-fd7d88d6ea2d)

Though it is still deployed with `optional` as documented for 22.04 type of instance.

If it is configured to use `optional`:
```
  metadata_options {
    http_tokens            = "optional"
  }
```
Then plan looks like next:
```
  # module.private-cloud.aws_instance.server[0] will be updated in-place
  ~ resource "aws_instance" "server" {
        id                                   = "i-x"
        tags                                 = {
            "ConsulAutoJoin" = "nomad-auto-join"
            "Name"           = "nomad-server-0"
            "NomadType"      = "server"
        }
        # (40 unchanged attributes hidden)

      ~ metadata_options {
          ~ http_tokens                 = "required" -> "optional"
            # (4 unchanged attributes hidden)
        }

        # (7 unchanged blocks hidden)
    }
```

This should be fixed to use "optional" value for any types of instances as documented.

**Comment by justinretzolk** [comment]
Hey @EugenKon 👋 Thank you for taking the time to raise this! It looks like the [`http_tokens` argument](https://github.com/hashicorp/terraform-provider-aws/blob/28e7f1bd3e84dcccfe6f2146c76908c1eb97527d/internal/service/ec2/ec2_instance.go#L568-L573) is both `Computed` and `Optional` (in the provider schema), which means that if it's not provided in the configuration, it gets set to whatever is in the response from the API. 

With that in mind, it sounds like this should be a documentation fix, where we either remove the mention of a default, or update it if what the API returns by default has changed. I'm of the mind that we should remove the mention of a default value because a default value is not being set at the schema level, and what's being returned from AWS by default seems to be inconsistent. Does that seem like the right course of action to you?

**Comment by EugenKon** [comment]
Yep, we could remove the mention about `default`. But it worth to add that the value could depend on AMI version (response from AWS API). I suppose the documentation should recommend to configure that option explicitly to escape problems.

**Comment by stefanfreitag** [comment]
Hi @justinretzolk, hi @EugenKon, let me have look into updating the docs.
