### ISSUE TITLE
[Bug]: Terraform creates default VPC but does not destroy it when cluster is destroyed

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#38359]
### Terraform Core Version

v1.8.5

### AWS Provider Version

v5.55.0

### Affected Resource(s)

* aws_ default VPC

### Expected Behavior

When the region does not have any resource (in this case VPC) and a new cluster was created and destroyed, then all automatically created resource should be destroyed as well.

### Actual Behavior

After destroying a cluster it still has artifacts: default VPC, default SG and networks.

### Terraform Configuration Files

No errors happened

### Steps to Reproduce

1. Create a cluster with one EC2 instance
2. Destroy a cluster
3. No resources should left

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @EugenKon 👋 Thank you for taking the time to raise this! In scenarios like this, where AWS automatically creates additional resources when Terraform is creating something, there's not currently a way for Terraform to automatically adopt those into the state as well. You could adopt it into the state separately, but I imagine this is something that [Terraform Stacks](https://www.hashicorp.com/blog/terraform-stacks-explained) could help with as well.

Since this isn't something the AWS Provider team would be able to address, I'm going to close this issue for now.
