### ISSUE TITLE
[Enhancement]: Disable Secret Manager's Rotation Schedule by Default When Enabling manage_master_user_password for RDS

### ISSUE THREAD

**Issue by morisekntr** [hashicorp/terraform-provider-aws#38433]
### Description

Hello,

I have learned that when creating RDS instances with Terraform and enabling manage_master_user_password, the master password is automatically managed by Secret Manager without being stored in the tfstate file.

However, the password in Secret Manager has its rotation schedule automatically enabled. This automatic rotation schedule is critical for us, as we handle a PHP-based monolithic web application, and we would prefer to have it disabled by default.

Thank you for your consideration.

### Affected Resource(s) and/or Data Source(s)

* aws_db_instance
* aws_rds_cluster
* aws_secretsmanager_secret_rotation

### Potential Terraform Configuration

```terraform
resource "aws_db_instance" "example" {
  manage_master_user_password = true
  secretsmanager_secret_rotation = false   ## default: true
}
```

OR

```
resource "aws_db_instance" "example" {
  manage_master_user_password = true
}

resource "aws_secretsmanager_secret_rotation" "example" {
  secret_id = aws_db_instance.example.master_user_secret[0].secret_arn
  automatically_secret_rotation = false  ## default: true
}
```
```


### References

_No response_

### Would you like to implement a fix?

None

**Comment by aristosvo** [comment]
Hi @morisekntr 👋! 

Fellow DevOps engineer here, I understand your use case. 

Unfortunately this is not something the AWS provider for Terraform can help you with, as the provider is _just_ using the APIs of AWS, and they don't offer the functionality to stop the rotation.

At the same time it is a best practice to have a specific user for your application, instead of using the root user directly. In your case I'd look into that and how to solve that instead of expecting the functionality from the AWS provider.

**Comment by justinretzolk** [comment]
With the above in mind, and that it looks like there's already an existing issue tracking this request (#33462), I'm going to close this issue. If you have any additional requests in the future, please do reach out and let us know!
