### ISSUE TITLE
[Enhancement]: Change `Computed` behavior of `aws_route53_zone` data source

### ISSUE THREAD

**Issue by bombard1004** [hashicorp/terraform-provider-aws#38500]
### Description

I propose changing the `Computed` behavior of the `aws_route53_zone` data source. Here are the details and rationale for this change:

- **Current Behavior**: The `zone_id` (or `name`) attribute is marked as `computed`, meaning it is only known after the `apply` stage.
- **Proposed Change**: Set `Computed: false` for every attribute, making it known during the `plan` stage.

**Rationale**:
1. **Usage Context**: When using this data source, we often want to retrieve information about an existing hosted zone without managing it through Terraform. Since this is a simple lookup of an existing hosted zone, the value should not change during the `apply` stage.
2. **Common Issue**: Many users have reported issues where Route 53 records are unnecessarily recreated. This is due to `zone_id` being `known after apply`, which forces replacement even when there are no actual changes to the Route 53 configuration.
3. **Impact on Service Availability**: Unnecessary recreation of Route 53 records can lead to significant service availability issues. This makes it difficult to adopt Terraform more broadly for infrastructure management.

**Benefits**:
- **Consistency**: Ensures that `zone_id` (or `name`) is known at the `plan` stage, avoiding unnecessary resource replacements.
- **Stability**: Prevents unnecessary deletions and recreations of Route 53 records, thereby improving service stability and availability.
- **Adoption**: Makes it easier and more reliable to use Terraform for managing AWS infrastructure, encouraging broader adoption.

If there are any aspects I may have overlooked, I would appreciate your feedback. Thank you for considering this change.

### Affected Resource(s) and/or Data Source(s)

* aws_route53_zone

### References

#24467 
#64

### Would you like to implement a fix?

Yes

**Comment by bombard1004** [comment]
After conducting further research, I realized that the Computed behavior in Terraform does not indicate that a value is unknown during the plan stage, but rather that it applies to all attributes not provided as input. Therefore, the approach of disabling Computed as proposed in this PR may not be applicable.

I believe there should be a distinction between attributes that can be determined at the plan stage and those that cannot. In this case, attributes like zone_id and name should belong to the former category.

If my understanding is incorrect, I would greatly appreciate any corrections. Thank you for your consideration.

**Comment by justinretzolk** [comment]
Hey @bombard1004 👋 Thank you for taking the time to raise this! I'm not sure that changing the data source's attributes to `Computed: false` would make sense -- data sources are inherently mostly `Computed` values, since they're used to retrieve otherwise unknown data.

With that said, some of what you're describing leads me to believe you might be running into the specifics described in [Data Sources: Data Resource Behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior). Terraform will read data sources during the `plan` stage where possible, however, sometimes that read must be delayed until `apply` time (for the reasons described in the aforementioned article). I've often seen this lead to undesired recreation of resources, but it's something that can be worked around with configuration changes.

Since this isn't something the provider team will need to make changes for, I'm going to close this issue. If you have additional questions around the data resource behaviors I mentioned, I'd recommend starting a new topic in the [Terraform community forum](https://discuss.hashicorp.com/c/terraform-core/27). If you believe something is behaving incorrectly with regards to those data sources, you'd want to open a new issue in the [Terraform Core repository](https://github.com/hashicorp/terraform).
