### ISSUE TITLE
[Enhancement]: Add support for G.8X worker type for Glue 4.0

### ISSUE THREAD

**Issue by nexusmike** [hashicorp/terraform-provider-aws#38594]
### Description

Please add support for building out 4.0 Glue jobs of all worker types G.4X and G.8X through terraform. You can choose these options through the ui but the terraform scripts fail for Glue 4.0

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
Hi @nexusmike 👋, thanks for raising this issue!

What release of the provider are you running? We recently migrated Glue to use the `aws-sdk-go-v2` which was released in [`v.5.60.0`](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.60.0)

Could you try upgrading your provider version and otherwise send a snippet of the code and error response giving you this issue?

I'll gladly take a look for you.

**Comment by stefanfreitag** [comment]
Hi @nexusmike , hi @DanielRieske ,
I was looking into the code base and the `worker_type` is defined [here](https://github.com/hashicorp/terraform-provider-aws/blob/9503f324a77b1b690b441b8ed5a9c2c8c6a6301f/internal/service/glue/job.go#L188). There is a validation in place .
```go
ValidateDiagFunc: enum.Validate[awstypes.WorkerType](),
```
with `awstypes.WorkerType` resolving to 

```go
func (WorkerType) Values() []WorkerType {
	return []WorkerType{
		"Standard",
		"G.1X",
		"G.2X",
		"G.025X",
		"G.4X",
		"G.8X",
		"Z.2X",
	}
}
```
As Daniel recommended an upgrade of the AWS provider is something you could try out. Feel free to update your description with provider version in use and the error messages you are seeing.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
