### ISSUE TITLE
[New Resource]: Manage OpenSearch Role and Role Mapping With Terraform

### ISSUE THREAD

**Issue by santoshugale** [hashicorp/terraform-provider-aws#38700]
### Description

As of now, if we want to add the role and role mapping in aws open search, we must utilize the API or open search dashoboard.
Please consider adding the ability to add the role and role mapping using Terraform.

The OpenSearch Terraform provider has similar functionality, as shown at https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/role.

### Requested Resource(s) and/or Data Source(s)

1. opensearch_role
2. opensearch_roles_mapping 

### Affected Service
1. service/opensearch

### References

The OpenSearch Terraform provider has similar functionality, as shown at 
https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/role
https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/roles_mapping

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @santoshugale 👋 Thank you for taking the time to raise this! At this time neither the older [AWS Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/opensearchservice/) nor the newer [AWS Go SDK v2](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch) offer methods for managing the role/role mapping within OpenSearch. Since this isn't offered by the AWS SDK/API itself, we'll not be able to add it to the provider at this time. If that changes in the future, we'd be happy to take another look. In the meantime, the [OpenSearch provider](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs) that you linked to will be the best option, as it supports OpenSearch on AWS:

> AWS OpenSearch Service domains and OpenSearch clusters deployed on Kubernetes and other infrastructure are supported.

With that in mind, I'm going to close this issue. If you have additional suggestions in the future, please do let us know!
