### ISSUE TITLE
[New]: bedrock guardrail version

### ISSUE THREAD

**Issue by sasidhar-aws** [hashicorp/terraform-provider-aws#38853]
### Description

Guardrails for Amazon Bedrock supports versions.

New Resource(s)

aws_bedrock_guardrail_version

### Requested Resource(s) and/or Data Source(s)

* aws_bedrock_guardrail_version

### References

https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-versions-create-manage.html

### Would you like to implement a fix?

Yes

**Comment by sasidhar-aws** [comment]
I will work on this issue.

**Comment by acwwat** [comment]
@sasidhar-aws Are you still working on this new resource? If not, I don't mind working on it since I have a need.

I am doing some testing with the AWS CC Provider meanwhile and recognize that this resource likely needs a `skip_destroy` attribute to prevent the previous version to be deleted while a new version is created. Otherwise it defeats the purpose of versioning guardrails.

**Comment by sasidhar-aws** [comment]
Yes, I have PR almost ready, need to write unit tests. Not able to complete with other commitments. Will try to pick next week.
