### ISSUE TITLE
[Enhancement]: Cleanup dangling ENIs on EKS Cluster Deletion

### ISSUE THREAD

**Issue by dgr237** [hashicorp/terraform-provider-aws#38887]
### Description

When terraform destroys the AWS VPC CNI Addon there are occasions where the vpc cni does not correctly delete the secondary ENIs which it creates. It is noted that in EKSCTL has functionality to do this as part of cluster deletion and this enhancement would do something similar on cluster deletion.

### Affected Resource(s) and/or Data Source(s)

* aws_eks_cluster

### Potential Terraform Configuration

```terraform
resource "aws_eks_cluster" "cluster" {
  on_destroy_delete_dangling_ec2_enis = true
}
```

### Would you like to implement a fix?

Yes

**Comment by dgr237** [comment]
I know the VPC CNI has this logic but in v1.18.3 of the VPC CNI we are still seeing ENIs left dangling (we have a ticket open with AWS Support on this issue). This appears to be an issue with either the vpc cni not cleaning up the dangling ENIs before terminating or the eks addon resource returning successfully before all instances of the vpc cni have terminated.
 
In the module we have developed we are seeing this issue even when we do not provision any resources with Helm. We are seeing this issue when we have just provisioned the EKS Cluster, Self managed node group (Launch Template & Autoscaling Group) and the 4 core EKS Addons (VPC CNI, KubeProxy, CoreDns & Pod Identity Agent).
 
We have in debugging this issue rolled VPC CNI back to v1.16.0 and we see the dangling ENI issue significantly less (in 10 runs we saw this occur once) compared to 1 in 3 runs using v1.18.3.  We have additional tested using Cilium as the primary CNI and not enabled the Addons by default and have never seen this issue.
 
We have therefore a limited number of options to resolve this issue:
 
1)        Add the functionality into the terraform provider to enable the deletion of the dangling ENIs (This brings the terraform implementation in line with the EKS CTL implementation: https://github.com/eksctl-io/eksctl/blob/fc24e94034492faeda18c43e17fade077c2ff090/pkg/vpc/cleanup.go#L70-L85). This functionality is feature flagged and so is not enabled by default. The lookup of the ENIs is written in a way to target only those ENIs which are created by the VPC CNI.
2)        Rollback to a very old version of the vpc cni. This is not recommended by AWS, will mean we can’t leverage new features release to the vpc cni and be in break of our corporate policy about leveraging components which are not the latest.
3)        Replace the VPC CNI with an alternative CNI e.g. Cilium

**Comment by bryantbiggs** [comment]
> This appears to be an issue with either the vpc cni not cleaning up the dangling ENIs before terminating or the eks addon resource returning successfully before all instances of the vpc cni have terminated.
> 
> In the module we have developed we are seeing this issue even when we do not provision any resources with Helm. We are seeing this issue when we have just provisioned the EKS Cluster, Self managed node group (Launch Template & Autoscaling Group) and the 4 core EKS Addons (VPC CNI, KubeProxy, CoreDns & Pod Identity Agent).

This sounds like you have developed a custom Terraform module that you are potentially creating/destroying in quick sucession - perhaps this is automated as part of a continuous integration process. In those scenarios, I would encourage you to set [`preserve = true`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon#preserve) on the VPC CNI addon to ensure you give it time to clean-up its resources. 

Since there are usually no dependencies on the VPC CNI addon resource, when Terraform performs a destroy, it will remove this resource quite early in the destroy process. In conjunction - Terraform is not aware of the resources created by the VPC CNI (which can be further worsened if the number of warm ENIs or IPs is increased through the VPC CNI configurations) so it is unaware that the VPC CNI needs time to clean up its resources. By preserving the addon within the cluster, it will give the daemonsets time to clean up the resources they created

**Comment by dgr237** [comment]
Let me try setting the preserve and see if this solves the issue or not.

**Comment by dgr237** [comment]
In terms of dependencies yes there is nothing on the vpc cni which can be used to implicitly enforce the dependencies so we have had to force the ordering by placing depends_on on the other eks_addons to ensure that the vpc_cni is installed prior to the other resources.

**Comment by dgr237** [comment]
I have validated that with setting the preserve on a cycle of 10 runs the dangling ENI issue did not occur. Will reopen if on further testing the issue reoccurs.

@bryantbiggs thanks for your help!
