### ISSUE TITLE
[Bug]: terraform -v not reporting 1.9.4 as current, 1.9.3 as out-of-date. Still reportin 1.9.3 as current

### ISSUE THREAD

**Issue by jaffel-lc** [hashicorp/terraform-provider-aws#38922]
### Terraform Core Version

1.9.3, 1.3.10, 1.8.5

### AWS Provider Version

n/a

### Affected Resource(s)

$ terraform version doesn't report 1.9.3 as out of date despite 1.9.4 being releases on 2024-08-07

### Expected Behavior

* Expect terraform (all versions) to report 1.9.4 as the latest version.
* Expect 1.9.3 to report itself as out-of-date

### Actual Behavior

1.9.3 is not reporting that it is out-of-date

1.3.10 (and 1.8.5) are reporting that 1.9.3 is the latest version 

### Relevant Error/Panic Output Snippet

```shell
1.9.3:
$ terraform version
Terraform v1.9.3
on linux_amd64

1.3.10:
$ terraform version
Terraform v1.3.10
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.9.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

n/a

### Steps to Reproduce

Execute "terraform version" while configured to use Terraform 1.9.3 - we use symbolic links

Execute "terraform version" while configured to use Terraform 1.3.10 - we use symbolic links

Execute "terraform version" while configured to use any other version - e.g. 1.8.5

### Debug Output

n/a

### Panic Output

n/a

### References

https://releases.hashicorp.com/terraform/  - shows that terrafrom_1.9.4 is available

https://github.com/hashicorp/terraform/blob/v1.9/CHANGELOG.md - shows that Terraform 1.9.4 was released on 2024-08-07

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jaffel-lc 👋 Thank you for taking the time to raise this! This repository is used to track bugs and enhancement requests for the Terraform AWS Provider. For more general Terraform-related issues like this, you'll need to open an issue in the [Terraform Core repository](https://github.com/hashicorp/terraform). With that in mind, I'm going to close this issue.

**Comment by stefanfreitag** [comment]
Hi @jaffel-lc,

thanks for raising the issue. I think you are right as I see same behavior in my local environment

```shell
$ terraform version
Terraform v1.9.3
on linux_amd64
```

The additional information on the new Terraform release is created [here](https://github.com/hashicorp/terraform/blob/047c1af0b4a9e1e650f3811d011bcb92b2ceb15a/internal/command/version.go#L161) (in the Terraform repository, not in the Terraform AWS provider repository).
To my current understanding the check fails at the moment because the [API](https://checkpoint-api.hashicorp.com/v1/check/terraform) provides outdated information.

```json
{"product":"terraform","current_version":"1.9.3","current_release":1721850049,"current_download_url":"https://releases.hashicorp.com/terraform/1.9.3","current_changelog_url":"https://github.com/hashicorp/terraform/blob/v1.9.3/CHANGELOG.md","project_website":"https://www.terraform.io","alerts":[]}
```

I would kindly ask you to raise the issue [here](https://github.com/hashicorp/terraform/issues).

**Comment by jaffel-lc** [comment]
Oops.  Too bad there isn't a tools to let you clone this issue into the other repo.
