### ISSUE TITLE
[Enhancement]: Allow generating config when importing "non-existent" aws_s3_bucket_* configuration resources to avoid configuration drift

### ISSUE THREAD

**Issue by tkovis** [hashicorp/terraform-provider-aws#39418]
### Description

To my understanding, since aws_s3_bucket configuration is split into multiple different resources, there is a risk of configuration drift if each resource is not explicitly defined. Also when importing existing infrastructure, it might not be clear how it is currently configured and there is an additional risk of not importing an explicit configuration that should not drift eather.

I have existing buckets I want to import and I tried to import all the possible configuration resources, since I am not sure how they are currently configured, want to avoid manually figuring it out and want to avoid future configuration drift if implicitly disabled configuration happens to get explicitly defined outside of terraform.

I got errors "Cannot import non-existent remote object" regarding at least:
- lifecycle configuration
- cors configuration
- ownership controls
- replication configuration
- object lock configuration
- website configuration
- logging
- public access block

aws_s3_bucket_notification, aws_s3_bucket_accelerate_configuration, aws_s3_bucket_versioning, aws_s3_bucket_server_side_encryption_configuration, aws_s3_bucket_request_payment_configuration seems to import fine even without anything explicitly defined.

I have not and will not try imperative state imports, since I want to have a record of what has happened in version control.

I am currently working around by commenting out imports that do not work, but this is not desirable because of potential configuration drift.

### Affected Resource(s) and/or Data Source(s)

(at least)
aws_s3_bucket_lifecycle configuration, aws_s3_bucket_cors_configuration, aws_s3_bucket_ownership_controls, aws_s3_bucket_replication_configuration, aws_s3_bucket_object_lock_configuration, aws_s3_bucket_website_configuration, aws_s3_bucket_logging, aws_s3_bucket_public_access_block

### Potential Terraform Configuration

```terraform
import {
  id = "example-123"
  to = aws_s3_bucket.example
}

# autogenerated without null values
resource "aws_s3_bucket" "example" {
  bucket              = "example-123"
  object_lock_enabled = false
  tags                = {}
  tags_all            = {}
}


import {
  id = "example-123"
  to = aws_s3_bucket_public_access_block.example # is off, results in "Cannot import non-existent remote object"
}


## in another file
# __generated__ by Terraform from "example"
resource "aws_s3_bucket_notification" "example" {
  bucket      = "example-123"
  eventbridge = false
}
```

### References

eg. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block#import states that importing with bucket id should work, but does not if it is not explicitly defined for an existing resource.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @tkovis 👋 Thank you for taking the time to raise this! Unfortunately the error that you're receiving is coming from Terraform Core itself, and isn't something the AWS Provider has control over. I don't suspect that the Terraform Core team would be up for allowing imports of non-existent objects, but you could ask in a new issue in the [Terraform Core repository](https://github.com/hashicorp/terraform) if you feel so inclined.

One thing that I think is worth mentioning is that, while they are deprecated and shouldn't be used for configuration, the `aws_s3_bucket` resource still has related arguments for most of the split-off resources. For example, [`lifecycle_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#lifecycle-rule), [`cors_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#cors-rule), and [`replication_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#replication-configuration). After importing the S3 bucket itself, you could inspect the resource with [`terraform state show`](https://developer.hashicorp.com/terraform/cli/commands/state/show) to review what the bucket has configured, so you have a better idea of what additional resources you may need to configure for the bucket.

Since there's no action that the AWS Provider team can take to change this behavior, I'm going to close this issue. If you run into any other behavior that you think should be changed, or isn't working quite right, please do let us know!
