### ISSUE TITLE
[Enhancement]: Add tags for aws_ses_configuration_set 

### ISSUE THREAD

**Issue by LozanoMatheus** [hashicorp/terraform-provider-aws#39437]
### Description

It would be nice if we could add the tags to the resource, but by looking into the [AWS API](https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateConfigurationSet.html) I'm not sure if it will be possible since it doesn't have the parameter for tag or an `TagResource ` API for SES (like they do to some resources, e.g. [Lambda](https://docs.aws.amazon.com/lambda/latest/api/API_TagResource.html)).

### Affected Resource(s) and/or Data Source(s)

* aws_ses_configuration_set

### Potential Terraform Configuration

```terraform
resource "aws_ses_configuration_set" "test" {
  name = "some-configuration-set-test"

  tags = {
    Name = "my-ses-configuration-set"
  }
}
```

### References

* Ticket with AWS CLI as well: aws/aws-cli/issues/8938

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
This is an AWS upstream issue and the answer in the issue opened to AWS CLI would also apply here. The `aws_sesv2_configuration_set` resource already support tags and it's unlikely that AWS would update the older API which `aws_ses_configuration_set` resource depends on.

**Comment by justinretzolk** [comment]
Hey @LozanoMatheus 👋 This has come up a couple of times before (#25670, #27475), and unfortunately the same answer to those applies here (as mentioned above). Since this is something that AWS itself does not support, and doesn't seem they ever will, I'm going to close this issue. If you have any further requests for the provider, please do let us know!
