### ISSUE TITLE
[Docs]: Data Source: aws_kms_alias Attribute Reference error

### ISSUE THREAD

**Issue by satyajeetjsr** [hashicorp/terraform-provider-aws#39466]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/kms_alias#id

### Description

The aws_kms_alias data source documentation has identical descriptions for the arn and id attributes, which should be different since they represent different outputs

### Would you like to implement a fix?

Yes

**Comment by satyajeetjsr** [comment]
I am working to fix this issue

**Comment by stefanfreitag** [comment]
Hi @satyajeetjsr,
thank you for raising the issue.

We already track a very similar issue for the same resource under [38879](https://github.com/hashicorp/terraform-provider-aws/issues/38879) . 
I think we have the same description in place for both attributes as they actually have the same value. Here is the [link](https://github.com/hashicorp/terraform-provider-aws/blob/ae1327b36868ec370deaf34b9f674f864288fb3c/internal/service/kms/alias_data_source.go#L55) to the relevant section in the source code.

**Comment by justinretzolk** [comment]
Hey @satyajeetjsr 👋 Thank you for taking the time to raise this! As Stefan mentioned above (and I detailed further in my comment on the [related issue](https://github.com/hashicorp/terraform-provider-aws/issues/38879#issuecomment-2448209380)), the two attributes have the same description as they output the same value. With that in mind, and since there's no further action for the AWS Provider team to take, I'm going to close this issue. If you notice anything else in the documentation that appears to be amiss, please do continue to let us know!
