### ISSUE TITLE
[Bug]: aws_backup_plan fails to be decoded from state

### ISSUE THREAD

**Issue by bobbywarner** [hashicorp/terraform-provider-aws#39730]
### Terraform Core Version

1.8.2

### AWS Provider Version

5.70.0

### Affected Resource(s)

* aws_backup_plan

It seems quite coincidental that this PR was merged last week: https://github.com/hashicorp/terraform-provider-aws/pull/33653 🤔 

### Expected Behavior

Terraform should be able to refresh state for existing `aws_backup_plan` resources without issues given no version changes were done.

### Actual Behavior

Warning: Failed to decode resource from state

Error decoding `aws_backup_plan.my_backup` from prior state: unsupported attribute "schedule_expression_timezone"

Error: Resource instance managed by newer provider version

The current state of `aws_backup_plan.my_backup` was created by a newer provider version than is currently selected. Upgrade the aws provider to work with this state.

### Terraform Configuration Files

N/A

### Steps to Reproduce

Instantiate an `aws_backup_plan` resource and then try to refresh state with it.

### Would you like to implement a fix?

No

**Comment by bobbywarner** [comment]
@msg555 So something like this until 5.72 is released?

`terraform state rm aws_backup_plan.my_backup` ?

**Comment by justinretzolk** [comment]
Hey @bobbywarner 👋 Thank you for taking the time to raise this! As mentioned above, this is likely caused by `5.71.0` having been pulled. The team is in the process of releasing `5.72.0` now though, so I wouldn't bother removing the resource from your state and doing that whole dance, unless you have an urgent need to proceed. Once `5.72.0` is out, you shouldn't encounter any further issues.

**Comment by bobbywarner** [comment]
I removed the `aws_backup_plan` via AWS Console, removed the resource from Terraform state and then did a Terraform apply to recreate it successfully.  Good to go!
