### ISSUE TITLE
[Bug]: Image Builder Recipe Can't be Deleted because of Dependent Image Pipeline Resource

### ISSUE THREAD

**Issue by sophiecosgrove** [hashicorp/terraform-provider-aws#39985]
### Terraform Core Version

1.9.8

### AWS Provider Version

5.74.0

### Affected Resource(s)

aws_imagebuilder_image_recipe, aws_imagebuilder_image_pipeline

### Expected Behavior

Image recipe is expected to be deleted and recreated to facilitate component change. 

### Actual Behavior

Image recipe can't be deleted because of an update in 5.74.0 which allows the image pipeline to be updated in place: https://github.com/hashicorp/terraform-provider-aws/pull/39117 producing a dependency error. Previously the image pipeline would have been deleted and recreated, followed by the same for recipe and component, as per the order here: https://docs.aws.amazon.com/imagebuilder/latest/userguide/delete-resources.html. However now the pipeline is being updated in place it means that it's dependent on the recipe so the recipe can't be recreated. 

### Relevant Error/Panic Output Snippet

```shell
Error: deleting Image Builder Image Recipe (arn:aws:imagebuilder:xxx): operation error imagebuilder: DeleteImageRecipe, https response error StatusCode: 400, ResourceDependencyException: Resource dependency error: The resource ARN 'arn:aws:imagebuilder:xxx' has other resources depended on it.
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

Create an image pipeline with attached recipe and component. Change component to cause a recreation of the recipe. 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @sophiecosgrove 👋 Thank you for taking the time to raise this! This seems like an appropriate time to use [`replace_triggered_by`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by) in order to force replacement of the appropriate resource(s). Since the API allows for the `image_recipe_arn` to be updated, the provider should respect that behavior (hence the change in the PR that you linked to), but `replace_triggered_by` should help in your case. Can you give that approach a try and see if that resolves your issue?

**Comment by sjoukedv** [comment]
Making sure the pipeline (the thing that depends on the recipe) is destroyed before deleting (due to recreation) the recipe works for me;

```terraform
resource "aws_imagebuilder_image_pipeline" "main" {
  ...
  lifecycle {
    replace_triggered_by = [
      aws_imagebuilder_image_recipe.main
    ]
  }
}

resource "aws_imagebuilder_image_recipe" "main" {
  ...
  parent_image = "ami-xxx" # <-- forces replacement (with same version)
}
```
