### ISSUE TITLE
Import resources defined as data sources before

### ISSUE THREAD

**Issue by DeLoWaN** [hashicorp/terraform-provider-aws#4269]
Hi there,

I have a `aws_route53_zone` defined as a data source earlier. So I referenced it multiple times in my `.tf` config files.

Now I want to be able to transform it as a resource since I want to create records for it. So I deleted the data source, create the corresponding resource block like this:

```
resource "aws_route53_zone" "XXXX" {
  name         = "XXXX"
}
```

I changed the references in my config files from `${data.aws_route53_zone.XXXX.......}` to `${aws_route53_zone.XXXX.......}`

I then tried to import the resource by launching:

```
terraform import aws_route53_zone.XXXX MYROUTE53ID
```

But Terraform fails with `Error: aws_route53_zone.XXXX (import id: MYROUTE53ID): Can't import aws_route53_zone.XXXX, would collide with an existing resource`

This is odd, since when I check if the resources exists with `echo aws_route53_zone.XXXX.id | terraform console`, it answers:

```
Resource 'aws_route53_zone.XXXX' not found for variable 'aws_route53_zone.XXXX.id'
```

What am I doing wrong ? Any help is welcomed :). Thanks.

Terraform version: 

```
Terraform v0.11.5
+ provider.aws v1.11.0
```

**Comment by nhnicwaller** [comment]
I also encountered this error while attempting to refactor Route53 configuration into a separate stack. I used a `data.aws_route53_zone` to temporarily allow records in both stacks, but for a while I was stuck because I was unable to import the zone into the new stack.

Luckily I found a workaround:

- Use `terraform state list` to find the name of offending `aws_route53_zone`
- Use `terraform state rm` to purge the `aws_route53_zone` resource blocking the resource import
- Continue with the original import as planned

**Comment by TV4Fun** [comment]
This issue also occurs with GCP. It's confusing as `terraform state list` and `terraform state show` doesn't differentiate between data sources and resources, meaning it's not immediately obvious that it sees it as a data source and not a resource.
