### ISSUE TITLE
Feature request: Exclusive policy attachment list for users, groups, and roles

### ISSUE THREAD

**Issue by jbscare** [hashicorp/terraform-provider-aws#4426]
### Terraform Version

```
+$ terraform -v
Terraform v0.11.7
+ provider.aws v1.16.0
```

### Affected Resource(s)

- aws_iam_user_policy_attachment
- aws_iam_group_policy_attachment
- aws_iam_role_policy_attachment

### Expected Behavior

This is a feature request for either (a) an enhancement to aws_iam_user_policy_attachment, aws_iam_group_policy_attachment, and aws_iam_role_policy_attachment; or (b) to create a new trio of resources (perhaps aws_iam_user_policy_list, aws_iam_group_policy_list, and aws_iam_role_policy_list?), to allow for the specification of an exclusive list of policies that should be attached to a group or role, much like aws_iam_group_membership allows for the specification of an exclusive list of users who should be members of a group. If any policies are found attached to the group or role that aren't on the list, they should be removed.

### Actual Behavior

There doesn't seem to be a way to accomplish this effect at this time. (You can get sort of a converse of this effect with aws_iam_policy_attachment, which specifies an exclusive list of roles and users and groups to which a policy is attached, but doesn't exclude other policies from being attached to a role, user, or group.)

### Use case

We'd like to use Terraform to fully specify the policies that should be attached to a user or group or role, and if someone adds a policy outside of Terraform, for Terraform to detect and correct that.

**Comment by lorengordon** [comment]
Following. I thought terraform already did this. Yikes. Major security hole here.

**Comment by FernandoMiguel** [comment]
@lorengordon it's by design.
No security risk. 
If you allow anyone to modify your account, no security can save you

**Comment by lorengordon** [comment]
It can certainly be one thing to you and another to me and our auditors. Call it whatever you like. We call it a security risk.

We want to use terraform to manage infrastructure as code. We create the IAM role with terraform and we create the IAM policies with terraform. But it turns out we cannot actually guarantee an _exact_ configuration of a role using terraform, since any policies added to the role outside of terraform are basically invisible to terraform right now. That's pretty bad in our book. We'll need to use something else to manage IAM roles until this is fixed.

I see it as similar functionality as what terraform provides with security groups... You can either define the rules as part of the aws_security_group resource, and those rules will remove any other rules, ensuring the exact configuration of the security group. Or you can use the aws_security_group_rule resource to add rules to a security group without removing any externally added rules.

**Comment by jbscare** [comment]
The only thing I'd quibble with is that using Terraform in this way doesn't create a security hole where there wasn't one before. If you consider users groups and roles that aren't managed by code to be a security hole, then it's true that Terraform doesn't fix that, but Terraform doesn't fix a lot of security holes.

All that said, we of course want this feature, since this seems like a security hole that Terraform could fix. :^) (Or an "issue" that it could "address", if you like.)

**Comment by YakDriver** [comment]
@jbscare @bflad @lorengordon  I'm working on a PR for an exclusive list of role policies (`aws_iam_role_policy_list`) currently. There are a few design options. I'd like to get your thoughts.

1.  **_ONLY_ enforce exclusivity**

The new resource would not associate listed policies with the role. It would detach managed or delete inline policies found that weren't listed. If you didn't want the resource to mess with managed policies, you could skip the argument and the role's managed policies would be left unaffected. Same for inline policies.

If you wanted to make sure that no inline and/or managed policies were put/attached to the role, you could include `inline_policies = []` or `managed_policies = []`.

This would provide all the security benefits with no redundant functionality. To associate a policy with a role, you would have to use `aws_role_policy_attachment` (managed) or `aws_role_policy` (inline).

```hcl
resource "aws_iam_role_policy_list" "policy_list" {
  name = "yak_testing_role_policy_list"
  role = "${aws_iam_role.instance_role.name}"

  managed_policies = [
    "${aws_iam_policy.policy_one.arn}",
    "${aws_iam_policy.policy_two.arn}",
  ]

  inline_policies = [
    "${aws_iam_role_policy.inline_test_policy1.name}",
    "${aws_iam_role_policy.inline_test_policy2.name}",
  ]
}
```

2.  **Enforce exclusivity _and_ manage managed policies**

The same as the first approach except with the added convenience that you would not need `aws_role_policy_attachment` to attach **managed** policies to the role. In other words, the listed managed policies would be attached to the role if they were not already. Inline policies would still be handled as above (inline cannot be managed in the same way because to put an inline policy requires the policy document).

3. **Ultimate management of policies**

Redundant functionality but very convenient. You can create and associate managed and inline policies, and an exclusive list, all with the same resource.

```hcl
resource "aws_iam_role_policy_list" "policy_list" {
  name = "yak_testing_role_policy_list"
  role = "${aws_iam_role.instance_role.name}"

  managed_policy {
  name        = "test_managed_policy"
  path        = "/"
  description = "My test policy"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
  }

  inline_policy {
  name = "test_inline_policy"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
  }
}
```

4. **My view**

I think that # 2 is probably the best approach but #1 has merit. # 3 is the wrong approach IMO.

**Comment by lorengordon** [comment]
> It seems like option 1 could get you into a weird state where your TF config could define a policy attachment but not have it on the list -- what would Terraform do then?

Terraform would first attach it, then detach it! 😂 Don't do that!

Option 2 doesn't resolve that scenario for inline policies... If a user creates and associates the inline policy using `aws_role_policy`, but does not specify the inline policy in `aws_iam_role_policy_list`, then terraform would again create the inline policy and then delete it!

Personally, I'm ok with this, as I think it would be pretty apparent what was happening from one `apply` to the next. User would just need to update their config to match their intent.

I like option 1... I think option 3 could be compelling but only if we can reuse the code from the other modules.

**Comment by jbscare** [comment]
Just to clarify, in that table in the previous comment, the "Action" column describes what would happen if you did a `terraform apply` after someone took those actions via some out-of-band non-Terraform method (like the AWS web UI), right?

If so, that all sounds good to me!

One thought: I'm not sure about the `aws_iam_role_policy_list` name; it's not intuitively clear from the name how this relates to `aws_iam_policy_attachment`. It's sort of cumbersome, but would `aws_iam_exclusive_policy_attachment_list` be clearer? Any other ideas?

Also, is this only for roles? Could it be extended to cover users and groups as well?

Thanks for all your work on this!

**Comment by YakDriver** [comment]
I'll clean up the table to make it a bit clearer.

`aws_iam_role_policy_list` has 24 characters. What about `aws_iam_role_policy_sole_list` (29), `aws_iam_role_policy_exclusive_list` (34), or `aws_iam_role_policy_manager` (27)?

Right now I'm just working roles. With some lessons learned with roles (with the implementation and merge process), we may have a chance to do users and groups as well.

**Comment by YakDriver** [comment]
@jbscare @lorengordon Feel free to thumbs up the PR if you have a chance.

**Comment by YakDriver** [comment]
The acceptance tests for PR #5904 cover the tests in [the comment](https://github.com/terraform-providers/terraform-provider-aws/issues/4426#issuecomment-421183069) above.

**Comment by bflad** [comment]
Thanks for all your work here so far. From my design comment on #5904, I would like to introduce some talking points.

Adding more IAM resources (times 3 for group/role/policy) doesn't seem necessary and I think will further add to the confusing landscape that is AWS IAM management in Terraform. Is there a reason to split away this information from the original resource configurations (`aws_iam_group`/`aws_iam_role`/`aws_iam_user`)?

Starting with managed policies, we can introduce a `policy_attachments`/`managed_policies`/`managed_policy_attachments`/`managed_policy_arns` TypeSet attribute on the existing (e.g. `aws_iam_role`) resources to enable this type of configuration:

```hcl
# Design sketch - not currently implemented and details may change during development
resource "aws_iam_role" "example" {
  # ... other configuration ...

  managed_policy_arns = [
    "${aws_iam_policy.example.arn}",
    "arn:aws:iam::aws:policy/AdministratorAccess",
  ]
}
```

In this model, the `aws_iam_role` resource knows everything it needs to about maintaining a set list of managed policy attachments to add/update/remove them. The same caveat applies that this configuration conflicts with any `aws_iam_role_policy_attachment` resources.

Inline policies are _slightly_ trickier because they have a name associated with them, but there are a few potential solutions there, with a TypeMap potentially being the best in my opinion (the other being the introduction of another data source specifically for inline policies, but the additional complexity seems unnecessary). Drawing out how this might look:

```hcl
# Design sketch - not currently implemented and details may change during development
resource "aws_iam_role" "example" {
  # ... other configuration ...

  inline_policies = {
    policy1 = "${data.aws_iam_policy_document.example.json}"
    policy2 = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
POLICY
  }
}
```

In this model, the `aws_iam_role` resource knows everything it needs to about maintaining a set list of inline policies (based on name) to add/update/remove them. The same caveat applies that this configuration conflicts with any `aws_iam_role_policy` resources.

What do you all think?

Aside (and a very personal opinion): I think its extremely important to not include statements in documentation saying this type of functionality "enhances" security. While it does overall improve your security posture by detecting drift from a desired configuration, it does nothing to prevent security issues, is not designed to be a security alerting tool, and only provides point in time remediation (per run).

**Comment by lorengordon** [comment]
Seems reasonable to me. Could perhaps use the list of maps pattern as well, seems pretty common throughout Terraform. I don't think I have a preference between the two...

managed policies:
```
# Design sketch - not currently implemented and details may change during development
resource "aws_iam_role" "example" {
  # ... other configuration ...

  managed_policy {
    arn = "${aws_iam_policy.example.arn}"
  }

  managed_policy {
    arn = "arn:aws:iam::aws:policy/AdministratorAccess",
  }
}
```

inline policies:
```
# Design sketch - not currently implemented and details may change during development
resource "aws_iam_role" "example" {
  # ... other configuration ...

  inline_policy {
    name = "policy1"
    policy = "${data.aws_iam_policy_document.example.json}"
  }

  inline_policy {
    name = "policy2"
    policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
POLICY
  }
}
```

**Comment by jbscare** [comment]
I don't have a strong opinion either way, other than to note that this seems somewhat analogous to the situation with aws_security_group and aws_security_group_rule, and if it's going to behave in a similar way, it might make sense for its configuration to be similar.

**Comment by YakDriver** [comment]
After delving into the code more, `aws_iam_role` is a very clean resource so I think adding the functionality there is going to work fine. I hear that this approach will make more sense to users.

**Comment by YakDriver** [comment]
@bflad Can you help me with maps? I'm having some trouble. I defined the inline policies in the schema as follows:

```golang
"inline_policies": {
	Type:     schema.TypeMap,
	Optional: true,
	Computed: true,
	Elem: &schema.Schema{
		Type:             schema.TypeString,
		ValidateFunc:     validateJsonString,
		DiffSuppressFunc: suppressEquivalentJsonDiffs,
		StateFunc: func(v interface{}) string {
			json, _ := structure.NormalizeJsonString(v)
			return json
		},
	},
},
```

But, these extra schema goodies are not doing anything I'd expect. I can send in a bad JSON and it fails when it goes to AWS instead of validating it somewhere in Terraform beforehand. The `DiffSupressFunc` doesn't seem to do anything: `d.GetChange()` returns the entire old and new maps, including the elements (key/value pairs) that haven't changed. When I look at the resulting state, the policy JSON is not normalized so `NormalizeJsonString` isn't changing the value before storing in the state. Is all this related to using a `schema.TypeMap`? 

The resulting state has weird URL-encoded JSON strings:
```json
"inline_policies.%": "3",
"inline_policies.another_inline_policy": "%7B%0A%20%20%22Version%22%3A%20%222012-10-17%22%2C%0A%20%20%22Statement%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22Sid%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%22Effect%22%3A%20%22Allow%22%2C%0A%20%20%20%20%20%20%22Action%22%3A%20%22ec2%3ADescribeAccountAttributes%22%2C%0A%20%20%20%20%20%20%22Resource%22%3A%20%22%2A%22%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D",
"inline_policies.just_an_inline_policy": "%7B%0A%20%20%22Version%22%3A%20%222012-10-17%22%2C%0A%20%20%22Statement%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22Effect%22%3A%20%22Allow%22%2C%0A%20%20%20%20%20%20%22Action%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%22s3%3AListAllMyBuckets%22%2C%0A%20%20%20%20%20%20%20%20%22s3%3AListBucket%22%2C%0A%20%20%20%20%20%20%20%20%22s3%3AHeadBucket%22%0A%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%22Resource%22%3A%20%22%2A%22%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D%0A",
"inline_policies.yak_inline_test_policy": "%7B%0A%20%20%22Version%22%3A%20%222012-10-17%22%2C%0A%20%20%22Statement%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22Action%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%22ec2%3ADescribe%2A%22%0A%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%22Effect%22%3A%20%22Allow%22%2C%0A%20%20%20%20%20%20%22Resource%22%3A%20%22%2A%22%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D%0A",
```

I started with a config having 2 inline policies defined in the `aws_iam_role`, applied, everything creates fine. Then when I change the config to add another inline policy, without touching the existing 2, in `update()` I get a combination of URL-encoded and not URL-encoded and everything, instead of just what changed:

Old:
```
map[another_inline_policy:%7B%0A%20%20%22Version%22%3A%20%222012-10-17%22%2C%0A%20%20%22Statement%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22Sid%22%3A%20%22%22%2C%0A%20%20%20%20%20%20%22Effect%22%3A%20%22Allow%22%2C%0A%20%20%20%20%20%20%22Action%22%3A%20%22ec2%3ADescribeAccountAttributes%22%2C%0A%20%20%20%20%20%20%22Resource%22%3A%20%22%2A%22%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D yak_inline_test_policy:%7B%0A%20%20%22Version%22%3A%20%222012-10-17%22%2C%0A%20%20%22Statement%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22Action%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%22ec2%3ADescribe%2A%22%0A%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%22Effect%22%3A%20%22Allow%22%2C%0A%20%20%20%20%20%20%22Resource%22%3A%20%22%2A%22%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D%0A]
```

New:
```
map[yak_inline_test_policy:{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
 another_inline_policy:{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": "ec2:DescribeAccountAttributes",
      "Resource": "*"
    }
  ]
} just_an_inline_policy:{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:ListBucket",
        "s3:HeadBucket"
      ],
      "Resource": "*"
    }
  ]
}
]
```

**Comment by lorengordon** [comment]
Please don't close this, it would be a very important feature for maintaining strict control over iam roles (and users and groups).

**Comment by soumyajk** [comment]
Hi, 
This is a very valid problem(surprised to see the request in stale state). 
Its very annoying to have additional policies attached against iam roles which are created through terraform, which the terraform is completely unaware of. I would have expected terraform to show it as a drift, detach the managed policy if not present in terraform. 

This also makes it impossible to catch the drift, which stops the role from being deleted if force_detach_policies value is set true. 

I completely agree with the model shared in comment : https://github.com/hashicorp/terraform-provider-aws/issues/4426#issuecomment-421183069 

I would appreciate if someone can share the latest update on this bug. 

Thanks

**Comment by lorengordon** [comment]
If anyone subscribed here still really cares about this feature like I do, here are few other issues to please go give a thumbs up, plus the pr that implements exclusive attachment for IAM roles...

* https://github.com/hashicorp/terraform-provider-aws/issues/17510
* https://github.com/hashicorp/terraform-provider-aws/issues/17511
* https://github.com/hashicorp/terraform-provider-aws/issues/17512
* https://github.com/hashicorp/terraform-provider-aws/pull/5904

**Comment by AnthonyFoiani-at** [comment]
Hello! It took me a quite a while to figure out what `aws_iam_role.managed_policy_arns` meant, and why it was added.

It looks like I'm not the only person that was confused: https://discuss.hashicorp.com/t/confusion-about-aws-iam-role-managed-policy-arns-attribute/29728

Could the documentation be expanded / reworded? In particular, the usage of "exclusive" made me think that "oh, this role is the only user of this policy", not "this role is the only thing that controls which policies are attached to itself".

Maybe something along the lines of:

> If you specify a list of `managed_policy_arns`, Terraform `apply` will attempt to enforce that **exactly** and **only** those policies are attached to this role; any out-of-band changes or separate attachment resources will be disregarded and/or reverted (and/or cause resource cycling).

Thank you!

**Comment by AnthonyFoiani-at** [comment]
Hello again, and sorry for the noise!

It took me a few more iterations to realize that I also needed to keep the _desired_ `aws_iam_role_policy_attachment` resources in my input!

The phrase "If this attribute is not configured, Terraform will ignore policy attachments to this resource" confused me quite a bit: I had to experiment a bit before I realized the intent was:

> if this attribute **is not** configured, Terraform will neither notice nor modify the attachment of any policies to this role when processing this resource (regardless of whether those attachments are made with other TF resources or manually through the console or API).
>
> If this attribute **is** configured, Terraform will attempt to ensure that only policies in this list will be attached to this role (either through `aws_iam_role_policy_attachment` resources, or through out-of-band manual action).

It might also be helpful to include an example of a common state, something like:

```
resource "aws_iam_role" "sensitive" {
  ...
  # Enforce that we want exactly and only these policies attached to this role:
  managed_policy_arns = [
    aws_iam_policy.sensitive_stuff,
    aws_iam_policy.other_sensitive_stuff,
  ]
}

# Now create those attachments.
resource "aws_iam_role_policy_attachment" "sensitive_sensitive_stuff" {
  role       = aws_iam_role.sensitive
  policy_arn = aws_iam_policy.sensitive_stuff
}
resource "aws_iam_role_policy_attachment" "sensitive_other_sensitive_stuff" {
  role       = aws_iam_role.sensitive
  policy_arn = aws_iam_policy.other_sensitive_stuff
}
```

Including a contrasting sample "this is a problem" configuration might also help:

```
resource "aws_iam_role" "sensitive" {
  ...
  # Enforce that we want exactly and only this policy attached to this role:
  managed_policy_arns = [
    aws_iam_policy.sensitive_stuff,
  ]
}

# This attachment is fine, since it's explicitly mentioned in aws_iam_role.sensitive.managed_policy_arns:
resource "aws_iam_role_policy_attachment" "sensitive_sensitive_stuff" {
  role       = aws_iam_role.sensitive
  policy_arn = aws_iam_policy.sensitive_stuff
}

# This resource is problematic; we're attempting to attach this policy to the `sensitive` role, but
# aws_iam_role.sensitive.managed_policy_arns does not include this policy! Depending on which
# resource is processed last, it's possible to end up in an inconsistent state (or cause perpetual
# plan/apply cycles).
resource "aws_iam_role_policy_attachment" "sensitive_some_random_stuff" {
  role       = aws_iam_role.sensitive
  policy_arn = aws_iam_policy.some_random_stuff
}
```

Thank you again!

[If necessary, I'm happy to get a copyright disclaimer for the above, and you're more than welcome to cut-and-paste it as you see fit!]

**Comment by lorengordon** [comment]
@AnthonyFoiani-at I do not believe that is accurate. When you specify this:

```
resource "aws_iam_role" "sensitive" {
  ...
  # Enforce that we want exactly and only these policies attached to this role:
  managed_policy_arns = [
    aws_iam_policy.sensitive_stuff,
    aws_iam_policy.other_sensitive_stuff,
  ]
}
```

The `aws_iam_role` resource fully manages the attachments. You do not need and should not use `aws_iam_role_policy_attachment` for that role at all.

**Comment by AnthonyFoiani-at** [comment]
> The `aws_iam_role` resource fully manages the attachments. You do not need and should not use `aws_iam_role_policy_attachment` for that role at all.

Thank you for the correction -- I will do some experiments!

Hopefully it's still a constructive message that the documentation is confusing?

**Comment by AnthonyFoiani-at** [comment]
@lorengordon wrote:

> The `aws_iam_role` resource fully manages the attachments. You do not need and should not use `aws_iam_role_policy_attachment` for that role at all.

Verified!  Thank you for the correction.

**Comment by lorengordon** [comment]
Nice. I think part of understanding the docs comes with the term "exclusive" and what terraform means by that. And then the tri-modal nature of assigning a value.

A few resources have this concept of what I call a "container" resource and an attachment. Like IAM Roles (container) and policies (attachment), and security groups (container) and rules (attachment). "Exclusive" is in relation to how terraform manages the attachments on the container resource.

When you use an attribute on the "container" resource that manages attachments, it is an "exclusive" relationship. I.e. _Exactly and only_ these attachments should be present, and any other attachments other than what is specified will be removed.

When you use a _separate_ attachment resource, it is non-exclusive. Meaning you could have one terraform state that manages the container resource (without specifying the attachment attribute), and then you could have any number of other terraform states managing attachments to that container resource. Or really, the attachments could be created any way at all, including manually in the console or cli. When running terraform on the state that manages the container resource, it will just ignore the attachments.

So, that kinda gets at the tri-modal nature also... Here is what I mean, see the comment on each example:

```
resource "aws_iam_role" "sensitive" {
  ...
  # Enforce that we want exactly and only these policies attached to this role:
  managed_policy_arns = [
    aws_iam_policy.sensitive_stuff,
    aws_iam_policy.other_sensitive_stuff,
  ]
}
```

```
resource "aws_iam_role" "sensitive" {
  ...
  # Enforce that there must be exactly 0 attached policies:
  managed_policy_arns = []
}
```

```
resource "aws_iam_role" "sensitive" {
  ...
  # Ignore all attachments, neither add nor remove them
  # managed_policy_arns = null
}
```

**Comment by AnthonyFoiani-at** [comment]
@lorengordon Those examples are great! "Tri-modal" isn't a word I hear very often. :-)

And now that I [am pretty sure! I] understand what's going on, the existing wording in the docs makes sense. That's a tough puzzle to crack; hopefully my naive comments above might help us find a starting point.

The only change I'd suggest is to the last one:

```
resource "aws_iam_role" "sensitive" {
  ...
  # This resource will not manipulate associated policy attachments on its own; you will
  # need to attach policies through either `aws_iam_role_policy_attaachment` resources,
  # or manually via the console / API / CLI.
  managed_policy_arns = null
}
```

Thank you all again, and have a great weekend!

**Comment by jar-b** [comment]
As of `v5.72.1` of the AWS provider, the following standalone resources are available to enable Terraform to exclusively manage inline and managed policy attachments for IAM roles, users, and groups.

Inline policies:
- [`aws_iam_role_policies_exclusive`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policies_exclusive)
- [`aws_iam_user_policies_exclusive`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policies_exclusive)
- [`aws_iam_group_policies_exclusive`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_group_policies_exclusive)

Customer managed policy attachments:
- [`aws_iam_role_policy_attachments_exclusive`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy_attachments_exclusive)
- [`aws_iam_user_policy_attachments_exclusive`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_policy_attachments_exclusive)
- [`aws_iam_group_policy_attachments_exclusive`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_group_policy_attachments_exclusive)

The following [proposal](https://hashicorp.github.io/terraform-provider-aws/design-decisions/exclusive-relationship-management-resources/) contains more context for the creation of these resources, and this [meta issue](https://github.com/hashicorp/terraform-provider-aws/issues/39376) tracks the progress of "exclusive relationship management resources" across the entire provider.

With the availability of these resources, this issue can now be closed.
