### ISSUE TITLE
Mismatch reason: attribute mismatch: snapshot_identifier - Resource ID: aws_db_instance.default 

### ISSUE THREAD

**Issue by sandor11** [hashicorp/terraform-provider-aws#4968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.7

### Affected Resource(s)

aws_db_instance

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "default" {
  name                      = "${var.stack_name}-${var.env_name}-rds"
  allocated_storage         = 5
  instance_class            = "${var.db_instance_size}"
  identifier                = "${var.stack_name}-${var.env_name}-rds"
  db_subnet_group_name      = "${aws_db_subnet_group.default.name}"
  engine                    = "postgres"
  port                      = "${var.db_port}"
  publicly_accessible       = false
  storage_type              = "standard"
  vpc_security_group_ids    = ["${aws_security_group.allow_db.id}"]
  name                      = "${var.db_name}"
  username                  = "${var.db_username}"
  password                  = "${var.db_password}"
  skip_final_snapshot       = "${var.skip_final_snapshot}"
  final_snapshot_identifier = "${var.stack_name}-${var.env_name}-rds-final-snapshot"
  snapshot_identifier       = "${var.snapshot_id}"
}

variable "snapshot_id" {
  description = "The name of the snapshot to create the database from. BEWARE: this will delete your existing database and replace it with one from the snapshot"
  default     = ""
}
```

### Debug Output

https://gist.github.com/sandor11/ce2413e3868b36eee4b29bd89e0a6f2b

### Expected Behavior

I have made some comments on the thread
https://github.com/terraform-providers/terraform-provider-aws/issues/4126#issuecomment-399773320

1. Deployed db stack with no snapshot id: RDS is created
2. Deploy the stack, adding a snapshot id: RDS is destroyed and then created from snapshot
3. Deploy the stack, leave the same existing snapshot id in the config: RDS has no changes
4. Deploy the stack with the snapshot id set back to empty "": RDS is destroyed and created from scratch

### Actual Behavior

1. Deployed db stack with no snapshot id: RDS is created
2. Deploy the stack, adding a snapshot id: RDS is destroyed and then created from snapshot
3. Deploy the stack, leave the same existing snapshot id in the config: **RDS is destroyed and then created from snapshot**
4. Deploy the stack with the snapshot id set back to empty "": **Error as per the gist debug output**
_(5.) If I then deploy the stack over the top of the error, it will create the stack correctly._

### Steps to Reproduce

1. Create a module for the rds
2. bring the module into a stack configuration
3. pass the vars to the module from a file
4. terraform apply -auto-approve -var-file="vars.tfvars"

### Important Factoids
- using s3 backend
- Postgres
- aws_db_instance is being loaded from a module

**Comment by schollii** [comment]
I agree that if a re-deployment causes RDS to be re-started even if the snapshot identifier has not changed, then this is not likely expected. The parameter should be used to identify how to restart an RDS instance next time a restart is *needed*; it should never cause an RDS to be re-started, whether it is changed or non-empty. Otherwise, it implies that anytime a re-deploy is needed for a reason independent from RDS, the RDS will be re-instantiated, thereby loosing data. 

In general there are 3 use cases: 

1. on re-deploy, start with new DB (presumably because RDS is used as a cache): covered by snapshot_identifier="" or not declared
2. on re-deploy, always start from same snapshot (presumably because there is some initial state that is needed): covered by snapshot_identifier having a valid value pointing to a valid file (else fail apply)
3. on re-deploy, ensure the startup state is same as final state before latest shutdown: not currently available

AND a non-null value of the associated settings does not cause RDS to be re-started ever, these only inform terraform about how to restart. 

It could happen that re-deploy fails during start of new RDS instance, in this case user would have to make some changes to terraform files and deploy again, but this time the RDS is not running so terraform just needs to know "use the latest snapshot available".

**Comment by sandor11** [comment]
I have a more pressing issue with this now. I am drafting a disaster recover plan, and the idea is to use point-int-time-restore. AWS creates a new instance for your PITR choice, which is useless from a Terraform or even native CloudFormation point of view.

It looks like the standard workaround for this is:
1. Perform the point in time restore, creating a new instance
2. Snapshot the new instance
3. Deploy your CloudFormation or Terraform with the snapshot_id set

This seems harder than necessary, however it should work. The problem is, this will enable us to restore the database with the new snapshot_id, however every subsequent deploy, we will be restoring the database to that point-in-time snapshot.

We need the behaviour which matches CloudFormation. Is there anything I can do to help this move forward?
