### ISSUE TITLE
aws_rds_cluster_parameter_group plan shows changes after applying

### ISSUE THREAD

**Issue by benberg86** [hashicorp/terraform-provider-aws#5410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

aws_rds_cluster_parameter_group

### Terraform Configuration Files

```hcl
resource "aws_rds_cluster_parameter_group" "cluster_parameters" {
  name   = "${var.serviceName}-aurora-param-group"
  family = "aurora-mysql5.7"

    parameter {
      name  = "default_password_lifetime"
      value = "0"
    }

  parameter {
    name  = "innodb_purge_threads"
    value = "1"
  }
  parameter {
    name  = "lower_case_table_names"
    value = "1"
  }
}
```

### Expected Behavior

Once applying the cluster parameters, subsequent plan and apply should not make changes to the db cluster parameter group.

### Actual Behavior

On each plan or apply, cluster parameter group is attempting to modify the resource and does not make and changes.

### Steps to Reproduce

1. `terraform apply` -> yes
2. `terraform apply` -> see changes

### Important Factoids
In this example, commenting out the parameter below resolves the unintended behavior.

parameter {
      name  = "default_password_lifetime"
      value = "0"
    }

### References

Believe this may be similar to https://github.com/terraform-providers/terraform-provider-aws/issues/593 that occurs when attempting to set a parameter to the default value, except on the cluster parameter group resource.

**Comment by smetj** [comment]
It seems this is still an issue on 
```
Terraform v0.11.13
+ provider.aws v2.4.0
+ provider.template v2.1.0
```
 ... anyone following up on this?

**Comment by jbscare** [comment]
We've encountered an issue like this when removing a parameter from our configuration that we'd previously set.

**Comment by jbscare** [comment]
Hm, some more data: I tried removing and importing the parameter group, and it had no effect; but I did this:
```
aws rds reset-db-cluster-parameter-group --db-cluster-parameter-group-name prod-aurora-czen-cluster --parameters ParameterName=server_audit_excl_users,ApplyMethod=immediate
```
And then my `terraform plan` said no changes. Hm.

**Comment by kpocius** [comment]
Thanks for a workaround, @jbscare! In my case it was a single RDS instance, so I used:
```
aws rds reset-db-parameter-group --db-parameter-group-name <NAME> --reset-all-parameters
```

**Comment by domcleal** [comment]
> Believe this may be similar to #593 that occurs when attempting to set a parameter to the default value, except on the cluster parameter group resource.

Looks like it, yeah. The fix for that was in #3182 but was only applied to the non-cluster parameter group resource.

As a workaround I used the `dynamic` block in 0.12 to skip setting a parameter when null - but you could equally compare against the default value by changing the `for_each` line:

```hcl
  dynamic "parameter" {
    # Allow read_only to be `null`, so this param is removed and so defaults to {TrueIfReplica}
    #
    # Works around https://github.com/terraform-providers/terraform-provider-aws/issues/5410
    # where setting a parameter to a default value will continuously try to set it as it isn't
    # recognised as set by the user
    for_each = var.read_only != null ? [true] : []
    content {
      name  = "read_only"
      value = var.read_only
    }
  }
```

If the var is null/default then the dynamic block means the parameter's not set. The provider then seems to correctly remove the parameter if it had been set and is now null.

**Comment by olenm** [comment]
> rds reset-db-cluster-parameter-group --db-cluster-parameter-group-name prod-aurora-czen-cluster --parameters ParameterName=server_audit_excl_users,ApplyMethod=immediate

sadly this did not work for me - at least with parameter-name `log_output` - I'm wondering if #3182's logic isnt copy-able into cluster-parameter-group's logic to fix it up.

**Comment by YakDriver** [comment]
This is an old issue with no comments in a long time. I've found the problem with the OP config, see below. This issue can be resolved with some documentation and a test to show it works.

This is the issue with the op config:

1. The default `apply_method` is `immediate` and since the config doesn't supply `apply_method`, it gets the value of `immediate`.
2. However, AWS does not allow `default_password_lifetime` to be `immediate`. It must be `pending-reboot`. Even if you set it as `immediate`, AWS will respond with `pending-reboot`, which causes the diff. There's nothing the AWS Provider _should_ do to fix this since it is part of AWS's internal rules. In order to fix the problem in the config, add `apply_method = "pending-reboot"`.

```terraform
resource "aws_db_parameter_group" "test" {
  name   = "random-test-parameter"
  family = "mysql5.7"

  parameter {
    apply_method = "pending-reboot" # no changes
    # apply_method = "immediate"    # changes !
    name         = "default_password_lifetime"
    value        = "0"
  }
}
```
