### ISSUE TITLE
Destruction of aws_lb_target_group_attachment should block for deregistration delay

### ISSUE THREAD

**Issue by cpoole** [hashicorp/terraform-provider-aws#5603]
Feature Request:

If you have a terraform file with an `aws_instance` and an `aws_lb_target_group_attachment` and you run a `terraform destroy` the `aws_lb_target_group_attachement` should block for the de-registration delay value of the target group. 

Otherwise the subsequent deletion of the `aws_instance` will take place before connections are drained.

**Comment by chrisrlong** [comment]
Hi I seem to have noticed this. I have changed from elb to alb and set the draintime. If we taint an ec2 instance and rebuild it the new instance is added, and gets healthy. However the tainted instance is then deleted rather than de-registered and then deleted. It would be amazing if this issue could be looked into.

**Comment by chrisrlong** [comment]
Is there any chance this might get looked at? Managed to get a 402 error when our instances were moved from the alb which is undesirable when a draining feature exists in AWS tooling.

**Comment by tomcant** [comment]
I'm also experiencing this issue. It happens when rebuilding EC2 instances and their ALB target group attachments. It seems that AWS doesn't initiate the connection draining period when the request to destroy the attachment is issued by Terraform. As a result, during busy periods we see our customers experiencing a number of Bad Gateway HTTP errors.

We would really appreciate it if this could be looked into as soon as possible. Thanks!

**Comment by chrisrlong** [comment]
@bflad Is there a way to get attention on this bug? I have just confirmed it is still present in terraform 0.12.6 and aws provider 2.23.0

If this is not a terraform thing but an SDK or AWS I can raise a support case with them and see if they can find an issue.

**Comment by chrisrlong** [comment]
I found this other issue: https://github.com/terraform-providers/terraform-provider-aws/issues/971

However changing my element function to [..] syntax but the outcome was the same. The de-registration time was zero.

**Comment by chrisrlong** [comment]
In further investigation I removed the create_before_destroy requirement and terraform reports the attachment destroyed as before (in 0s) but the console shows the attachment draining for significant time before it is removed.

**Comment by chrisrlong** [comment]
Similar issue here it seems:

https://github.com/terraform-providers/terraform-provider-aws/issues/5813

**Comment by fv-ian** [comment]
Any visibility into this?  I am experiencing the same issue.
