### ISSUE TITLE
500 Internal Server errors don't report back meaningfully

### ISSUE THREAD

**Issue by gwvandesteeg** [hashicorp/terraform-provider-aws#7287]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
Provider.aws v1.51.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

The configuration isn't the problem, the issue is the 500 Internal Server error response that comes back from AWS and the error message as part of that response not being returned through to the end user when the error is being raised back in the failure.

To reproduce all you need is a minimal ec2 instance of the right type in the right location and availability zone (ec2, t3.large, ap-southeast-2b)

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/gwvandesteeg/fe9547f8326598a90c439b3d12cf7ba3

### Panic Output

No panic

### Expected Behavior

A reason displayed as to WHY the instance failed to create (a verbatim copy from the 500 Internal Server Error message is sufficient).

### Actual Behavior

Timeout creating an instance (timeout while waiting for state to become 'success')

### Steps to Reproduce

Difficult to reproduce if you don't know the resource limits available.

1. `terraform apply`

### Important Factoids

Running in ap-southeast-2, in particular creating ec2 instances of type t3.large in ap-southeast-2b

### References

* #0000

**Comment by bflad** [comment]
Hi @gwvandesteeg 👋 Thanks for reporting this and sorry for the strange behavior here.

Since the EC2 API is returning a 500 HTTP status, the AWS Go SDK is automatically retrying requests before reporting back to the Terraform resource code. The resource code creating EC2 instances is wrapped in time-limited logic that will uncleanly abort underlying calls, which generally is used to return unrecoverable operator errors much quicker while retrying for common eventual consistency issues. These combined prevents the resource from ever seeing the actual error message from the SDK. Here is the code for reference:

https://github.com/terraform-providers/terraform-provider-aws/blob/78c6ea396678815c002cf8a9b37b7ea9ba031918/aws/resource_aws_instance.go#L595-L619

One of the fixes/workarounds to this issue that we have applied in other similar cases is checking the error returned from `resource.Retry()` with `isResourceTimeoutError(err)` and attempting one last repeat of the problematic SDK call outside the time-limiting code. This relies on the SDK's `MaxRetries` logic, configurable via `max_retries` in the Terraform AWS provider configuration, instead of time boxing the request and always will return the error after exhausting the configured retries.

Other alternatives here would be:
* Configuring the SDK to not retry on this specific error and return it in the `resource.Retry()` as a `resource.RetryableError(err)` ourselves. In this case the Terraform resource would be able to see and return the error, leaving it with its 30 seconds of retries before timing out.
* Potentially using `RunInstancesWithContext()` and our own context configured with `context.WithTimeout(context.Background(), 30*time.Second)` although I've never personally verified if this would work as expected in situations like these.

The real complication here is that since the error is transient and outside our control, it won't really be possible to test it in an automated fashion to verify the behavior.

**Comment by gwvandesteeg** [comment]
Well that is a bit of a design problem since HTTP 5xx (and a lot of the
4xx) errors should never be retried due to them being fatal errors at
either the server end (for 5xx) or badly formed requests (for 4xx errors)
unless they contain an appropriate Retry-After response header.
Secondly the AWS API errors actually being returned of the Server Error
category are also generally fatal non-retry-able errors.
Use the below for reference:

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#CommonErrors

And look at the list of Server Errors you'll hopefully understand why these
are fatal errors which should not be retried.
It is generally better to fail fast and fail early with meaningful
information than it is to repeatedly retry requests you know are going to
repeatedly fail.

So from what I'm seeing here is that the code using the SDK doesn't do
enough of an in-depth analysis of the received error responses and as such
doesn't handle them correctly.

The more correct approach is easiest to describe in some psuedo-code

if response is an error {
  if the error is in the category of fatal errors {
    if the response has a Retry-After and the retry-after value is <= the
timeout/retry window {
       retry request
    }
    else {
       fail immediately
    }
  }
  else {
    // non fatal error, so retry
     retry
  }
}

And yes, the error in this scenario is as you say "transient" and the only
way to test it would be to mock the AWS API endpoint and respond with an
appropriate error response instead to test the code execution path or to
write the error handling code in a manner which allows it to be unittested
with various input response objects.
