### ISSUE TITLE
Support tags in aws_service_discovery_private_dns_namespace

### ISSUE THREAD

**Issue by barnharts4** [hashicorp/terraform-provider-aws#7840]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_service_discovery_private_dns_namespace` does not support adding tags.  However, it creates a Route53 hosted zone, which costs money monthly.  Since we use tags to track and allocate costs, we have no way to have this resource's hosted zone reflected in our cost reporting by tag.

Please add support for adding a `tags` collection to this resource which will propagate to all underlying AWS resources that support tags.

### New or Affected Resource(s)

* aws_service_discovery_private_dns_namespace

### Potential Terraform Configuration

```hcl
  resource "aws_service_discovery_private_dns_namespace" "mytest" {
    name = "mytestzone.lcl"
    vpc  = "${var.vpc_id}"
  }
```

**Comment by bflad** [comment]
Hi @barnharts4 👋 It does not appear that Cloud Map currently supports this functionality in its [API](https://docs.aws.amazon.com/cloud-map/latest/api/API_CreatePrivateDnsNamespace.html), which means support within the Terraform AWS Provider is not likely to be implemented at the current time due to its potential maintenance burden. I would suggest reaching out to AWS through your Support or TAM channels to request this functionality and we will be happy to include it if/when its natively supported by the API.

**Comment by ewbankkit** [comment]
Relates #13696.

**Comment by ewbankkit** [comment]
[`tags`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_private_dns_namespace#tags) are now supported on the `aws_service_discovery_private_dns_namespace` resource.
