### ISSUE TITLE
Route53 Resolver Endpoint IP addresses not being marked for change

### ISSUE THREAD

**Issue by mikecook** [hashicorp/terraform-provider-aws#7950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_route53_resolver_endpoint

### Expected Behavior

Case1: When changing an existing aws_route53_resolver_endpoint.ipaddress.[\*].ip from undefined (auto generated) to explicitly defined, the aws_route53_resolver_endpoint.ipaddress.[\*].ip should be changed to the new explicit IP.

Case2: When adding an additional ip_address block (that has a subnet_id identical to an existing ip_address block) to an existing endpoint, that new IP should be provisioned.

### Actual Behavior

Case1: Existing aws_route53_resolver_endpoint.ipaddress.[\*].ip does not get marked for change or changed from the autogenerated IP to the explicitly defined IP.

Case2: aws_route53_resolver_endpoint.ip_address.# is not updated, no additional IP is provisioned to the endpoint. (Case2 isn't as important to me, I ran across it trying to cause an update.)

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/6525
* https://github.com/terraform-providers/terraform-provider-aws/pull/6574

### Reasoning

To migrate with minimal impact from EC2 forwarders to route53_resolver forwarders I need to be able to replace them 1 server (IP) at a time. 
This means (simplified):
- destroy EC2 dns2, set r53r inbound endpoint config to own that dns2 IP, apply r53r
- destroy EC2 dns1 (queries will failover to secondary IP now in r53r), set r53r inbound endpoint config to own dns1 IP, apply r53r

**Comment by mikecook** [comment]
@ewbankkit Any thoughts?

**Comment by ewbankkit** [comment]
@mikecook This is because of the implementation of `route53ResolverEndpointHashIpAddress` https://github.com/terraform-providers/terraform-provider-aws/blob/cfa2d40139fbb73aa8e1fa27093d8057975095b3/aws/resource_aws_route53_resolver_endpoint.go#L329-L334

The `ip_address.ip` attribute is `Optional` and `Computed` which means it can't reliably used in the set's hash function. There was a discussion on this in the PR - e.g. https://github.com/terraform-providers/terraform-provider-aws/pull/6574#issuecomment-441403425 and subsequent.
I agree that this is not ideal and welcome suggestions on how to improve this.

**Comment by grimm26** [comment]
not directly related to the bug, but why do you care what the IP is? Create the endpoints, cut over whatever from using your EC2 forwarder to using the Route53 resolver endpoint IPs.  That way your EC2 is still up as a fallback if something doesn't go well.

**Comment by mikecook** [comment]
@grimm26 I cannot guarantee that instance OSs will obey DHCP resolver changes from existing IPs, and I cannot realistically enforce a reboot. I'm switching to r53r specifically to stop supporting fwder instance sets. Replacement is really the only option if I'm going to use r53r inbound endpoints at all.

**Comment by grimm26** [comment]
Inbound endpoints are not for your ec2 instances, they are for external clients to query route53. Your ec2 instances can just use the Amazon provider resolver option in dhcp. I switched to r53r to dump my dnsmasq nodes, so I feel your pain. The way you are proposing this, you will incur an outage of at least a short period between killing the ec2 fwrdr node and bringing up the r53r endpoint on that ip.

**Comment by mikecook** [comment]
@grimm26 Inbound endpoints are for anything you need to get into r53r that can't/doesn't use +.2 VPC default resolution or 169.254.169.253.

My ec2 instances are already using instance based fwders at specific IPs. Regardless of whether I switch DHCP opts to point at VPC default resolvers, I still need inbound endpoints to replace the existing fwders for instances that may not pick up the DHCP resolver change until reboot or replacement. I can then use flow logs to hunt down which instances didn't pick up the DHCP change at my leisure while not having to support instance based fwders.

As for the outage, I have multiple fwders per VPC. Yes, resolution failover will add a delay when, on the primary fwder, I release the IP and add the IP to an existing inbound endpoint, but if I have other fwders/inbound endpoint IPs up it will only cause a delay, and not a very long delay as adding an IP to an existing endpoint is quicker than creating an endpoint. If I have to replace the fwders all at once with an endpoint, then (for any instances that didn't pick up the DHCP resolver change to default VPC) I will take a complete DNS outage that will be the length of time for all of my existing fwders to release the addresses, plus the time it takes to create an inbound endpoint from scratch.

So, if I can effectively change endpoint addresses, I can have an inbound endpoint already up, change out the IPs one at a time, and take no real outage.

**Comment by ewbankkit** [comment]
@mikecook Your scenario is 100% valid but the current implementation is limited by the nature of the `ip` attribute (being _Optional_/_Computed_). I'm really interested in potential solutions to this.

**Comment by malginin** [comment]
I've just stumbled on [Case 2] above as a valid and desired design (even though it's not recommended by AWS, I'm trying to replicate a legacy on-prem network layout so that's what I want it to be). AWS explicitly allows subnet reuse and just on the most basic level if I can do something in AWS console I want Terraform to be able to do the same.

Maybe compute the hash like this:
if (ip is explicitly defined)
  hash = f (subnet id + ip)
else
  hash = f (subnet id)
?

**Comment by kbusekist** [comment]
While that could work, I don't want to be forced to provide IP addresses if I want to build 2 endpoint IPs per subnet.

**Comment by BrianMusson** [comment]
hey all, i created a zip map as local variable:
> local.myzip
{
  "10.75.113.223" = "subnet-hahahaha565"
  "10.75.113.247" = "subnet-hahahaha565"
  "10.75.117.238" = "subnet-hahahaha208"
  "10.75.117.46" = "subnet-hahahaha208"
  "10.75.121.200" = "subnet-hahahaha420f"
  "10.75.121.213" = "subnet-hahahaha420f"
}
when i use it in a resource block, plan and apply do not require any changes.
resource "aws_route53_resolver_endpoint" "inbound" {
  name      = var.vpc_name
  direction = "INBOUND"
  security_group_ids = [
    aws_security_group.route53-resolver.id
  ]
  dynamic "ip_address" {
    for_each = local.myzip
    content {
      ip        = ip_address.key
      subnet_id = ip_address.value
    }
  }
}
here is another strange data point, when i do a destroy of the resource, then apply, its only creating one ip from each subnet id - so three ips instead of six:
Terraform will perform the following actions:
  # aws_route53_resolver_endpoint.inbound will be created
  + resource "aws_route53_resolver_endpoint" "inbound" {
      + arn                = (known after apply)
      + direction          = "INBOUND"
      + host_vpc_id        = (known after apply)
      + id                 = (known after apply)
      + name               = "byname"
      + security_group_ids = [
          + "sg-<>",
        ]
      + ip_address {
          + ip        = "10.75.113.247"
          + ip_id     = (known after apply)
          + subnet_id = "subnet-hahahaha565"
        }
      + ip_address {
          + ip        = "10.75.117.46"
          + ip_id     = (known after apply)
          + subnet_id = "subnet-hahahaha208"
        }
      + ip_address {
          + ip        = "10.75.121.213"
          + ip_id     = (known after apply)
          + subnet_id = "subnet-hahahaha420f"
        }
    }
Plan: 1 to add, 0 to change, 0 to destroy.
