### ISSUE TITLE
Kinesis Firehose Delivery Streams, S3 Configuration doesn't support error_output_prefix

### ISSUE THREAD

**Issue by dkuntz2** [hashicorp/terraform-provider-aws#7997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.11.11`

### Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

```hcl
 resource "aws_kinesis_firehose_delivery_stream" "firehose-test" {
   name        = "test-firehose"
   destination = "s3"

   s3_configuration {
     role_arn            = "${aws_iam_role.firehose-test.arn}"
     bucket_arn          = "${aws_s3_bucket.test.arn}"
     prefix              = "test/year=!{timestamp:yyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/"
     error_output_prefix = "errors/test/!{firehose:error-output-type}/!{timestamp:yyyy/MM/dd}/"
     buffer_size         = 100
     buffer_interval     = 60
     compression_format  = "GZIP"
  }
}
```

### Expected Behavior

Terraform should set the firehose's `S3Destination.ErrorOutputPrefix` to the value of `s3_configuration.error_output_prefix`

### Actual Behavior

```
Error: aws_kinesis_firehose_delivery_stream.firehose-test: s3_configuration.0: invalid or unknown key: error_output_prefix
```

and without `error_output_prefix`

```
* aws_kinesis_firehose_delivery_stream.firehose-test: Error Updating Kinesis Firehose Delivery Stream: "test-firehose"
InvalidArgumentException: Ths supplied prefix(es) do not satisfy the following constraint: ErrorOutputPrefix cannot be null or empty when Prefix contains expressions
        status code: 400, request id: <aws request id>
```

### Steps to Reproduce

1. `terraform apply`

----

or, manually edit the firehose to use an error output prefix and watch things break.

----

Or, attempt to use an `extended_s3` destination and `_configuration`, and have a permadiff (because none of the data_format_configuration fields are set, and attempting to set them to disabled errors out because certain fields are required).

### Important Factoids

I think this is as easy to fix as just moving `error_output_prefix` from the `extended_s3_configuraion` block to the `s3_configuration` block, and move it into the `createS3Config` function.

I'm willing to do the work, I just would like some input on if those changes would be accepted.

### References

* S3 Destination Configuration api docs: https://docs.aws.amazon.com/firehose/latest/APIReference/API_S3DestinationConfiguration.html (includes ErrorOutputPrefix)

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/7953

**Comment by ryota548** [comment]
me too

**Comment by jmak123** [comment]
same here, this feature is useful because it allows better integration with Athena/Redshift services

**Comment by vanducng** [comment]
Hi there, is there any update on this PR?

**Comment by gmaghera** [comment]
The docs say it is implemented. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#error_output_prefix

**Comment by dkuntz2** [comment]
@gmaghera  it doesn’t say that, it says what I wrote in the original report, that the `extended_s3_configuration` has an `error_output_prefix`, while the bare `s3_configuration` does not

**Comment by gmaghera** [comment]
Fair enough, and I see how nuanced this issue is.

It seems counterintuitive, but if you are using an S3 destination, as in your original report, you should be using [extended_s3_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#extended_s3_configuration). For destinations other than S3 is when [s3_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#s3_configuration) is called for.

"s3_configuration - (Optional) Required for non-S3 destinations. For S3 destination, use extended_s3_configuration instead. Configuration options for the s3 destination (or the intermediate bucket if the destination is redshift). More details are given below."

Then to make things even more confusing, the same page contradicts itself, using `s3_configuration` for an S3 destination [in sample code](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#s3-destination)... 🤯  There are other, more useful examples there as well, showing the role of `s3_configuration` with non-S3 destinations.

To me it seems like this is a documentation issue. The way I read it is that, if you are using an S3 destination if you want full access to all the configs use the extended on.

**Comment by dkuntz2** [comment]
Please read the issue description again, I cannot just use the `extended_s3_configuration`, or I could not, because an `extended_s3_destination` without a transformation on it resulted in a permadiff when running a plan. That may have been fixed, I haven't been able to check though.

The other argument I have against this being a documentation issue is that the AWS API supports what I'm asking for, and it is a feature they added to the `S3Configuration` in the API (despite it being labeled as deprecated). This is a feature request because the provider does not currently match the AWS API in question, and I would like to see the provider updated to match it.

Additionally, as mentioned in the initial report, I am willing to do the work needed to make it match, I just wanted some confirmation that such a pull request would be accepted. There is also a pull request that's been sitting open for a year and a half at this point which I believe would fix this issue entirely, but there has not been any movement on it since April. (https://github.com/hashicorp/terraform-provider-aws/pull/11229)
