### ISSUE TITLE
Inconsistent behaviour of security group in shared vpc

### ISSUE THREAD

**Issue by rverma-nikiai** [hashicorp/terraform-provider-aws#8132]
### Terraform Version
0.11.13

### Affected Resource(s)

*ec2
*rds
*elasticserach
*redis

### Description
In ec2 and redis the security groups are referred to as account/sg-sss, while in rds and elasticsearch they are referred directly as sg-sss.

**Comment by nywilken** [comment]
Hi @rverma-nikiai thank you for opening up this issue and for your help in ensuring consistent behavior within the provider. 

In order for us to best understand which resources, and appropriately speak to any inconsistencies please provide sample configurations for each of the resources in question along with details around its current behavior and what the expected behavior should be. 

Thanks!

**Comment by rverma-nikiai** [comment]
@nywilken I found this inconsistent when using assigning a security group to the elastisearch resource. 

-/+ module.elasticsearch.aws_security_group_rule.ingress_security_groups[0] (new resource required)
      id:                       "sgrule-556410922" => <computed> (forces new resource)
      description:              "Allow inbound traffic from Security Groups" => "Allow inbound traffic from Security Groups"
      from_port:                "0" => "0"
      protocol:                 "tcp" => "tcp"
      security_group_id:        "sg-0038db38ac2c7ff40" => "sg-0038db38ac2c7ff40"
      self:                     "false" => "false"
      source_security_group_id: "sg-065f6bd2da854329c" => "639127283868/sg-065f6bd2da854329c" (forces new resource)
      to_port:                  "65535" => "65535"
      type:                     "ingress" => "ingress"
