### ISSUE TITLE
New resource for AWS Organization SCPs

### ISSUE THREAD

**Issue by gek0** [hashicorp/terraform-provider-aws#8901]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_organizations_policy_detachment

For adding an option of detaching propagated SCPs on OUs or accounts under Root tree
example: removing/detaching the default _FullAWSAccess_ policy

or maybe a more suitable option of defining a list polices on the OU or account itself

* aws_organizations_account_policies
* aws_organizations_organizational_unit_policies

### Potential Terraform Configuration

option 1:
```hcl
resource "aws_organizations_policy_detachment" "<resource>" {
  policy_id = "${aws_organizations_policy.<resource>.id}"
  target_id = "${aws_organizations_organizational_unit.<resource>.id}"
}
```
option 2:
```hcl
resource "aws_organizations_account_policies" "<resource>" {
  policies = []
  target_id = "${aws_organizations_account.<resource>.id}"
}

resource "aws_organizations_organizational_unit_policies" "<resource>" {
  policies = []
  target_id = "${aws_organizations_organizational_unit.<resource>.id}"
}
```

**Comment by bflad** [comment]
Hi @gek0 👋 Thank you for submitting this feature request.

The relevant [AWS Organizations API actions](https://docs.aws.amazon.com/organizations/latest/APIReference/API_Operations.html) appear to be:

* [`AttachPolicy`](https://docs.aws.amazon.com/organizations/latest/APIReference/API_AttachPolicy.html)
* [`DetachPolicy`](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DetachPolicy.html)

In general, Terraform resources are designed to handle the creation/attachment of infrastructure, rather than the inverse of ensuring deletion/detachment of infrastructure. In previous cases where handling automatically propagated infrastructure was required, we have typically added either argument(s) to the propagating resource to disable propagation (if the API supports it) or arguments to the propagated resources to disable the propagated items.

For this particular case it seems we might want to handle this the following way:

```hcl
resource "aws_organizations_organization" "example" {
  # ... other configuration ...

  attached_root_policies = ["..."] # Optional, Computed (API defaults this to `["FullAWSAccess"]`
}

resource "aws_organizations_account" "example" {
  # ... other configuration ...

  attached_policies = ["..."] # Optional, Computed (API defaults this to parent policies)
}

resource "aws_organizations_organizational_unit" "example" {
  # ... other configuration ...

  attached_policies = ["..."] # Optional, Computed (API defaults this to parent policies)
}
```

Where each level of resources can opt into overriding the attached policies or otherwise default to the parent attachments. What do you think?

**Comment by gek0** [comment]
Hi @bflad!
You are right, resources you gave as an example make much more sense and are a nice solution to a problem we are trying to solve.
It would be a nice option to define a list of policies at any give level - organization, OU or an account and this looks promising. Also it would make code more readable/writable as it would be under the same resource.
