### ISSUE TITLE
Import DynamoDb Items

### ISSUE THREAD

**Issue by ben-bourdin451** [hashicorp/terraform-provider-aws#8923]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Managing dynamodb items in Terraform is quite useful for small configuration tables. They are visible as code and go through the same auditing & review process as actual changes to infrastructure.

Unfortunately it has been difficult to start using it for existing tables where items cannot be imported. Specifically this would address the scenario that multiple delete & inserts could increase latencies or potentially impact service up times, making importing items a non-trivial task.

### New or Affected Resource(s)

* aws_dynamodb_table_item

### Potential Terraform Import syntax

The syntax can be a bit tricky here since you would have to specify quite a few fields:
* table name
* hashkey name
* hashkey type
* hashkey value
* rangekey name
* rangekey type
* rangekey value

This could look like the following:

```console
$ terraform import aws_dynamodb_table_item test_table/exampleHashKey/S/something/exampleRangeKey/N/1111
```

**Comment by prupe** [comment]
I've been wanting this for a while too, so I made a PR for it. My first foray into golang, but it seems to work. Suggestions welcome. https://github.com/terraform-providers/terraform-provider-aws/pull/9664

**Comment by Luminoth** [comment]
Is there any chance we'll see one of the PRs that resolves this get merged? It seems like they've been sitting a while now.

**Comment by YakDriver** [comment]
Sincere apologies for the wait on this one. Opened in 2019 by @ben-bourdin451, taken up in #9664 by @prupe shortly after, then auto-staled and eventually locked — not the experience we want for a request that has gathered this much community interest over the years.

I've put up #48520, which finally adds import for `aws_dynamodb_table_item`. It supports both the legacy `terraform import` form and the Terraform 1.12+ `import { identity = {...} }` form (the latter is preferable when key values can contain commas, since the legacy form uses comma as a separator). The PR also adds Resource Identity and a new list resource for the same type.

Will close this issue once #48520 merges. Thanks for the patience, and for the 👍s that kept it on the radar.

**Comment by YakDriver** [comment]
@ben-bourdin451 Thank you for raising this in 2019 and, once again, sorry for the delay!
