### ISSUE TITLE
Update aws_rds_cluster_instance resource to automatically detect a cluster's engine and engine_version upon create

### ISSUE THREAD

**Issue by Magicloud** [hashicorp/terraform-provider-aws#9531]
Original Question: Does aws_rds_cluster_instance inherit engine and engine_verison from cluster?

I specified "aurora-postgresql" engine in cluster, then applied. Seems like the instance gets the engine_version, but not the engine, so I got error:

`Error: error creating RDS DB Instance: InvalidParameterCombination: Cannot find version 9.6.9 for aurora`

This can be fixed by just setting the engine of the instance. But it seems weird.

**Comment by nywilken** [comment]
Hi @Magicloud thanks for opening up this issue. While the `engine` argument is optional in the documentation it is actually a required argument at create time. Currently, the provider defaults to `aurora` as the engine if no engine is specified within the configuration. Hence the error above. As for the `engine_version` you are correct in saying the version will be dictated by the cluster if not specified. 

In order to fix your issue you need to set `engine = "aurora-postgresql"`. I am going to add the documentation and thinking label to this issue because I suspect we might want to update the documentation for properly setting the engine argument.

**Comment by Magicloud** [comment]
Thanks for the explanation.

**Comment by nywilken** [comment]
@Magicloud thanks for you patience here. I am going to re-title this issue as "Update `aws_rds_cluster_instance` resource to automatically detect a cluster's `engine` and `engine_version` upon create". This has been a common issue for the resource. 

Until this update is made you must specific a value for `engine`.
