### ISSUE TITLE
aws_route53_resolver_endpoint: 

### ISSUE THREAD

**Issue by michalmedvecky** [hashicorp/terraform-provider-aws#9626]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.5

### Affected Resource(s)

* aws_route53_resolver_endpoint

### Terraform Configuration Files

```hcl
aws_route53_resolver_endpoint" "adp-outbound" {
  name      = "adp-outbound-resolver"
  direction = "OUTBOUND"

  security_group_ids = [ aws_security_group.dns-proxy-sg.id ]

  ip_address {
    subnet_id = var.resolver_subnet_id_1a
    ip = "11.224.73.53"
  }

  ip_address {
    subnet_id = var.resolver_subnet_id_1a
    ip        = "11.224.73.62"
  }
}
```

### Debug Output

Contains too many information I don't want to publish to internet. But it's simple to reproduce.

### Expected Behavior

Outbound resolver created with IP addresses in the same subnet

### Actual Behavior

Error: insufficient items for attribute "ip_address"; must have at least 2

-> If the IP addresses belong to the same subnet, TF refuses to create them, resulting in the above error. Having both IPs in the same subnet is a valid configuration in AWS anyway.

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/hashicorp/terraform/issues/22195

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/7942

**Comment by robison** [comment]
I'd be interested in contributing a fix for this.

**Comment by mdwheele** [comment]
Samesies

**Comment by shermanyin** [comment]
Running into this issue as well (outbound endpoint).  While waiting for a fix, the docs (https://www.terraform.io/docs/providers/aws/r/route53_resolver_endpoint.html) should at least say minimum 2 ip_address blocks with a _different_ subnet is required.  It's not clear how to fix the error message "ip_address: attribute supports 2 item as a minimum, config has 1 declared" because creating another ip_address block with the same subnet did not fix the error.

**Comment by zaphoodb** [comment]
Having this issue as well (outbound endpoint). Having one subnet with two IP addresses but endpoint creation is failing. Using AWS console it works without any issue.

**Comment by drewmullen** [comment]
dynamic blocks also do not work

```
resource "aws_route53_resolver_endpoint" "outbound" {
  name = "outbound-${local.prefix}"
  direction = "OUTBOUND"
  security_group_ids = [ aws_security_group.outbound.id ]
  tags = local.common_tags

  dynamic "ip_address" {
    for_each = var.outbound_subnet_ids
    subnet_id = ip_address.value
  }
}

variable "outbound_subnet_ids" {
  type = map(string)
  default = {
    homelab-private = "subnet-0cefb8e71475f2286"
  }
}
```

**Comment by drewmullen** [comment]
Previously i was getting errors when trying to make 2 outbound endpoints in the same subnet but that seems to have magically gone away (its working now). 

i do think this is a terraform provider bug: the `ip_address` block should accept the same subnet id multiple times

finally, there is a ticket open now to also clarify in the resolver api docs that 2 ENIs are required

**Comment by NK74** [comment]
Hey,
Same behaviour on 14.9 (provider aws v2.70.0)

```
resource "aws_route53_resolver_endpoint" "resource" {
  name      = "xxxx"
  direction = "INBOUND"

  security_group_ids = [
    aws_security_group.xxxx.id,
  ]
  ip_address {
    subnet_id = aws_subnet.xxxx.id
    ip        = "IP1"
  }
  ip_address {
    subnet_id = aws_subnet.xxxx.id
    ip        = "IP2"
  }
```

**Error: error creating Route53 Resolver endpoint: InvalidRequestException: [RSLVR-00400] Resolver endpoint need to have at least 2 IP addresses.**

is there a workaround ? thx

**Comment by rnsc** [comment]
@michalmedvecky @NK74 @drewmullen @ewbankkit @robison @mdwheele @zaphoodb @shermanyin 

Hey folks, I've created a PR that fixes the issue: https://github.com/hashicorp/terraform-provider-aws/pull/25708
I've tested it locally with multiple IPs in the same subnet and it works as expected as per the outputs I've added in the PR.

Let's hope we can add this fix in the next minor version of the provider, I'm currently blocked using Terraform to deploy endpoints with multiple IPs in the same subnet because of this bug.

Cheers!
