### ISSUE TITLE
Update keybase library dependencies

### ISSUE THREAD

**Issue by 007** [hashicorp/terraform-provider-aws#9769]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.5

### Affected Resource(s)

At least:
* aws_iam_user_login_profile
* aws_iam_access_key

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "~> 2.00"
}

resource "aws_iam_user" "user" {
  name = "deleteme"
}

resource "aws_iam_access_key" "user" {
  user    = "${aws_iam_user.user.name}"
  pgp_key = "keybase:007"
}
```

### Debug Output

N/A

### Expected Behavior

Created user, created access key, encrypted access key to `keybase:007`

### Actual Behavior
Created user, created access key, errored:
```
$ terraform apply foo.plan
aws_iam_user.user: Creating...
aws_iam_user.user: Creation complete after 1s [id=deleteme]
aws_iam_access_key.user: Creating...

Error: Error retrieving Public Key for keybase:007: openpgp: unsupported feature: unsupported oid: 2b060104019755010501

  on main.tf line 9, in resource "aws_iam_access_key" "user":
   9: resource "aws_iam_access_key" "user" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The key selected for `keybase:007` is an Ed25519 key, not RSA. The [current version of the keybase module](https://github.com/terraform-providers/terraform-provider-aws/blob/master/go.sum#L337) is from [late 2016](https://github.com/keybase/go-crypto/commit/93f5b35093ba).

### References

* https://github.com/keybase/keybase-issues/issues/1910#issuecomment-471028886

**Comment by rsclarke-vgw** [comment]
This also impacts base64 encoded ed25519 public keys set in the `pgp_key` property for a `aws_iam_access_key` resource. A similar error is given;

```
Error: Error encrypting IAM Access Key Secret: error parsing given PGP key: openpgp: unsupported feature: unsupported oid: 2b060104019755010501
```

**Comment by jsmilani** [comment]
Here is a related ticket that was closed as won't fix as it pertains to just aws_iam_access_key. https://github.com/hashicorp/terraform-provider-aws/issues/15384

The explanation for why is because of a reference to the docs https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#don-39-t-encrypt-state where it states the backend state will no longer support any form of encryption. If that explanation is accurate then this ticket should also be closed, but the problem remains that PGP keys is the only way to get the secret values from aws_iam_user_login_profile and to make matters worse, ed25519/cv25519 seems to be the new default as of gpg 2.3.0 which isn't compatible (reference https://lists.gnupg.org/pipermail/gnupg-announce/2021q2/000458.html). At least aws_iam_access_key has the option to access the unencrypted version but aws_iam_user_login_profile does not.
